EXECUTE('
INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (9502, 0, ''Topaz POS'', NULL, 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (9502, 9510, ''Movimientos Conciliados con Diferencias '', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (9502, 9511, ''Movimientos sin Conciliar '', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (9510, 1, NULL, 0, 0, 1)

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (9511, 1, NULL, 0, 0, 1)
')