EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (950, 7952, NULL, ''TJD_TLF_CONCILIACION'', 0, ''TJD_TLF_CONCILIACION'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79820, '''', 0, ''JTS_OID'', ''JTS_OID'', 18, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''JTS_OID'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79821, '''', 0, ''TOPAZPROCESSDATE'', ''TOPAZPROCESSDA'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''TOPAZPROCESSDATE'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79822, '''', 0, ''FECHAMENSAJE'', ''FECHAMENSAJE'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''FECHAMENSAJE'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79823, '''', 0, ''INCONSISTENCIA'', ''INCONSISTENCIA'', 1000, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''INCONSISTENCIA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79824, '''', 0, ''CORRECCIONAUTOMATICA'', ''CORRECCIONAUTO'', 1, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''CORRECCIONAUTOMATICA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79825, '''', 0, ''CORREGIDO'', ''CORREGIDO'', 1, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''CORREGIDO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79826, '''', 0, ''DESCRIPCIONCORRECCION'', ''DESCRIPCIONCOR'', 1000, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7952, ''DESCRIPCIONCORRECCION'', 0, '''')

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (7952, 1, ''Indice Principal'', 0, 79820, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


')