EXECUTE('
IF OBJECT_ID (''dbo.VBS_DETALLE_CUOTAS_PAGADAS'') IS NOT NULL
	DROP VIEW dbo.VBS_DETALLE_CUOTAS_PAGADAS
')

EXECUTE('
CREATE VIEW dbo.VBS_DETALLE_CUOTAS_PAGADAS
AS

SELECT HP_JTS_OID,
NUMERADOR,
NUMERADOR_HP,
NUMERADOR_HP_SUB,
SALDO_JTS_OID, 
VENCIMIENTOCUOTA,
NCUOTA,
CASE WHEN CAPITAL_ADELANTOS > 0 THEN 0 ELSE CAPITAL END AS CAPITAL,
INTERES, 
SALDO_CAPITAL,
SALDO_INTERES, 
DIASATRASO,
TASAINTERES,
PAGOPARCIAL,
SUM(PP_IVAINTERES) AS PP_IVAINTERES,
SUM(PP_IVAPERCEPCIONINTERES) AS PP_IVAPERCEPCIONINTERES ,
SUM(PP_MORA) AS PP_MORA,
SUM(PP_IVAMORA)AS PP_IVAMORA,
SUM(PP_IVAPERCEPCIONMORA) AS PP_IVAPERCEPCIONMORA ,
SUM(PP_INTCOMPMORA) AS PP_INTCOMPMORA ,
SUM(PP_IVAINTCOMPMORA) AS PP_IVAINTCOMPMORA,
SUM(PP_IVAPERCEPCIONINTCOMPMORA) AS PP_IVAPERCEPCIONINTCOMPMORA,
SUM(PP_GASTOS) AS PP_GASTOS,
(PP_GASTOS_TOT) AS PP_GASTOS_TOT,
SUM(SUBSIDIO) AS SUBSIDIO,
FECHAVALOR,
CODIGO, 
CARGO,
CASE WHEN OPERACION = (SELECT VALOR FROM PARAMETROS_JTS WITH (NOLOCK) WHERE FUNCIONALIDAD=''COBRANZA_AUTOMATICA'' AND PARAMETRO=''OPERACION'') THEN 1
     WHEN PAGOPARCIAL =''Pago'' THEN 1
	 ELSE 0 
END AS ADMITE_PP
 FROM (
SELECT 
	ROW_NUMBER() OVER(PARTITION BY PP.SALDO_JTS_OID,PP.C2300 ORDER BY PP.C2300 ASC) AS NUMERADOR,
	ROW_NUMBER() OVER(PARTITION BY PP.SALDO_JTS_OID, PP.C2300, P.HP_JTS_OID ORDER BY pp.C2300, P.HP_JTS_OID ASC) AS NUMERADOR_HP, 
	ROW_NUMBER() OVER(PARTITION BY PP.SALDO_JTS_OID, PP.C2300, P.HP_JTS_OID, G.CODIGO ORDER BY P.HP_JTS_OID ASC) AS NUMERADOR_HP_SUB,	
	PP.SALDO_JTS_OID,
	PP.C2300 AS NCUOTA,
	-- Si la fecha de vencimiento del plan de pagos es mayor a la del plan de pagos original mostramos esta porque tuvo un evento de
	-- cambio de vencimiento, caso contrario evaluamos mostrar la del orginal sino tuvo eventos o la del plan de pagos actual si
	-- tuvo algun evento de adelanto de cuotas
	CASE WHEN PP.C2302 > PPO.FECHA_FIN THEN PP.C2302 ELSE
	CASE WHEN PPO.FECHA_FIN IS NULL THEN PP.C2302 ELSE PPO.FECHA_FIN END
	END  AS VENCIMIENTOCUOTA,	
	
	
	CASE WHEN PP.TZ_LOCK <> 0 THEN ISNULL(PPO.CAPITAL,0) -- Cuota adelantada
		 WHEN P.HP_JTS_OID IS NOT NULL AND P.FECHAVALOR < PP.C2302 AND (PP.C2309+PP.C2310)>0 THEN ISNULL(P.CAPITALPAGADO+P.CAPITALADELANTADO,0) -- Cancela Parcialmente la cuota
		 WHEN P.HP_JTS_OID IS NOT NULL AND PP.C2302 <= PP.C2302_ORIGINAL AND (PP.C2309+PP.C2310)=0 THEN ISNULL(P.CAPITALPAGADO+P.CAPITALADELANTADO,0) -- Cancela antes del vto algoritmo 14
		 WHEN PP.C2313 < PP.C2302 AND (PP.C2309+PP.C2310)=0 THEN ISNULL(PP.C2304,0) -- Cancela antes del vencimiento algoritmo 0
		 
		 WHEN P.HP_JTS_OID IS NOT NULL AND ISNULL(P.CAPITALPAGADO,0) <> 0 THEN ISNULL(P.CAPITALPAGADO,0)  -- Cuota vencida
		 WHEN P.HP_JTS_OID IS NOT NULL AND ISNULL((P.CAPITALPAGADO+P.CAPITALADELANTADO),0) = 0 THEN 0 -- Cuota sin Capital
		 WHEN P.HP_JTS_OID IS NOT NULL AND ISNULL(P.CAPITALANTES,0) = 0 THEN 0 -- Cuota sin Capital
         ELSE ISNULL(PPO.CAPITAL,0) END AS CAPITAL,
         
	CASE WHEN PP.TZ_LOCK <> 0 THEN ISNULL(PPO.CAPITAL,0) END  AS CAPITAL_ADELANTOS,
	ISNULL(P.INTERESPAGADO,0) AS INTERES,
	BH.TASAINTERES AS TASAINTERES,  	 
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN (I.IVAINTERES+I.IVASUBSIDIO)
		 ELSE 0 -- PP.IVAINTERES 
	END  AS PP_IVAINTERES,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN (I.IVAINTERESPERCEPCION+I.IVASUBSIDIOPERCEPCION)
		 ELSE 0 -- PP.IVAPERCEPCIONINTERES 
	END AS PP_IVAPERCEPCIONINTERES,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN P.HP_JTS_OID IS NOT NULL THEN P.MORAPAGADA
		 ELSE 0 -- PP.C2311
	END AS PP_MORA,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN I.IVAMORA
		 ELSE 0 -- PP.IVAMORA 
	END AS PP_IVAMORA,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN I.IVAMORAPERCEPCION
		 ELSE 0 -- PP.IVAPERCEPCIONMORA 
    END AS PP_IVAPERCEPCIONMORA,
    CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN P.HP_JTS_OID IS NOT NULL THEN P.INTERES_COMP_MORA
		 ELSE 0 -- PP.ICMORA_DEV
	END AS PP_INTCOMPMORA,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN I.IVAICMORA
		 ELSE 0 -- PP.IVAINTCOMPMORA 
	END AS PP_IVAINTCOMPMORA,
	CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN I.HP_JTS_OID IS NOT NULL THEN I.IVAICMORAPERCEPCION 
		 ELSE 0 -- PP.IVAPERCEPCIONINTCOMPMORA 
	END AS PP_IVAPERCEPCIONINTCOMPMORA,		
    P.HP_JTS_OID,
    P.CUOTA AS CUOTA,
    PP.DIAS_ATRASO_CANCELACION  AS DIASATRASO,
    PP.C2309 AS SALDO_CAPITAL,
	PP.C2310 AS SALDO_INTERES, 
    CASE WHEN PP.TZ_LOCK<>0 THEN PP.C2313 ELSE P.FECHAVALOR END AS FECHAVALOR ,  
    CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN P.HP_JTS_OID IS NOT NULL 
		 	THEN isnull((SELECT sum(TOTAL_PAGADO) FROM BS_CHARGE_DETAIL WITH (NOLOCK) WHERE SALDOS_JTS_OID=PP.SALDO_JTS_OID AND HP_JTS_OID=p.HP_JTS_OID 
		 		  AND CUOTA=p.CUOTA AND CARGO_ID=g.CARGO_ID),0)	 		  
		 ELSE 0
	END AS PP_GASTOS, 
    CASE WHEN PP.TZ_LOCK <> 0 THEN 0 
		 WHEN P.HP_JTS_OID IS NOT NULL 
		 	THEN isnull((SELECT sum(TOTAL_PAGADO) FROM BS_CHARGE_DETAIL WITH (NOLOCK) WHERE SALDOS_JTS_OID=PP.SALDO_JTS_OID AND HP_JTS_OID=p.HP_JTS_OID 
		 		  AND CUOTA=p.CUOTA),0)	 		  
		 ELSE 0
	END AS PP_GASTOS_TOT,		
	CASE WHEN P.NROASIENTOMOV IS NOT NULL AND (ROW_NUMBER() OVER(PARTITION BY PP.SALDO_JTS_OID, P.HP_JTS_OID ORDER BY P.HP_JTS_OID ASC)) = 1
	THEN ISNULL(
	ISNULL(F.IMP_SUBSIDIO,0)+(SELECT SUM(CAPITALREALIZADO) FROM MOVIMIENTOS_CONTABLES WITH (NOLOCK) WHERE FECHAPROCESO=BH.FECHAPROCESOMOV AND ASIENTO=BH.NROASIENTOMOV 
	AND SUCURSAL=BH.SUCURSALMOV AND COD_TRANSACCION=3030 
	AND SUB_ASIENTO IN (SELECT SUB_ASIENTO FROM MOVIMIENTOS_CONTABLES MC1 WITH (NOLOCK)  
					    WHERE MC1.FECHAPROCESO=BH.FECHAPROCESOMOV AND MC1.ASIENTO=BH.NROASIENTOMOV 
						AND MC1.SUCURSAL=BH.SUCURSALMOV
					    AND MC1.SALDO_JTS_OID=S.JTS_OID)
						      ),0) ELSE 0 END AS SUBSIDIO,
	CASE 
 		 WHEN BPC.SALDOS_JTS_OID IS NOT NULL THEN ''Pago con Condonación''
 		 WHEN (PP.C2309+PP.C2310) <> (PP.C2304+PP.C2305) AND (PP.C2309+PP.C2310) >0
			THEN ''Pago Parcial''
		 WHEN PP.TZ_LOCK <> 0 OR PP.C2301 > (SELECT FECHAPROCESO FROM PARAMETROS WITH (nolock))THEN ''Pago Adelantada'' 
		 WHEN (PP.C2309+PP.C2310) = 0 THEN ''Pago''	
		 ELSE '''' 
	END AS PAGOPARCIAL,
	CASE WHEN ISNULL(C.TOTAL_PAGADO,0) = 0 THEN 0 ELSE G.CODIGO END AS CODIGO, 
	CASE WHEN ISNULL(C.TOTAL_PAGADO,0) = 0 THEN '''' ELSE G.DESCRIPCION  END AS CARGO,
	A.OPERACION
FROM PLANPAGOS PP WITH (NOLOCK) 
LEFT JOIN PLANPAGOS_ORIGINAL PPO WITH (NOLOCK)
	ON PPO.SALDO_JTS_OID=PP.SALDO_JTS_OID AND PPO.NUMERO_CUOTA=PP.C2300
INNER JOIN SALDOS S WITH (NOLOCK) 
	ON PP.SALDO_JTS_OID=S.JTS_OID AND S.C1785=5 AND S.TZ_LOCK=0
INNER JOIN PRODUCTOS pr WITH (NOLOCK) ON pr.C6250=s.PRODUCTO
INNER JOIN BS_HISTORIA_PLAZO BH WITH (NOLOCK) ON BH.SALDOS_JTS_OID=s.JTS_OID AND BH.TIPOMOV=''P'' AND BH.TZ_LOCK=0	
INNER JOIN ASIENTOS A ON A.ASIENTO=BH.NROASIENTOMOV AND A.SUCURSAL=BH.SUCURSALMOV AND A.FECHAPROCESO=BH.FECHAPROCESOMOV AND A.ESTADO=77
INNER JOIN (SELECT SALDOS_JTS_OID, HP_JTS_OID, CUOTA,max(FECHAVALOR) AS  FECHAVALOR, max(NROASIENTOMOV) AS NROASIENTOMOV , SUM(CAPITALPAGADO) AS CAPITALPAGADO , SUM(INTERESPAGADO) AS INTERESPAGADO ,
	    SUM(CAPITALADELANTADO) AS CAPITALADELANTADO , SUM(CAPITAL_ANTES) AS CAPITALANTES, SUM(MORAPAGADA) AS MORAPAGADA , SUM(INTERES_COMP_MORA) AS INTERES_COMP_MORA,
	    SUM(SALDO_CAPITAL_ANTES) AS SALDO_CAPITAL_ANTES
	    FROM BS_PAYS_DETAIL d1 WITH (NOLOCK)
	    WHERE d1.TZ_LOCK=0 AND (CAPITALPAGADO + CAPITALADELANTADO + INTERESPAGADO +  MORAPAGADA + INTERES_COMP_MORA)<>0
	    GROUP BY SALDOS_JTS_OID,HP_JTS_OID,CUOTA
		UNION 
		SELECT SALDOS_JTS_OID, max(HP_JTS_OID) AS HP_JTS_OID, CUOTA,max(FECHAVALOR) AS  FECHAVALOR, max(NROASIENTOMOV) AS NROASIENTOMOV , SUM(CAPITALPAGADO) AS CAPITALPAGADO , SUM(INTERESPAGADO) AS INTERESPAGADO ,
			    SUM(CAPITALADELANTADO) AS CAPITALADELANTADO , SUM(CAPITAL_ANTES) AS CAPITALANTES , SUM(MORAPAGADA) AS MORAPAGADA , SUM(INTERES_COMP_MORA) AS INTERES_COMP_MORA,
			    SUM(SALDO_CAPITAL_ANTES) AS SALDO_CAPITAL_ANTES
			    FROM BS_PAYS_DETAIL d2 WITH (NOLOCK)
			    INNER JOIN PLANPAGOS p ON p.SALDO_JTS_OID=SALDOS_JTS_OID
			    AND p.C2300=CUOTA AND p.TZ_LOCK<>0
			    WHERE d2.TZ_LOCK=0 AND (CAPITALPAGADO + CAPITALADELANTADO + INTERESPAGADO +  MORAPAGADA + INTERES_COMP_MORA)=0
			   GROUP BY SALDOS_JTS_OID,CUOTA) P 
ON P.SALDOS_JTS_OID=S.JTS_OID
 AND P.HP_JTS_OID = BH.JTS_OID
 AND P.CUOTA=PP.C2300 
	-- Se coloca CASE para contemplar cuotas adelantadas en primera condicion
	AND CASE WHEN PP.TZ_LOCK <> 0 THEN 1
	    		 ELSE (P.CAPITALPAGADO + P.CAPITALADELANTADO + P.INTERESPAGADO +  P.MORAPAGADA + P.INTERES_COMP_MORA ) 
	    	END <> 0 
	-- AND (TIPOAJUSTEHP<>''C'' OR TIPOAJUSTEHP IS NULL)
LEFT JOIN (	
SELECT DISTINCT gs.SALDOS_JTS_OID,gs.NUMERO_CUOTA, gs.CARGO_ID, gs.IMPUESTO_ID, gs.IMPORTE_GASTO, gs.SALDO_GASTO,
				CASE WHEN t.CODIGO IS NULL THEN ci.ID_CARGO ELSE t.CODIGO END AS CODIGO,
				CASE WHEN t.DESCRIPCION IS NULL THEN ci.DESCRIPCION ELSE t.DESCRIPCION END AS DESCRIPCION
				FROM GASTOS_POR_CUOTA gs WITH (nolock)
					INNER JOIN CI_CARGOS ci WITH (NOLOCK)  ON ci.ID_CARGO=gs.CARGO_ID AND ci.tz_lock=0
					LEFT JOIN 
						(SELECT ttl.ID_CARGO,ttl.CODIGO, ttl.DESCRIPCION
						FROM CRE_GASTOS_LEASING gl WITH (nolock)
						INNER JOIN CRE_TIPO_TRAMITE_LEASING ttl WITH (nolock) ON ttl.CODIGO=gl.CODIGO_TRAMITE  
						INNER JOIN opciones  op1 WITH (nolock) ON op1.NUMERODECAMPO=43371 AND op1.OPCIONINTERNA= ttl.TIPO 
						INNER JOIN opciones  op2 WITH (nolock) ON op2.NUMERODECAMPO=43374 AND op2.OPCIONINTERNA=ttl.CATEGORIA
						WHERE gl.TZ_LOCK=0 AND ttl.TZ_LOCK=0) t 
					ON t.ID_CARGO=gs.CARGO_ID 
				WHERE gs.TZ_LOCK=0
				GROUP BY gs.SALDOS_JTS_OID,gs.NUMERO_CUOTA, gs.CARGO_ID, gs.IMPUESTO_ID, gs.IMPORTE_GASTO, gs.SALDO_GASTO,
				ci.DESCRIPCION,ci.ID_CARGO, t.CODIGO, t.DESCRIPCION ) G
	ON g.SALDOS_JTS_OID=s.JTS_OID AND g.NUMERO_CUOTA=PP.C2300
LEFT JOIN BS_CHARGE_DETAIL C WITH (NOLOCK) 
	ON  P.SALDOS_JTS_OID = C.SALDOS_JTS_OID 
	AND P.HP_JTS_OID = C.HP_JTS_OID 
	AND P.CUOTA = C.CUOTA 
	AND C.CARGO_ID=G.CARGO_ID
	AND C.TOTAL_PAGADO<>0 
	AND C.TZ_LOCK=0	 
LEFT JOIN BS_PAYS_DETAIL_IVA I WITH (NOLOCK) 	
	ON P.SALDOS_JTS_OID = I.SALDOS_JTS_OID 
	AND P.HP_JTS_OID = I.HP_JTS_OID 
	AND P.CUOTA = I.CUOTA
	AND I.TZ_LOCK=0
LEFT JOIN (SELECT SALDOS_JTS_OID,HP_JTS_OID, sum(IVASUBSIDIO+IVASUBSIDIOPERCEPCION) AS IMP_SUBSIDIO
			FROM BS_PAYS_DETAIL_IVA WITH (NOLOCK) 
			GROUP BY SALDOS_JTS_OID, HP_JTS_OID) F
	ON F.SALDOS_JTS_OID = BH.SALDOS_JTS_OID
	AND F.HP_JTS_OID = BH.JTS_OID 
LEFT JOIN BS_PAYS_DETAIL_CONDONA BPC WITH (NOLOCK) 
	ON BPC.SALDOS_JTS_OID=s.JTS_OID AND BPC.HP_JTS_OID=BH.JTS_OID AND BPC.CUOTA=p.CUOTA
	AND BPC.TZ_LOCK=0
--WHERE (((PP.C2309+PP.C2310)=0) OR (PP.TZ_LOCK<>0))

) t
WHERE (CAPITAL+INTERES+PP_IVAINTERES+PP_IVAPERCEPCIONINTERES+PP_MORA+PP_IVAMORA+PP_IVAPERCEPCIONMORA+PP_INTCOMPMORA+PP_IVAINTCOMPMORA+
PP_IVAPERCEPCIONINTCOMPMORA+PP_GASTOS) > 0
GROUP BY 
NUMERADOR,
NUMERADOR_HP,
NUMERADOR_HP_SUB,
PP_GASTOS_TOT,
SALDO_JTS_OID, VENCIMIENTOCUOTA,NCUOTA,CAPITAL,CAPITAL_ADELANTOS,INTERES, SALDO_CAPITAL,
SALDO_INTERES,DIASATRASO,FECHAVALOR,TASAINTERES,PAGOPARCIAL,CODIGO, CARGO, OPERACION, HP_JTS_OID
')

