EXECUTE('
IF OBJECT_ID (''dbo.VW_DPF_FACTURA_CARGO'') IS NOT NULL
	DROP VIEW dbo.VW_DPF_FACTURA_CARGO
')
EXECUTE('
CREATE   VIEW [dbo].[VW_DPF_FACTURA_CARGO](	JTS_OID,
													MONTO,
													CARGO)
AS
SELECT	
	F.JTS_SALDO_CLIENTE AS JTS_OID,
	F.TOTAL_EMISION_FACTURA AS MONTO,
	L.ID_CARGO AS CARGO
FROM CI_FACTURA F WITH (NOLOCK)
INNER JOIN CI_FACTURA_LINEA L WITH (NOLOCK) ON 
	L.ASIENTO = F.ASIENTO
	AND L.FECHA_PROCESO_ASIENTO = F.FECHA_PROCESO_ASIENTO
	AND F.SUCURSAL_ASIENTO = L.SUCURSAL_ASIENTO
    AND L.TR_REAL= f.TR_REAL
INNER JOIN ASIENTOS AS A WITH (NOLOCK) ON
	A.ASIENTO = F.ASIENTO
	AND A.FECHAPROCESO = F.FECHA_PROCESO_ASIENTO
	AND A.SUCURSAL = F.SUCURSAL_ASIENTO
	AND A.ESTADO = 77

WHERE
	L.ID_CARGO IS NOT NULL
')