EXECUTE('
IF OBJECT_ID (''VW_SaldosAjustados'') IS NOT NULL
	DROP VIEW VW_SaldosAjustados
')
EXECUTE('
CREATE VIEW VW_SaldosAjustados
AS
SELECT
    CASE WHEN G.MONEDA IN (999,988) THEN 
    		SAL.C1620 
    	ELSE G.FECHA 
    END AS FECHA_COT,
    G.FECHA,
    G.SUCURSAL,
    G.MONEDA,
    G.SALDO_AJUSTADO,
    G.PROMEDIO_DIARIO,
    G.RUBROCONTABLE,
    1 AS CAT_BCRA,
    R.NUM1 AS MONEDA_NUM1
FROM 
    GRL_SALDOS_DIARIOS G WITH (NOLOCK)
INNER JOIN SALDOS SAL WITH (NOLOCK) ON 
	SAL.JTS_OID = G.SALDOS_JTS_OID AND
	SAL.TZ_LOCK=0
INNER JOIN SUCURSALES S WITH (NOLOCK)
    ON G.SUCURSAL = S.SUCURSAL AND 
    S.TZ_LOCK = 0
INNER JOIN RRI_PARAMETROS_INF R WITH (NOLOCK)
    ON G.MONEDA = R.ID1 AND 
    R.TZ_LOCK =0
WHERE 
    R.CODIGO = 1
    AND G.TZ_LOCK = 0
    AND SAL.C1604!=0
')
