EXECUTE('
	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35887

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35888

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35889

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35887, '' '', 0, ''ID Cheque'', ''ID Cheque'', 15, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 165, ''ID_CHEQUE'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35888, '' '', 0, ''CMC7'', ''CMC7'', 29, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 165, ''CMC7'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35889, '' '', 0, ''Estado Caducidad'', ''Estado Caducidad'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 165, ''ESTADO_CADUCIDAD'', 0, NULL)

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 35889 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''PP''

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 35889 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''PR''

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 35889 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''PI''

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 35889 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''I''
	
	INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
	VALUES (35889, ''E'', ''Pendiente Informar'', ''PI'', ''PI'')

	INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
	VALUES (35889, ''E'', ''Informado'', ''I'', ''I'')
	
	DELETE FROM dbo.DESCRIPTORES
	WHERE TITULO = 35 AND IDENTIFICACION = 3553

	INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
	VALUES (35, 3553, NULL, ''Cheques Identificador'', 0, ''VW_CHE_CHEQUES_PROCESO'', ''D'', 0, 0, ''Top/Clientes'', NULL, ''N'')

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35890

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35891

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35892

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35893

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35894

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35895

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35896

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35897

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35898

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35899

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35900

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35890, NULL, 0, ''Identificador'', ''Identificador'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Identificador'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35891, NULL, 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Sucursal'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35892, NULL, 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Moneda'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35893, NULL, 0, ''Cuenta'', ''Cuenta'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Cuenta'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35894, NULL, 0, ''Producto'', ''Producto'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Producto'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35895, NULL, 0, ''Operacion'', ''Operacion'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Operacion'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35896, NULL, 0, ''Ordinal'', ''Ordinal'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Ordinal'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35897, NULL, 0, ''Número Cheque'', ''Número Cheque'', 9, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''NUMEROCHEQUE'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35898, NULL, 0, ''Serie'', ''Serie'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Serie'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35899, NULL, 0, ''Estado'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''Estado'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35900, NULL, 0, ''Fecha Vencimiento'', ''Fecha Vencimiento'', 8, ''F'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3553, ''FECHA_VENCIMIENTO'', 0, NULL)

	DELETE FROM dbo.INDICES
	WHERE NUMERODEARCHIVO = 3553 AND NUMERODEINDICE = 1

	INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
	VALUES (3553, 1, ''Indice Cheques Identificador'', 0, 35890, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

	DELETE FROM dbo.OPERACIONES
	WHERE TITULO = 3552 AND IDENTIFICACION = 3461

	INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
	VALUES (3552, 3461, ''PA actualiza estado cheques (Desatendida)'', ''PA actualiza estado cheques (Desatendida)'', ''3461'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')

