execute('
INSERT INTO dbo.ITF_MASTER (TZ_LOCK, ID, DESCRIPCION, OBJ_KETTLE, P0_MODO, P0_TIPO, P0_CAPTION, P0_CONSTANTE, P1_MODO, P1_TIPO, P1_CAPTION, P1_CONSTANTE, P2_MODO, P2_TIPO, P2_CAPTION, P2_CONSTANTE, P3_MODO, P3_TIPO, P3_CAPTION, P3_CONSTANTE, P4_MODO, P4_TIPO, P4_CAPTION, P4_CONSTANTE, P5_MODO, P5_TIPO, P5_CAPTION, P5_CONSTANTE, P6_MODO, P6_TIPO, P6_CAPTION, P6_CONSTANTE, P7_MODO, P7_TIPO, P7_CAPTION, P7_CONSTANTE, P8_MODO, P8_TIPO, P8_CONSTANTE, P8_CAPTION, P9_MODO, P9_TIPO, P9_CAPTION, P9_CONSTANTE, TIPO_OBJ, COMENTARIO, ID_REPORTE, MODO_EJECUCION, KETTLE_NAME)
VALUES (0, 305, ''2.14.79 LK - EXTRACT EMISION ECHEQ'', ''ITF_LK_EXTRACT_EMISION_ECHEQ.kjb'', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', ''J'', '' '', 0, ''M'', NULL)
');
execute('
IF OBJECT_ID (''dbo.ITF_ECHEQ_EXTRACT_EMISION_CAB'') IS NOT NULL
	DROP TABLE dbo.ITF_ECHEQ_EXTRACT_EMISION_CAB
');
execute('
CREATE TABLE dbo.ITF_ECHEQ_EXTRACT_EMISION_CAB
	(
	NOM_ARCH      VARCHAR (26) NOT NULL,
	FECHA_EMISION DATE NOT NULL,
	PRIMARY KEY (NOM_ARCH, FECHA_EMISION)
	)
');
execute('
IF OBJECT_ID (''dbo.ITF_ECHEQ_EXTRACT_EMISION_DET'') IS NOT NULL
	DROP TABLE dbo.ITF_ECHEQ_EXTRACT_EMISION_DET
');
execute('
CREATE TABLE dbo.ITF_ECHEQ_EXTRACT_EMISION_DET
	(
	ID_ECHEQ      VARCHAR (15) NULL,
	NOM_ARCH      VARCHAR (26) NOT NULL,
	NRO_CHEQUE    VARCHAR (8) NOT NULL,
	NRO_CHEQUERA  VARCHAR (15) NULL,
	TIPO_CHEQUE   VARCHAR (3) NULL,
	ESTADO_CHEQUE VARCHAR (2) NULL,
	FECHA_EMISION NUMERIC (14) NULL,
	FECHA_PAGO    NUMERIC (14) NULL,
	MODO_CHEQUE   NUMERIC (1) NULL,
	MONTO_CHEQUE  NUMERIC (15, 2) NULL,
	CARACTER      VARCHAR (1) NULL,
	CMC7          VARCHAR (29) NOT NULL,
	CUIT_LIBRADOR NUMERIC (11) NULL,
	CBU_LIBRADOR  NUMERIC (22) NULL,
	TIPO_DOC_BEN  VARCHAR (4) NULL,
	CUIT_BEN      NUMERIC (11) NULL,
	FIRMANTE_1    VARCHAR (15) NULL,
	FIRMANTE_2    VARCHAR (15) NULL,
	FIRMANTE_3    VARCHAR (15) NULL
	)
');