IF OBJECT_ID (N'dbo.ITF_GIRELEC_AUX') IS NOT NULL
	DROP TABLE dbo.ITF_GIRELEC_AUX
GO

CREATE TABLE dbo.ITF_GIRELEC_AUX
	(
	  ORDEN      INT IDENTITY NOT NULL
	, CAMPO      VARCHAR (300) NULL
	, ID_CABEZAL INT NULL
	, TIPO       NUMERIC (1) NULL
	, SUCURSAL NUMERIC(5,0) NULL
	)
GO

