Execute('
DELETE FROM dbo.DESCRIPTORES WHERE IDENTIFICACION = 870;
INSERT INTO dbo.DESCRIPTORES
(TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES(930, 870, NULL, N''ITF_LK_ATM_COMISIONES'', 0, N''ITF_LK_ATM_COMISIONES'', N''D'', NULL, NULL, N''Top/Clientes'', NULL, N''N'');

DELETE FROM dbo.DESCRIPTORES WHERE IDENTIFICACION = 871;
INSERT INTO dbo.DESCRIPTORES
(TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES(930, 871, NULL, N''ITF_LK_ATM_COMISIONES_EXCLUSIO'', 0, N''ITF_LK_ATM_COMISIONES_EXCLUSIONES'', N''D'', NULL, NULL, N''Top/Clientes'', NULL, N''N'');

DELETE FROM dbo.OPERACIONES WHERE IDENTIFICACION = 5254;
INSERT INTO dbo.OPERACIONES
(TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES(6800, 5254, N''ABMC ITF LK ATM COMISIONES'', N''ABMC ITF LK ATM COMISIONES'', N''5254'', N''N'', NULL, NULL, N''P'', 0, NULL, 0, N''S'', N''N'', N''N'', N''N'', N''S'', NULL, 0);

DELETE FROM dbo.OPERACIONES WHERE IDENTIFICACION = 5255;
INSERT INTO dbo.OPERACIONES
(TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES(6800, 5255, N''ABMC ITF LK ATM COMISIONES EXCLUSIONES'', N''ABMC ITF LK ATM COMISIONES EXCLUSIONES'', N''5255'', N''N'', NULL, NULL, N''P'', 0, NULL, 0, N''S'', N''N'', N''N'', N''N'', N''S'', NULL, 0);

DELETE FROM dbo.OPCIONES WHERE NUMERODECAMPO = 41509;
INSERT INTO dbo.OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(41509, N''E'', N'''', N''BANELCO'', N''BANELCO'');
INSERT INTO dbo.OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(41509, N''E'', N'''', N''EXTERIOR'', N''EXTERIOR'');
INSERT INTO dbo.OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(41509, N''E'', N'''', N''LINKNBCH'', N''LINKNBCH'');
INSERT INTO dbo.OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(41509, N''E'', N'''', N''LINKOTRO'', N''LINKOTRO'');')