EXECUTE('
IF OBJECT_ID (''dbo.VW_CLIENTES_EXCLUIDOS'') IS NOT NULL
	DROP VIEW dbo.VW_CLIENTES_EXCLUIDOS
')

EXECUTE('
CREATE VIEW VW_CLIENTES_EXCLUIDOS AS
SELECT DISTINCT
A.PRODUCTO AS ''Producto'',
A.NOMBREPRODUCTO AS ''Nombre Producto'',
A.CLIENTE AS ''Cliente'',
A.CUENTA AS ''Cuenta'',
A.OPERACION AS ''Operación'',
CASE 
WHEN EC.GRADUACION IS NOT NULL THEN ''Cliente''
WHEN AUX.EXCLUIDO = ''S'' THEN ''Cuit Librador''
WHEN EA.GRADUACION IS NOT NULL THEN ''Asistencia''
WHEN EP.GRADUACION IS NOT NULL THEN ''Producto/Familia''
WHEN ETG.GRADUACION IS NOT NULL THEN ''Tipo garantía''
ELSE ''No'' 
END AS ''Ex Graduación'',
A.MONEDA AS ''Moneda'',
AD.SALDO_DEUDA AS ''Saldo Deuda'',
A.SUCURSAL AS ''Sucursal'',
A.NOMBRESUCURSAL AS ''Nombre Sucursal'',
A.VENCIMIENTO AS ''Fecha Vencimiento'',
A.JTS_OID AS ''JTS OID'',
A.FAMILIA AS ''Familia'',
A.OPERACION AS ''Operacion'',
A.DESGLOSE AS ''Desglose'',
A.NUMERODOC AS ''CUIT CUIL'',
A.NUMEROPERSONA AS ''Persona''
FROM VW_ASISTENCIAS A WITH(NOLOCK)
LEFT JOIN VW_DEUDA_CLIENTES AD WITH(NOLOCK) ON A.JTS_OID=AD.JTS_OID AND A.OPERACION = AD.OPERACION
LEFT JOIN CRE_GARANTIACREDITO GC WITH(NOLOCK) ON GC.JTSOID_SALDO =AD.JTS_OID AND GC.DESVINCULADO = ''N'' AND GC.TZ_LOCK=0
LEFT JOIN CRE_GARANTIASRECIBIDAS GR WITH(NOLOCK) ON GR.NUM_GARANTIA = GC.NUM_GARANTIA AND GR.TZ_LOCK = 0
LEFT JOIN CRE_EXCLUSIONES_ASISTENCIAS EA WITH(NOLOCK) ON AD.JTS_OID=EA.ASISTENCIA_JTS_OID AND EA.TZ_LOCK=0
LEFT JOIN CRE_EXCLUSIONES_CLIENTES EC WITH(NOLOCK) ON EC.CODIGOCLIENTE=A.CLIENTE AND EC.TZ_LOCK=0
LEFT JOIN CRE_EXCLUSIONES_PRODUCTOS EP WITH(NOLOCK) ON (CASE WHEN EP.TIPO=''F'' THEN A.FAMILIA ELSE A.PRODUCTO END) = EP.ITEM AND EP.TZ_LOCK=0
LEFT JOIN CRE_EXCLUSIONES_TIPOSGARANTIAS ETG WITH(NOLOCK) ON ETG.TIPO_GARANTIA = GR.TIPOGARANTIA AND ETG.TZ_LOCK = 0
LEFT JOIN (SELECT CD.JTS_OID, CASE WHEN MAX(ECE.CUENTA_FORANEA) IS NULL THEN ''N'' ELSE ''S'' END AS EXCLUIDO FROM VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO CD WITH(NOLOCK)
LEFT JOIN CRE_EXCLUSIONES_CUIT_EMISOR ECE WITH(NOLOCK) ON ECE.NUMERODOCUMENTO = CD.documento_librador AND ECE.CUENTA_FORANEA = CD.numerico_cuenta_giradora
AND ECE.TZ_LOCK = 0 
GROUP BY CD.JTS_OID) AUX ON AUX.JTS_OID = A.JTS_OID
WHERE AD.SALDO_DEUDA > 0
')

EXECUTE('
UPDATE dbo.AYUDAS
SET CAMPOS = ''565;760;617R;429;2616;2617;91R;804;35;427;376;127;2504R;665;622;618;''
	, CAMPOSVISTA = ''Producto;Nombre Producto;Cliente;Cuenta;Operacion;Desglose;Ex Graduación;Moneda;Saldo Deuda;Sucursal;Nombre Sucursal;Fecha Vencimiento;JTS OID;Familia;CUIT CUIL;Persona;''
WHERE NUMERODEAYUDA = 49450
')