EXECUTE('
INSERT INTO RRI_PARAMETROS_DEF (CODIGO, NOMBRE, ID1, ID1DESC, ID2, ID2DESC, ID3, ID3DESC, ID4, ID4DESC, ID5, ID5DESC, NUM1, NUM1DESC, NUM2, NUM2DESC, CHAR1, CHR1DESC, CHAR2, CHR2DESC, TZ_LOCK)
VALUES (11, ''TIPO ID OPE PASIVAS'', ''N'', '''', ''N'', '''', ''N'', '''', ''S'', ''TIPO IDENTIDAD'', ''N'', '''', ''S'', ''COD IDENTIDAD'', ''N'', '''', ''N'', '''', ''N'', '''', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''CDI'', '' '', 7, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''CI'', '' '', 6, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''CUIL'', '' '', 5, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''CUIT'', '' '', 4, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''DNI'', '' '', 1, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''LC'', '' '', 3, 0, '' '', '' '', 0)

INSERT INTO RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (11, 0, 0, 0, ''LE'', '' '', 2, 0, '' '', '' '', 0)

')