EXECUTE('
IF OBJECT_ID (''dbo.VW_RRII_OPCAM'') IS NOT NULL
	DROP VIEW dbo.VW_RRII_OPCAM;
')

EXECUTE('
CREATE      VIEW VW_RRII_OPCAM AS 
SELECT 
    2713 AS CODIGO_DISENO,
    311 AS CODIGO_ENTIDAD,
    '''' AS FECHA_INFORMACION,
    IRO.COD_JURISDICCION AS CODIGO_JURISDICCION,
    IRO.TIPO_OPERACION AS TIPO_OPERACION,
    IRO.NRO_REG_INTERNO AS NRO_BOLETO_INTERNO,
    IRO.NRO_ENTIDAD_COMPRADORA AS NRO_ENTIDAD,
    IRO.TIPO_ID_CLIENTE AS TIPO_IDENTIFICACION,
    IRO.NRO_ID_CLIENTE AS NRO_IDENTIFICACION,
    IRO.DENOMINACION_CLIENTE AS DENOMINACION,
    IRO.RESIDENCIA AS RESIDENCIA,
    IRO.CONDICION_CLIENTE AS CONDICION,
    IRO.COD_CORRESPONSAL AS CODIGO_CORRESPONSAL,
    --IRO.COD_INSTRUMENTO_VENDIDO AS CODIGO_INSTRUMENTO_VC,
    IRO.COD_INSTRUMENTO_RECIBIDO AS CODIGO_INSTRUMENTO_RRE,
    IRO.COD_PAIS_BENEF AS CODIGO_PAIS,
    IRO.DENOMINACION_BENEF AS DENOMINACION_BENEFICIARIO,
    IRO.PAIS_ORIGEN AS PAIS_ORIGEN,
    IRO.COD_CONCEPTO AS CODIGO_CONCEPTO,
    IRO.FECHA_OPERACION AS FECHA_OPERACION,
    IRO.COD_MONEDA AS CODIGO_MONEDA,
    IRO.IMPORTE_MONEDA_ORIGINAL AS IMPORTE_MONEDA,
    IRO.IMPORTE_PESOS AS IMPORTE_EN_PESOS,
    IRO.NRO_OFICIALIZACION_CONS_EXP AS NRO_OFICIALIZACION,
    ''0000000000000000''SIN_USO,
    CONVERT(DATETIME, CONVERT(CHAR(8),IRO.FECHA_INFO), 112) AS FECHA_PARAMETRO,
    IRO.COD_INSTRUMENTO_VENDIDO AS CODIGO_INSTRUMENTO_VC
    --1 AS INSTRUMENTO
    --IRO.FECHA_PROCESO AS FECHA_PARAMETRO
    FROM ITF_RRII_OPCAM IRO
    LEFT JOIN RRI_PARAMETROS_INF R ON R.CODIGO = 201 
    AND R.ID1 = 0	
	AND R.ID4 = IRO.COD_CONCEPTO
    --WHERE CONVERT(DATETIME, CONVERT(CHAR(8),IRO.FECHA_INFO), 112) = CONVERT(DATETIME,IRO.FECHA_INFO, 103)
   

  UNION ALL

  SELECT 
    2713 AS CODIGO_DISENO,
    (SELECT NUMERICO FROM PARAMETROSGENERALES WHERE CODIGO = 2) AS CODIGO_ENTIDAD,
    '''' AS FECHA_INFORMACION,--PARAMETRO
    CASE 
        WHEN EXISTS (SELECT 1 FROM SUCURSALES S WHERE S.ZONACOBRO = 1 AND S.SUCURSAL=MC.SUCURSAL) THEN ''1''
        ELSE ''6''
    END AS CODIGO_JURISDICCION,
    (SELECT DISTINCT R.CHAR1 FROM CODIGO_TRANSACCIONES CO 
    INNER JOIN RRI_PARAMETROS_INF R ON R.CODIGO=200 AND R.ID1=CO.CODIGO_OPERACION) AS TIPO_OPERACION,
    --IRO.NRO_REG_INTERNO AS NRO_BOLETO_INTERNO, PARAMETRIZAR CRIS 
    
    --R.CHAR1 || TO_CHAR(ROW_NUMBER() OVER (PARTITION BY R.CHAR1 ORDER BY R.CHAR1))) AS NRO_BOLETO_INTERNO,
     --R.CHAR1+  CONCAT(R.CHAR1, CAST(ROW_NUMBER() OVER (PARTITION BY R.CHAR1 ORDER BY R.CHAR1) AS CHAR)) AS NRO_BOLETO_INTERNO,
      CASE 
    WHEN R.CHAR1 IS NULL THEN SPACE(10)
    ELSE CONCAT(
        LTRIM(RTRIM(R.CHAR1)), 
        LEFT(
            CAST(ROW_NUMBER() OVER(PARTITION BY R.CHAR1 ORDER BY R.CHAR1) AS VARCHAR) + SPACE(10), 
            10
        )
    )
    END AS NRO_BOLETO_INTERNO,
    --''17533'' NRO_BOLETO_INTERNO,
    ''00000'' AS NRO_ENTIDAD,
    CASE 
    WHEN CDP.TIPO_DOC_FISICO = ''DNI'' THEN 01
    WHEN CDP.TIPO_DOC_FISICO = ''LE'' THEN 02
    WHEN CDP.TIPO_DOC_FISICO = ''LC'' THEN 03
    WHEN CDP.TIPO_DOC_FISICO = ''PAS'' THEN 04
    WHEN CDP.TIPO_DOC_FISICO = ''CI'' THEN 05
    WHEN CDP.TIPODOCUMENTO = ''CUIT'' THEN 11
    WHEN CDP.TIPODOCUMENTO = ''CNV'' THEN 55
    ELSE 07
    END AS TIPO_IDENTIFICACION,   
    CDP.NUMERODOCUMENTO AS NRO_IDENTIFICACION,
    CPF.PRIMERNOMBRE AS DENOMINACION,
    CASE 
     	WHEN CPF.CODIGODERESIDENCIA=2 THEN ''AR''
     	ELSE (SELECT CP.CODIGOSWIFT
     	      FROM CLI_PAISES CP
     	      WHERE CP.CODIGOPAIS=CPF.PAISRESIDENCIA)
    END AS RESIDENCIA, 
    CASE 
        WHEN CCP.TITULARIDAD = ''T'' THEN 1
        ELSE 2
    END AS CONDICION,--CONDICION CLIENTE    
    ''           '' AS CODIGO_CORRESPONSAL,
    --IRO.COD_INSTRUMENTO_VENDIDO AS CODIGO_INSTRUMENTO_VC, CASE CON OPCIONES 
    --2 AS CODIGO_INSTRUMENTO_VC,
    --IRO.COD_INSTRUMENTO_RECIBIDO AS CODIGO_INSTRUMENTO_RRE, CASE CON OPCIONES 
    99 AS CODIGO_INSTRUMENTO_RRE,
   ''00'' AS CODIGO_PAIS, 
    ''00000000000000000000000000000000000000000000000000'' AS DENOMINACION_BENEFICIARIO,
    ''00'' AS PAIS_ORIGEN,
   /* (SELECT TOP 1 GOC.COD_CONCEPTO 
     FROM GRL_OPE_CAMBIO GOC 
     WHERE GOC.SUCURSAL = MC.SUCURSAL 
       AND GOC.ASIENTO = MC.ASIENTO 
       AND GOC.FECHA_PROCESO = MC.FECHAPROCESO 
       AND GOC.MONEDA = MC.MONEDA) AS CODIGO_CONCEPTO,*/
    GOC.COD_CONCEPTO AS CODIGO_CONCEPTO,
    00000000 AS FECHA_OPERACION,
    (SELECT M.C6402 FROM MONEDAS M WHERE M.C6399 = MC.MONEDA) AS CODIGO_MONEDA,
    MC.CAPITALREALIZADO AS IMPORTE_MONEDA,
    MC.EQUIVALENTEMN AS IMPORTE_EN_PESOS,
    ''                '' AS NRO_OFICIALIZACION,
    ''0000000000000000'' AS SIN_USO,
     MC.FECHAPROCESO AS FECHA_PARAMETRO,
     
       
   CASE
       
        WHEN CO.CODIGO_OPERACION IN (3015, 3061) THEN 
            CASE 
                WHEN TCT.CODIGO_TRANSACCION = 1502 THEN 
                    CASE 
                        WHEN MC.MONEDA =1 THEN 01
                        ELSE 10 
                    END
                WHEN TCT.CODIGO_TRANSACCION = 1501 THEN 07
                ELSE NULL 
            END
      
        WHEN CO.CODIGO_OPERACION IN (3016, 3062) THEN 
            CASE 
                WHEN TCT.CODIGO_TRANSACCION = 1504 THEN 
                    CASE 
                        WHEN MC.MONEDA =1 THEN 01 
                        ELSE 10 
                    END
                WHEN TCT.CODIGO_TRANSACCION = 1503 THEN 07 
                ELSE NULL
            END
        ELSE NULL
    END AS CODIGO_INSTRUMENTO_VC
    
    FROM MOVIMIENTOS_CONTABLES MC WITH(NOLOCK)
    INNER JOIN CLI_CLIENTEPERSONA CCP WITH(NOLOCK) ON CCP.CODIGOCLIENTE=MC.CLIENTE AND CCP.TZ_LOCK=0
    LEFT JOIN CLI_PERSONASFISICAS CPF WITH(NOLOCK) ON CPF.NUMEROPERSONAFISICA=CCP.NUMEROPERSONA AND CPF.TZ_LOCK=0
    LEFT JOIN CLI_DocumentosPFPJ CDP WITH(NOLOCK) ON CDP.NUMEROPERSONAFJ=CCP.NUMEROPERSONA AND CDP.TZ_LOCK=0
    --LEFT JOIN TTR_CODIGO_TRANSACCION_DEF TCT WITH(NOLOCK) ON TCT.CODIGO_TRANSACCION=MC.COD_TRANSACCION AND TCT.TZ_LOCK=0
    --WHERE MC.FECHAPROCESO=''22/08/2024''
    INNER JOIN RRI_PARAMETROS_INF RP ON RP.ID1=MC.OPERACION AND RP.TZ_LOCK=0
    
    
    LEFT JOIN TTR_CODIGO_TRANSACCION_DEF TCT WITH(NOLOCK) ON TCT.CODIGO_TRANSACCION=MC.COD_TRANSACCION 
    													AND TCT.TZ_LOCK=0 
    													--AND TCT.CODIGO_TRANSACCION IN (1501, 1502, 1503, 1504)
    
    LEFT JOIN CODIGO_TRANSACCIONES CO WITH(NOLOCK) ON CO.CODIGO_TRANSACCION=MC.COD_TRANSACCION
    												 AND CO.TZ_LOCK=0 
    												 
     
    LEFT JOIN GRL_OPE_CAMBIO GOC  WITH(NOLOCK) ON  GOC.SUCURSAL = MC.SUCURSAL 
											       AND GOC.ASIENTO = MC.ASIENTO 
											       AND GOC.FECHA_PROCESO = MC.FECHAPROCESO 
											       AND GOC.MONEDA = MC.MONEDA												 
 	LEFT JOIN RRI_PARAMETROS_INF R  ON 
    R.CODIGO = 201 AND
    (
        
        (R.ID1 = 0 AND R.ID5 = MC.DEBITOCREDITO AND R.ID4 = GOC.COD_CONCEPTO)
        OR
       
        (R.ID1 = MC.OPERACION AND R.ID1 IN 
            (SELECT ID1 
             FROM RRI_PARAMETROS_INF 
             WHERE ID1 != 0 
             AND TZ_LOCK = 0 
             AND CODIGO = 201)
        )
    ) 				
    
    WHERE RP.CODIGO=200 AND MC.MONEDA!=1 AND MC.PRODUCTO=1
    
    
   
    
    UNION ALL
   
   
   SELECT 
    2713 AS CODIGO_DISENO,
    (SELECT NUMERICO FROM PARAMETROSGENERALES WHERE CODIGO = 2) AS CODIGO_ENTIDAD,
    '''' AS FECHA_INFORMACION,--PARAMETRO
    CASE 
        WHEN EXISTS (SELECT 1 FROM SUCURSALES S WHERE S.ZONACOBRO = 1 AND S.SUCURSAL=MC.SUCURSAL) THEN ''1''
        ELSE ''6''
    END AS CODIGO_JURISDICCION,
    (SELECT DISTINCT R.CHAR1 FROM CODIGO_TRANSACCIONES CO 
    INNER JOIN RRI_PARAMETROS_INF R ON R.CODIGO=200 AND R.ID1=CO.CODIGO_OPERACION) AS TIPO_OPERACION,
    --(SELECT R.CHAR1 FROM CODIGO_TRANSACCIONES CO 
    --INNER JOIN RRI_PARAMETROS_INF R ON R.CODIGO=200 AND R.ID1=CO.CODIGO_OPERACION )
    --IRO.NRO_REG_INTERNO AS NRO_BOLETO_INTERNO, PARAMETRIZAR CRIS 
    --''17533'' NRO_BOLETO_INTERNO,
       CASE 
    WHEN R.CHAR1 IS NULL THEN SPACE(10)
    ELSE CONCAT(
        LTRIM(RTRIM(R.CHAR1)), 
        LEFT(
            CAST(ROW_NUMBER() OVER(PARTITION BY R.CHAR1 ORDER BY R.CHAR1) AS VARCHAR) + SPACE(10), 
            10
        )
    )
    END AS NRO_BOLETO_INTERNO,   
    ''00000'' AS NRO_ENTIDAD,
    CASE 
    WHEN CDP.TIPO_DOC_FISICO = ''DNI'' THEN 01
    WHEN CDP.TIPO_DOC_FISICO = ''LE'' THEN 02
    WHEN CDP.TIPO_DOC_FISICO = ''LC'' THEN 03
    WHEN CDP.TIPO_DOC_FISICO = ''PAS'' THEN 04
    WHEN CDP.TIPO_DOC_FISICO = ''CI'' THEN 05
    WHEN CDP.TIPODOCUMENTO = ''CUIT'' THEN 11
    WHEN CDP.TIPODOCUMENTO = ''CNV'' THEN 55
    WHEN CPJ.TIPOSOCIEDAD = 66 THEN 66
    ELSE 07
    END AS TIPO_IDENTIFICACION,
    
    CDP.NUMERODOCUMENTO AS NRO_IDENTIFICACION,
    CPJ.RAZONSOCIAL AS DENOMINACION,
    CASE 
     	WHEN CPJ.CODIGODERESIDENCIA=2 THEN ''AR''
     	ELSE (SELECT CP.CODIGOSWIFT
     	      FROM CLI_PAISES CP
     	      WHERE CP.CODIGOPAIS=CPJ.PAISRESIDENCIA)
    END AS RESIDENCIA, 
--
--
--
    CASE 
        WHEN CCP.TITULARIDAD = ''T'' THEN 1
        ELSE 2
    END AS CONDICION,--CONDICION CLIENTE
    
    ''           '' AS CODIGO_CORRESPONSAL,
    --IRO.COD_INSTRUMENTO_VENDIDO AS CODIGO_INSTRUMENTO_VC, CASE CON OPCIONES 
    --2 AS CODIGO_INSTRUMENTO_VC,
    --IRO.COD_INSTRUMENTO_RECIBIDO AS CODIGO_INSTRUMENTO_RRE, CASE CON OPCIONES 
    99 AS CODIGO_INSTRUMENTO_RRE,
   ''00'' AS CODIGO_PAIS, 
    ''00000000000000000000000000000000000000000000000000'' AS DENOMINACION_BENEFICIARIO,
    ''00'' AS PAIS_ORIGEN,
    /*(SELECT TOP 1 GOC.COD_CONCEPTO 
     FROM GRL_OPE_CAMBIO GOC 
     WHERE GOC.SUCURSAL = MC.SUCURSAL 
       AND GOC.ASIENTO = MC.ASIENTO 
       AND GOC.FECHA_PROCESO = MC.FECHAPROCESO 
       AND GOC.MONEDA = MC.MONEDA) AS CODIGO_CONCEPTO,*/
    GOC.COD_CONCEPTO AS CODIGO_CONCEPTO,
    00000000 AS FECHA_OPERACION,
    (SELECT M.C6402 FROM MONEDAS M WHERE M.C6399 = MC.MONEDA) AS CODIGO_MONEDA,
    MC.CAPITALREALIZADO AS IMPORTE_MONEDA,
    MC.EQUIVALENTEMN AS IMPORTE_EN_PESOS,
    ''                '' AS NRO_OFICIALIZACION,
    ''0000000000000000'' AS SIN_USO,
    MC.FECHAPROCESO AS FECHA_PARAMETRO,
    
    --(SELECT CO.CODIGO_OPERACION FROM CODIGO_TRANSACCIONES CO WHERE CO.CODIGO_OPERACION IN(3015,3016,3061,3062) AND CO.CODIGO_TRANSACCION=TCT.CODIGO_TRANSACCION) AS INSTRUMENTO
    
   CASE
       
        WHEN CO.CODIGO_OPERACION IN (3015, 3061) THEN 
            CASE 
                WHEN TCT.CODIGO_TRANSACCION = 1502 THEN 
                    CASE 
                        WHEN MC.MONEDA =1 THEN 01
                        ELSE 10 
                    END
                WHEN TCT.CODIGO_TRANSACCION = 1501 THEN 07
                ELSE NULL 
            END
      
        WHEN CO.CODIGO_OPERACION IN (3016, 3062) THEN 
            CASE 
                WHEN TCT.CODIGO_TRANSACCION = 1504 THEN 
                    CASE 
                        WHEN MC.MONEDA =1 THEN 01 
                        ELSE 10 
                    END
                WHEN TCT.CODIGO_TRANSACCION = 1503 THEN 07 
                ELSE NULL
            END
        ELSE NULL
    END AS CODIGO_INSTRUMENTO_VC
    
    FROM MOVIMIENTOS_CONTABLES MC WITH(NOLOCK)
    INNER JOIN CLI_CLIENTEPERSONA CCP WITH(NOLOCK) ON CCP.CODIGOCLIENTE=MC.CLIENTE AND CCP.TZ_LOCK=0
    LEFT JOIN CLI_PERSONASJURIDICAS CPJ WITH(NOLOCK) ON CPJ.NUMEROPERSONAJURIDICA=CCP.NUMEROPERSONA 
    												AND CPJ.TZ_LOCK=0
    LEFT JOIN CLI_DocumentosPFPJ CDP WITH(NOLOCK) ON CDP.NUMEROPERSONAFJ=CCP.NUMEROPERSONA 	
    												AND CDP.TZ_LOCK=0
    INNER JOIN RRI_PARAMETROS_INF RP ON RP.ID1=MC.OPERACION AND RP.TZ_LOCK=0
    
    
    LEFT JOIN TTR_CODIGO_TRANSACCION_DEF TCT WITH(NOLOCK) ON TCT.CODIGO_TRANSACCION=MC.COD_TRANSACCION 
    													AND TCT.TZ_LOCK=0 
    													--AND TCT.CODIGO_TRANSACCION IN (1501, 1502, 1503, 1504)
    
    LEFT JOIN CODIGO_TRANSACCIONES CO WITH(NOLOCK) ON CO.CODIGO_TRANSACCION=MC.COD_TRANSACCION
    												 AND CO.TZ_LOCK=0 
    
    LEFT JOIN GRL_OPE_CAMBIO GOC  WITH(NOLOCK) ON  GOC.SUCURSAL = MC.SUCURSAL 
											       AND GOC.ASIENTO = MC.ASIENTO 
											       AND GOC.FECHA_PROCESO = MC.FECHAPROCESO 
											       AND GOC.MONEDA = MC.MONEDA										    												 
  	LEFT JOIN RRI_PARAMETROS_INF R  ON 
    R.CODIGO = 201 AND
    (
        
        (R.ID1 = 0 AND R.ID5 = MC.DEBITOCREDITO AND R.ID4 = GOC.COD_CONCEPTO)
        OR
       
        (R.ID1 = MC.OPERACION AND R.ID1 IN 
            (SELECT ID1 
             FROM RRI_PARAMETROS_INF 
             WHERE ID1 != 0 
             AND TZ_LOCK = 0 
             AND CODIGO = 201)
        )
    ) 																 
    WHERE RP.CODIGO=200  AND MC.MONEDA!=1 AND MC.PRODUCTO=1;
')