EXEC('
    DELETE FROM TTR_CODIGO_PROGRAMA_TRANSACCION WHERE codigoPrograma = 10;
    DELETE FROM TTR_CODIGO_TRANSACCION_INFO_EXTENDIDA WHERE codigoTransaccion = 400;
');

EXEC('
    INSERT INTO TTR_CODIGO_PROGRAMA_TRANSACCION (codigoPrograma,nombrePrograma,descripcion,TZ_LOCK) VALUES
	    (10,''MP_INFO_EXTENDIDA_TLF_CELULARES'',''TLF: Recarga celulares'',0);
');

EXEC('
    INSERT INTO TTR_CODIGO_TRANSACCION_INFO_EXTENDIDA (codigoTransaccion,infoExtendidaTipo,descripcion,TZ_LOCK) VALUES
	    (400,10,''TLF: Recarga de celulares'',0);
');

Execute('DROP TABLE IF EXISTS dbo.ITF_BEE_COMISIONES_EXCEPCIONES;
CREATE TABLE dbo.ITF_BEE_COMISIONES_EXCEPCIONES (
	CUIT VARCHAR(11) NOT NULL PRIMARY KEY,
	FECHA_DESDE DATETIME NOT NULL,
	FECHA_HASTA DATETIME NOT NULL,
	TZ_LOCK NUMERIC(15,0) NOT NULL DEFAULT 0
);')

Execute('DELETE FROM PARAMETROSGENERALES WHERE CODIGO = 783;
INSERT INTO PARAMETROSGENERALES (
	CODIGO,	DESCRIPCION,IMPORTE
) VALUES
(783,	''BEE - Com. por Mto. de Serv.'',	1607.07);')
