


-- Parche_NUTOPAZ56_34

-- Parche_NUTOPAZ56_34

-- Add new column PRONTOCAMBIARFECHA in table PARAMETROS
ALTER TABLE PARAMETROS ADD PRONTOCAMBIARFECHA NUMERIC(1,0) DEFAULT(0);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20240913_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVVRPUEFaNTZfMzQKDQotLSBQYXJjaGVfTlVUT1BBWjU2XzM0Cg0KLS0g
QWRkIG5ldyBjb2x1bW4gUFJPTlRPQ0FNQklBUkZFQ0hBIGluIHRhYmxlIFBBUkFNRVRST1MNCkFM
VEVSIFRBQkxFIFBBUkFNRVRST1MgQUREIFBST05UT0NBTUJJQVJGRUNIQSBOVU1FUklDKDEsMCkg
REVGQVVMVCgwKTsKDQoKCg0K', NULL, 0);
