EXECUTE('
CREATE OR ALTER PROCEDURE [dbo].[SP_COMPLETAR_TEMP_ACTIVIDAD_ECONOMICA]
	@P_ID_PROCESO float(53),
	@P_DT_PROCESO datetime2(0),
	@P_NRO_DOCUMENTO VARCHAR(20),
	@P_CODIGO_PERSONA NUMERIC(12,0),
	@P_TIPO_PERSONA VARCHAR(1),
	@P_USUARIO VARCHAR(10),
	@P_RET_PROCESO float(53) OUTPUT,
	@P_MSG_PROCESO varchar(max) OUTPUT
AS
BEGIN
	SET @P_RET_PROCESO = 0
	SET @P_MSG_PROCESO = ''Actividades completadas correctamente''
     
    BEGIN TRY
	 	
	 	INSERT INTO dbo.TEMP_CLI_ACTIVIDAD_ECONOMICA (
	 		TZ_LOCK, 
	 		CODIGO_USUARIO, 
	 		CODIGO_PERSONA_CLIENTE, 
	 		CODIGO_ACTIVIDAD, 
	 		ORDINAL_ACTIVIDAD, 
	 		EMPRESA, 
	 		CARGO, 
	 		FECHAINGRESO, 
	 		FECHAEGRESO, 
	 		SALARIO, 
	 		MONEDA, 
	 		FECHAACTUALIZACIONINGRESOS, 
	 		FUENTE_INGRESO, 
	 		INGRESO_LIQUIDO_PESOS, 
	 		RUC_INDEPENDIENTE, 
	 		INICIO_ACTIVIDAD, 
	 		NRO_CAJA_PROFESIONAL, 
	 		INGRESO_PROM_PESOS, 
	 		TIPO_DE_RENTA, 
	 		UBICACION_DEL_BIEN, 
	 		VTO_CONTRATO, 
	 		PADRON, 
	 		GIRO, 
	 		NRO_BPS, 
	 		PEQUEÑA_EMPRESA_DGI, 
	 		VENTA_ANUAL, 
	 		COSTO_VENTA_ANUAL, 
	 		PRESENTA_BAL_DECL_JURADA, 
	 		TIPO_DE_VIVIENDA, 
	 		CUOTA_HIPOTECA, 
	 		CUOTA_ALQUILER, 
	 		PERSONAS_A_CARGO, 
	 		NRO_HIJOS, 
	 		REQUIERE_CODEUDOR, 
	 		P_ESTADO_PATR_CERT, 
	 		CERTIFICADO_AFIP, 
	 		VTO_CERT_AFIP, 
	 		TIPO_DE_PERSONA, 
	 		COD_PAIS, 
	 		F_GRUPO_ACT_EC, 
	 		CONSTANCIA_INGRESOS, 
	 		IMPORTE, 
	 		INGRESOS_CERTIFICADOS, 
	 		VIATICOS, 
	 		PARTIDAS_EXTRAORDINARIAS, 
	 		HORAS_EXTRAS, 
	 		PARTIDAS_VARIABLES, 
	 		COMISIONES_COBRADAS, 
	 		ADELANTO_SUELDOS, 
	 		VIATICOS_SIN_RENDICION, 
	 		INGRESO_NOMINAL, 
	 		VTAS_ANUALES_UI, 
	 		DIRECCION, 
	 		CANTIDAD_EMPLEADOS, 
	 		ORIGEN_FUNTE_INGRESO, 
	 		TIPO_FISJUR, 
	 		FECHA_ACT_ECONOMICA, 
	 		CONSEJO_PROFESIONAL, 
	 		NRO_MAT_PROFESIONAL, 
	 		FECHA_INSCRIPCION_CNA, 
	 		FECHA_VENCIMIENTO_CNA, 
	 		IERIC, 
	 		FECHA_INICIO_IERIC, 
	 		FECHA_VENC_IERIC, 
	 		CARACTER_IERIC, 
	 		VERIFICADO_AFIP, 
	 		FECHA_VERIFICADO, 
	 		ORDEN_AFIP, 
	 		ESTADO_REGISTRO, 
	 		CUIL
	 	)
	 	
	 	SELECT 
	 		0 AS TZ_LOCK, --TZ_LOCK
			@P_USUARIO AS CODIGO_USUARIO, --CODIGO_USUARIO
			@P_CODIGO_PERSONA AS CODIGO_PERSONA_CLIENTE, --CODIGO_PERSONA_CLIENTE
			I.COD_ACTIVIDAD, --CODIGO_ACTIVIDAD
			ROW_NUMBER() OVER(ORDER BY I.COD_ACTIVIDAD) + (	
				SELECT MAX(ORDINAL_ACTIVIDAD) 
				FROM CLI_ACTIVIDAD_ECONOMICA 
				WHERE CODIGO_PERSONA_CLIENTE = @P_CODIGO_PERSONA
			) AS ORDINAL_ACTIVIDAD, --ORDINAL_ACTIVIDAD
			AE.EMPRESA, --EMPRESA
			AE.CARGO, --CARGO
			AE.FECHAINGRESO, --FECHAINGRESO
			AE.FECHAEGRESO, --FECHAEGRESO
			AE.SALARIO, --SALARIO
			AE.MONEDA, --MONEDA
			AE.FECHAACTUALIZACIONINGRESOS AS FECHAACTUALIZACIONINGRESOS, --FECHAACTUALIZACIONINGRESOS
			CASE 
				WHEN AE.CODIGO_PERSONA_CLIENTE IS NULL 
					THEN ''S'' 
					ELSE AE.FUENTE_INGRESO 
			END AS FUENTE_INGRESO, --FUENTE_INGRESO
			AE.INGRESO_LIQUIDO_PESOS, --INGRESO_LIQUIDO_PESOS
			AE.RUC_INDEPENDIENTE, --RUC_INDEPENDIENTE
			CONCAT(SUBSTRING(I.PERIODO,5,2),SUBSTRING(I.PERIODO,1,4)) AS INICIO_ACTIVIDAD, --INICIO_ACTIVIDAD
			AE.NRO_CAJA_PROFESIONAL, --NRO_CAJA_PROFESIONAL
			AE.INGRESO_PROM_PESOS, --INGRESO_PROM_PESOS
			AE.TIPO_DE_RENTA, --TIPO_DE_RENTA
			AE.UBICACION_DEL_BIEN, --UBICACION_DEL_BIEN
			AE.VTO_CONTRATO, --VTO_CONTRATO
			AE.PADRON, --PADRON
			AE.GIRO, --GIRO
			AE.NRO_BPS, --NRO_BPS
			AE.PEQUEÑA_EMPRESA_DGI, --PEQUEÑA_EMPRESA_DGI
			AE.VENTA_ANUAL, --VENTA_ANUAL
			AE.COSTO_VENTA_ANUAL, --COSTO_VENTA_ANUAL
			AE.PRESENTA_BAL_DECL_JURADA, --PRESENTA_BAL_DECL_JURADA
			AE.TIPO_DE_VIVIENDA, --TIPO_DE_VIVIENDA
			AE.CUOTA_HIPOTECA, ---CUOTA_HIPOTECA
			AE.CUOTA_ALQUILER, --CUOTA_ALQUILER
			AE.PERSONAS_A_CARGO, --PERSONAS_A_CARGO
			AE.NRO_HIJOS, --NRO_HIJOS
			AE.REQUIERE_CODEUDOR, --REQUIERE_CODEUDOR
			AE.P_ESTADO_PATR_CERT, --P_ESTADO_PATR_CERT
			AE.CERTIFICADO_AFIP, --CERTIFICADO_AFIP
			AE.VTO_CERT_AFIP, --VTO_CERT_AFIP
			AE.TIPO_DE_PERSONA, --TIPO_DE_PERSONA
			AE.COD_PAIS, --COD_PAIS
			AE.F_GRUPO_ACT_EC, --F_GRUPO_ACT_EC
			AE.CONSTANCIA_INGRESOS, --CONSTANCIA_INGRESOS
			AE.IMPORTE, --IMPORTE
			AE.INGRESOS_CERTIFICADOS, --INGRESOS_CERTIFICADOS
			AE.VIATICOS, --VIATICOS
			AE.PARTIDAS_EXTRAORDINARIAS, --PARTIDAS_EXTRAORDINARIAS
			AE.HORAS_EXTRAS, --HORAS_EXTRAS
			AE.PARTIDAS_VARIABLES, --PARTIDAS_VARIABLES
			AE.COMISIONES_COBRADAS, --COMISIONES_COBRADAS
			AE.ADELANTO_SUELDOS, --ADELANTO_SUELDOS
			AE.VIATICOS_SIN_RENDICION, --VIATICOS_SIN_RENDICION
			AE.INGRESO_NOMINAL, --INGRESO_NOMINAL
			AE.VTAS_ANUALES_UI, --VTAS_ANUALES_UI
			AE.DIRECCION, --DIRECCION
			AE.CANTIDAD_EMPLEADOS, --CANTIDAD_EMPLEADOS
			AE.ORIGEN_FUNTE_INGRESO, --ORIGEN_FUNTE_INGRESO
			@P_TIPO_PERSONA AS TIPO_FISJUR, --TIPO_FISJUR
			AE.FECHA_ACT_ECONOMICA, --FECHA_ACT_ECONOMICA
			AE.CONSEJO_PROFESIONAL, --CONSEJO_PROFESIONAL
			AE.NRO_MAT_PROFESIONAL, --NRO_MAT_PROFESIONAL
			AE.FECHA_INSCRIPCION_CNA, --FECHA_INSCRIPCION_CNA
			AE.FECHA_VENCIMIENTO_CNA, --FECHA_VENCIMIENTO_CNA
			AE.IERIC, --IERIC
			AE.FECHA_INICIO_IERIC, --FECHA_INICIO_IERIC
			AE.FECHA_VENC_IERIC, --FECHA_VENC_IERIC
			AE.CARACTER_IERIC, --CARACTER_IERIC
			''S'' AS VERIFICADO_AFIP, --VERIFICADO_AFIP
			@P_DT_PROCESO AS FECHA_VERIFICADO, --FECHA_VERIFICADO
			I.ORDEN, --ORDEN_AFIP
			CASE WHEN AE.CODIGO_PERSONA_CLIENTE IS NULL THEN ''A'' ELSE ''M'' END AS ESTADO_REGISTRO, --ESTADO_REGISTRO
			@P_NRO_DOCUMENTO AS CUIL --CUIL
	 	FROM ITF_AFIP_ACT_ECONOMICA AS I
	 	LEFT JOIN CLI_ACTIVIDAD_ECONOMICA AS AE ON
	 		AE.CODIGO_ACTIVIDAD = I.COD_ACTIVIDAD
	 		AND AE.CODIGO_PERSONA_CLIENTE = @P_CODIGO_PERSONA
			AND ((AE.TZ_LOCK < 100000000000000 OR AE.TZ_LOCK >= 200000000000000)
				AND (AE.TZ_LOCK < 300000000000000 OR AE.TZ_LOCK >= 400000000000000)  
			)	
	 	WHERE 
	 		I.CUIL = @P_NRO_DOCUMENTO
			AND ((I.TZ_LOCK < 100000000000000 OR I.TZ_LOCK >= 200000000000000)
				AND (I.TZ_LOCK < 300000000000000 OR I.TZ_LOCK >= 400000000000000)  
			)
	 	
	END TRY

	BEGIN CATCH
		DECLARE
        	@errornumber int
        SET @errornumber = ERROR_NUMBER()
	    DECLARE
	        @errormessage nvarchar(4000)
	    SET @errormessage = ERROR_MESSAGE()
	    BEGIN
	    	SET @P_RET_PROCESO = ERROR_NUMBER()
	        SET @P_MSG_PROCESO = ''Error al completar actividades económicas. '' + @errormessage
	        DECLARE
	            @PKG_CONSTANTES$C_LOG_TIPO_ERROR varchar(30)
	        SET @PKG_CONSTANTES$C_LOG_TIPO_ERROR = ''E''
	        EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
	            @P_ID_PROCESO = @P_ID_PROCESO, 
	            @P_FCH_PROCESO = @P_DT_PROCESO, 
	            @P_NOM_PACKAGE = ''SP_COMPLETAR_TEMP_ACTIVIDAD_ECONOMICA'',
	            @P_COD_ERROR = @P_RET_PROCESO, 
	            @P_MSG_ERROR = @P_MSG_PROCESO, 
	            @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_ERROR
		END
	END CATCH
END
')

