DROP TABLE IF EXISTS dbo.RRII_CREDEB_XLS_AUX


CREATE TABLE dbo.RRII_CREDEB_XLS_AUX
	(
	  ANIO_RECAUDACIONES   NUMERIC (4) DEFAULT ((0)) NOT NULL
	, MES_RECAUDACIONES    NUMERIC (2) DEFAULT ((0)) NOT NULL
	, CUOTA_RECAUDACIONES  NUMERIC (1) DEFAULT ((0)) NOT NULL
	, CODIGO_REGIMEN       NUMERIC (3) DEFAULT ((0)) NOT NULL
	, TIPO_DOCUMENTO       NUMERIC (2) DEFAULT ((0)) NOT NULL
	, NUMERO_DOCUMENTO     VARCHAR (13) DEFAULT (' ') NOT NULL
	, CBU                  VARCHAR (22) DEFAULT (' ') NOT NULL
	, IMPORTE_IMPUESTO     NUMERIC (15, 2) DEFAULT ((0)) NOT NULL
	, BASE_IMPONIBLE       NUMERIC (15, 2) DEFAULT ((0)) NOT NULL
	, MODALIDAD_MOVIMIENTO NUMERIC (2) DEFAULT ((0)) NOT NULL
	, CODIGO_BENEFICIO     NUMERIC (2) DEFAULT ((0)) NOT NULL
	, FECHA_MOVIMIENTO     VARCHAR (10) NOT NULL
	, SUCURSAL             NUMERIC (5) NOT NULL
	, DIA_RECAUDACIONES    NUMERIC (2) DEFAULT ((0)) NOT NULL
	, NRO_ASIENTO          NUMERIC (10) NOT NULL
	, CONSTRAINT PK_RRII_CREDEB_XLS_AUX PRIMARY KEY (ANIO_RECAUDACIONES, MES_RECAUDACIONES, DIA_RECAUDACIONES, CUOTA_RECAUDACIONES, CODIGO_REGIMEN, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, CBU, MODALIDAD_MOVIMIENTO, CODIGO_BENEFICIO, NRO_ASIENTO, SUCURSAL , FECHA_MOVIMIENTO )
	)
GO

