EXECUTE('
UPDATE DICCIONARIO
SET LARGO = 99
	, TIPODECAMPO = ''A''
WHERE NUMERODECAMPO = 40999
')

EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40998, '' '', 0, ''Campo concepto 507'', ''Campo concepto 507'', 255, ''A'', 0, NULL, 0, 507, 0, 0, 0, 0, 0, 0, ''Concepto 507'', 0, NULL)
')

