EXECUTE('
IF OBJECT_ID (''dbo.VW_TJD_ITF_NUM_RAIZ'') IS NOT NULL
	DROP VIEW dbo.VW_TJD_ITF_NUM_RAIZ
')
EXECUTE('
CREATE VIEW VW_TJD_ITF_NUM_RAIZ
AS

SELECT 
    LEN(prefijo) AS LARGO_PREFIJO,
    PREFIJO,
    MAX(RIGHT(RTRIM(numraiz), LEN(numraiz) - LEN(prefijo))) AS NUMERO,
    RTRIM(prefijo) + CAST(CAST(MAX(RIGHT(RTRIM(numraiz), LEN(numraiz) - LEN(prefijo))) AS INT) + 1 AS VARCHAR) AS NUMRAIZ
FROM 
    TJD_ITF_TARJETA_RAIZ AS R WITH (NOLOCK)
	where producto !=''0004''
GROUP BY 
    prefijo, LEN(prefijo)
   ')
