


-- Parche_NUCRDSIS_97

-- Parche_NUCRDSIS_97

-- Add PARAMETROS_JTS en SqlServer
-- HM begin sentence
			If not exists (select VALOR from PARAMETROS_JTS where upper(FUNCIONALIDAD)='CATEGORIZACION' and upper(PARAMETRO) = 'PIVOT_IPF_DEVENGADO_VIGENTE' )

			INSERT INTO PARAMETROS_JTS
			(FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
			VALUES(N'CATEGORIZACION', N'PIVOT_IPF_DEVENGADO_VIGENTE', N'0000', 0);
			
			If not exists (select VALOR from PARAMETROS_JTS where upper(FUNCIONALIDAD)='CATEGORIZACION' and upper(PARAMETRO) = 'PIVOT_DEVENGADO_IPFMORATORIO_VIGENTE' )
			
			INSERT INTO PARAMETROS_JTS
			(FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
			VALUES(N'CATEGORIZACION', N'PIVOT_DEVENGADO_IPFMORATORIO_VIGENTE', N'0000', 0);
		-- HM end sentence;




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20240826_2',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVUNSRFNJU185NwoNCi0tIFBhcmNoZV9OVUNSRFNJU185NwoNCi0tIEFk
ZCBQQVJBTUVUUk9TX0pUUyBlbiBTcWxTZXJ2ZXINCi0tIEhNIGJlZ2luIHNlbnRlbmNlCgkJCUlm
IG5vdCBleGlzdHMgKHNlbGVjdCBWQUxPUiBmcm9tIFBBUkFNRVRST1NfSlRTIHdoZXJlIHVwcGVy
KEZVTkNJT05BTElEQUQpPSdDQVRFR09SSVpBQ0lPTicgYW5kIHVwcGVyKFBBUkFNRVRSTykgPSAn
UElWT1RfSVBGX0RFVkVOR0FET19WSUdFTlRFJyApCgoJCQlJTlNFUlQgSU5UTyBQQVJBTUVUUk9T
X0pUUwoJCQkoRlVOQ0lPTkFMSURBRCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKCQkJVkFM
VUVTKE4nQ0FURUdPUklaQUNJT04nLCBOJ1BJVk9UX0lQRl9ERVZFTkdBRE9fVklHRU5URScsIE4n
MDAwMCcsIDApOwoJCQkKCQkJSWYgbm90IGV4aXN0cyAoc2VsZWN0IFZBTE9SIGZyb20gUEFSQU1F
VFJPU19KVFMgd2hlcmUgdXBwZXIoRlVOQ0lPTkFMSURBRCk9J0NBVEVHT1JJWkFDSU9OJyBhbmQg
dXBwZXIoUEFSQU1FVFJPKSA9ICdQSVZPVF9ERVZFTkdBRE9fSVBGTU9SQVRPUklPX1ZJR0VOVEUn
ICkKCQkJCgkJCUlOU0VSVCBJTlRPIFBBUkFNRVRST1NfSlRTCgkJCShGVU5DSU9OQUxJREFELCBQ
QVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQoJCQlWQUxVRVMoTidDQVRFR09SSVpBQ0lPTicsIE4n
UElWT1RfREVWRU5HQURPX0lQRk1PUkFUT1JJT19WSUdFTlRFJywgTicwMDAwJywgMCk7CgkJLS0g
SE0gZW5kIHNlbnRlbmNlOwoNCgoKDQo=', NULL, 0);
