DROP TABLE dbo.ITF_TLF_POS_HISTORICO;

CREATE TABLE dbo.ITF_TLF_POS_HISTORICO (
    FECHA_NEGOCIO DATETIME NOT NULL,
	FECHA_RELOJ DATETIME NOT NULL,
	ARCHIVO VARCHAR(7) COLLATE Modern_Spanish_CI_AS NOT NULL,
	LKBYTE varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
	LKPREF varchar(8) COLLATE Modern_Spanish_CI_AS NULL,
	LKDATT varchar(19) COLLATE Modern_Spanish_CI_AS NULL,
	LKRECT varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKAUTP varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKLNAT varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKFIIA varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKTERM varchar(16) COLLATE Modern_Spanish_CI_AS NOT NULL,
	LKLNCA varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKFIIC varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKPANC varchar(28) COLLATE Modern_Spanish_CI_AS NULL,
	LKMBRN numeric(3,0) DEFAULT 0 NULL,
	LKBRCH varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKREGN varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKUSER varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKTYPC varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKTYP numeric(4,0) DEFAULT 0 NULL,
	LKRTES numeric(2,0) DEFAULT 0 NULL,
	LKFI01 varchar(59) COLLATE Modern_Spanish_CI_AS NULL,
	LKTRAD varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	LKTRAT varchar(8) COLLATE Modern_Spanish_CI_AS NOT NULL,
	LKPOST varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI02 varchar(12) COLLATE Modern_Spanish_CI_AS NULL,
	LKSEQN varchar(12) COLLATE Modern_Spanish_CI_AS NOT NULL,
	LKTERT varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI03 varchar(27) COLLATE Modern_Spanish_CI_AS NULL,
	LKTCDE varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKTFRO varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKTTO varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKFROM varchar(28) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI04 varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	LKTOAC varchar(28) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI05 varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	LKAMT1 numeric(19,2) DEFAULT 0 NULL,
	LKAMT2 numeric(19,2) DEFAULT 0 NULL,
	LKAMT3 numeric(19,2) DEFAULT 0 NULL,
	LKFI08 varchar(11) COLLATE Modern_Spanish_CI_AS NULL,
	LKRES1 varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	LKRES2 varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKNOMB varchar(25) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI10 varchar(38) COLLATE Modern_Spanish_CI_AS NULL,
	LKTERC varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI11 varchar(28) COLLATE Modern_Spanish_CI_AS NULL,
	LKORIG numeric(3,0) DEFAULT 0 NULL,
	LKDATO varchar(22) COLLATE Modern_Spanish_CI_AS NULL,
	LKTIPV numeric(8,3) DEFAULT 0 NULL,
	LKFI14 varchar(11) COLLATE Modern_Spanish_CI_AS NULL,
	LKRVSL numeric(2,0) DEFAULT 0 NULL,
	LKPIN varchar(16) COLLATE Modern_Spanish_CI_AS NULL,
	LKFILL varchar(72) COLLATE Modern_Spanish_CI_AS NULL,
	LKTIPD varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	LKISSU varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	LKINTE numeric(6,2) DEFAULT 0 NULL,
	LKCASH numeric(8,2) DEFAULT 0 NULL,
	LKFI15 varchar(250) COLLATE Modern_Spanish_CI_AS NULL,
	LKFI16 varchar(25) COLLATE Modern_Spanish_CI_AS NULL,
	ID_TICKET numeric(15,0) DEFAULT 0 NOT NULL,
	ORDINAL numeric(10,0) NOT NULL,
	FECHAREGISTRO datetime NULL
	PRIMARY KEY (FECHA_NEGOCIO, ARCHIVO, LKTRAD, LKTRAT, LKSEQN, LKTERM, ORDINAL)
);