EXECUTE('
DELETE FROM CI_EVENTO WHERE ID_EVENTO=1016

DELETE FROM CI_CARGOS_X_EVENTO WHERE ID_EVENTO = 1016


INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (1016, ''IMP. A TRANSF. RECIBIDA DE OTROS BANCOS'', 0)

INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (401, 1016, 0, ''A'', 34096, ''CONDICIÓN CREDEB'', 1)


INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (501, 1016, 0, ''A'', 33991, ''CONDICIÓN SIRCREB'', 2)


INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (555, 1016, 0, ''A'', 0, '''', 3)
')
