


-- Patch_NUCRDSIS_67

-- Se agrega el Tipo de IPF a la tabla de Productos
ALTER TABLE PRODUCTOS ADD TIPO_CALCULO_IPF VARCHAR(1) DEFAULT('R') WITH VALUES;

-- Actualización de Conceptos, Diccionario y Opciones por Tipo Cálculo IPF
INSERT INTO CONCEPTOS (CODIGO, DESCRIPCION, CAMPOV25)
			VALUES (1354, 'Tipo Calculo IPF', 0);

			INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
			VALUES (60410, NULL, 0, 'Tipo Calculo IPF', 'TipoCalcIPF', 1, 'A', 0, NULL, 0, 1354, 0, 0, 0, 0, 1, 65, 'TIPO_CALCULO_IPF', 0, NULL);

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'E', 'Sobre el Remanente Capital', 'R', 'R');

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'E', 'Sobre el Capital Cuota', 'C', 'C');

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'E', 'Sobre el Monto Cuota', 'M', 'M');

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'P', 'Sobre o Saldo Capital', 'R', 'R');

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'P', 'Sobre o Capital Quota', 'C', 'C');

			INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
			VALUES (60410, 'P', 'Sobre o Total Cuota', 'M', 'M');




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20240911_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VQ1JEU0lTXzY3Cg0KLS0gU2UgYWdyZWdhIGVsIFRpcG8gZGUgSVBGIGEg
bGEgdGFibGEgZGUgUHJvZHVjdG9zDQpBTFRFUiBUQUJMRSBQUk9EVUNUT1MgQUREIFRJUE9fQ0FM
Q1VMT19JUEYgVkFSQ0hBUigxKSBERUZBVUxUKCdSJykgV0lUSCBWQUxVRVM7Cg0KLS0gQWN0dWFs
aXphY2nDs24gZGUgQ29uY2VwdG9zLCBEaWNjaW9uYXJpbyB5IE9wY2lvbmVzIHBvciBUaXBvIEPD
oWxjdWxvIElQRg0KSU5TRVJUIElOVE8gQ09OQ0VQVE9TIChDT0RJR08sIERFU0NSSVBDSU9OLCBD
QU1QT1YyNSkKCQkJVkFMVUVTICgxMzU0LCAnVGlwbyBDYWxjdWxvIElQRicsIDApOwoKCQkJSU5T
RVJUIElOVE8gRElDQ0lPTkFSSU8gKE5VTUVST0RFQ0FNUE8sIFVTT0RFTENBTVBPLCBSRUZFUkVO
Q0lBLCBERVNDUklQQ0lPTiwgUFJPTVBULCBMQVJHTywgVElQT0RFQ0FNUE8sIERFQ0lNQUxFUywg
RURJQ0lPTiwgQ09OVEFCSUxJWkEsIENPTkNFUFRPLCBDQUxDVUxPLCBWQUxJREFDSU9OLCBUQUJM
QURFVkFMSURBQ0lPTiwgVEFCTEFERUFZVURBLCBPUENJT05FUywgVEFCTEEsIENBTVBPLCBCQVNJ
Q08sIE1BU0NBUkEpCgkJCVZBTFVFUyAoNjA0MTAsIE5VTEwsIDAsICdUaXBvIENhbGN1bG8gSVBG
JywgJ1RpcG9DYWxjSVBGJywgMSwgJ0EnLCAwLCBOVUxMLCAwLCAxMzU0LCAwLCAwLCAwLCAwLCAx
LCA2NSwgJ1RJUE9fQ0FMQ1VMT19JUEYnLCAwLCBOVUxMKTsKCgkJCUlOU0VSVCBJTlRPIE9QQ0lP
TkVTIChOVU1FUk9ERUNBTVBPLCBJRElPTUEsIERFU0NSSVBDSU9OLCBPUENJT05JTlRFUk5BLCBP
UENJT05ERVBBTlRBTExBKQoJCQlWQUxVRVMgKDYwNDEwLCAnRScsICdTb2JyZSBlbCBSZW1hbmVu
dGUgQ2FwaXRhbCcsICdSJywgJ1InKTsKCgkJCUlOU0VSVCBJTlRPIE9QQ0lPTkVTIChOVU1FUk9E
RUNBTVBPLCBJRElPTUEsIERFU0NSSVBDSU9OLCBPUENJT05JTlRFUk5BLCBPUENJT05ERVBBTlRB
TExBKQoJCQlWQUxVRVMgKDYwNDEwLCAnRScsICdTb2JyZSBlbCBDYXBpdGFsIEN1b3RhJywgJ0Mn
LCAnQycpOwoKCQkJSU5TRVJUIElOVE8gT1BDSU9ORVMgKE5VTUVST0RFQ0FNUE8sIElESU9NQSwg
REVTQ1JJUENJT04sIE9QQ0lPTklOVEVSTkEsIE9QQ0lPTkRFUEFOVEFMTEEpCgkJCVZBTFVFUyAo
NjA0MTAsICdFJywgJ1NvYnJlIGVsIE1vbnRvIEN1b3RhJywgJ00nLCAnTScpOwoKCQkJSU5TRVJU
IElOVE8gT1BDSU9ORVMgKE5VTUVST0RFQ0FNUE8sIElESU9NQSwgREVTQ1JJUENJT04sIE9QQ0lP
TklOVEVSTkEsIE9QQ0lPTkRFUEFOVEFMTEEpCgkJCVZBTFVFUyAoNjA0MTAsICdQJywgJ1NvYnJl
IG8gU2FsZG8gQ2FwaXRhbCcsICdSJywgJ1InKTsKCgkJCUlOU0VSVCBJTlRPIE9QQ0lPTkVTIChO
VU1FUk9ERUNBTVBPLCBJRElPTUEsIERFU0NSSVBDSU9OLCBPUENJT05JTlRFUk5BLCBPUENJT05E
RVBBTlRBTExBKQoJCQlWQUxVRVMgKDYwNDEwLCAnUCcsICdTb2JyZSBvIENhcGl0YWwgUXVvdGEn
LCAnQycsICdDJyk7CgoJCQlJTlNFUlQgSU5UTyBPUENJT05FUyAoTlVNRVJPREVDQU1QTywgSURJ
T01BLCBERVNDUklQQ0lPTiwgT1BDSU9OSU5URVJOQSwgT1BDSU9OREVQQU5UQUxMQSkKCQkJVkFM
VUVTICg2MDQxMCwgJ1AnLCAnU29icmUgbyBUb3RhbCBDdW90YScsICdNJywgJ00nKTsKDQoKCg0K', NULL, 0);
