exec('

CREATE OR ALTER PROCEDURE dbo.SP_ITF_ACTUALIZAPERSONA
/*
PARAMETRO @P_TIPO_PERSONA
	F: persona fisica, actualizo tabla CLI_PERSONASFISICAS
	J: persona juridica, actualizo tabla CLI_PERSONASJURIDICAS
*/   
   @P_NUMPER NUMERIC(12,0),
   @P_CUIL VARCHAR(20),
   @P_TIPO_PERSONA varchar(1),   
   @P_IVA varchar(2),
   @P_IGA varchar(2),
   @P_MONOTRIBUTO varchar(2),
   @P_ASIENTO NUMERIC(10,0),
   @P_USUARIO VARCHAR(10)
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
   BEGIN   	  
   		
   	  DECLARE @V_IVA VARCHAR(2);
   	  DECLARE @V_IGA VARCHAR(2);
   	  DECLARE @V_MONOTRIBUTO VARCHAR(2);
   	  DECLARE @V_CADENA VARCHAR(255) = '''';
   	  DECLARE @V_EXISTE VARCHAR(1) = ''S'';   	  
   	  DECLARE @V_TABLA VARCHAR(25);
   	  
   	  SET @P_IVA = CASE @P_IVA WHEN '''' THEN ''EX'' ELSE @P_IVA END;
	  SET @P_IGA = CASE @P_IGA WHEN '''' THEN ''EX'' ELSE @P_IGA END;
   	  
	  DECLARE cursor_personas CURSOR FOR
	  SELECT [CODIGOCLIENTE] FROM VW_CLIENTES_PERSONAS WHERE NUMEROPERSONA = @P_NUMPER AND TITULARIDAD = ''T'';
	  
	  DECLARE @cod_cli NUMERIC(12,0);	  	  	  
	  
	  OPEN cursor_personas
	  
	  FETCH NEXT FROM cursor_personas into @cod_cli
	  
	  WHILE @@FETCH_STATUS = 0
		BEGIN	 
			SET @V_EXISTE = ''S''; 
			SET @V_IVA = '''';
			SET @V_IGA = '''';
			SET @V_MONOTRIBUTO = '''';			 
			SET @V_TABLA = ''CLI_CLIENTES'';
			 
			SELECT @V_IVA = IVA, @V_IGA = IGA, @V_MONOTRIBUTO = MONOTRIBUTO FROM CLI_CLIENTES WHERE [CODIGOCLIENTE] = @cod_cli;
			
			UPDATE CLI_CLIENTES SET IVA = @P_IVA, IGA = @P_IGA, MONOTRIBUTO = @P_MONOTRIBUTO  
		    WHERE [CODIGOCLIENTE] = @cod_cli AND [CODIGOCLIENTE] IN (SELECT [CODIGOCLIENTE] FROM VW_CLIENTES_PERSONAS WHERE [CODIGOCLIENTE] = @cod_cli AND TITULARIDAD = ''T'');
			 
			IF @@ROWCOUNT = 0 SET @V_EXISTE = ''N'';
			PRINT @@ROWCOUNT;
			
			IF @V_EXISTE = ''S''
			  BEGIN
				  SET @V_CADENA = CONCAT(''CUIL: '', @P_CUIL);	 
				  SET @V_CADENA = CONCAT(@V_CADENA, '' - TABLA:'');
          	      SET @V_CADENA = CONCAT(@V_CADENA, rtrim(ltrim(@V_TABLA)));	          
		  	      SET @V_CADENA = CONCAT(@V_CADENA, '' - IGA ANT:'');			 
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_IGA AS varchar));
			      SET @V_CADENA = CONCAT(@V_CADENA, '' - IGA DSP:'');
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_IGA AS varchar));
			      SET @V_CADENA = CONCAT(@V_CADENA, '' - IVA ANT:'');
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_IVA AS varchar));
			      SET @V_CADENA = CONCAT(@V_CADENA, '' - IVA DSP:'');
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_IVA AS varchar));
			      SET @V_CADENA = CONCAT(@V_CADENA, '' - MONOTRIB ANT:'');
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_MONOTRIBUTO AS varchar));
			      SET @V_CADENA = CONCAT(@V_CADENA, '' - MONOTRIB DSP:'');
			      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_MONOTRIBUTO AS varchar));
			  
			      INSERT INTO ITF_BITACORA (FECHAHORA, INTERFACE, DESCRIPCION, TZ_LOCK) VALUES
			      (GETDATE(), ''AFIP'', @V_CADENA, 0);
			      
			      /* Grabo Tabla BITACORA_CLIENTES */
			      EXEC dbo.SP_ITF_GRABO_BITACORA_CLIENTES @cod_cli, @P_ASIENTO, @P_USUARIO;
			        
			  END 
			FETCH NEXT FROM cursor_personas into @cod_cli	
		END
	  
	  CLOSE cursor_personas 
	  DEALLOCATE cursor_personas	  	  
      
      SET @V_EXISTE = ''S''
      SET @V_IVA = '''';
	  SET @V_IGA = '''';
	  SET @V_MONOTRIBUTO = '''';
		  
      IF @P_TIPO_PERSONA = ''J''
        BEGIN      
          SET @V_TABLA = ''CLI_PERSONASJURIDICAS'';                     
          
          SELECT @V_IVA = IVA, @V_IGA = IGA, @V_MONOTRIBUTO = MONOTRIBUTO FROM CLI_PERSONASJURIDICAS
		  WHERE NUMEROPERSONAJURIDICA = @P_NUMPER;
		  
      	  UPDATE CLI_PERSONASJURIDICAS SET IVA = @P_IVA, IGA = @P_IGA, MONOTRIBUTO= @P_MONOTRIBUTO 
      	  WHERE NUMEROPERSONAJURIDICA = @P_NUMPER AND ((TZ_LOCK < 300000000000000 OR TZ_LOCK >= 400000000000000) AND (TZ_LOCK = 0 OR TZ_LOCK >= 200000000000000));
      	  
      	  IF @@ROWCOUNT = 0
      	    SET @V_EXISTE = ''N'';
        END 
        
    ELSE --IF @P_TIPO_PERSONA = ''F''
        BEGIN       
          SET @V_TABLA = ''CLI_PERSONASFISICAS'';
            
          SELECT @V_IVA = IVA, @V_IGA = IGA, @V_MONOTRIBUTO = MONOTRIBUTO FROM CLI_PERSONASFISICAS
          WHERE NUMEROPERSONAFISICA = @P_NUMPER;
          
		  UPDATE CLI_PERSONASFISICAS SET IVA = @P_IVA, IGA = @P_IGA, MONOTRIBUTO= @P_MONOTRIBUTO 
      	  WHERE NUMEROPERSONAFISICA = @P_NUMPER AND ((TZ_LOCK < 300000000000000 OR TZ_LOCK >= 400000000000000) AND (TZ_LOCK = 0 OR TZ_LOCK >= 200000000000000));  
      	  
      	  IF @@ROWCOUNT = 0
      	    SET @V_EXISTE = ''N'';    	      
        END 
      
      IF @V_EXISTE = ''S''
        BEGIN
          SET @V_CADENA = CONCAT(''CUIL: '', @P_CUIL);          
          SET @V_CADENA = CONCAT(@V_CADENA, '' - TABLA:'');
          SET @V_CADENA = CONCAT(@V_CADENA, rtrim(ltrim(@V_TABLA)));
  	      SET @V_CADENA = CONCAT(@V_CADENA, '' - IGA ANT:'');			 
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_IGA AS varchar));
	      SET @V_CADENA = CONCAT(@V_CADENA, '' - IGA DSP:'');
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_IGA AS varchar));
	      SET @V_CADENA = CONCAT(@V_CADENA, '' - IVA ANT:'');
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_IVA AS varchar));
	      SET @V_CADENA = CONCAT(@V_CADENA, '' - IVA DSP:'');
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_IVA AS varchar));
	      SET @V_CADENA = CONCAT(@V_CADENA, '' - MONOTRIB ANT:'');
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@V_MONOTRIBUTO AS varchar));
	      SET @V_CADENA = CONCAT(@V_CADENA, '' - MONOTRIB DSP:'');
	      SET @V_CADENA = CONCAT(@V_CADENA, CAST(@P_MONOTRIBUTO AS varchar));
	  
	      INSERT INTO ITF_BITACORA (FECHAHORA, INTERFACE, DESCRIPCION, TZ_LOCK) VALUES
	      (GETDATE(), ''AFIP'', @V_CADENA, 0);
	      
	      /* Dependiendo del tipo de persona grabo Tabla BITACORA_PERSONAS_FISICAS o BITACORA_PERSONAS_JURIDICAS */
	      EXEC dbo.SP_ITF_GRABO_BITACORA_PERSONAS @P_NUMPER, @P_TIPO_PERSONA, @P_ASIENTO, @P_USUARIO
	      
	    END 
   END

');