

EXECUTE('



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45856, '' '', 0, ''NOMBRE_EO'', ''NOMBRE_EO'', 16, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''NOMBRE_EO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45857, '' '', 0, ''FECHA_PRESENTACION'', ''FECHA_PRESENTACION'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4466, ''FECHA_PRESENTACION'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45858, '' '', 0, ''FECHA_RECEPCION'', ''FECHA_RECEPCION'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4466, ''FECHA_RECEPCION'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45859, '' '', 0, ''COD_ENT_ORIGINANTE'', ''COD_ENT_ORIGINANTE'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''COD_ENT_ORIGINANTE'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45860, '' '', 0, ''COD_SUC_ORIGINANTE'', ''COD_SUC_ORIGINANTE'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''COD_SUC_ORIGINANTE'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45861, '' '', 0, ''COD_ENT_DESTINO'', ''COD_ENT_DESTINO'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''COD_ENT_DESTINO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45862, '' '', 0, ''COD_SUC_DESTINO'', ''COD_SUC_DESTINO'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''COD_SUC_DESTINO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45863, '' '', 0, ''CONTADOR_REGISTRO'', ''CONTADOR_REGISTRO'', 15, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''CONTADOR_REGISTRO'', 0, NULL)


')





