EXECUTE('
UPDATE dbo.DICCIONARIO
SET CAMPO = ''CODIGOPROCESAMIENTO'', DESCRIPCION=''CODIGOPROCESAMIENTO''
WHERE NUMERODECAMPO = 79551

UPDATE dbo.DICCIONARIO
SET CAMPO = ''CODIGORESPUESTA'', DESCRIPCION=''CODIGORESPUESTA''
WHERE NUMERODECAMPO = 79555
')