EXECUTE('
DELETE CI_IMPUESTOS_X_CARGO WHERE ID_CARGO IN (2103) AND ID_IMPUESTO IN (900,901)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (900, 2103, ''A'', 0, 34096, ''Cond CREDEB'', 0)

 
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (901, 2103, ''A'', 0, 34096, ''Cond CREDEB'', 0)

')
