EXECUTE('
IF OBJECT_ID (''dbo.VW_CRE_ORDEN_COBRANZA_SUELDOS'') IS NOT NULL
	DROP VIEW dbo.VW_CRE_ORDEN_COBRANZA_SUELDOS
')

EXECUTE('
CREATE VIEW VW_CRE_ORDEN_COBRANZA_SUELDOS
AS
SELECT T.CODIGO, T.ORDEN, T.JTS_DEBITO, T.CLIENTE, T.FECHA, T.TIPO, T.CLASIFICACION, V.NUMERODOCUMENTO AS NUMERODOC FROM (
SELECT DA.CODIGO,
DA.ORDEN,
DA.CONVENIO AS JTS_DEBITO,
DA.CLIENTE,
DA.FECHA,
DA.TIPO,
DA.CLASIFICACION
FROM VW_ORDEN_COBRANZA_DEBITOS_AUTOMATICOS DA
UNION
SELECT
CA.codigo,
CA.orden,
CA.JTS_OID,
CA.CLIENTE,
CA.VENCIMIENTO,
CA.TIPO,
CA.CLASIFICACION
FROM VW_CRE_ORDEN_COBRANZA_ASISTENCIAS CA) T
INNER JOIN CLI_CLIENTEPERSONA  AS CP WITH (nolock) ON CP.CODIGOCLIENTE = T.CLIENTE AND CP.TITULARIDAD=''T'' AND CP.TZ_LOCK=0
INNER JOIN CLI_DOCUMENTOSPFPJ  AS V WITH (nolock) ON CP.NUMEROPERSONA = V.NUMEROPERSONAFJ AND V.TZ_LOCK=0
')