EXECUTE('
	DROP VIEW IF EXISTS VW_NBCH24_CRE_SCORING;
');

EXECUTE('
	CREATE OR ALTER PROCEDURE dbo.SP_NBCH24_CRE_SCORING
	@DOCUMENTO BIGint,
	@LINEA numeric(5, 0),
	@jtsCV numeric(15, 0)
	AS 
	BEGIN
		SELECT 
	vc.JTS_CV jtsCV,
	p.C6250 AS linea, 
	p.C6251 AS descripcion,
	case when (pc.MONTO_MINIMO = 0) then pc.MONTO_MINIMO + 1000 else pc.MONTO_MINIMO end AS montoMinimo,
	SUM(ca.MONTO_CALCULADO) OVER (PARTITION BY p.C6250, doc.CODIGOCLIENTE, vc.JTS_CV ORDER BY p.C6250) AS montoMaximo,
	doc.numerodoc documentoUsuario,
	p.C6800 modulo, 
	dg.CANAL canal, 
	CONCAT(
			CONVERT(VARCHAR(20), vc.ID_CONVENIO), ''-'',
			CONVERT(VARCHAR(20), vc.JTS_CV), ''-'',
			CONVERT(VARCHAR(20), vc.ID_JURISDICCION), ''-'',
			CONVERT(VARCHAR(20), pc.PRODUCTO) , ''-'',
			CONVERT(VARCHAR(20), vc.ID_BENEFICIO) 
		) AS id
	 
	FROM CRE_VINCULACIONES_CONVENIOS vc WITH (NOLOCK)
	INNER JOIN SALDOS s WITH (NOLOCK) ON vc.JTS_CV = s.JTS_OID AND s.TZ_LOCK = 0 AND s.C1785 IN (2,3)
	INNER JOIN SUCURSALES suc WITH (NOLOCK) ON s.SUCURSAL = suc.SUCURSAL AND suc.TZ_LOCK = 0
	INNER JOIN CRE_PROD_CONVENIOS pc WITH (NOLOCK) ON vc.ID_CONVENIO = pc.DATO_TIPO AND pc.TIPO = ''C'' AND pc.HABILITADO = ''S'' 	AND pc.TZ_LOCK = 0
	INNER JOIN CONV_CONVENIOS_PAG c WITH (NOLOCK) ON pc.DATO_TIPO = c.ID_ConvPago AND c.TZ_LOCK=0
	INNER JOIN CONV_TIPOS t WITH (NOLOCK) ON c.Id_TpoConv = t.Id_TpoConv AND t.TZ_LOCK = 0
	INNER JOIN PRODUCTOS p WITH (NOLOCK) ON pc.PRODUCTO = p.C6250 AND p.TZ_LOCK = 0 AND p.C6800 = ''AH''
	INNER JOIN CRE_PRODUCTOSCANALDIGITAL dg WITH (NOLOCK) ON dg.PRODUCTO=P.C6250
	INNER JOIN VW_CLI_X_DOC doc WITH (NOLOCK) ON doc.CODIGOCLIENTE=s.C1803
	LEFT JOIN CRE_AUX_SOL_CALCULO_ADELANTO ca (NOLOCK) ON p.C6250 = ca.PRODUCTO AND c.ID_ConvPago = ca.CONVENIO
					AND s.C1803 = ca.CLIENTE AND vc.ID_JURISDICCION = ca.ID_JURIDICCION and dg.CANAL = ca.CANAL
	where (vc.TZ_LOCK=0 AND dg.CANAL=''HO'')
	 
	AND	doc.numerodoc = @DOCUMENTO
	AND  (@LINEA IS NULL OR P.C6250 = @LINEA)
	AND  (@jtsCV IS NULL OR vc.JTS_CV = @jtsCV)
	END
');

EXECUTE('
DELETE FROM ITF_MASTER_PARAMETROS WHERE CODIGO IN (272, 273, 274, 275, 545);

INSERT INTO ITF_MASTER_PARAMETROS
(CODIGO, CODIGO_INTERFACE, FUNCIONALIDAD, ALFA_1, ALFA_2, ALFA_3, NUMERICO_1, NUMERICO_2, FECHA, IMPORTE_1, IMPORTE_2, TZ_LOCK)
VALUES
(272, 2018002, ''NCF - Rescate'', ''F3 PYMES'', ''CHACO FCI PYMES'', ''2'', 30, 5941310, NULL, 0.00, 0.00, 0),
(273, 2018002, ''NCF - Rescate'', ''F1 AA'', ''CHACO FCI ABIERTO AHORRO'', ''2'', 30, 5899609, NULL, 0.00, 0.00, 0),
(274, 2018002, ''NCF - Rescate'', ''F2 RF'', ''CHACO FCI RENTA FIJA I'', ''2'', 30, 5899500, NULL, 0.00, 0.00, 0),
(275, 2018002, ''NCF - Rescate'', ''F4 INFRA'', ''CHACO FCI INFRAESTRUCTURA'', ''2'', 30, 5941201, NULL, 0.00, 0.00, 0),
(545, 2018002,''NCFRESCATE'',''A'',''no-reply@nbch.com.ar'',''FONDOS24 RESCATE'',9,0,NULL,0.00,0.00,0);
')

EXECUTE('
DROP TABLE IF EXISTS dbo.BITACORA_NCF_RESCATE_ARCHIVOS;

CREATE TABLE dbo.BITACORA_NCF_RESCATE_ARCHIVOS (
	ID bigint IDENTITY(1,1) NOT NULL,
	NOMBRE_ARCHIVO varchar(100) COLLATE Modern_Spanish_CI_AS NOT NULL,
	FECHA_PROCESO date NOT NULL,
	[TIMESTAMP] datetime NOT NULL,
	USUARIO_PROCESO varchar(30) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CONSTRAINT PK__BITACORA__3214EC27908155F3 PRIMARY KEY (ID)
);
')

EXECUTE('
DROP TABLE IF EXISTS dbo.BITACORA_NCF_RESCATE_REGISTROS;

CREATE TABLE dbo.BITACORA_NCF_RESCATE_REGISTROS (
	ID bigint IDENTITY(1,1) NOT NULL,
	ID_ARCHIVO bigint NOT NULL,
	CODIGO_FONDO varchar(10) COLLATE Modern_Spanish_CI_AS NULL,
	NOMBRE_FONDO varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	CUENTA_FONDO numeric(12,0) NULL,
	SUCURSAL_FONDO numeric(5,0) NULL,
	MODULO_FONDO numeric(5,0) NULL,
	IMPORTE varchar(18) COLLATE Modern_Spanish_CI_AS NULL,
	MONEDA numeric(5,0) NULL,
	NRO_ASIENTO numeric(10,0) NULL,
	SUCURSAL_ASIENTO numeric(5,0) NULL,
	ORIGEN_JTS_OID numeric(10,0) NULL,
	DESTINO_JTS_OID numeric(10,0) NULL,
	DESTINO_CBU varchar(22) COLLATE Modern_Spanish_CI_AS NULL,
	DESTINO_CODIGO_CLIENTE numeric(12,0) NULL,
	DESTINO_NOMBRE varchar(70) COLLATE Modern_Spanish_CI_AS NULL,
	DETALLE varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	CONSTRAINT PK__BITACORA__3214EC27F7DE0D87 PRIMARY KEY (ID),
	CONSTRAINT FK_BITACORA_NCF_RESCATE_REGISTROS_ARCHIVOS FOREIGN KEY (ID_ARCHIVO) REFERENCES dbo.BITACORA_NCF_RESCATE_ARCHIVOS(ID) ON DELETE CASCADE
);
')