EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40207, '' '', 0, ''NROPERSONANUEVA'', ''NROPERSONANUEVA'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3612, ''NROPERSONANUEVA'', 0, NULL)


ALTER TABLE MA_BANDEJA_SALIDA ADD NROPERSONANUEVA NUMERIC (12) DEFAULT ((0))

')