EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50800, '' '', 0, ''Opciones reporte tesoreria'', ''Opciones reporte tesoreria'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Opciones reporte tesoreria'', 0, NULL)
')

EXECUTE('
INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (50800, ''E'', ''8200 - Ingresadas Sucursales'', ''8200'', ''8200'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (50800, ''E'', ''8203 - Ingresadas Transportadoras'', ''8203'', ''8203'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (50800, ''E'', ''8204 - Movimientos Transportadoras'', ''8204'', ''8204'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (50800, ''E'', ''8205 - Movimientos Tesoro General'', ''8205'', ''8205'')
')

