EXECUTE('
CREATE OR ALTER            PROCEDURE [DBO].[SP_ITF_SOS_OPERACIONES]
	@FECHA VARCHAR(8),
	@MSG_ERROR VARCHAR(500) OUTPUT
AS
  DECLARE @FECHAPROCESO NUMERIC(8);
  
BEGIN
	
	BEGIN TRY
	
	SELECT @FECHAPROCESO = CONVERT(VARCHAR,FECHAPROCESO,112) FROM PARAMETROS WITH (NOLOCK);
	
	--LIMPIAMOS POR SI HAY REPROCESO
	DELETE FROM SOS_MOVS_HISTORICOS WHERE CONVERT(VARCHAR,FECHADEINFORMACION) = @FECHAPROCESO;
	
	/*********************************
	      CUENTAS VISTA
	**********************************/
	BEGIN 
		INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA
										, FECHADEINFORMACION
										, NUMERODECUENTA
										, NUMERODEOPERACION
										, CLASEDECUENTA
										, TIPODECUENTAUOPERACION
										, SUCURSALSISCEN
										, SUCURSALINTERNA
										, FECHADELAOPERACION
										, MONTOPESOS
										, ESPECIETRANSADACANTIDAD
										, ESPECIETRANSADATIPO
										, BANCOCORRESPONSALSWIFT
										, BENEFICIARIOORDENANTEDELEXTE
										, PAISDELBENEFICIARIOORDENANTE
										, DATOSADICIONALES
										, FECHAALTA
										, CODIGOSTOPAZ
										, COTIZACION
										, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
			RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
			RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
			RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
			FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
			REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
	    SELECT
		--1
		311 AS EMPRESA, 
		--2
		@FECHAPROCESO AS FECHADEINFORMACION,
		--3
		(CASE WHEN SOS.SUBSISTEMA IN (''PR'')
		  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR, SA.OPERACION),CONVERT(VARCHAR,SA.ORDINAL))
		  	  WHEN SOS.SUBSISTEMA IN (''PF'')
		  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR,MOV.OPERACION_CUENTA))
		      ELSE CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR,MOV.CUENTA)) END)AS NUMERODECUENTA,
		--4
		LEFT(CONCAT(MOV.ASIENTO, CONVERT(VARCHAR,MOV.FECHAPROCESO,112), MOV.SUCURSAL, MOV.ORDINAL),22) AS NUMERODEOPERACION,
		--5
		LEFT(SOS.SUBSISTEMA,3) AS CLASEDECUENTA,
		--6
		SOS.TIPOPERACION  AS TIPODECUENTAUOPERACION,
		--7
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,SUC.SUCURSALBCRA) END) AS SUCURSALSISCEN,
		--8
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,MOV.SUCURSAL) END) AS SUCURSALINTERNA,
		--9
		(CASE WHEN SA.C1785 = 4 THEN CONVERT(VARCHAR, SA.C1621, 112) ELSE CONVERT(VARCHAR,MOV.FECHAPROCESO,112) END) AS FECHADELAOPERACION,
		--10
		(CASE WHEN MOV.MONEDA IN (1,998,999) THEN
		 		 MOV.CAPITALREALIZADO 
			  ELSE 0 END) AS MONTOPESOS, 
		--11
		(CASE WHEN MOV.MONEDA NOT IN (1,998,999) THEN 
		   MOV.CAPITALREALIZADO
		   ELSE 0 END) AS ESPECIETRANSADACANTIDAD, 
		--12
		LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
		      WHERE M.C6399 = (CASE WHEN MOV.MONEDA IN (988,999) THEN 1 ELSE MOV.MONEDA END)
			    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
		--13
		'''' AS BANCOCORRESPONSALSWIFT,
		--14
		'''' AS BENEFICIARIOORDENANTEDELEXTE,
		--15
		'''' AS PAISDELBENEFICIARIOORDENANTE,
		--16
		(CASE WHEN SOS.SUBSISTEMA IN (''PF'',''CE'',''ME'') THEN '''' 
			  WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.TIPOPERACION NOT IN (101, 103) THEN '''' 
		      WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.TIPOPERACION IN (101, 103) 
		         THEN ISNULL(VT.BEN_MISMO_TITULAR, (CASE WHEN (SELECT COUNT(DISTINCT CLIENTE) 
		         				  FROM MOVIMIENTOS_CONTABLES MC WITH (NOLOCK) 
		                          WHERE MC.ASIENTO = MOV.ASIENTO 
		                            AND MC.SUCURSAL = MOV.SUCURSAL 
		                            AND MC.FECHAPROCESO = MOV.FECHAPROCESO
		                            AND MC.CLIENTE <> 0) > 1 THEN ''N''
		                            WHEN (SELECT COUNT(DISTINCT CLIENTE) 
		         				  FROM MOVIMIENTOS_CONTABLES MC WITH (NOLOCK) 
		                          WHERE MC.ASIENTO = MOV.ASIENTO 
		                            AND MC.SUCURSAL = MOV.SUCURSAL 
		                            AND MC.FECHAPROCESO = MOV.FECHAPROCESO
		                            AND MC.CLIENTE <> 0) = 1 THEN ''S''
		                    ELSE ''NO'' END))
		      WHEN SOS.SUBSISTEMA = ''PR'' THEN ''EFSI''
		END) AS DATOSADICIONALES,	
		--17
		CONVERT(VARCHAR, MOV.FECHAVALOR,112) AS FECHAALTA,
		--18
		CONCAT(RIGHT(CONCAT(REPLICATE(''0'',4),SOS.OPERACION),4), SOS.SUBSISTEMA, RIGHT(CONCAT(REPLICATE(''0'',7), SOS.CODTRANSACCION),7)) AS CODIGOSTOPAZ,
		--19
		ISNULL((CASE WHEN (CASE WHEN MOV.MONEDA IN (988,999) THEN 1 ELSE MOV.MONEDA END) = 1 THEN 0 ELSE 
		  (CASE WHEN SOS.SUBSISTEMA IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN 
		        	(SELECT TIPC.TIPO_CAMBIO_OFICIAL 
		        	 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
		        	 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO 
		        	   AND TIPC.MONEDA = SA.MONEDA 
		        	   AND TIPC.TZ_LOCK = 0)
		        WHEN SOS.SUBSISTEMA IN (''PR'',''PF'') THEN 
		            (SELECT CASE WHEN MOV.OPERACION = 3015 THEN TIPC.TIPO_CAMBIO_COMPRA 
								 WHEN MOV.OPERACION = 3016 THEN TIPC.TIPO_CAMBIO_VENTA 
								 ELSE TIPC.TIPO_CAMBIO_COMPRA END
					 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
					 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO
					    AND TIPC.MONEDA = SA.MONEDA 
					    AND TIPC.TZ_LOCK = 0)
				WHEN SOS.SUBSISTEMA = ''CE'' THEN 
					(SELECT TIPO_CAMBIO 
					 FROM GRL_OPE_CAMBIO WITH (NOLOCK) 
					 WHERE SUCURSAL = MOV.SUCURSAL 
					 AND FECHA_PROCESO = MOV.FECHAPROCESO 
					 AND ASIENTO = MOV.ASIENTO
					 AND TZ_LOCK = 0)																			 
		   ELSE 0 END) END),0) AS COTIZACION,
		--20
		(CASE WHEN ASI.EXTORNO = 1 THEN ''SI''ELSE ''NO'' END)  AS REVERSADA,
		--21
		'''' AS OPER_ID_BIC_SWIFT,
		--22
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
				  THEN (CASE WHEN SOS.OPERACION = 3510 THEN CONVERT(VARCHAR,CHELAV.NRO_DOC_ORDEN) ELSE CONVERT(VARCHAR,VMOV.NRO_DOC_I) END)
		     WHEN SOS.TIPOPERACION IN (101,103) THEN 
		     								ISNULL(CONVERT(VARCHAR,VT.BEN_NRO_DOC),
													     (SELECT (CLIX.NUMERODOC) FROM MOVIMIENTOS_CONTABLES MOVX WITH (NOLOCK)
													      INNER JOIN SALDOS SAX ON SAX.JTS_OID = MOVX.SALDO_JTS_OID
													      INNER JOIN VW_CLI_X_DOC CLIX WITH (NOLOCK) ON CLIX.CODIGOCLIENTE = MOVX.CLIENTE_ORIGEN
														WHERE MOVX.FECHAPROCESO = MOV.FECHAPROCESO
														  AND MOVX.ASIENTO = MOV.ASIENTO
														  AND MOVX.SUCURSAL = MOV.SUCURSAL
														  AND MOVX.ORDINAL = 0
														  AND MOVX.COD_TRANSACCION <> MOV.COD_TRANSACCION))
			ELSE '''' END
		),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
		--23
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		          THEN (CASE WHEN SOS.OPERACION = 3510 THEN (CASE WHEN CHELAV.TIPO_PERSONA_ORDEN = ''F'' THEN ''PF'' WHEN CHELAV.TIPO_PERSONA_ORDEN = ''J'' THEN ''PJ'' END)
		               ELSE (CASE WHEN VMOV.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END) END)
			ELSE '''' END
		),2) AS RTE_OPE_FON_TIPO_PERSONA,
		--24
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.NOMBRE FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_ORDEN))
		                      ELSE CONCAT(VMOV.APELLIDO_I,'' '', VMOV.NOMBRE_I) END)
			ELSE '''' END
		),100) AS RTE_OPE_FON_DENOMINACION,
		--25
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.APELLIDOS FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_ORDEN))
		                      ELSE VMOV.APELLIDO_I END)
			ELSE '''' END
		),50)  AS RTE_OPE_FON_APELLIDOS,
		--26
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.PRIMERNOMBRE FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_ORDEN))
		                      ELSE VMOV.NOMBRE_I END)
			ELSE '''' END
		),50) AS RTE_OPE_FON_NOMBRES,
		--27
		(CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)  
		      THEN ''96'' ELSE '''' END) AS RTE_OPE_FON_TIPODOC,
		--28
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
				  THEN (CASE WHEN SOS.OPERACION = 3510 THEN SUBSTRING(CONVERT(VARCHAR,CHELAV.NRO_DOC_ORDEN),3,8)
				             ELSE SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_I),3,8) END)
			ELSE '''' END
		),10)  AS RTE_OPE_FON_NUMDOC,
		--29
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR) ELSE  CONVERT(VARCHAR,VMOV.NRO_DOC_M) END)
			ELSE '''' END
		),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
		--30
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		          THEN (CASE WHEN SOS.OPERACION = 3510 THEN (CASE WHEN CHELAV.TIPO_PERSONA_TITULAR = ''F'' THEN ''PF'' WHEN CHELAV.TIPO_PERSONA_TITULAR = ''J'' THEN ''PJ'' END) ELSE (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END) END)
			ELSE '''' END
		),2) AS RTE_TIT_FON_TIPO_PERSONA,
		--31
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.NOMBRE FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR)) ELSE CONCAT(VMOV.APELLIDO_M,'' '', VMOV.NOMBRE_M) END)
			ELSE '''' END
		),100) AS RTE_TIT_FON_DENOMINACION,
		--32
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		        THEN  (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.APELLIDOS FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR)) ELSE VMOV.APELLIDO_M END)
			ELSE '''' END
		),50) AS RTE_TIT_FON_APELLIDOS,
		--33
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		        THEN (CASE WHEN SOS.OPERACION = 3510 THEN (SELECT PFJ.PRIMERNOMBRE FROM VW_PERSONAS_FYJ PFJ WHERE PFJ.NroDocIdent = CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR)) ELSE VMOV.NOMBRE_M END)
			ELSE '''' END
		),50) AS RTE_TIT_FON_NOMBRES,
		--34
		(
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (CASE WHEN CHELAV.TIPO_PERSONA_TITULAR = ''F'' THEN ''96'' WHEN CHELAV.TIPO_PERSONA_TITULAR = ''J'' THEN ''80'' END) ELSE
		                (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''96'' WHEN VMOV.TIPO_PERSONA_M = ''J'' THEN ''80'' END) END)
			ELSE '''' END
		) AS RTE_TIT_FON_TIPODOC,
		--35
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN SOS.OPERACION = 3510 THEN (CASE WHEN CHELAV.TIPO_PERSONA_TITULAR = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR),3,8)
								      WHEN CHELAV.TIPO_PERSONA_TITULAR = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,CHELAV.NRO_DOC_TITULAR),1,10) END)
		                ELSE (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),3,8)
								      WHEN VMOV.TIPO_PERSONA_M = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),1,10) END) END)
			ELSE '''' END
		),10) AS RTE_TIT_FON_NUMDOC,
		--36
		'''' AS RTI_TIPOPERSONA,
		--37
		'''' AS RTI_TIPOOPERACION_COMEX,
		--FECHAAPERTURACUENTA
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, MOV.FECHAVALOR  ,112))  
			  ELSE
			   CONVERT(NUMERIC,CONVERT(VARCHAR,SA.C1620 ,112)) END) AS FECHAAPERTURACUENTA,
		--CLIENTE
		SA.C1803 AS CODCLIENTE,
		SUC.SUCURSALBCRA AS SUCURSALSISCENCTA,
		--38
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''TITULAR'' END), 30) AS REL_FON_TIT,
		--39
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
		  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_I AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
																   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_I 
																     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
																     --AND VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
																     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_TIT,
		--40
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''OPERADOR'' END), 30) AS REL_FON_OPER,
		--41
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
		  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_M AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
																   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_M 
																     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
																   --VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
																     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_OPER,
		--
		SA.JTS_OID
		--SELECT MOV.*
		FROM MOVIMIENTOS_CONTABLES MOV WITH (NOLOCK)
		  INNER JOIN ASIENTOS ASI WITH (NOLOCK) ON ASI.FECHAPROCESO = MOV.FECHAPROCESO AND ASI.SUCURSAL = MOV.SUCURSAL AND ASI.ASIENTO = MOV.ASIENTO
		  INNER JOIN SOS_TRANSACCIONES SOS WITH (NOLOCK) ON SOS.CODTRANSACCION = MOV.COD_TRANSACCION AND SOS.OPERACION = MOV.OPERACION
		    AND SOS.SUBSISTEMA NOT IN (''ME'',''TC'',''TT'',''PR'',''CE'')
		    AND ((SOS.PAGOSAINFORMAR = ''T'') OR
		         (SOS.PAGOSAINFORMAR = ''E'' AND ((MOV.CAJADIARIO = ''D'' AND ASI.EXTORNO = 1) OR (MOV.CAJADIARIO = ''C''))) OR
		         (SOS.PAGOSAINFORMAR = ''D'' AND MOV.CAJADIARIO <> ''C''))
		    AND ((ASI.EXTORNO = 0 AND (SOS.TIPO_MOVIMIENTO = MOV.DEBITOCREDITO
		          OR SOS.TIPO_MOVIMIENTO = ''A''))
		            OR ASI.EXTORNO = 1)
		  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOV.SUCURSAL
		  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.C1785 NOT IN (''5'',''8'') AND SA.JTS_OID = MOV.SALDO_JTS_OID AND SA.OPERACION = MOV.OPERACION_CUENTA
											  AND (CASE WHEN SA.C1785 = ''3'' THEN ''AC''
														WHEN SA.C1785 = ''2'' THEN ''CC''
														WHEN SA.C1785 = ''4'' THEN ''PF'' END) =  SOS.SUBSISTEMA
											 AND ((SA.TZ_LOCK < 300000000000000 OR SA.TZ_LOCK >= 400000000000000) 
												AND (SA.TZ_LOCK < 100000000000000 OR SA.TZ_LOCK >= 200000000000000))
											AND mov.SUCURSAL_CUENTA = SA.sucursal 
		  LEFT JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
		  LEFT JOIN VTA_TRANSFERENCIAS VT ON VT.FECHA_ASIENTO = MOV.FECHAPROCESO AND VT.NUMERO_ASIENTO = MOV.ASIENTO AND VT.SUCURSAL_ASIENTO = MOV.SUCURSAL
		  LEFT JOIN CHE_LAVADO CHELAV ON CHELAV.JTS_OID_CUENTA = MOV.SALDO_JTS_OID AND CHELAV.FECHA = MOV.FECHAPROCESO AND CHELAV.NRO_CHEQUE = MOV.REFERENCIA
		WHERE MOV.FECHAPROCESO =  @FECHA
		  AND MOV.CLIENTE <> 0
		  AND SOS.TZ_LOCK = 0
		  AND SUC.TZ_LOCK = 0
		  AND (MOV.NROCAJA <> 0 
			OR (MOV.NROCAJA = 0 AND MOV.OPERACION IN (8620, 3511, 3502, 3538))
			OR (MOV.NROCAJA = 0 AND SOS.SUBSISTEMA = ''PF''))
		  AND SA.PRODUCTO <> 0
		  AND ASI.ESTADO = 77
		  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS X WITH (NOLOCK) 
		  				 WHERE X.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' 
		  				   AND X.ALFA_1 = SA.PRODUCTO
		  				   AND X.TZ_LOCK = 0)
		  AND NOT EXISTS(SELECT 1 FROM ASIENTOS_EXTORNADOS ASI WITH (NOLOCK)
		  				 WHERE ASI.SUCURSAL = MOV.SUCURSAL 
		  				    AND ASI.FECHA_PROCESO = MOV.FECHAPROCESO
		                 	AND ASI.ASIENTO = MOV.ASIENTO
		                 	AND ASI.FECHA_PROCESO = ASI.FECHA_EXTORNO)
		  AND NOT EXISTS(SELECT 1 FROM CAJ_SOLICITUD_BAJA_ASIENTO BAJ 
		  				 WHERE BAJ.ASIENTO = MOV.ASIENTO
		  				   AND BAJ.SUCURSAL = MOV.SUCURSAL
		  				   AND BAJ.FECHAPROCESO = MOV.FECHAPROCESO
		  				   AND BAJ.ESTADO = ''C'')
		  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
		   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
		  					INNER JOIN CLI_PERSONASFISICAS NAT WITH(NOLOCK) ON P.NUMEROPERSONA = NAT.NUMEROPERSONAFISICA
		  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
		  				   AND NAT.SECTOR IN (6,7)
		  				   AND NAT.TZ_LOCK = 0
		  				   AND P.TZ_LOCK = 0
		  				   AND CLI.TZ_LOCK = 0)
		  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
		   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
		  					INNER JOIN CLI_PERSONASJURIDICAS JUR WITH(NOLOCK) ON P.NUMEROPERSONA = JUR.NUMEROPERSONAJURIDICA
		  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
		  				   AND JUR.SECTOR IN (6,7)
		  				   AND JUR.TZ_LOCK = 0
		  				   AND P.TZ_LOCK = 0
		  				   AND CLI.TZ_LOCK = 0)
	END
	/*********************************
	      CUENTAS VISTA (CE)
	**********************************/
	BEGIN 
		INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
			SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
			ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
			FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
			RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
			RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
			RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
			FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
			REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
		SELECT
		--1
		311 AS EMPRESA, 
		--2
		@FECHAPROCESO AS FECHADEINFORMACION,
		--3
		(CASE WHEN SOS.SUBSISTEMA IN (''PR'')
		  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR, SA.OPERACION),CONVERT(VARCHAR,SA.ORDINAL))
		  	  WHEN SOS.SUBSISTEMA IN (''PF'')
		  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR,MOV.OPERACION_CUENTA))
		      ELSE CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR,MOV.CUENTA)) END)AS NUMERODECUENTA,
		--4
		LEFT(CONCAT(MOV.ASIENTO, CONVERT(VARCHAR,MOV.FECHAPROCESO,112), MOV.SUCURSAL, MOV.ORDINAL),22) AS NUMERODEOPERACION,
		--5
		LEFT(SOS.SUBSISTEMA,3) AS CLASEDECUENTA,
		--6
		SOS.TIPOPERACION  AS TIPODECUENTAUOPERACION,
		--7
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,SUC.SUCURSALBCRA) END) AS SUCURSALSISCEN,
		--8
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,MOV.SUCURSAL) END) AS SUCURSALINTERNA,
		--9
		(CASE WHEN SA.C1785 = 4 THEN CONVERT(VARCHAR, SA.C1621, 112) ELSE CONVERT(VARCHAR,MOV.FECHAPROCESO,112) END) AS FECHADELAOPERACION,
		--10
		(CASE WHEN CB.MONEDA IN (1,998,999) THEN
		 		 CB.IMPORTE_ME
			  ELSE 0 END) AS MONTOPESOS, 
		--11
		(CASE WHEN CB.MONEDA NOT IN (1,998,999) THEN 
		     CB.IMPORTE_ME
		   ELSE 0 END) AS ESPECIETRANSADACANTIDAD, 
		--12
		LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
		      WHERE M.C6399 = (CASE WHEN CB.MONEDA IN (988,999) THEN 1 ELSE CB.MONEDA END)
			    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
		--13
		'''' AS BANCOCORRESPONSALSWIFT,
		--14
		'''' AS BENEFICIARIOORDENANTEDELEXTE,
		--15
		'''' AS PAISDELBENEFICIARIOORDENANTE,
		--16
		(CASE WHEN SOS.SUBSISTEMA IN (''PF'',''CE'',''ME'') THEN '''' 
			  WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.TIPOPERACION NOT IN (101, 103) THEN '''' 
		      WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.TIPOPERACION IN (101, 103) 
		         THEN ISNULL(VT.BEN_MISMO_TITULAR, (CASE WHEN (SELECT COUNT(DISTINCT CLIENTE) 
		         				  FROM MOVIMIENTOS_CONTABLES MC WITH (NOLOCK) 
		                          WHERE MC.ASIENTO = MOV.ASIENTO 
		                            AND MC.SUCURSAL = MOV.SUCURSAL 
		                            AND MC.FECHAPROCESO = MOV.FECHAPROCESO
		                            AND MC.CLIENTE <> 0) > 1 THEN ''N''
		                            WHEN (SELECT COUNT(DISTINCT CLIENTE) 
		         				  FROM MOVIMIENTOS_CONTABLES MC WITH (NOLOCK) 
		                          WHERE MC.ASIENTO = MOV.ASIENTO 
		                            AND MC.SUCURSAL = MOV.SUCURSAL 
		                            AND MC.FECHAPROCESO = MOV.FECHAPROCESO
		                            AND MC.CLIENTE <> 0) = 1 THEN ''S''
		                    ELSE ''NO'' END))
		      WHEN SOS.SUBSISTEMA = ''PR'' THEN ''EFSI''
		END) AS DATOSADICIONALES,
		--17
		CONVERT(VARCHAR, MOV.FECHAVALOR,112) AS FECHAALTA,
		--18
		CONCAT(RIGHT(CONCAT(REPLICATE(''0'',4),SOS.OPERACION),4), SOS.SUBSISTEMA, RIGHT(CONCAT(REPLICATE(''0'',7), SOS.CODTRANSACCION),7)) AS CODIGOSTOPAZ,
		--19
		ISNULL((CASE WHEN (CASE WHEN cb.MONEDA IN (988,999) THEN 1 ELSE cb.MONEDA END) = 1 THEN 0 ELSE 
		  (CASE WHEN SOS.SUBSISTEMA IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN 
		        	(SELECT TIPC.TIPO_CAMBIO_OFICIAL 
		        	 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
		        	 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO 
		        	   AND TIPC.MONEDA = SA.MONEDA 
		        	   AND TIPC.TZ_LOCK = 0)
		        WHEN SOS.SUBSISTEMA IN (''PR'',''PF'') THEN 
		            (SELECT CASE WHEN MOV.OPERACION = 3015 THEN TIPC.TIPO_CAMBIO_COMPRA 
								 WHEN MOV.OPERACION = 3016 THEN TIPC.TIPO_CAMBIO_VENTA 
								 ELSE TIPC.TIPO_CAMBIO_COMPRA END
					 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
					 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO
					    AND TIPC.MONEDA = SA.MONEDA 
					    AND TIPC.TZ_LOCK = 0)
				WHEN SOS.SUBSISTEMA = ''CE'' THEN CB.TIPO_CAMBIO
					/*(SELECT TIPO_CAMBIO 
					 FROM GRL_OPE_CAMBIO WITH (NOLOCK) 
					 WHERE SUCURSAL = MOV.SUCURSAL 
					 AND FECHA_PROCESO = MOV.FECHAPROCESO 
					 AND ASIENTO = MOV.ASIENTO
					 AND TZ_LOCK = 0)*/																		 
		   ELSE 0 END) END),0) AS COTIZACION,
		--20
		(CASE WHEN ASI.EXTORNO = 1 THEN ''SI''ELSE ''NO'' END)  AS REVERSADA,
		--21
		'''' AS OPER_ID_BIC_SWIFT,
		--22
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
				  THEN CONVERT(VARCHAR,VMOV.NRO_DOC_I)
		     WHEN SOS.TIPOPERACION IN (101,103) THEN 
		     								ISNULL(CONVERT(VARCHAR,VT.BEN_NRO_DOC),
													     (SELECT (CLIX.NUMERODOC) FROM MOVIMIENTOS_CONTABLES MOVX WITH (NOLOCK)
													      INNER JOIN SALDOS SAX ON SAX.JTS_OID = MOVX.SALDO_JTS_OID
													      INNER JOIN VW_CLI_X_DOC CLIX WITH (NOLOCK) ON CLIX.CODIGOCLIENTE = MOVX.CLIENTE_ORIGEN
														WHERE MOVX.FECHAPROCESO = MOV.FECHAPROCESO
														  AND MOVX.ASIENTO = MOV.ASIENTO
														  AND MOVX.SUCURSAL = MOV.SUCURSAL
														  AND MOVX.ORDINAL = 0
														  AND MOVX.COD_TRANSACCION <> MOV.COD_TRANSACCION))
			ELSE '''' END
		),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
		--23
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		          THEN (CASE WHEN VMOV.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
			ELSE '''' END
		),2) AS RTE_OPE_FON_TIPO_PERSONA,
		--24
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN CONCAT(VMOV.APELLIDO_I,'' '', VMOV.NOMBRE_I)
			ELSE '''' END
		),100) AS RTE_OPE_FON_DENOMINACION,
		--25
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN VMOV.APELLIDO_I
			ELSE '''' END
		),50)  AS RTE_OPE_FON_APELLIDOS,
		--26
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN VMOV.NOMBRE_I
			ELSE '''' END
		),50) AS RTE_OPE_FON_NOMBRES,
		--27
		(CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)  THEN ''96'' ELSE '''' END) AS RTE_OPE_FON_TIPODOC,
		--28
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
				  THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_I),3,8)
			ELSE '''' END
		),10)  AS RTE_OPE_FON_NUMDOC,
		--29
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN CONVERT(VARCHAR,VMOV.NRO_DOC_M)
			ELSE '''' END
		),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
		--30
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		          THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
			ELSE '''' END
		),2) AS RTE_TIT_FON_TIPO_PERSONA,
		--31
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN CONCAT(VMOV.APELLIDO_M,'' '', VMOV.NOMBRE_M)
			ELSE '''' END
		),100) AS RTE_TIT_FON_DENOMINACION,
		--32
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		        THEN  VMOV.APELLIDO_M
			ELSE '''' END
		),50) AS RTE_TIT_FON_APELLIDOS,
		--33
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		        THEN VMOV.NOMBRE_M
			ELSE '''' END
		),50) AS RTE_TIT_FON_NOMBRES,
		--34
		(
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''96''
								      WHEN VMOV.TIPO_PERSONA_M = ''J'' THEN ''80'' END)
			ELSE '''' END
		) AS RTE_TIT_FON_TIPODOC,
		--35
		LEFT((
		CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
		           THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),3,8)
								      WHEN VMOV.TIPO_PERSONA_M = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),1,10) END)
			ELSE '''' END
		),10) AS RTE_TIT_FON_NUMDOC,
		--36
		'''' AS RTI_TIPOPERSONA,
		--37
		'''' AS RTI_TIPOOPERACION_COMEX,
		--FECHAAPERTURACUENTA
		(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, MOV.FECHAVALOR  ,112))  
			  ELSE
			   CONVERT(NUMERIC,CONVERT(VARCHAR,SA.C1620 ,112)) END) AS FECHAAPERTURACUENTA,
		--CLIENTE
		SA.C1803 AS CODCLIENTE,
		SUC.SUCURSALBCRA AS SUCURSALSISCENCTA,
		--38
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''TITULAR'' END), 30) AS REL_FON_TIT,
		--39
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
		  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_I AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
																   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_I 
																     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
																     --AND VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
																     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_TIT,
		--40
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''OPERADOR'' END), 30) AS REL_FON_OPER,
		--41
		LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
		  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_M AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
																   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_M 
																     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
																   --VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
																     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_OPER,
		--
		SA.JTS_OID
		--SELECT MOV.*
		FROM MOVIMIENTOS_CONTABLES MOV WITH (NOLOCK)
		  INNER JOIN ASIENTOS ASI WITH (NOLOCK) ON ASI.FECHAPROCESO = MOV.FECHAPROCESO AND ASI.SUCURSAL = MOV.SUCURSAL AND ASI.ASIENTO = MOV.ASIENTO
		  INNER JOIN GRL_OPE_CAMBIO CB WITH (NOLOCK) ON CB.FECHA_PROCESO = MOV.FECHAPROCESO 
		  						AND CB.SUCURSAL = MOV.SUCURSAL 
		  						AND CB.ASIENTO = MOV.ASIENTO
		  						AND CB.CODIGO_CLIENTE = MOV.CLIENTE
		  INNER JOIN SOS_TRANSACCIONES SOS WITH (NOLOCK) ON SOS.CODTRANSACCION = MOV.COD_TRANSACCION AND SOS.OPERACION = MOV.OPERACION
		    AND SOS.SUBSISTEMA = ''CE''
		    AND ((SOS.PAGOSAINFORMAR = ''T'') OR
		         (SOS.PAGOSAINFORMAR = ''E'' AND MOV.CAJADIARIO = ''D'') OR
		         (SOS.PAGOSAINFORMAR = ''D'' AND MOV.CAJADIARIO <> ''C''))
		    AND ((ASI.EXTORNO = 0 AND (SOS.TIPO_MOVIMIENTO = MOV.DEBITOCREDITO
		          OR SOS.TIPO_MOVIMIENTO = ''A''))
		            OR ASI.EXTORNO = 1)
		  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOV.SUCURSAL
		  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.C1785 NOT IN (''5'',''8'') AND SA.JTS_OID = MOV.SALDO_JTS_OID AND SA.OPERACION = MOV.OPERACION_CUENTA
											 AND ((SA.TZ_LOCK < 300000000000000 OR SA.TZ_LOCK >= 400000000000000) 
												AND (SA.TZ_LOCK < 100000000000000 OR SA.TZ_LOCK >= 200000000000000)) 
											AND mov.SUCURSAL_CUENTA = SA.sucursal 
		  LEFT JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
		  LEFT JOIN VTA_TRANSFERENCIAS VT ON VT.FECHA_ASIENTO = MOV.FECHAPROCESO AND VT.NUMERO_ASIENTO = MOV.ASIENTO AND VT.SUCURSAL_ASIENTO = MOV.SUCURSAL
		WHERE MOV.FECHAPROCESO = @FECHA
		  AND MOV.CLIENTE <> 0
		  AND SOS.TZ_LOCK = 0
		  AND SUC.TZ_LOCK = 0
		  AND (MOV.NROCAJA <> 0 OR (MOV.NROCAJA = 0 AND MOV.OPERACION = 8620) OR (MOV.NROCAJA = 0 AND SOS.SUBSISTEMA = ''PF''))
		  AND SA.PRODUCTO <> 0
		  AND ASI.ESTADO = 77
		  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS X WITH (NOLOCK) 
		  				 WHERE X.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' 
		  				   AND X.ALFA_1 = SA.PRODUCTO
		  				   AND X.TZ_LOCK = 0)
		  AND NOT EXISTS(SELECT 1 FROM ASIENTOS_EXTORNADOS ASI WITH (NOLOCK) 
		  				 WHERE ASI.SUCURSAL = MOV.SUCURSAL 
		  				    AND ASI.FECHA_PROCESO = MOV.FECHAPROCESO
		                 	AND ASI.ASIENTO = MOV.ASIENTO
		                 	AND ASI.FECHA_PROCESO = ASI.FECHA_EXTORNO)
		  AND NOT EXISTS(SELECT 1 FROM CAJ_SOLICITUD_BAJA_ASIENTO BAJ 
		  				 WHERE BAJ.ASIENTO = MOV.ASIENTO
		  				   AND BAJ.SUCURSAL = MOV.SUCURSAL
		  				   AND BAJ.FECHAPROCESO = MOV.FECHAPROCESO
		  				   AND BAJ.ESTADO = ''C'')
		  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
		   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
		  					INNER JOIN CLI_PERSONASFISICAS NAT WITH(NOLOCK) ON P.NUMEROPERSONA = NAT.NUMEROPERSONAFISICA
		  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
		  				   AND NAT.SECTOR IN (6,7)
		  				   AND NAT.TZ_LOCK = 0
		  				   AND P.TZ_LOCK = 0
		  				   AND CLI.TZ_LOCK = 0)
		  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
		   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
		  					INNER JOIN CLI_PERSONASJURIDICAS JUR WITH(NOLOCK) ON P.NUMEROPERSONA = JUR.NUMEROPERSONAJURIDICA
		  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
		  				   AND JUR.SECTOR IN (6,7)
		  				   AND JUR.TZ_LOCK = 0
		  				   AND P.TZ_LOCK = 0
		  				   AND CLI.TZ_LOCK = 0)
	END	
	/*********************************
	      PRESTAMO
	**********************************/
	BEGIN 
	INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
		SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
		ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
		FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
		RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
		RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
		RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
		FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
		REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
	SELECT
	--1
	311 AS EMPRESA, 
	--2
	@FECHAPROCESO AS FECHADEINFORMACION,
	--3
	(CASE WHEN SOS.SUBSISTEMA IN (''PF'',''PR'')
	  THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR, SA.OPERACION),CONVERT(VARCHAR,SA.ORDINAL))
	  ELSE CONCAT(RIGHT(''0''+CONVERT(VARCHAR,SA.SUCURSAL),2), SOS.SUBSISTEMA, CONVERT(VARCHAR,MOV.CUENTA)) END)AS NUMERODECUENTA,
	--4
	LEFT(CONCAT(MOV.ASIENTO, CONVERT(VARCHAR,MOV.FECHAPROCESO,112), MOV.SUCURSAL, MOV.ORDINAL),22) AS NUMERODEOPERACION,
	--5
	LEFT(SOS.SUBSISTEMA,3) AS CLASEDECUENTA,
	--6
	SOS.TIPOPERACION  AS TIPODECUENTAUOPERACION,
	--7
	(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,SUC.SUCURSALBCRA) END) AS SUCURSALSISCEN,
	--8
	(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,MOV.SUCURSAL) END) AS SUCURSALINTERNA,
	--9
	(CASE WHEN SA.C1785 = 4 THEN CONVERT(VARCHAR, SA.C1621, 112) ELSE CONVERT(VARCHAR,MOV.FECHAPROCESO,112) END) AS FECHADELAOPERACION,
	--10
	(CASE WHEN MOV.MONEDA in (1,998,999) THEN
	 		 MOV.CAPITALREALIZADO 
		  ELSE 0 END) AS MONTOPESOS, 
	--11
	(CASE WHEN MOV.MONEDA NOT IN (1,998,999) THEN 
	   MOV.CAPITALREALIZADO
	   ELSE 0 END) AS ESPECIETRANSADACANTIDAD, 
	--12
	LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
	      WHERE M.C6399 = (CASE WHEN MOV.MONEDA IN (988,999) THEN 1 ELSE MOV.MONEDA END)
		    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
	--13
	'''' AS BANCOCORRESPONSALSWIFT,
	--14
	'''' AS BENEFICIARIOORDENANTEDELEXTE,
	--15
	'''' AS PAISDELBENEFICIARIOORDENANTE,
	--16
	(CASE WHEN mov.cajadiario=''C'' THEN ''EFSI'' ELSE ''EFNO'' END) AS DATOSADICIONALES,
	--17
	CONVERT(VARCHAR, MOV.FECHAVALOR,112) AS FECHAALTA,
	--18
	CONCAT(RIGHT(CONCAT(REPLICATE(''0'',4),SOS.OPERACION),4), SOS.SUBSISTEMA, RIGHT(CONCAT(REPLICATE(''0'',7), SOS.CODTRANSACCION),7)) AS CODIGOSTOPAZ,
	--19
	ISNULL((CASE WHEN (CASE WHEN MOV.MONEDA IN (988,999) THEN 1 ELSE MOV.MONEDA END) = 1 THEN 0 ELSE 
	  (CASE WHEN SOS.SUBSISTEMA IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN 
	        	(SELECT TIPC.TIPO_CAMBIO_OFICIAL 
	        	 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
	        	 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO 
	        	   AND TIPC.MONEDA = SA.MONEDA 
	        	   AND TIPC.TZ_LOCK = 0)
	        WHEN SOS.SUBSISTEMA IN (''PR'',''PF'') THEN 
	            (SELECT CASE WHEN MOV.OPERACION = 3015 THEN TIPC.TIPO_CAMBIO_COMPRA 
							 WHEN MOV.OPERACION = 3016 THEN TIPC.TIPO_CAMBIO_VENTA 
							 ELSE TIPC.TIPO_CAMBIO_COMPRA END
				 FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK) 
				 WHERE TIPC.FECHA_COTIZACION = MOV.FECHAPROCESO
				    AND TIPC.MONEDA = SA.MONEDA 
				    AND TIPC.TZ_LOCK = 0)
			WHEN SOS.SUBSISTEMA = ''CE'' THEN 
				(SELECT TIPO_CAMBIO 
				 FROM GRL_OPE_CAMBIO WITH (NOLOCK) 
				 WHERE SUCURSAL = MOV.SUCURSAL 
				 AND FECHA_PROCESO = MOV.FECHAPROCESO 
				 AND ASIENTO = MOV.ASIENTO
				 AND TZ_LOCK = 0)																			 
	   ELSE 0 END) END),0) AS COTIZACION,
	--20
	(CASE WHEN ASI.EXTORNO = 1 THEN ''SI''ELSE ''NO'' END)  AS REVERSADA,
	--21
	'''' AS OPER_ID_BIC_SWIFT,
	--22
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
			  THEN CONVERT(VARCHAR,VMOV.NRO_DOC_I)
		ELSE '''' END
	),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
	--23
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	          THEN (CASE WHEN VMOV.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
		ELSE '''' END
	),2) AS RTE_OPE_FON_TIPO_PERSONA,
	--24
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN CONCAT(VMOV.APELLIDO_I,'' '', VMOV.NOMBRE_I)
		ELSE '''' END
	),100) AS RTE_OPE_FON_DENOMINACION,
	--25
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN VMOV.APELLIDO_I
		ELSE '''' END
	),50)  AS RTE_OPE_FON_APELLIDOS,
	--26
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN VMOV.NOMBRE_I
		ELSE '''' END
	),50) AS RTE_OPE_FON_NOMBRES,
	--27
	(CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)  THEN ''96'' ELSE '''' END) AS RTE_OPE_FON_TIPODOC,
	--28
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
			  THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_I),3,8)
		ELSE '''' END
	),10)  AS RTE_OPE_FON_NUMDOC,
	--29
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN CONVERT(VARCHAR,VMOV.NRO_DOC_M)
		ELSE '''' END
	),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
	--30
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	          THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN VMOV.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
		ELSE '''' END
	),2) AS RTE_TIT_FON_TIPO_PERSONA,
	--31
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN CONCAT(VMOV.APELLIDO_M,'' '', VMOV.NOMBRE_M)
		ELSE '''' END
	),100) AS RTE_TIT_FON_DENOMINACION,
	--32
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	        THEN  VMOV.APELLIDO_M
		ELSE '''' END
	),50) AS RTE_TIT_FON_APELLIDOS,
	--33
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	        THEN VMOV.NOMBRE_M
		ELSE '''' END
	),50) AS RTE_TIT_FON_NOMBRES,
	--34
	(
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN ''96''
							      WHEN VMOV.TIPO_PERSONA_M = ''J'' THEN ''80'' END)
		ELSE '''' END
	) AS RTE_TIT_FON_TIPODOC,
	--35
	LEFT((
	CASE WHEN SOS.SUBSISTEMA IN (''CC'',''AC'') AND SOS.IND_RTE = ''S'' AND ((SOS.MTOMINIMO < MOV.CAPITALREALIZADO AND SOS.MTOMINIMO <> 0) OR SOS.MTOMINIMO = 0)
	           THEN (CASE WHEN VMOV.TIPO_PERSONA_M = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),3,8)
							      WHEN VMOV.TIPO_PERSONA_M = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,VMOV.NRO_DOC_M),1,10) END)
		ELSE '''' END
	),10) AS RTE_TIT_FON_NUMDOC,
	--36
	'''' AS RTI_TIPOPERSONA,
	--37
	'''' AS RTI_TIPOOPERACION_COMEX,
	--FECHAAPERTURACUENTA
	(CASE WHEN SOS.SUBSISTEMA = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, MOV.FECHAVALOR  ,112))  
		  ELSE
		   CONVERT(NUMERIC,CONVERT(VARCHAR,SA.C1620 ,112)) END) AS FECHAAPERTURACUENTA,
	--CLIENTE
	SA.C1803 AS CODCLIENTE,
	SUC.SUCURSALBCRA AS SUCURSALSISCENCTA,
	--38
	LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''TITULAR'' END), 30) AS REL_FON_TIT,
	--39
	LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
	  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_I AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
															   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_I 
															     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_I
															     --AND VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
															     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_TIT,
	--40
	LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE ''OPERADOR'' END), 30) AS REL_FON_OPER,
	--41
	LEFT((CASE WHEN SOS.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
	  														   --INNER JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON V.TIPODOCUMENTO = VMOV.TIPO_DOC_M AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
															   WHERE V.TIPODOCUMENTO = VMOV.TIPO_DOC_M 
															     AND V.NUMERODOCUMENTO= VMOV.NRO_DOC_M
															   --VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
															     AND  V.CODIGOCLIENTE = SA.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_OPER,
	--
	SA.JTS_OID
	--SELECT MOV.*
	FROM MOVIMIENTOS_CONTABLES MOV WITH (NOLOCK)
	  INNER JOIN ASIENTOS ASI WITH (NOLOCK) ON ASI.FECHAPROCESO = MOV.FECHAPROCESO AND ASI.SUCURSAL = MOV.SUCURSAL AND ASI.ASIENTO = MOV.ASIENTO
	  INNER JOIN SOS_TRANSACCIONES SOS WITH (NOLOCK) ON SOS.CODTRANSACCION = MOV.COD_TRANSACCION AND SOS.OPERACION = MOV.OPERACION
	    AND SOS.SUBSISTEMA = ''PR''
	    AND ((SOS.PAGOSAINFORMAR = ''T'') OR
	         (SOS.PAGOSAINFORMAR = ''E'' AND MOV.CAJADIARIO = ''C'') OR
	         (SOS.PAGOSAINFORMAR = ''D'' AND MOV.CAJADIARIO <> ''C''))
	    AND ((ASI.EXTORNO = 0 AND (SOS.TIPO_MOVIMIENTO = MOV.DEBITOCREDITO
		          OR SOS.TIPO_MOVIMIENTO = ''A''))
		            OR ASI.EXTORNO = 1)
	  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOV.SUCURSAL
	  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.C1785 IN (''5'',''8'') AND mov.SUCURSAL_CUENTA =SA.sucursal 
	    AND CONVERT(VARCHAR,SA.OPERACION) = (CASE WHEN CHARINDEX('':'', MOV.CONCEPTO) > 0 THEN SUBSTRING(MOV.CONCEPTO, CHARINDEX('':'', MOV.CONCEPTO)+2, 12) ELSE CONVERT(VARCHAR,MOV.OPERACION_CUENTA) END)
		AND (CASE WHEN SA.C1785 IN (''5'',''8'') THEN ''PR'' END) =  SOS.SUBSISTEMA
		AND ((SA.TZ_LOCK < 300000000000000 OR SA.TZ_LOCK >= 400000000000000) 
			AND (SA.TZ_LOCK < 100000000000000 OR SA.TZ_LOCK >= 200000000000000)) 
	  LEFT JOIN VTA_CUMPLIMIENTO VMOV WITH (NOLOCK) ON VMOV.SUCURSAL = MOV.SUCURSAL AND VMOV.ASIENTO = MOV.ASIENTO AND VMOV.FECHA_PROCESO = MOV.FECHAPROCESO
	WHERE MOV.FECHAPROCESO = @FECHA
	  AND MOV.CLIENTE <> 0
	  AND SOS.TZ_LOCK = 0
	  AND SUC.TZ_LOCK = 0
	  AND ASI.ESTADO = 77
	  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS X WITH (NOLOCK) 
	  				 WHERE X.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' 
	  				   AND X.ALFA_1 = SA.PRODUCTO
	  				   AND X.TZ_LOCK = 0)
	  AND NOT EXISTS(SELECT 1 FROM ASIENTOS_EXTORNADOS ASI WITH (NOLOCK)
		  				 WHERE ASI.SUCURSAL = MOV.SUCURSAL 
		  				    AND ASI.FECHA_PROCESO = MOV.FECHAPROCESO
		                 	AND ASI.ASIENTO = MOV.ASIENTO
		                 	AND ASI.FECHA_PROCESO = ASI.FECHA_EXTORNO)
      AND NOT EXISTS(SELECT 1 FROM CAJ_SOLICITUD_BAJA_ASIENTO BAJ 
		  				 WHERE BAJ.ASIENTO = MOV.ASIENTO
		  				   AND BAJ.SUCURSAL = MOV.SUCURSAL
		  				   AND BAJ.FECHAPROCESO = MOV.FECHAPROCESO
		  				   AND BAJ.ESTADO = ''C'')
	  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
	   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
	  					INNER JOIN CLI_PERSONASFISICAS NAT WITH(NOLOCK) ON P.NUMEROPERSONA = NAT.NUMEROPERSONAFISICA
	  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
	  				   AND NAT.SECTOR IN (6,7)
	  				   AND NAT.TZ_LOCK = 0
	  				   AND P.TZ_LOCK = 0
	  				   AND CLI.TZ_LOCK = 0)
	  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
	   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
	  					INNER JOIN CLI_PERSONASJURIDICAS JUR WITH(NOLOCK) ON P.NUMEROPERSONA = JUR.NUMEROPERSONAJURIDICA
	  				 WHERE CLI.CODIGOCLIENTE = SA.C1803
	  				   AND JUR.SECTOR IN (6,7)
	  				   AND JUR.TZ_LOCK = 0
	  				   AND P.TZ_LOCK = 0
	  				   AND CLI.TZ_LOCK = 0)
	END 
	/**********************************
	   TC - TARJETA DE CREDITO
	**********************************/
	BEGIN 
	INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
		SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
		ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
		FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
		RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
		RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
		RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
		FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
		REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
	SELECT
	--1
	311 AS EMPRESA, 
	--2
	@FECHAPROCESO AS FECHADEINFORMACION,
	--3
	CONCAT(RIGHT(''0''+CONVERT(VARCHAR, B.SUC_CUENTA_COBRO),2), TRA.SUBSISTEMA, CONVERT(VARCHAR, B.TIPO_TJC), CONVERT(VARCHAR,MOV.USUARIO)) AS NUMERODECUENTA,
	--4
	(LEFT(CONCAT(MOVC.ASIENTO, CONVERT(VARCHAR,MOVC.FECHAPROCESO,112), MOVC.SUCURSAL, MOVC.ORDINAL),22)) AS NUMERODEOPERACION,
	--5
	TRA.SUBSISTEMA AS CLASEDECUENTA,
	--6
	TRA.TIPOPERACION AS TIPODECUENTAUOPERACION,
	--7
	CONVERT(VARCHAR,SUC.SUCURSALBCRA) AS SUCURSALSISCEN,
	--8
	CONVERT(VARCHAR,B.SUC_CUENTA_COBRO) AS SUCURSALINTERNA,
	--9
	CONVERT(VARCHAR,MOV.FECHA,112) AS FECHADELAOPERACION,
	--10
	MOV.PAGO_MN AS MONTOPESOS,
	--11
	MOV.PAGO_ME AS ESPECIETRANSADACANTIDAD,
	--12
	LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
	      WHERE M.C6399 = (CASE WHEN MOVC.MONEDA IN (988,999) THEN 1 ELSE MOVC.MONEDA END)
		    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
	--13
	'''' AS BANCOCORRESPONSALSWIFT,
	--14
	'''' AS BENEFICIARIOORDENANTEDELEXTE,
	--15
	'''' AS PAISDELBENEFICIARIOORDENANTE,
	--16
	(CASE WHEN MOV.CANAL IN (1, 4, 5) THEN ''EFSI'' ELSE ''EFNO'' END) AS DATOSADICIONALES,
	--17
	CONVERT(VARCHAR, MOV.FECHA,112) AS FECHAALTA,
	--18
	--CONVERT(VARCHAR(5),TRA.CODTRANSACCION) AS CODIGOSTOPAZ,
	CONCAT(RIGHT(CONCAT(REPLICATE(''0'',4),TRA.OPERACION),4), TRA.SUBSISTEMA, RIGHT(CONCAT(REPLICATE(''0'',7), TRA.CODTRANSACCION),7)) AS CODIGOSTOPAZ,
	--19
	(CASE WHEN MOV.PAGO_MN > 0 AND MOV.PAGO_ME = 0 THEN 0
	  ELSE (SELECT TIPC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK)
	    WHERE TIPC.FECHA_COTIZACION = MOVC.FECHAPROCESO AND TIPC.MONEDA = MOVC.MONEDA AND TIPC.TZ_LOCK = 0)
	END) AS COTIZACION,
	--20
	(CASE WHEN ASI.EXTORNO = 1 THEN ''SI''ELSE ''NO'' END)  AS REVERSADA,
	--21
	'''' AS OPER_ID_BIC_SWIFT,
	--22
	'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
	--23
	'''' AS RTE_OPE_FON_TIPO_PERSONA,
	--24
	''''  AS RTE_OPE_FON_DENOMINACION,
	--25
	''''   AS RTE_OPE_FON_APELLIDOS,
	--26
	''''  AS RTE_OPE_FON_NOMBRES,
	--27
	'''' AS RTE_OPE_FON_TIPODOC,
	--28
	''''  AS RTE_OPE_FON_NUMDOC,
	--29
	''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
	--30
	''''  AS RTE_TIT_FON_TIPO_PERSONA,
	--31
	''''  AS RTE_TIT_FON_DENOMINACION,
	--32
	''''  AS RTE_TIT_FON_APELLIDOS,
	--33
	''''  AS RTE_TIT_FON_NOMBRES,
	--34
	'''' AS RTE_TIT_FON_TIPODOC,
	--35
	'''' AS RTE_TIT_FON_NUMDOC,
	--36
	'''' AS RTI_TIPOPERSONA,
	--37
	'''' AS RTI_TIPOOPERACION_COMEX,
	--FECHAAPERTURACUENTA
	CONVERT(NUMERIC,CONVERT(VARCHAR, MOV.FECHA,112)) AS FECHAAPERTURACUENTA, --CAMPO USUARIO EN EL 1.16.4 SOS - CUENTAS
	--CLIENTE
	B.CLIENTE AS CODCLIENTE,
	--SUCURSAL BCRA
	(SELECT SUCX.SUCURSALBCRA FROM SOS_SUCURSALES SUCX WITH (NOLOCK) WHERE SUCX.SUCURSAL = B.SUC_CUENTA_COBRO AND SUCX.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
	--38
	'''' AS REL_FON_TIT,
	--39
	''NO'' AS REL_PRO_TIT,
	--40
	'''' AS REL_FON_OPER,
	--41
	''NO'' AS REL_PRO_OPER,
	--
	SA.JTS_OID
	--SELECT MOV.* 
	FROM TJC_HISTORICO_PAGOS MOV WITH (NOLOCK)
	  INNER JOIN MOVIMIENTOS_CONTABLES MOVC WITH (NOLOCK) ON MOVC.FECHAPROCESO = MOV.FECHA AND MOVC.ASIENTO = MOV.ASIENTO
	  	/*AND MOVC.OPERACION = 2854*/ AND MOVC.SUCURSAL_CUENTA = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 400)
	  INNER JOIN ASIENTOS ASI WITH (NOLOCK) ON ASI.FECHAPROCESO = MOVC.FECHAPROCESO AND ASI.SUCURSAL = MOVC.SUCURSAL AND ASI.ASIENTO = MOVC.ASIENTO
	  INNER JOIN SOS_TRANSACCIONES TRA WITH (NOLOCK) ON TRA.CODTRANSACCION = MOVC.COD_TRANSACCION 
	                           AND TRA.OPERACION = MOVC.OPERACION
	                           AND ((TRA.PAGOSAINFORMAR = ''E'' AND MOV.CANAL IN (1,4,5)) OR
	                                (TRA.PAGOSAINFORMAR = ''D'' AND MOV.CANAL NOT IN (1,4,5)) OR
	                                (TRA.PAGOSAINFORMAR = ''T''))
	                           AND ((ASI.EXTORNO = 0 AND (TRA.TIPO_MOVIMIENTO = MOVC.DEBITOCREDITO
										  OR TRA.TIPO_MOVIMIENTO = ''A''))
								     OR ASI.EXTORNO = 1)
	  INNER JOIN TJC_MAESTRO_USUARIO B WITH (NOLOCK) ON B.ADMINISTRADORA = MOV.ADMINISTRADORA AND B.USUARIO = MOV.USUARIO
	  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOVC.SUCURSAL
	  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.JTS_OID = MOV.JTS_SALDO_TARJETA --AND movc.SUCURSAL_CUENTA = SA.sucursal 
	    AND ((SA.TZ_LOCK < 300000000000000 OR SA.TZ_LOCK >= 400000000000000) 
			AND (SA.TZ_LOCK < 100000000000000 OR SA.TZ_LOCK >= 200000000000000)) 
	WHERE MOV.FECHA = @FECHA
	  AND MOV.TZ_LOCK = 0
	  AND SUC.TZ_LOCK = 0
	  AND B.TZ_LOCK = 0
	  AND ASI.ESTADO = 77
	  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS X WITH (NOLOCK) WHERE X.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' AND X.ALFA_1 = SA.PRODUCTO)
	  AND NOT EXISTS(SELECT 1 FROM ASIENTOS_EXTORNADOS ASI WITH (NOLOCK)
		  				 WHERE ASI.SUCURSAL = MOVC.SUCURSAL 
		  				    AND ASI.FECHA_PROCESO = MOVC.FECHAPROCESO
		                 	AND ASI.ASIENTO = MOVC.ASIENTO
		                 	AND ASI.FECHA_PROCESO = ASI.FECHA_EXTORNO)
	  AND NOT EXISTS(SELECT 1 FROM CAJ_SOLICITUD_BAJA_ASIENTO BAJ 
		  				 WHERE BAJ.ASIENTO = MOVC.ASIENTO
		  				   AND BAJ.SUCURSAL = MOVC.SUCURSAL
		  				   AND BAJ.FECHAPROCESO = MOVC.FECHAPROCESO
		  				   AND BAJ.ESTADO = ''C'')
	  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
	   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
	  					INNER JOIN CLI_PERSONASFISICAS NAT WITH(NOLOCK) ON P.NUMEROPERSONA = NAT.NUMEROPERSONAFISICA
	  				 WHERE CLI.CODIGOCLIENTE = MOV.CLIENTE
	  				   AND NAT.SECTOR IN (6,7))
	  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES CLI WITH(NOLOCK)
	   					INNER JOIN CLI_CLIENTEPERSONA P WITH(NOLOCK) ON P.CODIGOCLIENTE = CLI.CODIGOCLIENTE
	  					INNER JOIN CLI_PERSONASJURIDICAS JUR WITH(NOLOCK) ON P.NUMEROPERSONA = JUR.NUMEROPERSONAJURIDICA
	  				 WHERE CLI.CODIGOCLIENTE = MOV.CLIENTE
	  				   AND JUR.SECTOR IN (6,7))
	END
	/**********************************
	    MOVIMIENTOS EXTERNOS O TRANSFERENCIAS AL/DEL EXTERIOR
	**********************************/
	BEGIN 
	INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
		SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
		ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
		FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
		RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
		RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
		RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
		FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
		REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
	SELECT
	--1
	311 AS EMPRESA, 
	--2
	@FECHAPROCESO AS FECHADEINFORMACION,
	--3
	CONCAT(RIGHT(''0''+CONVERT(VARCHAR, MOV.CODSUCURSAL),2), ''ME'', CONVERT(VARCHAR,MOV.CUENTA)) AS NUMERODECUENTA,
	--4
	MOV.NUMBOLETO + MOV.FECINGRESO + MOV.CODSUCURSAL  + MOV.OPERACION AS NUMERODEOPERACION,
	--5
	''ME'' AS CLASEDECUENTA,
	--6
	RIGHT(MOV.CODOPERACIONMOV,3) AS TIPODECUENTAUOPERACION,
	--7
	''0'' AS SUCURSALSISCEN,
	--8
	CONVERT(VARCHAR,MOV.CODSUCORIGENOPE) AS SUCURSALINTERNA,
	--9
	CONVERT(VARCHAR,MOV.FECINGRESO,112) AS FECHADELAOPERACION,
	--10
	(CASE WHEN MOV.CODMONEDA IN (1,998,999) THEN MOV.IMPORTEOPE ELSE 0 END) AS MONTOPESOS,
	--11
	(CASE WHEN MOV.CODMONEDA NOT IN (1,998,999) THEN MOV.IMPORTEOPE ELSE 0 END)  AS ESPECIETRANSADACANTIDAD,
	--12
	LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
	      WHERE M.C6399 = (CASE WHEN MOV.CODMONEDA IN (988,999) THEN 1 ELSE MOV.CODMONEDA END)
		    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
	--13
	MOV.BANCOCORRESP AS BANCOCORRESPONSALSWIFT,
	--14
	MOV.BENEFORDENEXT AS BENEFICIARIOORDENANTEDELEXTE,
	--15
	(SELECT PAIS.CODIGOSWIFT FROM CLI_PAISES PAIS WITH (NOLOCK) WHERE PAIS.CODIGOPAIS = MOV.CODPAISBENEF AND PAIS.TZ_LOCK = 0) AS PAISDELBENEFICIARIOORDENANTE,
	--16
	'''' AS DATOSADICIONALES,
	--17
	CONVERT(VARCHAR, MOV.FECINGRESO,112) AS FECHAALTA,
	--18
	CONCAT(''ME'',MOV.CODCONCEPTO) AS CODIGOSTOPAZ,
	--19
	(CASE WHEN MOV.CODMONEDA = 1 THEN 0
	  ELSE 
	   (SELECT TIPC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK)
	    WHERE TIPC.FECHA_COTIZACION = CONVERT(DATE,CONVERT(VARCHAR, MOV.FECINGRESO,103)) AND TIPC.MONEDA = MOV.CODMONEDA AND TIPC.TZ_LOCK = 0)
	END)
	  AS COTIZACION,
	--20
	(CASE WHEN MOV.MARCAREVERSADO = 1 THEN ''SI'' ELSE ''NO'' END) AS REVERSADA,
	--21
	CONCAT(CONCAT(REPLICATE(''0'',4),MOV.CODSUCURSAL), MOV.CODSISTEMA, CONCAT(REPLICATE(''0'',11),MOV.OPERACION), 
	      CONCAT(REPLICATE('' '',11),MOV.CODOPERACIONMOV), CONCAT(REPLICATE(''0'',20),MOV.NUMBOLETO), MOV.FECINGRESO) AS OPER_ID_BIC_SWIFT,
	--22
	'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
	--23
	'''' AS RTE_OPE_FON_TIPO_PERSONA,
	--24
	''''  AS RTE_OPE_FON_DENOMINACION,
	--25
	''''   AS RTE_OPE_FON_APELLIDOS,
	--26
	''''  AS RTE_OPE_FON_NOMBRES,
	--27
	'''' AS RTE_OPE_FON_TIPODOC,
	--28
	''''  AS RTE_OPE_FON_NUMDOC,
	--29
	''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
	--30
	''''  AS RTE_TIT_FON_TIPO_PERSONA,
	--31
	''''  AS RTE_TIT_FON_DENOMINACION,
	--32
	''''  AS RTE_TIT_FON_APELLIDOS,
	--33
	''''  AS RTE_TIT_FON_NOMBRES,
	--34
	'''' AS RTE_TIT_FON_TIPODOC,
	--35
	'''' AS RTE_TIT_FON_NUMDOC,
	--36
	MOV.TIPOPERSBENEF AS RTI_TIPOPERSONA,
	--37
	CONVERT(VARCHAR,MOV.OPERACION) AS RTI_TIPOOPERACION_COMEX,
	--FECHAAPERTURACUENTA
	CONVERT(NUMERIC,CONVERT(VARCHAR, MOV.FECINGRESO,112)) AS FECHAAPERTURACUENTA, --CAMPO USUARIO EN EL 1.16.4 SOS - CUENTAS
	--CLIENTE
	C.CODCLIENTE AS CODCLIENTE,
	--SUCURSAL BCRA
	(SELECT SUC.SUCURSALBCRA FROM SOS_SUCURSALES BX WITH (NOLOCK) WHERE BX.SUCURSAL = B.CODSUCURSAL AND BX.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
	--38
	'''' AS REL_FON_TIT,
	--39
	''NO'' AS REL_PRO_TIT,
	--40
	'''' AS REL_FON_OPER,
	--41
	''NO'' AS REL_PRO_OPER,
	--
	NULL AS JTS_OID
	--SELECT * 
	FROM ITF_I2000_MOVS_HIST MOV WITH (NOLOCK)
	  INNER JOIN ITF_I2000_CUENTAS_HIST B WITH (NOLOCK) ON B.CODSUCURSAL = MOV.CODSUCURSAL AND B.CODSISTEMA = MOV.CODSISTEMA AND B.NUMCUENTA = MOV.CUENTA
	  INNER JOIN ITF_I2000_CLIENTES_HIST C WITH (NOLOCK) ON C.TIPODOC = B.TIPODOCUMENTO AND C.NUMDOC = B.NUMDOCUMENTO
	  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOV.CODSUCURSAL
	  INNER JOIN SOS_TRANSACCIONES TRX WITH (NOLOCK) ON TRX.SUBSISTEMA = ''ME'' AND TRX.TIPOPERACION = RIGHT(MOV.CODOPERACIONMOV,3)
	WHERE MOV.FECINGRESO = @FECHA
	  AND SUC.TZ_LOCK = 0
	  AND TRX.TZ_LOCK = 0
	END
	/**********************************
	    TITULOS UNITRADE
	**********************************/
	BEGIN 
	INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
		SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
		ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
		FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
		RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
		RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
		RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
		FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
		REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
	SELECT
	--1
	311 AS EMPRESA, 
	--2
	@FECHAPROCESO AS FECHADEINFORMACION,
	--3
	CONCAT(RIGHT(''0''+CONVERT(VARCHAR, SA.SUCURSAL),2), ''TT'', CONVERT(VARCHAR,SA.CUENTA)) AS NUMERODECUENTA,
	--4
	CONCAT(MOV.FECHA_INFORMACION, MOV.NUMERO_MINUTA) AS NUMERODEOPERACION,
	--5
	''TT'' AS CLASEDECUENTA,
	--6
	MOV.CODIGO_OPERACION_BCRA AS TIPODECUENTAUOPERACION,
	--7
	SUC.SUCURSALBCRA AS SUCURSALSISCEN,
	--8
	CONVERT(VARCHAR,MOV.SUCURSAL_OPERACION) AS SUCURSALINTERNA,
	--9
	MOV.FECHA_OPERACION AS FECHADELAOPERACION,
	--10
	(CASE WHEN MOV.MONEDA_OPERACION_ORIGEN IN (1,998,999) THEN (CONVERT(NUMERIC(15,2), MOV.IMPORTE_MONEDA_ORIGINAL)/100) ELSE 0 END) AS MONTOPESOS,
	--11
	(CASE WHEN MOV.MONEDA_OPERACION_ORIGEN NOT IN (1,998,999) THEN (CONVERT(NUMERIC(15,2), MOV.IMPORTE_MONEDA_ORIGINAL)/100) ELSE 0 END)  AS ESPECIETRANSADACANTIDAD,
	--12
	LEFT((SELECT M.C6402 FROM MONEDAS M WITH (NOLOCK) 
	      WHERE M.C6399 = (CASE WHEN MOV.MONEDA_OPERACION_ORIGEN IN (988,999) THEN 1 ELSE MOV.MONEDA_OPERACION_ORIGEN END)
		    AND M.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
	--13
	'''' AS BANCOCORRESPONSALSWIFT,
	--14
	'''' AS BENEFICIARIOORDENANTEDELEXTE,
	--15
	'''' AS PAISDELBENEFICIARIOORDENANTE,
	--16
	MOV.TIPO_ESPECIE AS DATOSADICIONALES,
	--17
	MOV.FECHA_OPERACION AS FECHAALTA,
	--18
	'''' AS CODIGOSTOPAZ,
	--19
	(CASE WHEN MOV.MONEDA_OPERACION_ORIGEN = 1 THEN 0
	  ELSE 
	   (SELECT TIPC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TIPC WITH (NOLOCK)
	    WHERE TIPC.FECHA_COTIZACION = CONVERT(DATE,CONVERT(VARCHAR, MOV.FECHA_OPERACION,103)) AND TIPC.MONEDA = MOV.MONEDA_OPERACION_ORIGEN AND TIPC.TZ_LOCK = 0)
	END)
	  AS COTIZACION,
	--20
	(CASE WHEN MOV.ACCION IN (''REVERSADO'',''ANULADO'') THEN ''SI'' ELSE ''NO'' END) AS REVERSADA,
	--21
	'''' AS OPER_ID_BIC_SWIFT,
	--22
	'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
	--23
	'''' AS RTE_OPE_FON_TIPO_PERSONA,
	--24
	''''  AS RTE_OPE_FON_DENOMINACION,
	--25
	''''   AS RTE_OPE_FON_APELLIDOS,
	--26
	''''  AS RTE_OPE_FON_NOMBRES,
	--27
	'''' AS RTE_OPE_FON_TIPODOC,
	--28
	''''  AS RTE_OPE_FON_NUMDOC,
	--29
	''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
	--30
	''''  AS RTE_TIT_FON_TIPO_PERSONA,
	--31
	''''  AS RTE_TIT_FON_DENOMINACION,
	--32
	''''  AS RTE_TIT_FON_APELLIDOS,
	--33
	''''  AS RTE_TIT_FON_NOMBRES,
	--34
	'''' AS RTE_TIT_FON_TIPODOC,
	--35
	'''' AS RTE_TIT_FON_NUMDOC,
	--36
	'''' AS RTI_TIPOPERSONA,
	--37
	'''' AS RTI_TIPOOPERACION_COMEX,
	--FECHAAPERTURACUENTA
	CONVERT(NUMERIC,CONVERT(VARCHAR,SA.C1620 ,112)) AS FECHAAPERTURACUENTA, --CAMPO USUARIO EN EL 1.16.4 SOS - CUENTAS
	--CLIENTE
	SA.C1803 AS CODCLIENTE,
	--SUCURSAL BCRA
	(SELECT SUC.SUCURSALBCRA FROM SOS_SUCURSALES BX WITH (NOLOCK) WHERE BX.SUCURSAL = MOV.SUCURSAL_CUENTA_PARTE AND BX.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
	--38
	'''' AS REL_FON_TIT,
	--39
	''NO'' AS REL_PRO_TIT,
	--40
	'''' AS REL_FON_OPER,
	--41
	''NO'' AS REL_PRO_OPER,
	--
	SA.JTS_OID AS JTS_OID
	--SELECT * 
	FROM ITF_UNTD_IMPUESTOS MOV WITH (NOLOCK)  
	  INNER JOIN SOS_SUCURSALES SUC WITH (NOLOCK) ON SUC.SUCURSAL = MOV.SUCURSAL_OPERACION
	  INNER JOIN SOS_TRANSACCIONES TRX WITH (NOLOCK) ON TRX.SUBSISTEMA = ''TT'' AND TRX.TIPOPERACION = MOV.CODIGO_OPERACION_BCRA
	  INNER JOIN REL_CLIENTE_CTA_COMITENTE CTA WITH (NOLOCK) ON CTA.CUENTA = MOV.NUMERO_CUENTA_PARTE
	  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.CUENTA = CTA.CUENTA AND SA.sucursal = mov.SUCURSAL_CUENTA_PARTE AND sa.c1785 = 1
	    AND ((SA.TZ_LOCK < 300000000000000 OR SA.TZ_LOCK >= 400000000000000) 
			AND (SA.TZ_LOCK < 100000000000000 OR SA.TZ_LOCK >= 200000000000000)) 
	WHERE MOV.FECHA_INFORMACION = @FECHA
	  AND SUC.TZ_LOCK = 0
	  AND TRX.TZ_LOCK = 0
	END  
	
	END TRY
	BEGIN CATCH
	
		SET @MSG_ERROR = ERROR_PROCEDURE() + '' '' + CONVERT(VARCHAR,ERROR_NUMBER()) + '' '' + ERROR_MESSAGE();
		    
	END CATCH
END
')