EXECUTE('
ALTER PROCEDURE dbo.SP_CONTROL_GYF_GRUPO
@GRUPO NUMERIC(12),
@IMPORTE_SOLICITUD NUMERIC(15,2),
@EXCLUSION VARCHAR(1),
@CON_GTIA VARCHAR(1),
@CLIENTE NUMERIC(12,0),
@EXCLUIDO VARCHAR (1),
@LIMITE_GRAD NUMERIC(15,2),
@TRAMO_SIN_G_B NUMERIC(15,2),
@TRAMO_CON_G_B NUMERIC(15,2),
@RPC_CLIENTE NUMERIC(18,2),
@PERSONA NUMERIC(12),
@EXCEDE_GRADUACION VARCHAR(1) OUTPUT,
@EXCEDE_FRACCIONAMIENTO VARCHAR(1) OUTPUT,
@IMPORTE_SING_GRUPO NUMERIC (15,2) OUTPUT,
@IMPORTE_CONG_GRUPO NUMERIC (15,2) OUTPUT,
@TOTAL_DEUDA_GRUPO NUMERIC (15,2) OUTPUT,
@EXCLUSIONES_GRUPALES_GRADUACION NUMERIC (15,2) OUTPUT,
@IMPORTE_A_EVALUAR NUMERIC (15,2) OUTPUT,
@RESULTADO_GRADUACION VARCHAR(200) OUTPUT,
@RESULTADO_FRACCIONAMIENTO VARCHAR(200) OUTPUT
AS 
BEGIN
--VARIABLES QUE SUMAN EXCLUSIONES DEL GRUPO
DECLARE @EXC_GRUPO_CON_G NUMERIC (15,2); 
DECLARE @EXC_GRUPO_SIN_G NUMERIC (15,2);
--EXCLUSIONES DEL GRUPO GRAL
DECLARE @EXCLUSION_GRUPOCLIENTE_G NUMERIC (15,2);
DECLARE @EXCLUSION_GRUPOASIST_G NUMERIC (15,2);
DECLARE @EXCLUSION_GRUPOPROD_G NUMERIC (15,2);
DECLARE @TOTAL_DEUDA_GRUPO_F NUMERIC (15,2);
DECLARE @TOPE_ANALISIS NUMERIC(15,2);
DECLARE @TRAMO_SIN_G   NUMERIC(15,2); 
DECLARE @TRAMO_CON_G  NUMERIC(15,2);
DECLARE @TOT_CONTROL_GRAD NUMERIC(15,2);
DECLARE @DEUDA_TOTAL NUMERIC(18,2);
DECLARE @DEUDA_TOTAL_IR NUMERIC(18,2);
--- Tabla auxiliar de deudas
DECLARE @TABLA_ASISTENCIAS TABLE (CLIENTE NUMERIC(12), JTS_ASISTENCIA NUMERIC(10),
IMPORTE_DEUDA NUMERIC(15,2), TIENE_GARANTIA VARCHAR(1), TIPO_GARANTIA NUMERIC(2),
PRODUCTO NUMERIC(5), FAMILIA NUMERIC(10), PERSONA NUMERIC(12));
---LECTURA Y GRABADO EN TABLA TEMPORAL CLIENTE X CLIENTE

BEGIN
DECLARE @TBL_AUX TABLE (
	 PERSONA NUMERIC(12),
     CLIENTE NUMERIC(12),
     DEUDA_TOTAL NUMERIC(20,2),
     DEUDA_CON_G NUMERIC(20,2),
     DEUDA_SIN_G NUMERIC(20,2),
     EXCLUSION_CLI_GRAD NUMERIC (20,2),
     EXCLUSION_ASIST_GRAD NUMERIC (20,2),
     EXCLUSION_PROD_GRAD NUMERIC (20,2),
     EXCLUSION_GAR_GRAD NUMERIC (20,2),
     EXCLUSION_DESC_GRAD NUMERIC(20,2),
     TOT_CONTROL_GRAD NUMERIC (20,2),
     TRAMO_SIN_G NUMERIC (20,2),
     TRAMO_CON_G NUMERIC (20,2),
     EXCEDIDO_GRAD VARCHAR(1),
     EXCEDIDO_FRACC VARCHAR (1)
    )
   
--- Tabla auxiliar clientes - persona

DECLARE @GRUPO_PERSONAS TABLE (CLIENTE NUMERIC(12), PERSONA NUMERIC(12), GRUPO NUMERIC(12))

INSERT INTO @GRUPO_PERSONAS
SELECT GE.CODIGOCLIENTE, CP.NUMEROPERSONA, GE.CODIGOGRUPOECONOMICO
FROM CLI_GRUPOSECONOMICOSCLIENTE GE WITH(NOLOCK)
INNER JOIN CLI_CLIENTEPERSONA CP WITH(NOLOCK) ON CP.TZ_LOCK = 0 AND CP.CODIGOCLIENTE = GE.CODIGOCLIENTE AND CP.TITULARIDAD = ''T''
WHERE GE.CODIGOGRUPOECONOMICO = @GRUPO AND GE.TZ_LOCK = 0


--- Inserta en tabla auxiliar

	INSERT INTO @TABLA_ASISTENCIAS
	SELECT 
	AD.CLIENTE,
	AD.JTS_OID,
	ISNULL(SUM(AD.SALDO_DEUDA),0),
	CASE 
	WHEN gar.TIPO_GARANTIA IS NULL THEN ''N''
	ELSE ''S''
	END AS GARANTIA,
	ISNULL(gar.TIPO_GARANTIA,0),
	p.C6250, 
	p.C6283,
	AD.NUMEROPERSONA
	FROM VW_DEUDA_CLIENTES AD WITH(NOLOCK)
	INNER JOIN SALDOS S WITH(NOLOCK) ON S.JTS_OID = AD.JTS_OID
	INNER JOIN PRODUCTOS p WITH(NOLOCK) ON s.PRODUCTO = p.C6250 
	AND ( (p.tz_lock < 300000000000000 OR p.tz_lock >= 400000000000000) 
	AND (p.tz_lock < 100000000000000 OR p.tz_lock >= 200000000000000)  )	
	LEFT JOIN (SELECT DISTINCT CG.JTSOID_SALDO, CTG.TIPO_GARANTIA FROM CRE_GARANTIACREDITO CG WITH(NOLOCK)
	LEFT JOIN CRE_GARANTIASRECIBIDAS CGR WITH(NOLOCK) ON CGR.NUM_GARANTIA = CG.NUM_GARANTIA
	LEFT JOIN CRE_TIPOSGARANTIAS CTG WITH(NOLOCK) ON CGR.TIPOGARANTIA = CTG.TIPO_GARANTIA AND
	CTG.TIPO_BCRA IN (1,2)) gar ON gar.JTSOID_SALDO = S.JTS_OID
	WHERE AD.SALDO_DEUDA <> 0 ---AND S.C1785 IN (1,5,6)
	AND AD.NUMEROPERSONA IN (SELECT PERSONA FROM @GRUPO_PERSONAS WHERE GRUPO=@GRUPO)
	GROUP BY AD.JTS_OID, gar.JTSOID_SALDO, gar.TIPO_GARANTIA, p.C6250, p.C6283, AD.CLIENTE, AD.NUMEROPERSONA
	
	
	INSERT INTO @TBL_AUX (CLIENTE, DEUDA_TOTAL, DEUDA_CON_G, DEUDA_SIN_G, PERSONA)
    SELECT A.CLIENTE,
    SUM(A.IMPORTE_DEUDA) AS DEUDA_TOTAL,
    ISNULL(SUM(CASE WHEN TIENE_GARANTIA =''S'' THEN A.IMPORTE_DEUDA ELSE 0 END),0),
    ISNULL(SUM(CASE WHEN TIENE_GARANTIA =''N'' THEN A.IMPORTE_DEUDA ELSE 0 END),0),
    A.PERSONA
    FROM  @TABLA_ASISTENCIAS A 
    GROUP BY CLIENTE, PERSONA
    

	---- Exclusiones graduacion

	UPDATE @TBL_AUX
    SET EXCLUSION_CLI_GRAD=ISNULL((SELECT SUM(AD.IMPORTE_DEUDA) 
                               FROM @TABLA_ASISTENCIAS AD 
                               WHERE AD.CLIENTE=T.CLIENTE AND
	AD.CLIENTE IN (SELECT CODIGOCLIENTE FROM CRE_EXCLUSIONES_CLIENTES WITH(NOLOCK) WHERE 
	TZ_LOCK=0)),0)
    FROM @TBL_AUX T
  
    UPDATE @TBL_AUX
    SET EXCLUSION_DESC_GRAD = ISNULL((SELECT SUM(IMPORTE_DEUDA) FROM @TABLA_ASISTENCIAS AD WHERE CLIENTE = T.CLIENTE
								 AND AD.CLIENTE NOT IN (SELECT CODIGOCLIENTE 
								 FROM CRE_EXCLUSIONES_CLIENTES WITH(NOLOCK) WHERE TZ_LOCK=0)
								 AND AD.JTS_ASISTENCIA IN (SELECT DISTINCT JTS_OID FROM VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO CD WITH(NOLOCK) 
								 WHERE EXISTS (SELECT 1 FROM CRE_EXCLUSIONES_CUIT_EMISOR CE WITH(NOLOCK)
								 WHERE CE.NUMERODOCUMENTO = CD.documento_librador AND CE.CUENTA_FORANEA = CD.numerico_cuenta_giradora) 
								 AND CD.jts_oid <> 0)),0)
	FROM @TBL_AUX T
   
   
	UPDATE @TBL_AUX
    SET EXCLUSION_ASIST_GRAD=ISNULL((SELECT SUM(AD.IMPORTE_DEUDA)
                                 FROM @TABLA_ASISTENCIAS AD 
                                 WHERE T.CLIENTE=AD.CLIENTE AND
	 AD.CLIENTE NOT IN (SELECT CODIGOCLIENTE FROM CRE_EXCLUSIONES_CLIENTES WITH(NOLOCK) WHERE TZ_LOCK=0)
	 AND AD.JTS_ASISTENCIA NOT IN (SELECT DISTINCT JTS_OID FROM VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO CD WITH(NOLOCK) 
								WHERE EXISTS (SELECT 1 FROM CRE_EXCLUSIONES_CUIT_EMISOR CE WITH(NOLOCK)
								WHERE CE.NUMERODOCUMENTO = CD.documento_librador AND CE.CUENTA_FORANEA = CD.numerico_cuenta_giradora) 
								AND CD.jts_oid <> 0)
     AND AD.JTS_ASISTENCIA IN (SELECT ASISTENCIA_JTS_OID FROM CRE_EXCLUSIONES_ASISTENCIAS 
     WITH(NOLOCK) WHERE TZ_LOCK=0)),0)
     FROM @TBL_AUX T
     
 
	UPDATE @TBL_AUX
    SET EXCLUSION_PROD_GRAD=ISNULL((SELECT SUM(AD.IMPORTE_DEUDA)
                                FROM @TABLA_ASISTENCIAS AD
                                WHERE T.CLIENTE=AD.CLIENTE  
                                AND AD.CLIENTE NOT IN (SELECT CODIGOCLIENTE FROM CRE_EXCLUSIONES_CLIENTES WITH(NOLOCK) 
                                WHERE TZ_LOCK=0)
    AND AD.JTS_ASISTENCIA NOT IN (SELECT ASISTENCIA_JTS_OID FROM CRE_EXCLUSIONES_ASISTENCIAS 
    WITH(NOLOCK) WHERE TZ_LOCK = 0)
    AND ((AD.PRODUCTO IN (SELECT ITEM FROM CRE_EXCLUSIONES_PRODUCTOS WITH(NOLOCK) WHERE TIPO=''P'' 
    AND TZ_LOCK = 0))
    OR (AD.FAMILIA IN (SELECT ITEM FROM CRE_EXCLUSIONES_PRODUCTOS WITH(NOLOCK) WHERE TIPO=''F'' 
    AND TZ_LOCK = 0)))),0) 
    FROM @TBL_AUX T
    
    
    UPDATE @TBL_AUX
    SET EXCLUSION_GAR_GRAD = ISNULL((SELECT SUM(AD.IMPORTE_DEUDA)
                                FROM @TABLA_ASISTENCIAS AD
                                WHERE T.CLIENTE=AD.CLIENTE  
                                AND AD.CLIENTE NOT IN (SELECT CODIGOCLIENTE FROM CRE_EXCLUSIONES_CLIENTES WITH(NOLOCK) 
                                WHERE TZ_LOCK=0)
   	 AND AD.JTS_ASISTENCIA NOT IN (SELECT DISTINCT JTS_OID FROM VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO CD WITH(NOLOCK) 
								WHERE EXISTS (SELECT 1 FROM CRE_EXCLUSIONES_CUIT_EMISOR CE WITH(NOLOCK)
								WHERE CE.NUMERODOCUMENTO = CD.documento_librador AND CE.CUENTA_FORANEA = CD.numerico_cuenta_giradora) 
								AND CD.jts_oid <> 0)
   AND AD.JTS_ASISTENCIA NOT IN (SELECT ASISTENCIA_JTS_OID FROM CRE_EXCLUSIONES_ASISTENCIAS 
   WITH(NOLOCK) WHERE TZ_LOCK = 0)
   AND ((AD.PRODUCTO NOT IN (SELECT ITEM FROM CRE_EXCLUSIONES_PRODUCTOS WITH(NOLOCK) WHERE TIPO=''P'' 
   AND TZ_LOCK = 0))
   OR (AD.FAMILIA NOT IN (SELECT ITEM FROM CRE_EXCLUSIONES_PRODUCTOS WITH(NOLOCK) WHERE TIPO=''F'' 
   AND TZ_LOCK = 0))) AND AD.TIPO_GARANTIA IS NOT NULL AND AD.TIPO_GARANTIA IN
   (SELECT TIPO_GARANTIA FROM CRE_EXCLUSIONES_TIPOSGARANTIAS WITH(NOLOCK) WHERE TZ_LOCK=0)),0) 
   FROM @TBL_AUX T
   
	UPDATE @TBL_AUX
    SET TOT_CONTROL_GRAD=(T.DEUDA_TOTAL+(CASE WHEN @EXCLUSION = ''N'' AND T.CLIENTE = @CLIENTE THEN @IMPORTE_SOLICITUD ELSE 0 END))-(EXCLUSION_CLI_GRAD+EXCLUSION_ASIST_GRAD+EXCLUSION_PROD_GRAD+EXCLUSION_GAR_GRAD+EXCLUSION_DESC_GRAD)
    FROM @TBL_AUX T

	UPDATE @TBL_AUX
    SET TRAMO_SIN_G=T.DEUDA_SIN_G
    FROM @TBL_AUX T


	UPDATE @TBL_AUX
    SET TRAMO_CON_G=T.DEUDA_CON_G
    FROM @TBL_AUX T

	---COMPARACIÓN CLIENTE X CLIENTE PARA VERIFICAR SI SUPERA LIMITE GRADUACION, FRACC CON GARANTIA Y SIN GARANTIA 
	UPDATE @TBL_AUX
	SET EXCEDIDO_GRAD = CASE WHEN @LIMITE_GRAD>=TOT_CONTROL_GRAD  THEN ''N'' ELSE ''S'' END;
	
	UPDATE @TBL_AUX
	SET EXCEDIDO_FRACC = CASE WHEN @TRAMO_SIN_G_B >= TRAMO_SIN_G AND @TRAMO_CON_G_B >= TRAMO_CON_G
	                          THEN ''N'' ELSE ''S'' END;

	-- Si la deuda total supera el % por sobre el importe de referencia establecido, queda encuadradro en graduacion. Se obtiene valor    
    SET @TOPE_ANALISIS = ((SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO=501) * (SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO=615));
    
	SET @TOT_CONTROL_GRAD = ISNULL((SELECT SUM(TOT_CONTROL_GRAD) FROM @TBL_AUX WHERE PERSONA = @PERSONA),0);
	
	SET @DEUDA_TOTAL = ISNULL((SELECT SUM(DEUDA_TOTAL) FROM @TBL_AUX WHERE PERSONA = @PERSONA),0) + CASE WHEN @EXCLUSION = ''N'' THEN @IMPORTE_SOLICITUD ELSE 0 END;

	SET @DEUDA_TOTAL_IR = ISNULL((SELECT SUM(DEUDA_TOTAL) FROM @TBL_AUX WHERE PERSONA = @PERSONA),0) + @IMPORTE_SOLICITUD;
	
	--Determinar a que tramo se suma el importe de la simulacion	
	IF(@CON_GTIA = ''S'')
		BEGIN
			SET @TRAMO_CON_G = ISNULL((ISNULL((SELECT SUM(DEUDA_CON_G) FROM @TBL_AUX),0)+@IMPORTE_SOLICITUD),0);
			SET @TRAMO_SIN_G = ISNULL((SELECT SUM(DEUDA_SIN_G) FROM @TBL_AUX),0);
		END 
	ELSE 
		BEGIN
			SET @TRAMO_CON_G = ISNULL((SELECT SUM(DEUDA_CON_G) FROM @TBL_AUX),0);
			SET @TRAMO_SIN_G = ISNULL((ISNULL((SELECT SUM(DEUDA_SIN_G) FROM @TBL_AUX),0)+@IMPORTE_SOLICITUD),0);
		END
	
--CUENTA SI LA CANTIDAD DE CLIENTES QUE EXCEDEN GRADUACIÓN/FRACCIONAMIENTO ES >=1

   	IF (@TOPE_ANALISIS>@DEUDA_TOTAL_IR)
		BEGIN
			SET @RESULTADO_GRADUACION =  concat(''Encuadrado (Riesgo Total < '' , (SELECT LTRIM(STR(IMPORTE))  FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO=615) , ''IR)'');
			SET @EXCEDE_GRADUACION = ''N''
		END
	ELSE IF (@RPC_CLIENTE = 0)
		BEGIN
	        SET @EXCEDE_GRADUACION = ''N'';
	        SET @RESULTADO_GRADUACION = ''Encuadrado.'';
	    END
	ELSE IF (@TOT_CONTROL_GRAD>@LIMITE_GRAD)
	    BEGIN
	        SET @EXCEDE_GRADUACION = ''S'';
	        SET @RESULTADO_GRADUACION = ''Exceso en Graduación: ''+CONVERT(VARCHAR(30),FORMAT(ROUND((@TOT_CONTROL_GRAD)-@LIMITE_GRAD,2), ''C'', ''es-ar''))+''.'';
	    END
	/*ELSE IF (@TOT_CONTROL_GRAD=0 AND @DEUDA_TOTAL>@LIMITE_GRAD)
	    BEGIN
	        SET @EXCEDE_GRADUACION = ''S'';
	        SET @RESULTADO_GRADUACION = ''Exceso en Graduación: ''+CONVERT(VARCHAR(30),FORMAT(ROUND((@DEUDA_TOTAL)-@LIMITE_GRAD,2), ''C'', ''es-ar''))+''.'';
	    END*/
	ELSE 
	    BEGIN
	        SET @EXCEDE_GRADUACION = ''N'';
	        SET @RESULTADO_GRADUACION = ''Encuadrado.'';
	    END
    
--Nueva Logica
--GRANDES EXPOSICIONES
	 		IF (@TRAMO_SIN_G_B>=@TRAMO_SIN_G AND @TRAMO_CON_G_B>=(@TRAMO_CON_G+@TRAMO_SIN_G) )
				BEGIN
					SET @RESULTADO_FRACCIONAMIENTO = ''Encuadrado en Grandes Exposiciones sin garantía.'' +char(10) + char(13) + ''Encuadrado en Grandes Exposiciones con y sin garantía.'';
					SET @EXCEDE_FRACCIONAMIENTO = ''N'';
				END
			ELSE IF (@TRAMO_SIN_G_B>=@TRAMO_SIN_G AND @TRAMO_CON_G_B<(@TRAMO_CON_G+@TRAMO_SIN_G) )
				BEGIN
					SET @RESULTADO_FRACCIONAMIENTO = ''Encuadrado en Grandes Exposiciones sin garantía.'' +char(10) + char(13) + ''Exceso en Grandes Exposiciones con y sin garantía: '' + CONVERT(VARCHAR(30),FORMAT(ROUND((@TRAMO_CON_G+@TRAMO_SIN_G)-@TRAMO_CON_G_B,2), ''C'', ''es-ar'')) + ''.'';
					SET @EXCEDE_FRACCIONAMIENTO = ''S'';
				END	
			ELSE IF (@TRAMO_SIN_G_B<@TRAMO_SIN_G AND @TRAMO_CON_G_B>=(@TRAMO_CON_G+@TRAMO_SIN_G) )
				BEGIN
					SET @RESULTADO_FRACCIONAMIENTO = ''Exceso en Grandes Exposiciones sin garantía: '' + CONVERT(VARCHAR(30),FORMAT(ROUND(@TRAMO_SIN_G-@TRAMO_SIN_G_B,2), ''C'', ''es-ar'')) + ''.'' +char(10) + char(13) + ''Encuadrado en Grandes Exposiciones con y sin garantía. '';
					SET @EXCEDE_FRACCIONAMIENTO = ''S'';
				END
			ELSE IF (@TRAMO_SIN_G_B<@TRAMO_SIN_G AND @TRAMO_CON_G_B<(@TRAMO_CON_G+@TRAMO_SIN_G) )
				BEGIN
					SET @RESULTADO_FRACCIONAMIENTO = ''Exceso en Grandes Exposiciones sin garantía: '' + CONVERT(VARCHAR(30),FORMAT(ROUND(@TRAMO_SIN_G-@TRAMO_SIN_G_B,2), ''C'', ''es-ar'')) + ''.'' +char(10) + char(13) + ''Exceso en Grandes Exposiciones con y sin garantía: '' + CONVERT(VARCHAR(30),FORMAT(ROUND((@TRAMO_CON_G+@TRAMO_SIN_G)-@TRAMO_CON_G_B,2), ''C'', ''es-ar'')) + ''.'';
					SET @EXCEDE_FRACCIONAMIENTO = ''S'';
				END	
       

	END

--EXCLUSIONES GRUPO GRADUACION EN GENERAL
	  
		--EXCLUSIONES GRADUACIÓN CLIENTE +CLIENTE
	  /*	SET @EXCLUSION_GRUPOCLIENTE_G =(SELECT SUM(EXCLUSION_CLI_GRAD) FROM @TBL_AUX) 
		
		--EXCLUSIONES GRADUACION ASISTENCIAS+CLIENTE
		SET @EXCLUSION_GRUPOASIST_G =(SELECT SUM(EXCLUSION_ASIST_GRAD)FROM @TBL_AUX)
	    
	    --EXCLUSION GRADUACION PRODUCTO+GRUPO
	    SET @EXCLUSION_GRUPOPROD_G =(SELECT SUM(EXCLUSION_PROD_GRAD) FROM @TBL_AUX)
		
		
		SET @EXCLUSIONES_GRUPALES_GRADUACION=(@EXCLUSION_GRUPOCLIENTE_G+@EXCLUSION_GRUPOASIST_G+@EXCLUSION_GRUPOPROD_G);*/
		
	  
---CALCULOS PARA GRUPO EN GENERAL
 /*	IF(@EXCLUIDO=''N'')
		BEGIN 
		--
		--DEUDA TOTAL DEL GRUPO
			SET @TOTAL_DEUDA_GRUPO=(SELECT SUM(DEUDA_TOTAL) FROM @TBL_AUX) +@IMPORTE_SOLICITUD 
	  
			SET @IMPORTE_A_EVALUAR=@TOTAL_DEUDA_GRUPO-@EXCLUSIONES_GRUPALES_GRADUACION; 
	   
     	END
       
	    
	 ELSE
	   BEGIN 
	   		SET @TOTAL_DEUDA_GRUPO=(SELECT SUM(DEUDA_TOTAL) FROM @TBL_AUX)
	  
	  
	    	SET @TOTAL_DEUDA_GRUPO=@TOTAL_DEUDA_GRUPO
	    	SET @IMPORTE_A_EVALUAR=@TOTAL_DEUDA_GRUPO-@EXCLUSIONES_GRUPALES_GRADUACION; 
	   
	 END */
	 
	  
  --CALCULO IMPORTE CON G Y SIN G FRACCIONAMIENTO PARA EL GRUPO EN GENERAL
  --GRUPO CON GARANTIA
  	SET @IMPORTE_CONG_GRUPO = @TRAMO_CON_G
		
   --GRUPO SIN GARANTIA
    SET @IMPORTE_SING_GRUPO=@TRAMO_SIN_G		
	  
 END
')