EXECUTE('
IF OBJECT_ID (''dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO'') IS NOT NULL
	DROP TABLE dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO
')
EXECUTE('
CREATE TABLE dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO
	(
	TZ_LOCK               NUMERIC (15) DEFAULT ((0)) NOT NULL,
	TIPO_IMPUESTO         NUMERIC (2) DEFAULT ((0)) NOT NULL,
	CARGO_O_IMPUESTO      VARCHAR (1) DEFAULT ('' '') NOT NULL,
	TIPO_CARGO_IMPOSITIVO NUMERIC (2) DEFAULT ((0)),
	DESCRIPCION           VARCHAR (40) DEFAULT ('' ''),
	DESCRIPCION_REGIMEN	  VARCHAR (40) DEFAULT ('' '')
	CONSTRAINT PK_CON_EQUIVALENCIA_CARGO_I_01 PRIMARY KEY (TIPO_IMPUESTO, CARGO_O_IMPUESTO)
	)
')