EXECUTE('
	DELETE FROM dbo.OPERACIONES
	WHERE TITULO = 3552 AND IDENTIFICACION = 3459

	INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
	VALUES (3552, 3459, ''Solicitud COELSA certificado de acción civil'', ''Solicitud COELSA certificado de acción civil'', ''3459'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 91072

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (91072, '' '', 0, ''Busqueda'', ''Buscar por'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Busqueda'', 0, NULL)

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 91072 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''1''

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 91072 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''2''

	DELETE FROM dbo.OPCIONES
	WHERE NUMERODECAMPO = 91072 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''3''

	INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
	VALUES (91072, ''E'', ''Nro. Cliente'', ''1'', ''1'')

	INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
	VALUES (91072, ''E'', ''Nro. Cuenta'', ''2'', ''2'')

	INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
	VALUES (91072, ''E'', ''Nro. Cheque'', ''3'', ''3'')
	
	DELETE FROM dbo.AYUDAS
	WHERE NUMERODEAYUDA = 93457

	INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
	VALUES (0, 93457, ''Ayuda Vista Cheques COELSA'', '''', 0, ''1803R;1593R;1090R;1093R;1091R;1092R;2576R;2614R;1988R;8895R;2617R;1093R;'', ''NumeroCliente;NumeroCuenta;NumeroCheque;Estado;Importe;Fecha;Sucursal;Moneda;Producto;Operacion;Ordinal;Serie;'', ''Top/Clientes'', ''VW_CHEQUES_COELSA'', 0)

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 99348

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (99348, '' '', 0, ''Ayuda CHEQUES_COELSA'', ''Ayuda CHEQUES_COELSA'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 93457, 0, 0, ''Ayuda CHEQUES_COELSA'', 0, NULL)

	DELETE FROM dbo.AYUDAS
	WHERE NUMERODEAYUDA = 93458

	INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
	VALUES (0, 93458, ''Busqueda Cheques'', '''', 0, ''1090R;1086;1093;1091;1092;'', ''NumeroCheque;Cuenta;Estado;Importe;Fecha;'', ''Top/Clientes'', ''VW_CHEQUES_RECHAZADOS'', 0)

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 99349

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (99349, '' '', 0, ''Ayuda CHEQUES'', ''Ayuda CHEQUES'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 93458, 0, 0, ''Ayuda CHEQUES'', 0, NULL)

	DELETE FROM dbo.DESCRIPTORES
	WHERE TITULO = 35 AND IDENTIFICACION = 3459

	INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
	VALUES (35, 3549, NULL, ''Relación Cheques X COELSA'', 0, ''CHEQUES_X_COELSA'', ''D'', 0, 0, ''Top/Clientes'', NULL, ''N'')

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35871

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35872

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35873

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35874

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35875

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35876

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35877

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35878

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35879

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35880

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35881

	DELETE FROM dbo.DICCIONARIO
	WHERE NUMERODECAMPO = 35882

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35871, NULL, 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Sucursal'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35872, NULL, 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Moneda'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35873, NULL, 0, ''Cuenta'', ''Cuenta'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Cuenta'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35874, NULL, 0, ''Producto'', ''Producto'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Producto'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35875, NULL, 0, ''Operacion'', ''Operacion'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Operacion'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35876, NULL, 0, ''Ordinal'', ''Ordinal'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Ordinal'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35877, NULL, 0, ''Nro.Cheque'', ''Nro.Cheque'', 9, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''NUMEROCHEQUE'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35878, NULL, 0, ''Importe'', ''Importe'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Importe'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35879, NULL, 0, ''Código visualización'', ''Código visualización'', 15, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''CODIGO_VISUALIZACION'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35880, NULL, 0, ''Fecha estado'', ''Fecha estado'', 8, ''F'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''FECHAESTADO'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35881, NULL, 0, ''Estado'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Estado'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35882, NULL, 0, ''Serie'', ''Serie'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3549, ''Serie'', 0, NULL)

	DELETE FROM dbo.INDICES
	WHERE NUMERODEARCHIVO = 3549 AND NUMERODEINDICE = 1

	INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
	VALUES (3549, 1, ''Indice Cheque X Código'', 0, 35871, 35872, 35873, 35874, 35875, 35876, 35877, 35882, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
')