EXECUTE('

IF OBJECT_ID(''dbo.CLE_DESCUENTOS_ECHEQ'', ''U'') IS NOT NULL
BEGIN
    DROP TABLE dbo.CLE_DESCUENTOS_ECHEQ
END


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35909

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35910


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35911


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35912


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35913


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35914


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35915


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35916


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35917


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35918


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35930


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35931


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35932


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35933


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35934


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35935


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35936


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35937


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35938


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35939


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35940


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35941


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35942


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35943


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35944


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35945


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35946


DELETE FROM dbo.AYUDAS
WHERE NUMERODEAYUDA = 99967


DELETE FROM dbo.DESCRIPTORES
WHERE TITULO = 35 AND IDENTIFICACION = 3581


DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 3581 AND NUMERODEINDICE = 1




CREATE TABLE dbo.CLE_DESCUENTOS_ECHEQ
	(
	TZ_LOCK            NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ID_CHEQUE          NUMERIC (10) DEFAULT ((0)) NOT NULL,
	SUCURSAL           NUMERIC (5) DEFAULT ((0)),
	MONEDA             NUMERIC (4) DEFAULT ((0)),
	CUENTA             NUMERIC (12) DEFAULT ((0)),
	PRODUCTO           NUMERIC (5) DEFAULT ((0)),
	OPERACION          NUMERIC (12) DEFAULT ((0)),
	ORDINAL            NUMERIC (6) DEFAULT ((0)),
	NUMERO_CHEQUE      NUMERIC (9) DEFAULT ((0)),
	IMPORTE            NUMERIC (15, 2) DEFAULT ((0)),
	JTS_OID_DESTINO    NUMERIC (10) DEFAULT ((0)),
	CMC7               VARCHAR (30) DEFAULT ('' ''),
	CANAL_ORIGEN       NUMERIC (2) DEFAULT ((0)),
	ORDEN              NUMERIC (12) DEFAULT ((0)),
	FECHA_EMISION      DATETIME,
	FECHA_VTO          DATETIME,
	TIPO_DOC           VARCHAR (4),
	NRO_DOC            VARCHAR (20),
	codigoNegociacion  VARCHAR (15) NOT NULL,
	ESTADO             VARCHAR (2),
	FECHA_PAGO         DATETIME,
	CUIT_NEGOCIADOR    VARCHAR (20),
	ORIGEN             VARCHAR (2),
	CODIGO_BANCO_CMC7  VARCHAR (3),
	SUCURSAL_CMC7      VARCHAR (3),
	CODIGO_POSTAL_CMC7 VARCHAR (4),
	NUMERO_CHEQUE_CMC7 VARCHAR (8),
	NUMERO_CUENTA_CMC7 VARCHAR (11),
	CONSTRAINT PK_CLE_DESCUENTOS_ECHEQ_01 PRIMARY KEY (codigoNegociacion, ID_CHEQUE)
	)





INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3581, NULL, ''Descuento Cheques electrónicos'', 0, ''CLE_DESCUENTOS_ECHEQ'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3581, 1, ''Indice Principal'', 0, 35918, 35930, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3581, 99967, ''Ayuda Desc Cheques Electronico'', '''', 0, ''35930R;35909;35931;35932;35933;35934;35937;35911;35918R;35914;35915;35910;35916;35917;'', NULL, NULL, NULL, 0)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35909, '''', 0, ''Importe'', ''Importe'', 15, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''IMPORTE'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35910, '''', 0, ''JTS OID depósito'', ''Saldo de depósito'', 10, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''JTS_OID_DESTINO'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35911, '''', 0, ''CMC7'', ''Banda del Cheque'', 30, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CMC7'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35912, '''', 0, ''Canal de Origen'', ''Canal de Origen'', 2, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CANAL_ORIGEN'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35913, '''', 0, ''Nro.de Orden'', ''Nro. de Orden'', 12, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''ORDEN'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35914, '''', 0, ''Fecha de emisión'', ''Fecha de emisión'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''FECHA_EMISION'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35915, '''', 0, ''Fecha de Vencimiento'', ''Fecha de Vencimiento'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''FECHA_VTO'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35916, '''', 0, ''Tipo Documento'', ''Tipo Documento'', 4, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''TIPO_DOC'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35917, '''', 0, ''Nro Documento'', ''Nro Documento'', 20, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''NRO_DOC'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35918, '''', 0, ''Código Negociación'', ''Código Negociación'', 15, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''codigoNegociacion'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35930, '''', 0, ''ID Cheque electrónico'', ''ID Cheque'', 10, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''ID_CHEQUE'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35931, '''', 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''SUCURSAL'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35932, '''', 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''MONEDA'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35933, '''', 0, ''Cuenta'', ''Cuenta'', 12, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CUENTA'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35934, '''', 0, ''Producto'', ''Producto'', 5, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''PRODUCTO'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35935, '''', 0, ''Operación'', ''Operación'', 12, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''OPERACION'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35936, '''', 0, ''Ordinal'', ''Ordinal'', 6, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''ORDINAL'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35937, '''', 0, ''Nro. Cheque'', ''Nro. Cheque'', 9, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''NUMERO_CHEQUE'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35938, NULL, 0, ''Estado'', ''Estado'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3581, ''ESTADO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35939, '''', 0, ''Fecha de pago'', ''Fecha de pago'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''FECHA_PAGO'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35940, '''', 0, ''CUIT Negociador'', ''CUIT Negociador'', 20, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CUIT_NEGOCIADOR'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35941, '''', 0, ''Origen'', ''Origen'', 2, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''ORIGEN'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35942, '''', 0, ''Codigo Banco CMC7'', ''Codigo Banco CMC7'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CODIGO_BANCO_CMC7'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35943, '''', 0, ''Sucursal CMC7'', ''Sucursal CMC7'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''SUCURSAL_CMC7'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35944, '''', 0, ''Codigo Postal CMC7'', ''Codigo Postal CMC7'', 4, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''CODIGO_POSTAL_CMC7'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35945, '''', 0, ''Numero Cheque CMC7'', ''Numero Cheque CMC7'', 8, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''NUMERO_CHEQUE_CMC7'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35946, '''', 0, ''Numero Cuenta CMC7'', ''Numero Cuenta CMC7'', 11, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3581, ''NUMERO_CUENTA_CMC7'', 0, '''')


')