EXECUTE ('

-- DESCRIPTOR
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (4000, 3625, NULL, ''Productos por convenio'', 0, ''MA_CONVENIO_PRODUCTOS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


-- DICCIONARIO
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40213, '' '', 0, ''Convenio de Pago'', ''Convenio de Pago'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3625, ''ConvenioPago'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40214, '' '', 0, ''Producto'', ''Producto'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3625, ''Producto'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40218, '' '', 0, ''Tipo Convenio'', ''Tpo Convenio'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3625, ''TipoConvenio'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40219, '' '', 0, ''Nombre Convenio Pago'', ''Nombre Convenio'', 40, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3625, ''NomConvPago'', 0, NULL)

--INDICES
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3625, 1, ''Índice Principal'', 0, 40213, 40214, 40218, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--DICCIONARIO
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44085, '' '', 0, ''Alfanumerico'', ''alfa'', 999, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Alfanumerico'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40215, '' '', 0, ''Convenio de Pago'', ''Convenio de Pago'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3621, ''ConvenioPago'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40217, '' '', 0, ''Ay Convenio'', ''Ay Convenio'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 44723, 0, 0, ''AY_Convenio'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (40216, '' '', 0, ''Ay Prod Convenio'', ''Ay Prod Convenio'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 36251, 0, 0, ''Prod_Convenio'', 0, NULL)



--OPERACIONES
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (4600, 4606, ''ABC Productos por convenio Altas Masivas'', ''ABC Productos por convenio Altas Masivas'', ''4606'', ''N'', 0, 0, ''P'', 0, 0, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)


--AYUDAS
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 36251, ''Ay prod convenio'', '''', 0, ''44782R;44783;44788R;198R;114;'', ''ConvenioPago;NomConvPago;TipoConvenio;Producto;Descripcion_Producto'', ''top/clientes'', ''VW_MA_PRODUCTOS_X_CONVENIOS'', 0)


INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4472, 44723, ''Ay prod convenio'', '''', 0, ''44782R;44788R;44783;'',NULL, NULL, NULL, 0)



')






