EXECUTE('
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (400, 2154, 0, ''A'', 0, '''', 1)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (10, 705, ''A'', 0, 34096, ''Cond CREDEB'', 0)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (10, 706, ''A'', 0, 34096, ''Cond CREDEB'', 0)
')