EXECUTE('

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2080, 2093, ''Consultas y mod. de condición CREDEB por CBU'', ''Consultas y modificaciones de condición CREDE-CBU'', ''2093'', ''A'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99903, '' '', 0, ''Opciones CREDEB. Mod/Cons'', ''Opciones CREDEB. Mod/Cons'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Opciones CREDEB. Mod/Cons'', 0, NULL)

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (99903, ''E'', ''Consulta'', ''C'', ''C'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (99903, ''E'', ''Modificación'', ''M'', ''M'')

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 93455, ''Ayuda Vista CREDEB Consulta'', '''', 0, ''1057R;1963R;99998R;1239R;596R;240R;238R;99997R;9788R;46159R;46161R;'', ''NUMERO_CLIENTE;NUMERODOCUMENTO;CBU;SEGMENTO;TASA;PADRON_BENEF_FISCAL;PADRON_MiPyme;CREDEB_Condicion;JTS_OID_SALDO;FECHA;TIPO_CARGO_IMPOSITIVO;'', ''Top/Clientes'', ''VW_CONSULTA_CREDEB'', 0)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99346, '' '', 0, ''Ayuda CREDEB'', ''Ayuda CREDEB'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 93455, 0, 0, ''Ayuda CREDEB'', 0, NULL)

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (4600, 4607, NULL, ''Bitácora de CREDEB'', 0, ''RRII_BITACORA_CREDEB'', ''D'', 0, 0, ''Top/Clientes'', NULL, ''N'')

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46158, '' '', 0, ''JTS_OID_SALDOS'', ''JTS_OID_SALDOS'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4607, ''JTS_OID_SALDOS'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46159, '' '', 0, ''FECHA'', ''FECHA'', 8, ''F'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4607, ''FECHA'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46160, '' '', 0, ''SEGMENTO'', ''SEGMENTO'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4607, ''SEGMENTO'', 0, NULL)

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46160, ''E'', ''Segmento'', ''0'', ''0'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46160, ''E'', ''Segmento'', ''1'', ''1'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46160, ''E'', ''Segmento'', ''2'', ''2'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46160, ''E'', ''Segmento'', ''3'', ''3'')

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46161, '' '', 0, ''TIPO_CARGO_IMPOSITIVO'', ''TIPO_CARGO_IMPOSITIVO'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4607, ''TIPO_CARGO_IMPOSITIVO'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46162, '' '', 0, ''PADRON_BENEF_FISCAL'', ''PADRON_BENEF_FISCAL'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4607, ''PADRON_BENEF_FISCAL'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (46163, '' '', 0, ''PADRON_MiPyme'', ''PADRON_MiPyme'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4607, ''PADRON_MiPyme'', 0, NULL)

INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4607, 1, ''JTS OID de Saldos'', 0, 46158, 46159, 46161, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 99998

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99998, '' '', 0, ''CBU'', ''CBU'', 22, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''CBU'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99997, '' '', 0, ''Condición CREDEB'', ''Condición CREDEB'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Condición CREDEB'', 0, NULL)

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (99997, ''E'', ''Alcanzado'', ''AC'', ''AC'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (99997, ''E'', ''Exento parcial'', ''EP'', ''EP'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (99997, ''E'', ''Exento'', ''EX'', ''EX'')
')