EXECUTE('

DELETE FROM dbo.DESCRIPTORES WHERE TITULO = 930 AND IDENTIFICACION = 864;

INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (930, 864, '' '', ''Padron IIBB Corrientes'', 0, ''ITF_PADRON_IMPUESTOS'', ''D'', 0, 0, ''Top/Clientes'', NULL, ''N'');

DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO = 41470;

DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO = 41471;

DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO = 41472;

DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO = 41473;

DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO = 41474;


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41470, '' '', 0, ''id'', ''Id '', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 864, ''ID'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41471, '' '', 0, ''CUIT'', ''CUIT'', 11, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 864, ''CUIT'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41472, '' '', 0, ''RAZON SOCIAL'', ''RAZON SOCIAL'', 44, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 864, ''RAZON_SOCIAL'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41473, '' '', 0, ''PERIODO_ARCHIVO'', ''PERIODO_ARCHIVO'', 6, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 864, ''PERIODO_ARCHIVO'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41474, '' '', 0, ''ALICUOTA'', ''ALICUOTA '', 11, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 864, ''ALICUOTA'', 0, NULL);



DELETE FROM dbo.INDICES WHERE NUMERODEARCHIVO = 864 AND NUMERODEINDICE = 1;

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (864, 1, ''CUIL'', 0, 41471, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
')