EXECUTE('
IF OBJECT_ID (''dbo.RML_BANDAS_AHORA_12'') IS NOT NULL
	DROP TABLE dbo.RML_BANDAS_AHORA_12;
')
EXECUTE('

CREATE TABLE dbo.RML_BANDAS_AHORA_12
	(
	FECHA           DATETIME,
	PARTIDA         INT,
	ADMINISTRADORA  VARCHAR (20),
	NRO_USUARIO     VARCHAR (20),
	SALDO           NUMERIC (2),
	TIPO_DOC        VARCHAR (4),
	NRO_DOC         VARCHAR (20),
	NOMBRE_APELLIDO VARCHAR (70)
	);
')