EXECUTE('
UPDATE DICCIONARIO
SET LARGO = 21
WHERE NUMERODECAMPO = 34958
')

EXECUTE('
ALTER TABLE TJD_COBRO_COMISIONES  
ALTER COLUMN CUENTA_PBF VARCHAR(21) COLLATE Modern_Spanish_CI_AS;
')

EXECUTE('
CREATE NONCLUSTERED INDEX TJD_TARJETAS_ID_TARJETA_BASE_IDX ON dbo.TJD_TARJETAS (  ID_TARJETA_BASE ASC  );
')