EXECUTE('
IF OBJECT_ID (''dbo.VW_VINCULACIONES_JUDICIALES'') IS NOT NULL
	DROP VIEW dbo.VW_VINCULACIONES_JUDICIALES
')

EXECUTE('
CREATE VIEW [dbo].[VW_VINCULACIONES_JUDICIALES] AS (
SELECT 
cau.NRO_CAUSA,
CAU.ANO,
CONVERT(NUMERIC(12),CAU.EXPEDIENTE) AS EXPEDIENTE,
CAU.TIPO_CAUSA,
CAU.JUZGADO,
doc.NUMERODOCUMENTO,
ben.ID_BENEFICIARIO,
CC.JTS_OID_CUENTA AS JTS_OID_CUENTA,
S.CUENTA,
S.c1803 AS CLIENTE,
cli.NUMERODOC AS DOCTITCTA,
S.MONEDA,
S.SUCURSAL,
cau.CARATULA
FROM DJ_CAUSAS cau WITH(NOLOCK)
INNER JOIN DJ_CAUSA_CUENTA CC WITH(NOLOCK) ON CC.NRO_CAUSA = cau.NRO_CAUSA AND CC.TZ_LOCK = 0
INNER JOIN SALDOS S WITH(NOLOCK) ON S.JTS_OID = CC.JTS_OID_CUENTA 
-- INNER JOIN VW_CUENTAS c WITH(NOLOCK) ON CC.JTS_OID_CUENTA = c.JTS_OID
INNER JOIN VW_CLI_X_DOC cli WITH(NOLOCK) ON cli.CODIGOCLIENTE = S.C1803
LEFT JOIN DJ_BENEFICIARIOS ben WITH(NOLOCK) ON ben.NRO_CAUSA = cau.NRO_CAUSA AND ben.TZ_LOCK = 0
LEFT JOIN CLI_DOCUMENTOSPFPJ doc WITH(NOLOCK) ON ben.ID_BENEFICIARIO = doc.NUMEROPERSONAFJ AND doc.TZ_LOCK = 0
WHERE cau.TZ_LOCK = 0 AND ISNUMERIC(CAU.EXPEDIENTE) = 1 
)
')