IF OBJECT_ID ('dbo.ITF_DD_PRESENT_RECIB_RECHAZOS') IS NOT NULL
	DROP TABLE dbo.ITF_DD_PRESENT_RECIB_RECHAZOS
GO

CREATE TABLE dbo.ITF_DD_PRESENT_RECIB_RECHAZOS
	(
	  ID                 INT IDENTITY NOT NULL
	, ID_TICKET          NUMERIC (16) NULL
	, FECHAPROCESO       DATETIME NULL
	, CODIGO_TRANSACCION VARCHAR (2) NULL
	, ENTIDAD_DEBITAR    VARCHAR (8) NULL
	, CUENTA_DEBITAR     VARCHAR (17) NULL
	, IMPORTE            VARCHAR (20) NULL
	, REFERENCIA_UNIVOCA VARCHAR (30) NULL
	, ID_CLIENTE_PAGADOR VARCHAR (22) NULL
	, INFO_ADICIONAL     VARCHAR (2) NULL
	, ESTADO             VARCHAR (1) NULL
	, CODIGO_ERROR       NUMERIC(3,0) NULL
	, SALDO_JTS_OID      NUMERIC (10) NULL
	, MONEDA             NUMERIC (4) NULL
	, fecha_vto          DATE NULL
	, fecha_comp         DATE NULL
	, cbu                VARCHAR (22) NULL
	, referencia         VARCHAR (15) NULL
	, cliente_pagador    VARCHAR (22) NULL
	, cuit_eo            NUMERIC (11) NULL
	, prestacion         VARCHAR (10) NULL
	, TRACENUMBER        VARCHAR (15) NULL
	, CONSTRAINT PK__ITF_DD_PRESENT_RECIB_RECHAZOS PRIMARY KEY (ID)
	)
GO

