EXECUTE('
----------------------------------------------------------------
--AJUSTE DE MOVIMIENTOS DESCARTADOS RENOVACIONES DPF CON ERROR--
----------------------------------------------------------------
WITH MOVS AS (
	SELECT
		DENSE_RANK() OVER (PARTITION BY SALDO_JTS_OID ORDER BY SALDO_JTS_OID, FECHAPROCESO, JTS_OID) AS ID_LINEA,
		MC.JTS_OID,
		MC.SALDO_JTS_OID,
		MC.FECHAPROCESO
	FROM MOVIMIENTOS_CONTABLES AS MC
	WHERE MC.SALDO_JTS_OID IN (
		SELECT JTS_OID from SALDOS (NOLOCK) WHERE C1785 = 4 AND C1621 = C1627
	) AND OPERACION = 8620
)

UPDATE MC
	SET
		COD_TRANSACCION = 99002 --Código transacción movimientos descartados.
FROM MOVIMIENTOS_CONTABLES AS MC
INNER JOIN MOVS AS M ON
	M.JTS_OID = MC.JTS_OID
	AND M.ID_LINEA > 2
')
	
	
