EXECUTE('
----
INSERT INTO dbo.CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN, NOTACION_REGIMEN)
VALUES (0, 2784, 3, ''20230419'', ''Intereses por otro tipo de Operaciones'',''R.G. AFIP 3130/90'')
--
INSERT INTO dbo.CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN, NOTACION_REGIMEN)
VALUES (0, 2784, 4, ''20230419'', ''Intereses por otro tipo de Operaciones'',''R.G. AFIP 830/00'')
--
INSERT INTO dbo.CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN, NOTACION_REGIMEN)
VALUES (0, 2784, 12, ''20230419'', ''Intereses por otro tipo de Operaciones'',''Resolución Nº 352 / AGIP / 2022'')
----
INSERT INTO dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 3, ''C'', 3, ''IVA RETENCION'')
--
INSERT INTO dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 4, ''C'', 4, ''IGA'')
--
INSERT INTO dbo.CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 12, ''C'', 12, ''IIBB CABA RET'')
----
')