


-- Parche_NUGAN106_605

-- Parche_NUGAN106_605

-- Add salt column in usuarios table
ALTER TABLE USUARIOS ADD SALT VARCHAR(250);
		ALTER TABLE USUARIOS ADD CONTRASENIASUSADAS_SALT VARCHAR(250);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20241217_4',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVUdBTjEwNl82MDUKDQotLSBQYXJjaGVfTlVHQU4xMDZfNjA1Cg0KLS0g
QWRkIHNhbHQgY29sdW1uIGluIHVzdWFyaW9zIHRhYmxlDQpBTFRFUiBUQUJMRSBVU1VBUklPUyBB
REQgU0FMVCBWQVJDSEFSKDI1MCk7CgkJQUxURVIgVEFCTEUgVVNVQVJJT1MgQUREIENPTlRSQVNF
TklBU1VTQURBU19TQUxUIFZBUkNIQVIoMjUwKTsKDQoKCg0K', NULL, 0);
