EXECUTE('
-- Elimino parametros jts agregados
DELETE FROM PARAMETROS_JTS 
        WHERE FUNCIONALIDAD = ''PROCESO_CAMBIO_SUCURSAL'' 
        AND PARAMETRO IN (''PIVOT_INTERES_DEVENG_VIG_F1'', 
                          ''PIVOT_IPF_DEVENGADO_VIGENTE'', 
                          ''PIVOT_IPF_DEVENGADO_VIG_F1'', 
                          ''PIVOT_IPF_MORATORIO_DEV_VIG'', 
                          ''PIVOT_MULTA_PMOS_EN_MORA'',
						  ''PIVOT_INT_VIGENTE_CH_ESPECIAL'', 
                          ''PIVOT_INT_SUSPENSOS_CH_ESPECIAL'', 
                          ''PIVOT_INTERESES_AD_VIGENTES'', 
                          ''PIVOT_INTERESES_AD_SUSPENSOS'',
						  ''NRO_CAMPO_INT_VIGENTES'');
')

EXECUTE('
-- Elimino tabla PARAMETROS_PREJUIZO
DROP TABLE PARAMETROS_PREJUIZO;
')


EXECUTE('
INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES (''20250221_1NBCH'',NULL,''MANUAL'',''NO_DEFINIDO'',''CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fMTgxMwoNCi0tIEVsaW1pbm8gcGFyYW1ldHJvcyBqdHMg
YWdyZWdhZG9zDQpERUxFVEUgRlJPTSBQQVJBTUVUUk9TX0pUUyAKICAgICAgICBXSEVSRSBGVU5D
SU9OQUxJREFEID0gJ1BST0NFU09fQ0FNQklPX1NVQ1VSU0FMJyAKICAgICAgICBBTkQgUEFSQU1F
VFJPIElOICgnUElWT1RfSU5URVJFU19ERVZFTkdfVklHX0YxJywgCiAgICAgICAgICAgICAgICAg
ICAgICAgICAgJ1BJVk9UX0lQRl9ERVZFTkdBRE9fVklHRU5URScsIAogICAgICAgICAgICAgICAg
ICAgICAgICAgICdQSVZPVF9JUEZfREVWRU5HQURPX1ZJR19GMScsIAogICAgICAgICAgICAgICAg
ICAgICAgICAgICdQSVZPVF9JUEZfTU9SQVRPUklPX0RFVl9WSUcnLCAKICAgICAgICAgICAgICAg
ICAgICAgICAgICAnUElWT1RfTVVMVEFfUE1PU19FTl9NT1JBJywKCQkJCQkJICAnUElWT1RfSU5U
X1ZJR0VOVEVfQ0hfRVNQRUNJQUwnLCAKICAgICAgICAgICAgICAgICAgICAgICAgICAnUElWT1Rf
SU5UX1NVU1BFTlNPU19DSF9FU1BFQ0lBTCcsIAogICAgICAgICAgICAgICAgICAgICAgICAgICdQ
SVZPVF9JTlRFUkVTRVNfQURfVklHRU5URVMnLCAKICAgICAgICAgICAgICAgICAgICAgICAgICAn
UElWT1RfSU5URVJFU0VTX0FEX1NVU1BFTlNPUycsCgkJCQkJCSAgJ05ST19DQU1QT19JTlRfVklH
RU5URVMnKTsKDQotLSBFbGltaW5vIHRhYmxhIFBBUkFNRVRST1NfUFJFSlVJWk8NCkRST1AgVEFC
TEUgUEFSQU1FVFJPU19QUkVKVUlaTzsKDQoKCg0K'', NULL, 0);
')