EXECUTE('
CREATE OR ALTER    PROCEDURE [dbo].[SP_ITF_SOS_CUENTAS_CONT]
	@FechaIni VARCHAR(8),
	@FechaFin VARCHAR(8)
AS
  DECLARE @PERIODO VARCHAR(6);
  DECLARE @FECHAPROCESO VARCHAR(8);
  
BEGIN
	
  SELECT @FECHAPROCESO = CONVERT(VARCHAR, FECHAPROCESO, 112) FROM PARAMETROS
  
  SET @PERIODO = SUBSTRING(CONVERT(VARCHAR, @FechaIni, 112),1,6);
  
	--Limpiamos por si hay reproceso
	DELETE FROM SOS_CUENTAS_CONT WHERE PERIODO = @PERIODO;
	
	INSERT INTO SOS_CUENTAS_CONT
	SELECT distinct
		--1
		EMPRESA, 
		--2
		@PERIODO,
		--3
		@FECHAPROCESO AS FECHADEINFORMACION,
		--4
		CLASEDECUENTA,
		--5
		NUMERODECUENTA,
		--6
	    SUCURSALSISCENCTA,                    
		--7
		ISNULL(FECHAAPERTURACUENTA,0),
		--8
		CODCLIENTE
		--SELECT mov.*
	FROM SOS_MOVS_HISTORICOS MOV
	WHERE mov.FECHADEINFORMACION BETWEEN @FechaIni AND @FechaFin

END
')