

EXECUTE('
IF OBJECT_ID (''dbo.TJD_TMP_MODIF_TARJETA_CUENTA'') IS NOT NULL
	DROP TABLE dbo.TJD_TMP_MODIF_TARJETA_CUENTA
')

EXECUTE ('


CREATE TABLE dbo.TJD_TMP_MODIF_TARJETA_CUENTA
	(
	ID_TARJETA     VARCHAR (19) DEFAULT ('' '') NOT NULL,
	SALDO_JTS_OID  NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ESTADO         VARCHAR (2) DEFAULT ('' '') NULL,
	CODIGO_USUARIO VARCHAR (8) DEFAULT ('' '') NULL,
	TZ_LOCK        NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_TJD_TMP_MODIF_TARJETA_CU_01 PRIMARY KEY (ID_TARJETA, SALDO_JTS_OID)
	)

')