EXECUTE('
ALTER TABLE SNP_ADHESIONES ADD COD_ENT_DESTINO VARCHAR(4) NULL

ALTER TABLE SNP_ADHESIONES ADD COD_SUC_DESTINO VARCHAR(4) NULL

ALTER TABLE SNP_ADHESIONES ADD FECHA_RECEPCION DATETIME NULL

ALTER TABLE SNP_ADHESIONES ADD IDENTIF_ARCHIVO VARCHAR(1) NULL
')