EXECUTE('
UPDATE OPERACIONES
SET COMPORTAMIENTOENCIERRE=''I''
WHERE IDENTIFICACION = 8613
')

EXECUTE('
UPDATE OPERACIONES
SET COMPORTAMIENTOENCIERRE=''I''
WHERE IDENTIFICACION = 6115
')

EXECUTE('
UPDATE OPERACIONES
SET COMPORTAMIENTOENCIERRE=''I''
WHERE IDENTIFICACION = 6116
')

EXECUTE('
UPDATE OPERACIONES
SET COMPORTAMIENTOENCIERRE=''I''
WHERE IDENTIFICACION = 6080
')