EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45790, '' '', 0, ''Cod Entidad Destino'', ''Cod Entidad Destino'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4453, ''COD_ENT_DESTINO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45791, '' '', 0, ''Cod Sucursal Destino'', ''Cod Sucursal Destino'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4453, ''COD_SUC_DESTINO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45792, '' '', 0, ''Fecha Recepción'', ''Fecha Recepción'', 8, ''F'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4453, ''FECHA_RECEPCION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45793, '' '', 0, ''Identificación de Archivo'', ''Identificación de Archivo'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4453, ''IDENTIF_ARCHIVO'', 0, NULL)
')