EXECUTE('
IF OBJECT_ID (''dbo.SOS_TRANSFERENCIAS'') IS NOT NULL
	DROP TABLE dbo.SOS_TRANSFERENCIAS
')

EXECUTE('
CREATE TABLE dbo.SOS_TRANSFERENCIAS
	(
	EMPRESA                      NUMERIC (4) NOT NULL,
	PERIODO                      VARCHAR (6) NOT NULL,
	FECHADEINFORMACION           NUMERIC (8) NOT NULL,
	NUMERODECUENTA               VARCHAR (22),
	NUMERODEOPERACION            VARCHAR (22),
	CLASEDECUENTA                VARCHAR (3),
	TIPODECUENTAUOPERACION       VARCHAR (3),
	SUCURSALSISCEN               VARCHAR (5),
	SUCURSALINTERNA              VARCHAR (5),
	FECHADELAOPERACION           NUMERIC (8),
	MONTOPESOS                   NUMERIC (15, 2),
	ESPECIETRANSADACANTIDAD      NUMERIC (15, 2),
	ESPECIETRANSADATIPO          VARCHAR (10),
	BANCOCORRESPONSALSWIFT       VARCHAR (12),
	BENEFICIARIOORDENANTEDELEXTE VARCHAR (50),
	PAISDELBENEFICIARIOORDENANTE VARCHAR (2),
	DATOSADICIONALES             VARCHAR (80),
	FECHAALTA                    VARCHAR (8),
	CODIGOSTOPAZ                 VARCHAR (15),
	COTIZACION                   NUMERIC (15),
	REVERSADA                    VARCHAR (2),
	OPER_ID_BIC_SWIFT            VARCHAR (100),
	RTE_OPE_FON_CUIT_CUIL_CDI    VARCHAR (11),
	RTE_OPE_FON_TIPO_PERSONA     VARCHAR (2),
	RTE_OPE_FON_DENOMINACION     VARCHAR (100),
	RTE_OPE_FON_APELLIDOS        VARCHAR (50),
	RTE_OPE_FON_NOMBRES          VARCHAR (50),
	RTE_OPE_FON_TIPODOC          VARCHAR (5),
	RTE_OPE_FON_NUMDOC           VARCHAR (10),
	RTE_TIT_FON_CUIT_CUIL_CDI    VARCHAR (11),
	RTE_TIT_FON_TIPO_PERSONA     VARCHAR (2),
	RTE_TIT_FON_DENOMINACION     VARCHAR (100),
	RTE_TIT_FON_APELLIDOS        VARCHAR (50),
	RTE_TIT_FON_NOMBRES          VARCHAR (50),
	RTE_TIT_FON_TIPODOC          VARCHAR (5),
	RTE_TIT_FON_NUMDOC           VARCHAR (10),
	RTI_TIPOPERSONA              VARCHAR (2),
	RTI_TIPOOPERACION_COMEX      VARCHAR (10),
	REL_FON_TIT                  VARCHAR (30),
	REL_PRO_TIT                  VARCHAR (30),
	REL_FON_OPER                 VARCHAR (30),
	REL_PRO_OPER                 VARCHAR (30),
	FECHAAPERTURACUENTA          NUMERIC (8),
	CODCLIENTE                   NUMERIC (12),
	SUCURSALSISCENCTA            NUMERIC (5),
	SALDO_JTS_OID                NUMERIC (12)
	)
')