DROP TABLE IF EXISTS dbo.BE_TRANSFERENCIAS;
DROP TABLE IF EXISTS dbo.ITF_BEE_TRANSFERENCIAS;
DROP TABLE IF EXISTS dbo.ITF_BEE_TRANSFERENCIAS_CABECERA;
DROP TABLE IF EXISTS dbo.ITF_BEE_TRANSFERENCIAS_HISTORICO;
DROP TABLE IF EXISTS dbo.ITF_BEE_TRANSFERENCIAS_CURSADAS;

CREATE TABLE dbo.ITF_BEE_TRANSFERENCIAS (
	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TRANSFERENCIA NUMERIC(9,0) NOT NULL,
	DEBITO_CUIT NUMERIC(13,0) NULL,
	DEBITO_BANCO VARCHAR(4) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_TIPO_CUENTA VARCHAR(2) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_NUMERO_CUENTA VARCHAR(19) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_NOMBRE_CUENTA varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_CBU VARCHAR(23) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_JTS_OID NUMERIC(10,0) NULL,
	DEBITO_NUMERO_PERSONA NUMERIC(12,0) NULL,
	CREDITO_BANCO VARCHAR(4) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_TIPO_CUENTA VARCHAR(2) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_NUMERO_CUENTA VARCHAR(19) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_NOMBRE_CUENTA VARCHAR(50) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_CBU VARCHAR(23) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_JTS_OID NUMERIC(10,0) NULL,
	CREDITO_NUMERO_PERSONA NUMERIC(12,0) NULL,
	IMPORTE numeric(15,2) NULL,
	CONCEPTO varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	IMPUTACION_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	ALTA_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	ALTA_HORA VARCHAR(6) COLLATE Modern_Spanish_CI_AS NULL,
	ALTA_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION1_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION1_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION1_HORA VARCHAR(6) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION2_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION2_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION2_HORA VARCHAR(6) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION3_USUARIO VARCHAR(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION3_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION3_HORA VARCHAR(6) COLLATE Modern_Spanish_CI_AS NULL,
	ENVIO_FECHA VARCHAR(8) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_CUIT NUMERIC(13,0) NULL,
	CREDITO_TITULARIDAD VARCHAR(1) COLLATE Modern_Spanish_CI_AS NULL,
	MOTIVO VARCHAR(3) COLLATE Modern_Spanish_CI_AS NULL,
	REFERENCIA VARCHAR(12) COLLATE Modern_Spanish_CI_AS NULL,
	ESTADO VARCHAR(1) COLLATE Modern_Spanish_CI_AS NULL, -- "R"echazada / "C"ursada / "P"endiente
	ESTADO_DESCRIPCION VARCHAR(100) COLLATE Modern_Spanish_CI_AS NULL,
	TIPO_TRANSFERENCIA VARCHAR(1) COLLATE Modern_Spanish_CI_AS NOT NULL --"I"nterbanco / "M"onobanco
);

CREATE TABLE dbo.ITF_BEE_TRANSFERENCIAS_CABECERA (
	LOCK char(1) COLLATE Modern_Spanish_CI_AS DEFAULT 'X' NOT NULL PRIMARY KEY,
	NOMBRE_ARCHIVO varchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MD5 varchar(80) COLLATE Modern_Spanish_CI_AS NOT NULL,
	FECHA_ARCHIVO date NOT NULL,
	ESTADO varchar(1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CONSTRAINT CK_ITF_BEE_TRANSFERENCIAS_CABECERA_LOCKED CHECK (LOCK='X')
);

CREATE TABLE dbo.ITF_BEE_TRANSFERENCIAS_CURSADAS (
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE_ARCHIVO VARCHAR(50) NOT NULL,
	FECHA_PROCESO DATE NOT NULL,
	TRANSFERENCIA NUMERIC(9,0) NOT NULL,
	DEBITO_CUIT NUMERIC(13,0) NULL,
	DEBITO_BANCO VARCHAR(4) NULL,
	DEBITO_TIPO_CUENTA VARCHAR(2) NULL,
	DEBITO_NUMERO_CUENTA VARCHAR(19) NULL,
	DEBITO_NOMBRE_CUENTA varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	DEBITO_CBU VARCHAR(23) NULL,
	DEBITO_JTS_OID NUMERIC(10,0) NULL,
	CREDITO_CUIT NUMERIC(13,0) NULL,
	CREDITO_BANCO VARCHAR(4) NULL,
	CREDITO_TIPO_CUENTA VARCHAR(2) NULL,
	CREDITO_NUMERO_CUENTA VARCHAR(19) NULL,
	CREDITO_NOMBRE_CUENTA VARCHAR(50) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_CBU VARCHAR(23) NULL,
	CREDITO_TITULARIDAD VARCHAR(1) COLLATE Modern_Spanish_CI_AS NULL,
	CREDITO_JTS_OID NUMERIC(10,0) NULL,
	IMPORTE numeric(15,2) NULL,
	CONCEPTO varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	IMPUTACION_FECHA VARCHAR(8) NULL,
	ALTA_FECHA VARCHAR(8) NULL,
	ALTA_HORA VARCHAR(6) NULL,
	ALTA_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION1_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION1_FECHA VARCHAR(8) NULL,
	AUTORIZACION1_HORA VARCHAR(6) NULL,
	AUTORIZACION2_USUARIO varchar(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION2_FECHA VARCHAR(8) NULL,
	AUTORIZACION2_HORA VARCHAR(6) NULL,
	AUTORIZACION3_USUARIO VARCHAR(13) COLLATE Modern_Spanish_CI_AS NULL,
	AUTORIZACION3_FECHA VARCHAR(8) NULL,
	AUTORIZACION3_HORA VARCHAR(6) NULL,
	ENVIO_FECHA VARCHAR(8) NULL,
	MOTIVO VARCHAR(3) COLLATE Modern_Spanish_CI_AS NULL,
	REFERENCIA VARCHAR(12) COLLATE Modern_Spanish_CI_AS NULL,
	ESTADO VARCHAR(1) COLLATE Modern_Spanish_CI_AS NULL,
	ESTADO_DESCRIPCION VARCHAR(100) COLLATE Modern_Spanish_CI_AS NULL,
	TIPO_TRANSFERENCIA VARCHAR(1) COLLATE Modern_Spanish_CI_AS NULL
);

DELETE FROM OPERACIONES WHERE IDENTIFICACION = 9965;
INSERT INTO OPERACIONES (TITULO,IDENTIFICACION,NOMBRE,DESCRIPCION,MNEMOTECNICO,AUTORIZACION,FORMULARIOPRINCIPAL,PROXOPERACION,ESTADO,TZ_LOCK,COPIAS,SUBOPERACION,PERMITEBAJA,COMPORTAMIENTOENCIERRE,REQUIERECONTRASENA,PERMITECONCURRENTE,PERMITEESTADODIFERIDO,ICONO_TITULO,ESTILO) VALUES
	 (7901,9965,N'INSERT VTA_TRANSFERENCIAS',N'INSERT VTA_TRANSFERENCIAS',N'9965',N'N',NULL,NULL,N'P',0,NULL,0,N'S',N'N',N'N',N'N',N'N',NULL,0);

