EXECUTE('
--extornar lo del día 05/03

DECLARE @fecha VARCHAR(10)

SELECT @fecha = format(fechaproceso, ''yyyyMMdd'') FROM PARAMETROS

INSERT INTO dbo.BANDEJA_ASIENTOS_IN (ESTADO, ORIGEN, OPERACION, DESCRIPCION, FECHAPROCESO)

VALUES (''S'', ''CON'',  8624, (SELECT DESCRIPCION FROM BANDEJA_ORIGENES WHERE ORIGEN=''CON''), @fecha)

INSERT INTO dbo.BANDEJA_MOVS_IN (JTS_OID_ASIENTO, SUCURSAL, PRODUCTO, 

    CUENTA, MONEDA, OPERACION, ORDINAL, CLIENTE, SIGNO, MONTO, CONCEPTO, RUBRO_CONTABLE,RUBRO_OPERATIVO, 
    
    plazo, fecha_valor, moneda_monto,MARCA_AJUSTE)

select (SELECT MAX(JTS_OID) FROM BANDEJA_ASIENTOS_IN WHERE ESTADO=''S'' AND ORIGEN=''CON''),

   M.SUCURSAL_CUENTA,M.PRODUCTO, m.CUENTA, m.MONEDA,M.OPERACION_CUENTA,M.ORDINAL_CUENTA,M.CLIENTE,CASE WHEN M.DEBITOCREDITO = ''D'' THEN ''C'' ELSE ''D'' END,

   M.CAPITALREALIZADO,Concat(''Extorno '',M.CONCEPTO),M.RUBROCONTABLE, case when M.RUBROCONTABLE=1317910000 then 124000 else 123001 end , 0, ''20250305'', m.MONEDA, ''A'' 

   from MOVIMIENTOS_CONTABLES m, asientos a with (nolock) where (( m.rubrocontable in (1317910000) and m.producto=92)  

    or (m.RUBROCONTABLE=1317180001 and m.producto=0) ) and  

    m.FECHAPROCESO=a.FECHAPROCESO and 

    m.ASIENTO=a.ASIENTO and 

    m.SUCURSAL=a.SUCURSAL and 

    a.ESTADO=77 and 

   m.OPERACION not in (1) 
   order by m.SUCURSAL_CUENTA
  
  
  ---------
  
  
  -----asiento corregido

INSERT INTO dbo.BANDEJA_ASIENTOS_IN (ESTADO, ORIGEN, OPERACION, DESCRIPCION, FECHAPROCESO)

VALUES (''S'', ''CON'',  8624, (SELECT DESCRIPCION FROM BANDEJA_ORIGENES WHERE ORIGEN=''CON''), @fecha)

INSERT INTO dbo.BANDEJA_MOVS_IN (JTS_OID_ASIENTO, SUCURSAL, PRODUCTO, 

    CUENTA, MONEDA, OPERACION, ORDINAL, CLIENTE, SIGNO, MONTO, CONCEPTO, RUBRO_CONTABLE,RUBRO_OPERATIVO, 
    
    plazo, fecha_valor, moneda_monto,MARCA_AJUSTE)

select (SELECT MAX(JTS_OID) FROM BANDEJA_ASIENTOS_IN WHERE ESTADO=''S'' AND ORIGEN=''CON''),

   M.SUCURSAL_CUENTA, case when M.PRODUCTO=0 then 92 else 0 end , m.CUENTA, m.MONEDA,M.OPERACION_CUENTA,M.ORDINAL_CUENTA,M.CLIENTE, M.DEBITOCREDITO ,

   M.CAPITALREALIZADO,Concat(''Ajuste '',M.CONCEPTO),M.RUBROCONTABLE, case when M.RUBROCONTABLE=1317910000 then 124000 else 123001 end , 0, ''20250305'', m.MONEDA, ''A'' 

   from MOVIMIENTOS_CONTABLES m, asientos a with (nolock) where (( m.rubrocontable in (1317910000) and m.producto=92)  

    or (m.RUBROCONTABLE=1317180001 and m.producto=0) ) and  

    m.FECHAPROCESO=a.FECHAPROCESO and 

    m.ASIENTO=a.ASIENTO and 

    m.SUCURSAL=a.SUCURSAL and 

    a.ESTADO=77 and m.FECHAPROCESO=''2025-03-05'' and

   m.OPERACION not in (1) 
   order by m.SUCURSAL_CUENTA
 ')
 EXECUTE('
 update  S2 set s2.c1620=''2025-03-05'', s2.c1621=''2025-03-05''
FROM  saldos S1 inner join SALDOS S2
on S1.sucursal=S2.SUCURSAL and  S1.moneda=S2.MONEDA and  S1.OPERACION= S2.operacion and S1.ordinal=S2.ORDINAL
where S2.CUENTA=1317180001 and s2.C1620>''20250305'' and 
s1.PRODUCTO in(26000,26620) and s1.C1620=''20250305''
')