EXECUTE('

IF OBJECT_ID (''dbo.VW_CERTIF_IVA'') IS NOT NULL
	DROP VIEW dbo.VW_CERTIF_IVA

')

EXECUTE('

CREATE   VIEW [dbo].[VW_CERTIF_IVA]
AS
SELECT *
FROM CON_BITACORA_IMPUESTOS CBI WITH (nolock)
WHERE CBI.TABLA_CARGOS_IMPUESTOS IS NULL AND 
	CBI.ID_CLIENTE IS NOT NULL
	AND CBI.TIPO_NOVEDAD = ''A''
	AND CBI.FECHA_FIN > (select fechaproceso from parametros)

')