EXECUTE('
ALTER   PROCEDURE [dbo].[SP_ITF_SOS_CUENTAS]
	@Fecha VARCHAR(8)
AS
  DECLARE @FECHAPROCESO VARCHAR(8);
BEGIN

SELECT @FECHAPROCESO = CONVERT(VARCHAR,FECHAPROCESO,112) FROM PARAMETROS WITH (NOLOCK);

--Limpiamos por si hay reproceso
DELETE FROM SOS_CUENTAS WHERE convert(VARCHAR,FECHADEINFORMACION) = @FECHAPROCESO;

INSERT INTO SOS_CUENTAS
SELECT distinct
	--1
	EMPRESA, 
	--2
	FECHADEINFORMACION AS FECHADEINFORMACION,
	--3
	CLASEDECUENTA,
	--4
	NUMERODECUENTA,
	--5
    SUCURSALSISCENCTA,                    
	--6
	ISNULL(FECHAAPERTURACUENTA,0),
	--7
	CODCLIENTE
	--SELECT mov.*
FROM SOS_MOVS_HISTORICOS MOV
WHERE mov.FECHADEINFORMACION = @FECHAPROCESO

END
')