EXECUTE('
IF OBJECT_ID (''dbo.VW_NUMERACION_CUENTAS_VISTA'') IS NOT NULL
	DROP VIEW dbo.VW_NUMERACION_CUENTAS_VISTA
')
EXECUTE('
CREATE VIEW VW_NUMERACION_CUENTAS_VISTA (
	CUENTA,
	SIG_NUMERACION,
	PROX_CUENTA,
	CLIENTE,
	TIPO_CUENTA,
	SALDO_JTS_OID
)
AS
WITH CUENTAS AS (
	SELECT
		CUENTA,
		C1785 AS TIPO_CUENTA
	FROM SALDOS
	WHERE C1785 IN (2,3)
	GROUP BY CUENTA, C1785
	
	UNION
	
	SELECT
		S.CUENTA,
		P.C6252 AS TIPO_CUENTA
	FROM SOLICAPERTCTAVISTA AS S
	INNER JOIN PRODUCTOS AS P ON
		P.C6250 = S.PRODUCTO
	GROUP BY CUENTA, P.C6252
),

NUMERACIONES AS (
	SELECT CUENTA, CUENTA + 1 AS SIG_NUMERACION, PROX_CUENTA, TIPO_CUENTA
	FROM (
		SELECT CUENTA, LEAD(CUENTA) OVER(PARTITION BY TIPO_CUENTA ORDER BY CUENTA) AS PROX_CUENTA, TIPO_CUENTA
		FROM CUENTAS
	) T
)

SELECT
	S.CUENTA,
	N.SIG_NUMERACION,
	N.PROX_CUENTA,
	S.C1803 AS CLIENTE,
	S.C1785 AS TIPO_CUENTA,
	S.JTS_OID
FROM SALDOS AS S
INNER JOIN NUMERACIONES AS N ON
	N.CUENTA = S.CUENTA
	AND N.TIPO_CUENTA = S.C1785
WHERE
	S.C1785 IN (2,3)
')

