EXECUTE('
IF OBJECT_ID (''dbo.ITF_PADRON_IMPUESTOS'') IS NOT NULL
   DROP TABLE dbo.ITF_PADRON_IMPUESTOS
')


EXECUTE('
CREATE TABLE dbo.ITF_PADRON_IMPUESTOS
	(
	ID              INT IDENTITY,
	CUIT            NUMERIC,
	RAZON_SOCIAL    VARCHAR (44),
	PERIODO_ARCHIVO VARCHAR (6),
	ALICUOTA        NUMERIC,
	CONSTRAINT PK_PADRON PRIMARY KEY (ID)
	);
')