EXECUTE('
ALTER function FN_ACTUALIZACIONES_PADRON (@fch_proceso DATETIME) 
RETURNS TABLE 
AS 
RETURN

WITH AUX AS ( 
-- Alta personas fisicas
SELECT
		@fch_proceso as FECHAPROCESO,--P.FECHAPROCESO,
		D.NUMERODOCUMENTO, 
		10 AS TIPOMOVIMIENTO, 
		PP.TIPO_IDENT_TRIB, 
		PP.TIPO_DOCUMENTO_IDENTIDAD, 
		D.NUM_DOC_FISICO,
		PF.PRIMERNOMBRE+'' ''+PF.SEGUNDONOMBRE+'' ''+PF.APELLIDOPATERNO+'' ''+PF.APELLIDOMATERNO AS DENOMINACION,
		CASE 
			WHEN PF.INCLUIDO_PEP = ''N'' THEN
				''2'' 
			ELSE
				''1''
		END AS PEP_CAMBIO,
		CASE 
			WHEN (PF.CODIGODERESIDENCIA = 3) THEN 
				RIGHT(Ltrim(Rtrim(CP.CODIGOSWIFT)),4)
			ELSE 
				DIR.CPA_NUEVO	
		END SCOD_POSTAL_CAMBIO
		
FROM CLI_DocumentosPFPJ D WITH(nolock) 

INNER JOIN CLI_PERSONASFISICAS PF WITH(nolock) ON 
	D.NUMEROPERSONAFJ = PF.NUMEROPERSONAFISICA AND
	PF.TZ_LOCK = 0 AND
	PF.ESTADO = 0
	
INNER JOIN CLI_DIRECCIONES DIR WITH(nolock) ON 
	DIR.ID = PF.NUMEROPERSONAFISICA
	AND DIR.TIPODIRECCION = CASE WHEN PF.CODIGODERESIDENCIA =2 THEN ''PR'' ELSE ''ED'' END
	AND DIR.TZ_LOCK = 0

-- voy con PAIS de CLI_DIRECCIONES a la CLI_PAISES por su campo CODIGOPAIS   
INNER JOIN CLI_PAISES CP WITH(nolock) ON 
	CP.CODIGOPAIS = DIR.PAIS AND
	CP.TZ_LOCK = 0
										
INNER JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON 
	D.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC 
	AND D.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.NACIONALIDAD = (SELECT CASE WHEN D.COD_PAIS_ORIGEN=32 THEN ''N'' ELSE ''E'' END)
	AND PP.TZ_LOCK = 0

--Chequeo en pyf_apoderados, para saber si es tutor / curador, con cod_apoderamiento = 5
INNER JOIN PYF_APODERADOS APO WITH(nolock) ON 
	PF.NUMEROPERSONAFISICA = APO.ID_PERSONA AND
	APO.TIPO_ENTIDAD = 1 AND
	APO.TZ_LOCK = 0
	
WHERE PF.FECHAALTA BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	AND PF.NUMEROPERSONAFISICA IN (	SELECT NUMEROPERSONA 
									FROM CLI_CLIENTEPERSONA CP WITH(nolock) 
 									LEFT JOIN CLI_CLIENTES C WITH(nolock) ON CP.CODIGOCLIENTE = C.CODIGOCLIENTE 
										AND C.FECHAAPERTURA BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
  									WHERE CP.FECHAALTARELACION BETWEEN @fch_proceso AND EOMONTH(@fch_proceso))

	AND D.TZ_LOCK=0 

UNION ALL

-- persona juridica, lo mismo que la fisica. Solamente que pj siempre es con pais 32, nunca es extranjera

-- PERSONA JURIDICA ALTA

SELECT	DISTINCT 
		@fch_proceso as FECHAPROCESO,-- FECHA PARAMETRO,
		D.NUMERODOCUMENTO, 
		10 AS TIPOMOVIMIENTO, 
		PP.TIPO_IDENT_TRIB, 
		PP.TIPO_DOCUMENTO_IDENTIDAD, 
		D.NUM_DOC_FISICO, 
		PJ.RAZONSOCIAL AS DENOMINACION,
		CASE 
			WHEN PJ.INCL_PEPS = ''N'' THEN
				''2'' 
			ELSE
				''1''
		END AS PEP_CAMBIO, 
		CASE 
			WHEN (PJ.CODIGODERESIDENCIA = 3) THEN 
				RIGHT(Ltrim(Rtrim(CP.CODIGOSWIFT)),4)
			ELSE 
				DIR.CPA_NUEVO	
		END SCOD_POSTAL_CAMBIO

FROM CLI_INTEGRANTESPJ IPJ WITH(nolock), 
CLI_DocumentosPFPJ D WITH(nolock)

INNER JOIN CLI_PERSONASJURIDICAS PJ WITH(nolock) ON 
	D.NUMEROPERSONAFJ = PJ.NUMEROPERSONAJURIDICA AND
	PJ.TZ_LOCK = 0 AND 
	PJ.ESTADO = 0
	
INNER JOIN CLI_DIRECCIONES DIR WITH(nolock) ON 
	DIR.ID = PJ.NUMEROPERSONAJURIDICA 
	AND DIR.TIPODIRECCION = ''L'' AND
	DIR.TZ_LOCK = 0

-- voy con PAIS de CLI_DIRECCIONES a la CLI_PAISES por su campo CODIGOPAIS   
INNER JOIN CLI_PAISES CP WITH(nolock) ON 
	CP.CODIGOPAIS = DIR. PAIS AND 
	CP.TZ_LOCK = 0

INNER JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON 
	D.TIPOPERSONA = PP.TIPO_PERSONA
	AND D.TIPODOCUMENTO = PP.NOMBRE_TIPO_DOC 
	AND PP.NACIONALIDAD = ''N'' AND 
	PP.TZ_LOCK = 0
	
WHERE 
	PJ.FECHAALTA BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	AND PJ.NUMEROPERSONAJURIDICA IN (SELECT NUMEROPERSONA 
									FROM CLI_CLIENTEPERSONA CP WITH(nolock) 
 									LEFT JOIN CLI_CLIENTES C WITH(nolock) ON 
 										CP.CODIGOCLIENTE = C.CODIGOCLIENTE 
										AND C.FECHAAPERTURA BETWEEN @fch_proceso AND EOMONTH (@fch_proceso)
  									WHERE CP.FECHAALTARELACION BETWEEN @fch_proceso AND EOMONTH (@fch_proceso))
	AND PJ.NUMEROPERSONAJURIDICA = IPJ.NUMEROPERSONAJURIDICA
	AND IPJ.CODIGOCARGO IN (''SDE'',''FCO'',''APO'')
	AND PP.CARGO_SDE_FCO	=	CASE	WHEN IPJ.CODIGOCARGO = ''SDE'' THEN ''SDE''
  										WHEN IPJ.CODIGOCARGO = ''FCO'' THEN ''FCO''
  								ELSE ''N''
  								END
	AND DIR.ID = PJ.NUMEROPERSONAJURIDICA
	AND D.TZ_LOCK=0	
	AND IPJ.TZ_LOCK = 0
 -- duda de si consultar cargo de apoderado en PYF_APODERADOS o en CODIGOCARGO, como los anteriores
 --	OR PJ.NUMEROPERSONAJURIDICA IN (SELECT ID_PERSONA FROM PYF_APODERADOS))
UNION
/*
esto es para el punto B)
trae docs de personas fisicas que pertenecen a un cliente que se dio de baja en el mes actual
*/
--PERSONA FISICA BAJA 


SELECT	DISTINCT 
		@fch_proceso as FECHAPROCESO,--P.FECHAPROCESO,
		D.NUMERODOCUMENTO, 
		20 AS TIPOMOVIMIENTO, 
		PP.TIPO_IDENT_TRIB, 
		PP.TIPO_DOCUMENTO_IDENTIDAD,  
		D.NUM_DOC_FISICO, 
		PF.PRIMERNOMBRE+'' ''+PF.SEGUNDONOMBRE+'' ''+PF.APELLIDOPATERNO+'' ''+PF.APELLIDOMATERNO AS DENOMINACION,
		
		CASE 
			WHEN PF.INCLUIDO_PEP = ''N'' THEN
				''2''
			ELSE
				''1''
		END AS PEP_CAMBIO, 
		
		CASE 
			WHEN (PF.CODIGODERESIDENCIA = 3)
			THEN RIGHT(Ltrim(Rtrim(CPais.CODIGOSWIFT)),4)
			ELSE DIR.CPA_NUEVO	
		END SCOD_POSTAL_CAMBIO--,

FROM CLI_CLIENTES C WITH(nolock) 

INNER JOIN CLI_BLOQUEOS B WITH(nolock) on 
	C.CODIGOCLIENTE = B.NROCLIENTE AND
	B.TZ_LOCK = 0
	
INNER JOIN CLI_CLIENTEPERSONA CP WITH(nolock) on 
	C.CODIGOCLIENTE=CP.CODIGOCLIENTE AND
	CP.TZ_LOCK = 0

INNER JOIN CLI_PERSONASFISICAS PF WITH(nolock) 
	ON PF.NUMEROPERSONAFISICA = CP.NUMEROPERSONA
	AND PF.TZ_LOCK=0 

INNER JOIN PYF_APODERADOS APO WITH(nolock) ON 
	PF.NUMEROPERSONAFISICA = APO.ID_PERSONA AND
	APO.TIPO_ENTIDAD = 1 AND
	APO.TZ_LOCK = 0
	
INNER JOIN CLI_DocumentosPFPJ D WITH(nolock) on 
	D.NUMEROPERSONAFJ = PF.NUMEROPERSONAFISICA 
	AND D.TZ_LOCK=0

INNER JOIN CLI_DIRECCIONES DIR WITH(nolock) ON 
	DIR.ID = PF.NUMEROPERSONAFISICA
	AND DIR.TIPODIRECCION = CASE WHEN PF.CODIGODERESIDENCIA =2 THEN ''PR'' ELSE ''ED'' END
	AND DIR.TZ_LOCK = 0

-- voy con PAIS de CLI_DIRECCIONES a la CLI_PAISES por su campo CODIGOPAIS   
INNER JOIN CLI_PAISES CPais WITH(nolock) ON 
	CPais.CODIGOPAIS = DIR.PAIS AND 
	CPAIS.TZ_LOCK = 0
	
LEFT JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) 
	ON D.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC 
	AND D.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.NACIONALIDAD = (SELECT CASE WHEN D.COD_PAIS_ORIGEN=32 THEN ''N'' ELSE ''E'' END)
	AND PP.TZ_LOCK = 0

WHERE  C.ESTADO=1 
	AND PF.ESTADO = 1 	
	AND PF.NUMEROPERSONAFISICA IN (SELECT NUMEROPERSONA 
								FROM CLI_CLIENTEPERSONA CP WITH(nolock))
	AND B.FECHABLOQUEO BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	--Comentada porque sino no muestra ningun registro
--	AND (PF.NUMEROPERSONAFISICA IN (SELECT NUMEROPERSONAFISICA 
--								FROM CLI_INTEGRANTESPJ WITH(nolock) 
--								WHERE CODIGOCARGO IN(''REP'',''APO''))
--		OR APO.TIPO_PODER IN (	SELECT CODPODER 
--							FROM PYF_APODERAMIENTO  WITH(nolock)
--							WHERE CODAPODERAMIENTO = 5))
	AND C.TZ_LOCK = 0

UNION ALL

-- PERSONAS JURIDICAS BAJA

SELECT	DISTINCT 
		@fch_proceso as FECHAPROCESO,--P.FECHAPROCESO,
		D.NUMERODOCUMENTO, 
		20 AS TIPOMOVIMIENTO, 
		PP.TIPO_IDENT_TRIB, 
		PP.TIPO_DOCUMENTO_IDENTIDAD,
		D.NUM_DOC_FISICO , 
		PJ.RAZONSOCIAL AS DENOMINACION,
		CASE 
			WHEN PJ.INCL_PEPS = ''N'' THEN
				''2'' 
			ELSE
				''1''
		END AS PEP_CAMBIO, 
		CASE 
			WHEN (PJ.CODIGODERESIDENCIA = 3)
			THEN RIGHT(Ltrim(Rtrim(CPais.CODIGOSWIFT)),4)
			ELSE DIR.CPA_NUEVO	
		END SCOD_POSTAL_CAMBIO 
		
FROM CLI_CLIENTES C WITH(nolock)

INNER JOIN CLI_BLOQUEOS B WITH(nolock) ON  
	C.CODIGOCLIENTE=B.NROCLIENTE AND
	B.TZ_LOCK = 0
	
INNER JOIN CLI_CLIENTEPERSONA CP WITH(nolock) ON 
	C.CODIGOCLIENTE = CP.CODIGOCLIENTE AND
	CP.TZ_LOCK = 0
	
INNER JOIN CLI_PERSONASJURIDICAS PJ WITH(nolock) 
	ON PJ.NUMEROPERSONAJURIDICA = CP.NUMEROPERSONA
	AND PJ.TZ_LOCK=0 

INNER JOIN CLI_DocumentosPFPJ D WITH(nolock) ON  
	D.NUMEROPERSONAFJ = PJ.NUMEROPERSONAJURIDICA
	AND D.TZ_LOCK=0

LEFT JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON 
	D.TIPOPERSONA = PP.TIPO_PERSONA
	AND D.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC 
	AND PP.NACIONALIDAD = (SELECT CASE WHEN D.COD_PAIS_ORIGEN=32 THEN ''N'' ELSE ''E'' END)
	AND PP.TZ_LOCK = 0
	
INNER JOIN CLI_DIRECCIONES DIR WITH(nolock) ON 
	DIR.ID = PJ.NUMEROPERSONAJURIDICA
	AND DIR.TIPODIRECCION = ''L''
	AND DIR.TZ_LOCK = 0
	
-- voy con PAIS de CLI_DIRECCIONES a la CLI_PAISES por su campo CODIGOPAIS   
INNER JOIN CLI_PAISES CPais WITH(nolock) ON 
	CPais.CODIGOPAIS = DIR.PAIS 
	AND CPais.TZ_LOCK = 0
	
INNER JOIN CLI_INTEGRANTESPJ IPJ WITH(nolock) ON 
	PJ.NUMEROPERSONAJURIDICA = IPJ.NUMEROPERSONAJURIDICA
	AND IPJ.CODIGOCARGO IN (''SDE'',''FCO'',''APO'')
	AND IPJ.TZ_LOCK = 0
	
WHERE	C.ESTADO=1
		AND PJ.ESTADO=1
		
		AND B.FECHABLOQUEO BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)

		AND PJ.NUMEROPERSONAJURIDICA IN (	SELECT NUMEROPERSONA 
											FROM dbo.CLI_CLIENTEPERSONA CP WITH(nolock))
		AND PP.CARGO_SDE_FCO	=	CASE	WHEN IPJ.CODIGOCARGO = ''SDE'' THEN ''SDE''
  											WHEN IPJ.CODIGOCARGO = ''FCO'' THEN ''FCO''
  									ELSE ''N''
  									END
		AND C.TZ_LOCK = 0
),

ALTAS_PF_CPA AS ( 
	SELECT DISTINCT ID,
		CPA_NUEVO, 
		TIPODIRECCION 
	FROM BITACORA_DIRECCIONES 
	WHERE TIPO_TRAZA=''A'' AND 
		TZ_LOCK=0 AND 
		TIPODIRECCION = CASE WHEN PAIS =32 THEN ''PR'' ELSE ''ED'' END
		AND FORMATO=''PF''
),

ALTAS_PJ_CPA AS ( 
	SELECT DISTINCT ID,
		CPA_NUEVO, 
		TIPODIRECCION 
	FROM BITACORA_DIRECCIONES 
	WHERE TIPO_TRAZA=''A'' AND 
		TZ_LOCK=0 
		AND TIPODIRECCION=''L''
		AND FORMATO=''PJ''
),								
--Punto C)
AUX2 AS (

--PERSONA FISICA MODIFICACION CPA 

 SELECT
	MAX(BD.FECHA) AS MAX_FECHA,
	
	DOC.NUMERODOCUMENTO,
	
	30 AS TIPOMOVIMIENTO,
	
	PP.TIPO_IDENT_TRIB,
	
	PP.TIPO_DOCUMENTO_IDENTIDAD,
	
	DOC.NUM_DOC_FISICO,
	
	PF.PRIMERNOMBRE + '' '' + PF.SEGUNDONOMBRE + '' '' + PF.APELLIDOPATERNO + '' '' + PF.APELLIDOMATERNO AS DENOMINACION,
	
	CASE 
		WHEN PF.INCLUIDO_PEP = ''N'' THEN
			''2''
		ELSE
			''1''
	END AS PEP_CAMBIO,
	
	CASE
		WHEN D.PAIS = 32 THEN BD.CPA_NUEVO
		WHEN D.PAIS <> 32 THEN CONCAT(PA.CODIGOSWIFT, ''000000'')
	END SCOD_POSTAL_CAMBIO
	
FROM BITACORA_DIRECCIONES BD WITH(nolock)

INNER JOIN CLI_PERSONASFISICAS PF WITH(nolock) ON 
	BD.ID = PF.NUMEROPERSONAFISICA 
	AND PF.TZ_LOCK = 0

--Chequeo en pyf_apoderados, para saber si es tutor / curador, con cod_apoderamiento = 5
INNER JOIN PYF_APODERADOS APO WITH(nolock) ON 
	PF.NUMEROPERSONAFISICA = APO.ID_PERSONA AND
	APO.TIPO_ENTIDAD = 1 AND
	APO.TZ_LOCK = 0
	

INNER JOIN ALTAS_PF_CPA BD_AUX WITH(nolock) ON 
	BD.ID = BD_AUX.ID
	AND BD.CPA_NUEVO <> BD_AUX.CPA_NUEVO
	
INNER JOIN CLI_DIRECCIONES D WITH(nolock) ON 
	D.ID = BD_AUX.ID
	AND D.TZ_LOCK = 0
	
LEFT JOIN CLI_PAISES PA WITH(nolock) ON	
	D.PAIS = PA.CODIGOPAIS AND
	PA.TZ_LOCK = 0
	
INNER JOIN CLI_DocumentosPFPJ DOC WITH(nolock) ON 
	DOC.NUMEROPERSONAFJ = PF.NUMEROPERSONAFISICA AND
	DOC.TZ_LOCK = 0
	
LEFT JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON	
	DOC.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC
	AND DOC.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.NACIONALIDAD = (SELECT CASE WHEN DOC.COD_PAIS_ORIGEN=32 THEN ''N'' ELSE ''E'' END)
	AND PP.TZ_LOCK = 0


WHERE 
	PF.ESTADO=0
	AND BD.TZ_LOCK = 0
	AND BD.TIPODIRECCION= CASE WHEN BD.PAIS =32 THEN ''PR'' ELSE ''ED'' END
	AND BD.TIPO_TRAZA=''M''
	AND BD.FECHA_MODIFICACION BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	AND PF.NUMEROPERSONAFISICA IN (
										SELECT
											NUMEROPERSONA
										FROM
											CLI_CLIENTEPERSONA CP WITH(nolock)) 
		AND PP.NACIONALIDAD =
								CASE
									WHEN PF.PAISNACIMIENTO = 32 THEN ''N''
									WHEN PF.PAISNACIMIENTO <> 32 THEN ''E''
								END

				
GROUP BY
		BD.ID,
		BD.CPA_NUEVO,
		PF.INCLUIDO_PEP,
		BD_AUX.CPA_NUEVO,
		DOC.NUMERODOCUMENTO,
		PP.TIPO_IDENT_TRIB,
		PP.TIPO_DOCUMENTO_IDENTIDAD,
		PF.PRIMERNOMBRE,
		PF.SEGUNDONOMBRE,
		PF.APELLIDOPATERNO,
		PF.APELLIDOMATERNO,
		DOC.NUM_DOC_FISICO,
		D.PAIS,
		PA.CODIGOSWIFT


UNION ALL

--PERSONA JURIDICA MODIFICACION CPA
SELECT	
	MAX(BD.FECHA) AS MAX_FECHA,
	
	DOC.NUMERODOCUMENTO, 
	
	30 AS TIPOMOVIMIENTO, 
	
	PP.TIPO_IDENT_TRIB, 
	
	PP.TIPO_DOCUMENTO_IDENTIDAD, 
	
	DOC.NUM_DOC_FISICO,
	
	PJ.RAZONSOCIAL AS DENOMINACION, 
	
	CASE WHEN PJ.INCL_PEPS = ''N'' THEN
		''2''
	ELSE
		''1''
	END AS PEP_CAMBIO,
	
	BD.CPA_NUEVO AS SCOD_POSTAL_CAMBIO
		 
FROM BITACORA_DIRECCIONES BD WITH(nolock) 

LEFT JOIN CLI_PERSONASJURIDICAS PJ  WITH(nolock) 
	ON BD.ID = PJ.NUMEROPERSONAJURIDICA
	AND PJ.TZ_LOCK=0 

INNER JOIN ALTAS_PJ_CPA BD_AUX WITH(nolock) ON 
	BD.ID = BD_AUX.ID
	AND BD.CPA_NUEVO <> BD_AUX.CPA_NUEVO
	
INNER JOIN CLI_DIRECCIONES D WITH(nolock) ON 
	D.ID = BD_AUX.ID
	AND D.TZ_LOCK=0
	
INNER JOIN CLI_DocumentosPFPJ DOC WITH(nolock) ON 
	DOC.NUMEROPERSONAFJ = PJ.NUMEROPERSONAJURIDICA
	AND DOC.TZ_LOCK = 0
	
LEFT JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON 
	DOC.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC 
	AND DOC.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.TZ_LOCK = 0
	
INNER JOIN CLI_INTEGRANTESPJ IPJ WITH(nolock) ON 
	PJ.NUMEROPERSONAJURIDICA = IPJ.NUMEROPERSONAJURIDICA
	AND IPJ.CODIGOCARGO IN (''SDE'',''FCO'',''APO'')
	AND IPJ.TZ_LOCK = 0
	
WHERE PJ.ESTADO=0
	AND BD.TIPODIRECCION = ''L''
	AND BD.TIPO_TRAZA = ''M''
	AND BD.FECHA_MODIFICACION BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	
	AND PJ.NUMEROPERSONAJURIDICA IN (SELECT NUMEROPERSONA FROM CLI_CLIENTEPERSONA CP  WITH(nolock))
 
	AND PP.CARGO_SDE_FCO	= CASE	WHEN IPJ.CODIGOCARGO = ''SDE'' THEN ''SDE''
									WHEN IPJ.CODIGOCARGO = ''FCO'' THEN ''FCO''
									ELSE ''N''
									END
	AND BD.TZ_LOCK = 0
  		
GROUP BY BD.ID, 
		BD.CPA_NUEVO, 
		PJ.INCL_PEPS,
		DOC.NUMERODOCUMENTO, 
		PP.TIPO_IDENT_TRIB, 
		PP.TIPO_DOCUMENTO_IDENTIDAD,
		PJ.RAZONSOCIAL, 
		DOC.NUM_DOC_FISICO
),
--Punto D)
--s.INCLUIDO_PEP es el valor que tenia ese campo en el ultimo regtistro del mes pasado
--BP_INCLUIDO_PEP es el valor que tiene este mes.
--se chequea si son iguales o no
--Se debe usar campo CPA_NUEVO en vez de SCOD_POSTAL???
--WITH 

ALTAS_PF_PEP AS ( 
	SELECT DISTINCT
		NUMEROPERSONAFISICA AS ID, 
		INCLUIDO_PEP
	FROM BITACORA_PERSONAS_FISICAS
	WHERE TIPO_TRAZA=''A''
		AND TZ_LOCK=0 
),

ALTAS_PJ_PEP AS ( 
	SELECT DISTINCT 
		NUMEROPERSONAJURIDICA AS ID, 
		INCL_PEPS
	FROM BITACORA_PERSONAS_JURIDICAS
	WHERE TIPO_TRAZA=''A'' AND 
		TZ_LOCK=0 
),
aux3 AS (
-- Persona Fisica Modificacion PEP

SELECT
	MAX(BPF.FECHAULTACTUALIZACION) AS MAX_FECHA, 
	
	DOC.NUMERODOCUMENTO, 
	
	30 AS TIPOMOVIMIENTO,  
	
	PP.TIPO_IDENT_TRIB, 
	
	PP.TIPO_DOCUMENTO_IDENTIDAD, 
	
	DOC.NUM_DOC_FISICO,
	
	PF.PRIMERNOMBRE+'' ''+PF.SEGUNDONOMBRE+'' ''+PF.APELLIDOPATERNO+'' ''+PF.APELLIDOMATERNO AS DENOMINACION,
	
	CASE WHEN BPF.INCLUIDO_PEP = ''N'' THEN
			''2''
		ELSE
			''1''
	END AS PEP_CAMBIO,

	CASE
		WHEN D.PAIS = 32 THEN D.CPA_NUEVO
		WHEN D.PAIS <> 32 THEN CONCAT(PA.CODIGOSWIFT, ''000000'')
	END AS SCOD_POSTAL_CAMBIO

FROM BITACORA_PERSONAS_FISICAS BPF WITH(nolock) 

INNER JOIN CLI_PERSONASFISICAS PF WITH(nolock) ON 
	BPF.NUMEROPERSONAFISICA = PF.NUMEROPERSONAFISICA AND
	PF.TZ_LOCK = 0

--Chequeo en pyf_apoderados, para saber si es tutor / curador, con cod_apoderamiento = 5
INNER JOIN PYF_APODERADOS APO WITH(nolock) ON 
	PF.NUMEROPERSONAFISICA = APO.ID_PERSONA AND
	APO.TIPO_ENTIDAD = 1 AND
	APO.TZ_LOCK = 0
	
	
INNER JOIN ALTAS_PF_PEP BPF_AUX WITH(nolock) ON 
	BPF.NUMEROPERSONAFISICA = BPF_AUX.ID
	AND BPF.INCLUIDO_PEP <> BPF_AUX.INCLUIDO_PEP

INNER JOIN CLI_DIRECCIONES D WITH(nolock) ON 
	D.ID = BPF_AUX.ID
	AND D.TIPODIRECCION = CASE WHEN PF.CODIGODERESIDENCIA =2 THEN ''PR'' ELSE ''ED'' END
	AND D.TZ_LOCK = 0
	
INNER JOIN CLI_PAISES PA WITH(nolock) ON	
	D.PAIS = PA.CODIGOPAIS AND
	PA.TZ_LOCK = 0

INNER JOIN CLI_DocumentosPFPJ DOC WITH(nolock) 
	ON DOC.NUMEROPERSONAFJ = BPF.NUMEROPERSONAFISICA 
	AND DOC.TZ_LOCK = 0
	
INNER JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON	
	DOC.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC
	AND DOC.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.NACIONALIDAD = (SELECT CASE WHEN DOC.COD_PAIS_ORIGEN=32 THEN ''N'' ELSE ''E'' END)
	AND PP.TZ_LOCK = 0

	
WHERE	
	PF.ESTADO=0
	AND BPF.TZ_LOCK=0
	AND BPF.TIPO_TRAZA = ''M''
	AND BPF.FECHAULTACTUALIZACION BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	AND PF.NUMEROPERSONAFISICA IN (	SELECT NUMEROPERSONA 
									FROM CLI_CLIENTEPERSONA CP WITH(nolock))
	AND PP.NACIONALIDAD =	CASE	WHEN PF.PAISNACIMIENTO = 32 THEN ''N''
									WHEN PF.PAISNACIMIENTO <> 32 THEN ''E''
							END

	
GROUP BY 
	DOC.NUMERODOCUMENTO, 
	PP.TIPO_IDENT_TRIB, 
	D.PAIS,
	BPF.INCLUIDO_PEP,
	D.CPA_NUEVO,
	PA.CODIGOSWIFT,
	PP.TIPO_DOCUMENTO_IDENTIDAD,
	PF.PRIMERNOMBRE, 
	PF.SEGUNDONOMBRE, 
	PF.APELLIDOPATERNO, 
	PF.APELLIDOMATERNO,
	DOC.NUM_DOC_FISICO


UNION ALL

--PERSONA JURIDICA MODIFICACION PEP
SELECT	
	MAX(BPJ.FECHAULTIMAACTUALIZACION) AS MAX_FECHA,
	
	DOC.NUMERODOCUMENTO, 
	
	30 AS TIPOMOVIMIENTO, 
	
	PP.TIPO_IDENT_TRIB, 
	
	PP.TIPO_DOCUMENTO_IDENTIDAD, 
	
	DOC.NUM_DOC_FISICO,
	
	PJ.RAZONSOCIAL AS DENOMINACION, 
	
	CASE WHEN BPJ.INCL_PEPS = ''N'' THEN
			''2''
		ELSE
			''1''
	END AS PEP_CAMBIO,

	D.CPA_NUEVO AS SCOD_POSTAL_CAMBIO
		 
FROM BITACORA_PERSONAS_JURIDICAS BPJ WITH(NOLOCK) 

LEFT JOIN CLI_PERSONASJURIDICAS PJ  WITH(nolock) 
	ON BPJ.NUMEROPERSONAJURIDICA= PJ.NUMEROPERSONAJURIDICA
	AND PJ.TZ_LOCK=0 

INNER JOIN ALTAS_PJ_PEP BPJ_AUX WITH(nolock) ON 
	BPJ.NUMEROPERSONAJURIDICA = BPJ_AUX.ID
	AND BPJ.INCL_PEPS <> BPJ_AUX.INCL_PEPS
	
INNER JOIN CLI_DIRECCIONES D WITH(nolock) ON 
	D.ID = BPJ_AUX.ID
	AND D.TIPODIRECCION = ''L''
	AND D.TZ_LOCK=0
	
INNER JOIN CLI_DocumentosPFPJ DOC WITH(nolock) ON 
	DOC.NUMEROPERSONAFJ = PJ.NUMEROPERSONAJURIDICA
	AND DOC.TZ_LOCK = 0
	
LEFT JOIN RRII_PARAMETROS_PADRON PP WITH(nolock) ON 
	DOC.TIPO_DOC_FISICO = PP.NOMBRE_TIPO_DOC 
	AND DOC.TIPOPERSONA = PP.TIPO_PERSONA
	AND PP.TZ_LOCK = 0
	
INNER JOIN CLI_INTEGRANTESPJ IPJ WITH(nolock) ON 
	PJ.NUMEROPERSONAJURIDICA = IPJ.NUMEROPERSONAJURIDICA
	AND IPJ.CODIGOCARGO IN (''SDE'',''FCO'',''APO'')
	AND IPJ.TZ_LOCK = 0
	
WHERE 
	PJ.ESTADO=0
	AND BPJ.TIPO_TRAZA = ''M''
	AND BPJ.FECHAULTIMAACTUALIZACION BETWEEN @fch_proceso AND EOMONTH(@fch_proceso)
	AND BPJ.TZ_LOCK = 0
	AND PJ.NUMEROPERSONAJURIDICA IN (SELECT NUMEROPERSONA FROM CLI_CLIENTEPERSONA CP  WITH(nolock))
 
	AND PP.CARGO_SDE_FCO	= CASE	WHEN IPJ.CODIGOCARGO = ''SDE'' THEN ''SDE''
									WHEN IPJ.CODIGOCARGO = ''FCO'' THEN ''FCO''
									ELSE ''N''
									END
  		
GROUP BY
	BPJ.INCL_PEPS,
	D.CPA_NUEVO,
	PJ.INCL_PEPS,
	DOC.NUMERODOCUMENTO, 
	PP.TIPO_IDENT_TRIB, 
	PP.TIPO_DOCUMENTO_IDENTIDAD,
	PJ.RAZONSOCIAL, 
	DOC.NUM_DOC_FISICO

	

)
SELECT * FROM AUX WITH(NOLOCK)
UNION ALL
SELECT * FROM AUX2  WITH(NOLOCK)WHERE SCOD_POSTAL_CAMBIO IS NOT NULL
UNION ALL
SELECT * FROM AUX3 WITH(NOLOCK) WHERE PEP_CAMBIO IS NOT NULL;
')