EXECUTE('
	INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
	VALUES (2000, 2644, ''Balance Comprobación Arbol - Consolidado'', ''J'', 0, NULL, 0, 0, 0, ''N'')

	INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
	VALUES (2644, 1, NULL, 0, 0, 1)
')

