EXECUTE('
	INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
	VALUES (305, 3585, NULL, ''Tasa Fija de Precanc. DPF'', 0, ''DPF_PARAM_TASA_PRECANCELACION'', ''D'', 0, 0, ''Top/Clientes'', NULL, ''N'')

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35883, NULL, 0, ''Producto'', ''Producto'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 651, 0, 3585, ''PRODUCTO'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35884, NULL, 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 93461, 0, 3585, ''MONEDA'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35885, NULL, 0, ''Sector'', ''Sector'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3585, ''SECTOR'', 0, NULL)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (35886, NULL, 0, ''Puntos Porcentuales'', ''Puntos Porcentuales'', 11, ''N'', 7, NULL, 0, 0, 0, 0, 0, 0, 0, 3585, ''PUNTOS_PORCENTUALES'', 0, NULL)

	INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
	VALUES (3585, 1, ''Indice DPF_PARAM_TASA'', 0, 35883, 35884, 35885, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

	INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
	VALUES (5001, 5069, ''ABMC - Tasa Fija Precancelación'', ''ABMC - Tasa Fija Precancelación'', ''5069'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

	INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
	VALUES (0, 93459, ''Ayuda PARAMETRÍA DPF TASA FIJA'', '''', 0, ''35883R;35884R;35885R;35886R;'', ''Producto;Moneda;Sector;Puntos_Porcentuales;'', ''Top/Clientes'', ''VW_PARAM_TASA_FIJA_DPF'', 0)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (99350, '' '', 0, ''Ayuda PARAMETRIA DPF TASA FIJA'', ''Ayuda PARAMETRIA DPF TASA FIJA'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 93459, 0, 0, ''Ayuda CREDEB'', 0, NULL)

	INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
	VALUES (0, 93460, ''Ayuda CLI_SECTORES'', '''', 0, ''33039R;33040;33041;'', ''Sector;Sector_Contable;Descripción;'', ''Top/Clientes'', ''VW_CLI_SECTOR'', 0)

	INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (99351, '' '', 0, ''Ayuda CLI_SECTORES'', ''Ayuda CLI_SECTORES'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 93460, 0, 0, ''Ayuda CREDEB'', 0, NULL)

	INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
	VALUES (0, 93461, ''Ayuda MONEDA NO INDEXADA'', '''', 0, ''6399R;6400;'', ''Código_Moneda;Moneda;'', ''Top/Clientes'', ''VW_MONEDA_NO_INDEXADA'', 0)
')