EXECUTE('
IF OBJECT_ID (''dbo.VW_DIF_ARQUEO_CAJA'') IS NOT NULL
	DROP VIEW dbo.VW_DIF_ARQUEO_CAJA
')
EXECUTE ('
CREATE OR ALTER VIEW [dbo].[VW_DIF_ARQUEO_CAJA]
AS
SELECT  D.SUCURSAL, 
		D.FECHAPROCESO, 
		D.ASIENTO, 
		D.TIPO, 
		D.MONEDA, 
		D.CAJA, 
		D.USUARIO, 
		D.MONTO, 
		D.MONTO_PENDIENTE
FROM DIF_ARQUEO_CAJA D 
INNER JOIN CAJ_DIFERENCIA_MAX_CAJA C 
ON D.MONEDA= C.MONEDA
WHERE D.MONTO_PENDIENTE > C.IMPORTE 
AND D.TZ_LOCK = 0 
AND C.TZ_LOCK = 0
')