execute('
INSERT INTO dbo.SUCURSALESSC (TZ_LOCK, SUCURSAL, FECHAPROCESOANTERIOR, FECHAPROCESOACTUAL, FECHAPROCESOPROXIMO, FECHAULTIMOPROCESO, DESCRIPCION, ESTADO, CENTRO_CANJE_RECEPTOR, VIRTUAL, WORKONHOLIDAYS, ACTIVA, EMPRESA, SUCURSAL_EMPRESA, REGION_FERIADOS)
VALUES (0, 102, (SELECT FECHAPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROXIMOPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROXIMOPROCESO FROM PARAMETROS WITH (nolock))+1, (SELECT FECHAPROCESOANTERIOR FROM PARAMETROS WITH (nolock)), ''TOPAZPOS 2'', ''A'', 0, 1, ''N'', 1, 0, NULL, 0)

INSERT INTO dbo.SUCURSALESSC (TZ_LOCK, SUCURSAL, FECHAPROCESOANTERIOR, FECHAPROCESOACTUAL, FECHAPROCESOPROXIMO, FECHAULTIMOPROCESO, DESCRIPCION, ESTADO, CENTRO_CANJE_RECEPTOR, VIRTUAL, WORKONHOLIDAYS, ACTIVA, EMPRESA, SUCURSAL_EMPRESA, REGION_FERIADOS)
VALUES (0, 103, (SELECT FECHAPROCESOANTERIOR FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROXIMOPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROCESOANTERIOR FROM PARAMETROS WITH (nolock)), ''SERVICIOS INTERFACES'', ''A'', 0, 1, ''N'', 1, 0, NULL, 0)

INSERT INTO dbo.SUCURSALESSC (TZ_LOCK, SUCURSAL, FECHAPROCESOANTERIOR, FECHAPROCESOACTUAL, FECHAPROCESOPROXIMO, FECHAULTIMOPROCESO, DESCRIPCION, ESTADO, CENTRO_CANJE_RECEPTOR, VIRTUAL, WORKONHOLIDAYS, ACTIVA, EMPRESA, SUCURSAL_EMPRESA, REGION_FERIADOS)
VALUES (0, 104, (SELECT FECHAPROCESOANTERIOR FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROXIMOPROCESO FROM PARAMETROS WITH (nolock)), (SELECT FECHAPROCESOANTERIOR FROM PARAMETROS WITH (nolock)), ''SERVICIOS BANCA'', ''A'', 0, 1, ''N'', 1, 0, NULL, 0)
')