EXECUTE('
ALTER PROCEDURE dbo.SP_TP_TLF_SUMMARY  
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */

   @P_ID_PROCESO float(53),
   @P_DT_PROCESO datetime2(0),
   @P_FECHA datetime2(0),
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */

   @P_RET_PROCESO float(53)  OUTPUT,
   @P_MSG_PROCESO varchar(max)  OUTPUT
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
   BEGIN
   DECLARE @FECHACAPTURA VARCHAR (4)
   DECLARE @RETORNO_CON_REGISTRO NUMERIC (12)
   DECLARE @P_FECHA_ALT VARCHAR(12)

         SET @P_RET_PROCESO = NULL

         SET @P_MSG_PROCESO = NULL
         
         SET @P_FECHA_ALT = REPLACE(FORMAT(@P_FECHA,''dd/MM/yy''),''/'','''')
		
		--Se agrega acción para que cuando haya registros en la tabla para la fecha ingresada
		--los elimine y no genere dobles registros 
		SET @FECHACAPTURA=substring(@P_FECHA_ALT, 3 ,2)+substring(@P_FECHA_ALT, 1 ,2);
		SELECT @FECHACAPTURA
		DELETE FROM TJD_TLF_SUMMARY 
		WHERE FECHACAPTURA = @FECHACAPTURA;
		
		
		INSERT dbo.TJD_TLF_SUMMARY(
            TIPOMENSAJE, --ELEMNTO0, 200 CORRESPONDE 210 = LKTYP
            CODIGOPROCESAMIENTO, --TIPO DE OPERACION, CONSULTA CON INNER JOIN DE TABLA NUEVA IGUALANDO LKTCDE+LKTFRO+LKTTO JOIN TIPOMSJ TABLA DIEGO
            FECHACAPTURA, --FECHA @PARAMETROFECHAP, FORMATO DD/MM 
            FECHATRANSACCION, --LKTRAD, FORMATO DD/MM
            HORATRANSACCION, --LKTRAT SIN 00 ULTIMOS
            CODIGORESPUESTA, --LKRES2 COMPARAR CON TABLA JUAN
            NUMEROTARJETA, --LKPANC
            NUMEROTRANSACCION, --LKSEQN NUMERO RECIBO
            NUMEROAUTORIZACION, --00000
            IDENTIFICACIONCAJERO,-- LKTERM
            IMPORTE, --LKAMT1
            IMPORTEDISPENSADO, --LKAMT2
            FROMACCOUNT, --LKFROM
            TOACCOUNT, --LKTOAC
            MONEDA,
            CONCILIACION,
            IMPORTETLF) 
            SELECT DISTINCT 
            CASE ITF_TLF_POS.LKTYP    
            WHEN ''210'' THEN ''0200''
            WHEN ''420'' THEN ''0420''
            ELSE ITF_TLF_POS.LKTYP   
            END
            AS TIPOMENSAJE, 
            (SELECT COD_MSJ_H2H FROM TLF_COD_TRANSACCIONES O WITH (NOLOCK) 
            WHERE LKTCDE+LKTFRO+LKTTO=O.COD_MSJ_TLF)
            AS CODIGOPROCESAMIENTO, 
            substring(@P_FECHA_ALT, 3 ,2)+substring(@P_FECHA_ALT, 1 ,2) AS FECHACAPTURA,            
      		substring(ITF_TLF_POS.LKPOST, 3, 2)+substring(ITF_TLF_POS.LKPOST, 5, 2) AS FECHATRANSACCION,  
             substring(ITF_TLF_POS.LKTRAT, 0, 7) AS HORATRANSACCION, --FALTA SACARLE 00
             (SELECT H2H FROM dbo.COD_RETORNO_2H2_TLF O WITH (NOLOCK) 
              WHERE LKRES2=O.TLF)
               AS CODIGORESPUESTA, 
               ITF_TLF_POS.LKPANC AS NUMEROTARJETA,  
               ITF_TLF_POS.LKSEQN AS NUMEROTRANSACCION,  
               ''00000'' AS NUMEROAUTORIZACION, 
               ITF_TLF_POS.LKTERM AS IDENTIFICACIONCAJERO,  
              replace((CONVERT(varchar(15), ITF_TLF_POS.LKAMT1)),''.'','''')AS IMPORTE,  
               NULL               AS IMPORTEDISPENSADO,
				CASE                       
					WHEN LKTCDE NOT IN (''29'',''F4'') THEN LKTFRO+LKFROM
					ELSE LKFROM
				END AS FROMACCOUNT,
				CASE                       
					WHEN LKTCDE IN (''29'',''F4'', ''40'') THEN LKTTO+LKTOAC
					ELSE LKTOAC
				END AS TOACCOUNT,  
               CASE ITF_TLF_POS.LKORIG 
                  WHEN 32 THEN ''N'' --logico cambiar a N
                  WHEN 840 THEN ''D''
                  ELSE ''N''
               END AS MONEDA,
               ''S'' AS CONCILIACION,
               ITF_TLF_POS.LKAMT1 AS IMPORTETLF
            FROM dbo.ITF_TLF_POS WITH (NOLOCK) 
            INNER JOIN TLF_COD_TRANSACCIONES WITH (NOLOCK) 
            ON COD_MSJ_TLF=LKTCDE+LKTFRO+LKTTO --JOIN CON  TABLA TLF_COD_TRANSACCIONES
            WHERE 
            ITF_TLF_POS.LKTYP IN (''210'', ''0220'', ''0420'' ) AND 
             ITF_TLF_POS.LKRECT=''01'' 
             /* Solo transacciones monetarias*/ AND 
             ITF_TLF_POS.LKPOST=substring(@P_FECHA_ALT, 5 ,2)+substring(@P_FECHA_ALT, 3 ,2)+substring(@P_FECHA_ALT, 1 ,2)
             --substring(REPLACE(CONVERT(VARCHAR,@P_FECHA,103),''/'',''''), 7 ,2)+substring(REPLACE(CONVERT(VARCHAR,@P_FECHA,103),''/'',''''), 3 ,2)+substring(REPLACE(CONVERT(VARCHAR,@P_FECHA,103),''/'',''''), 1 ,2)

         SET @P_RET_PROCESO = 1/* Process Ok*/

         SET @P_MSG_PROCESO = ''La tabla TJD_TLF_SUMMARY se ha cargado correctamente.''

      SELECT @RETORNO_CON_REGISTRO=COUNT(1) FROM TJD_TLF_SUMMARY 
      WHERE FECHACAPTURA = substring(@P_FECHA_ALT, 3 ,2)+substring(@P_FECHA_ALT, 1 ,2)
      
      IF(@RETORNO_CON_REGISTRO=0)
      BEGIN

               SET @P_RET_PROCESO = 2/* Error*/

               SET @P_MSG_PROCESO = ''No se insertaron registros en la tabla TJD_TLF_SUMMARY''

             END
             

     END
')