EXECUTE('
DELETE FROM dbo.CI_IMPUESTOS_X_CARGO WHERE ID_CARGO = 3003
')

EXECUTE('
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (5, 3003, ''A'', 0, 1357, ''Cond IVA'', 0)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (6, 3003, ''A'', 0, 1357, ''Cond Percep IVA'', 0)
')