IF OBJECT_ID ('dbo.ITF_AFIP_SITEREX_HIST') IS NOT NULL
	DROP TABLE dbo.ITF_AFIP_SITEREX_HIST
GO

CREATE TABLE dbo.ITF_AFIP_SITEREX_HIST
	(
	  ID                          INT IDENTITY NOT NULL
	, TIPO_REGISTRO               VARCHAR (2) NULL
	, CUIT_INFORMANTE             VARCHAR (22) NULL
	, PERIODO_INFORMADO           VARCHAR (8) NULL
	, SECUENCIA                   VARCHAR (2) NULL
	, COD_IMPUESTO                VARCHAR (4) NULL
	, COD_CONCEPTO                VARCHAR (3) NULL
	, NRO_FORMULARIO              VARCHAR (4) NULL
	, VERSION                     VARCHAR (5) NULL
	, PRESENTACION_SIN_MOVIMIENTO VARCHAR (1) NULL
	, CBU                         VARCHAR (22) NULL
	, CUIT_CUIL_CDI               VARCHAR (22) NULL
	, CARACTER_INTEGRANTE         VARCHAR (2) NULL
	, FECHA_OPERACION             VARCHAR (8) NULL
	, ID_PAIS                     VARCHAR (5) NULL
	, SG_MONTO_OP_PESOS           VARCHAR (1) NULL
	, MONTO_OP_PESOS              VARCHAR (15) NULL
	, NOM_COMERCIO                VARCHAR (60) NULL
	, COD_RUBRO                   VARCHAR (2) NULL
	, CONSTRAINT PK_SITEREX PRIMARY KEY (ID)
	)
GO

