EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45795, '''', 0, ''NUMERODOC'', ''NUMERODOC'', 20, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 4544, ''NUMERODOC'', 0, '''')
')