EXECUTE('
DELETE FROM dbo.PARAMETROSGENERALES
WHERE CODIGO = 780
')

EXECUTE('
INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (780, ''Considerar Reservas POS'', '''', 7, NULL, 0, 0, 0)
')