EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79581, '''', 0, ''CONCEPTO_DEBIN'', ''CONCEPTO_DEBIN'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7951, ''CONCEPTO_DEBIN'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (79582, '''', 0, ''CONCEPTO_TRANSF_INM'', ''CONCEPTO_TRANS'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 7951, ''CONCEPTO_TRANSF_INM'', 0, '''')
')