EXECUTE('
CREATE OR ALTER          PROCEDURE [dbo].[SP_ITF_SOS_OPERACIONES]
	@Fecha VARCHAR(8)
AS
  DECLARE @FECHAPROCESO VARCHAR(8);
  
BEGIN

SELECT @FECHAPROCESO = CONVERT(VARCHAR,FECHAPROCESO,112) FROM PARAMETROS WITH (NOLOCK);

--Limpiamos por si hay reproceso
DELETE FROM SOS_MOVS_HISTORICOS WHERE convert(VARCHAR,FECHADEINFORMACION) = @FECHAPROCESO;


INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
SELECT
--1
311 AS EMPRESA, 
--2
@FECHAPROCESO AS FECHADEINFORMACION,
--3
(CASE WHEN sos.Subsistema IN (''PR'')
  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,sa.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR, sa.OPERACION),CONVERT(VARCHAR,sa.ORDINAL))
  	  WHEN sos.Subsistema IN (''PF'')
  		THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,sa.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR,mov.OPERACION_CUENTA))
      ELSE CONCAT(RIGHT(''0''+CONVERT(VARCHAR,sa.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR,mov.CUENTA)) END)AS NUMERODECUENTA,
--4
LEFT(concat(mov.ASIENTO, CONVERT(VARCHAR,mov.FECHAPROCESO,112), mov.SUCURSAL, mov.ORDINAL),22) AS NUMERODEOPERACION,
--5
LEFT(sos.Subsistema,3) AS CLASEDECUENTA,
--6
SOS.TipOperacion  AS TIPODECUENTAUOPERACION,
--7
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,suc.SucursalBCRA) END) AS SUCURSALSISCEN,
--8
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,mov.SUCURSAL) END) AS SUCURSALINTERNA,
--9
(CASE WHEN sa.C1785 = 4 THEN CONVERT(VARCHAR, sa.C1621, 112) ELSE CONVERT(VARCHAR,mov.FECHAPROCESO,112) END) AS FECHADELAOPERACION,
--10
(CASE WHEN mov.MONEDA = 1 THEN
 		 mov.CAPITALREALIZADO 
	  ELSE 0 END) AS MONTOPESOS, 
--11
(CASE WHEN mov.MONEDA <> 1 THEN 
   mov.CAPITALREALIZADO
   ELSE 0 END) AS ESPECIETRANSADACANTIDAD, 
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WITH (NOLOCK) 
      WHERE m.C6399 = (CASE WHEN mov.MONEDA IN (988,999) THEN 1 ELSE mov.MONEDA END)
	    AND m.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
--13
'''' AS BANCOCORRESPONSALSWIFT,
--14
'''' AS BENEFICIARIOORDENANTEDELEXTE,
--15
'''' AS PAISDELBENEFICIARIOORDENANTE,
--16
(CASE WHEN sos.Subsistema IN (''PF'',''CE'',''ME'') THEN '''' 
	  WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.TIPOPERACION NOT IN (101, 103) THEN '''' 
      WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.TIPOPERACION IN (101, 103) 
         THEN ISNULL(vt.BEN_MISMO_TITULAR, (CASE WHEN (SELECT COUNT(DISTINCT CLIENTE) 
         				  FROM MOVIMIENTOS_CONTABLES mc WITH (NOLOCK) 
                          WHERE mc.ASIENTO = mov.ASIENTO 
                            AND mc.SUCURSAL = mov.SUCURSAL 
                            AND mc.FECHAPROCESO = mov.FECHAPROCESO
                            AND mc.CLIENTE <> 0) > 1 THEN ''N''
                            WHEN (SELECT COUNT(DISTINCT CLIENTE) 
         				  FROM MOVIMIENTOS_CONTABLES mc WITH (NOLOCK) 
                          WHERE mc.ASIENTO = mov.ASIENTO 
                            AND mc.SUCURSAL = mov.SUCURSAL 
                            AND mc.FECHAPROCESO = mov.FECHAPROCESO
                            AND mc.CLIENTE <> 0) = 1 THEN ''S''
                    ELSE ''NO'' END))
      WHEN sos.Subsistema = ''PR'' THEN ''EFSI''
END) AS DATOSADICIONALES,
--17
CONVERT(VARCHAR, mov.FECHAVALOR,112) AS FECHAALTA,
--18
concat(right(concat(Replicate(''0'',4),sos.Operacion),4), sos.Subsistema, RIGHT(concat(Replicate(''0'',7), sos.CodTransaccion),7)) AS CODIGOSTOPAZ,
--19
ISNULL((CASE WHEN mov.MONEDA = 1 THEN 0 ELSE 
  (CASE WHEN sos.SubSistema IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN 
        	(SELECT TipC.TIPO_CAMBIO_OFICIAL 
        	 FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK) 
        	 WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO 
        	   AND Tipc.MONEDA = sa.MONEDA 
        	   AND Tipc.TZ_LOCK = 0)
        WHEN sos.SubSistema IN (''PR'',''PF'') THEN 
            (SELECT CASE WHEN mov.OPERACION = 3015 THEN TipC.TIPO_CAMBIO_COMPRA 
						 WHEN mov.OPERACION = 3016 THEN TipC.TIPO_CAMBIO_VENTA 
						 ELSE TipC.TIPO_CAMBIO_COMPRA END
			 FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK) 
			 WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO
			    AND Tipc.MONEDA = sa.MONEDA 
			    AND Tipc.TZ_LOCK = 0)
		WHEN sos.SubSistema = ''CE'' THEN 
			(SELECT TIPO_CAMBIO 
			 FROM GRL_OPE_CAMBIO WITH (NOLOCK) 
			 WHERE SUCURSAL = mov.SUCURSAL 
			 AND FECHA_PROCESO = mov.FECHAPROCESO 
			 AND ASIENTO = mov.ASIENTO
			 and TZ_LOCK = 0)																			 
   ELSE 0 END) END),0) AS COTIZACION,
--20
ISNULL((SELECT (CASE WHEN asi.ESTADO = 42 THEN ''SI'' ELSE ''NO'' END) FROM ASIENTOS asi 
 WHERE asi.FECHAPROCESO = mov.FECHAPROCESO AND asi.ASIENTO = mov.ASIENTO AND asi.SUCURSAL = mov.SUCURSAL),''NO'') AS REVERSADA,
--21
'''' AS OPER_ID_BIC_SWIFT,
--22
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
		  THEN CONVERT(VARCHAR,vmov.NRO_DOC_I)
     WHEN sos.TipOperacion IN (101,103) THEN 
     								isnull(CONVERT(VARCHAR,vt.BEN_NRO_DOC),
											     (SELECT (clix.NUMERODOC) FROM MOVIMIENTOS_CONTABLES movx WITH (NOLOCK)
											      INNER JOIN SALDOS sax ON sax.JTS_OID = movx.SALDO_JTS_OID
											      INNER JOIN VW_CLI_X_DOC clix WITH (NOLOCK) ON clix.CODIGOCLIENTE = movx.CLIENTE_ORIGEN
												WHERE movx.FECHAPROCESO = mov.FECHAPROCESO
												  AND movx.ASIENTO = mov.ASIENTO
												  AND movx.SUCURSAL = mov.SUCURSAL
												  AND movx.ORDINAL = 0
												  AND movx.COD_TRANSACCION <> mov.COD_TRANSACCION))
	ELSE '''' END
),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
          THEN (CASE WHEN vmov.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
	ELSE '''' END
),2) AS RTE_OPE_FON_TIPO_PERSONA,
--24
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN concat(vmov.APELLIDO_I,'' '', vmov.NOMBRE_I)
	ELSE '''' END
),100) AS RTE_OPE_FON_DENOMINACION,
--25
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN vmov.APELLIDO_I
	ELSE '''' END
),50)  AS RTE_OPE_FON_APELLIDOS,
--26
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN vmov.NOMBRE_I
	ELSE '''' END
),50) AS RTE_OPE_FON_NOMBRES,
--27
(CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)  THEN ''96'' ELSE '''' END) AS RTE_OPE_FON_TIPODOC,
--28
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
		  THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_I),3,8)
	ELSE '''' END
),10)  AS RTE_OPE_FON_NUMDOC,
--29
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN CONVERT(VARCHAR,vmov.NRO_DOC_M)
	ELSE '''' END
),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
          THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
	ELSE '''' END
),2) AS RTE_TIT_FON_TIPO_PERSONA,
--31
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN concat(vmov.APELLIDO_M,'' '', vmov.NOMBRE_M)
	ELSE '''' END
),100) AS RTE_TIT_FON_DENOMINACION,
--32
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
        THEN  vmov.APELLIDO_M
	ELSE '''' END
),50) AS RTE_TIT_FON_APELLIDOS,
--33
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
        THEN vmov.NOMBRE_M
	ELSE '''' END
),50) AS RTE_TIT_FON_NOMBRES,
--34
(
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN ''96''
						      WHEN vmov.TIPO_PERSONA_M = ''J'' THEN ''80'' END)
	ELSE '''' END
) AS RTE_TIT_FON_TIPODOC,
--35
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),3,8)
						      WHEN vmov.TIPO_PERSONA_M = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),1,10) END)
	ELSE '''' END
),10) AS RTE_TIT_FON_NUMDOC,
--36
'''' AS RTI_TIPOPERSONA,
--37
'''' AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
(CASE WHEN sos.Subsistema = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, mov.FECHAVALOR  ,112))  
	  ELSE
	   CONVERT(NUMERIC,CONVERT(VARCHAR,sa.c1620 ,112)) END) AS FECHAAPERTURACUENTA,
--CLIENTE
sa.C1803 AS CODCLIENTE,
suc.SucursalBCRA AS SUCURSALSISCENCTA,
--38
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE ''Titular'' END), 30) AS REL_FON_TIT,
--39
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
  														   --inner join VTA_CUMPLIMIENTO vmov WITH (NOLOCK) on V.TIPODOCUMENTO = vmov.TIPO_DOC_I AND V.NUMERODOCUMENTO= vmov.NRO_DOC_I
														   WHERE V.TIPODOCUMENTO = vmov.TIPO_DOC_I 
														     AND V.NUMERODOCUMENTO= vmov.NRO_DOC_I
														     --AND vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
														     AND  V.CODIGOCLIENTE = sa.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_TIT,
--40
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE ''Operador'' END), 30) AS REL_FON_OPER,
--41
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
  														   --inner join VTA_CUMPLIMIENTO vmov WITH (NOLOCK) on V.TIPODOCUMENTO = vmov.TIPO_DOC_M AND V.NUMERODOCUMENTO= vmov.NRO_DOC_M
														   WHERE V.TIPODOCUMENTO = vmov.TIPO_DOC_M 
														     AND V.NUMERODOCUMENTO= vmov.NRO_DOC_M
														   --vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
														     AND  V.CODIGOCLIENTE = sa.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_OPER,
--
sa.JTS_OID
--SELECT mov.*
FROM MOVIMIENTOS_CONTABLES mov WITH (NOLOCK)
  INNER JOIN SOS_TRANSACCIONES sos WITH (NOLOCK) ON sos.CodTransaccion = mov.COD_TRANSACCION AND sos.Operacion = mov.OPERACION
    AND sos.Subsistema NOT IN (''ME'',''TC'',''TT'',''PR'')
    AND ((sos.PagosAInformar = ''T'') OR
         (sos.PagosAInformar = ''E'' AND mov.CAJADIARIO = ''C'') OR
         (sos.PagosAInformar = ''D'' AND mov.CAJADIARIO <> ''C''))
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = mov.SUCURSAL
  INNER JOIN SALDOS sa WITH (NOLOCK) ON sa.C1785 NOT IN (''5'',''8'') AND sa.JTS_OID = mov.SALDO_JTS_OID AND sa.OPERACION = mov.OPERACION_CUENTA
									  AND (CASE WHEN sa.C1785 = ''3'' THEN ''AC''
												WHEN sa.C1785 = ''2'' THEN ''CC''
												WHEN sa.C1785 = ''4'' THEN ''PF'' END) =  sos.Subsistema
									 AND ((sa.TZ_LOCK < 300000000000000 OR sa.TZ_LOCK >= 400000000000000) 
										AND (sa.TZ_LOCK < 100000000000000 OR sa.TZ_LOCK >= 200000000000000)) 
  LEFT JOIN VTA_CUMPLIMIENTO vmov WITH (NOLOCK) ON vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
  LEFT JOIN VTA_TRANSFERENCIAS vt ON vt.FECHA_ASIENTO = mov.FECHAPROCESO AND vt.NUMERO_ASIENTO = mov.ASIENTO AND vt.SUCURSAL_ASIENTO = mov.SUCURSAL
WHERE mov.FECHAPROCESO = @Fecha
  AND mov.CLIENTE <> 0
  AND sos.TZ_LOCK = 0
  AND suc.TZ_LOCK = 0
  AND (mov.NROCAJA <> 0 OR (mov.NROCAJA = 0 AND mov.OPERACION = 8620) OR (mov.NROCAJA = 0 AND sos.Subsistema = ''PF''))
  AND sa.PRODUCTO <> 0
  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS x WITH (NOLOCK) 
  				 WHERE x.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' 
  				   AND x.ALFA_1 = sa.PRODUCTO
  				   AND x.TZ_LOCK = 0)
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASFISICAS nat WITH(NOLOCK) ON p.NUMEROPERSONA = nat.NUMEROPERSONAFISICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND nat.SECTOR IN (6,7)
  				   AND nat.TZ_LOCK = 0
  				   AND p.TZ_LOCK = 0
  				   AND cli.TZ_LOCK = 0)
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASJURIDICAS jur WITH(NOLOCK) ON p.NUMEROPERSONA = jur.NUMEROPERSONAJURIDICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND jur.SECTOR IN (6,7)
  				   AND jur.TZ_LOCK = 0
  				   AND p.TZ_LOCK = 0
  				   AND cli.TZ_LOCK = 0)

/*********************************
      PRESTAMO
**********************************/
INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
SELECT
--1
311 AS EMPRESA, 
--2
@FECHAPROCESO AS FECHADEINFORMACION,
--3
(CASE WHEN sos.Subsistema IN (''PF'',''PR'')
  THEN CONCAT(RIGHT(''0''+CONVERT(VARCHAR,sa.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR, sa.OPERACION),CONVERT(VARCHAR,sa.ORDINAL))
  ELSE CONCAT(RIGHT(''0''+CONVERT(VARCHAR,sa.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR,mov.CUENTA)) END)AS NUMERODECUENTA,
--4
LEFT(concat(mov.ASIENTO, CONVERT(VARCHAR,mov.FECHAPROCESO,112), mov.SUCURSAL, mov.ORDINAL),22) AS NUMERODEOPERACION,
--5
LEFT(sos.Subsistema,3) AS CLASEDECUENTA,
--6
SOS.TipOperacion  AS TIPODECUENTAUOPERACION,
--7
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,suc.SucursalBCRA) END) AS SUCURSALSISCEN,
--8
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,mov.SUCURSAL) END) AS SUCURSALINTERNA,
--9
(CASE WHEN sa.C1785 = 4 THEN CONVERT(VARCHAR, sa.C1621, 112) ELSE CONVERT(VARCHAR,mov.FECHAPROCESO,112) END) AS FECHADELAOPERACION,
--10
(CASE WHEN mov.MONEDA = 1 THEN
 		 mov.CAPITALREALIZADO 
	  ELSE 0 END) AS MONTOPESOS, 
--11
(CASE WHEN mov.MONEDA <> 1 THEN 
   mov.CAPITALREALIZADO
   ELSE 0 END) AS ESPECIETRANSADACANTIDAD, 
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WITH (NOLOCK) 
      WHERE m.C6399 = (CASE WHEN mov.MONEDA IN (988,999) THEN 1 ELSE mov.MONEDA END)
	    AND m.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
--13
'''' AS BANCOCORRESPONSALSWIFT,
--14
'''' AS BENEFICIARIOORDENANTEDELEXTE,
--15
'''' AS PAISDELBENEFICIARIOORDENANTE,
--16
(CASE WHEN mov.OPERACION = 7002 THEN ''EFSI'' ELSE ''EFSI'' END) AS DATOSADICIONALES,
--17
CONVERT(VARCHAR, mov.FECHAVALOR,112) AS FECHAALTA,
--18
concat(right(concat(Replicate(''0'',4),sos.Operacion),4), sos.Subsistema, RIGHT(concat(Replicate(''0'',7), sos.CodTransaccion),7)) AS CODIGOSTOPAZ,
--19
ISNULL((CASE WHEN mov.MONEDA = 1 THEN 0 ELSE 
  (CASE WHEN sos.SubSistema IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN 
        	(SELECT TipC.TIPO_CAMBIO_OFICIAL 
        	 FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK) 
        	 WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO 
        	   AND Tipc.MONEDA = sa.MONEDA 
        	   AND Tipc.TZ_LOCK = 0)
        WHEN sos.SubSistema IN (''PR'',''PF'') THEN 
            (SELECT CASE WHEN mov.OPERACION = 3015 THEN TipC.TIPO_CAMBIO_COMPRA 
						 WHEN mov.OPERACION = 3016 THEN TipC.TIPO_CAMBIO_VENTA 
						 ELSE TipC.TIPO_CAMBIO_COMPRA END
			 FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK) 
			 WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO
			    AND Tipc.MONEDA = sa.MONEDA 
			    AND Tipc.TZ_LOCK = 0)
		WHEN sos.SubSistema = ''CE'' THEN 
			(SELECT TIPO_CAMBIO 
			 FROM GRL_OPE_CAMBIO WITH (NOLOCK) 
			 WHERE SUCURSAL = mov.SUCURSAL 
			 AND FECHA_PROCESO = mov.FECHAPROCESO 
			 AND ASIENTO = mov.ASIENTO
			 and TZ_LOCK = 0)																			 
   ELSE 0 END) END),0) AS COTIZACION,
--20
ISNULL((SELECT (CASE WHEN asi.ESTADO = 42 THEN ''SI'' ELSE ''NO'' END) FROM ASIENTOS asi 
 WHERE asi.FECHAPROCESO = mov.FECHAPROCESO AND asi.ASIENTO = mov.ASIENTO AND asi.SUCURSAL = mov.SUCURSAL),''NO'') AS REVERSADA,
--21
'''' AS OPER_ID_BIC_SWIFT,
--22
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
		  THEN CONVERT(VARCHAR,vmov.NRO_DOC_I)
	ELSE '''' END
),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
          THEN (CASE WHEN vmov.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
	ELSE '''' END
),2) AS RTE_OPE_FON_TIPO_PERSONA,
--24
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN concat(vmov.APELLIDO_I,'' '', vmov.NOMBRE_I)
	ELSE '''' END
),100) AS RTE_OPE_FON_DENOMINACION,
--25
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN vmov.APELLIDO_I
	ELSE '''' END
),50)  AS RTE_OPE_FON_APELLIDOS,
--26
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN vmov.NOMBRE_I
	ELSE '''' END
),50) AS RTE_OPE_FON_NOMBRES,
--27
(CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)  THEN ''96'' ELSE '''' END) AS RTE_OPE_FON_TIPODOC,
--28
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
		  THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_I),3,8)
	ELSE '''' END
),10)  AS RTE_OPE_FON_NUMDOC,
--29
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN CONVERT(VARCHAR,vmov.NRO_DOC_M)
	ELSE '''' END
),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
          THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END)
	ELSE '''' END
),2) AS RTE_TIT_FON_TIPO_PERSONA,
--31
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN concat(vmov.APELLIDO_M,'' '', vmov.NOMBRE_M)
	ELSE '''' END
),100) AS RTE_TIT_FON_DENOMINACION,
--32
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
        THEN  vmov.APELLIDO_M
	ELSE '''' END
),50) AS RTE_TIT_FON_APELLIDOS,
--33
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
        THEN vmov.NOMBRE_M
	ELSE '''' END
),50) AS RTE_TIT_FON_NOMBRES,
--34
(
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN ''96''
						      WHEN vmov.TIPO_PERSONA_M = ''J'' THEN ''80'' END)
	ELSE '''' END
) AS RTE_TIT_FON_TIPODOC,
--35
LEFT((
CASE WHEN sos.Subsistema IN (''CC'',''AC'') AND sos.ind_rte = ''S'' AND ((sos.MtoMinimo < mov.CAPITALREALIZADO AND sos.MtoMinimo <> 0) OR sos.MtoMinimo = 0)
           THEN (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),3,8)
						      WHEN vmov.TIPO_PERSONA_M = ''J''  THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),1,10) END)
	ELSE '''' END
),10) AS RTE_TIT_FON_NUMDOC,
--36
'''' AS RTI_TIPOPERSONA,
--37
'''' AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
(CASE WHEN sos.Subsistema = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, mov.FECHAVALOR  ,112))  
	  ELSE
	   CONVERT(NUMERIC,CONVERT(VARCHAR,sa.c1620 ,112)) END) AS FECHAAPERTURACUENTA,
--CLIENTE
sa.C1803 AS CODCLIENTE,
suc.SucursalBCRA AS SUCURSALSISCENCTA,
--38
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE ''Titular'' END), 30) AS REL_FON_TIT,
--39
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
  														   --inner join VTA_CUMPLIMIENTO vmov WITH (NOLOCK) on V.TIPODOCUMENTO = vmov.TIPO_DOC_I AND V.NUMERODOCUMENTO= vmov.NRO_DOC_I
														   WHERE V.TIPODOCUMENTO = vmov.TIPO_DOC_I 
														     AND V.NUMERODOCUMENTO= vmov.NRO_DOC_I
														     --AND vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
														     AND  V.CODIGOCLIENTE = sa.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_TIT,
--40
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE ''Operador'' END), 30) AS REL_FON_OPER,
--41
LEFT((CASE WHEN sos.IND_RTE = ''N'' THEN '''' ELSE (CASE WHEN (SELECT COUNT(1) FROM VW_CLIENTE_PERSONAS V WITH (NOLOCK)
  														   --inner join VTA_CUMPLIMIENTO vmov WITH (NOLOCK) on V.TIPODOCUMENTO = vmov.TIPO_DOC_M AND V.NUMERODOCUMENTO= vmov.NRO_DOC_M
														   WHERE V.TIPODOCUMENTO = vmov.TIPO_DOC_M 
														     AND V.NUMERODOCUMENTO= vmov.NRO_DOC_M
														   --vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
														     AND  V.CODIGOCLIENTE = sa.C1803) > 0 THEN ''SI'' ELSE ''NO'' END) END), 30) AS REL_PRO_OPER,
--
sa.JTS_OID
--SELECT mov.*
FROM MOVIMIENTOS_CONTABLES mov WITH (NOLOCK)
  INNER JOIN SOS_TRANSACCIONES sos WITH (NOLOCK) ON sos.CodTransaccion = mov.COD_TRANSACCION AND sos.Operacion = mov.OPERACION
    AND sos.Subsistema = ''PR''
    AND ((sos.PagosAInformar = ''T'') OR
         (sos.PagosAInformar = ''E'' AND mov.CAJADIARIO = ''C'') OR
         (sos.PagosAInformar = ''D'' AND mov.CAJADIARIO <> ''C''))
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = mov.SUCURSAL
  INNER JOIN SALDOS sa WITH (NOLOCK) ON sa.C1785 in (''5'',''8'') 
    AND sa.OPERACION = (CASE WHEN CHARINDEX('':'', mov.CONCEPTO) > 0 THEN convert(NUMERIC(12),SUBSTRING(mov.CONCEPTO, CHARINDEX('':'', mov.CONCEPTO)+2, 12)) ELSE 0 END)
	AND (CASE WHEN sa.C1785 IN (''5'',''8'') THEN ''PR'' END) =  sos.Subsistema
	AND ((sa.TZ_LOCK < 300000000000000 OR sa.TZ_LOCK >= 400000000000000) 
		AND (sa.TZ_LOCK < 100000000000000 OR sa.TZ_LOCK >= 200000000000000)) 
  LEFT JOIN VTA_CUMPLIMIENTO vmov WITH (NOLOCK) ON vmov.SUCURSAL = mov.SUCURSAL AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO
WHERE mov.FECHAPROCESO = @Fecha
  AND mov.CLIENTE <> 0
  AND sos.TZ_LOCK = 0
  AND suc.TZ_LOCK = 0
  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS x WITH (NOLOCK) 
  				 WHERE x.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' 
  				   AND x.ALFA_1 = sa.PRODUCTO
  				   AND x.TZ_LOCK = 0)
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASFISICAS nat WITH(NOLOCK) ON p.NUMEROPERSONA = nat.NUMEROPERSONAFISICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND nat.SECTOR IN (6,7)
  				   AND nat.TZ_LOCK = 0
  				   AND p.TZ_LOCK = 0
  				   AND cli.TZ_LOCK = 0)
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASJURIDICAS jur WITH(NOLOCK) ON p.NUMEROPERSONA = jur.NUMEROPERSONAJURIDICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND jur.SECTOR IN (6,7)
  				   AND jur.TZ_LOCK = 0
  				   AND p.TZ_LOCK = 0
  				   AND cli.TZ_LOCK = 0)

/**********************************
   TC - TARJETA DE CREDITO
**********************************/
INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
SELECT
--1
311 AS EMPRESA, 
--2
@FECHAPROCESO AS FECHADEINFORMACION,
--3
CONCAT(RIGHT(''0''+CONVERT(VARCHAR, B.SUC_CUENTA_COBRO),2), tra.SUBSISTEMA, CONVERT(VARCHAR, B.TIPO_TJC), CONVERT(VARCHAR,mov.USUARIO)) AS NUMERODECUENTA,
--4
(LEFT(concat(movc.ASIENTO, CONVERT(VARCHAR,movc.FECHAPROCESO,112), movc.SUCURSAL, movc.ORDINAL),22)) AS NUMERODEOPERACION,
--5
tra.SUBSISTEMA AS CLASEDECUENTA,
--6
tra.TIPOPERACION AS TIPODECUENTAUOPERACION,
--7
CONVERT(VARCHAR,suc.SucursalBCRA) AS SUCURSALSISCEN,
--8
CONVERT(VARCHAR,B.SUC_CUENTA_COBRO) AS SUCURSALINTERNA,
--9
CONVERT(VARCHAR,mov.FECHA,112) AS FECHADELAOPERACION,
--10
mov.PAGO_MN AS MONTOPESOS,
--11
mov.PAGO_ME AS ESPECIETRANSADACANTIDAD,
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WITH (NOLOCK) 
      WHERE m.C6399 = (CASE WHEN sa.MONEDA IN (988,999) THEN 1 ELSE sa.MONEDA END)
	    and m.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
--13
'''' AS BANCOCORRESPONSALSWIFT,
--14
'''' AS BENEFICIARIOORDENANTEDELEXTE,
--15
'''' AS PAISDELBENEFICIARIOORDENANTE,
--16
(CASE WHEN mov.CANAL IN (1, 4, 5) THEN ''EFSI'' ELSE ''EFNO'' END) AS DATOSADICIONALES,
--17
CONVERT(VARCHAR, mov.FECHA,112) AS FECHAALTA,
--18
--CONVERT(VARCHAR(5),tra.CODTRANSACCION) AS CODIGOSTOPAZ,
concat(right(concat(Replicate(''0'',4),tra.Operacion),4), tra.Subsistema, RIGHT(concat(Replicate(''0'',7), tra.CodTransaccion),7)) AS CODIGOSTOPAZ,
--19
(CASE WHEN mov.PAGO_MN > 0 AND mov.PAGO_ME = 0 THEN 0
  ELSE (SELECT TipC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK)
    WHERE TipC.FECHA_COTIZACION = mov.FECHA AND Tipc.MONEDA = sa.MONEDA AND Tipc.TZ_LOCK = 0)
END) AS COTIZACION,
--20
ISNULL((SELECT (CASE WHEN asi.ESTADO = 42 THEN ''SI'' ELSE ''NO'' END) FROM ASIENTOS asi WITH (NOLOCK)
 WHERE asi.FECHAPROCESO = mov.FECHA AND asi.ASIENTO = mov.ASIENTO AND asi.SUCURSAL = B.SUC_CUENTA_COBRO),''NO'') AS REVERSADA,
--21
'''' AS OPER_ID_BIC_SWIFT,
--22
'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
'''' AS RTE_OPE_FON_TIPO_PERSONA,
--24
''''  AS RTE_OPE_FON_DENOMINACION,
--25
''''   AS RTE_OPE_FON_APELLIDOS,
--26
''''  AS RTE_OPE_FON_NOMBRES,
--27
'''' AS RTE_OPE_FON_TIPODOC,
--28
''''  AS RTE_OPE_FON_NUMDOC,
--29
''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
''''  AS RTE_TIT_FON_TIPO_PERSONA,
--31
''''  AS RTE_TIT_FON_DENOMINACION,
--32
''''  AS RTE_TIT_FON_APELLIDOS,
--33
''''  AS RTE_TIT_FON_NOMBRES,
--34
'''' AS RTE_TIT_FON_TIPODOC,
--35
'''' AS RTE_TIT_FON_NUMDOC,
--36
'''' AS RTI_TIPOPERSONA,
--37
'''' AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
CONVERT(NUMERIC,CONVERT(VARCHAR, mov.FECHA,112)) AS FECHAAPERTURACUENTA, --Campo Usuario en el 1.16.4 SOS - Cuentas
--CLIENTE
B.CLIENTE AS CODCLIENTE,
--SUCURSAL BCRA
(SELECT sucx.SucursalBCRA FROM SOS_SUCURSALES sucx WITH (NOLOCK) where sucx.sucursal = B.SUC_CUENTA_COBRO and sucx.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
--38
'''' AS REL_FON_TIT,
--39
''NO'' AS REL_PRO_TIT,
--40
'''' AS REL_FON_OPER,
--41
''NO'' AS REL_PRO_OPER,
--
sa.JTS_OID
--SELECT MOV.* 
FROM TJC_HISTORICO_PAGOS mov WITH (NOLOCK)
  INNER JOIN MOVIMIENTOS_CONTABLES movc WITH (NOLOCK) ON movc.FECHAPROCESO = mov.FECHA AND movc.ASIENTO = mov.ASIENTO
  	/*AND movc.OPERACION = 2854*/ AND movc.SUCURSAL_CUENTA = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 400)
  INNER JOIN SOS_TRANSACCIONES tra WITH (NOLOCK) ON tra.CodTransaccion = movc.COD_TRANSACCION 
                           AND tra.Operacion = movc.OPERACION
                           AND ((tra.PagosAInformar = ''E'' AND mov.CANAL IN (1,4,5)) OR
                                (tra.PagosAInformar = ''D'' AND mov.CANAL NOT IN (1,4,5)) OR
                                (tra.PagosAInformar = ''T''))
  INNER JOIN TJC_MAESTRO_USUARIO B WITH (NOLOCK) ON B.ADMINISTRADORA = mov.ADMINISTRADORA AND B.USUARIO = mov.USUARIO
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = movc.SUCURSAL
  INNER JOIN SALDOS sa WITH (NOLOCK) ON sa.JTS_OID = mov.JTS_SALDO_TARJETA
    AND ((sa.TZ_LOCK < 300000000000000 OR sa.TZ_LOCK >= 400000000000000) 
		AND (sa.TZ_LOCK < 100000000000000 OR sa.TZ_LOCK >= 200000000000000)) 
WHERE mov.FECHA = @Fecha
  AND mov.TZ_LOCK = 0
  AND suc.TZ_LOCK = 0
  AND B.TZ_LOCK = 0
  AND NOT EXISTS(SELECT 1 FROM ITF_MASTER_PARAMETROS x WITH (NOLOCK) WHERE x.FUNCIONALIDAD = ''PRODUCTO JUDICIAL'' AND x.ALFA_1 = sa.PRODUCTO)
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASFISICAS nat WITH(NOLOCK) ON p.NUMEROPERSONA = nat.NUMEROPERSONAFISICA
  				 WHERE cli.CODIGOCLIENTE = mov.CLIENTE
  				   AND nat.SECTOR IN (6,7))
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASJURIDICAS jur WITH(NOLOCK) ON p.NUMEROPERSONA = jur.NUMEROPERSONAJURIDICA
  				 WHERE cli.CODIGOCLIENTE = mov.CLIENTE
  				   AND jur.SECTOR IN (6,7))

/**********************************
    Movimientos Externos o Transferencias al/del exterior
**********************************/
INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
SELECT
--1
311 AS EMPRESA, 
--2
@FECHAPROCESO AS FECHADEINFORMACION,
--3
CONCAT(RIGHT(''0''+CONVERT(VARCHAR, mov.CODSUCURSAL),2), ''ME'', CONVERT(VARCHAR,mov.CUENTA)) AS NUMERODECUENTA,
--4
'''' AS NUMERODEOPERACION,
--5
''ME'' AS CLASEDECUENTA,
--6
LEFT(mov.CODOPERACIONMOV,3) AS TIPODECUENTAUOPERACION,
--7
''0'' AS SUCURSALSISCEN,
--8
CONVERT(VARCHAR,mov.CODSUCURSAL) AS SUCURSALINTERNA,
--9
CONVERT(VARCHAR,mov.FECINGRESO,112) AS FECHADELAOPERACION,
--10
(CASE WHEN mov.CODMONEDA = 1 THEN mov.IMPORTEOPE ELSE 0 END) AS MONTOPESOS,
--11
(CASE WHEN mov.CODMONEDA <> 1 THEN mov.IMPORTEOPE ELSE 0 END)  AS ESPECIETRANSADACANTIDAD,
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WITH (NOLOCK) 
      WHERE m.C6399 = (CASE WHEN mov.CODMONEDA IN (988,999) THEN 1 ELSE mov.CODMONEDA END)
	    AND m.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
--13
mov.BANCOCORRESP AS BANCOCORRESPONSALSWIFT,
--14
mov.BENEFORDENEXT AS BENEFICIARIOORDENANTEDELEXTE,
--15
(SELECT pais.CODIGOSWIFT FROM CLI_PAISES pais WITH (NOLOCK) WHERE pais.CODIGOPAIS = mov.CODPAISBENEF AND pais.TZ_LOCK = 0) AS PAISDELBENEFICIARIOORDENANTE,
--16
'''' AS DATOSADICIONALES,
--17
CONVERT(VARCHAR, mov.FECINGRESO,112) AS FECHAALTA,
--18
CONCAT(''ME'',mov.CODCONCEPTO) AS CODIGOSTOPAZ,
--19
(CASE WHEN mov.CODMONEDA = 1 THEN 0
  ELSE 
   (SELECT TipC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK)
    WHERE TipC.FECHA_COTIZACION = CONVERT(DATE,CONVERT(VARCHAR, mov.FECINGRESO,103)) AND Tipc.MONEDA = mov.CODMONEDA AND Tipc.TZ_LOCK = 0)
END)
  AS COTIZACION,
--20
(CASE WHEN mov.MARCAREVERSADO = 1 THEN ''SI'' ELSE ''NO'' END) AS REVERSADA,
--21
CONCAT(CONCAT(REPLICATE(''0'',4),mov.CODSUCURSAL), mov.CODSISTEMA, CONCAT(REPLICATE(''0'',11),mov.OPERACION), 
      CONCAT(REPLICATE('' '',11),mov.CODOPERACIONMOV), CONCAT(REPLICATE(''0'',20),mov.NUMBOLETO), mov.FECINGRESO) AS OPER_ID_BIC_SWIFT,
--22
'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
'''' AS RTE_OPE_FON_TIPO_PERSONA,
--24
''''  AS RTE_OPE_FON_DENOMINACION,
--25
''''   AS RTE_OPE_FON_APELLIDOS,
--26
''''  AS RTE_OPE_FON_NOMBRES,
--27
'''' AS RTE_OPE_FON_TIPODOC,
--28
''''  AS RTE_OPE_FON_NUMDOC,
--29
''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
''''  AS RTE_TIT_FON_TIPO_PERSONA,
--31
''''  AS RTE_TIT_FON_DENOMINACION,
--32
''''  AS RTE_TIT_FON_APELLIDOS,
--33
''''  AS RTE_TIT_FON_NOMBRES,
--34
'''' AS RTE_TIT_FON_TIPODOC,
--35
'''' AS RTE_TIT_FON_NUMDOC,
--36
mov.TIPOPERSBENEF AS RTI_TIPOPERSONA,
--37
CONVERT(VARCHAR,mov.OPERACION) AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
CONVERT(NUMERIC,CONVERT(VARCHAR, mov.FECINGRESO,112)) AS FECHAAPERTURACUENTA, --Campo Usuario en el 1.16.4 SOS - Cuentas
--CLIENTE
C.CODCLIENTE AS CODCLIENTE,
--SUCURSAL BCRA
(select suc.SucursalBCRA from SOS_SUCURSALES bx WITH (NOLOCK) WHERE bx.SUCURSAL = b.CODSUCURSAL and bx.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
--38
'''' AS REL_FON_TIT,
--39
''NO'' AS REL_PRO_TIT,
--40
'''' AS REL_FON_OPER,
--41
''NO'' AS REL_PRO_OPER,
--
NULL AS JTS_OID
--SELECT * 
FROM ITF_I2000_MOVS_HIST mov WITH (NOLOCK)
  INNER JOIN ITF_I2000_CUENTAS_HIST B WITH (NOLOCK) ON B.CODSUCURSAL = mov.CODSUCURSAL AND B.CODSISTEMA = mov.CODSISTEMA AND B.NUMCUENTA = mov.CUENTA
  INNER JOIN ITF_I2000_CLIENTES_HIST C WITH (NOLOCK) ON C.TIPODOC = B.TIPODOCUMENTO AND C.NUMDOC = B.NUMDOCUMENTO
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = mov.CODSUCURSAL
  INNER JOIN SOS_TRANSACCIONES trx WITH (NOLOCK) ON trx.Subsistema = ''ME'' AND trx.TipOperacion = RIGHT(mov.CODOPERACIONMOV,3)
WHERE mov.FECINGRESO = @Fecha
  AND suc.TZ_LOCK = 0
  AND trx.TZ_LOCK = 0

/**********************************
    Titulos UNITRADE
**********************************/
INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CODCLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER, SALDO_JTS_OID)
SELECT
--1
311 AS EMPRESA, 
--2
@FECHAPROCESO AS FECHADEINFORMACION,
--3
CONCAT(RIGHT(''0''+CONVERT(VARCHAR, SA.SUCURSAL),2), ''TT'', CONVERT(VARCHAR,SA.CUENTA)) AS NUMERODECUENTA,
--4
CONCAT(mov.FECHA_INFORMACION, mov.NUMERO_MINUTA) AS NUMERODEOPERACION,
--5
''TT'' AS CLASEDECUENTA,
--6
mov.CODIGO_OPERACION_BCRA AS TIPODECUENTAUOPERACION,
--7
suc.SucursalBCRA AS SUCURSALSISCEN,
--8
CONVERT(VARCHAR,mov.SUCURSAL_OPERACION) AS SUCURSALINTERNA,
--9
mov.FECHA_OPERACION AS FECHADELAOPERACION,
--10
(CASE WHEN mov.MONEDA_OPERACION_ORIGEN = 1 THEN (CONVERT(NUMERIC(15,2), mov.IMPORTE_MONEDA_ORIGINAL)/100) ELSE 0 END) AS MONTOPESOS,
--11
(CASE WHEN mov.MONEDA_OPERACION_ORIGEN <> 1 THEN (CONVERT(NUMERIC(15,2), mov.IMPORTE_MONEDA_ORIGINAL)/100) ELSE 0 END)  AS ESPECIETRANSADACANTIDAD,
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WITH (NOLOCK) 
      WHERE m.C6399 = (CASE WHEN mov.MONEDA_OPERACION_ORIGEN IN (988,999) THEN 1 ELSE mov.MONEDA_OPERACION_ORIGEN END)
	    and m.TZ_LOCK = 0),10) AS ESPECIETRANSADATIPO,
--13
'''' AS BANCOCORRESPONSALSWIFT,
--14
'''' AS BENEFICIARIOORDENANTEDELEXTE,
--15
'''' AS PAISDELBENEFICIARIOORDENANTE,
--16
mov.TIPO_ESPECIE AS DATOSADICIONALES,
--17
mov.FECHA_OPERACION AS FECHAALTA,
--18
'''' AS CODIGOSTOPAZ,
--19
(CASE WHEN mov.MONEDA_OPERACION_ORIGEN = 1 THEN 0
  ELSE 
   (SELECT TipC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TipC WITH (NOLOCK)
    WHERE TipC.FECHA_COTIZACION = CONVERT(DATE,CONVERT(VARCHAR, mov.FECHA_OPERACION,103)) AND Tipc.MONEDA = mov.MONEDA_OPERACION_ORIGEN AND Tipc.TZ_LOCK = 0)
END)
  AS COTIZACION,
--20
(CASE WHEN mov.ACCION IN (''Reversado'',''Anulado'') THEN ''SI'' ELSE ''NO'' END) AS REVERSADA,
--21
'''' AS OPER_ID_BIC_SWIFT,
--22
'''' AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
'''' AS RTE_OPE_FON_TIPO_PERSONA,
--24
''''  AS RTE_OPE_FON_DENOMINACION,
--25
''''   AS RTE_OPE_FON_APELLIDOS,
--26
''''  AS RTE_OPE_FON_NOMBRES,
--27
'''' AS RTE_OPE_FON_TIPODOC,
--28
''''  AS RTE_OPE_FON_NUMDOC,
--29
''''  AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
''''  AS RTE_TIT_FON_TIPO_PERSONA,
--31
''''  AS RTE_TIT_FON_DENOMINACION,
--32
''''  AS RTE_TIT_FON_APELLIDOS,
--33
''''  AS RTE_TIT_FON_NOMBRES,
--34
'''' AS RTE_TIT_FON_TIPODOC,
--35
'''' AS RTE_TIT_FON_NUMDOC,
--36
'''' AS RTI_TIPOPERSONA,
--37
'''' AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
CONVERT(NUMERIC,CONVERT(VARCHAR,sa.c1620 ,112)) AS FECHAAPERTURACUENTA, --Campo Usuario en el 1.16.4 SOS - Cuentas
--CLIENTE
sa.C1803 AS CODCLIENTE,
--SUCURSAL BCRA
(select suc.SucursalBCRA from SOS_SUCURSALES bx WITH (NOLOCK) WHERE bx.SUCURSAL = mov.SUCURSAL_CUENTA_PARTE and bx.TZ_LOCK = 0) AS SUCURSALSISCENCTA,
--38
'''' AS REL_FON_TIT,
--39
''NO'' AS REL_PRO_TIT,
--40
'''' AS REL_FON_OPER,
--41
''NO'' AS REL_PRO_OPER,
--
NULL AS JTS_OID
--SELECT * 
FROM ITF_UNTD_IMPUESTOS mov WITH (NOLOCK)  
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = mov.SUCURSAL_OPERACION
  INNER JOIN SOS_TRANSACCIONES trx WITH (NOLOCK) ON trx.Subsistema = ''TT'' AND trx.TipOperacion = mov.CODIGO_OPERACION_BCRA
  INNER JOIN REL_CLIENTE_CTA_COMITENTE cta WITH (NOLOCK) ON cta.CUENTA = mov.NUMERO_CUENTA_PARTE
  INNER JOIN SALDOS SA WITH (NOLOCK) ON SA.CUENTA = cta.CUENTA 
    AND ((sa.TZ_LOCK < 300000000000000 OR sa.TZ_LOCK >= 400000000000000) 
		AND (sa.TZ_LOCK < 100000000000000 OR sa.TZ_LOCK >= 200000000000000)) 
WHERE mov.FECHA_INFORMACION = @Fecha
  AND suc.TZ_LOCK = 0
  AND trx.TZ_LOCK = 0
  
  
END
')