EXECUTE('
ALTER PROCEDURE [dbo].[SP_ACTUALIZA_DISCREPANCIA]
	@p_id_proceso FLOAT(53),     /* Identificador de proceso */
	@p_dt_proceso DATETIME,   /* Fecha de proceso */
	@p_ret_proceso FLOAT OUT, /* Estado de ejecucion SQL(0:Correcto, 2: Error) */
	@p_msg_proceso VARCHAR(MAX) OUT
AS
BEGIN
	DECLARE 
	------- Campos para el LOG --------
	@c_log_tipo_error varchar(30),
	@c_log_tipo_informacion VARCHAR(30),
	-----------------------------------	
	@contador NUMERIC(10)
	SET @contador = 0;
	------- Campos para el LOG --------
	SET @c_log_tipo_error = ''E'';
	SET @c_log_tipo_informacion = ''I'';
	-----------------------------------	
	DECLARE @CLIENTES_CENDEU TABLE (CODIGOCLIENTE NUMERIC(11), DEUDA_TOTAL NUMERIC(15,2), SITUACION_ENTIDAD NUMERIC(1), 
							COD_ENTIDAD NUMERIC(5),CATEGORIAOBJETIVA VARCHAR(3),CATEGORIA_COMERCIAL VARCHAR(3),
							OBJETIVA_REFINANCIADO VARCHAR(3)
						   )
						   
	BEGIN TRY
        INSERT INTO @CLIENTES_CENDEU
		SELECT c.CODIGOCLIENTE, b.DEUDA_TOTAL, b.SITUACION_ENTIDAD, 
		CAST(b.COD_ENTIDAD AS NUMERIC(5))
		, c.CATEGORIAOBJETIVA, c.CATEGORIA_COMERCIAL, c.OBJETIVA_REFINANCIADO 
		FROM CLI_CLIENTES c (nolock)
		INNER JOIN CRE_BCRA_CENDEU b WITH (nolock) ON c.CODIGOCLIENTE=b.CODIGOCLIENTE
		WHERE (c.CATEGORIAOBJETIVA <> '' '' AND c.OBJETIVA_REFINANCIADO <> '' '') AND c.TZ_LOCK=0 AND b.TZ_LOCK=0  
		
			  
		SET @contador =	(SELECT count(1)
		FROM CLI_CLIENTES c WITH (NOLOCK)
		-- Deuda fuera de la institucion que supere total de niveles peores
		INNER JOIN (SELECT cen.CODIGOCLIENTE, sum(cen.DEUDA_TOTAL) AS DEUDA 
				FROM @CLIENTES_CENDEU cen
				-- CRE_BCRA_CENDEU cen WITH (NOLOCK)
				--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
				INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
				INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
				WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND cen.SITUACION_ENTIDAD <> ''6'' AND
				cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))		
				GROUP BY cen.CODIGOCLIENTE) d ON c.CODIGOCLIENTE = d.CODIGOCLIENTE 
		-- Deuda TOTAL fuera de la institucion
		INNER JOIN (SELECT cen.CODIGOCLIENTE, sum(cen.DEUDA_TOTAL) AS DEUDA 
				FROM @CLIENTES_CENDEU cen
				--CRE_BCRA_CENDEU cen WITH (NOLOCK)
				--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
				WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2)AND cen.SITUACION_ENTIDAD <> ''6'' AND
				cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))				
				GROUP BY cen.CODIGOCLIENTE) dt ON c.CODIGOCLIENTE = dt.CODIGOCLIENTE 
		-- Busco deuda con la institucion		
		INNER JOIN (SELECT CODIGOCLIENTE, sum(DEUDA_TOTAL) AS DEUDA 
				FROM CRE_BCRA_CENDEU WITH (NOLOCK)
				WHERE COD_ENTIDAD = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND TZ_LOCK = 0 				
				GROUP BY CODIGOCLIENTE) dm ON c.CODIGOCLIENTE = dm.CODIGOCLIENTE				
		/*INNER JOIN (SELECT sum(SALDO) AS DEUDA, CLIENTE 
				FROM VW_ASISTENCIAS WITH (NOLOCK)
				WHERE SALDO > 0
				GROUP BY CLIENTE ) dm ON c.CODIGOCLIENTE = dm.CLIENTE */
		-- Cantidad de entidades con niveles peores que el actual
		INNER JOIN (SELECT cen.CODIGOCLIENTE, count(cen.CODIGOCLIENTE) AS CANTIDAD
				  FROM @CLIENTES_CENDEU cen
				--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
				--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
				INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
				INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
				WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2)  AND cen.SITUACION_ENTIDAD <> ''6'' AND
				cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))
				GROUP BY cen.CODIGOCLIENTE) cant ON c.CODIGOCLIENTE = cant.CODIGOCLIENTE AND cant.CANTIDAD >= (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 169)			
		-- Busco peor nivel con mayor deuda			   
		INNER JOIN (SELECT b.CODIGOCLIENTE, b.PONDERACION 
					FROM (
						SELECT a.CODIGOCLIENTE, a.PONDERACION,
						ROW_NUMBER() OVER(PARTITION BY a.CODIGOCLIENTE ORDER BY a.DEUDA_TOTAL DESC) AS CANTIDAD
						FROM(
							SELECT cen.CODIGOCLIENTE, pon1.PONDERACION, sum(cen.DEUDA_TOTAL) AS DEUDA_TOTAL
							FROM @CLIENTES_CENDEU cen
							--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
							--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
							INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
							INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																			AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
							WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2)  AND cen.SITUACION_ENTIDAD <> ''6'' AND
							cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD  FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))
							GROUP BY cen.CODIGOCLIENTE, pon1.PONDERACION) a 
						) b
					WHERE b.CANTIDAD = 1) pn ON c.CODIGOCLIENTE = pn.CODIGOCLIENTE	
		WHERE c.TZ_LOCK = 0 AND
		round(( d.DEUDA / (dt.DEUDA + dm.DEUDA) ),2) * 100  >= (SELECT IMPORTE FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 168))				

-- Si existen registros candidatos actualizamos
	   	IF @contador > 0
		BEGIN
			UPDATE c
			SET c.DISCREPANCIA = a.CATEGORIASUB
			FROM CLI_CLIENTES c WITH (NOLOCK)
			INNER JOIN (SELECT c.CODIGOCLIENTE, p.CATEGORIASUB
				FROM CLI_CLIENTES c WITH (NOLOCK)
				-- Deuda fuera de la institucion que supere total de niveles peores
				INNER JOIN (SELECT cen.CODIGOCLIENTE, sum(cen.DEUDA_TOTAL) AS DEUDA 
						FROM @CLIENTES_CENDEU cen
						--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
						--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
						INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
						INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																		AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
						WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND cen.SITUACION_ENTIDAD <> ''6'' AND
						cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))		
						GROUP BY cen.CODIGOCLIENTE) d ON c.CODIGOCLIENTE = d.CODIGOCLIENTE 
				-- Deuda TOTAL fuera de la institucion
				INNER JOIN (SELECT cen.CODIGOCLIENTE, sum(cen.DEUDA_TOTAL) AS DEUDA 
						FROM @CLIENTES_CENDEU cen
						--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
						--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
						WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND cen.SITUACION_ENTIDAD <> ''6'' AND
						cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))				
						GROUP BY cen.CODIGOCLIENTE) dt ON c.CODIGOCLIENTE = dt.CODIGOCLIENTE 
				-- Busco deuda con la institucion		
				INNER JOIN (SELECT CODIGOCLIENTE, sum(DEUDA_TOTAL) AS DEUDA 
						FROM @CLIENTES_CENDEU cen
						--FROM CRE_BCRA_CENDEU WITH (NOLOCK)
						WHERE COD_ENTIDAD = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2)				
						GROUP BY CODIGOCLIENTE) dm ON c.CODIGOCLIENTE = dm.CODIGOCLIENTE				
				/*INNER JOIN (SELECT sum(SALDO) AS DEUDA, CLIENTE 
						FROM VW_ASISTENCIAS WITH (NOLOCK)
						WHERE SALDO > 0
						GROUP BY CLIENTE ) dm ON c.CODIGOCLIENTE = dm.CLIENTE */
				-- Cantidad de entidades con niveles peores que el actual
				INNER JOIN (SELECT cen.CODIGOCLIENTE, count(cen.CODIGOCLIENTE) AS CANTIDAD
						FROM @CLIENTES_CENDEU cen
						--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
						--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
						INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
						INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																		AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
						WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND cen.SITUACION_ENTIDAD <> ''6'' AND
						cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))
						GROUP BY cen.CODIGOCLIENTE) cant ON c.CODIGOCLIENTE = cant.CODIGOCLIENTE AND cant.CANTIDAD >= (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 169)			
				-- Busco peor nivel con mayor deuda			   
				INNER JOIN (SELECT b.CODIGOCLIENTE, b.PONDERACION FROM (
								SELECT a.CODIGOCLIENTE, a.PONDERACION,
								ROW_NUMBER() OVER(PARTITION BY a.CODIGOCLIENTE ORDER BY a.DEUDA_TOTAL DESC) AS CANTIDAD
								FROM(
									SELECT cen.CODIGOCLIENTE, pon1.PONDERACION, sum(cen.DEUDA_TOTAL) AS DEUDA_TOTAL
									FROM @CLIENTES_CENDEU cen
									--FROM CRE_BCRA_CENDEU cen WITH (NOLOCK)
									--INNER JOIN CLI_CLIENTES cli WITH (NOLOCK) ON cen.CODIGOCLIENTE = cen.CODIGOCLIENTE AND cen.TZ_LOCK = 0
									INNER JOIN CLI_CLASUBJETIVA pon1 WITH (NOLOCK) ON pon1.CATEGORIASUB = CAST(cen.SITUACION_ENTIDAD AS VARCHAR(2)) AND pon1.TZ_LOCK = 0
									INNER JOIN CLI_CLASUBJETIVA pon2 WITH (NOLOCK) ON pon2.CATEGORIASUB = (CASE WHEN (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.CATEGORIAOBJETIVA, '' '')) >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH (NOLOCK) WHERE CATEGORIASUB = isnull(cen.OBJETIVA_REFINANCIADO,'' '')) THEN cen.CATEGORIAOBJETIVA ELSE cen.OBJETIVA_REFINANCIADO END)
																					AND pon2.TZ_LOCK = 0 AND pon2.PONDERACION + (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 170) < pon1.PONDERACION 
									WHERE cen.COD_ENTIDAD <> (SELECT NUMERICO FROM PARAMETROSGENERALES WITH (NOLOCK) WHERE CODIGO = 2) AND cen.SITUACION_ENTIDAD <> ''6'' AND
									cen.COD_ENTIDAD NOT IN (SELECT ENTIDAD FROM CRE_Excep_Ent_Discrepancia WITH (NOLOCK) WHERE TZ_LOCK = 0 AND (CARTERA = ''T'' OR CARTERA = cen.CATEGORIA_COMERCIAL OR (CARTERA = ''C'' AND cen.CATEGORIA_COMERCIAL = ''S'')))
									GROUP BY cen.CODIGOCLIENTE, pon1.PONDERACION) a ) b
								WHERE b.CANTIDAD = 1) pn ON c.CODIGOCLIENTE = pn.CODIGOCLIENTE	
				INNER JOIN CLI_CLASUBJETIVA p ON pn.PONDERACION - (SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 171) = p.PONDERACION AND p.TZ_LOCK = 0
				WHERE c.TZ_LOCK = 0 AND
				round((d.DEUDA / (dt.DEUDA + dm.DEUDA) ),2) * 100 >= (SELECT IMPORTE FROM CRE_PARAMETROS WITH (NOLOCK) WHERE CODIGO = 168)) a
			ON a.CODIGOCLIENTE = c.CODIGOCLIENTE
			WHERE c.TZ_LOCK = 0	
				
		END
		  
		SET @p_msg_proceso = ''El Proceso de Actualización de Discrepancia ha finalizado correctamente. Registros procesados: ''+ CONVERT(VARCHAR(10), @contador)
		SET @p_ret_proceso = 1 		
			
		-- Logueo de información
		EXECUTE PKG_LOG_PROCESO$proc_ins_log_proceso 
			@p_id_proceso,
		   	@p_dt_proceso,
		   	''SP_ACTUALIZA_DISCREPANCIA'',
		   	@p_cod_error = @p_ret_proceso, 
			@p_msg_error = @p_msg_proceso, 
			@p_tipo_error = @c_log_tipo_informacion
	END TRY
							             
	BEGIN CATCH
	
	    SET @p_ret_proceso = ERROR_NUMBER()
	    SET @p_msg_proceso = ''Ocurrió un error en el Proceso de Actualización de Discrepancia: '' + ERROR_MESSAGE()
	
		EXECUTE PKG_LOG_PROCESO$proc_ins_log_proceso 
	       	@p_id_proceso = @p_id_proceso, 
	       	@p_fch_proceso = @p_dt_proceso, 
	       	@p_nom_package = ''SP_ACTUALIZA_DISCREPANCIA'', 
	       	@p_cod_error = @p_ret_proceso, 
	       	@p_msg_error = @p_msg_proceso, 
	  		@p_tipo_error = @c_log_tipo_informacion
	END CATCH
END
')