execute('
CREATE TABLE dbo.ITF_ECHEQ_CONCILIACION_HIST
	(
	FECHA_ARCHIVO    DATETIME NOT NULL,
	VERSION_CABEZAL  VARCHAR (3) NULL,
	CODIGO_ENTIDAD   NUMERIC (3) NULL,
	HORA_CORTE       NUMERIC (4) NULL,
	TIPO_OBJETO      VARCHAR (5) NULL,
	ID_CHEQUE        VARCHAR (15) NOT NULL,
	TIPO_MOVIMIENTO  VARCHAR (1) NOT NULL,
	FECHA            DATETIME NULL,
	HORA             NUMERIC (4) NOT NULL,
	CBU              VARCHAR (22) NULL,
	CUIT             NUMERIC (11) NULL,
	IMPORTE          NUMERIC (15, 2) NULL,
	CMC7             VARCHAR (29) NULL,
	CODIGO_RECHAZO   VARCHAR (3) NULL,
	VERSION_DETALLE  VARCHAR (3) NULL,
	RECHAZO_ACORDADO VARCHAR (1) NULL,
	FECHA_ACUREDO    DATETIME NULL,
	CEDIDO           VARCHAR (1) NULL,
	FECHA_CESION     DATETIME NULL,
	NOMBRE_ARCHIVO   VARCHAR (25) NULL
	CONSTRAINT PK_ITF_ECHEQ_CONCILIACION_HIST PRIMARY KEY (FECHA_ARCHIVO,ID_CHEQUE,TIPO_MOVIMIENTO,HORA)
	)
');
