EXECUTE('
IF OBJECT_ID (''dbo.DEUDORES_4302'') IS NOT NULL
	DROP TABLE dbo.DEUDORES_4302;
')
EXECUTE('
CREATE TABLE dbo.DEUDORES_4302
	(
	CODIGO_DISENIO            NUMERIC (4),
	CONCEPTO                  NUMERIC (1),
	CATEGORIA                 NUMERIC (1),
	SITUACION                 NUMERIC (2),
	GAR_PREF_A_CAP_INT        NUMERIC (12),
	GAR_PREF_B_CAP_INT_NOPREV NUMERIC (12),
	GAR_PREF_B_INT_PREV       NUMERIC (12),
	SIN_GAR_CAP_INT_NOPREV    NUMERIC (12),
	SIN_GAR_INT_PREV          NUMERIC (12),
	CANT_DEUDORES             NUMERIC (6),
	FECHA_PROCESO             DATE
	);
')