Execute('
--GRL_SALDOS_DIARIOS
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = ''IX_GRL_SALDOS_DIARIOS_FECHA'' AND object_id = OBJECT_ID(''GRL_SALDOS_DIARIOS''))
    DROP INDEX IX_GRL_SALDOS_DIARIOS_FECHA ON GRL_SALDOS_DIARIOS;
CREATE NONCLUSTERED INDEX IX_GRL_SALDOS_DIARIOS_FECHA
ON GRL_SALDOS_DIARIOS (TZ_LOCK,FECHA,SALDO_AJUSTADO)
INCLUDE (RUBROCONTABLE,SUCURSAL,MONEDA,PROMEDIO_DIARIO)')

Execute('
--RRI_PARAMETROS_INF
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = ''IX_RRI_PARAMETROS_INF_ID1'' AND object_id = OBJECT_ID(''RRI_PARAMETROS_INF''))
    DROP INDEX IX_RRI_PARAMETROS_INF_ID1 ON RRI_PARAMETROS_INF;
CREATE NONCLUSTERED INDEX IX_RRI_PARAMETROS_INF_ID1
ON RRI_PARAMETROS_INF (ID1, TZ_LOCK, CODIGO)
INCLUDE (NUM1);')

