EXECUTE('
INSERT INTO IMP_PARAM_SEG_TASAS VALUES (0, 0.006)
INSERT INTO IMP_PARAM_SEG_TASAS VALUES (1, 0.0025)
INSERT INTO IMP_PARAM_SEG_TASAS VALUES (2, 0.00075)
INSERT INTO IMP_PARAM_SEG_TASAS VALUES (3, 0)
')