service ACTUALIZARRELACIONCC;
description "Actualiza la Relacion Conyugal, solo para casar";

 action:OperationQuery ejecutarOperacion
(


	TIPODOC: string,
      	NRODOC: string,
      	PAISDOC: numeric,
     	ESTADOCIVIL: string,
      	TIPODOCCONY: string,
	NRODOCCONY: string,
        PAISDOCCONY: numeric,  
        PRIMERAPELLIDO: string, 
	PRIMERNOMBRE: string,
	PAISNAC: numeric,
	SEXO: string,
	PAISRES: numeric,
	DEPTO: string,
	CODIGOPOSTAL: string,
	CIUDAD: string,
	CALLE: string,
	NROPUERTA: string,
	FECHANAC: string,
	FECHAVTO: string, 
	SEGUNDOAPELLIDO: string, 
	SEGUNDONOMBRE: string,
	NACIONALIDAD: string,
	APTO: string,
	PISO: numeric,
	TIPOVIVIENDA: string, 
	TELFIJO: string,
	TELCELU: string 

): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR,
	C2615: numeric as NROPERSONA
	
	

	

] {

	properties
	{
		("operationNumber", "6792")
	
		}

}