service ALTAINTERFAZCRM;
description "Notificacion de Incio de Tramite";

action:OperationQuery ejecutarOperacion
(

	IdMovCrm: numeric,
	TipoMovCrm: string,
	CodProducto: numeric,
	TipoDocumento:string,
	NumeroDocumento:string,
	PaisDocumento:numeric,
	Importe:float,
	Sucursal: numeric,
	Usuario:string,
	CampaniaCrm: string,
	Observaciones: string,
	IdPersona: numeric,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
	

        
): [
	C4898: string as CODERROR
	
	

] {

	properties
	{
		("operationNumber", "9921")
			
		}

}
