service ALTATDCCC;
description "ALTA TARJETA CREDITO PARA CALLCENTER";

 action: SQLQuery ALTATDC(
	   
	Producto: numeric,
	Cliente: numeric,
	Canal: numeric,
	Paquete: numeric,
	Campania: numeric,
	Prioritario: string,
	Moneda: numeric,
	LimiteSolic: numeric,
	FechaVenc: date,
	VencTarj: date,
	Responsabilidad: string,
	TipoResp: string,
	MontoEECC: numeric,
	Marca: string,
	Programa: numeric,
	Cobertura: numeric,
	Destino: string,
	TipoTarj: string,
	Permanente: string,
	Ciclo: numeric,
	CanalDist: numeric,
	Grupo: string,
	Promotor: numeric,
	VIP: string,
	GeneraTarj: string,
	Idioma: numeric,
	NombreEmb: string,
	SolicitaAdic: string,
	NroPersonaAdic: numeric,
	Cobertura: numeric,
	GeneraTarjAdic: string,
	ParentezcoAdic: numeric,
	NombreEmbAdic: string,
	PermanenteAdic: string,
	ResponsabAdic: string,
	DebitoAut: string,
	CuentaDeb: numeric,
	TipoPago: string,
	MonedaCont: string 
	 
	 ): [ 
	   
	 CODERROR: string as CodError,
	 MSGERROR: string as MsgError,
	 NROSOLICITUD: numeric as NroSolicitud
	 	
	]{
    	
    	    properties 
    			{ 
    			("statement", "SELECT '0' as CODERROR, 'OK' as MSGERROR, 123456 as NROSOLICITUD from DUAL") 
    			  
    
                   }
}

