service AUMENTOLINEATDC;
description "Ingresar por CRM aumento de línea para tarjeta de crédito";

 action:OperationQuery ejecutarOperacion(
	   
	SOLICITUDCRM: string,
	CTATARJETA: numeric,      
	MONEDA: numeric,      
	LIMITE: numeric
	
	): [
	
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR

     ] {

	properties
	{
		("operationNumber", "6789")
	
		}

}