service CAMBIOESTADOCC;
description "Cambio estado CRM-In Concert";

action:OperationQuery ejecutarOperacion
(

 SOLICITUDCRM: string,
 PRODUCTO: numeric,
 ESTADO: string

): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR

	

] {

	properties
	{
		("operationNumber", "6786")
	
		}

}