service CAPACIDADPAGOCC;
description "Capacidad de Pago CRM-In Concert";

action:OperationQuery ejecutarOperacion
(

 SOLICITUDCRM      : string,	
 TIPODOC           : string,
 NRODOC		   : string,
 PAISDOC	   : numeric,
 FUENTEINGRESO	   : string,
 INGRESOLIQ   	   : numeric,
 VIATICOSSINREND   : numeric,
 VIATICOSCONREND   : numeric,
 PARTIDASEXT  	   : numeric,
 HORASEXTRAS  	   : numeric,
 COMISIONES   	   : numeric,
 ADELANTOS         : numeric,
 PARTIDASVAR       : numeric,
 PRODUCTO          : numeric,
 MONEDA            : numeric,
 CAPITAL           : numeric,
 VALORCUOTA        : numeric,
 CAMPANIA          : numeric,
 PROGRAMA          : numeric,
 FECHAINGRESO      : string,
 EMPRESA           : string,
 INGRESO_NOMINAL   : numeric,
 RUC_INDEP         : numeric,
 TELEFONO          : string
        
): [
	
	C4131: numeric as CODERROR,
	C904: string  as DESCERROR,
	C537: string as RESULTADO,
	C4192: numeric as IMPORTE
	
	

] {

	properties
	{
		("operationNumber", "6783")
	
		}

}