service CAPENDEUDCC;
description "Capacidad endeudamiento";

action:SQLQuery CAPENDEUD
(

TIPODOC: string,
NRODOC: string,
PAISDOC: numeric
        
): [
	CODERROR: string as CODERROR,
	DESCERROR: string  as DESCERROR,
	MONTO: numeric as MONTO


] {
    	
    	    properties 
    			{ 
    			("statement", "SELECT '0' as CODERROR, '' as DESCERROR, 10500 as MONTO from DUAL") 
    			  
    
}

}