service CLIENTESDEUNAPERSONA;
description "Consulta de Clientes de una Persona";

action:OperationQuery ejecutarOperacion
(

	IdPersona: numeric,
	NroDocumento: string,
	TipoDocumento: string,
	PaisDocumento: numeric,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
        
): [
	C4898: string as CODERROR,
	C3793: numeric as IdCliente,
	C4862: string as RolPersona,
	C4837: string as PrimerNombre,
	C4838: string as PrimerApellido,
	C656 : string as NombreCliente,
	C745 : string as TipoDocumento,
	C746 : string as NroDocumento,
	C747 : string as EjecutivoCli,
	C2615: numeric as IdPersona
	

] {

	properties
	{
		("operationNumber", "9929"),
		("transaction", "6")
	
		}

}