service COMPRAVENTA;
description "Compra Venta de Moneda Extranjera";

action:OperationQuery ejecutarOperacion
(

	ImporteOrigen: numeric,
	ImporteDestino: numeric,
	MonedaOrigen: numeric,
	MonedaDestino: numeric,
	ImporteCambio: numeric,
	TipoCotizacion: string,
	Cotizacion: numeric,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
	

        
): [
	C4898: string as CodError,
	C2616: numeric as Numerador
	
	
	

] {

	properties
	{
		("operationNumber", "9959")
			
		}

}
