service CONSULTATRANSFERNCIA;
description "Consulta de Transferencia entre cuentas del banco";

action:OperationQuery ejecutarOperacion
(

SucursalDeb: numeric,
ProductoDeb: numeric,
CuentaDeb: numeric,
MonedaDeb: numeric,
OperacionDeb: numeric,
OrdinalDeb: numeric,
SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
OperacionAcr: numeric,
OrdinalAcr: numeric,
DiasValor: numeric,
TipoCotizacion: string,
Mercado: string,
TipoProceso: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
MontoIngreso: float,
MonedaIngresada: numeric,
IdInvocaTopaz: string
        
): [
	C4898: string as CODERROR,
	C611: numeric as Moneda,
	C4837: string as NombreProdCred,
	C718: float as MontoDebito,
	C4838: string as NombreProdDeb,
	C720: float as MontoCredito,
	C7781: float as Arbitraje,
	C7776: float as Cotizacion,
	C429: numeric as CuentaAcr,
	C2615: numeric as CuentaDeb
	
	

] {

	properties
	{
		("operationNumber", "9937")
	
		}

}