service CONSULTAPRODUCTOPRIMERNIVEL; 
description "Consulta de Productos de Primer Nivel"; 


	action: OperationQuery ejecutarOperacion(
				
	IdPersona: string,
	TipoDocumento: string,
	NumeroDocumento: string,
	PaisDocumento: numeric,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
	
			
			
	): [
		C3901: string as XML_TAG, 
		C4898: string as CodError,
		C9635: string as ProdDescTopaz,
		C9636: numeric as Cuenta,
		C9637: float as Saldo,
		C9638: string as NroTarjeta,
		C9639: numeric as Paquete,
		C9640: numeric as ClaveLegada,
		C9641: string as TipoProducto,
		C9642: string as ProductoTopaz,
		C9643: string as DesTipoProdcto,
		C9644: numeric as Moneda,
		C9645: numeric as Operacion,
		C9633: numeric as Cliente,
		C6900: string as SimboloMoneda

		
		
	
	] {
	
		properties
		{
			("operationNumber", "9960"),
			("transaction", "7")
		
			}
	
}