service CONSULTASOLPVTA;
description "Consulta de Solicitudes de Compra en PVTA";

action:OperationQuery ejecutarOperacion
(

NroSolicitud: numeric
        
): [
	
	C121: string as CodError,
	C9208: string as Mensaje,
	C4191: float as CapitalMo,
	C934: string as NombreDeudor,
	C4192: float as Cuota,
	C4193: float as ImpSolicitadoMo,
	C1433: string as Moneda,
	C2631: numeric as CantidadCuotas,
	C4194: float as TasaMora,
	C6587: string as Resultado,
	C4197: float as ResuIvaComMol,
	C2611: numeric as NroSolicitud,
	C231: string as MotivoRechazo,
	C536: numeric as PeriodoPago,
	C4195: float as Comision,
	C4196: float as TasaIntAnual


] {

	properties
	{
		("operationNumber", "2039")
	
		}

}