service CONSULTAESTADO; 
description "Consulta estado de un proceso CRM"; 

action:	SQLQuery CONSULTAESTADO ( 
	IDMOVCRM: numeric
	
): [ 
 	ESTADO: string,
 	ERROR: string
]
{ 
  	properties { 
  	("statement", "SELECT ESTADO, ERROR FROM ITF_TOPAZCRM WHERE IDMVOCRM=?"),
	("0", "IDMOVCRM"), 
	
	}
}