service CONSULTAMULTSALDOS;
description "Consulta de Multiples Saldos de Cuentas";

action:OperationQuery ejecutarOperacion
(

Cuenta1: string,
Cuenta2: string,
Cuenta3: string,
Cuenta4: string,
Cuenta5: string,
Cuenta6: string,
Cuenta7: string,
Cuenta8: string,
Cuenta9: string,
Cuenta10: string,
TipoProceso: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C3168: string as Cuenta1,
	C686: float  as Saldo1,
	C3169: string as Cuenta2,
	C687: float  as Saldo2,
	C3170: string as Cuenta3,
	C688: float  as Saldo3,
	C3171: string as Cuenta4,
	C689: float  as Saldo4,
	C3172: string as Cuenta5,
	C576: float  as Saldo5,
	C3173: string as Cuenta6,
	C671: float  as Saldo6,
	C764: string as Cuenta7,
	C672: float  as Saldo7,
	C765: string as Cuenta8,
	C673: float  as Saldo8,
	C766: string as Cuenta9,
	C674: float  as Saldo9,
	C767: string as Cuenta10,
	C675: float  as Saldo10
	

	
	

] {

	properties
	{
		("operationNumber", "9972")
	
		}

}