service CONSULTACLIENTE; 
description "Parámetros de entrada al servicio CONSULTACLIENTE"; 

action:	SQLQuery CONSULTACLIENTE ( 
	IDCLIENTE: numeric
	
): [ 
 	CODERROR: numeric, 
	NOMBRECLIENTE: string,
	CALLE: string,
	NUMEROPUERTA: string,
	TELEFONO: string,
	FECHAAPERTURA: date,
	TIPO: string, 
	CODIGOBLOQUEO: string
	
	
]
{ 
  	properties { 
  	("statement", "SELECT 0 AS CODERROR,NOMBRECLIENTE,CALLE,NUMEROPUERTA,TELEFONOPREFERIDO as TELEFONO,FECHAAPERTURA,TIPO,CODIGOBLOQUEO FROM CLI_CLIENTES C, CLI_DIRECCIONES_CLIENTES D WHERE C.CODIGOCLIENTE=? AND C.CODIGOCLIENTE=D.CODIGOCLIENTE AND TipoDireccion=2"),
	("0", "IDCLIENTE")
	
	}
}