service CONSULTATJD;
description "Consulta de Tarjetas de Debito por Documento";

action:OperationQuery ejecutarOperacion
(

	
	TipoDocumento: string,
	NroDocumento: string,
	PaisDocumento: numeric,
	Estado: string,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
        
): [
	C3901: string as XML_TAG,
	C4898: string as CodError,
	C9152: string as NroTarjeta,
	C3875: string as Marca
	
	
	
	

] {

	properties
	{
		("operationNumber", "9978"),
		("transaction", "7")
	
		}

 

    
  }  