service CONSULTACOTIZACION;
description "Consulta de Cotizacion para Compra/Venta ME";

action:OperationQuery ejecutarOperacion
(
        
	SucursalAcr: numeric,
	ProductoAcr: numeric,
	CuentaAcr: numeric,
	MonedaAcr: numeric,
	OperacionAcr: numeric,
	OrdinalAcr: numeric,
	MontoIngresado: numeric,
	MonedaIngresada: numeric,
	TipoCotizacion: string,
	MonedaDestino: numeric,
	Mercado: numeric,
        NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
): [
	
	C4898: string as CodError,
	C1984: numeric as MonedaIngreso,
	C1988: numeric as MonedaDestino,
	C5112: numeric as MontoIngresado,
	C4111: string as TipoCotizacion,
	C320: numeric as Cotizacion,
	C689: numeric as ImpCredIngreso
	
] {

	properties
	{
		("operationNumber", "9958")
	
		}

}