service CONSULTAPAGOTARJETA;
description "Consulta de Pago de Tarjetas";

action:OperationQuery ejecutarOperacion
(

SucursalDeb: numeric,
ProductoDeb: numeric,
CuentaDeb: numeric,
MonedaDeb: numeric,
OperacionDeb: numeric,
OrdinalDeb: numeric,
TarjetaCuenta: string,
TipoProceso: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C4898: string as CodError,
	C1382: numeric as Moneda,
	C4837: string as NombreProdDeb,
	C718: numeric as MontoDebito,
	C4838: string as NombreProdCred,
	C2615: numeric as CuentaDeb,
	C4158: string as NumeroTarjeta,
	C4159: string as CuentaTarjeta,
	C8899: numeric as IdCliente
	
	

] {

	properties
	{
		("operationNumber", "9930")
	
		}

}