service CONSULTACOTIZACIONCC; 
description "Consulta Cotizacion del Dolar"; 

action:	SQLQuery CONSULTACOTIZACION ( 
   
 

	
): [ 

 	
	COTIZACIONBCU: numeric as COTIZACIONBCU
	
	
	
]
{ 
  	properties { 
  	("statement", "SELECT C6440 AS COTIZACIONBCU FROM MONEDAS WHERE C6399=2225 AND (Tz_lock < 310000000000000  OR Tz_lock > 339999999999999)")
	
	
	}
}


