service CONSULTASOLPVTA;
description "Consulta de Solicitudes de Compra en PVTA";

action:OperationQuery ejecutarOperacion
(

NroSolicitud: numeric
        
): [
	
	C121: string as CodError,
	C9208: string as Mensaje,
	C6587: string as Resultado,
	C2611: numeric as NroSolicitud,
	C231: string as MotivoRechazo,
	C934: string as Nombre,
	C4193: numeric as LimiteCredito,
	C254: string as Documento,
	C3962: string as Ciudad,
	C3920: string as Domicilio

] {

	properties
	{
		("operationNumber", "9969")
	
		}

}