service COTIZACION;
description "Cotizacion de Transferencia";

action:OperationQuery ejecutarOperacion
(
        SucursalDeb: numeric,
	ProductoDeb: numeric,     
	NroCuentaDeb:   numeric,      
	MonedaDeb:   numeric ,
	OperacionDeb: numeric,
	OrdinalDeb: numeric,
	SucursalAcr: numeric,
	ProductoAcr: numeric,     
	NroCuentaAcr:   numeric,      
	MonedaAcr:   numeric,
	OperacionAcr: numeric,
	OrdinalAcr: numeric,
	Monto: float,
        MonedaMonto: numeric
): [
	
	C6417: numeric as TipoCambio,
	C4816: numeric as Imp_Cotizado
] {

	properties
	{
		("operationNumber", "9313")
	
		}

}