service CUOTAMAXCC;
description "CUOTA MAXIMA y CAP. ENDEUD PARA CALLCENTER";


action:OperationQuery ejecutarOperacion
(

SOLICITUDCRM: string,
TIPODOC: string,
NRODOC: string,
PAISDOC: numeric

): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR,
	C4192: numeric as CUOTAMAX,
	C672: numeric as CUOTAPA,
	C673: numeric as CUOTATDC,
	C701 : numeric as MONTO
	
	
	

	

] {

	properties
	{
		("operationNumber", "6782")
	
		}

}