service DEPOSITOCAJA;
description "Deposito en Efectivo o Cheque por Caja";

action:OperationQuery ejecutarOperacion
(

TipoOpe: string,
SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
MontoCredito: numeric,
MonedaIngreso: numeric,
MontoIngreso: numeric,
TipoProceso: string,
Cotizacion: numeric,
CantidadCheques: numeric,
NroLote: numeric,
DiasValor: numeric,
NodoCliente: string,
FormaPago: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: string,
IdAutentica: numeric,
IdInvocaTopaz: numeric
        
): [
	C4898: string as CodError,
	C2616: numeric as Numerador,
	C360: string as NombreProdCred,
	C1146: numeric as CuentaAcr
			
	

] 
        { 
        
	properties
	{
		("operationNumber", "9939")
	}	
}
	
