service DEPOSITOCAJAEFECTIVO;
description "Deposito en Efectivo por Caja";

action:OperationQuery ejecutarOperacion
(

SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
MontoCredito: numeric,
MonedaIngreso: numeric,
MontoIngreso: numeric,
TipoProceso: string,
Cotizacion: numeric,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: string,
IdAutentica: numeric
        
): [
	C4898: string as CODERROR,
	C2616: numeric as Numerador,
	C360: string as NombreProdCred
		
	

] {

	properties
	{
		("operationNumber", "9925")
	
		}

}