service DEPOSITOENSOBRADOGASTO;
description "Pago de Cuentas de Tercero Efectivo o Cheque por Buzon";

action:OperationQuery ejecutarOperacion
(

TipoOpe: string,	
SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
OperacionAcr: numeric,
OrdinalAcr: numeric,
MontoCredito: numeric,
MonedaIngreso: numeric,
MontoIngreso: numeric,
DiasValor: numeric,
FormaPago: string,
TipoProceso: string,
Cotizacion: numeric,
NroLote: numeric,
CantidadCheques: numeric,
NroComprobante: numeric,
NroTransaccion: numeric,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
IdAutentica: string,
IdInvocaTopaz: numeric
        
): [
	C4898: string as CodError,
	C669: numeric as Numerador,
	C4838: string as NombreProdCred,
	C720: numeric as MontoCredito,
	C1382: numeric as MonedaAcr
		
	

] {

	properties
	{
		("operationNumber", "9946")
	
		}

}