service EXCHANGUERATEINQUIRY.; 
description "Consulta las Cotizaciones de todas las Monedas"; 

action:	SQLQuery CONSULTACOTIZACIONES ( 
	
	
): [ 
 	
 	SERRORCODE: string, 
	MONEDA: numeric as Moneda,
	MONEDADESCRIPCION: string as MonedaDescripcion,
	TIPOCAMBIOCOMPRA: numeric as TipoCambioCompra,
	TIPOCAMBIOVENTA: numeric as TipoCambioVenta
	
	
]
{ 
  	properties { 
  	("statement", "SELECT 0 AS SERRORCODE,C6399 AS Moneda,C6400 AS MonedaDescripcion,TCCOMPRACOMUN AS TipoCambioCompra,TCVENTACOMUN AS TipoCambioVenta FROM MONEDAS")
	
	
	}
}


