service FINOUTBOUNDCC;
description "Aprobacion/Rechazo Solicitudes";

action:OperationQuery ejecutarOperacion
(

SOLICITUDCRM: string,
PRODUCTOP: numeric,
PRODUCTOT: numeric,
ESTADOP: string,
ESTADOT: string



): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR

] {

	properties
	{
		("operationNumber", "6796")
	
		}

}