service INGRESARADICIONAL;
description "INGRESAR ADICIONAL PARA TARJETA DE CREDITO";

 action:OperationQuery ejecutarOperacion(
	   
	SOLICITUDCRM: string,
	CUENTATDC: numeric,      
	PAISDOC: numeric,
	TIPODOC: string,
	NRODOC: string,
      	PRIMERAPELLIDO: string,	
	PRIMERNOMBRE: string,
	PAISNAC: numeric,
	SEXO: string,
	ESTADOCIVIL: string,
	PAISRES: numeric,
	DEPTO: string,
	CODIGOPOSTAL: numeric,
	CIUDAD: string,
	CALLE: string,
	NROPUERTA: string,
	FECHANAC: string,
	FECHAVTO: string,
	SEGUNDOAPELLIDO: string,
	SEGUNDONOMBRE: string,
	NACIONALIDAD: string,
	APTO: string,
	PISO: numeric,
	TIPOVIVIENDA: string,
	TELFIJO: string,
	TELCELU: string

	): [
	
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR

     ] {

	properties
	{
		("operationNumber", "6788")
	
		}

}