service INGRESARVENTACC;
description "INGRESAR VENTA PARA CALLCENTER";

 action:OperationQuery ejecutarOperacion(
	   
	SOLICITUDCRM: string,
	SUCURSAL: numeric,      
	PAISDOC: numeric,
	TIPODOC: string,
	NRODOC: string,
      	PRIMERAPELLIDO: string,	
	PRIMERNOMBRE: string,
	PAISNAC: numeric,
	SEXO: string,
	ESTADOCIVIL: string,
	PAISRES: numeric,
	DEPTO: string,
	CODIGOPOSTAL: numeric,
	CIUDAD: string,
	CALLE: string,
	NROPUERTA: string,
	FECHANAC: string,
	FECHAVTO: string,
	SEGUNDOAPELLIDO: string,
	SEGUNDONOMBRE: string,
	NACIONALIDAD: string,
	APTO: string,
	PISO: numeric,
	TIPOVIVIENDA: string,
	TELFIJO: string,
	TELCELU: string,
	PRODPRESTAMO: numeric,
	IMPPRESTAMO: numeric,
	MONPRESTAMO: numeric,
	TASAPRESTAMO: numeric,
	PERPRESTAMO: numeric,
	CUOTASPRESTAMO: numeric,
	PRODUCTOTDC: numeric,
	CANAL: numeric,
	PAQUETE: numeric, 
	CAMPANIA: numeric,
	MONEDATDC: numeric,
	LIMITESOLIC: numeric,
	RESPONSABILIDAD: string,
	TIPORESP: string,
	MARCA: string,
	PROGRAMA: numeric,
	COBERTURA: numeric,
	TIPOTARJ: string,
	CICLO: numeric,
	GRUPO: string,
	NOMBREEMB: string,
	CAMPANIAPA: numeric
	
	
	
	): [
	
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR,
	C2616: numeric as NROSOLICITUD
	
	

     ] {

	properties
	{
		("operationNumber", "6785")
	
		}

}
