service INGRESOSOLICITUDPVTA;
description "Ingreso de Solicitudes de Compra en PVTA";

action:OperationQuery ejecutarOperacion
(

IP_ORIGEN: string,
USUARIO: string,
NRO_DEP: numeric,
idAplicacion: numeric,
RUC_EMP_COM: numeric,
CODIGO_PRODUCTO: numeric,
CANT_CUOTAS: numeric,
MONEDA: string,
IMP_SOLIC_MO: float,
COD_DESTINO: string,
PERIODO_PAGO: numeric,
T_SEXO: string,
T_COD_DEPTO: numeric,
T_PROPIETARIO: string,
T_TELEFONO: string,
T_COD_ACTIVIDAD: string,
T_D_ING_NOMINAL: float,
T_D_ADELANTO: float,
T_TEL_EMPLEADOR: string,
T_NRO_DOCUMENTO: string,
T_COD_PAIS: numeric,
T_COD_POSTAL: numeric,
T_D_VIATICOS: float,
T_RUC_EMP: numeric,
T_LOCALIDAD: string,
T_D_EXTRAS: float,
T_LUGAR_TRABAJO: string,
T_NRO_BPS: numeric,
T_EST_PAT_C: string,
T_EST_CIVIL: string,
T_D_COM_COB: float,
T_D_PAR_VAR: float,
T_APE_RAZON2: string,
T_D_PART_EXT: float,
T_APE_RAZON1: string,
T_MONTO: float,
T_NOM_FANTASIA1: string,
T_NOM_FANTASIA2: string,
T_CALLE: string,
T_CONS_DOMICILI: string,
T_FAX: string,
T_FEC_INGRESO: date <"YYYY-MM-DD">,
T_FEC_NACIMIENT: date <"YYYY-MM-DD">,
J_NRO_DOCUMENTO: string,
J_SEXO: string,
J_NOM_FANTASIA1: string,
J_NOM_FANTASIA2: string,
J_APE_RAZON1: string,
J_APE_RAZON2: string,
J_D_VIATICOS: float,
J_D_PAR_EXTR: float,
J_COD_ACTIVIDAD: string,
J_D_ING_NOM: float,
J_D_COM_COB: float,
J_LUGAR_TRABAJO: string,
J_NRO_BPS: numeric,
J_TEL_EMPLEADOR: string,
J_D_PAR_VARI: float,
J_D_EXTRAS: float,
J_MONTO: float,
J_D_ADELANTO: float,
J_RUC_EMP: numeric,
J_FEC_NACIMIENT: date <"YYYY-MM-DD">,
J_FEC_INGRESO: date <"YYYY-MM-DD">,
J_RESPONSABILID: string
        
): [
	
	C121: string as CodError,
	C2611: numeric as NroSolicitud,
        C9208: string as Mensaje
	

] {

	properties
	{
		("operationNumber", "9970")
	
		}

}