service INICIOTRAMITE;
description "Inicio de tramite CRM";

action:OperationQuery ejecutarOperacion
(
	NroIdMov: numeric,
	TipoMov: string,     
	IdCliente:   numeric,      
	Importe:   numeric ,
	Sucursal: numeric,
	Producto: numeric,
	Usuario: string,
	Campania: string,
	Observaciones: string
	
): [
	
	
] {

	properties
	{
		("operationNumber", "9921")
	
		}

}