service MAYORDEUDORCC;
description "Mayor deudor de un cliente";


action:OperationQuery ejecutarOperacion
(

SOLICITUDCRM: string,
CLIENTE: numeric

): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR,
	C2614: numeric as MONEDA,
	C701: numeric as MAYORDEUDOR

] {

	properties
	{
		("operationNumber", "6790")
	
		}

}