service ObtenerNavegaciones;
description "nombre cli";

 action:NavegacionesAction ObtenerNavegaciones(
		listAll: boolean
	): [ 
 	CODIGO_NAVEGACION: numeric, 
	CODIGO_SECCION: numeric,
	DESCRIPCION: string,
	ES_HOME: numeric,
	JSON: string,
	PERMITE: numeric
	]
{ 
  	properties { 

	}
}