service OBTENERCLIENTECC;
description "Datos de persona si es cliente";

action: OperationQuery ejecutarOperacion(

	PAISDOC: numeric,
	TIPODOC: string,
      	NRODOC: string
    
): [

	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR,
	C3793: numeric as NROPERSONA,
	C9104: string as PRIMERNOMBRE ,
	C3982: string as SEGUNDONOMBRE,
	C3983: string as PRIMERAPELLIDO ,
	C3985: string as SEGUNDOAPELLIDO,
	C91: string as FECHANAC,
	C2631: numeric as PAISNAC ,
	C4159: string as NACIONALIDAD,
	C4110: string as SEXO ,
	C4111: string as ESTADOCIVIL ,
	C532 : numeric as PAISRES ,
	C523 : string as CALLE ,
	C348 : string as NROPUERTA ,
	C3144: string as APTO,
        C466 : numeric as PISO,
	C3952: string as CIUDAD ,
	C4981: string as CODIGOPOSTAL ,
	C9148: string as DEPTO ,
	C2970: string as TIPOVIVIENDA,
        C4990: string as TELFIJO,
	C4991: string as TELCELU,
	C92: string as FECHAVTO

	
	
		
	
    ] {

	properties
	{
		("operationNumber", "6794")
	
		}

}