service OUTBOUNDCC;
description "Solicitudes por campañas preaprobadas";

action:OperationQuery ejecutarOperacion
(

SOLICITUDCRM: string,
SUCURSAL: numeric,
NROCLIENTE: numeric,
NROPERSONA: numeric,
CAMPANIAP: numeric,
PRODUCTOP: numeric,
MONEDAP: numeric,
CAPITALP: numeric,
TASAPRESTAMO: numeric,
PERPRESTAMO: numeric,
CUOTASPRESTAMO: numeric,
CAMPANIAT: numeric,
PRODUCTOT: numeric,
MONEDAT: numeric,
CAPITALT: numeric,
CANAL: numeric,
PAQUETE: numeric,
TIPORESP: string,
MARCA: numeric,
PROGRAMA: numeric,
COBERTURA: numeric,
TIPOTARJ: string,
CICLO: numeric,
GRUPO: string,
NOMBREEMB: string,
CANALVENTA: numeric



): [
	C4131: numeric as CODERROR,
	C904 : string  as DESCERROR

] {

	properties
	{
		("operationNumber", "6795")
	
		}

}