service PAGODEFACTURAS;
description "Pago de factura por caja";

action:OperationQuery ejecutarOperacion
(

MontoIngresado: float,
MonedaIngresada: numeric,
NroLote: numeric,
TipoProceso: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: string,
IdAutentica: numeric,
IdInvocaTopaz: numeric

        
): [
	C4898: string as CODERROR
	

] {

	properties
	{
		("operationNumber", "9967")
	
	}

}