service PAGOGASTODEBITO;
description "Pago Gastos con Debito en Cuenta";

action:OperationQuery ejecutarOperacion
(

SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
OperacionAcr: numeric,
OrdinalAcr: numeric,
SucursalDeb: numeric,
ProductoDeb: numeric,
CuentaDeb: numeric,
MonedaDeb: numeric,
OperacionDeb: numeric,
OrdinalDeb: numeric,
MontoDebito: numeric,
MontoCredito: numeric,
MonedaIngresada: numeric,
MontoIngresado: numeric,
Cotizacion: numeric,
TipoProceso: string,
NroComprobante: numeric,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C4898: string as CodError,
	C1382: numeric as Moneda,
	C718: numeric as MontoDebito,
	C4837: string as NombreProdDeb,
	C720: numeric as MontoCredito,
	C4838: string as NombreProdCred,
	C429: numeric as CuentaAcr,
	C2615: numeric as CuentaDeb
	
	
	
	

] {

	properties
	{
		("operationNumber", "9932")
	
		}

}