service PAGOTARJETADEBITO;
description "Pago de Tarjetas con Debito en Cuenta";

action:OperationQuery ejecutarOperacion
(

SucursalDeb: numeric,
ProductoDeb: numeric,
CuentaDeb: numeric,
MonedaDeb: numeric,
OperacionDeb: numeric,
OrdinalDeb: numeric,
MontoCredito: numeric,
MonedaIngresada: numeric,
TipoPago: string,
TarjetaOCuenta: string,
TipoProceso: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C4898: string as CodError,
	C1382: numeric as Moneda,
	C4838: string as NombreProdCred,
	C718: numeric as MontoCredito,
	C721: numeric as MontoDebito,
	C4837: string as NombreProdDeb,
	C2615: numeric as CuentaDeb,
	C4158: string as NumeroTarjeta,
	C4159: string as CuentaTarjeta
	
	

] {

	properties
	{
		("operationNumber", "9931")
	
		}

}