service PAGOPRESTAMOCAJA;
description "Pago de Prestamo Efec/Cheq por Caja";

action:OperationQuery ejecutarOperacion
(

SucursalAcr: numeric,
ProductoAcr: numeric,
CuentaAcr: numeric,
MonedaAcr: numeric,
OperacionAcr: numeric,
OrdinalAcr: numeric,
MontoIngreso: numeric,
MonedaIngreso: numeric,
DiasValor: numeric,
FormaPago: string,
NroCuotas: numeric,
TipoProceso: string,
NroLote: numeric,
CantidadCheques: numeric,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C4898: string as CODERROR,
	C669: numeric as Numerador,
	C4838: string as NombreProdAcr,
	C1382: numeric as MonedaAcr,
	C720: numeric as MontoCredito,
	C682: numeric as Mora,
	C7776: numeric as Cotizacion,
	C718: numeric as MontoResto,
	C429: numeric as CuentaAcr
	
	
	
	

] {

	properties
	{
		("operationNumber", "9934")
	
		}

}