service PAGOTARJETABUZON;
description "Pago de Tarjetas Credito por Buzon en Efectivo/Cheque";

action:OperationQuery ejecutarOperacion
(

MonedaIngresada: numeric,
MontoIngresado: float,
DiasValor: numeric,
TipoPago: string,
TarjetaOCuenta: string,
TipoProceso: string,
TarjetaBanco: string,
TipoDocumento: string,
NroDocumento: string,
NroLote: numeric,
CantidadCheques: numeric,
FormaPago: string,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdAutentica: string,
IdInvocaTopaz: string
        
): [
	C4898: string as CodError,
	C2616: numeric as Numerador,
	C4838: string as NombreProdCred,
	C718: numeric as MontoCredito,
	C4158: string as NumeroTarjeta,
	C4159: string as CuentaTarjeta
	
	

] {

	properties
	{
		("operationNumber", "9962")
	
		}

}