service DesembolsosCredito; 
description "Servicio Desembolsos Creditos"; 

action:	SQLQuery Entity ( 
 NROCUENTA: string
): [ 
	FECHAVENCIMIENTOSOL: string,
	MONTOSOLICITADO: string,
	MONTOAPROVADO: string,
   	FORMADESEMBOLSO: string,
	CUENTAACREDITA: string,
	SUCURSALDESEMBOLSO: string,
	CUENTADEBITA: string
	]
{ 
  	properties { 
  	("statement", "SELECT to_char(sl.FECHA_VENCIMIENTO_SOLICITUD,'dd/mm/yyyy') AS FECHAVENCIMIENTOSOL, TO_CHAR(sl.MONTOSOLICITADO,'9999G999G999G999G999D99') AS MONTOSOLICITADO, TO_CHAR(sl.MONTOAPROBADO,'9999G999G999G999G999D99') AS MONTOAPROVADO, o.DESCRIPCION AS FORMADESEMBOLSO, sl.CUENTA_ACREDITAR_SALDOS AS CUENTAACREDITA, sl.CUENTA_DEBITAR_SALDOS AS CUENTADEBITA, suc.NOMBRESUCURSAL AS SUCURSALDESEMBOLSO FROM CRE_SOLICITUDCREDITO sl LEFT JOIN OPCIONES o ON o.NUMERODECAMPO = 7339 AND o.IDIOMA = 'E' AND o.OPCIONINTERNA = sl.FORMAPAGO LEFT JOIN  SUCURSALES suc ON suc.SUCURSAL = sl.CODIGOSUCURSAL AND suc.TZ_LOCK=0 WHERE sl.C5002 = ? AND sl.TZ_LOCK = 0 "),
	("0", "NROCUENTA")
	}
}