service Movimientos10; 
description "Servicio Movimientos"; 

action:	SQLQuery Entity ( 
	IDSALDO: string
): [ 
   	FECHAPROCESO: string,
	SUCURSAL: string,
	ASIENTO: string, 
	FECHAVALOR: string,
	DEBITOCREDITO: string,
	MONEDA: string,
	CAPITAL: string,
	USUARIO: string,
	HORA: string,
	NROOPERACION: string,
	NOMBREOPERACION: string
	]
{ 
  	properties { 
  	("statement", "SELECT * FROM ( SELECT to_char(m.FECHA_PROCESADO,'DD/MM/YYYY') as FECHAPROCESO,  m.SUCURSAL AS SUCURSAL, m.ASIENTO AS ASIENTO, TO_CHAR(m.FECHA_VALOR,'DD/MM/YYYY') AS FECHAVALOR, m.DEBITO_CREDITO AS DEBITOCREDITO, mo.C6401 AS MONEDA, TO_CHAR(m.MONTO,'9999G999G999G999G999D99') AS CAPITAL, a.INIUSR AS USUARIO,  TO_CHAR(a.HORAFIN,'HH:MM:SS') AS HORA,  a.OPERACION AS NROOPERACION,  m.CONCEPTO AS NOMBREOPERACION  FROM HISTORIA_VISTA m left join ASIENTOS a on a.ASIENTO = m.ASIENTO AND a.SUCURSAL = m.SUCURSAL and a.FECHAPROCESO = m.FECHA_PROCESADO left join OPERACIONES op on op.IDENTIFICACION = a.OPERACION join SALDOS s on s.JTS_OID = m.SALDO_JTS_OID join MONEDAS mo on s.MONEDA = mo.C6399 WHERE m.SALDO_JTS_OID = ? AND (m.EVENTO = 'A' OR (m.EVENTO = 'M' AND m.CODIGO_TRAMITE = 0 AND m.MONTO <> 0))  ORDER BY m.FECHA_PROCESADO desc, m.SALDO_JTS_OID desc ) WHERE ROWNUM < 11 "),
	("0", "IDSALDO")
	}
}