service RetencionesCuentasVistas; 
description "Servicio Retenciones"; 

action:	SQLQuery Entity ( 
	IDSALDO: string 
): [ 
	SUCURSAL: string,
    FECHA: string,
	HORA: string,
   	USUARIO: string,
	ORIGENIMPORTE: string,
   	IMPORTEACTUAL: string,
	FECHAVIGENCIA: string,
   	FECHAVENCIMIENTO: string 
]
{ 
  	properties { 
  	("statement", "SELECT r.SUCURSAL_ALTA || ' - ' || s.NOMBRESUCURSAL as SUCURSAL, TO_CHAR(r.FECHA_ALTA,'DD/MM/YYYY') as FECHA , r.HORA_ALTA as HORA , r.USUARIO_ALTA as USUARIO , TO_CHAR(r.IMPORTE_ORIGEN,'9999G999G999G999G999D99') as ORIGENIMPORTE , TO_CHAR(r.IMPORTE_DISPONIBLE,'9999G999G999G999G999D99') as IMPORTEACTUAL , TO_CHAR(r.FECHA_VIGENCIA,'DD/MM/YYYY') as FECHAVIGENCIA , TO_CHAR(r.FECHA_VENCIMIENTO,'DD/MM/YYYY') as FECHAVENCIMIENTO FROM VTA_RESERVAS r JOIN SUCURSALES s ON s.SUCURSAL = r.SUCURSAL_ALTA AND s.TZ_LOCK=0 WHERE r.SALDO_JTS_OID = ? AND r.ESTADO = 1 "),
	("0", "IDSALDO")
	}
}




