service RenovacionesDPF; 
description "Servicio Renovaciones DPF"; 

action:	SQLQuery Entity ( 
 CUENTA: string
): [ 
		FECHAINICIAL: string,
		FECHAVENCIMIENTO: string,
		CAPITALRENOVACION: string, 
		INTERESRENOVACION: string
	]
{ 
  	properties { 
  	("statement", "SELECT TO_CHAR(FECHA_INICIAL,'DD/MM/YYYY') as FECHAINICIAL, TO_CHAR(FECHA_VENCIMIENTO,'DD/MM/YYYY') as FECHAVENCIMIENTO, TO_CHAR(CAPITAL_RENOVACION,'9999G999G999G999G999D99') as CAPITALRENOVACION, TO_CHAR(INTERES_RENOVACION,'9999G999G999G999G999D99') as INTERESRENOVACION FROM DPF_RENOVACIONES WHERE CUENTA = ? "),
	("0", "CUENTA")
	}
}

