service PlanPagosDPF; 
description "Servicio Plan de Pagos DPF"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
   	NROCUOTA: string,
	CAPITAL: string,
	INTERES: string, 
	TOTAL: string,
	FECHAPAGO: string,
	PENDIENTECAPITAL: string,
	PENDIENTEINTERES: string,
	ESTADOCUOTA: string
	]
{ 
  	properties { 
  	("statement", "SELECT C2300 AS NROCUOTA, TO_CHAR(C2304,'9999G999G999G999G999D99') AS CAPITAL, TO_CHAR(C2305,'9999G999G999G999G999D99') AS INTERES,TO_CHAR((C2304+C2305),'9999G999G999G999G999D99') AS TOTAL, to_char(C2302, 'dd/mm/yyyy') AS FECHAPAGO, TO_CHAR(C2309,'9999G999G999G999G999D99') AS PENDIENTECAPITAL, TO_CHAR(C2310,'9999G999G999G999G999D99') AS PENDIENTEINTERES, CASE WHEN (C2309+C2310)>0 THEN 'PENDIENTE' WHEN (C2309+C2310)=0 THEN 'CUOTA PAGA' END AS ESTADOCUOTA FROM PLANPAGOS WHERE SALDO_JTS_OID = ? AND TZ_LOCK=0 "),
	("0", "IDSALDO")
	}
}




