service DatosPersonaJuridica; 
description "Servicio Datos Persona"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string
): [ 
   	RAZONSOCIAL: string,
	DENOMINACION: string,
   	FECHAINICIO: string,
   	TIPOEMPRESA: string,
	ACTIVIDAD: string,
	NUMERODOC: string
]
{ 
  	properties { 
  	("statement", "SELECT d.NUMERODOCUMENTO AS NUMERODOC, c.RAZONSOCIAL AS RAZONSOCIAL, c.NOMBREFANTASIA AS DENOMINACION,  to_char(c.FECHA_INICIO_ACT,'DD/MM/YYYY') AS FECHAINICIO, t.DESCRIPCION AS TIPOEMPRESA, act.DESCRIPCION AS ACTIVIDAD  FROM CLI_PERSONASJURIDICAS c  JOIN CLI_DOCUMENTOSPFPJ d ON d.NUMEROPERSONAFJ = c.NUMEROPERSONAJURIDICA AND d.TZ_LOCK NOT BETWEEN 300000000000000 AND 399999999999999 LEFT JOIN CLI_COD_ACT_CIIU act ON act.CODACTCIIU = c.CODIGOCIIU AND act.TZ_LOCK = 0 JOIN CLI_TIPO_PERSONA_JUR t ON t.CODIGOTIPO = c.TIPOEMPRESA AND t.TZ_LOCK = 0 WHERE d.NUMERODOCUMENTO = ? AND d.TIPODOCUMENTO = ? AND c.TZ_LOCK NOT BETWEEN 300000000000000 AND 399999999999999 "),
	("0", "NRODOC"),
	("1", "TIPODOC")
	}
}
