service IntegrantesPersonaJuridica; 
description "Servicio Integrantes"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string
): [ 
 	TIPODOC: string,
   	NRODOC: string,
	NOMBRE: string,
   	CARGO: string
]
{ 
  	properties { 
  	("statement", "SELECT o.DESCRIPCION AS TIPODOC, r2.NUMERODOCUMENTO AS NRODOC, pf.APELLIDOPATERNO || ' ' || pf.APELLIDOMATERNO  || '' || pf.PRIMERNOMBRE || ' ' || pf.SEGUNDONOMBRE AS NOMBRE, car.CARGO AS CARGO FROM CLI_INTEGRANTESPJ pjf JOIN CLI_DOCUMENTOSPFPJ r ON r.NUMEROPERSONAFJ = pjf.NUMEROPERSONAJURIDICA AND r.TZ_LOCK = 0 JOIN CLI_PERSONASFISICAS pf ON pf.NUMEROPERSONAFISICA = pjf.NUMEROPERSONAFISICA AND pf.TZ_LOCK = 0 JOIN CLI_DOCUMENTOSPFPJ r2 ON r2.NUMEROPERSONAFJ = pf.NUMEROPERSONAFISICA AND r2.TZ_LOCK = 0 JOIN OPCIONES o ON o.NUMERODECAMPO = 751 AND o.OPCIONINTERNA = r2.TIPODOCUMENTO AND o.IDIOMA = 'E' LEFT JOIN CLI_CARGOS_PERSONAS car  ON car.CODIGO = pjf.CODIGOCARGO WHERE r.NUMERODOCUMENTO = ? AND r.TIPODOCUMENTO = ? AND pjf.TZ_LOCK = 0 "),
	("0", "NRODOC"),
	("1", "TIPODOC")
	}
}




