service ClienteDatos; 
description "Servicio Cliente Datos"; 

action:	SQLQuery Entity ( 
 IDCLIENTE: string
): [ 
   	IDCLIENTE: string,
	NOMBRE: string,
	RESIDENCIA: string,
   	FECHAAPERTURA: string,
   	ESTADO: string,
	ACTCIIU: string,
	ACTSBS: string
]
{ 
  	properties { 
  	("statement", "SELECT c.CODIGOCLIENTE AS IDCLIENTE, c.NOMBRECLIENTE AS NOMBRE, o.DESCRIPCION AS RESIDENCIA, TO_CHAR(c.FECHAAPERTURA,'DD/MM/YYYY') AS FECHAAPERTURA, o2.DESCRIPCION AS ESTADO, ciiu.DESCRIPCION AS ACTCIIU, act.DESCRIPCION AS ACTSBS FROM CLI_CLIENTES c left join OPCIONES o2 on o2.NUMERODECAMPO = 1038 AND o2.OPCIONINTERNA = c.ESTADO left join OPCIONES o on o.NUMERODECAMPO = 1030 AND o.OPCIONINTERNA = c.CODIGORESIDENCIA left join CLI_COD_ACT_CIIU ciiu on ciiu.CODACTCIIU = c.CODACTIVIDACIIU left join CLI_COD_ACT_BC act on act.CODIGOACT = c.CODACTIVIDADBANCOCENTRAL WHERE  c.CODIGOCLIENTE = ? "),
	("0", "IDCLIENTE")
	}
}


