service HomeValidacion; 
description "Servicio Valida Home"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string
): [ 
   	VALIDA: string,
	TEXTO: string	
]
{ 
  	properties { 
  	("statement", "SELECT 1 AS VALIDA, 'Parametros invalidos' AS TEXTO from dual ")
	}
}




