service PruebaGetForm;
description "Obtener formulario de asiento.";

action:GetForm Entity
(
   FORM          : numeric             ,
   FECHAPROCESO  : date <"DD/MM/YYYY"> ,
   ASIENTO       : numeric             ,
   JTSOID        : numeric             ,
   TRANSACTIONS  : string              ,
   SUCURSAL      : numeric                     
): [	
	reportFileName: string as ReportFileName
] {
	properties
	{
        ("form"         , "FORM"         ),
        ("processDate"  , "FECHAPROCESO" ),
        ("posting"      , "ASIENTO"      ),
        ("jtsOid"       , "JTSOID"       ),
        ("transactions" , "TRANSACTIONS" ),
        ("branch"       , "SUCURSAL"     )
	}
}