service DatosJuridica; 
description "Servicio Datos Persona"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string
): [ 
   	RAZONSOCIAL: string,
	DENOMINACION: string,
	NUMERODOC: string,
   	FECHAINICIO: string,
   	TIPOEMPRESA: string,
	ACTIVIDAD: string
]
{ 
  	properties { 
  	("statement", "SELECT r.NUMERODOCUMENTO AS NUMERODOC, a.RAZONSOCIAL AS RAZONSOCIAL, a.NOMBREFANTASIA AS DENOMINACION, to_char(a.FECHACONSTITUCION,'DD/MM/YYYY') AS FECHAINICIO, n.DESCRIPCION AS TIPOEMPRESA, act.DESCRIPCION AS ACTIVIDAD FROM CLI_PERSONASJURIDICAS a JOIN CLI_DOCUMENTOSPFPJ r ON r.NUMEROPERSONAFJ = a.NUMEROPERSONAJURIDICA AND r.TZ_LOCK = 0 JOIN CLI_CLIENTEPERSONA cli ON cli.NUMEROPERSONA = a.NUMEROPERSONAJURIDICA JOIN CLI_CLIENTES c ON c.CODIGOCLIENTE = cli.CODIGOCLIENTE AND c.TZ_LOCK = 0 LEFT JOIN CLI_COD_ACT_CIIU act ON act.CODACTCIIU = c.CODACTIVIDACIIU  AND act.tz_lock=0 JOIN CLI_TIPO_PERSONA_JUR n ON n.CODIGOTIPO = a.TIPOEMPRESA AND n.TZ_LOCK=0 WHERE r.NUMERODOCUMENTO = ?  AND r.TIPODOCUMENTO = ?  AND a.TZ_LOCK = 0 "),
	("0", "NRODOC"),
	("1", "TIPODOC")
	}
}