service PERSONADEUNCLIENTEXCLI;
description "Consulta de Personas asocidas a un Clientes";

action:OperationQuery ejecutarOperacion
(

	IdCliente: numeric
	

        
): [
	C4898: string as CODERROR,
	C3793: numeric as IdPersona,
	C1051: string as Pais,
	C9097: string as SwiftPais,
	C938 : string as TipoPersona,
	C745 : string as TipoDocumento,
	C746 : string as NroDocumento,
	C4837: string as NombrePersona,
	C4838: string as ApellidoPersona,
	C410 : string as Empresa,
	C5507: string as RolPersona
	

] {

	properties
	{
		("operationNumber", "9949"),
		("transaction", "5")
	
		}

}