service RETIROPORCOLA;
description "Retiro por Cola";

action:OperationQuery ejecutarOperacion
(
	
SucursalDeb: numeric,
ProductoDeb: numeric,
CuentaDeb: numeric,
MonedaDeb: numeric,
MontoDebito: numeric,
MonedaIngreso: numeric,
MontoIngreso: numeric,
TipoProceso: string,
Cotizacion: numeric,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: numeric,
IdInvocaTopaz: numeric
        
): [
	C4898: string as CodError,
	C2616: numeric as Numerador,
	C360: string as NombreProdDeb,
	C1146: numeric as CuentaDeb
		
	

] {

	properties
	{
		("operationNumber", "9924")
	
		}

}