service SIMULACIONDPF;
description "Simulacion deposito plazo fijo";

action:OperationQuery ejecutarOperacion
(

Cliente: numeric,
Producto: numeric,
Moneda: numeric,
Capital: numeric,
Plazo: numeric,
Periodo: string

        
): [
	C3990: numeric as CODERROR, 
	C1627: date as Vencimiento,
	C1632: numeric as TasaInteres,
	C1632: numeric as TasaPizarra,
	C1608: numeric as InteresVto,
	C29: numeric as Capital
	

] {

	properties
	{
		("operationNumber", "9920")
	
		}

}