service SIMULADORCREDITOS;
description "Simulador de Creditos";

action:OperationQuery ejecutarOperacion
(

Producto: numeric,
Cliente: numeric,
Moneda: numeric,
Importe: float,
ModoCuota: string,
CantidadCuotas: numeric,
Periodo: numeric,
TipoCuota: string,
VtoCuotaCuota: string,
FechaVto: date<"DD/MM/YYYY">,
NodoCliente: string,
TicketSesion: numeric,
InfoOrigen: string,
ModoAutentica: string,
CodCanal: string,
Origen: string,
NroDepOrigen: numeric,
NroTransaccion: string,
IdAutentica: numeric,
IdInvocaTopaz: numeric
        
): [
	C4898: string as CODERROR,
	C479: date as FechaProxVto,
	C480: date as FechaVto,
	C78: float as TasaInteres,
	C4111: string as TipoTasa,
	C9308: numeric as TotalCuotas,
	C4112: string as DiasCalculo,
	C2631: numeric as Plazo,
	C369: string as DetallePlanPago
			
	

] 
        { 
        
	properties
	{
		("operationNumber", "9957")
	}	
}
	
