service SRV_LISTADO_PAISES; 
description "Lista los paises en la Base";
    	                
    action: SQLCall LISTA_PAISES() : [lista_paises : string]
	{ 	
	  	properties 
		{ 
					("statement", "{call SP_LISTA_DE_PAISES ( ? )}"),
					("0", "out lista_paises : string") 
	    }
	}

