service TESTSPOR3; 
description "Test de ejecucion de stored proc"; 

action:	SQLCall TESTSPOR3 (p1 : string): [ 
 	p2 : string
]
{ 
  	properties { 
  	("statement", "{call TESTSP3 (?, ?)}"),
	("0", "out p2 : string"),
	("1", "p1")
	}
}