service TRANSFERENCIAS;
description "Transferencia entre Cuentas Vistas";

action:OperationQuery ejecutarOperacion
(
        SucursalDeb: numeric,
	ProductoDeb: numeric,     
	NroCuentaDeb:   numeric,      
	MonedaDeb:   numeric ,
	OperacionDeb: numeric,
	OrdinalDeb: numeric,
	SucursalAcr: numeric,
	ProductoAcr: numeric,     
	NroCuentaAcr:   numeric,      
	MonedaAcr:   numeric,
	OperacionAcr: numeric,
	OrdinalAcr: numeric,
	Monto: float,
        MonedaMonto: numeric
): [
	C3990: int as Estado,
	C5110: float as MontoDeb,
	C3888: string as NombreDeb,
	C5111: float as MontoCred,
	C3889: string as NombreCred
	
] {

	properties
	{
		("operationNumber", "9315")
	
		}

}

