service VISUALIZARPERSONA; 
description "Parámetros de SALIDA al servicio VisualizarPersona"; 

action:	OperationQuery VisualizoPersona ( 
	IdPersona: numeric,
	NodoCliente: string,
	TicketSesion: numeric,
	InfoOrigen: string,
	ModoAutentica: string,
	CodCanal: string,
	Origen: string,
	NroDepOrigen: numeric,
	NroTransaccion: numeric,
	IdAutentica: string,
	TipoProceso: string,
	IdInvocaTopaz: string
): [	
   	C4898: string as CODERROR,
   	C4162: numeric as IdPersona,
   	C1200: date as FechaNacimiento,
	C3458:string as EstadoCivil,
	C7729: string as Sexo,
	C3381: string as ApellidoPaterno,
	C3882: string as ApellidoMaterno,
	C3883: string as PrimerNombre,
   	C3884: string as SegundoNombre,
   	C535 : numeric as PaisNacimiento,
   	C4291: string as Email,
   	C556: string as TipoVivienda,
	C536: numeric as CIIU,
	C650: string as TipoPersona, 
	C745: string as TipoDocumento1, 
	C746: string as NroDocumento1, 
	C6494: numeric as PaisDocumento1, 
	C950: string as SwiftPaisDoc, 
	C4180: date as FechaPresenta, 
	C4181: date as FechaVto, 
	C3913: string as EmpresaTrabaja,
    	C3914: string as DirEmpresa,
    	C3915: string as Cargo,
    	C4903: date as FechaIngreso,
    	C702: float as Salario,
    	C410: string as RazonSocial,
    	C3886: string as Telefono,
    	C3888: string as TelefonoCelular,
    	C3889: string as TelefonoFax,
    	C3887: string as TelPreferido,
    	C118: string as NombreFantasia,
    	C4165:numeric as Cliente,
    	C7293: string as EjecutivoCli,
    	C3100:numeric as SegmentoCli,
    	C3810: string as GrupoVencidos,
    	C2611: numeric as IdPersona,
    	C4821: string as TipoDomicilio,
	C3936: string as Calle,
	C339: string as NumeroPuerta,
	C345: string as Apartamento,
	C2373: numeric as Piso,
	C2237: numeric as Pais,
	C3921: string as Ciudad,
	C2617: numeric as Departamento,
	C532: numeric as BarrioZona,
	C1064: string as TipoDocumento2,
	C3875: string as NroDocumento2,
	C647: string as TipoDocumento3,
	C3878: string as NroDocumento3,
	C2488: numeric as PaisDocumento2,
	C549: numeric as PaisDocumento3

] {

	properties
	{
		("operationNumber", "9950")
	
		}

}