service ITF_Fallecidos;
description "Este servicio se utiliza para dar de alta los fallecidos y bloquear cuentas,etc";
	action: Operation ejecutarOperacion
					(
						CODCLIENTE:        numeric,
						NROPERSONA:        numeric,
						TIPOREL:           string,
						FECHA_FALLECIDO:   date,
						CUIL:              numeric

					):
					[
                        C269: string  as STATUS						
					]
				{ 
					properties {("operation", "83")}
                        
                    
				}
