service AyudaNroDocJF; 
description "Ayuda de NroDoc JF"; 

action:	SQLQuery Entity ( 
 TIPODOC: string,
 CODPAIS: numeric,
 TIENEFILTRO: string,
 CAMPO: string,
 OPERADOR: string,
 VALOR: string
): [
   	STIENEFILTRO: string,
	SCAMPO: string,
	SOPERADOR: string,
	SVALOR: string
	]
{ 
	properties {
  	("statement", "select ? as STIENEFILTRO, ? as SCAMPO, ? as SOPERADOR, ? as SVALOR, (SELECT TIPOPERSONA FROM CLI_TIPOSDOCUMENTOS WHERE TIPODOCUMENTO=? AND TZ_LOCK NOT LIKE '3%' AND TIPOPERSONA<>'I' ) as STIPOPERSONA, ? as STIPODOC, ? as SCODPAIS "), 
	("0", "TIENEFILTRO"), ("1", "CAMPO"), ("2", "OPERADOR"), ("3", "VALOR"), ("4", "TIPODOC"), ("5", "TIPODOC"), ("6", "CODPAIS")};
	
	
	action:	SQLQuery Entity0 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"0\") && (STIPOPERSONA == \"F\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO = ?"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
	action:	SQLQuery Entity1 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"0\") && (STIPOPERSONA == \"J\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO = ?"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
	action:	SQLQuery Entity2 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"1\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA AND relPer.TZ_LOCK NOT LIKE '3%'  WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO LIKE  ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
	action:	SQLQuery Entity3 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"1\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO LIKE  ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity4 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"2\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO LIKE '%' + ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity5 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"2\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO LIKE '%' + ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity6 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"3\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO NOT LIKE '%' + ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity7 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"3\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO NOT LIKE '%' + ? + '%'"),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity8 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"4\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO = ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity9 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"4\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO = ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };		
		action:	SQLQuery Entity10 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"5\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO <> ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity11 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"5\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO <> ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };				
		action:	SQLQuery Entity12 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"6\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO > ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity13 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"6\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO > ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };	
		action:	SQLQuery Entity14 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"7\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO >= ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity15 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"7\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO >= ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity16 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"8\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO < ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity17 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"8\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO < ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity18 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"F\") && (SOPERADOR == \"9\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, (RTRIM(pF.PRIMERNOMBRE) + ' ' + RTRIM(pF.SEGUNDONOMBRE) + ' ' + RTRIM(pF.APELLIDOPATERNO) + ' ' + RTRIM(pF.APELLIDOMATERNO)) NOMBRE FROM CLI_PERSONASFISICAS pF JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pF.NUMEROPERSONAFISICA WHERE pF.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO <= ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    };
		action:	SQLQuery Entity19 ( 
		): [ CODPAIS: string, TIPODOC: string, NRODOC: string, NOMBRE: string ]
		{
		condition {" (STIENEFILTRO == \"1\") && (STIPOPERSONA == \"J\") && (SOPERADOR == \"9\") "};
		properties {
		("statement", "SELECT relPer.PAISDOCUMENTO AS CODPAIS, relPer.TIPODOCUMENTO AS TIPODOC, relPer.NUMERODOCUMENTO AS NRODOC, pJ.RAZONSOCIAL AS NOMBRE FROM CLI_PERSONASJURIDICAS pJ JOIN CLI_DOCUMENTOSPFPJ relPer ON relPer.NUMEROPERSONAFJ = pJ.NUMEROPERSONAJURIDICA WHERE pJ.TZ_LOCK NOT LIKE '3%' AND relPer.TZ_LOCK NOT LIKE '3%' AND relPer.PAISDOCUMENTO = ? AND relPer.TIPODOCUMENTO = ? AND  relPer.NUMERODOCUMENTO <= ? "),
		("0", "SCODPAIS"),
		("1", "STIPODOC"),
		("2", "SVALOR")
	    }
	    }				
}
