service OperacionesPendientesDeCobro; 
description "Servicio OperacionesPendientesDeCobro"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
   	PRODUCTO: string,
   	FECHA_MOVIMIENTO: string,
   	DESCRIPCION_MOVIMIENTO: string,
	IMPORTE_ORIGINAL: string,
	MONEDA: string,
	FECHA_ALTA_COBRO: string,
	FECHA_CADUCIDAD_COBRO: string

]
{ 
  	properties { 
  	("statement", "SELECT CC.DESCRIPCION AS PRODUCTO, CONVERT(VARCHAR(10),CS.FECHA_PROCESO,103) AS FECHA_MOVIMIENTO,CS.CONCEPTO AS DESCRIPCION_MOVIMIENTO, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(CS.IMPORTE AS MONEY),1) , '.','p') , ',', '.'),'p',',')   AS IMPORTE_ORIGINAL, m.C6401 AS MONEDA, CONVERT(VARCHAR(10),CS.FECHA_A_COBRAR,103) AS FECHA_ALTA_COBRO, CONVERT(VARCHAR(10),CS.FECHA_CADUCIDAD_COBRO,103) AS FECHA_CADUCIDAD_COBRO FROM CI_SOLICITUD CS JOIN MONEDAS m ON CS.MONEDA=m.C6399 AND m.TZ_LOCK NOT LIKE '3%' JOIN CI_CARGOS CC ON CS.ID_CARGO = CC.ID_CARGO WHERE CS.ESTADO IN (0,3) AND cs.SALDO_JTS_OID=? AND CS.TZ_LOCK NOT LIKE '3%' AND CC.TZ_LOCK NOT LIKE '3%'"),
	("0", "IDSALDO")
	}
}




