service BloqueosCuenta; 
description "Servicio BloqueosCuenta"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
   	CODIGO: numeric,
   	DESCRIPCION: string,
   	FECHA_ALTA: string,
	FECHA_VENCIMIENTO: string,
	USUARIO: string,
	MENSAJE: string
]
{ 
  	properties { 
  	("statement", "SELECT B.COD_BLOQUEO AS CODIGO, CB.DESCRIPCION , CONVERT(VARCHAR(10),B.FECHA_GRABADA,103) AS FECHA_ALTA, CONVERT(VARCHAR(10),B.FECHA_VENCIMIENTO,103) AS FECHA_VENCIMIENTO, B.USUARIO_INGRESO AS USUARIO, B.DESCRIPCION AS MENSAJE FROM GRL_BLOQUEOS B JOIN GRL_COD_BLOQUEOS CB ON CB.COD_BLOQUEO=B.COD_BLOQUEO  WHERE B.TZ_LOCK NOT LIKE '3%' AND CB.TZ_LOCK NOT LIKE '3%' AND ( (B.FECHA_VENCIMIENTO>=(SELECT FECHAPROCESO FROM PARAMETROS) AND B.MANEJA_VENCIMIENTO=1) OR B.MANEJA_VENCIMIENTO=0) AND B.ESTADO=1 AND B.SALDO_JTS_OID=? ORDER BY B.COD_BLOQUEO ASC"),
	("0", "IDSALDO")
	}
}




