service SubsidiosPrestamo; 
description "Servicio SubsidiosPrestamo"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
	CODIGO: numeric,
	DESCRIPCION: string,
   	TIPOSUBSIDIOINTERES: string,
	PTSINTERES: numeric,
	TIPOSUBSIDIOCARGO: string,
	PTSCARGOS: numeric,
	FECHADESDE: string,
	FECHAINACTIVACION: string,
	ESTADO: string
	]
{ 
  	properties { 
  	("statement", "SELECT b.CodigoSubsidio AS CODIGO, b.Descripcion AS DESCRIPCION, o2.DESCRIPCION AS TIPOSUBSIDIOINTERES, b.PuntosInteres AS PTSINTERES, o3.DESCRIPCION AS TIPOSUBSIDIOCARGO, b.PuntosCargos AS PTSCARGOS,  CONVERT(VARCHAR(10),c.FechaDesde,103) AS FECHADESDE, CONVERT(VARCHAR(10),c.FechaInactivacion,103) AS FECHAINACTIVACION, o.DESCRIPCION AS ESTADO FROM CRE_SUBSIDIOS_PRESTAMOS c JOIN SALDOS s ON c.Jts_asistencia=s.JTS_OID AND s.TZ_LOCK NOT LIKE '3%' JOIN CRE_SUBSIDIOS b ON c.CodigoSubsidio=b.CodigoSubsidio AND b.TZ_LOCK NOT LIKE '3%' JOIN OPCIONES o ON o.NUMERODECAMPO=43125 AND o.IDIOMA='E' AND o.OPCIONINTERNA=c.Estado JOIN OPCIONES o2 ON o2.NUMERODECAMPO=44312 AND o2.IDIOMA='E' AND o2.OPCIONINTERNA=b.TipoSubsidioInteres JOIN OPCIONES o3 ON o3.NUMERODECAMPO=44313 AND o3.IDIOMA='E' AND o3.OPCIONINTERNA=b.TipoSubsidioCargo WHERE s.JTS_OID=? ORDER BY b.CodigoSubsidio ASC "),
	("0", "IDSALDO")
	}
}

