service SobregirosCuenta; 
description "Servicio SobregirosCuenta"; 

action:	SQLQuery Entity ( 
 IDSALDO: numeric
): [ 
   	NRO_AUTORIZACION: numeric,
   	FECHA_VENCIMIENTO: string,
   	FECHA_CANCELACION: string,
   	TASA_DE_INTERESES: numeric,
   	TIPO_AUTORIZACION: string,
   	ESTADO: string,
	IMPORTE: numeric,
	SALDO_ACUERDO: numeric
]
{ 
  	properties { 
  	("statement", "SELECT V.NRO_AUTORIZACION, CONVERT(VARCHAR(10),V.FECHA_VENCIMIENTO,103) AS FECHA_VENCIMIENTO ,CONVERT(VARCHAR(10),V.FECHA_CANCELACION,103) AS FECHA_CANCELACION ,V.TASA_DE_INTERESES,O2.DESCRIPCION AS TIPO_AUTORIZACION,O.DESCRIPCION AS ESTADO,V.IMPORTE AS IMPORTE,V.SALDO_ACUERDO AS ACUERDO FROM VTA_SOBREGIROS V JOIN OPCIONES O ON O.NUMERODECAMPO=1583 AND O.IDIOMA='E' AND O.OPCIONINTERNA=V.ESTADO JOIN OPCIONES O2 ON O2.NUMERODECAMPO=1512 AND O2.IDIOMA='E' AND O2.OPCIONINTERNA=V.TIPO_AUTORIZACION WHERE V.TZ_LOCK NOT LIKE '3%'  AND V.JTS_OID_SALDO=? ORDER BY V.FECHA_ALTA"),
	("0", "IDSALDO")
	}
}




