service ListaCreditos; 
description "Servicio Lista Creditos"; 

action:	SQLQuery Entity ( 
 IDCLIENTE: string,
 IDMONEDA: string
): [ 
   	PRODUCTO: string,
	NROCUENTA: string,
	MONEDA: string,
	SALDOACTUAL: string,
	ASESOR: string,
	FECHADESEMBOLSO: string,
	FECHAVENCIMIENTO: string,
	ULTIMOMOV: string,
	IDSALDO: string
	]
{ 
  	properties { 
  	("statement", "SELECT CONVERT(VARCHAR(10),s.PRODUCTO) +' ' + prd.C6251 AS PRODUCTO, s.CUENTA AS NROCUENTA,  m.C6400 AS MONEDA, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST((-1*s.C1604) AS MONEY),1), '.','p') , ',', '.'),'p',',')  AS SALDOACTUAL, f1.NOMBREOFIC AS ASESOR,  CONVERT(VARCHAR(10),s.c1621,103) AS FECHADESEMBOLSO,    CONVERT(VARCHAR(10),s.C1627, 103) AS FECHAVENCIMIENTO,  CONVERT(VARCHAR(10),s.c1624,103) AS ULTIMOMOV, s.jts_oid as IDSALDO   FROM   SALDOS s JOIN MONEDAS m ON m.C6399 = s.MONEDA JOIN PRODUCTOS prd ON prd.C6250 = s.PRODUCTO LEFT JOIN CLI_OFICUENTA f1 ON CONVERT(VARCHAR(5),s.C1670) = f1.CODOFICIAL AND f1.TZ_LOCK NOT LIKE '3%'  WHERE  s.C1785 = 5 AND s.C1803 = ? AND s.Moneda= ? AND s.TZ_LOCK NOT LIKE '3%'   ORDER BY s.C1621 DESC "),
	("0", "IDCLIENTE"),
	("1", "IDMONEDA")
	}
}


