service RetencionesCuentasVistas; 
description "Servicio Retenciones"; 

action:	SQLQuery Entity ( 
	IDSALDO: string 
): [ 
	SUCURSAL: string,
    FECHA: string,
	HORA: string,
   	USUARIO: string,
	ORIGENIMPORTE: string,
   	IMPORTEACTUAL: string,
	FECHAVIGENCIA: string,
   	FECHAVENCIMIENTO: string 
]
{ 
  	properties { 
  	("statement", "SELECT CONVERT(VARCHAR(5),r.SUCURSAL_ALTA) + ' - '  +  s.NOMBRESUCURSAL as SUCURSAL, CONVERT(VARCHAR(10),r.FECHA_ALTA, 103) as FECHA , r.HORA_ALTA as HORA , r.USUARIO_ALTA as USUARIO , REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(r.IMPORTE_ORIGEN AS MONEY),1) , '.','p') , ',', '.'),'p',',')   as ORIGENIMPORTE , REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(r.IMPORTE_DISPONIBLE AS MONEY),1) , '.','p') , ',', '.'),'p',',')  as IMPORTEACTUAL , CONVERT(VARCHAR(10),r.FECHA_VIGENCIA,103) as FECHAVIGENCIA , CONVERT(VARCHAR(10),r.FECHA_VENCIMIENTO,103) as FECHAVENCIMIENTO FROM VTA_RESERVAS r JOIN SUCURSALES s ON s.SUCURSAL = r.SUCURSAL_ALTA AND s.TZ_LOCK NOT LIKE '3%' WHERE r.SALDO_JTS_OID = ? AND r.ESTADO = 1 "),
	("0", "IDSALDO")
	}
}




