service ChequesCustodia; 
description "Servicio Cheques Custodia para la cuenta"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
   	SERIE: string,
   	NUMEROCHEQUE: numeric,
   	BANCOEMISOR: string,
	SUCURSALEMISOR: string,
	CUENTAEMISOR: numeric,
	MONEDA: string,
	IMPORTE: string,
	FECHAALTA: string,
	FECHA_ACREDITACION: string,
	ESTADO: string
]
{ 
  	properties { 
  	("statement", "SELECT C.SERIE_DEL_CHEQUE AS SERIE, C.NUMERO_CHEQUE AS NUMEROCHEQUE, B.NOMBRE AS BANCOEMISOR, B.NOMBRESUC AS SUCURSALEMISOR, C.NUMERICO_CUENTA_GIRADORA AS CUENTAEMISOR, M.C6401 AS MONEDA, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(C.IMPORTE AS MONEY),1) , '.','p') , ',', '.'),'p',',')  AS IMPORTE, CONVERT(VARCHAR(10),C.FECHA_ALTA,103) AS FECHAALTA, CONVERT(VARCHAR(10),C.FECHA_ACREDITACION,103) AS FECHA_ACREDITACION, O.DESCRIPCION AS ESTADO   FROM CLE_CHEQUES_LISTA_DESCUENTO C  JOIN MONEDAS M ON C.MONEDA=M.C6399 AND M.TZ_LOCK NOT LIKE '3%' JOIN OPCIONES O ON O.NUMERODECAMPO=7134 AND O.IDIOMA='E' AND O.OPCIONINTERNA=C.ESTADO  JOIN CLI_BANCOSPLAZA B ON B.TZ_LOCK NOT LIKE '3%' AND B.CODIGOBC=C.BANCO_GIRADO AND B.SUCURSAL=C.SUCURSAL_BANCO_GIRADO WHERE C.TZ_LOCK NOT LIKE '3%' AND C.VALOR_AL_COBRO='S' AND C.JTS_OID_SALDO=?"),
	("0", "IDSALDO")
	}
}




