service AcuerdosExcesosGarantias; 
description "Servicio AcuerdosExcesosGarantias"; 

action:	SQLQuery Entity ( 
 IDSALDO: numeric
): [ 
   	GARANTIA: numeric,
   	NOMBRESUCURSAL: string,
   	TIPO_GARANTIA: numeric,
   	SUBCLASS_GARANTIA: numeric,
   	DESCRIPCION: string,
	MONEDA: string,
	MONTO: string,
	VENCIMIENTO: string,
	COBERTURA: numeric,
	COBERTURA_POST_ANIO: numeric,
	TIPO_DOC_ORDENANTE: string,
	NRO_DOC_ORDENANTE: string
]
{ 
  	properties { 
  	("statement", "SELECT gc.NUM_GARANTIA AS GARANTIA,s.NOMBRESUCURSAL AS NOMBRESUCURSAL, g.TIPOGARANTIA AS TIPO_GARANTIA,g.COD_SUBCLAGARANTIA AS SUBCLASS_GARANTIA,c.DSC_CLASIFICACION AS DESCRIPCION ,m.C6401 AS MONEDA, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(g.IMPORTE_REAL AS MONEY),1) , '.','p') , ',', '.'),'p',',')   AS MONTO, CONVERT(VARCHAR(10),g.FCHVTO_GARANTIA,103) AS VENCIMIENTO, c.PORCENTAJEAFECTACION AS COBERTURA,c.PORCENTAJEAFECTACION_1_ANIO AS COBERTURA_POST_ANIO,g.TIPODOCUMENTO AS TIPO_DOC_ORDENANTE, g.NUMERODOCUMENTO AS NRO_DOC_ORDENANTE FROM CRE_GARANTIACREDITO gc  JOIN CRE_GARANTIASRECIBIDAS g ON gc.NUM_GARANTIA=g.NUM_GARANTIA AND gc.TZ_LOCK NOT LIKE '3%' JOIN SUCURSALES s  ON  g.SUCURSAL_GARANTIA = s.SUCURSAL AND s.TZ_LOCK NOT LIKE '3%'   JOIN MONEDAS m   ON g.MONEDA_GARANTIA = m.C6399 AND m.TZ_LOCK NOT LIKE '3%'   JOIN CRE_CLASGARANTIAS c  ON g.TIPOGARANTIA = c.TIPOGARANTIA AND c.TZ_LOCK NOT LIKE '3%'   WHERE gc.JTSOID_SALDO=?  ORDER BY gc.NUM_GARANTIA ASC "),
	("0", "IDSALDO")
	}
}




