service AcuerdosExcesos; 
description "Servicio AcuerdosExcesos"; 

action:	SQLQuery Entity ( 
 IDSALDO: numeric
): [ 
   	NRO_AUTORIZACION: numeric,
   	TIPO_AUTORIZACION: string,
   	FECHA_VENCIMIENTO: string,
   	FECHA_BAJA: string,
   	TASA_INTERES: numeric,
	IMPORTE: numeric,
	SALDO_ACUERDO: numeric,
	ESTADO: string
]
{ 
  	properties { 
  	("statement", "SELECT V.NRO_AUTORIZACION ,O.DESCRIPCION AS TIPO_AUTORIZACION,CONVERT(VARCHAR(10),V.FECHA_VENCIMIENTO,103) AS FECHA_VENCIMIENTO,CONVERT(VARCHAR(10),V.FECHA_CANCELACION,103) AS FECHA_BAJA,V.TASA_DE_INTERESES AS TASA_INTERES,V.IMPORTE AS IMPORTE,V.SALDO_ACUERDO AS SALDO_ACUERDO,O2.DESCRIPCION AS ESTADO  FROM VTA_SOBREGIROS V LEFT JOIN OPCIONES O ON O.NUMERODECAMPO=1512 AND O.IDIOMA='E' AND O.OPCIONINTERNA=V.TIPO_AUTORIZACION LEFT JOIN OPCIONES O2 ON O2.NUMERODECAMPO=1583 AND O2.IDIOMA='E' AND O2.OPCIONINTERNA=V.ESTADO WHERE V.TZ_LOCK NOT LIKE '3%' AND V.JTS_OID_SALDO=? ORDER BY V.NRO_AUTORIZACION ASC"),
	("0", "IDSALDO")
	}
}




