service RenovacionesDPF; 
description "Servicio Renovaciones DPF"; 

action:	SQLQuery Entity ( 
 IDSALDO: string
): [ 
		FECHAINICIAL: string,
		FECHAVENCIMIENTO: string,
		CAPITALRENOVACION: string, 
		INTERESRENOVACION: string
	]
{ 
  	properties { 
  	("statement", "SELECT CONVERT(VARCHAR(10),D.FECHA_INICIAL,103) as FECHAINICIAL, CONVERT(VARCHAR(10),D.FECHA_VENCIMIENTO,103) as FECHAVENCIMIENTO, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(D.CAPITAL_RENOVACION AS MONEY),1) , '.','p') , ',', '.'),'p',',')  as CAPITALRENOVACION, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(D.INTERES_RENOVACION AS MONEY),1) , '.','p') , ',', '.'),'p',',')   as INTERESRENOVACION FROM SALDOS S JOIN DPF_RENOVACIONES D ON S.SUCURSAL=D.SUCURSAL AND S.MONEDA=D.MONEDA AND S.CUENTA=D.CUENTA AND S.PRODUCTO=D.PRODUCTO AND S.ORDINAL=D.ORDINAL AND S.OPERACION=D.OPERACION AND S.C1803=D.CLIENTE WHERE S.TZ_LOCK  NOT LIKE '3%' AND D.TZ_LOCK NOT LIKE '3%' AND  S.JTS_OID= ?"),
	("0", "IDSALDO")
	}
}

