service IntegrantesGrupoEconomico; 
description "Servicio IntegrantesGrupoEconomico"; 

action:	SQLQuery Entity ( 
 IDCLIENTE: string
): [ 
   	CODIGOCLIENTE: numeric,
   	NOMBRECLIENTE: string,
   	TIPODOCUMENTO: string,
	NOMBREPAIS: string,
	NUMERODOCUMENTO: string 
]
{ 
  	properties { 
  	("statement", "SELECT C.CODIGOCLIENTE, C.NOMBRECLIENTE, DP.TIPODOCUMENTO, P.NOMBREPAIS, DP.NUMERODOCUMENTO FROM CLI_CLIENTES C JOIN CLI_GRUPOSECONOMICOSCLIENTE GR ON GR.CODIGOCLIENTE=C.CODIGOCLIENTE LEFT JOIN CLI_ClientePersona CP ON CP.CODIGOCLIENTE=C.CODIGOCLIENTE AND CP.TITULARIDAD='T' AND CP.TZ_LOCK NOT LIKE '3%' LEFT JOIN CLI_DocumentosPFPJ DP ON CP.NUMEROPERSONA=DP.NUMEROPERSONAFJ AND DP.TZ_LOCK NOT LIKE '3%' LEFT JOIN CLI_PAISES P ON DP.PAISDOCUMENTO=P.CODIGOPAIS AND P.TZ_LOCK NOT LIKE '3%' WHERE C.CODIGOCLIENTE!=? AND  CP.TZ_LOCK NOT LIKE '3%' AND C.TZ_LOCK NOT LIKE '3%' AND GR.TZ_LOCK NOT LIKE '3%' AND GR.CODIGOGRUPOECONOMICO IN (SELECT G.CODIGOGRUPOECONOMICO FROM CLI_GRUPOSECONOMICOSCLIENTE G WHERE G.CODIGOCLIENTE=?)"),
	("0", "IDCLIENTE"),
	("1", "IDCLIENTE")
	}
}




