service DatosEmailsPJ; 
description "Servicio Emails Persona Juridica"; 

action:	SQLQuery Entity( 
NRODOC: string,
TIPODOC: string,
CODPAIS: numeric,
TIPOPERSONA: string):
[ DESC_TIPO: string, ORDINAL: numeric, EMAIL: string]	
{
	properties {
	 ("statement", "SELECT (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA = 'E' AND O.NUMERODECAMPO = 33494 AND O.OPCIONINTERNA= a.TIPO) AS DESC_TIPO, A.ORDINAL AS ORDINAL, A.EMAIL AS EMAIL FROM dbo.CLI_EMAILS A JOIN dbo.CLI_DOCUMENTOSPFPJ V ON A.ID=V.NUMEROPERSONAFJ AND ((V.TZ_LOCK < 300000000000000 OR V.TZ_LOCK >= 400000000000000) AND (V.TZ_LOCK < 100000000000000 OR V.TZ_LOCK >= 200000000000000)) JOIN dbo.CLI_PERSONASJURIDICAS PJ ON V.NUMEROPERSONAFJ=PJ.NUMEROPERSONAJURIDICA AND ((PJ.TZ_LOCK < 300000000000000 OR PJ.TZ_LOCK >= 400000000000000) AND (PJ.TZ_LOCK < 100000000000000 OR PJ.TZ_LOCK >= 200000000000000)) WHERE A.FORMATO = 'PJ' AND A.TZ_LOCK NOT LIKE '3%' AND V.TIPODOCUMENTO=? AND V.NUMERODOCUMENTO=? AND V.PAISDOCUMENTO=? ORDER BY A.ORDINAL ASC "),
	 ("0", "TIPODOC"),
	 ("1", "NRODOC"),
	 ("2", "CODPAIS")}
}
