service PaquetesCliente; 
description "Servicio PaquetesCliente"; 

action:	SQLQuery Entity ( 
 IDCLIENTE: string
): [ 
   	COD_PAQUETE: numeric,
   	DESCRIPCION_PAQUETE: string,
   	ESTADOPAQUETE: string
]
{ 
  	properties { 
  	("statement", "SELECT P.COD_PAQUETE, P.DESCRIPCION_PAQUETE, O.DESCRIPCION AS ESTADOPAQUETE FROM CLI_PAQUETES P JOIN OPCIONES O ON O.NUMERODECAMPO=1928 AND O.IDIOMA='E' AND O.OPCIONINTERNA=P.ESTADO JOIN CLI_CLIENTES_PAQUETES CP ON P.COD_PAQUETE=CP.COD_PAQUETE AND CP.TZ_LOCK NOT LIKE '3%' AND CP.COD_CLIENTE=? JOIN CLI_CLIENTES C ON CP.COD_CLIENTE=C.CODIGOCLIENTE AND CP.TZ_LOCK NOT LIKE '3%' WHERE P.TZ_LOCK NOT LIKE '3%'  ORDER BY P.COD_PAQUETE ASC "),
	("0", "IDCLIENTE")
	}
}




