service IntegrantesPersonaJuridica; 
description "Servicio Integrantes"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string,
 CODPAIS: numeric
): [ 
	PAISDOCUMENTO: numeric,
 	TIPODOCUMENTO: string,
   	NRODOC: string,
	TIPOPERSONA: string,
	NOMBRE: string,
   	CARGO: string
]
{ 
  	properties { 
  	("statement", "SELECT r2.PAISDOCUMENTO, r2.TIPODOCUMENTO , r2.NUMERODOCUMENTO AS NRODOC, o.DESCRIPCION AS TIPOPERSONA,  pf.APELLIDOPATERNO + ' ' + pf.APELLIDOMATERNO  + '' + pf.PRIMERNOMBRE + ' ' + pf.SEGUNDONOMBRE AS NOMBRE, car.CARGO AS CARGO FROM CLI_INTEGRANTESPJ pjf JOIN CLI_DOCUMENTOSPFPJ r ON r.NUMEROPERSONAFJ = pjf.NUMEROPERSONAJURIDICA AND r.TZ_LOCK NOT LIKE '3%'  JOIN CLI_PERSONASFISICAS pf ON pf.NUMEROPERSONAFISICA = pjf.NUMEROPERSONAFISICA AND pf.TZ_LOCK NOT LIKE '3%'  JOIN CLI_DOCUMENTOSPFPJ r2 ON r2.NUMEROPERSONAFJ = pf.NUMEROPERSONAFISICA AND r2.TZ_LOCK NOT LIKE '3%'  LEFT JOIN OPCIONES o ON o.NUMERODECAMPO=1861 AND o.IDIOMA='E' AND o.OPCIONINTERNA=r2.TIPOPERSONA LEFT JOIN CLI_CARGOS_PERSONAS car  ON car.CODIGO = pjf.CODIGOCARGO WHERE r.NUMERODOCUMENTO = ? AND r.TIPODOCUMENTO = ? AND r.PAISDOCUMENTO=? AND pjf.TZ_LOCK NOT LIKE '3%'  "),
	("0", "NRODOC"),
	("1", "TIPODOC"),
	("2", "CODPAIS")
	}
}




