service PersonasJuridicasQueIntegra; 
description "Servicio Datos Personas Juridicas"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string,
 CODPAIS: numeric
): [ 
	TIPODOCUMENTO: string,
	NUMERODOCUMENTO: string,
	NOMBREPAIS: string,
	RAZONSOCIAL: string,
	NOMBREFANTASIA: string
]
{ 
  	properties { 
  	("statement", "SELECT DPJ.TIPODOCUMENTO, DPJ.NUMERODOCUMENTO, PA.NOMBREPAIS , PPJ.RAZONSOCIAL AS RAZONSOCIAL, PPJ.NOMBREFANTASIA AS NOMBREFANTASIA FROM (SELECT DP.NUMEROPERSONAFJ FROM CLI_DocumentosPFPJ  DP JOIN  CLI_PERSONASFISICAS PF  ON DP.NUMEROPERSONAFJ=PF.NUMEROPERSONAFISICA AND DP.TZ_LOCK NOT LIKE '3%' AND PF.TZ_LOCK NOT LIKE '3%'  WHERE  DP.NUMERODOCUMENTO= ? AND DP.TIPODOCUMENTO = ? AND DP.PAISDOCUMENTO = ? ) QUERY JOIN CLI_INTEGRANTESPJ PJ ON PJ.NUMEROPERSONAFISICA=QUERY.NUMEROPERSONAFJ AND PJ.TZ_LOCK NOT LIKE '3%' JOIN CLI_PERSONASJURIDICAS PPJ ON PPJ.NUMEROPERSONAJURIDICA=PJ.NUMEROPERSONAJURIDICA AND PPJ.TZ_LOCK NOT LIKE '3%' JOIN CLI_DocumentosPFPJ DPJ ON DPJ.NUMEROPERSONAFJ=PPJ.NUMEROPERSONAJURIDICA AND DPJ.TZ_LOCK NOT LIKE '3%' JOIN CLI_PAISES PA ON DPJ.PAISDOCUMENTO=PA.CODIGOPAIS AND PA.TZ_LOCK NOT LIKE '3%'  "),
	("0", "NRODOC"),
	("1", "TIPODOC"),
	("2", "CODPAIS")
	}
}





