service DatosTelefonosPJ; 
description "Servicio Telefonos Persona Humana"; 

action:	SQLQuery Entity( 
NRODOC: string,
TIPODOC: string,
CODPAIS: numeric,
TIPOPERSONA: string):
[ DESC_TIPO: string, ORDINAL: numeric, TIPO_CEL_TEL: string, NUMERO: string]	
{
	properties {
	 ("statement", "SELECT  QUERY.DESC_TIPO, QUERY.ORDINAL, QUERY.TIPO_CEL_TEL, QUERY.NUMERO  FROM (SELECT (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA = 'E' AND O.NUMERODECAMPO = 33427 AND O.OPCIONINTERNA= A.TIPO) AS DESC_TIPO, A.ORDINAL AS ORDINAL, (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA = 'E' AND O.NUMERODECAMPO = 33435 AND O.OPCIONINTERNA= A.TIPO_CEL_TEL)  AS TIPO_CEL_TEL, A.NUMERO AS NUMERO FROM dbo.CLI_TELEFONOS A JOIN dbo.CLI_DOCUMENTOSPFPJ V ON A.ID=V.NUMEROPERSONAFJ AND ((V.TZ_LOCK < 300000000000000 OR V.TZ_LOCK >= 400000000000000) AND (V.TZ_LOCK < 100000000000000 OR V.TZ_LOCK >= 200000000000000)) JOIN dbo.CLI_PERSONASJURIDICAS PJ ON V.NUMEROPERSONAFJ=PJ.NUMEROPERSONAJURIDICA AND ((PJ.TZ_LOCK < 300000000000000 OR PJ.TZ_LOCK >= 400000000000000) AND (PJ.TZ_LOCK < 100000000000000 OR PJ.TZ_LOCK >= 200000000000000)) WHERE A.FORMATO = 'PJ' AND V.TIPODOCUMENTO= ? AND V.NUMERODOCUMENTO= ? AND V.PAISDOCUMENTO= ? ) QUERY ORDER BY QUERY.ORDINAL "),
	 ("0", "TIPODOC"),
	 ("1", "NRODOC"),
	 ("2", "CODPAIS")}
}
