service ClientesIntegrados; 
description "Servicio Clientes Integrados"; 

action:	SQLQuery Entity ( 
 NRODOC: string,
 TIPODOC: string,
 CODPAIS: numeric
): [ 
 	IDCLIENTE: string,
   	TITULARIDAD: string,
	FECHAALTA: string,
	NATURALEZA: string,
	GRUPOECONOMICO: string
]
{ 
  	properties { 
  	("statement", "SELECT c.CODIGOCLIENTE AS IDCLIENTE, c.TITULARIDAD AS TITULARIDAD, CONVERT(VARCHAR(10),c.FECHAALTARELACION,103) AS FECHAALTA, (SELECT o.descripcion FROM OPCIONES o WHERE o.IDIOMA='E' AND o.NUMERODECAMPO=1036 AND o.OPCIONINTERNA=CLI.CATEGORIA_COMERCIAL) AS NATURALEZA, CASE WHEN G.CODIGOGRUPOECONOMICO IS NULL THEN 'NO TIENE' ELSE (SELECT GE.NOMBRE FROM CLI_GRUPOSECONOMICOS GE WHERE GE.TZ_LOCK NOT LIKE '3%' AND GE.CODIGOGRUPOECONOMICO=G.CODIGOGRUPOECONOMICO) END AS GRUPOECONOMICO FROM CLI_CLIENTES CLI JOIN CLI_CLIENTEPERSONA c ON C.CODIGOCLIENTE=CLI.CODIGOCLIENTE AND CLI.TZ_LOCK NOT LIKE '3%' AND C.TZ_LOCK NOT LIKE '3%' JOIN CLI_DOCUMENTOSPFPJ r ON r.NUMEROPERSONAFJ = c.NUMEROPERSONA AND r.TZ_LOCK NOT LIKE '3%'  LEFT JOIN CLI_GRUPOSECONOMICOSCLIENTE G ON G.CODIGOCLIENTE=CLI.CODIGOCLIENTE AND G.TZ_LOCK NOT LIKE '3%'  WHERE r.NUMERODOCUMENTO = ? AND r.TIPODOCUMENTO = ? AND r.PAISDOCUMENTO= ?"),
	("0", "NRODOC"),
	("1", "TIPODOC"),
	("2", "CODPAIS")
	}
}




