service Movimientos; 
description "Servicio Movimientos"; 

action:	SQLQuery Entity ( 
	IDSALDO: numeric
): [ 
   	FECHAPROCESO: string,
	SUCURSAL: string,
	ASIENTO: string, 
	FECHAVALOR: string,
	DEBITOCREDITO: string,
	MONEDA: string,
	CAPITAL: string,
	USUARIO: string,
	HORA: string,
	NROOPERACION: string,
	NOMBREOPERACION: string
	]
{ 
  	properties { 
  	("statement", "SELECT convert(VARCHAR(10),m.FECHA_PROCESADO,103) as FECHAPROCESO, m.SUCURSAL AS SUCURSAL, m.ASIENTO AS ASIENTO, convert(VARCHAR(10),m.FECHA_VALOR,103) AS FECHAVALOR, m.DEBITO_CREDITO AS DEBITOCREDITO, mo.C6401 AS MONEDA, REPLACE(REPLACE(REPLACE( CONVERT(VARCHAR,CAST(m.MONTO AS MONEY),1) , '.','p') , ',', '.'),'p',',')  AS CAPITAL, a.INIUSR AS USUARIO,  convert(VARCHAR(8),a.HORAFIN,8) AS HORA,  a.OPERACION AS NROOPERACION,  m.CONCEPTO AS NOMBREOPERACION  FROM HISTORIA_VISTA m left join ASIENTOS a on a.ASIENTO = m.ASIENTO AND a.SUCURSAL = m.SUCURSAL and a.FECHAPROCESO = m.FECHA_PROCESADO left join OPERACIONES op on op.IDENTIFICACION = a.OPERACION join SALDOS s on s.JTS_OID = m.SALDO_JTS_OID join MONEDAS mo on s.MONEDA = mo.C6399 WHERE m.SALDO_JTS_OID = ? AND (m.EVENTO = 'A' OR (m.EVENTO = 'M' AND m.CODIGO_TRAMITE = 0 AND m.MONTO <> 0))  ORDER BY m.FECHA_PROCESADO desc, m.SALDO_JTS_OID desc "),
	("0", "IDSALDO")
	}
}