service DatosAsientosMovimientos; 
description "Servicio Datos Asientos"; 

action:	SQLQuery Entity ( 
 ASIENTO: string,
 FECHAPROCESO: string,
 SUCURSAL: string
): [ 
   	FECHAPROCESO: string,
	SUCURSAL: string,
   	ASIENTO: string,
   	OPERACION: string,
	NOMBREOPERACION: string,
	CONCEPTO: string,
	USUARIOINGRESO: string	
]
{ 
  	properties { 
  	("statement", "SELECT  CONVERT(VARCHAR(10),A.FECHAPROCESO,103) as FECHAPROCESO, CONVERT(VARCHAR(5),A.SUCURSAL) + '-' + s.DESCRIPCION AS SUCURSAL ,A.ASIENTO,A.OPERACION, O.NOMBRE as NOMBREOPERACION,A.DESCRIPCION AS CONCEPTO, A.INIUSR AS USUARIOINGRESO FROM ASIENTOS A JOIN SUCURSALESSC s ON s.SUCURSAL = a.SUCURSAL LEFT join OPERACIONES O ON O.IDENTIFICACION=A.OPERACION  WHERE ASIENTO = ? AND CONVERT(VARCHAR(10), A.FECHAPROCESO ,103) = ? AND A.SUCURSAL = ? "),
	("0", "ASIENTO"),
	("1", "FECHAPROCESO"),
	("2", "SUCURSAL")
	
	}
}




