EXECUTE('
---------------------------------
--CORRECCIÓN IMPUESTO POR CARGO--
---------------------------------
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (1, 2200, ''A'', 0, NULL, NULL)
----
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (832, ''COMISION LIQUIDACION CONVENIO S/IVA'', 0)
--
INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (2201, ''COMISION LIQUIDACION CONVENIO CANAL'', ''N'', ''N'', 2, ''N'', 2200, 34354, 1, 300, 700, ''C'', 0, 36, 0, ''N'', 9999, 0, NULL, ''N'', ''C'', ''C'', ''S'', 0, ''F'', ''N'', ''20991231'', ''20000101'', 0, ''N'', 2200, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)
--
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (2201, 832, 0, ''A'', 44806, ''SEGMENTO CONVENIO RECAUDACION'', 1)
----
INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2201, 1, 999999999999, 0.03, 0, 1, 0, 0, ''0'', ''N'', 0, 0, ''19000101'', ''20990101'', 0)
--
INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2201, 1, 999999999999, 0.035, 0, 1, 0, 0, ''P'', ''N'', 0, 0, ''19000101'', ''20990101'', 0)
--
INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2201, 1, 999999999999, 0.05, 0, 1, 0, 0, ''V'', ''N'', 0, 0, ''19000101'', ''20990101'', 0)
----
')


