


-- Parche_NUSICREDBR_2966

-- Insertar parametroJts
INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CANCELACION_DPF', 'CONCEPTO_CONTABLE_TRANSITORIA_DPF', '0', 0);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20230511_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVVNJQ1JFREJSXzI5NjYKDQotLSBJbnNlcnRhciBwYXJhbWV0cm9KdHMN
CklOU0VSVCBJTlRPIFBBUkFNRVRST1NfSlRTIChGVU5DSU9OQUxJREFELCBQQVJBTUVUUk8sIFZB
TE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdDQU5DRUxBQ0lPTl9EUEYnLCAnQ09OQ0VQVE9fQ09OVEFC
TEVfVFJBTlNJVE9SSUFfRFBGJywgJzAnLCAwKTsKDQoKCg0K', NULL, 0);
