EXECUTE('
---------------------------
--ASOCIAR CARGO AL EVENTO--
---------------------------
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (400, 2200, 0, ''A'', 34096, ''CONDICIÓN CREDEB'', 1)
----
')
