EXECUTE('
UPDATE dbo.OPERACIONES
SET DESCRIPCION = ''ABMC SIBE Sectores''
WHERE TITULO = 6800 AND IDENTIFICACION = 8899

UPDATE dbo.DICCIONARIO
SET DESCRIPCION = ''DESCRIPCIÓN''
	, PROMPT = ''Descripción''
WHERE NUMERODECAMPO = 41342

')