
EXECUTE('
DROP TABLE SALDOSCAJA_HISTORICO;
')

EXECUTE('
CREATE TABLE dbo.SALDOSCAJA_HISTORICO
	(
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	FECHAPROCESO DATETIME NOT NULL,
	NROCAJA      NUMERIC (3) DEFAULT ((0)) NOT NULL,
	MONEDA       NUMERIC (4) DEFAULT ((0)) NOT NULL,
	SALDOINICIAL NUMERIC (15, 2) DEFAULT ((0)),
	ENTRADAS     NUMERIC (15, 2) DEFAULT ((0)),
	SALIDAS      NUMERIC (15, 2) DEFAULT ((0)),
	MINIMOAVISO  NUMERIC (15, 2) DEFAULT ((0)),
	MAXIMOAVISO  NUMERIC (15, 2) DEFAULT ((0)),
	SUCURSAL     NUMERIC (5) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SALDOSCAJA_HISTORICO PRIMARY KEY (FECHAPROCESO, NROCAJA, MONEDA, SUCURSAL)
	)
')