EXECUTE('
UPDATE DICCIONARIO
SET USODELCAMPO='' '', REFERENCIA=0, DESCRIPCION=''Nro. de Sucursal'', PROMPT=''Sucursal'', LARGO=5, TIPODECAMPO=''N'', DECIMALES=0, EDICION=NULL, CONTABILIZA=0, CONCEPTO=0, CALCULO=0, VALIDACION=0, TABLADEVALIDACION=0, TABLADEAYUDA=0, OPCIONES=0, TABLA=811, CAMPO=''DEPENDENCIA'', BASICO=0, MASCARA=NULL
WHERE NUMERODECAMPO=8992;

UPDATE DICCIONARIO
SET USODELCAMPO='' '', REFERENCIA=0, DESCRIPCION=''Nombre de la Sucursal'', PROMPT=''Nombre Sucursal'', LARGO=35, TIPODECAMPO=''A'', DECIMALES=0, EDICION=NULL, CONTABILIZA=0, CONCEPTO=0, CALCULO=0, VALIDACION=0, TABLADEVALIDACION=0, TABLADEAYUDA=0, OPCIONES=0, TABLA=811, CAMPO=''NOMBRE_DEPENDENCIA'', BASICO=0, MASCARA=NULL
WHERE NUMERODECAMPO=8993;
');