


-- Patch_NUNBCHACO_824

-- Agrega los Pivots en PARAMETROS_JTS
INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CATEGORIZACION', 'PIVOT_IVA_FINANCIADO', '35650', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CATEGORIZACION', 'PIVOT_IVA_PERCEPCION_FINANCIADO', '35651', 0);

-- Agrega los Pivot al Diccionario
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35650, ' ', 0, 'PIVOT_IVA_FINANCIADO', 'Pivot_Iva_Finan', 15, 'N', 2, 'i', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35651, ' ', 0, 'PIVOT_IVA_PERCEPCION_FINANCIADO', 'Pivot_Iva_Percep_Finan', 15, 'N', 2, 'i', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20211111_1NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VTkJDSEFDT184MjQKDQotLSBBZ3JlZ2EgbG9zIFBpdm90cyBlbiBQQVJB
TUVUUk9TX0pUUw0KSU5TRVJUIElOVE8gUEFSQU1FVFJPU19KVFMgKEZVTkNJT05BTElEQUQsIFBB
UkFNRVRSTywgVkFMT1IsIFRaX0xPQ0spClZBTFVFUyAoJ0NBVEVHT1JJWkFDSU9OJywgJ1BJVk9U
X0lWQV9GSU5BTkNJQURPJywgJzU4MzU3JywgMCk7CgpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pU
UyAoRlVOQ0lPTkFMSURBRCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQ0FU
RUdPUklaQUNJT04nLCAnUElWT1RfSVZBX1BFUkNFUENJT05fRklOQU5DSUFETycsICc1ODM1OCcs
IDApOwoNCi0tIEFncmVnYSBsb3MgUGl2b3QgYWwgRGljY2lvbmFyaW8NCklOU0VSVCBJTlRPIERJ
Q0NJT05BUklPIChOVU1FUk9ERUNBTVBPLCBVU09ERUxDQU1QTywgUkVGRVJFTkNJQSwgREVTQ1JJ
UENJT04sIFBST01QVCwgTEFSR08sIFRJUE9ERUNBTVBPLCBERUNJTUFMRVMsIEVESUNJT04sIENP
TlRBQklMSVpBLCBDT05DRVBUTywgQ0FMQ1VMTywgVkFMSURBQ0lPTiwgVEFCTEFERVZBTElEQUNJ
T04sIFRBQkxBREVBWVVEQSwgT1BDSU9ORVMsIFRBQkxBLCBDQU1QTywgQkFTSUNPLCBNQVNDQVJB
KQpWQUxVRVMgKDU4MzU3LCAnICcsIDAsICdQSVZPVF9JVkFfRklOQU5DSUFETycsICdQaXZvdF9J
dmFfRmluYW4nLCAxNSwgJ04nLCAyLCAnaScsIDAsIDAsIDAsIDAsIDAsIDAsIDAsIDAsIE5VTEws
IDAsIE5VTEwpCgpJTlNFUlQgSU5UTyBESUNDSU9OQVJJTyAoTlVNRVJPREVDQU1QTywgVVNPREVM
Q0FNUE8sIFJFRkVSRU5DSUEsIERFU0NSSVBDSU9OLCBQUk9NUFQsIExBUkdPLCBUSVBPREVDQU1Q
TywgREVDSU1BTEVTLCBFRElDSU9OLCBDT05UQUJJTElaQSwgQ09OQ0VQVE8sIENBTENVTE8sIFZB
TElEQUNJT04sIFRBQkxBREVWQUxJREFDSU9OLCBUQUJMQURFQVlVREEsIE9QQ0lPTkVTLCBUQUJM
QSwgQ0FNUE8sIEJBU0lDTywgTUFTQ0FSQSkKVkFMVUVTICg1ODM1OCwgJyAnLCAwLCAnUElWT1Rf
SVZBX1BFUkNFUENJT05fRklOQU5DSUFETycsICdQaXZvdF9JdmFfUGVyY2VwX0ZpbmFuJywgMTUs
ICdOJywgMiwgJ2knLCAwLCAwLCAwLCAwLCAwLCAwLCAwLCAwLCBOVUxMLCAwLCBOVUxMKTsKDQoK
Cg0K', NULL, 0);
