EXECUTE('

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37362, '' '', 0, ''Descripcion Tipo Sujeto'', ''Descripcion Tipo Sujeto'', 500, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''DESCRIPCION_CODIGO'', 0, NULL)

')


