EXECUTE('
------------------------------
--NUEVA VISTA VW_COF_EVENTOS--
------------------------------
INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (810, 3537, NULL, ''Vista eventos de Cajas de Seg.'', 0, ''VW_COF_EVENTOS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35370, '' '', 0, ''Nro. Evento'', ''Nro. Evento'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''NUMERO_EVENTO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35371, '' '', 0, ''Tipo de Evento'', ''Tipo de Evento'', 25, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''TIPO_EVENTO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35372, '' '', 0, ''Fecha de Evento'', ''Fecha de Evento'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3537, ''FECHA_EVENTO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35373, '' '', 0, ''Código de Contrato'', ''Código de Contrato'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''CODIGO_CONTRATO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35374, '' '', 0, ''Estado'', ''Estado'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''ESTADO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35375, '' '', 0, ''Fecha de Pago'', ''Fecha de Pago'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3537, ''FECHA_PAGO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35376, '' '', 0, ''Importe'', ''Importe'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''IMPORTE'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35377, '' '', 0, ''Mora'', ''Mora'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''MORA'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35378, '' '', 0, ''Impuestos'', ''Impuestos'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''IMPUESTOS'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35379, '' '', 0, ''Importe Total'', ''Importe Total'', 17, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 3537, ''IMPORTE_TOTAL'', 0, NULL)
----
INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3537, 1, ''índice de eventos Cajas Seg.'', 0, 35370, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3537, 35371, ''Listado eventos Cajas de Seg.'', '''', 0, ''35370ROA1;35371;35372;35376;35377;35378;35379;'', NULL, NULL, NULL, 0)
----
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35637, '' '', 0, ''Listado eventos Cajas de Seguridad'', ''Listado eventos Cajas de Seguridad'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 35371, 0, 0, NULL, 0, NULL)
----
')
