EXECUTE('
CREATE OR ALTER VIEW VW_CON_CERTIFICADOS_RETENCION(
									NRO_CERTIFICADO,
									FECHA_RETENCION,
									NOMBRECLIENTE,
									NUMERODOCUMENTO,
									DIRECCION,
									TIPO_IMPUESTO,
									IMPUESTO,
									REGIMEN,
									DESCRIPCION_REGIMEN,
									COMPROBANTE,
									MONTO_COMPROBANTE,
									MONTO_SUJETO_RETENCION,
									MONTO,
									ALICUOTA,
									DENOMINACIONAGENTE,
									CUITAGENTE,
									DIRECCION_AGENTE)
AS
SELECT CCR.NRO_CERTIFICADO, 
	CCR.FECHA_RETENCION,
	CD.NOMBRECLIENTE,
	CD.NUMERODOCUMENTO,
	CONCAT(CD.PAIS,'','',CD.PROVINCIA,'','',CD.DEPARTAMENTO,'','',CD.LOCALIDAD,'','',CD.CPA_NUEVO,'','',CD.CALLE,'' '',CD.NUMERO,'','',CD.PISO,'','',CD.APARTAMENTO) AS DIRECCION,
	CI.TIPO_IMPUESTO,
	CI.DESCRIPCION AS IMPUESTO, 
	CCR.CODIGO_REGIMEN AS REGIMEN,
	CRC.DESCRIPCION_REGIMEN AS DESCRIPCION_REGIMEN,
	CCR.NRO_COMPROBANTE AS COMPROBANTE,
	ccr.MONTO_COMPROBANTE AS MONTO_COMPROBANTE,
	CCR.MONTO_SUJETO_RETENCION AS MONTO_SUJETO_RETENCION,
	CCR.MONTO_RETENCION AS MONTO,
	CCR.ALICUOTA AS ALICUOTA,
	(SELECT NOMBRE1 FROM PARAMETROS) AS DENOMINACIONAGENTE,
	(SELECT NOMBRE2 FROM PARAMETROS) AS CUITAGENTE,
    (SELECT CONCAT(CP.DESCRIPCION,'','',CDD.NOMBREDEP,'','',CL.DESCRIPCION_DIM3,'','',CD.CPA_NUEVO,'','',CD.CALLE,'','',CD.NUMERO,'','',CD.PISO,'','',CD.APARTAMENTO) 
		FROM CLI_DIRECCIONES CD 
			INNER JOIN CLI_PROVINCIAS CP ON
				CD.PROVINCIA=CP.DIM1  
				AND CD.TZ_LOCK=0
			INNER JOIN CLI_DEPARTAMENTOS CDD ON 
				CDD.DEPARTAMENTO=CD.DEPARTAMENTO AND
				CDD.PROVINCIA=CP.DIM1
				AND CDD.TZ_LOCK=0
			INNER JOIN CLI_LOCALIDADES CL ON 
				CL.DIM1=CP.DIM1 AND
				CL.DIM2=CDD.DEPARTAMENTO AND
				CL.DIM3=CD.LOCALIDAD
				AND CL.TZ_LOCK=0
			WHERE FORMATO=''S'' 
				AND CD.ID=(SELECT NUMERICO FROM PARAMETROSGENERALES WHERE TZ_LOCK=0 AND CODIGO=21) 
				AND CD.TZ_LOCK=0
	) AS DIRECCION_AGENTE
	FROM CON_CERTIFICADOS_RETENCION CCR 
INNER JOIN VW_CLI_DIRECCIONES CD ON
	CCR.CODIGO_CLIENTE=CD.CODIGOCLIENTE 
INNER JOIN CON_EQUIVALENCIA_CARGO_IMPOSITIVO CI ON 
	CI.TIPO_CARGO_IMPOSITIVO=CCR.TIPO_CARGO_IMPOSITIVO
	--AND CI.CARGO_O_IMPUESTO = (SELECT TOP 1 CARGO_O_IMPUESTO FROM CON_EQUIVALENCIA_CARGO_IMPOSITIVO WHERE TIPO_CARGO_IMPOSITIVO=CCR.TIPO_CARGO_IMPOSITIVO)
	AND CI.TZ_LOCK=0
INNER JOIN CON_REGIMEN_CERTIF_RET  CRC ON
	CRC.TIPO_CARGO_IMPOSITIVO = CCR.TIPO_CARGO_IMPOSITIVO
	--AND CRC.TIPO_CARGO_IMPOSITIVO = 12
	AND CRC.TZ_LOCK = 0
WHERE CCR.TZ_LOCK=0
')

