execute('
DROP TABLE IF EXISTS dbo.BE_TRANSFERENCIAS


CREATE TABLE dbo.BE_TRANSFERENCIAS
	(
	FECHA_PROCESO        NUMERIC (8) NOT NULL,
	NRO_SECUENCIA        NUMERIC (3),
	TRANSFERENCIA        NUMERIC (9) NOT NULL,
	CUIT                 NUMERIC (13),
	BANCO_DEBITO         NUMERIC (4),
	TIPO_CUENTA_DB       NUMERIC (2),
	NUMERO_CUENTA_DB     NUMERIC (19),
	NOMBRE_CUENTA_DB     VARCHAR (50),
	CBU_DB               NUMERIC (23),
	BANCO_CR             NUMERIC (4),
	TIPO_CUENTA_CR       NUMERIC (2),
	NUMERO_CUENTA_CR     NUMERIC (19),
	NOMBRE_CUENTA_CR     VARCHAR (50),
	CBU_CR               NUMERIC (23),
	IMPORTE              NUMERIC (15, 2),
	CONCEPTO             VARCHAR (50),
	FECHA_INPUTACION     NUMERIC (8),
	FECHA_ALTA           NUMERIC (8),
	HORA_ALTA            NUMERIC (6),
	USUARIO_ALTA         VARCHAR (13),
	USUARIO_AUT_1        VARCHAR (13),
	FECHA_AUT_1          NUMERIC (8),
	HORA_AUT_1           NUMERIC (6),
	USUARIO_AUT_2        VARCHAR (13),
	FECHA_HORA_AUT_2     NUMERIC (8),
	HORA_AUT_2           NUMERIC (6),
	USUARIO_AUT_3        VARCHAR (13),
	FECHA_HORA_AUT_3     NUMERIC (8),
	HORA_AUT_3           NUMERIC (6),
	FECHA_ENVIO          NUMERIC (8),
	CUIT_CUIL_CDI_CR     NUMERIC (13),
	TITULARIDAD_CTA_CR   VARCHAR (1),
	MOTIVO               VARCHAR (3),
	REFERENCIA           VARCHAR (12),
	ESTADO_TRANSFERENCIA VARCHAR (62),
	PRIMARY KEY (FECHA_PROCESO, TRANSFERENCIA)
	)
');