
EXECUTE('
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 49689

DELETE FROM OPCIONES WHERE NUMERODECAMPO = 49689

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49689, '' '', 0, ''Opciones IVA MANT. MANUAL'', ''Tipo Cargo/Impuesto'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, NULL)

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49689, ''E'', ''Ambos'', ''0'', ''0'')


INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49689, ''E'', ''IVA Percepción'', ''1'', ''1'')
')