Execute('
ALTER TABLE ITF_CONVENIOS_PADRON ALTER COLUMN FECHA_PRIMER_VENCIMIENTO VARCHAR(8);
ALTER TABLE ITF_CONVENIOS_PADRON ALTER COLUMN FECHA_Segundo_VENCIMIENTO VARCHAR(8);
ALTER TABLE ITF_CONVENIOS_PADRON ALTER COLUMN FECHA_VIGENCIA VARCHAR(8);')