EXECUTE('

IF OBJECT_ID (''[dbo].[ITF_AFIP_DEUDA_CONSULTA_SERVICIO]'') IS NOT NULL
	DROP TABLE [dbo].[ITF_AFIP_DEUDA_CONSULTA_SERVICIO]

')

EXECUTE('

CREATE TABLE dbo.ITF_AFIP_DEUDA_CONSULTA_SERVICIO
	(
	ID_TICKET      NUMERIC (16) DEFAULT ((0)) NOT NULL,
	FECHAPROCESO   DATETIME DEFAULT (sysdatetime()),
	CUIT           NUMERIC (12),
	SERVICIO       VARCHAR (10),
	CONSULTA_ID    NUMERIC (15),
	TIENE_DEUDA    VARCHAR (6),
	RESPUESTA_JSON VARCHAR (8000)
	)
')