EXECUTE('
INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA) 
VALUES (666, 0, 5, 1, ''Obteniendo Nombre Situacion'', NULL, NULL)


INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA) 
VALUES (666, 1, 5, 1, ''C2013=C43'', ''C904'', ''C2015'')
')