Execute('
TRUNCATE TABLE ITF_CONVENIOS_PADRON;
ALTER TABLE ITF_CONVENIOS_PADRON ALTER COLUMN fecha_padron VARCHAR(10);
ALTER TABLE ITF_CONVENIOS_PADRON ALTER COLUMN CANTIDAD_REGISTROS VARCHAR(12);')

