EXECUTE ('
INSERT INTO OPERACIONES
(TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES(3552, 3451, ''Novedades Clearing'', ''Novedades Clearing'', ''3451'', ''A'', 0, 0, ''P'', 0, 0, 0, ''S'', ''N'', ''N'', ''N'', ''N'', 0, 0);
');