EXECUTE('
UPDATE dbo.PARAMETROS_JTS
SET VALOR = ''58492''
WHERE FUNCIONALIDAD = ''CREA_CRONOGRAMA_DIFERENTE_TASA_INTERES'' AND PARAMETRO = ''PIVOT_DIFERENCIA_TOTAL_INTERES''

 
UPDATE dbo.PARAMETROS_JTS
SET VALOR = ''58493''
WHERE FUNCIONALIDAD = ''DEVENGA_DIFERENCIA_INTERESES'' AND PARAMETRO = ''PIVOT_TOTAL_INTERES''
')