EXECUTE('
CREATE OR ALTER PROCEDURE [dbo].[SP_ITF_SOS_CLIENTES_SINMOV]
	@Fecha VARCHAR(8)
AS
BEGIN

--Limpiamos por si hay reproceso
DELETE FROM SOS_CLIENTES_SINMOV WHERE convert(VARCHAR,FECHADEINFORMACION) = @Fecha;

SELECT DISTINCT sa.c1803 AS CODCLIENTE 
  INTO #TMP_CLIENTES
FROM SALDOS sa
WHERE sa.C1604 <> 0
  AND sa.C1803 <> 0
  AND NOT EXISTS(SELECT 1 FROM SOS_MOVS_HISTORICOS smov WHERE smov.FECHADEINFORMACION = @Fecha AND smov.CUENTACLIENTE = sa.C1803)
  AND NOT EXISTS(SELECT 1 FROM SOS_VINCULACION svinc WHERE svinc.FECHADEINFORMACION = @Fecha AND svinc.CODCLIENTE = sa.C1803)
  AND sa.TZ_LOCK = 0

INSERT INTO SOS_CLIENTES_SINMOV
--NATURAL
SELECT 
--1
''311'' AS EMPRESA,
--2
CONVERT(NUMERIC,@Fecha) AS FECHADEINFORMACION,
--3
ISNULL((SELECT CONVERT(NUMERIC,ALFA_2) FROM ITF_MASTER_PARAMETROS
WHERE FUNCIONALIDAD = ''SOSDOCIDENTIFICA''
  AND ALFA_1 = ''N''
  AND ALFA_3 = doc.TIPODOCUMENTO),0) AS IDENTTRIBUTARIATIPO,
--4
CONVERT(NUMERIC,doc.NUMERODOCUMENTO) AS IDENTTRIBUTARIANUMERO,
--5
ISNULL((SELECT CONVERT(NUMERIC,ALFA_2) FROM ITF_MASTER_PARAMETROS
WHERE FUNCIONALIDAD = ''SOSDOCIDENTIFICA''
  AND ALFA_1 = ''N''
  AND ALFA_3 = doc.TIPODOCUMENTO),0) AS DOCIDENTIFICATORIATIPO,
--6
CONVERT(NUMERIC,doc.NUMERODOCUMENTO) AS DOCIDENTIFICATORIANUMERO,
--7
SUBSTRING(cli.NOMBRECLIENTE,1,55) AS DENOMINACION,
--8
SUBSTRING(dir.CALLE,1,55) AS DOMICILIOCALLE,
--9
dir.NUMERO AS DOMICILIONUMERO,
--10
RIGHT(dir.PISO,2) AS DOMICILIOPISO,
--11
dir.APARTAMENTO AS DOMICILIODPTOOFICINA,
--12
dir.CPA_VIEJO AS DOMICILIOCODIGOPOSTAL,
--13
dir.LOCALIDAD AS DOMICILIOLOCALIDAD,
--14
dir.PROVINCIA AS DOMICILIOPROVINCIA,
--15
(SELECT x.CODIGOSWIFT FROM CLI_PAISES x WHERE x.CODIGOPAIS = dir.PAIS) AS DOMICIOLIOPAISSWFIT,
--16
(SELECT cliact.CODIGO_BCRA FROM VW_SOS_ACT_ECO cliact	
WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
  AND cliact.tipo_actividad = ''Primaria'') AS CODIGOACTIVIDAD,
--17
(SELECT TOP 1 cliact.CODIGO_BCRA FROM VW_SOS_ACT_ECO cliact	
WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
  AND cliact.tipo_actividad = ''Secundaria'') AS CODIGOACTIVIDADSEC,
--18
(SELECT x.CODIGOSWIFT FROM CLI_PAISES x WHERE x.CODIGOPAIS = nat.PAISRESIDENCIA)  AS RESIDENCIA,
--19
'''' AS CODIGOAREATEL,
--20
'''' AS CARACTERISTICATEL,
--21
'''' AS TELEFONO,
--22
'''' AS FAX,
--23
'''' AS TELEX,
--24
'''' AS EMAIL,
--25
nat.SEXO,
--26
nat.ESTADOCIVIL,
--27
'''' AS CODIGOACTIVIDADINTERNO,
--28
convert(VARCHAR, nat.FECHAALTA, 112) AS FECHAALTA,
--29
''00000000'' AS FECHABAJA,
--30
nat.SUC_ALTA,
--31
nat.PAISNACIMIENTO AS CODIGOPAIS,
--32
''PF'' AS TIPOCLIENTE,
--33
(CASE WHEN nat.EMPLEADO_BC_BANCO = ''1'' THEN ''N'' ELSE ''S'' END)  AS MARCAEMPLEADO,
--34
nat.INCLUIDO_PEP AS PEP,
--35
nat.SUJETO_UIF AS SUJETOOBLIGADO,
--36
isnull(nat.INSC_UIF,''N'') AS CONST_INSCRIP_SSOO,
--37
(SELECT cliact.CODIGO_ACT_AFIP FROM VW_SOS_ACT_ECO cliact	
  WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
    AND cliact.tipo_actividad = ''Primaria'') AS CODIGOACTIVIDADAFIP,
--38
(SELECT TOP 1 cliact.CODIGO_ACT_AFIP FROM VW_SOS_ACT_ECO cliact	
  WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
    AND cliact.tipo_actividad = ''Secundaria'') AS CODIGOACTIVIDADAFIPSEC,
--39
0 AS FORMAJURIDICA,
--40
nat.SECTOR AS SECTORBCRA,
--41
SUBSTRING(RTRIM(nat.APELLIDOPATERNO + '''' + nat.APELLIDOMATERNO),1,55) AS APELLIDO,
--42
SUBSTRING(RTRIM(nat.PRIMERNOMBRE + '' '' + nat.SEGUNDONOMBRE),1,55) AS NOMBRE,
--43
''00000000'' AS FECHACONSTITUCIONSOCIEDAD,
--44
nat.TIPO_SUJETO_UIF AS TIPOSSOO,
--45
nat.INSC_UIF AS DECJURSSOO, --ojo
--46
nat.IVA AS CATEGORIAIVA,
--47
''N'' AS MARCASUELDO,
--48
0 AS TAMANIOEMPRESA,
--49
nat.MONOTRIBUTO AS CLIMONTRIBIVA,
--
cli.CODIGOCLIENTE
--SELECT dir.PAIS, *
FROM CLI_CLIENTES cli (NOLOCK)
  INNER JOIN CLI_CLIENTEPERSONA cp (NOLOCK) ON cp.CODIGOCLIENTE = cli.CODIGOCLIENTE
  INNER JOIN CLI_PERSONASFISICAS nat (NOLOCK) ON nat.NUMEROPERSONAFISICA = cp.NUMEROPERSONA
  INNER JOIN CLI_DIRECCIONES dir (NOLOCK) ON dir.ID = nat.NUMEROPERSONAFISICA AND dir.FORMATO = ''PF'' AND dir.TIPODIRECCION = ''F''
    AND dir.ORDINAL_DIR = 1
  INNER JOIN CLI_DocumentosPFPJ doc (NOLOCK) ON doc.NUMEROPERSONAFJ = nat.NUMEROPERSONAFISICA
WHERE cli.TZ_LOCK = 0
  AND cp.TZ_LOCK = 0
  AND nat.TZ_LOCK = 0
  AND dir.TZ_LOCK = 0
  AND doc.TZ_LOCK = 0
  AND cp.TITULARIDAD = ''T''
  AND nat.SECTOR NOT IN (6,7)
  --AND cli.CODIGOCLIENTE = 144606
  AND EXISTS(SELECT 1 FROM #TMP_CLIENTES x WHERE x.CODCLIENTE = cli.CODIGOCLIENTE)
  
--UNION
---JURIDICA
INSERT INTO SOS_CLIENTES_SINMOV
SELECT 
--1
''311'' AS EMPRESA,
--2
CONVERT(NUMERIC,@Fecha) AS FECHADEINFORMACION,
--3
ISNULL((SELECT CONVERT(NUMERIC,ALFA_2) FROM ITF_MASTER_PARAMETROS
WHERE FUNCIONALIDAD = ''SOSDOCIDENTIFICA''
  AND ALFA_1 = ''J''
  AND ALFA_3 = doc.TIPODOCUMENTO),0) AS IDENTTRIBUTARIATIPO,
--4
CONVERT(NUMERIC,doc.NUMERODOCUMENTO) AS IDENTTRIBUTARIANUMERO,
--5
0 AS DOCIDENTIFICATORIATIPO,
--6
0 AS DOCIDENTIFICATORIANUMERO,
--7
SUBSTRING(cli.NOMBRECLIENTE,1,55) AS DENOMINACION,
--8
SUBSTRING(dir.CALLE,1,55) AS DOMICILIOCALLE,
--9
dir.NUMERO AS DOMICILIONUMERO,
--10
RIGHT(dir.PISO,2) AS DOMICILIOPISO,
--11
dir.APARTAMENTO AS DOMICILIODPTOOFICINA,
--12
dir.CPA_VIEJO AS DOMICILIOCODIGOPOSTAL,
--13
dir.LOCALIDAD AS DOMICILIOLOCALIDAD,
--14
dir.PROVINCIA AS DOMICILIOPROVINCIA,
--15
(SELECT x.CODIGOSWIFT FROM CLI_PAISES x WHERE x.CODIGOPAIS = dir.PAIS) AS DOMICIOLIOPAISSWFIT,
--16
(SELECT cliact.CODIGO_BCRA FROM VW_SOS_ACT_ECO cliact	
  WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
    AND cliact.tipo_actividad = ''Primaria'') AS CODIGOACTIVIDAD,
--17
(SELECT TOP 1 cliact.CODIGO_BCRA FROM VW_SOS_ACT_ECO cliact	
WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
  AND cliact.tipo_actividad = ''Secundaria'')AS CODIGOACTIVIDADSEC,
--18
(SELECT x.CODIGOSWIFT FROM CLI_PAISES x WHERE x.CODIGOPAIS = jur.PAISRESIDENCIA)  AS RESIDENCIA,
--19
'''' AS CODIGOAREATEL,
--20
'''' AS CARACTERISTICATEL,
--21
'''' AS TELEFONO,
--22
'''' AS FAX,
--23
'''' AS TELEX,
--24
'''' AS EMAIL,
--25
'''' AS SEXO,
--26
'''' AS ESTADOCIVIL,
--27
'''' AS CODIGOACTIVIDADINTERNO,
--28
convert(VARCHAR, jur.FECHAALTA, 112) AS FECHAALTA,
--29
''00000000'' AS FECHABAJA,
--30
jur.SUC_ALTA,
--31
jur.PAISRESIDENCIA AS CODIGOPAIS,
--32
''PF'' AS TIPOCLIENTE,
--33
''N'' AS MARCAEMPLEADO,
--34
jur.INCL_PEPS AS PEP, --
--35
jur.SUJETO_UIF,
--36
jur.INSC_UIF AS CONST_INSCRIP_SSOO,
--37
(SELECT cliact.CODIGO_ACT_AFIP FROM VW_SOS_ACT_ECO cliact	
  WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
    AND cliact.tipo_actividad = ''Primaria'') AS CODIGOACTIVIDADAFIP,
--38
(SELECT TOP 1 cliact.CODIGO_ACT_AFIP FROM VW_SOS_ACT_ECO cliact	
  WHERE cliact.CODIGO_PERSONA = cp.NUMEROPERSONA
    AND cliact.tipo_actividad = ''Secundaria'') AS CODIGOACTIVIDADAFIPSEC,
--39
jur.TIPOSOCIEDAD AS FORMAJURIDICA,
--40
jur.SECTOR,
--41
'''' AS APELLIDO,
--42
'''' AS NOMBRE,
--43
CONVERT(VARCHAR, jur.FECHACONSTITUCION,112) AS FECHACONSTITUCIONSOCIEDAD,
--44
jur.TIPO_SUJETO_UIF,
--45
jur.INSC_UIF AS DECJURSSOO,
--46
jur.IVA AS CATEGORIAIVA,
--47
''N'' AS MARCASUELDO,
--48
0 AS TAMANIOEMPRESA,
--49
jur.MONOTRIBUTO,
--
cli.CODIGOCLIENTE
--SELECT dir.PAIS, *
FROM CLI_CLIENTES cli (NOLOCK)
  INNER JOIN CLI_CLIENTEPERSONA cp (NOLOCK) ON cp.CODIGOCLIENTE = cli.CODIGOCLIENTE AND cp.TITULARIDAD = ''T''
  INNER JOIN CLI_PERSONASJURIDICAS jur (NOLOCK) ON jur.NUMEROPERSONAJURIDICA = cp.NUMEROPERSONA
  INNER JOIN CLI_DIRECCIONES dir (NOLOCK) ON dir.ID = jur.NUMEROPERSONAJURIDICA AND dir.FORMATO = ''PJ'' AND dir.TIPODIRECCION = ''L''
    AND dir.ORDINAL_DIR = 1
  INNER JOIN CLI_DocumentosPFPJ doc (NOLOCK) ON doc.NUMEROPERSONAFJ = jur.NUMEROPERSONAJURIDICA
WHERE cp.TZ_LOCK = 0
  AND cli.TZ_LOCK = 0
  AND jur.TZ_LOCK = 0
  AND dir.TZ_LOCK = 0
  AND doc.TZ_LOCK = 0
  AND jur.SECTOR NOT IN (6,7)
  AND EXISTS(SELECT 1 FROM #TMP_CLIENTES x WHERE x.CODCLIENTE = cli.CODIGOCLIENTE)
  --AND cli.CODIGOCLIENTE = 144606
END
')