
EXECUTE('
ALTER TABLE VTA_SOBREGIROS ADD FECHA_CAT_COM       DATETIME
ALTER TABLE VTA_SOBREGIROS ADD TAMANIO             VARCHAR (1) DEFAULT ('' '')
ALTER TABLE VTA_SOBREGIROS ADD CODIGO_SUBSIDIO     NUMERIC (5)
ALTER TABLE VTA_SOBREGIROS ADD CODIGO_ACTIVIDAD    VARCHAR (12)
ALTER TABLE VTA_SOBREGIROS ADD CODIGO_SECTOR       NUMERIC (5)
ALTER TABLE VTA_SOBREGIROS ADD DESTINO_FONDOS      NUMERIC (5)
ALTER TABLE CRE_SALDOS ADD DESTINO_FONDOS NUMERIC(5)')











