EXECUTE('CREATE TABLE dbo.CRE_SEGURO_VIDA_VOLUNTARIO 
	(
	TZ_LOCK NUMERIC(15) DEFAULT ((0)) NOT NULL,
	SALDO_JTS_OID NUMERIC(10) NULL,
	CLIENTE NUMERIC(12) NOT NULL,
	ASEGURADORA NUMERIC(12) DEFAULT ((0)) NULL,
	FECHA_VENCIMIENTO DATETIME NOT NULL,
	MONTO NUMERIC(15,2) DEFAULT ((0)) NULL,
	NUMERO_POLIZA VARCHAR(25) NOT NULL,
	NRO_SOLICITUD NUMERIC(15) NOT NULL,
	ORDINAL NUMERIC(5) NOT NULL,
	
	CONSTRAINT CRE_SEGUROVIDAVOLUNTARIO1 PRIMARY KEY (NRO_SOLICITUD, ORDINAL)
	)
')