EXECUTE('
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (5005, 50051, ''ANIOMES'', '''', 0, ''46027ROD1;46028;'', NULL, NULL, NULL, 0)
')