EXECUTE('
CREATE PROCEDURE [dbo].[SP_BUSCA_SEGURO_SALDO]
    @P_PRODUCTO NUMERIC(5),
    @P_FAMILIA NUMERIC(5),
    @P_CLIENTE NUMERIC(15),
    @P_IMPORTE_SOLICITUD NUMERIC(15,2),
    @P_ASEGURADORA NUMERIC(10),
    @P_EDAD NUMERIC(3),
    @P_EDAD_FIN NUMERIC(3),
    @IMPORTE_DISPONIBLE NUMERIC(15,2)  OUTPUT,
    @EDAD_DESDE NUMERIC(5)  OUTPUT,
    @FALTANTE_CUBRIR NUMERIC(15,2) OUTPUT
AS
BEGIN

    DECLARE @DEUDA_TOTAL NUMERIC(15,2)
    DECLARE @IMPORTE_MAXIMO NUMERIC(15,2)
    DECLARE @EDAD_MIN NUMERIC(5)
    DECLARE @EDAD_INI NUMERIC(5)
    
    
    SET @EDAD_MIN = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH(NOLOCK) WHERE CODIGO=13)
    
    
    ---- Busco seguro
    
    IF(@P_EDAD>=@EDAD_MIN)
    	BEGIN
    		---- Obtengo deuda total
    		SET @DEUDA_TOTAL = (SELECT ISNULL(SUM(SALDO_DEUDA),0)
    		FROM CRE_SEGURO_SALDO_DEUDOR SSD WITH(NOLOCK)
    		INNER JOIN VW_DEUDA_CLIENTES DC WITH(NOLOCK) ON DC.JTS_OID = SSD.SALDOS_JTS_OID
    		WHERE  SSD.TZ_LOCK=0 AND SSD.ASEGURADORA = @P_ASEGURADORA
    		AND DC.CLIENTE = @P_CLIENTE AND (DC.PRODUCTO = @P_PRODUCTO OR DC.FAMILIA = @P_FAMILIA))
    		
    		--- Obtengo seguro para edad
    		
    		SELECT TOP 1 @IMPORTE_MAXIMO = PSSD.MONTO_MAXIMO, 
			@EDAD_INI = PSSD.EDAD_DESDE
    		FROM CRE_PROD_SEGUROS_SALDO_DEUDOR PSSD WITH(NOLOCK)
    		WHERE PSSD.TZ_LOCK=0 
    		AND PSSD.ASEGURADORA = @P_ASEGURADORA AND PSSD.EDAD_DESDE>= @P_EDAD 
			AND PSSD.EDAD_HASTA>= @P_EDAD_FIN 
    		AND ((PSSD.TIPO=''P'' AND PSSD.CODIGO=@P_PRODUCTO) OR (PSSD.TIPO=''F'' AND PSSD.CODIGO=@P_FAMILIA))
    		ORDER BY PSSD.EDAD_DESDE ASC, PSSD.MONTO_MAXIMO DESC
    		
    		--- Seteo importe disponible

			SET @IMPORTE_DISPONIBLE = (@IMPORTE_MAXIMO-@DEUDA_TOTAL)
			
			--- Setea edad inicio para filtrar en grilla
			
			SET @EDAD_DESDE = @EDAD_INI
			
			--- Setea lo que falta para cubrir el total de la asistencia
			
			IF(@IMPORTE_DISPONIBLE < @P_IMPORTE_SOLICITUD)
				SET @FALTANTE_CUBRIR = (@P_IMPORTE_SOLICITUD - @IMPORTE_DISPONIBLE)
			ELSE
				SET @FALTANTE_CUBRIR = 0

    	END
      
END
')
