EXECUTE('
INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (7615, 1, 49, 0)


INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (7616, 1, 48, 0)

')