EXECUTE('
IF OBJECT_ID (''dbo.TJC_ADINTAR_DEUDASPLAS'') IS NOT NULL
	DROP TABLE dbo.TJC_ADINTAR_DEUDASPLAS
')
EXECUTE('

CREATE TABLE dbo.TJC_ADINTAR_DEUDASPLAS
	(
	FECHA_GENERACION  DATETIME NOT NULL,
	ADMINISTRADORA    NUMERIC (2) DEFAULT ((0)) NOT NULL,
	NRO_CUENTA        NUMERIC (20) DEFAULT ((0)) NOT NULL,
	CONDICION         VARCHAR (1) DEFAULT ('' ''),
	NRO_PLASTICO      NUMERIC (16) DEFAULT ((0)),
	TIPO              VARCHAR (2) DEFAULT ('' ''),
	ESTADO            VARCHAR (1) DEFAULT ('' ''),
	ULT_LIQUIDACION   DATETIME,
	FECHA_VENCIMIENTO DATETIME,
	OPERA             VARCHAR (1) DEFAULT ('' ''),
	TIPO_PRODUCTO     VARCHAR (1) DEFAULT ('' ''),
	SUB_PRODUCTO      NUMERIC (3) DEFAULT ((0)),
	TZ_LOCK           NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_TJC_ADINTAR_DEUDASPLAS_01 PRIMARY KEY (FECHA_GENERACION, ADMINISTRADORA, NRO_CUENTA)
	)
')
EXECUTE('
IF OBJECT_ID (''dbo.VW_REGIMEN_TRANSPARENCIA'') IS NOT NULL
	DROP VIEW dbo.VW_REGIMEN_TRANSPARENCIA
')
EXECUTE('
CREATE VIEW VW_REGIMEN_TRANSPARENCIA as
SELECT
--1
RPI.CHAR1 AS CodigoPartida, 
--2
CT.IMPORTE_APLICAR AS ImporteVigente,
--3
CT.TASA AS TasaInteres,
--4
''0'' AS Observaciones,
--5
NULL AS Moneda,
--6
0050 AS Empresa,
--7
0 AS ImportePrevisto, --no se encuentra en topaz, CT.IMPORTE_APLICAR con mes o dia +1
--8
CT.FECHA_HASTA AS FechaVigencia,
--9
CT.FECHA_DESDE AS FechaDesde,
--10
NULL AS Cantidad

FROM CI_CARGOS C
JOIN CI_CARGOS_TARIFAS CT ON C.ID_CARGO = CT.ID_CARGO
	AND C.TZ_LOCK=CT.TZ_LOCK
JOIN RRI_PARAMETROS_INF RPI ON C.ID_CARGO = RPI.ID1 
WHERE RPI.CODIGO = 100
AND C.TZ_LOCK = 0

UNION

SELECT

--1
R.CHAR1 AS CodigoPartida, 
--2
NULL AS ImporteVigente,
--3
NULL AS TasaInteres,
--4
''0'' AS Observaciones,
--5
NULL AS Moneda,
--6
0050 AS Empresa,
--7
0 AS ImportePrevisto, --no se encuentra en topaz, CT.IMPORTE_APLICAR con mes o dia +1
--8
NULL AS FechaVigencia,
--9
NULL AS FechaDesde,
--10
	COUNT(*) AS Cantidad
FROM RRI_PARAMETROS_INF R
INNER JOIN SALDOS S 
	ON S.C1785 = R.ID1
INNER JOIN GRL_SALDOS_DIARIOS G
	ON G.SALDOS_JTS_OID = S.JTS_OID
	AND G.TZ_LOCK = S.TZ_LOCK
WHERE R.CODIGO = 101
AND R.TZ_LOCK=0
AND R.CHAR1 IN (010000,020000)
AND G.MONEDA = 1
AND G.TZ_LOCK = 0
GROUP BY 
	R.CHAR1
	
UNION ALL

SELECT

--1
R.CHAR1 AS CodigoPartida, 
--2
NULL AS ImporteVigente,
--3
NULL AS TasaInteres,
--4
''0'' AS Observaciones,
--5
NULL AS Moneda,
--6
0050 AS Empresa,
--7
0 AS ImportePrevisto, --no se encuentra en topaz, CT.IMPORTE_APLICAR con mes o dia +1
--8
NULL AS FechaVigencia,
--9
NULL AS FechaDesde,
--10
	COUNT(T.USUARIO) AS Cantidad
	
FROM RRI_PARAMETROS_INF R
INNER JOIN TJC_SALDOS  T
	ON T.ADMINISTRADORA = R.ID1
	AND T.TZ_LOCK = R.TZ_LOCK
INNER JOIN TJC_ADINTAR_DEUDASPLAS TAD 
	ON T.ADMINISTRADORA = TAD.ADMINISTRADORA
WHERE R.CODIGO = 102
AND R.TZ_LOCK=0
AND R.CHAR1 IN (034000,035000)
AND TAD.CONDICION = ''T''
GROUP BY 
	R.CHAR1
')