EXECUTE('
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (6000, 6688, ''Exclusiones del Cliente'', ''Exclusiones del Cliente'', ''6688'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

')