execute('


INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (30, 4908, NULL, ''Tabla ATM'', 0, ''TABLA_ATM'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (30, 4909, NULL, ''Saldos ATM'', 0, ''SALDOSATM'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (30, 4910, NULL, ''Categorías ATM'', 0, ''CAJ_ATM_CATEGORIAS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (30, 4911, NULL, ''Historico de Saldo ATM'', 0, ''SALDOSATM_HISTORICO'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49250, '' '', 0, ''Descripción ATM'', ''Nombre'', 25, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''NOMBRE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49251, '' '', 0, ''Nro ATM'', ''Nro ATM'', 5, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 4908, ''NRO_ATM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49252, '' '', 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''MONEDA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49253, '' '', 0, ''Código ATM'', ''Código ATM'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''CODIGO_ATM '', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49254, '' '', 0, ''Dirección'', ''Dirección'', 250, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''DIRECCION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49255, '' '', 0, ''Localidad'', ''Localidad'', 250, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''LOCALIDAD'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49256, '' '', 0, ''Sucursal ubicación'', ''Sucursal ubicación'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 511, 0, 4908, ''SUCURSAL_UBICACION '', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49257, '' '', 0, ''Sucursal Contable'', ''Sucursal Contable'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 511, 0, 4908, ''SUCURSAL_CONTABLE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49258, '' '', 0, ''Ubicación'', ''Ubicación'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4908, ''UBICACION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49259, '' '', 0, ''Estado'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4908, ''ESTADO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49260, '' '', 0, ''Categoría'', ''Categoría'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49101, 0, 4908, ''CATEGORIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49261, '' '', 0, ''JTS de SALDOS'', ''JTS de SALDOS'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4908, ''JTS_SALDO '', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49263, '' '', 0, ''Administración'', ''Administración'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4908, ''ADMINISTRACION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49264, '' '', 0, ''Transportadora'', ''Transportadora'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 421, 0, 4908, ''TRANSPORTADORA'', 0, NULL)




INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49270, '' '', 0, ''Nro ATM'', ''Nro ATM'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''NRO_ATM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49271, '' '', 0, ''Moneda Saldo'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''MONEDA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49272, '' '', 0, ''Saldo inicio del día'', ''Saldo inicio del día'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4909, ''SALDO_INICIAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49273, '' '', 0, ''Entradas del día '', ''Entradas'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4909, ''ENTRADAS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49274, '' '', 0, ''Salidas del día'', ''Salidas'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''SALIDAS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49275, '' '', 0, ''Depósitos del día'', ''Depósitos'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4909, ''DEPOSITOS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49276, '' '', 0, ''Retiros del día'', ''Retiros'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''RETIROS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49277, '' '', 0, ''Jtsoid de Saldos de ATM '', ''Jtsoid de saldos de ATM'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''SALDOJTSOID'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49278, '' '', 0, ''Sucursal Contable del saldo del ATM'', ''Sucursal Contable'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4909, ''SUCURSAL_CONTABLE'', 0, NULL)



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49290, '' '', 0, ''Categoría'', ''Categoría'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4910, ''CATEGORIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49291, '' '', 0, ''Descripción Categoria'', ''Descripción'', 25, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4910, ''DESCRIPCION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49292, '' '', 0, ''Coeficiente Sucursal'', ''Coeficiente Sucursal'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4910, ''COEF_SUCURSAL '', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49293, '' '', 0, ''Coeficiente Neutral'', ''Coeficiente Neutral'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4910, ''COEF_NEUTRAL'', 0, NULL)



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49300, '' '', 0, ''Numero ATM'', ''Numero ATM'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4911, ''NRO_ATM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49301, '' '', 0, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4911, ''MONEDA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49302, '' '', 0, ''Saldo inicial'', ''Saldo inicial'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4911, ''SALDO_INICIAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49303, '' '', 0, ''Entradas'', ''Entradas'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4911, ''ENTRADAS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49304, '' '', 0, ''Salidas'', ''Salidas'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4911, ''SALIDAS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49305, '' '', 0, ''Depositos'', ''Depositos'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4911, ''DEPOSITOS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49306, '' '', 0, ''Retiros'', ''Retiros'', 15, ''N'', 2, ''i'', 0, 0, 0, 0, 0, 0, 0, 4911, ''RETIROS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49307, '' '', 0, ''Fecha proceso'', ''Fecha proceso'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4911, ''FECHAPROCESO'', 0, NULL)
')
