EXECUTE('
------------------------
--NUEVO CAMPO CONCEPTO--
------------------------
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35500, '' '', 0, ''Concepto'', ''Concepto'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3463, ''CONCEPTO'', 0, NULL)
------
')




