EXECUTE('
IF OBJECT_ID (''VW_REM_MINIFILIALES'') IS NOT NULL
	DROP VIEW VW_REM_MINIFILIALES
')

EXECUTE('
CREATE   VIEW VW_REM_MINIFILIALES 
AS
SELECT distinct	rs.NRO_SOLICITUD ''Nro. Solicitud'', 
		rs.MONEDA Moneda, 
		rs.IMPORTE Importe, 
		rs.TIPODESTINO ''Tipo Destino'', 
		o.DESCRIPCION ''Descripción'', 
		rs.CAJA_DESTINO ''Caja Destino'', 
		CASE
		    WHEN rs.CAJA_DESTINO = 999 THEN 0
		    ELSE vwc.MINIFILIAL
		END AS ''Minifilial Destino'', 
		rs.SUCURSAL Sucursal, 
		rs.ESTADO Estado, 
		rs.CAJA_ORIGEN ''Caja Origen'' 
FROM REM_SOLICITUDREMESA rs WITH (NOLOCK) 
INNER JOIN OPCIONES o  WITH (NOLOCK) ON o.OPCIONINTERNA = rs.TIPODESTINO
									AND o.NUMERODECAMPO = 2599
									AND o.IDIOMA = ''E''
									AND rs.TIPODESTINO = 11
									AND rs.TIPOORIGEN = 11
INNER JOIN VW_CAJ_CAJAS vwc  WITH (NOLOCK)ON vwc.NRO_CAJA = rs.CAJA_DESTINO
											AND vwc.SUCURSAL = CAST(rs.DESTINO AS int) 
											AND (vwc.MINIFILIAL > 0) OR (rs.CAJA_DESTINO = 999)
WHERE ((rs.TZ_LOCK < 300000000000000 OR rs.TZ_LOCK >= 400000000000000) 
AND (rs.TZ_LOCK < 100000000000000 OR rs.TZ_LOCK >= 200000000000000))
')