------------------------
--AJUSTE DE PARAMETRÍA--
------------------------
TRUNCATE TABLE CLE_ZONAS_CLEARING
--
INSERT INTO CLE_ZONAS_CLEARING (TZ_LOCK, ZONAS_CLEARING, DESCRIPCION)
VALUES (0, 0, 'CLEARING DEFAULT')
----
TRUNCATE TABLE CLE_CAMARAS_COMPENSADORAS
--
INSERT INTO CLE_CAMARAS_COMPENSADORAS (CODIGO_DE_CAMARA, NOMBRE, DIRECCION, CENTRO_DE_CANJE, CORRESPONSAL_DE_CLEARING, SUCURSAL_CORRESPONSAL, TIPO_DE_CONFIRMACION, PLAZO_DE_CONFIRMACION, TIPO_DE_INTERFASE, TZ_LOCK, IMPORTE_TRUNCAMIENTO, CANJE_CON_IMAGENES, COD_CAMARA_BC_MN, COD_CAMARA_BC_ME)
VALUES (1, 'CAMARA FEDERAL UNIFORME', 'Buenos Aires', 0, NULL, 50, NULL, NULL, NULL, 0, 80000, 'S', 1, 1)
----
TRUNCATE TABLE CLE_CENTROS_DE_CANJE
--
INSERT INTO CLE_CENTROS_DE_CANJE (CODIGO_CENTRO_DE_CANJE, NOMBRE, SUCURSAL, CAMARA_COMPENSADORA, CORRESPONSAL_DE_CLEARING, TZ_LOCK)
VALUES (0, 'DEFAULT', 1, 0, 0, 0)
----
TRUNCATE TABLE CLE_ZONAS_CAMARAS
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 7, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 15, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 16, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 34, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 72, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 147, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 299, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 309, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 330, 0, 1, 2, NULL)
--
INSERT INTO dbo.CLE_ZONAS_CAMARAS (TZ_LOCK, ZONA_CLEARING, BANCO, SUCURSAL, CAMARA, PLAZO_COMPENSACION, PLAZO_PRESENTACION)
VALUES (0, 0, 341, 0, 1, 2, NULL)
----



