EXECUTE('
----
IF OBJECT_ID (''dbo.VW_DOCUMENTOS_PJ'') IS NOT NULL
	DROP VIEW dbo.VW_DOCUMENTOS_PJ
----
')
EXECUTE('
----
CREATE   VIEW [dbo].[VW_DOCUMENTOS_PJ] (
										[Tipo Documento Identificativo], 
										[Número de Documento Identificativo], 
										[Razón Social],
										[Tipo Persona],  
										[Nivel de Apertura], 
										[Estado de la Persona],
										[Motivo Inhabilitado], 
										[Número de la Persona])
AS 
SELECT TOP 9223372036854775807 WITH TIES 
	V.TIPODOCUMENTO, 
	V.NUMERODOCUMENTO, 
	T.RAZONSOCIAL, 
	V.TIPOPERSONA, 
	OA.DESCRIPCION AS NIVELAPERTURA,       
	OE.DESCRIPCION AS ESTADO,        	
	OM.DESCRIPCION AS MOTIVO_INHABILITADO,
	V.NUMEROPERSONAFJ
FROM dbo.CLI_PERSONASJURIDICAS  AS T WITH (NOLOCK)
INNER JOIN dbo.CLI_DOCUMENTOSPFPJ  AS V WITH (NOLOCK)ON  T.NUMEROPERSONAJURIDICA = V.NUMEROPERSONAFJ 
													AND V.TIPOPERSONA = ''J'' 
													AND (	(T.TZ_LOCK < 300000000000000 OR T.TZ_LOCK >= 400000000000000) 
														AND (T.TZ_LOCK < 100000000000000 OR T.TZ_LOCK >= 200000000000000)) 
													AND (	(V.TZ_LOCK < 300000000000000 OR V.TZ_LOCK >= 400000000000000) 
														AND (V.TZ_LOCK < 100000000000000 OR V.TZ_LOCK >= 200000000000000))
LEFT JOIN OPCIONES AS OA WITH (NOLOCK) ON
	OA.NUMERODECAMPO = 2045
	AND OA.IDIOMA = ''E''
	AND OA.OPCIONINTERNA = T.NIVEL_APERTURA
LEFT JOIN OPCIONES AS OE WITH (NOLOCK) ON
	OE.NUMERODECAMPO = 33367
	AND OE.IDIOMA = ''E''
	AND OE.OPCIONINTERNA = T.ESTADO
LEFT JOIN OPCIONES AS OM WITH (NOLOCK) ON
	OM.NUMERODECAMPO = 33369
	AND OM.IDIOMA = ''E''
	AND OM.OPCIONINTERNA = T.MOTIVO_INHABILITADO
ORDER BY NUMEROPERSONAFJ;
----
')

