


-- Parche_NUPAGSEGUR_211

-- NUPAGSEGUR-211

-- Adding concept number 2740
INSERT INTO CONCEPTOS (CODIGO, DESCRIPCION, CAMPOV25)
VALUES (2740, 'ASIENTO_FECHA_INIT', 0);

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES ('3684', ' ', 0, 'Asiento fecha inicio', 'Asiento fecha inicio', 8, 'F', 0, 'F', 0, 2740, 0, 0, 0, 0, 0, 0, NULL, 0, NULL);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20211130_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVVBBR1NFR1VSXzIxMQoNCi0tIE5VUEFHU0VHVVItMjExCg0KLS0gQWRk
aW5nIGNvbmNlcHQgbnVtYmVyIDI3NDANCklOU0VSVCBJTlRPIENPTkNFUFRPUyAoQ09ESUdPLCBE
RVNDUklQQ0lPTiwgQ0FNUE9WMjUpClZBTFVFUyAoMjc0MCwgJ0FTSUVOVE9fRkVDSEFfSU5JVCcs
IDApOwoKSU5TRVJUIElOVE8gRElDQ0lPTkFSSU8gKE5VTUVST0RFQ0FNUE8sIFVTT0RFTENBTVBP
LCBSRUZFUkVOQ0lBLCBERVNDUklQQ0lPTiwgUFJPTVBULCBMQVJHTywgVElQT0RFQ0FNUE8sIERF
Q0lNQUxFUywgRURJQ0lPTiwgQ09OVEFCSUxJWkEsIENPTkNFUFRPLCBDQUxDVUxPLCBWQUxJREFD
SU9OLCBUQUJMQURFVkFMSURBQ0lPTiwgVEFCTEFERUFZVURBLCBPUENJT05FUywgVEFCTEEsIENB
TVBPLCBCQVNJQ08sIE1BU0NBUkEpClZBTFVFUyAoJzM2ODQnLCAnICcsIDAsICdBc2llbnRvIGZl
Y2hhIGluaWNpbycsICdBc2llbnRvIGZlY2hhIGluaWNpbycsIDgsICdGJywgMCwgJ0YnLCAwLCAy
NzQwLCAwLCAwLCAwLCAwLCAwLCAwLCBOVUxMLCAwLCBOVUxMKTsKDQoKCg0K', NULL, 0);
