EXECUTE('

INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (2000, 2623, ''Balance de Comprobación'', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (2000, 2624, ''Balance de Comprobación al Mes'', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (2624, 1, NULL, 0, 0, 1)

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (2623, 1, NULL, 0, 0, 1)


')