EXECUTE('
INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO, DEBITO_CREDITO)
VALUES (0, 3040, ''DEBITO COBRO TC MASTERCARD'', ''N'', NULL, '' '', ''S'', 0, NULL, NULL)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO, DEBITO_CREDITO)
VALUES (0, 3041, ''DEBITO COBRO TC CABAL'', ''N'', NULL, '' '', ''S'', 0, NULL, NULL)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO, DEBITO_CREDITO)
VALUES (0, 3042, ''DEBITO COBRO TC VISA'', ''N'', NULL, '' '', ''S'', 0, NULL, NULL)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO, DEBITO_CREDITO)
VALUES (0, 3043, ''DEBITO COBRO TC TUYA'', ''N'', NULL, '' '', ''S'', 0, NULL, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2854, 1, 3040, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2854, 2, 3041, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2854, 3, 3042, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2854, 8, 3043, 0)
')