EXECUTE('
----------------------------
--MODIFICACIONES NUMERADOR--
----------------------------
--UPDATE NUMERATORDEFINITION
--SET INIVAL = 1
--WHERE NUMERO = 6029
-----------------------------------
--ELIMINO NUMERADOR 34738 Y CAMPO--
-----------------------------------
DELETE FROM NUMERATORASIGNED WHERE OID IN (SELECT OID FROM NUMERATORVALUES WHERE NUMERO = 34738)
--
DELETE FROM NUMERATORVALUES WHERE NUMERO = 34738
--
DELETE FROM NUMERATORDEFINITION WHERE NUMERO = 34738
--
DELETE FROM DICCIONARIO
WHERE NUMERODECAMPO = 34738
----
')