EXECUTE('
ALTER VIEW [dbo].[VW_ITF_PEP_DOCS] ( 
											   NUMEROPERSONAFJ, 
											   TIPODOCUMENTO, 
											   NUMERODOCUMENTO, 
											   TIPOPERSONA,
											   NOMBRE)
AS
SELECT
	PF.NUMEROPERSONAFISICA,
	DF.TIPODOCUMENTO,
	DF.NUMERODOCUMENTO,
	DF.TIPOPERSONA,
	UPPER(PF.APELLIDOPATERNO + '' '' + PF.PRIMERNOMBRE)
		
	
FROM CLI_DocumentosPFPJ DF WITH (NOLOCK)
INNER JOIN CLI_PERSONASFISICAS PF WITH (NOLOCK)ON  DF.TIPOPERSONA = ''F'' 
											AND DF.TIPODOCUMENTO = ''CUIL'' 
											AND DF.NUMEROPERSONAFJ = PF.NUMEROPERSONAFISICA
WHERE PF.TZ_LOCK = 0 AND DF.TZ_LOCK = 0 

UNION ALL

	SELECT
	PJ.NUMEROPERSONAJURIDICA,
	DJ.TIPODOCUMENTO,
	DJ.NUMERODOCUMENTO,
	DJ.TIPOPERSONA,
	UPPER(PJ.RAZONSOCIAL)
	
FROM CLI_DocumentosPFPJ DJ WITH (NOLOCK)
INNER JOIN CLI_PERSONASJURIDICAS PJ WITH (NOLOCK)ON  DJ.TIPOPERSONA = ''J'' 
												AND DJ.TIPODOCUMENTO = ''CUIT'' 
												AND DJ.NUMEROPERSONAFJ = PJ.NUMEROPERSONAJURIDICA
WHERE PJ.TZ_LOCK = 0 AND DJ.TZ_LOCK = 0 
')