EXECUTE ('

INSERT INTO dbo.NUMERATORVALUES (DIA, MES, ANIO, SUCURSAL, NUMERO, VALOR)
VALUES (0, 0, 0, 0, 35395, ''300'')


INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (35395, 300, 1, '' '', NULL, 1, 1, 0, ''Numerador cta TriSupJus'', ''T'')

')

