EXECUTE('
UPDATE REPORTES
SET TIPO = ''J''
WHERE TITULO = 2000 AND IDENTIFICACION = 7656
')
EXECUTE('
DELETE FROM dbo.REPORTESJASPER
WHERE IDENTIFICACION = 7656
')
EXECUTE('
INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (7656, 1, NULL, 1, 0, 1)
')
