EXECUTE('
--DICCIONARIO

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 58406

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (58406, '' '', 0, ''Marca aceptacion cheq propio'', ''Marca aceptacion cheq propio'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL)

')