EXECUTE ('
CREATE OR ALTER VIEW [dbo].[VW_INTEGRANTESPJ] (
												[Tipo Documento Identificativo], 
												[Número Documento Identificativo],
												[Tipo Documento Físico],
												[Número Documento Físico],
												[Razón Social/Nombre],
												[Tipo Persona], 
												[Nivel de Apertura],
												[Estado Persona],
												[Motivo Inhabilitado],
												[Persona Jurídica],
												[Integrante PJ],
												[Tipo Vinculación],
												[Cargo]
												)
AS 
  (	SELECT TOP 1000000000
		  V.TIPODOCUMENTO , 
		  V.NUMERODOCUMENTO ,
		  V.TIPO_DOC_FISICO,
		  V.NUM_DOC_FISICO,
		  (U.RAZONSOCIAL) AS RAZONSOCIAL,
		  V.TIPOPERSONA ,  
		  (	SELECT DESCRIPCION 
			FROM OPCIONES O WITH (NOLOCK) 
			WHERE O.IDIOMA=''E'' 
				AND O.OPCIONINTERNA=U.NIVEL_APERTURA 
				AND O.NUMERODECAMPO = 2203) AS NIVEL_APERTURA,
		  (	SELECT DESCRIPCION 
			FROM OPCIONES O WITH (NOLOCK) 
			WHERE O.IDIOMA=''E'' 
			AND O.OPCIONINTERNA=U.ESTADO 
			AND O.NUMERODECAMPO = 33367) AS ESTADO,   
		  (	SELECT DESCRIPCION 
			FROM OPCIONES O WITH (NOLOCK) 
			WHERE O.IDIOMA=''E'' 
			AND O.OPCIONINTERNA=U.MOTIVO_INHABILITADO 
			AND O.NUMERODECAMPO = 33369) AS  MOTIVO_INHABILITADO,
		  I.NUMEROPERSONAJURIDICA,
          I.NUMEROPERSONAFISICA,
		  (	SELECT DESCRIPCION 
			FROM OPCIONES O WITH (NOLOCK) 
			WHERE O.IDIOMA=''E'' 
			AND O.OPCIONINTERNA=I.TIPOVINCULACION 
			AND O.NUMERODECAMPO = 1212) AS  TIPOVINCULACION,
		  (	SELECT CARGO 
			FROM dbo.CLI_CARGOS_PERSONAS C WITH (NOLOCK) 
			WHERE C.CODIGO=I.CODIGOCARGO ) AS  CARGO
       
	FROM dbo.CLI_PERSONASJURIDICAS  AS U WITH (NOLOCK)
	INNER JOIN dbo.CLI_INTEGRANTESPJ AS I WITH (NOLOCK)ON I.NUMEROPERSONAFISICA = U.NUMEROPERSONAJURIDICA
														AND I.TZ_LOCK =0
	INNER JOIN dbo.CLI_DOCUMENTOSPFPJ  AS V WITH (NOLOCK)ON I.NUMEROPERSONAFISICA = V.NUMEROPERSONAFJ
														AND V.TIPOPERSONA = ''J''
		   WHERE 
		   (U.TZ_LOCK < 300000000000000 or U.TZ_LOCK >= 400000000000000) 
		   and (U.TZ_LOCK < 100000000000000 or U.TZ_LOCK >= 200000000000000)
	       AND (V.TZ_LOCK < 300000000000000 or V.TZ_LOCK >= 400000000000000) 
	       and (V.TZ_LOCK < 100000000000000 or V.TZ_LOCK >= 200000000000000)												
   )
UNION ALL
  ( SELECT TOP 1000000000
      V.TIPODOCUMENTO , 
      V.NUMERODOCUMENTO ,
      V.TIPO_DOC_FISICO,
      V.NUM_DOC_FISICO,
      (F.APELLIDOPATERNO + '' '' + F.PRIMERNOMBRE) AS NOMBRES,
      V.TIPOPERSONA ,  
      (	SELECT DESCRIPCION 
		FROM OPCIONES O WITH (NOLOCK) 
		WHERE O.IDIOMA=''E'' 
		AND O.OPCIONINTERNA=F.NIVEL_APERTURA 
		AND O.NUMERODECAMPO = 2203) AS NIVEL_APERTURA,
      (	SELECT DESCRIPCION 
		FROM OPCIONES O WITH (NOLOCK) 
		WHERE O.IDIOMA=''E'' 
		AND O.OPCIONINTERNA=F.ESTADO 
		AND O.NUMERODECAMPO = 33366) AS ESTADO,   
	  (	SELECT DESCRIPCION 
		FROM OPCIONES O WITH (NOLOCK) 
		WHERE O.IDIOMA=''E'' 
		AND O.OPCIONINTERNA=F.MOTIVO_INHABILITADO 
		AND O.NUMERODECAMPO = 33368) AS  MOTIVO_INHABILITADO,
      I.NUMEROPERSONAJURIDICA,
      I.NUMEROPERSONAFISICA,
      (	SELECT DESCRIPCION 
		FROM OPCIONES O WITH (NOLOCK) 
		WHERE O.IDIOMA=''E'' 
		AND O.OPCIONINTERNA=I.TIPOVINCULACION 
		AND O.NUMERODECAMPO = 1212) AS  TIPOVINCULACION,
      (	SELECT CARGO 
		FROM dbo.CLI_CARGOS_PERSONAS C WITH (NOLOCK) 
		WHERE C.CODIGO=I.CODIGOCARGO ) AS  CARGO 
   FROM dbo.CLI_PERSONASFISICAS  AS F WITH (NOLOCK)
   INNER JOIN dbo.CLI_INTEGRANTESPJ AS I WITH (NOLOCK)ON I.NUMEROPERSONAFISICA = F.NUMEROPERSONAFISICA
													   	AND I.TZ_LOCK =0 
   INNER JOIN dbo.CLI_DOCUMENTOSPFPJ  AS V WITH (NOLOCK)ON I.NUMEROPERSONAFISICA = V.NUMEROPERSONAFJ
														AND V.TIPOPERSONA = ''F''
													   
        WHERE 
        (F.TZ_LOCK < 300000000000000 or F.TZ_LOCK >= 400000000000000) 
        and (F.TZ_LOCK < 100000000000000 or F.TZ_LOCK >= 200000000000000)
	    AND (V.TZ_LOCK < 300000000000000 or V.TZ_LOCK >= 400000000000000) 
	    and (V.TZ_LOCK < 100000000000000 or V.TZ_LOCK >= 200000000000000)
   
   )

')