
EXECUTE('
DELETE FROM DESCRIPTORES WHERE IDENTIFICACION =  3548

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3548, NULL, ''Vista Cheques Rechazados PA'', 0, ''VW_CLE_CHEQUES_RECHAZADOS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

DELETE FROM DICCIONARIO WHERE TABLA = 3548

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35702, '' '', 0, ''MICRLINE'', ''MICRLINE'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''MICRLINE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35703, '' '', 0, ''NUMERO_SERIE'', ''NUMERO_SERIE'', 6, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''NUMERO_SERIE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35704, '' '', 0, ''NUMERO_CHEQUE'', ''NUMERO_CHEQUE'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''NUMERO_CHEQUE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35705, '' '', 0, ''CUENTA'', ''CUENTA'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35706, '' '', 0, ''SUCURSAL'', ''SUCURSAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35707, '' '', 0, ''MONEDA'', ''MONEDA'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''MONEDA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35708, '' '', 0, ''PRODUCTO'', ''PRODUCTO'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3548, ''PRODUCTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35709, '' '', 0, ''FECHA'', ''FECHA'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3548, ''FECHA'', 0, NULL)

DELETE FROM INDICES WHERE NUMERODEARCHIVO = 3548

INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3548, 1, ''PK'', 0, 35702, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

')