EXECUTE('
INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (6650, 9021, ''Minuta Informativa (Pág1)'', '' '', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (6650, 9022, ''Minuta Informativa (Pág2)'', ''C'', 0, NULL, 0, 0, 0, ''N'')
')

