


-- Patch_NUNBCHACO_841

-- Patch_NUNBCHACO_841

-- Se modifica la tabla HISTORICO_CALIF_X_SALDO agregando un nuevo campo ORIGEN
ALTER TABLE HISTORICO_CALIF_X_SALDO ADD ORIGEN VARCHAR(2) DEFAULT 'A';




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20211207_2NBCHAR',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VTkJDSEFDT184NDEKDQotLSBQYXRjaF9OVU5CQ0hBQ09fODQxCg0KLS0g
U2UgbW9kaWZpY2EgbGEgdGFibGEgSElTVE9SSUNPX0NBTElGX1hfU0FMRE8gYWdyZWdhbmRvIHVu
IG51ZXZvIGNhbXBvIE9SSUdFTg0KQUxURVIgVEFCTEUgSElTVE9SSUNPX0NBTElGX1hfU0FMRE8g
QUREIE9SSUdFTiBWQVJDSEFSKDIpIERFRkFVTFQgJ0EnCiAgICAgICAgICAgIEdPOwoNCgoKDQo=', NULL, 0);
