EXECUTE('
-------------------------------
--NUEVO DESCRIPTOR PARA VISTA--
-------------------------------
INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (50, 3507, NULL, ''Vista de Firmas de Personas'', 0, ''VW_CLI_PERSONAS_FIRMAS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35072, '' '', 0, ''Tipo Documento'', ''Tipo Documento'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''TIPO_DOC'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35073, '' '', 0, ''Número Documento'', ''Nro. Documento'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''NRO_DOC'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35074, '' '', 0, ''Número de Persona'', ''Nro. Persona Física'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''NRO_PERSONA'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35075, '' '', 0, ''Nombre y Apellido'', ''Nombre y Apellido'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''NOMBRE_APELLIDO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35076, '' '', 0, ''Número de Firma'', ''Nro. de Firma'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''NRO_FIRMA'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35077, '' '', 0, ''Fecha de Vencimiento'', ''Fecha de Vencimiento'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3507, ''VENCIMIENTO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35078, '' '', 0, ''Usuario Autorizador'', ''Usuario Autorizador'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3507, ''AUTORIZADOR'', 0, NULL)
----
INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3507, 1, ''índice Firmas de Personas'', 0, 35074, 35076, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3507, 35071, ''Listado de Firmas de Personas'', '''', 0, ''35072;35073;35074ROA1;35075;35076ROA2;35077;35078;'', NULL, NULL, NULL, 0)
----
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35079, '' '', 0, ''Listado de Firmas de Personas'', ''Listado de Firmas de Personas'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 35071, 0, 0, NULL, 0, NULL)
----
')