execute('
ALTER TABLE ITF_ACREDITACION_BITACORA
ADD CAUSAL VARCHAR(10) DEFAULT('' '') NULL

DECLARE @constrainName NVARCHAR(255);
DECLARE @query NVARCHAR(MAX);
   SELECT 
       @constrainName = dc.name 
   FROM 
       sys.default_constraints AS dc
       INNER JOIN sys.tables AS t
           ON dc.parent_object_id = t.object_id
       INNER JOIN sys.columns AS c
           ON dc.parent_object_id = c.object_id 
           AND dc.parent_column_id = c.column_id
   WHERE 
       t.name = ''ITF_ACREDITACION_BITACORA''
       AND c.name = ''SATELITE'';

SET @query = ''ALTER TABLE ITF_ACREDITACION_BITACORA
DROP CONSTRAINT ''+@constrainName
EXEC sp_executesql @query
   
ALTER TABLE ITF_ACREDITACION_BITACORA
ALTER COLUMN SATELITE VARCHAR(10)

ALTER TABLE ITF_ACREDITACION_BITACORA
ADD DEFAULT('' '') FOR SATELITE;

UPDATE dbo.DICCIONARIO
SET LARGO = 10
	, TIPODECAMPO = ''A''
WHERE NUMERODECAMPO = 41280

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41286, '' '', 0, ''CAUSAL'', ''Causal'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 849, ''CAUSAL'', 0, NULL)

EXEC sp_rename ''ITF_ACREDITACION_BITACORA.JTS_OID'',''SALDOS_JTS_OID'',''COLUMN''

UPDATE dbo.DICCIONARIO
SET CAMPO = ''SALDOS_JTS_OID''
WHERE NUMERODECAMPO = 41281
')