EXECUTE('
--------------------------------
--AJUSTE CAMPO SEGMENTO CREDEB--
--------------------------------
UPDATE dbo.CI_CARGOS_X_EVENTO
SET CAMPO_SEGMENTO = 34096
	, DESCRIPCION_SEGMENTO = ''CONDICIÓN CREDEB''
WHERE ID_CARGO = 401 AND ID_EVENTO = 1413
---- 
UPDATE dbo.CI_CARGOS_X_EVENTO
SET CAMPO_SEGMENTO = 34096
	, DESCRIPCION_SEGMENTO = ''CONDICIÓN CREDEB''
WHERE ID_CARGO = 401 AND ID_EVENTO = 2214
---- 
UPDATE dbo.CI_CARGOS_X_EVENTO
SET CAMPO_SEGMENTO = 34096
	, DESCRIPCION_SEGMENTO = ''CONDICIÓN CREDEB''
WHERE ID_CARGO = 401 AND ID_EVENTO = 2215
----
')