EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (24560, '''', 0, ''SALDO_JTS_OID_ORIGEN'', ''SALDO_JTS_OID_'', 15, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 296, ''SALDO_JTS_OID_ORIGEN'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (24561, '''', 0, ''FECHA_ENVIADO'', ''FECHA_ENVIADO'', 8, ''F'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 296, ''FECHA_ENVIADO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (24562, '''', 0, ''ESTADO_ENVIADO'', ''ESTADO_ENVIADO'', 1, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 296, ''ESTADO_ENVIADO'', 0, '''')

')