--FORMULA SAMEEP

EXECUTE('IF EXISTS (SELECT * FROM AYUDAS WHERE NUMERODEAYUDA = 44511)
BEGIN

 DELETE FROM AYUDAS WHERE NUMERODEAYUDA = 44511;
 
INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4451, 44511, ''Ayuda PRESTACIONES EMPRESAS'', '''', 0, ''44507R;44508R;44502;44510;44511;44512;44513;44514;44515;'', NULL, NULL, NULL, 0)


END
ELSE
BEGIN

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4451, 44511, ''Ayuda PRESTACIONES EMPRESAS'', '''', 0, ''44507R;44508R;44502;44510;44511;44512;44513;44514;44515;'', NULL, NULL, NULL, 0)

END


IF EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO IN (44507))
BEGIN

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN (44507)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44507, '' '', 0, ''CUIT Empresa Originante'', ''Cuit:'', 11, ''N'', 0, NULL, 0, 0, 0, 0, 0, 44511, 0, 4451, ''CUIT_EO'', 0, NULL)



END
ELSE
BEGIN

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44507, '' '', 0, ''CUIT Empresa Originante'', ''Cuit:'', 11, ''N'', 0, NULL, 0, 0, 0, 0, 0, 44511, 0, 4451, ''CUIT_EO'', 0, NULL)

END


IF EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO IN (44516))
BEGIN

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN (44516)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44516, '' '', 0, ''Fecha Alta'', ''Fecha Alta:'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4451, ''FECHA_ALTA'', 0, NULL)



END
ELSE
BEGIN

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44516, '' '', 0, ''Fecha Alta'', ''Fecha Alta:'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4451, ''FECHA_ALTA'', 0, NULL)

END

IF EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO IN (44514))
BEGIN

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN (44514)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44514, '' '', 0, ''Tipo Comisión'', ''Tipo Comisión:'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4451, ''TIPO_COMISION'', 0, NULL)



END
ELSE
BEGIN

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44514, '' '', 0, ''Tipo Comisión'', ''Tipo Comisión:'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4451, ''TIPO_COMISION'', 0, NULL)

END


')