execute('
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37409, '' '', 0, ''Codigo Postal Exterior'', ''Codigo Postal Exterior'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3302, ''CP_EXTERIOR'', 0, NULL)
 
--
ALTER TABLE CLI_DIRECCIONES ADD CP_EXTERIOR VARCHAR (10);

--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37410, '' '', 0, ''Codigo Postal Exterior'', ''Codigo Postal Exterior'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3340, ''CP_EXTERIOR'', 0, NULL)

--
ALTER TABLE BITACORA_DIRECCIONES ADD CP_EXTERIOR VARCHAR (10);


--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37411, '' '', 0, ''Codigo Postal Exterior'', ''Codigo Postal Exterior'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''CP_EXTERIOR'', 0, NULL)

')