EXECUTE('
Delete from AYUDAS where NUMERODEAYUDA in (8521,90819,90820,34556);
Delete from DICCIONARIO where NUMERODECAMPO in (41104,41169,41334,41166);
Delete from INDICES where NUMERODEARCHIVO in (835,836,852);
')

EXECUTE('

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (852, 8521, ''Ayuda ITF_MASTER_SATELITES'', '''', 0, ''41331R;41332;41333;'', NULL, NULL, NULL, 0);


INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (835, 90819, ''Ayuda ITF_MASTER_CAUSALES'', '''', 0, ''41284R;41158R;41159;41160;41161;41286;41162;41164;41163;41294;'', NULL, NULL, NULL, 0);


INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (836, 90820, ''Ayuda ITF_MASTER_CARGOS'', '''', 0, ''41285R;41165R;41295;41167;'', NULL, NULL, NULL, 0);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41104, '' '', 0, ''Ayuda ITF_MASTER_CANALES'', NULL, 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 90819, 0, 0, ''C41104'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41169, '' '', 0, ''Ayuda ITF_MASTER_CARGOS'', NULL, 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 90820, 0, 0, ''C41169'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41334, '' '', 0, ''Ayuda ITF_MASTER_SATELITES'', NULL, 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 8521, 0, 0, ''C41334'', 0, NULL);

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (835, 1, ''Indice Primario'', 0, 41284, 41158, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (836, 1, ''Indice Primario'', 0, 41285, 41165, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (852, 1, ''Indice ITF_MASTER_SATELITES'', 0, 41331, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41166, '' '', 0, ''Ayuda VW_CODIGO_TRANSACCIONES'', ''Ayuda Codigo Transacciones'', 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34556, 0, 0, ''COD_TRANSACCIONES'', 0, NULL);


INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 34556, ''VW_CODIGO_TRANSACCIONES'', '''', 0, ''2631;199R;3920;'', ''Operacion;Codigo_Interno;Descripcion;'', ''TOP/CLIENTES'', ''VW_CODIGO_TRANSACCIONES'', 0)



')