EXECUTE('
----
CREATE TABLE CLE_DPF_RECIBIDO (
	TZ_LOCK numeric(15,0) DEFAULT 0 NOT NULL,
	MONEDA numeric(4,0) DEFAULT 0 NOT NULL,
	NUMERO_DPF numeric(12,0) DEFAULT 0 NOT NULL,
	CLIENTE numeric(12,0) DEFAULT 0 NOT NULL,
	NUMERICO_CUENTA numeric(12,0) DEFAULT 0 NOT NULL,
	PRODUCTO numeric(5,0) NOT NULL,
	OPERACION numeric(12,0) NOT NULL,
	ORDINAL numeric(6,0) DEFAULT 0 NOT NULL,
	BANCO_DEPOSITANTE numeric(6,0) DEFAULT 0 NOT NULL,
	CODIGO_USUARIO varchar(10) COLLATE Modern_Spanish_CI_AS DEFAULT '' '' NULL,
	FECHA_VALOR datetime NOT NULL,
	IMPORTE numeric(15,2) DEFAULT 0 NULL,
	ESTADO numeric(4,0) DEFAULT 0 NULL,
	NUMERO_DEPENDENCIA numeric(5,0) DEFAULT 0 NOT NULL,
	TRACKNUMBER varchar(20) COLLATE Modern_Spanish_CI_AS NULL,
	ESTADO_DPF varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	BANDA varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	CODIGO_CAUSAL_RECHAZO numeric(2,0) NULL,
	CONSTRAINT PK_CLE_DPF_RECIBIDO_01 PRIMARY KEY (MONEDA,NUMERICO_CUENTA,PRODUCTO,NUMERO_DEPENDENCIA,OPERACION,ORDINAL,NUMERO_DPF,FECHA_VALOR)
);
----
')
