


-- Parche_NUNBCHACO_1303

IF OBJECT_ID ('dbo.CO_AJUSTE_X_INFLACION') IS NOT NULL
DROP TABLE dbo.CO_AJUSTE_X_INFLACION;

CREATE TABLE dbo.CO_AJUSTE_X_INFLACION
(
RUBRO_ORIGEN      NUMERIC (15) DEFAULT ((0)) NOT NULL,
MONEDA            VARCHAR (1) NOT NULL,
RUBRO_DESTINO     NUMERIC (15) DEFAULT ((0)),
RUBRO_PATRIMONIAL NUMERIC (15) DEFAULT ((0)),
TIPO_INDICE       NUMERIC (2) DEFAULT ((0)),
TZ_LOCK           NUMERIC (15) DEFAULT ((0)) NOT NULL,
MONETARIO         VARCHAR (1),
CONSTRAINT CLAVE_PRIMARIA PRIMARY KEY (RUBRO_ORIGEN, MONEDA)
);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20230712_1NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fMTMwMwoNCklGIE9CSkVDVF9JRCAoJ2Riby5DT19BSlVT
VEVfWF9JTkZMQUNJT04nKSBJUyBOT1QgTlVMTApEUk9QIFRBQkxFIGRiby5DT19BSlVTVEVfWF9J
TkZMQUNJT047CgpDUkVBVEUgVEFCTEUgZGJvLkNPX0FKVVNURV9YX0lORkxBQ0lPTgooClJVQlJP
X09SSUdFTiAgICAgIE5VTUVSSUMgKDE1KSBERUZBVUxUICgoMCkpIE5PVCBOVUxMLApNT05FREEg
ICAgICAgICAgICBWQVJDSEFSICgxKSBOT1QgTlVMTCwKUlVCUk9fREVTVElOTyAgICAgTlVNRVJJ
QyAoMTUpIERFRkFVTFQgKCgwKSksClJVQlJPX1BBVFJJTU9OSUFMIE5VTUVSSUMgKDE1KSBERUZB
VUxUICgoMCkpLApUSVBPX0lORElDRSAgICAgICBOVU1FUklDICgyKSBERUZBVUxUICgoMCkpLApU
Wl9MT0NLICAgICAgICAgICBOVU1FUklDICgxNSkgREVGQVVMVCAoKDApKSBOT1QgTlVMTCwKTU9O
RVRBUklPICAgICAgICAgVkFSQ0hBUiAoMSksCkNPTlNUUkFJTlQgQ0xBVkVfUFJJTUFSSUEgUFJJ
TUFSWSBLRVkgKFJVQlJPX09SSUdFTiwgTU9ORURBKQopOwoNCgoKDQo=', NULL, 0);
