EXECUTE('
IF OBJECT_ID (''dbo.CRE_PAGO_DOMICILIO'') IS NOT NULL
	DROP TABLE dbo.CRE_PAGO_DOMICILIO
')

EXECUTE('
CREATE TABLE dbo.CRE_PAGO_DOMICILIO
	(
	TZ_LOCK     NUMERIC (15) DEFAULT ((0)),
	JTS_OID_CTA NUMERIC (10),
	ID_SOPORTE  NUMERIC (10) NOT NULL,
	ORDINAL_DET NUMERIC (10) NOT NULL,
	ANIO 		VARCHAR (4),
	MES			VARCHAR (2),
	CUIL		VARCHAR (20),
	NRO_RECIBO  VARCHAR (8),
	ID_DIR		NUMERIC (10),
	TIPO_DIR	VARCHAR (2),
	FORMATODIR	VARCHAR (2),
	ORDINALDIR  NUMERIC (3),
	IMPORTE		NUMERIC (15,2),
	CONSTRAINT PK_PAGO_DOMICILIO PRIMARY KEY (ID_SOPORTE, ORDINAL_DET)
	)
')

EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (7000, 7010, NULL, ''CRE_PAGO_DOMICILIO'', 0, ''CRE_PAGO_DOMICILIO'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70100, '' '', 0, ''JTS OID cuenta'', ''JTS OID cuenta'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''JTS_OID_CTA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70101, '' '', 0, ''ID Soporte'', ''ID Soporte'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''ID_SOPORTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70102, '' '', 0, ''Ordinal detalle'', ''Ordinal detalle'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''ORDINAL_DET'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70103, '' '', 0, ''Anio'', ''Anio'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''ANIO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70104, '' '', 0, ''Mes'', ''Mes'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''MES'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70105, '' '', 0, ''CUIL'', ''CUIL'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''CUIL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70106, '' '', 0, ''Nro recibo'', ''Nro recibo'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''NRO_RECIBO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70107, '' '', 0, ''ID Direccion'', ''ID Direccion'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''ID_DIR'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70108, '' '', 0, ''Tipo direccion'', ''Tipo Direccion'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''TIPO_DIR'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70109, '' '', 0, ''Formato direccion'', ''Formato direccion'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''FORMATODIR'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70110, '' '', 0, ''Ordinal direccion'', ''Ordinal direccion'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''ORDINALDIR'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70111, '' '', 0, ''Importe'', ''Importe'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 7010, ''IMPORTE'', 0, NULL)

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (7010, 1, ''Indice'', 0, 70101, 70102, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
')

