Execute('
ALTER TABLE ITF_CONVENIOS_SACHEEP_SAMEEP ALTER COLUMN Importe_primer_vencimiento NUMERIC(16,2);
ALTER TABLE ITF_CONVENIOS_SACHEEP_SAMEEP ALTER COLUMN Importe_segundo_vencimiento NUMERIC(16,2);')
