EXECUTE('
IF OBJECT_ID (''dbo.VW_EXCLUSIONES_CLIENTES'') IS NOT NULL
	DROP VIEW dbo.VW_EXCLUSIONES_CLIENTES
')

EXECUTE('
CREATE   VIEW [dbo].[VW_EXCLUSIONES_CLIENTES]
							([Código de Cliente],
							Nombre,
							[Graduación],
							[Identificador Graduación]
							)
AS
SELECT C.CODIGOCLIENTE,
D.NOMBRECLIENTE, 
TE.DETALLE AS GRADUACION,
TE.ID_EXCLUSION
FROM CRE_EXCLUSIONES_CLIENTES C WITH(NOLOCK)
INNER JOIN CRE_TIPO_EXCLUSION TE WITH (NOLOCK) ON C.GRADUACION=TE.ID_EXCLUSION
INNER JOIN VW_CLI_X_DOC D WITH(NOLOCK) ON C.CODIGOCLIENTE = D.CODIGOCLIENTE
WHERE C.TZ_LOCK = 0

')