Execute('
DROP TABLE IF EXISTS REC_EXT_RECAUDOS_CANAL;
CREATE TABLE dbo.REC_EXT_RECAUDOS_CANAL
	(
	FORMATO     VARCHAR (15) DEFAULT ('' '') NOT NULL,
	FECHA       DATETIME NOT NULL,
	CORRELATIVO NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CADENA_01   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_02   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_03   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_04   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_05   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_06   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_07   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_08   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_09   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_10   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_11   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_12   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_13   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_14   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_15   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_16   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_17   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_18   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_19   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_20   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_21   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_22   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_23   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_24   VARCHAR (100) DEFAULT ('' '') NULL,
	CADENA_25   VARCHAR (100) DEFAULT ('' '') NULL,
	NRO_01      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_02      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_03      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_04      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_05      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_06      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_07      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_08      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_09      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_10      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_11      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_12      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_13      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_14      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	NRO_15      NUMERIC (15, 2) DEFAULT ((0)) NULL,
	FECHA_01    DATETIME NULL,
	FECHA_02    DATETIME NULL,
	FECHA_03    DATETIME NULL,
	FECHA_04    DATETIME NULL,
	FECHA_05    DATETIME NULL,
	TZ_LOCK     NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ID_CABEZAL  NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ID_LINEA    NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_REC_EXT_RECAUDOS_CANAL_01 PRIMARY KEY (ID_CABEZAL, ID_LINEA))')

Execute('CREATE  Or ALTER   PROCEDURE [dbo].[SP_ITF_CAJA_MUNICIPAL] @formato AS VARCHAR(20), @fch_proceso AS VARCHAR(8), @nomArchivo AS VARCHAR(15), @ticket AS VARCHAR(15)
AS
BEGIN
	--------------- DECLARO VRIABLES --------------- 						
	DECLARE @tabla NUMERIC(5,0) = 0;
	DECLARE @nro_ayuda NUMERIC(5,0) = 0;
	DECLARE @codEnte VARCHAR(15);
	DECLARE @convenio VARCHAR(15);
	DECLARE @convenioPadre VARCHAR(15);	
	DECLARE @descrEnte VARCHAR(50);
	DECLARE @CargoEspec NUMERIC(15,2);
	DECLARE @ID_CABEZAL NUMERIC(15,0) = 0;
	DECLARE @ID_LINEA NUMERIC(15,0) = 0;
	DECLARE @TZ_LOCK NUMERIC(15,0) = 0;
	DECLARE @TOT_IMPORTE NUMERIC(15,2);
	DECLARE @TOT_CARGO_ESPEC NUMERIC(15,2);
	
	DECLARE @CADENA_01 VARCHAR(100);
	DECLARE @CADENA_02 VARCHAR(100);
	DECLARE @CADENA_03 VARCHAR(100);
	DECLARE @CADENA_04 VARCHAR(100);
	DECLARE @CADENA_05 VARCHAR(100);
	DECLARE @CADENA_06 VARCHAR(100);
	DECLARE @CADENA_07 VARCHAR(100);				
	DECLARE @CADENA_08 VARCHAR(100);
	DECLARE @CADENA_09 VARCHAR(100);
	DECLARE @CADENA_10 VARCHAR(100);
	DECLARE @CADENA_11 VARCHAR(100);
	DECLARE @CADENA_12 VARCHAR(100);
	DECLARE @CADENA_13 VARCHAR(100);
	DECLARE @CADENA_14 VARCHAR(100);
	DECLARE @CADENA_15 VARCHAR(100);
	DECLARE @NRO_01 NUMERIC(15,2);
	DECLARE @NRO_02 NUMERIC(15,2);
	DECLARE @NRO_03 NUMERIC(15,2);
	DECLARE @NRO_04 NUMERIC(15,2);
	DECLARE @NRO_05 NUMERIC(15,2);
	DECLARE @NRO_06 NUMERIC(15,2);
	DECLARE @NRO_07 NUMERIC(15,2);
	DECLARE @NRO_08 NUMERIC(15,2);
	DECLARE @NRO_09 NUMERIC(15,2);
	DECLARE @NRO_10 NUMERIC(15,2);
	DECLARE @NRO_11 NUMERIC(15,2);
	DECLARE @FECHA_01 DATETIME;
	
	DECLARE @CANT_REG NUMERIC(10,0) = 0;
	------------------------------------------------		
	
	IF @formato = ''CM01''
	BEGIN
		DECLARE cursor_ayuda cursor FOR
			SELECT DISTINCT cadena_03 FROM REC_EXT_RECAUDOS_CANAL WHERE FORMATO = @formato AND FECHA = @fch_proceso AND ID_CABEZAL = @ticket;
		
		OPEN cursor_ayuda;
		FETCH NEXT FROM cursor_ayuda INTO @codEnte
		
		WHILE @@fetch_status = 0 
		BEGIN		
			SET @convenio = (SELECT ID_CONVREC FROM CONV_REL_ENTECONV WHERE TZ_LOCK = 0 AND COD_ENTE = @codEnte)
			SET @descrEnte = (SELECT DESC_ENTE FROM CONV_REL_ENTECONV WHERE TZ_LOCK = 0 AND COD_ENTE = @codEnte AND ID_CONVREC = @convenio)
			SET @ID_CABEZAL = ( SELECT (ISNULL(max(ID),0)+1) AS MAX_ID FROM REC_CAB_RECAUDOS_CANAL );
			
			INSERT INTO dbo.REC_CAB_RECAUDOS_CANAL (ID, ESTADO, ARCHIVO, CONVENIO, FECHACARGA, ID_LIQUIDACION, MONEDA, TOTALREGISTROS, TOTALIMPORTE, TZ_LOCK, TOTAL_CARGO_ESPECIFICO, NOMBRE)
			VALUES (@ID_CABEZAL, ''I'', @nomArchivo, @convenio, @fch_proceso, 0, 1, 0, 0, @TZ_LOCK, 0, @descrEnte);

			DECLARE cursor_convenios cursor FOR
				SELECT CADENA_01, CADENA_02, CADENA_03, CADENA_04, CADENA_05, CADENA_06, CADENA_07, 
				CADENA_08, CADENA_09, CADENA_10, CADENA_11, CADENA_12, CADENA_14, NRO_01, NRO_02, NRO_03, NRO_04, 
				NRO_05, NRO_06, NRO_07, NRO_08, NRO_09, NRO_10, FECHA_01
				FROM REC_EXT_RECAUDOS_CANAL WHERE FORMATO= @formato AND FECHA= @fch_proceso AND CADENA_03= @codEnte  AND ID_CABEZAL = @ticket;	
		
			OPEN cursor_convenios;
			
			SET @ID_LINEA = 0;
			SET @TOT_IMPORTE = 0;
			SET @TOT_CARGO_ESPEC = 0;
			
			FETCH NEXT FROM cursor_convenios INTO @CADENA_01,@CADENA_02,@CADENA_03,@CADENA_04,@CADENA_05,@CADENA_06,@CADENA_07,@CADENA_08,
			@CADENA_09,@CADENA_10,@CADENA_11,@CADENA_12,@CADENA_14,@NRO_01,@NRO_02,@NRO_03,@NRO_04,@NRO_05,@NRO_06,@NRO_07,@NRO_08,
			@NRO_09,@NRO_10,@FECHA_01
			
			WHILE @@fetch_status = 0
			BEGIN
				
				SET @convenioPadre = (SELECT Id_ConvPadre FROM CONV_CONVENIOS_REC WHERE TZ_LOCK = 0 AND Id_ConvRec = @convenio)
				
				SET @CargoEspec = (SELECT TOTAL_CARGO_ESPECIFICO FROM CONV_PADRONES WHERE TZ_LOCK = 0 AND CONVENIO = @convenioPadre AND CODIGO_BARRA = @CADENA_12 AND ESTADO = ''P'')
					
				SET @ID_LINEA = @ID_LINEA + 1;
				SET @TOT_IMPORTE = @TOT_IMPORTE + @NRO_02;
				SET @TOT_CARGO_ESPEC = @TOT_CARGO_ESPEC + @CargoEspec;
				
				INSERT INTO dbo.REC_DET_RECAUDOS_CANAL 
				(ID_CABEZAL, ID_LINEA, MONEDA, IMPORTE, CODIGO_BARRAS, CODIGO_BARRAS_RENDIDO, ESTADO, DETALLE_ESTADO, 
				TOTAL_CARGO_ESPECIFICO, TZ_LOCK, FECHA_COBRANZA)
				VALUES (@ID_CABEZAL, @ID_LINEA, @NRO_06, @NRO_02, @CADENA_12, @CADENA_12, ''I'', '' '', @CargoEspec, @TZ_LOCK,@FECHA_01);
				
			    FETCH NEXT FROM cursor_convenios INTO @CADENA_01,@CADENA_02,@CADENA_03,@CADENA_04,@CADENA_05,@CADENA_06,@CADENA_07,@CADENA_08,
				@CADENA_09,@CADENA_10,@CADENA_11,@CADENA_12,@CADENA_14,@NRO_01,@NRO_02,@NRO_03,@NRO_04,@NRO_05,@NRO_06,@NRO_07,@NRO_08,
				@NRO_09,@NRO_10,@FECHA_01
			END
			
			CLOSE cursor_convenios;
			DEALLOCATE cursor_convenios;
			
			UPDATE REC_CAB_RECAUDOS_CANAL SET TOTALREGISTROS = @ID_LINEA, TOTALIMPORTE = @TOT_IMPORTE, TOTAL_CARGO_ESPECIFICO = @TOT_CARGO_ESPEC WHERE ID = @ID_CABEZAL
					
			FETCH NEXT FROM cursor_ayuda INTO @codEnte			
		END 
		
		CLOSE cursor_ayuda;
		DEALLOCATE cursor_ayuda;
	END	  
	
	IF @formato = ''CM02''
	BEGIN
		SET @convenio = (SELECT NUMERICO FROM PARAMETROSGENERALES WHERE TZ_LOCK = 0 AND CODIGO = 303)
		SET @descrEnte = (SELECT NomConvRec FROM CONV_CONVENIOS_REC WHERE Id_ConvRec = @convenio AND TZ_LOCK = 0)
		SET @ID_CABEZAL = ( SELECT (ISNULL(max(ID),0)+1) AS MAX_ID FROM REC_CAB_RECAUDOS_CANAL );
		SET @CANT_REG = ( SELECT count(*) FROM REC_EXT_RECAUDOS_CANAL WHERE FORMATO= @formato AND FECHA= @fch_proceso );
		SET @TOT_IMPORTE = ( SELECT sum(NRO_07) FROM REC_EXT_RECAUDOS_CANAL WHERE FORMATO= @formato AND FECHA= @fch_proceso );
		
		INSERT INTO dbo.REC_CAB_RECAUDOS_CANAL (ID, ESTADO, ARCHIVO, CONVENIO, FECHACARGA, ID_LIQUIDACION, MONEDA, TOTALREGISTROS, TOTALIMPORTE, TZ_LOCK, TOTAL_CARGO_ESPECIFICO, NOMBRE)
			VALUES (@ID_CABEZAL, ''I'', @nomArchivo, @convenio, @fch_proceso, 0, 1, @CANT_REG, @TOT_IMPORTE, @TZ_LOCK, 0, @descrEnte);
			
		DECLARE cursor_convenios_3 cursor FOR
			SELECT NRO_01, NRO_02, NRO_03, NRO_04, NRO_05, NRO_06, NRO_07, NRO_08, NRO_09, NRO_10, NRO_11, CADENA_01, CADENA_02, 
			CADENA_13, CADENA_14, CADENA_15, CADENA_03, CADENA_04, CADENA_05, CADENA_06, CADENA_07, CADENA_08, CADENA_09, 
			CADENA_10, CADENA_11, CADENA_12
			FROM REC_EXT_RECAUDOS_CANAL WHERE FORMATO= @formato AND FECHA= @fch_proceso;
		
		
		OPEN cursor_convenios_3;
		FETCH NEXT FROM cursor_convenios_3 INTO @NRO_01,@NRO_02,@NRO_03,@NRO_04,@NRO_05,@NRO_06,@NRO_07,@NRO_08,@NRO_09,@NRO_10,
		@NRO_11,@CADENA_01,@CADENA_02,@CADENA_13,@CADENA_14,@CADENA_15,@CADENA_03,@CADENA_04,@CADENA_05,@CADENA_06,@CADENA_07,@CADENA_08,
		@CADENA_09,@CADENA_10,@CADENA_11,@CADENA_12
		
		SET @ID_LINEA = 0;
		SET @TOT_IMPORTE = 0;
		
		WHILE @@fetch_status = 0 
			BEGIN
				
				--SET @ID_CABEZAL = ( SELECT (ISNULL(max(ID),0)+1) AS MAX_ID FROM REC_CAB_RECAUDOS_CANAL );	
				SET @ID_LINEA = @ID_LINEA + 1;
				--SET @TOT_IMPORTE = @TOT_IMPORTE + @NRO_07;
				
				INSERT INTO dbo.REC_DET_RECAUDOS_CANAL 
				(ID_CABEZAL, ID_LINEA, MONEDA, IMPORTE, CODIGO_BARRAS, CODIGO_BARRAS_RENDIDO, ESTADO, DETALLE_ESTADO, 
				TOTAL_CARGO_ESPECIFICO, TZ_LOCK)
				VALUES (@ID_CABEZAL, @ID_LINEA, CAST(@CADENA_07 AS NUMERIC(4,0)), @NRO_07, @CADENA_12, @CADENA_12, ''I'', '' '', 0, @TZ_LOCK);
				
				FETCH NEXT FROM cursor_convenios_3 INTO @NRO_01,@NRO_02,@NRO_03,@NRO_04,@NRO_05,@NRO_06,@NRO_07,@NRO_08,@NRO_09,@NRO_10,
				@NRO_11,@CADENA_01,@CADENA_02,@CADENA_13,@CADENA_14,@CADENA_15,@CADENA_03,@CADENA_04,@CADENA_05,@CADENA_06,@CADENA_07,@CADENA_08,
				@CADENA_09,@CADENA_10,@CADENA_11,@CADENA_12
				
			END
			
		CLOSE cursor_convenios_3;
		DEALLOCATE cursor_convenios_3;
	END
		 				
END')

Execute('DELETE FROM dbo.ITF_MASTER WHERE ID = 35')

Execute('
INSERT INTO dbo.ITF_MASTER (TZ_LOCK, ID, DESCRIPCION, OBJ_KETTLE, P0_MODO, P0_TIPO, P0_CAPTION, P0_CONSTANTE, P1_MODO, P1_TIPO, P1_CAPTION, P1_CONSTANTE, P2_MODO, P2_TIPO, P2_CAPTION, P2_CONSTANTE, P3_MODO, P3_TIPO, P3_CAPTION, P3_CONSTANTE, P4_MODO, P4_TIPO, P4_CAPTION, P4_CONSTANTE, P5_MODO, P5_TIPO, P5_CAPTION, P5_CONSTANTE, P6_MODO, P6_TIPO, P6_CAPTION, P6_CONSTANTE, P7_MODO, P7_TIPO, P7_CAPTION, P7_CONSTANTE, P8_MODO, P8_TIPO, P8_CONSTANTE, P8_CAPTION, P9_MODO, P9_TIPO, P9_CAPTION, P9_CONSTANTE, TIPO_OBJ, COMENTARIO, ID_REPORTE, MODO_EJECUCION)
VALUES (0, 35, ''Carga Caja Municipal General'', ''ITF_CAJA_MUNICIPAL_GENERAL.kjb'', ''P'', ''S'', ''Nombre Archivo'', '' '', ''P'', ''S'', ''Fecha (YYYYMMDD)'', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', ''J'', ''Carga Padron Convenios'', 0, ''O'')')



