EXECUTE('
--------------------
--DELETE DE VISTAS--
--------------------
IF OBJECT_ID (''dbo.VW_CON_ASIENTOS_TIPO_CV_LINEAS'') IS NOT NULL
	DROP VIEW dbo.VW_CON_ASIENTOS_TIPO_CV_LINEAS
--
IF OBJECT_ID (''dbo.VW_CON_ASIENTOS_X_USUARIO'') IS NOT NULL
	DROP VIEW dbo.VW_CON_ASIENTOS_X_USUARIO
----
')
EXECUTE('
------------------------------------
--NUEVA VISTA LINEAS ASIENTOS TIPO--
------------------------------------
CREATE VIEW VW_CON_ASIENTOS_TIPO_CV_LINEAS
AS
SELECT
	L.ID_ASIENTO,
	L.NRO_LINEA,
	OD.DESCRIPCION AS DEBITO_CREDITO,
	OT.DESCRIPCION AS TIPO_CUENTA,
	OA.DESCRIPCION AS APERTURA,
	L.SUCURSAL_CUENTA,
	L.PRODUCTO_CUENTA,
	L.CUENTA,
	L.MONEDA_CUENTA
FROM
	CON_ASIENTOS_TIPO_CV_LINEAS AS L WITH (nolock)
INNER JOIN OPCIONES AS OD WITH (nolock) ON
	OD.OPCIONINTERNA = L.DEBITO_CREDITO
	AND OD.NUMERODECAMPO = 49692
	AND OD.IDIOMA =''E''
INNER JOIN OPCIONES AS OT WITH (nolock) ON
	OT.OPCIONINTERNA = L.TIPO_CUENTA
	AND OT.NUMERODECAMPO = 49693
	AND OT.IDIOMA = ''E''
INNER JOIN OPCIONES AS OA WITH (nolock) ON
	OA.OPCIONINTERNA = L.APERTURA
	AND OA.NUMERODECAMPO = 49698
	AND OA.IDIOMA = ''E''
WHERE
	( (L.TZ_LOCK < 300000000000000 OR L.TZ_LOCK >= 400000000000000) 
	AND (L.TZ_LOCK < 100000000000000 OR L.TZ_LOCK >= 200000000000000))
----
')
EXECUTE('
---------------------------------------------------
--NUEVA VISTA ASIENTOS TIPO POR GRUPO DE USUARIOS--
---------------------------------------------------
CREATE VIEW VW_CON_ASIENTOS_X_USUARIO
AS
SELECT
	U.GRUPO_USUARIOS,
	U.ID_ASIENTO,
	A.DESCRIPCION AS DESCRIPCION_ASIENTO,
	OH.DESCRIPCION AS HABILITADO
FROM
	CON_ASIENTOTIPO_X_USUARIO AS U WITH (nolock)
INNER JOIN CON_ASIENTOS_TIPO_CV AS A WITH (nolock) ON
	A.ID_ASIENTO = U.ID_ASIENTO
	AND ( (U.TZ_LOCK < 300000000000000 OR U.TZ_LOCK >= 400000000000000) 
		  AND (U.TZ_LOCK < 100000000000000 OR U.TZ_LOCK >= 200000000000000)
	)
INNER JOIN OPCIONES AS OH WITH (nolock) ON
	OH.OPCIONINTERNA = U.HABILITADO
	AND OH.NUMERODECAMPO = 49702
	AND OH.IDIOMA = ''E''
WHERE
	( (U.TZ_LOCK < 300000000000000 OR U.TZ_LOCK >= 400000000000000) 
	AND (U.TZ_LOCK < 100000000000000 OR U.TZ_LOCK >= 200000000000000))
----
')