execute('
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (821, ''COMISION REC. CONV POR COMPR'', 0)

INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (822, ''IVA PERCEPCION RECAUD. CONVENIO'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (2101, ''CANTIDAD DE MOV. CONV. POR COMPROB'', ''N'', ''N'', 2, ''N'', 2100, 34355, 1, 300, 700, ''C'', 0, 36, 0, ''N'', 9999, 0, NULL, ''N'', ''E'', ''C'', ''N'', 0, ''F'', ''N'', ''3065-01-01'', ''2000-01-01'', 0, ''N'', 2100, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (2102, ''IVA PERCEPCIÓN REC. CONV'', ''N'', ''N'', 2, ''N'', 2102, 58360, 1, 60, 9999999999999, ''D'', 0, 0, 0, ''N'', 9999, 0, NULL, NULL, ''R'', ''R'', ''S'', 2, ''F'', ''N'', ''3065-01-01'', ''2000-01-01'', 0, ''N'', 203, ''N'', ''I'', ''N'', 0, 0, 0, 0, 0, NULL, 0, NULL, NULL, NULL, ''N'', 2)

INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (2101, 821, 0, ''A'', 44741, ''ID CONVENIO'', 1)

INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (2102, 822, 0, ''A'', 0, '' '', 1)

INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (2102, ''CONDICIÓN IVA PERCEPCION CONV'', ''(C1357=''''AC'''')Y(C33360#''''S'''')Y(C1728#''''I'''')'', 0, 1)

INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2101, 1, 999999999, 1, 0, 1, 0, 0, ''221'', ''S'', 3, 7, ''1900-01-01'', ''2099-01-01'', 0)

INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2102, 1, 999999999999, 0, 0, 1, 0, 0, ''0'', ''N'', 0, 0, ''1900-01-01'', ''2099-01-01'', 0)

INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2102, 1, 999999999999, 0.03, 0, 1, 0, 0, ''AC'', ''N'', 0, 0, ''1900-01-01'', ''2099-01-01'', 0)

INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2102, 2, 999999999999, 0, 0, 1, 0, 0, ''0'', ''N'', 0, 0, ''1900-01-01'', ''2099-01-01'', 0)

INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA, EMPRESA)
VALUES (2102, 2, 999999999999, 0.03, 0, 1, 0, 0, ''AC'', ''N'', 0, 0, ''1900-01-01'', ''2099-01-01'', 0)

DELETE FROM CI_IMPUESTOS_X_CARGO WHERE ID_CARGO = 2101 AND ID_IMPUESTO = 4

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45299, '' '', 0, ''Esquema Comision'', ''Esquema Comisión'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4469, ''EsquemaComision'', 0, NULL)

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45299, ''E'', ''No'', ''N'', ''N'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45299, ''E'', ''Si'', ''S'', ''S'')
')



