EXECUTE
('

IF OBJECT_ID (''dbo.CHE_PEDIDO_SUCURSAL_CUENTA'') IS NOT NULL
	DROP TABLE dbo.CHE_PEDIDO_SUCURSAL_CUENTA

CREATE TABLE dbo.CHE_PEDIDO_SUCURSAL_CUENTA
	(
	SUCURSAL      NUMERIC (5) DEFAULT ((0)) NOT NULL,
	SALDO_JTS_OID NUMERIC (10) DEFAULT ((0)) NOT NULL,
	NRO_PEDIDO    NUMERIC (5) DEFAULT ((0)) NULL,
	TZ_LOCK       NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CHE_PEDIDO_SUCURSAL_CUEN_01 PRIMARY KEY (SUCURSAL,SALDO_JTS_OID)
	)
')

