EXECUTE('


INSERT INTO INDICES
(NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES(154, 2, ''Indice secundario'', 0, 4529, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO AYUDAS
(NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES(154, 1543, ''ayuda chqs propios rec. ind se'', '''', 0, ''4529R;4539;4541;4533;4534;4535;4538;4544;4531;4532;'', NULL, NULL, NULL, 0);


INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36084, '' '', 0, ''ayuda chqs. recibidos ind sec.'', ''Ayuda chqs. recibidos ind sec.'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 1543, 0, 0, NULL, 0, NULL);





--PROMPT

UPDATE DICCIONARIO
SET PROMPT=''Cámara Compensadora''
WHERE NUMERODECAMPO=4531;


UPDATE DICCIONARIO
SET PROMPT=''Estado Contabilización''
WHERE NUMERODECAMPO=4539;

UPDATE DICCIONARIO
SET PROMPT=''Estado Devolución''
WHERE NUMERODECAMPO=4541;


')