EXECUTE('
--------------------------------------
--CORRECCION NUMERADOR CANJE INTERNO--
--------------------------------------
UPDATE CHE_SOLICITUD_CANJE_INTERNO
SET ESTADO = ''T''
WHERE ESTADO IN (''A'',''I'')
----
DELETE FROM NUMERATORASIGNED
WHERE OID IN (SELECT OID FROM NUMERATORVALUES WHERE NUMERO = 35006)
----
DELETE FROM NUMERATORVALUES
WHERE NUMERO = 35006 AND SUCURSAL NOT IN (0)
----
BEGIN
	UPDATE NUMERATORVALUES
	SET VALOR = (SELECT max(NRO_SOLICITUD) + 1 FROM CHE_SOLICITUD_CANJE_INTERNO)
	WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 35006
	
	if @@rowcount = 0
		BEGIN
			INSERT INTO NUMERATORVALUES (DIA, MES, ANIO, SUCURSAL, NUMERO, VALOR)
			VALUES (0, 0, 0, 0, 35006, ISNULL((SELECT max(NRO_SOLICITUD) + 1 FROM CHE_SOLICITUD_CANJE_INTERNO),1))
		END	
END
----
UPDATE NUMERATORDEFINITION
SET INIVAL = 1
	, INCREMENTO = 1
	, PERIODO = '' ''
	, ULTIMAINIC = NULL
	, REUTILIZABLE = 1
	, CENTRALIZADO = 1
	, MAXIMO = 9999999999
	, DESCRIPCION = ''Numerador Solic. Canje Interno Ch.''
	, TIPO = ''T''
WHERE NUMERO = 35006
----
')



