EXECUTE('
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 58506

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (58506, '' '', 0, ''Pivot Seguro Saldo D'', ''Pivot Seguro Saldo D'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL)

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5001

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5002

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5003

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5004

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5005

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5006

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5007

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5008

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5009

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5010

DELETE FROM dbo.CI_CARGOS
WHERE ID_CARGO = 5011


INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5001, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5002, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5003, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5004, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5005, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5006, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5007, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5008, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5009, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5010, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (5011, ''GASTOS LEASING'', ''N'', ''N'', 1, ''N'', 0, 58506, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''S'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 0, ''F'', ''N'', ''20600331'', ''19990301'', 0, ''N'', 2152, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

DELETE FROM CRE_TIPO_TRAMITE_LEASING

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (1, ''Seguro s/bien (automotor)'', ''S'', ''S'', 0, 5001, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (2, ''Seguro tecnico'', ''S'', ''S'', 0, 5002, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (3, ''Patente'', ''S'', ''P'', 0, 5003, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (4, ''Gasto por multas'', ''S'', ''M'', 0, 5004, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (5, ''Gastos por comision y otros '', ''S'', ''O'', 0, 5005, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (6, ''Gastos Inscripcion registro Bien'', ''G'', ''T'', 0, 5006, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (7, ''Gastos Inscripcion contrato'', ''G'', ''T'', 0, 5007, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (8, ''Otros gastos'', ''G'', ''T'', 0, 5008, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (9, ''Aj. PATENTE'', ''S'', ''P'', 0, 5009, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (10, ''Aj. Seguro autom.'', ''S'', ''S'', 0, 5010, ''N'')

INSERT INTO dbo.CRE_TIPO_TRAMITE_LEASING (CODIGO, DESCRIPCION, TIPO, CATEGORIA, TZ_LOCK, ID_CARGO, DISTRIBUIDO_CUOTAS)
VALUES (11, ''Aj. Seguro Tecnico'', ''S'', ''S'', 0, 5011, ''N'')

')




