


-- Patch_NUNBCHACO_542

-- SQL - Modificación de SUMA_PROMEDIO_DIARIO
ALTER TABLE GRL_SALDOS_DIARIOS ALTER COLUMN SUMA_PROMEDIO_DIARIO NUMERIC(18,2);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210129_1NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VTkJDSEFDT181NDIKDQotLSBTUUwgLSBNb2RpZmljYWNp824gZGUgU1VN
QV9QUk9NRURJT19ESUFSSU8NCkFMVEVSIFRBQkxFIEdSTF9TQUxET1NfRElBUklPUyBBTFRFUiBD
T0xVTU4gU1VNQV9QUk9NRURJT19ESUFSSU8gTlVNRVJJQygxOCwyKTsKDQoKCg0K', NULL, 0);
