EXECUTE('

DELETE FROM CHE_ESTADOSCHEQUES
WHERE CODIGO=''H'';


INSERT INTO CHE_ESTADOSCHEQUES
(TZ_LOCK, CODIGO, DESCRIPCION, ACCION, PERMISO, MENSAJE, CODIGORETORNADO, REVERSA, CODIGOCONTROL)
VALUES(0, ''B'', ''ROBADO'', ''P'', 840, ''CHEQUE ROBADO'', 6, ''N'', 12);


')