
EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35691, '' '', 0, ''Valor Control Sobregiro'', ''Valor Control Sobregiro'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Valor Control Sobregiro'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35688, '' '', 0, ''Importe Control Sobregiro'', ''Importe Control Sobregiro'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Importe Control Sobregiro'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35663, '' '', 0, ''Campo Control Sobregiro'', ''Campo Control Sobregiro'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Campo Control Sobregiro'', 0, NULL)

INSERT INTO TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
VALUES (1, 1044, ''S'', ''SUBRUTINA - CONTROL SOBREGIRO'', ''SUBRUTINA - CONTROL SOBREGIRO'', ''O'', 0, 0)

')
