EXECUTE('
IF OBJECT_ID (''dbo.RRII_CREDEBEX'') IS NOT NULL
	DROP TABLE dbo.RRII_CREDEBEX
')
EXECUTE('
CREATE TABLE dbo.RRII_CREDEBEX
	(
	CODIGO_REGIMEN       NUMERIC (3) DEFAULT ((0)) NOT NULL,
	TIPO_DOCUMENTO       NUMERIC (2) DEFAULT ((0)) NOT NULL,
	NUMERO_DOCUMENTO     NUMERIC (13) DEFAULT ('' '') NOT NULL,
	POSEE_CBU            NUMERIC (1),
	CBU                  VARCHAR (22) DEFAULT ('' '') NOT NULL,
	BASE_IMPONIBLE       NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
	MODALIDAD_MOVIMIENTO NUMERIC (2) DEFAULT ((0)) NOT NULL,
	FECHA_GENERACION     VARCHAR (10) NOT NULL,
	PERIODO_GENERADO     VARCHAR (8) NOT NULL,
	CONSTRAINT PK_RRII_CREDEBEX PRIMARY KEY (CODIGO_REGIMEN, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, CBU, MODALIDAD_MOVIMIENTO)
	)
')
EXECUTE('
DELETE FROM RRI_PARAMETROS_DEF
WHERE CODIGO = 501

INSERT INTO RRI_PARAMETROS_DEF (CODIGO, NOMBRE, ID1, ID1DESC, ID2, ID2DESC, ID3, ID3DESC, ID4, ID4DESC, ID5, ID5DESC, NUM1, NUM1DESC, NUM2, NUM2DESC, CHAR1, CHR1DESC, CHAR2, CHR2DESC, TZ_LOCK)
VALUES (501, ''CREDEB Exentos'', ''S'', ''Tipo de producto'', ''N'', '''', ''N'', '''', ''S'', ''Código de concepto'', ''S'', ''Tipo movi. (D, C) '', ''S'', ''Código Exento'', ''N'', '''', ''N'', '''', ''N'', '''', 0)
')
EXECUTE('
DELETE FROM dbo.RRI_PARAMETROS_INF
WHERE CODIGO = 501

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 2, 0, 0, ''HAB'', ''C'', 396, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 2, 0, 0, ''HAB'', ''D'', 395, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 2, 0, 0, ''OIN'', ''C'', 501, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 2, 0, 0, ''OIN'', ''D'', 502, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 3, 0, 0, ''HAB'', ''C'', 398, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 3, 0, 0, ''OIN'', ''C'', 398, 0, '' '', '' '', 0)

INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (501, 3, 0, 0, ''OIN'', ''D'', 397, 0, '' '', '' '', 0)
')