EXECUTE('

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45622

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45622, '' '', 0, ''ID'', ''Id'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4522, ''ID'', 0, NULL)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45636

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45636, '' '', 0, ''ARCHIVO'', ''ARCHIVO'', 75, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4522, ''ARCHIVO'', 0, NULL)

')
