EXECUTE('
------------------------------------------
--AJUSTE DE EVENTOS Y COD. TRANSACCIONES--
------------------------------------------
DELETE FROM dbo.CODIGO_TRANSACCIONES
WHERE CODIGO_OPERACION = 2636 AND CODIGO_INTERNO_MOV = 4
----
DELETE FROM dbo.CI_CARGOS_X_EVENTO
WHERE ID_EVENTO = 845
----
DELETE FROM dbo.CI_EVENTO
WHERE ID_EVENTO = 845
----
')
EXECUTE('
-----
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (401, 844, 0, ''A'', 34096, ''CONDICIÓN CREDEB'', 2)
--
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (501, 844, 0, ''A'', 33991, ''CONDICIÓN SIRCREB'', 3)
--
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (555, 844, 0, ''A'', 0, '''', 4)
----
')