EXECUTE('
ALTER TABLE CRE_LIMITECLIENTE ADD DEFAULT 0 FOR COTIZA_DOL;
ALTER TABLE CRE_SOLLICCLIENTE ADD DEFAULT 0 FOR COTIZA_DOL;
')

EXECUTE('
UPDATE CRE_LIMITECLIENTE SET COTIZA_DOL = 0 WHERE COTIZA_DOL IS NULL;
UPDATE CRE_SOLLICCLIENTE SET COTIZA_DOL = 0 WHERE COTIZA_DOL IS NULL;
')

