Execute('

IF OBJECT_ID (''dbo.SUC_FICTICIA_CONV_CANALES'') IS NOT NULL
	DROP TABLE dbo.SUC_FICTICIA_CONV_CANALES


CREATE TABLE dbo.SUC_FICTICIA_CONV_CANALES
	(
	CANAL    INT NOT NULL,
	SUCURSAL VARCHAR (4),
	PRIMARY KEY (CANAL)
	)



INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (1, ''150'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (2, ''0002'')

INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (3, ''0101'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (4, ''0098'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (5, ''0005'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (6, ''0006'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (7, ''0007'')

INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (8, ''0008'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (9, ''0009'')


INSERT INTO dbo.SUC_FICTICIA_CONV_CANALES (CANAL, SUCURSAL)
VALUES (10, ''0010'')

')
