EXECUTE('

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (4003, '' '', 0, ''Cuit'', NULL, 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Cuit'', 0, NULL)

')
