EXECUTE('
INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (1002, 3335, ''PA Rechazar Solicitud ACT/INAC Causas'', ''PA Rechazar Solicitud ACT/INAC Causas'', ''3335'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''I'', ''N'', ''N'', ''S'', NULL, 0)
')
