EXECUTE('
-- Descriptor 4360
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN (44025,44028,44029,44032)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44025, '' '', 0, ''PUNT_CLI_NUEVO'', ''Puntaje Cliente Nuevo'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4360, ''PUNT_CLI_NUEVO'', 0, NULL)

-- Descriptor 4380
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44028, '''', 0, ''PUNT_CLI_NUEVO'', ''Puntaje Cliente Nuevo'', 5, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 4380, ''PUNT_CLI_NUEVO'', 0, '''')

-- Descriptor 11
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44029, '''', 0, ''SIC_SEGMENTO'', ''SIC Segmento'', 1, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 11, ''SIC_SEGMENTO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44032, '''', 0, ''SIC_PUNTOS'', ''SIC Puntos'', 5, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 11, ''SIC_PUNTOS'', 0, '''')
')
