EXECUTE('
INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''011000'', ''101100'', 7590, ''Extracciones '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', ''LKAMT2'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''011502'', ''101502'', 7590, ''Extracciones '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', ''LKAMT2'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''012000'', ''100100'', 7590, ''Extracciones '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', ''LKAMT2'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''091000'', ''191100'', 7610, ''Transferencias Inmediatas   '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''091500'', ''191500'', 7610, ''Transferencias Inmediatas   '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''092000'', ''190100'', 7610, ''Transferencias Inmediatas   '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''171000'', ''171100'', 7958, ''Recargas de Celular, SUBE'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''171500'', ''171500'', 7958, ''Recargas de Celular, SUBE'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''172000'', ''170100'', 7958, ''Recargas de Celular, SUBE'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''1B1000'', ''1B1100'', 7611, ''Transferencias Inmediatas       '', ''LKFROM'', ''LKFI10'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''1B2000'', ''1B0100'', 7611, ''Transferencias Inmediatas       '', ''LKFROM'', ''LKFI10'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''210010'', ''200011'', 7591, ''Depósitos Ensobrados e inteligentes  '', ''LKTOAC'', ''LKTERK'', ''LKAMT1'', ''LKFI04'', ''LKTCDE'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''210020'', ''200001'', 7591, ''Depósitos Ensobrados e inteligentes  '', ''LKTOAC'', ''LKTERK'', ''LKAMT1'', ''LKFI04'', ''LKTCDE'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''290010'', ''290011'', 7610, ''Transferencias Inmediatas   '', ''LKTOAC'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''290015'', ''290015'', 7610, ''Transferencias Inmediatas   '', ''LKTOAC'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''290020'', ''290001'', 7610, ''Transferencias Inmediatas   '', ''LKTOAC'', ''LKAMT1'', ''LKTERC'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''401010'', ''401111'', 7601, ''Transferencias entre Cuentas Asociadas misma tarj'', ''LKFROM'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''401015'', ''401115'', 7603, ''Compra/Venta de Moneda Extranjera'', ''LKTOAC'', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''401020'', ''401101'', 7601, ''Transferencias entre Cuentas Asociadas misma tarj'', ''LKFROM'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''401515'', ''401515'', 7601, ''Transferencias entre Cuentas Asociadas misma tarj'', ''LKFROM'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''402010'', ''400111'', 7601, ''Transferencias entre Cuentas Asociadas misma tarj'', ''LKFROM'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''402020'', ''400101'', 7601, ''Transferencias entre Cuentas Asociadas misma tarj'', ''LKFROM'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''711000'', ''711100'', 7595, ''Compras POS  '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''711500'', ''711500'', 7595, ''Compras POS  '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''712000'', ''710100'', 7595, ''Compras POS  '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''721000'', ''721100'', 7597, ''Devolución de Compras POS '', ''LKTERM'', ''LKFROM'', ''LKAMT1'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''722000'', ''720100'', 7597, ''Devolución de Compras POS '', ''LKTERM'', ''LKFROM'', ''LKAMT1'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''741000'', ''741100'', 7596, ''Devolución Dto'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''742000'', ''740100'', 7596, ''Devolución Dto'', ''LKTOAC'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''751000'', ''751100'', 7597, ''Anulacion POS'', ''LKTERM'', ''LKFROM'', ''LKAMT1'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''752000'', ''750100'', 7597, ''Anulacion POS'', ''LKTERM'', ''LKFROM'', ''LKAMT1'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''761000'', ''761100'', 7595, ''Compras con Cash-Back   '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''762000'', ''760100'', 7595, ''Compras con Cash-Back   '', ''LKFROM'', ''LKTERC'', ''LKAMT1'', ''LKAMT3'', ''LKTYP'', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''771000'', ''771100'', 7597, ''Anulación Compras con Cash-Back'', ''LKTERM'', ''LKFROM'', ''LKAMT1'', '''', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''811000'', ''811100'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''812000'', ''810100'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''881000'', ''881100'', 7966, ''Pago Tarjeta Crédito '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''882000'', ''880100'', 7966, ''Pago Tarjeta Crédito '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''901000'', ''511100'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''901020'', ''511101'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''902000'', ''510100'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''902020'', ''510101'', 7599, ''Pago de impuestos y servicios'', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKTYP'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''F31000'', ''F31100'', 7610, ''DEBIN/CREDIN     '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKFI10'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''F32000'', ''F30100'', 7610, ''DEBIN/CREDIN     '', ''LKFROM'', ''LKAMT1'', ''LKTERC'', ''LKFI10'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''F40010'', ''F40011'', 7610, ''DEBIN/CREDIN     '', ''LKTOAC'', ''LKAMT1'', ''LKTERC'', ''LKFI10'', '''', '''', '''', '''', '''', '''')


INSERT INTO dbo.TLF_CODIGOS_OPERACIONES (TZ_LOCK, COD_MSJ_H2H, COD_MSJ_TLF, NRO_OPE, DESC_COD_MSJ, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9, PARAMETRO10)
VALUES (0, ''F40020'', ''F40001'', 7610, ''DEBIN/CREDIN     '', ''LKTOAC'', ''LKAMT1'', ''LKTERC'', ''LKFI10'', '''', '''', '''', '''', '''', '''')

')
