/****** Object:  View [dbo].[VW_PAS_CV_INMOVILIZAR]    Script Date: 24/02/2021 10:46:04 ******/
DROP VIEW [dbo].[VW_PAS_CV_INMOVILIZAR]
GO
/****** Object:  View [dbo].[VW_PAS_CV_INMOVILIZAR]    Script Date: 24/02/2021 10:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PAS_CV_INMOVILIZAR] AS
WITH AUX1 AS(
				SELECT
					CASE 
					--WHEN PCI.VALOR IS NULL THEN 'N'
					WHEN PCI.INCLUIR_EXCLUIR = 'E' AND PCI.ACTIVO = 'A' THEN 'E'
					WHEN PCI.INCLUIR_EXCLUIR = 'I' AND PCI.ACTIVO = 'A' THEN 'I'
				--	WHEN PCI.ACTIVO = 'I' THEN 'I'
					END INCLUYE_MONEDA
					, S.*
				FROM
					SALDOS S with (nolock) 
					INNER JOIN TOPESPRODUCTO TP  with(nolock) ON S.PRODUCTO = TP.CODPRODUCTO AND S.MONEDA = TP.MONEDA 
					LEFT JOIN VTA_PARAM_CTAS_INMOV PCI  with(nolock) ON PCI.TIPO = 'N' 
																		AND PCI.VALOR = S.MONEDA 
																		AND PCI.TZ_LOCK = 0
				WHERE
					S.C1785 IN (2, 3)	
					AND S.C1679 = '0' 
					AND TP.PASAJE_INMOVILIZADO = 'S'
					AND S.C1728 <> 'I'
					AND S.C1734 <> 'I'
					AND S.TZ_LOCK = 0
					),
AUX2 AS(
--TRAER CUENTAS ENTRE SALDO MINIMO Y SALDO MAXIMO
		SELECT
			A.*
		FROM
			AUX1 A with(nolock)
			,VTA_PARAM_CTAS_INMOV PCI_MIN  with(nolock)   
			, VTA_PARAM_CTAS_INMOV PCI_MAX  with(nolock) 
		WHERE
			PCI_MIN.TIPO = 'M'
			AND INCLUYE_MONEDA = 'I'
			AND PCI_MAX.TIPO = 'X'
			AND 
			((PCI_MIN.ACTIVO = 'A'
			AND ((PCI_MIN.INCLUIR_EXCLUIR = 'I' AND A.C1604 >= PCI_MIN.VALOR) OR (PCI_MIN.INCLUIR_EXCLUIR = 'E' AND A.C1604 >= -999999999999999)))
			OR (PCI_MIN.ACTIVO = 'I'))
			AND 
			((PCI_MAX.ACTIVO = 'A'
			AND ((PCI_MAX.INCLUIR_EXCLUIR = 'I' AND A.C1604 <= PCI_MAX.VALOR) OR (PCI_MAX.INCLUIR_EXCLUIR = 'E' AND A.C1604 <= 999999999999999)))
			OR (PCI_MAX.ACTIVO = 'I'))
		),
AUX3 AS(
		SELECT
			DISTINCT
			CASE WHEN VP_TRANS.VALOR IS NULL THEN 'N'  --el cod movimiento no coincide con el de parametria
			WHEN VP_TRANS.INCLUIR_EXCLUIR = 'E' THEN 'E' --cod coincide, y se excluye del control de dias sin movs.
			WHEN VP_TRANS.INCLUIR_EXCLUIR = 'I' THEN 'I' --Cod coincide, pero se incluye en el control
			END CUENTA_CON_CODMOV,
			A.*
		FROM
			AUX2 A with(nolock) 
			LEFT JOIN MOVIMIENTOS_CONTABLES MC with(nolock) ON MC.SALDO_JTS_OID = A.JTS_OID
			LEFT JOIN VTA_PARAM_CTAS_INMOV VP_TRANS with(nolock) ON VP_TRANS.ACTIVO = 'A' 
																	AND VP_TRANS.TIPO = 'V'
																	AND MC.COD_TRANSACCION = VP_TRANS.VALOR
		),

AUX4 AS(
SELECT
	A.*
FROM
	AUX3 A with(nolock),
	PARAMETROS P with(nolock),
	VTA_PARAM_CTAS_INMOV VP_DIAS with(nolock)
WHERE
	VP_DIAS.INCLUIR_EXCLUIR = 'I'
	AND VP_DIAS.TIPO = 'D'
	AND ((VP_DIAS.ACTIVO = 'A'
		AND (A.C1624 < DATEADD(day, -(VP_DIAS.VALOR), P.FECHAPROCESO)
		AND A.CUENTA_CON_CODMOV <> 'E' )
		OR A.CUENTA_CON_CODMOV = 'E')
	OR (VP_DIAS.ACTIVO = 'I')) 
	),
--EXCLUIR O INCLUIR POR CODIGO DE BLOQUEO

AUX5 AS(
		SELECT DISTINCT 
		CASE 
		WHEN VP.INCLUIR_EXCLUIR = 'E' THEN 'E'
		WHEN VP.INCLUIR_EXCLUIR = 'I' THEN 'I'
		ELSE 'N'
		END EXCLUYE_BLOQUEO,
		A.*
		FROM AUX4 A with(nolock) 
		LEFT JOIN GRL_BLOQUEOS B with(nolock) ON A.JTS_OID = B.SALDO_JTS_OID 
		LEFT JOIN VTA_PARAM_CTAS_INMOV VP with(nolock) ON VP.TIPO = 'B' 
															AND VP.ACTIVO = 'A' 
															AND VP.VALOR = B.COD_BLOQUEO
		)
--excluye cuentas vista contracuenta de prestamos o plazos fijos, y que cuenta no esté asociada a caja de seguridad, y que no esté asociado a tarjeta de credito

SELECT DISTINCT 
A.C1803 AS NRO_CLIENTE,
	C.NOMBRECLIENTE,
	A.CUENTA,
	A.MONEDA,
	A.C1604 AS SALDO,
	A.JTS_OID 
FROM AUX5 A with(nolock) 
INNER JOIN CLI_CLIENTES C with(nolock) ON A.C1803 = C.CODIGOCLIENTE,
	VTA_PARAM_CTAS_INMOV VP with(nolock),
	PARAMETROS P with(nolock)
WHERE A.JTS_OID NOT IN (SELECT JTS_OID 
						FROM AUX5 with (nolock) 
						WHERE EXCLUYE_BLOQUEO = 'E')
	AND VP.TIPO = 'C'
	AND C.TZ_LOCK = 0
	--CONTROL PARA EXCLUIR A CUENTAS DEL SECTOR FINANCIERO
	AND C.SUBDIVISION1 <> '03'
	AND A.JTS_OID NOT IN ( SELECT JTS_OID_DEBITO 
							FROM COF_COFRES_CONTRATOS with(nolock)
						 )
	AND A.JTS_OID NOT IN (	SELECT SALDO_JTS_OID 
							FROM TJD_REL_TARJETA_CUENTA with(nolock)
						 )
--excluir o incluir contracuenta
	AND ((VP.ACTIVO = 'A'
	AND ((VP.INCLUIR_EXCLUIR = 'E' AND NOT (A.C1665 = 1 AND A.C1785 IN (VP.VALOR))) OR (VP.INCLUIR_EXCLUIR = 'I')))
	OR (VP.ACTIVO = 'I'));
GO


