EXECUTE('
INSERT INTO dbo.CRE_PRODUCTOSCANALDIGITAL (PRODUCTO, CANAL, HABILITADO, PORCENTAJE_AFECTACION, CANT_MAX_CUOTAS, SCORING_MINIMO, SCORING_MAXIMO, CANAL_PRESENCIAL, TZ_LOCK, COBRA_SELLOS)
VALUES (50201, ''PO'', ''S'', 100, 1, 50, 99999999, ''S'', 0, ''N'')

')