
EXECUTE('

ALTER VIEW VW_PERSONAS_CLIENTE (
   TipoDocIdent, 
   NroDocIdent, 
   TipoDocFisico,
   NumDocFisico,
   NOMBRE,
   NIVELAPERTURA, 
   TIPOPERSONA, 
   NUMEROPERSONA,
   Titularidad,
   Cliente)
AS 
   SELECT  
      V.TIPODOCUMENTO AS TipoDocIdent, 
      V.NUMERODOCUMENTO AS NroDocIdent, 
      V.TIPO_DOC_FISICO AS TIPO_DOC_FISICO,
      V.NUM_DOC_FISICO AS NUM_DOC_FISICO,
      ISNULL(U.PRIMERNOMBRE, '''') + '' '' + ISNULL(U.APELLIDOPATERNO, '''') + '' '' + ISNULL(U.APELLIDOMATERNO, '''') AS NOMBRE,
      CASE U.NIVEL_APERTURA
         WHEN 0 THEN ''REGISTRO''
         WHEN 1 THEN ''BÁSICO''
         -- WHEN 2 THEN ''PASIVOS''
         WHEN 3 THEN ''ACTIVOS''
      END AS NIVELAPERTURA, 
      V.TIPOPERSONA, 
      V.NUMEROPERSONAFJ AS NUMEROPERSONA,
      P.TITULARIDAD,
      P.CODIGOCLIENTE
   FROM dbo.CLI_PERSONASFISICAS  AS U, dbo.CLI_DOCUMENTOSPFPJ  AS V, dbo.CLI_ClientePersona AS P
   WHERE 
      (U.NUMEROPERSONAFISICA = V.NUMEROPERSONAFJ) AND (P.NUMEROPERSONA = U.NUMEROPERSONAFISICA) AND
      U.TZ_LOCK = 0 AND V.TZ_LOCK = 0 AND P.TZ_LOCK = 0
    UNION ALL
   SELECT  
      V.TIPODOCUMENTO AS TipoDocIdent, 
      V.NUMERODOCUMENTO AS NroDocIdent, 
      V.TIPO_DOC_FISICO AS TIPO_DOC_FISICO,
      V.NUM_DOC_FISICO AS NUM_DOC_FISICO,
      S.RAZONSOCIAL AS NOMBRE,
      CASE S.NIVEL_APERTURA
         WHEN 0 THEN ''REGISTRO''
         WHEN 1 THEN ''BÁSICO''
         -- WHEN 2 THEN ''PASIVOS''
         WHEN 3 THEN ''ACTIVOS''
         WHEN 4 THEN ''INST. FINANCIERA''
      END AS NIVELAPERTURA, 
      V.TIPOPERSONA, 
      V.NUMEROPERSONAFJ AS NUMEROPERSONA,
      P.TITULARIDAD,
      P.CODIGOCLIENTE
   FROM dbo.CLI_PERSONASJURIDICAS  AS S, dbo.CLI_DOCUMENTOSPFPJ  AS V, dbo.CLI_ClientePersona AS P
   WHERE 
      (S.NUMEROPERSONAJURIDICA = V.NUMEROPERSONAFJ) AND (P.NUMEROPERSONA = S.NUMEROPERSONAJURIDICA) AND
      S.TZ_LOCK = 0 AND V.TZ_LOCK = 0 


')