EXECUTE('
INSERT INTO dbo.CRE_SIC_CC (TIPO_SOBREGIRO, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (0, 0, 0, 0)


INSERT INTO dbo.CRE_SIC_CC (TIPO_SOBREGIRO, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (1, 50, 0, 0)


INSERT INTO dbo.CRE_SIC_CC (TIPO_SOBREGIRO, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (2, 100, 0, 0)


INSERT INTO dbo.CRE_SIC_CC (TIPO_SOBREGIRO, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (3, 0, 0, 0)



INSERT INTO dbo.CRE_SIC_CHEQUES (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (0, 0, 100, 0, 0)



INSERT INTO dbo.CRE_SIC_CHEQUES (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (1, 99999, 0, 0, 0)


INSERT INTO dbo.CRE_SIC_MORA (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (0, 0, 100, 0, 0)


INSERT INTO dbo.CRE_SIC_MORA (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (1, 1, 75, 0, 0)


INSERT INTO dbo.CRE_SIC_MORA (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (2, 2, 25, 0, 0)


INSERT INTO dbo.CRE_SIC_MORA (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (3, 99999, 0, 0, 0)



INSERT INTO dbo.CRE_SIC_NOSIS (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (0, 250, 0, 0, 0)


INSERT INTO dbo.CRE_SIC_NOSIS (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (251, 450, 28, 28, 0)


INSERT INTO dbo.CRE_SIC_NOSIS (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (451, 550, 60, 60, 0)


INSERT INTO dbo.CRE_SIC_NOSIS (RANGO_DESDE, RANGO_HASTA, PUNTAJE, PUNT_CLI_NUEVO, TZ_LOCK)
VALUES (551, 1000, 100, 100, 0)



INSERT INTO dbo.CRE_SIC_PONDERACION (TIPO_SIC, PONDERACION, PONDERACION_CLI_NUEVO, TZ_LOCK)
VALUES (0, 25, 100, 0)


INSERT INTO dbo.CRE_SIC_PONDERACION (TIPO_SIC, PONDERACION, PONDERACION_CLI_NUEVO, TZ_LOCK)
VALUES (1, 15, 0, 0)


INSERT INTO dbo.CRE_SIC_PONDERACION (TIPO_SIC, PONDERACION, PONDERACION_CLI_NUEVO, TZ_LOCK)
VALUES (2, 20, 0, 0)


INSERT INTO dbo.CRE_SIC_PONDERACION (TIPO_SIC, PONDERACION, PONDERACION_CLI_NUEVO, TZ_LOCK)
VALUES (3, 40, 0, 0)


INSERT INTO dbo.CRE_SIC_SEGMENTACION (RANGO_DESDE, RANGO_HASTA, SEGMENTO, DESCRIPCION, TZ_LOCK)
VALUES (0, 24, ''E'', ''0-24'', 0)


INSERT INTO dbo.CRE_SIC_SEGMENTACION (RANGO_DESDE, RANGO_HASTA, SEGMENTO, DESCRIPCION, TZ_LOCK)
VALUES (25, 39, ''D'', ''25-39'', 0)


INSERT INTO dbo.CRE_SIC_SEGMENTACION (RANGO_DESDE, RANGO_HASTA, SEGMENTO, DESCRIPCION, TZ_LOCK)
VALUES (40, 49, ''C'', ''40-49'', 0)


INSERT INTO dbo.CRE_SIC_SEGMENTACION (RANGO_DESDE, RANGO_HASTA, SEGMENTO, DESCRIPCION, TZ_LOCK)
VALUES (50, 59, ''B'', ''50-59'', 0)


INSERT INTO dbo.CRE_SIC_SEGMENTACION (RANGO_DESDE, RANGO_HASTA, SEGMENTO, DESCRIPCION, TZ_LOCK)
VALUES (60, 100, ''A'', ''60-100'', 0)
')

