EXECUTE('
----------------------------------
--AJUSTE DE PARÁMETROS GENERALES--
----------------------------------
DELETE FROM dbo.PARAMETROSGENERALES
WHERE CODIGO = 718
----
')
EXECUTE('
----
INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (660, ''Cargo retención IGA DPF inmov.'', NULL, 619, NULL, 0, 0, 0)
--
INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (661, ''Cargo ret. IGA DPF UVA inmov.'', NULL, 625, NULL, 0, 0, 0)
--
INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (662, ''Cargo ret. IGA DPF TV inmov.'', NULL, 624, NULL, 0, 0, 0)
----
')