EXECUTE('
----
IF OBJECT_ID (''dbo.VW_PF_DOCUMENTOS'') IS NOT NULL
	DROP VIEW dbo.VW_PF_DOCUMENTOS
----
')
EXECUTE('
----
CREATE VIEW [dbo].[VW_PF_DOCUMENTOS] 
AS 
SELECT TOP 9223372036854775807 WITH TIES 
    V.TIPODOCUMENTO AS ''Tipo Documento Identificativo'', 
    V.NUMERODOCUMENTO AS ''Número Documento Identificativo'',
    V.TIPO_DOC_FISICO AS ''Tipo Documento Físico'',
    V.NUM_DOC_FISICO AS ''Número Documento Físico'',
    concat(U.APELLIDOPATERNO,'' '', U.PRIMERNOMBRE) AS ''Apellido y Nombre'',
    CASE V.TIPOPERSONA 
    WHEN ''F'' THEN ''Persona Humana'' END AS ''Tipo de Persona'',
    OA.DESCRIPCION AS ''Nivel de Apertura'',
    OE.DESCRIPCION AS ''Estado de la Persona'',
    OM.DESCRIPCION AS ''Motivo Inhabilitado'',
    V.NUMEROPERSONAFJ AS ''Número de la Persona'',  
    U.EMPLEADO_BC_BANCO
FROM dbo.CLI_PERSONASFISICAS  AS U WITH(NOLOCK) 
INNER JOIN dbo.CLI_DOCUMENTOSPFPJ  AS V WITH(NOLOCK) ON  U.NUMEROPERSONAFISICA = V.NUMEROPERSONAFJ 
												AND (V.TIPOPERSONA = ''F'' OR V.TIPOPERSONA = ''U'') 
												AND (	(U.TZ_LOCK < 300000000000000 OR U.TZ_LOCK >= 400000000000000) 
													AND (U.TZ_LOCK < 100000000000000 OR U.TZ_LOCK >= 200000000000000)) 
												AND(	(V.TZ_LOCK < 300000000000000 OR V.TZ_LOCK >= 400000000000000) 
													AND (V.TZ_LOCK < 100000000000000 OR V.TZ_LOCK >= 200000000000000))
LEFT JOIN OPCIONES AS OA WITH (NOLOCK) ON
	OA.NUMERODECAMPO = 2203
	AND OA.IDIOMA = ''E''
	AND OA.OPCIONINTERNA = U.NIVEL_APERTURA
LEFT JOIN OPCIONES AS OE WITH (NOLOCK) ON
	OE.NUMERODECAMPO = 33366
	AND OE.IDIOMA = ''E''
	AND OE.OPCIONINTERNA = U.ESTADO
LEFT JOIN OPCIONES AS OM WITH (NOLOCK) ON
	OM.NUMERODECAMPO = 33368
	AND OM.IDIOMA = ''E''
	AND OM.OPCIONINTERNA = U.MOTIVO_INHABILITADO
ORDER BY ''Número de la Persona''
----
')

