EXECUTE('
------------------------------------
--NUEVOS CAMPOS DE CLE_TIPO_CAUSAL--
------------------------------------
ALTER TABLE CLE_TIPO_CAUSAL ADD SEGUNDA_PRESENTACION VARCHAR(1)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD MODIF_DURANTE_DIA VARCHAR(1)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD COMISION VARCHAR(1)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD MULTA VARCHAR(1)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD CONTABILIZA_RECHAZO VARCHAR(1)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD [CODIGO_NACHA] VARCHAR(3)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD [CODIGO_RRII] NUMERIC(3, 0)
--
ALTER TABLE CLE_TIPO_CAUSAL ADD [CODIGO_BCRA] NUMERIC(1, 0)
----
')