EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35363, '' '', 0, ''MONEDA_CUENTA'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3410, ''MONEDA_CUENTA'', 0, NULL)
')

