EXECUTE('
CREATE PROCEDURE dbo.SP_CLI_INTEGRANTESPJ_ASIENTO_PENDIENTE
   @P_CODIGO NUMERIC(12),
   @RESULTADO NUMERIC(4) OUTPUT
AS 
   BEGIN
	SET @RESULTADO = (SELECT COUNT(*) FROM CLI_INTEGRANTESPJ WITH (NOLOCK) WHERE NUMEROPERSONAJURIDICA=@P_CODIGO AND (TZ_LOCK < 300000000000000 OR TZ_LOCK >= 400000000000000) AND TZ_LOCK<>0)
   END

')

