EXECUTE('
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45725

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45725, '' '', 0, ''ID_LIQUIDACION'', ''ID_LIQUIDACION'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4480, ''ID_LIQUIDACION'', 0, NULL)

')
