EXECUTE('
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (56, 2073, ''Ayuda Codigo Swift'', '''', 0, ''1935;1936;1938R;'', NULL, NULL, NULL, 0)
')