


-- Patch_NUGAN106_10

-- 
CREATE TABLE EVENTOSMONITOREO(
  ID            NUMERIC (2) NOT NULL,
  DESTINATARIOS VARCHAR (1024),
  PRIMARY KEY (ID)
  );

ALTER TABLE BITACORA_USUARIOS add USUARIORED_USR VARCHAR(50);

ALTER TABLE USUARIOS add USUARIORED VARCHAR(50);

-- 
-- HM begin sentence
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'USUARIOSBK')
BEGIN
    ALTER TABLE USUARIOSBK
ADD		
USUARIORED VARCHAR(50)
END
-- HM end sentence;




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210126_3',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VR0FOMTA2XzEwCg0KLS0gDQpDUkVBVEUgVEFCTEUgRVZFTlRPU01PTklU
T1JFTygKICBJRCAgICAgICAgICAgIE5VTUVSSUMgKDIpIE5PVCBOVUxMLAogIERFU1RJTkFUQVJJ
T1MgVkFSQ0hBUiAoMTAyNCksCiAgUFJJTUFSWSBLRVkgKElEKQogICk7CgpBTFRFUiBUQUJMRSBC
SVRBQ09SQV9VU1VBUklPUyBhZGQgVVNVQVJJT1JFRF9VU1IgVkFSQ0hBUig1MCk7CgpBTFRFUiBU
QUJMRSBVU1VBUklPUyBhZGQgVVNVQVJJT1JFRCBWQVJDSEFSKDUwKTsKDQotLSANCi0tIEhNIGJl
Z2luIHNlbnRlbmNlCklGIEVYSVNUUyAoU0VMRUNUICogRlJPTSBJTkZPUk1BVElPTl9TQ0hFTUEu
VEFCTEVTIFdIRVJFIFRBQkxFX05BTUUgPSBOJ1VTVUFSSU9TQksnKQpCRUdJTgogICAgQUxURVIg
VEFCTEUgVVNVQVJJT1NCSwpBREQJCQpVU1VBUklPUkVEIFZBUkNIQVIoNTApCkVORAotLSBITSBl
bmQgc2VudGVuY2U7Cg0KCgoNCg==', NULL, 0);
