EXECUTE('
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (7590, 7590, ''Retiro Topaz POS'', ''Retiro Topaz POS'', ''7590'', ''N'', 500, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (7590, 1, 2, 0)

')

EXECUTE('
IF OBJECT_ID (''dbo.CRE_ADELANTOS_HABERES'') IS NOT NULL
	DROP TABLE dbo.CRE_ADELANTOS_HABERES
')

EXECUTE('
CREATE TABLE dbo.CRE_ADELANTOS_HABERES
	(
	JTS_OID_CV		NUMERIC(15) NOT NULL,
	FECHA			DATETIME NOT NULL,
	IMPORTE			NUMERIC(15,2),
	PRODUCTO		NUMERIC(5),
	CUOTAS			NUMERIC(5),
	PERIODICIDAD	NUMERIC(5),
	CANAL			VARCHAR(5),
	TZ_LOCK			NUMERIC(15),
	ESTADO			VARCHAR(1),
	NRO_RESERVA		NUMERIC(15),
	CONSTRAINT PK_ADELANTOS PRIMARY KEY (JTS_OID_CV, FECHA, PRODUCTO, CANAL)
	)
')


EXECUTE('
INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (752, ''Días adelanto'', NULL, 10, NULL, 0, 0, 0)

INSERT INTO dbo.CRE_PARAMETROS (TZ_LOCK, CODIGO, DESCRIPCION, UTILIZADO, IMPORTE, DIASINMOVILIZADA, DIAS_OPEVENCIDAS, MONEDA, FECHA_CONTROL, SUCURSAL_CALL_CENTER, PARAMETRO_ALFA)
VALUES (0, 503, ''Producto adelanto haberes'', ''S'', 0, 0, 0, 0, NULL, 0, ''517'')
')

EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (550, 4365, NULL, ''CRE_ADELANTOS_HABERES'', 0, ''CRE_ADELANTOS_HABERES'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43949, '' '', 0, ''JTS OID CV'', ''JTS OID CV'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''JTS_OID_CV'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43950, '' '', 0, ''Fecha'', ''Fecha'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4365, ''FECHA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43952, '' '', 0, ''Importe'', ''Importe'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4365, ''IMPORTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43953, '' '', 0, ''Producto'', ''Producto'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''PRODUCTO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43954, '' '', 0, ''Cuotas'', ''Cuotas'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''CUOTAS'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43955, '' '', 0, ''PERIODICIDAD'', ''Periodicidad'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''PERIODICIDAD'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43956, '' '', 0, ''Canal'', ''Canal'', 5, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''CANAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43957, '' '', 0, ''Estado'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4365, ''ESTADO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43958, '' '', 0, ''Nro reserva'', ''Nro Reserva'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4365, ''NRO_RESERVA'', 0, NULL)

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4365, 1, ''Indice'', 0, 43949, 43950, 43953, 43956, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

DELETE FROM CRE_PRODUCTOSCANALDIGITAL WHERE PRODUCTO IN (50701,50801)

INSERT INTO dbo.CRE_PRODUCTOSCANALDIGITAL (PRODUCTO, CANAL, HABILITADO, PORCENTAJE_AFECTACION, CANT_MAX_CUOTAS, SCORING_MINIMO, SCORING_MAXIMO, CANAL_PRESENCIAL, TZ_LOCK, COBRA_SELLOS)
VALUES (50701, ''AT'', ''S'', 100, 1, 50, 99999999, ''S'', 0, ''N'')

INSERT INTO dbo.CRE_PRODUCTOSCANALDIGITAL (PRODUCTO, CANAL, HABILITADO, PORCENTAJE_AFECTACION, CANT_MAX_CUOTAS, SCORING_MINIMO, SCORING_MAXIMO, CANAL_PRESENCIAL, TZ_LOCK, COBRA_SELLOS)
VALUES (50801, ''AT'', ''S'', 100, 1, 50, 99999999, ''S'', 0, ''N'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43957, ''E'', ''Ingresado'', ''I'', ''I'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43957, ''E'', ''Procesado'', ''P'', ''P'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43957, ''E'', ''Sin procesar'', ''S'', ''S'')
')