EXECUTE('

DELETE CI_CARGOS WHERE ID_CARGO=285

INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (285, ''SELLOS CHACO - COFRE DE SEGURIDAD'', ''N'', ''N'', 285, ''N'', 250, 58382, 1, 0, 9999999999999, ''C'', 0, 0, 0, ''N'', 9999, 0, NULL, NULL, ''R'', ''R'', ''N'', 2, ''F'', ''N'', ''30651205'', ''20001212'', 0, ''N'', 210, ''N'', ''I'', ''N'', 0, 0, 0, 0, 0, NULL, 0, NULL, NULL, NULL, ''N'', 10)


DELETE CI_FORMULAS WHERE ID_FORMULA IN (250,263,264,265)
INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (250, ''CONDICIÓN SELLOS <> CABA (SUC EJECUCIÓN)'', ''(C9502#19)Y(C33104#''''E'''')'', 0, 1)


INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (263, ''CONDICIÓN SELLOS <> CABA (SUC EJECUCIÓN) PRÉSTAMO'', ''(C9502#19)Y(C1983=5)Y((C33104#''''E'''')O(C6800=''''PP''''OC6800=''''AH''''))'', 0, 1)


INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (264, ''CONDICIÓN SELLOS = CABA (SUC EJECUCIÓN)PRESTAMO'', ''(C9502=19)Y(C1983=5)Y((C33104#''''E'''')O(C6800=''''PP''''OC6800=''''AH''''))'', 0, 1)


INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (265, ''CONDICIÓN SELLOS <> CABA (SUC EJECUCIÓN) DESCUENTO'', ''(C9502#19)Y(C1983=6)Y((C33104#''''E'''')O(C33104#''''D''''))'', 0, 1)

')