EXECUTE('
IF OBJECT_ID (''dbo.PREV_CATEG_A'') IS NOT NULL
	DROP TABLE dbo.PREV_CATEG_A
')

EXECUTE('
CREATE TABLE dbo.PREV_CATEG_A
	(
	TZ_LOCK    NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CATEGORIA  VARCHAR (3) NOT NULL,
	MODALIDAD  VARCHAR (1) NOT NULL,
	TIPO_BCRA  NUMERIC (2) NOT NULL,
	PORCENTAJE NUMERIC (5, 2) DEFAULT ((0)) NOT NULL,
	DIAS_TOP   NUMERIC (5) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_PREV_CATEG_A PRIMARY KEY (CATEGORIA, MODALIDAD ,TIPO_BCRA)
	)
')



