EXECUTE('
ALTER PROCEDURE dbo.SP_CESIONCARTERA
   @P_NUMEROCESION numeric(10),
   @P_USAFAMILIA varchar(1),
   @P_FAMILIA numeric(12),
   @P_USAPRODUCTO varchar(1),
   @P_PRODUCTO numeric(5),
   @P_USASUCURSAL varchar(1),
   @P_SUCURSAL numeric(5),
   @P_USASITUACION varchar(1),
   @P_SITUACION varchar(3),      
   @P_USAGARANTIA varchar(1),
   @P_GARANTIA varchar(1),      
   @P_USATASA varchar(1), 
   @P_TASADESDE numeric(15,2),
   @P_TASAHASTA numeric(15,2),
   @P_USAPORCENTAJE varchar(1),
   @P_PORCENTAJEPAGO numeric(5,2),
   @P_USAVENCIMIENTO varchar(1),
   @P_VENCIMIENTO datetime
AS 
	BEGIN            	 
      
      INSERT INTO dbo.CRE_DET_CESIONCARTERA (NUMERO_CESION, JTS_OID_ASISTENCIA, ESTADO, TZ_LOCK)
      SELECT @P_NUMEROCESION, a.JTS_OID, ''A'', 0
      FROM VW_ASISTENCIAS a
      WHERE a.SALDO > 0 AND a.TIPO = 5 AND a.JTS_OID NOT IN (SELECT JTS_OID_ASISTENCIA FROM CRE_DET_CESIONCARTERA WHERE TZ_LOCK = 0 AND NUMERO_CESION NOT IN (SELECT NUMERO_CESION FROM CRE_CAB_CESIONCARTERA WHERE TZ_LOCK = 0 AND ESTADO IN (''I'',''C''))) AND
      ((a.FAMILIA = @P_FAMILIA AND @P_USAFAMILIA = ''S'') OR @P_USAFAMILIA = ''N'') AND
      ((a.PRODUCTO = @P_PRODUCTO AND @P_USAPRODUCTO = ''S'') OR @P_USAPRODUCTO = ''N'') AND
      ((a.SUCURSAL = @P_SUCURSAL AND @P_USASUCURSAL = ''S'') OR @P_USASUCURSAL = ''N'') AND
      ((a.SITUACION = @P_SITUACION AND @P_USASITUACION = ''S'') OR @P_USASITUACION = ''N'') AND
      ((a.GARANTIA_DESEMBOLSO = @P_GARANTIA AND @P_USAGARANTIA = ''S'') OR @P_USAGARANTIA = ''N'') AND
      ((a.TASA >= @P_TASADESDE AND a.TASA <= @P_TASAHASTA AND @P_USATASA = ''S'') OR @P_USATASA = ''N'') AND
      ((a.PORCENTAJE_PAGO >= @P_PORCENTAJEPAGO AND @P_USAPORCENTAJE = ''S'') OR @P_USAPORCENTAJE = ''N'') AND
      ((a.VENCIMIENTO >= CONVERT(datetime, @P_VENCIMIENTO, 103) AND @P_USAVENCIMIENTO = ''S'') OR @P_USAVENCIMIENTO = ''N'')
      
    END
')


EXECUTE('
CREATE OR ALTER VIEW [dbo].[VW_TARJETAS_CRED] 
AS 

SELECT TOP 9223372036854775807 WITH TIES
	u.USUARIO AS [Num Usuario],
	a.COD_ADMINISTRADORA AS [Cod Administradora],
	a.DESCRIPCION AS [Administradora],
    CASE WHEN ts.PERIODO_DEUDA>0 THEN 
    CONCAT(RIGHT(CAST(ts.PERIODO_DEUDA AS varchar(8)),2) ,''/'', LEFT(CAST(ts.PERIODO_DEUDA AS varchar(8)),4)) 
    ELSE '' '' END AS [Periodo Deuda],
	u.CODIGO_CIERRE AS [Num Cartera],
	u.DESCRIPCION_CIERRE AS [Cartera],
	u.TIPO_COBRO AS [Tipo Cobro],
	u.TIPO_PAGO AS [Tipo Pago],
	u.CUENTA_COBRO AS [Cuenta Debito],
	u.CLIENTE AS [Cliente],
	ts.SALDO_MN_CIERRE AS [Saldo Pesos Cierre],
	ts.PAGO_MN AS [Pago Pesos],
	ts.SALDO_MN AS [Saldo Pesos],
	ts.SALDO_ME_CIERRE AS [Saldo Dolares Cierre],
	ts.PAGO_ME AS [Pago Dolares],
	ts.SALDO_ME AS [Saldo Dolares],
	ts.FECHA_VTO AS [Fecha Vencimiento],
	ts.FECHA_CIERRE AS [Fecha Cierre]
FROM TJC_MAESTRO_USUARIO u WITH(NOLOCK)
INNER JOIN TJC_MAESTRO_ADMINISTRADORAS a WITH(NOLOCK) ON a.COD_ADMINISTRADORA=u.ADMINISTRADORA 
												AND a.TZ_LOCK=0
												and u.TZ_LOCK=0
INNER JOIN TJC_SALDOS ts WITH(NOLOCK) ON ts.ADMINISTRADORA=a.COD_ADMINISTRADORA 
									AND ts.USUARIO=u.USUARIO 
									AND ts.TZ_LOCK=0
ORDER BY  [Periodo Deuda] DESC 
')

