EXECUTE ('
CREATE OR ALTER  VIEW [dbo].[VW_PODERES_PERSONAS_COFRES] (
													   NUMERO_CONTRATO, 
													   TIPODOC, 
													   NUMERODOC, 
													   NUMEROPERSONA, 
													   TITULARIDAD, 
													   TIPOPERSONA, 
													   NOMBRE, 
													   PODER, 
													   ESTADO, 
													   DEPENDENCIA)
AS 
SELECT 
      --SUBSTRING(CAST(w.NROCUENTA AS VARCHAR),2,LEN(w.NROCUENTA)-1) AS numero_contrato, 
      x.[CODIGO],
      v.TIPODOCUMENTO AS tipodoc, 
      v.NUMERODOCUMENTO AS numerodoc, 
      v.NUMEROPERSONAFJ AS numeropersona, 
      CASE WHEN (CP.CODIGOCLIENTE IS NULL AND IT.NUMEROPERSONAJURIDICA IS NULL) THEN ''AUTORIZADO''
         ELSE ''TITULAR''
      END AS titularidad, 
      v.TIPOPERSONA,
      ISNULL(u.PRIMERNOMBRE, '''') + '' '' + ISNULL(u.APELLIDOPATERNO, '''') + '' '' + ISNULL(u.APELLIDOMATERNO, '''') AS NOMBRE, 
      w.TIPO_PODER, 
      x.ESTADO, 
      y.DEPENDENCIA
   FROM 
   	dbo.PYF_APODERADOS  AS w WITH (NOLOCK)
   	INNER JOIN dbo.CLI_PERSONASFISICAS AS u WITH (NOLOCK) ON w.ID_PERSONA=U.NUMEROPERSONAFISICA AND u.TZ_LOCK=0
   	INNER JOIN dbo.CLI_DOCUMENTOSPFPJ  AS v WITH (NOLOCK) ON U.NUMEROPERSONAFISICA=V.NUMEROPERSONAFJ AND v.TZ_LOCK = 0 
   	INNER JOIN dbo.COF_COFRES  AS y WITH (NOLOCK) ON w.ID_ENTIDAD = y.CODIGO AND y.TZ_LOCK = 0	
    INNER JOIN dbo.COF_COFRES_CONTRATOS  AS x WITH (NOLOCK) ON y.CODIGO = x.CODIGO_COFRE AND x.TZ_LOCK = 0 AND x.ESTADO IN (''M'',''C'',''V'') 
    LEFT JOIN CLI_ClientePersona AS CP WITH (NOLOCK) ON CP.NUMEROPERSONA=U.NUMEROPERSONAFISICA AND CP.TZ_LOCK=0 AND x.CLIENTE=CP.CODIGOCLIENTE
    LEFT JOIN CLI_ClientePersona AS CPJ WITH (NOLOCK) ON CPJ.CODIGOCLIENTE=X.CLIENTE AND CPJ.TZ_LOCK=0
    LEFT JOIN CLI_INTEGRANTESPJ AS IT WITH (NOLOCK) ON IT.NUMEROPERSONAFISICA=U.NUMEROPERSONAFISICA AND IT.TZ_LOCK=0 AND IT.NUMEROPERSONAJURIDICA=CPJ.NUMEROPERSONA
    WHERE w.TIPO_ENTIDAD=3 AND w.TZ_LOCK=0

')