EXECUTE('IF OBJECT_ID (''SL_NOSIS_CALCULOCDA'') IS NOT NULL
	DROP TABLE SL_NOSIS_CALCULOCDA')
EXECUTE('
CREATE TABLE SL_NOSIS_CALCULOCDA
	(
	CLAVE         VARCHAR (20) DEFAULT ('' '') NULL,
	DETALLE       VARCHAR (50) DEFAULT ('' '') NULL,
	NRO           NUMERIC (3) DEFAULT ((0)) NULL,
	DESCRIPCION   VARCHAR (50) DEFAULT ('' '') NULL,
	VALOR         VARCHAR (10) DEFAULT ('' '') NULL,
	TIPO          NUMERIC (1) DEFAULT ((0)) NULL,
	CUIT          VARCHAR (11) DEFAULT ('' '') NOT NULL,
	FECHA_PROCESO DATETIME NOT NULL,
	ORDINAL       NUMERIC (15) DEFAULT ((0)) NOT NULL,
	TZ_LOCK       NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SL_NOSIS_CALCULOCDA_01 PRIMARY KEY (CUIT,FECHA_PROCESO,ORDINAL)
	)
')

EXECUTE('IF OBJECT_ID (''SL_NOSIS_DATOS'') IS NOT NULL
	DROP TABLE  SL_NOSIS_DATOS')

EXECUTE(' CREATE TABLE SL_NOSIS_DATOS
	(
	DOC          VARCHAR (11) DEFAULT ('' '') NOT NULL,
	TIPO_DOC     VARCHAR (4) DEFAULT ('' '') NOT NULL,
	RAZON_SOCIAL VARCHAR (70) DEFAULT ('' '') NULL,
	FECHA_NAC    DATETIME NULL,
	EDAD         NUMERIC (3) DEFAULT ((0)) NULL,
	COD_ACT      VARCHAR (6) DEFAULT ('' '') NULL,
	MONOTRIBUTO  VARCHAR (70) DEFAULT ('' '') NULL,
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SL_NOSIS_DATOS_01 PRIMARY KEY (DOC,TIPO_DOC)
	)')

EXECUTE('IF OBJECT_ID (''SL_NOSIS_ULTIMOINFORME'') IS NOT NULL
	DROP TABLE  SL_NOSIS_ULTIMOINFORME')


EXECUTE('
CREATE TABLE  SL_NOSIS_ULTIMOINFORME
	(
	COD_ENTIDAD           NUMERIC (3) DEFAULT ((0)) NULL,
	ENT_COD               VARCHAR (20) DEFAULT ('' '') NULL,
	MONTO                 NUMERIC (12,5) DEFAULT ((0)) NULL,
	PERIODO               NUMERIC (6) DEFAULT ((0)) NULL,
	PROC_JUD              NUMERIC (1) DEFAULT ((0)) NULL,
	LINEA_TOTAL           NUMERIC (15,2) DEFAULT ((0)) NULL,
	COD_LINEA             NUMERIC (12) DEFAULT ((0)) NULL,
	ENTIDAD               VARCHAR (50) DEFAULT ('' '') NULL,
	SIT                   NUMERIC (1) DEFAULT ((0)) NULL,
	COMPROMISOS_MENSUALES NUMERIC (15,2) DEFAULT ((0)) NULL,
	CUIT                  VARCHAR (11) DEFAULT ('' '') NOT NULL,
	FECHA_PROCESO         DATETIME NOT NULL,
	ORDINAL               NUMERIC (15) DEFAULT ((0)) NOT NULL,
	MONTO_TOTAL           NUMERIC (15,2) DEFAULT ((0)) NULL,
	TZ_LOCK               NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SL_NOSIS_ULTIMOINFORME_01 PRIMARY KEY (CUIT,FECHA_PROCESO,ORDINAL)
	)')





