EXECUTE('


CREATE VIEW VW_AYUDA_MEDIOSPAGO
AS
SELECT M.ID_ConvPago AS ''Id Convenio'', C.NomConvRec AS ''Nombre Convenio'', M.Id_TpoConv AS ''Tipo Convenio'', T.DscTpoConv AS ''Descripción Tipo'',
M.MedioPago AS ''Medio Pago'', M.Estado AS ''Estado''
FROM CONV_MEDIOPAGO M JOIN CONV_CONVENIOS_REC C ON M.ID_ConvPago = C.Id_ConvRec AND M.TZ_LOCK = 0 AND C.TZ_LOCK = 0
JOIN CONV_TIPOS T ON T.Id_TpoConv = C.Id_TpoConv AND T.TZ_LOCK = 0
')

EXECUTE ('

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 9655
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45147

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (9655, '' '', 0, ''Ayuda Cuentas Vista Cliente'', ''Ayuda Cuentas Vista'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 245, 0, 0, ''Ayuda Cuentas Vista'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45147, '' '', 0, ''Largo Id Referencia'', ''Largo Id Referencia'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4477, ''LARGO_ID'', 0, NULL)

DELETE FROM OPCIONES
WHERE NUMERODECAMPO = 44737 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''R''

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44737, ''E'', ''Recaudación'', ''R'', ''R'')

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 45545, ''Ayuda Medios de Pago Convenios'', '''', 0, ''9064R;3264;9096R;3260;8222R;3255;'', ''Id Convenio;Nombre Convenio;Tipo Convenio;Descripción Tipo;Medio Pago;Estado;'', ''TOP/CLIENTES'', ''VW_AYUDA_MEDIOSPAGO'', 0)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 44823

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44823, '' '', 0, ''Campo ayuda Medio de Pago'', NULL, 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 45545, 0, 0, NULL, 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3370, '' '', 0, ''Denominacion Cuenta'', ''Denominacion Cuenta'', 100, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Denominacion Cuenta'', 0, NULL)

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 45451, ''Ayuda cuentas con denominación'', '''', 0, ''2615R;3370R;2614R;2612R;2611R;2613R;3491R;2617R;'', ''Cuenta;Nombre;Moneda;Sucursal;Cliente;Producto;Operacion;Ordinal;'', ''TOP/CLIENTES'', ''VW_CUENTAS'', 0)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3509, '' '', 0, ''Ayuda cuentas con denominación'', ''Ayuda cuentas con denominación'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 45451, 0, 0, ''Ayuda cuentas C/D'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3491, '' '', 0, ''Operacion largo 13'', ''Operacion largo 13'', 13, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Operacion largo 13'', 0, NULL)

DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45146 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''1''

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45146, ''E'', ''Formato Débitos Automáticos'', ''1'', ''1'')

INSERT INTO MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (450, 0, 3440, 2, ''PA nombre cuentas vista'', NULL, NULL)

INSERT INTO MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (450, 1, 3440, 2, ''C34487=C3992'', ''C3370'', ''C34402'')

')