execute('
CREATE TABLE SALDOSATM_HISTORICO
	(
	NRO_ATM       NUMERIC (5) DEFAULT ((0)) NOT NULL,
	MONEDA        NUMERIC (4) DEFAULT ((0)) NOT NULL,
	FECHAPROCESO  DATETIME NOT NULL,
	SALDO_INICIAL NUMERIC (15, 2) DEFAULT ((0)),
	ENTRADAS      NUMERIC (15, 2) DEFAULT ((0)),
	SALIDAS       NUMERIC (15, 2) DEFAULT ((0)),
	DEPOSITOS     NUMERIC (15, 2) DEFAULT ((0)),
	RETIROS       NUMERIC (15, 2) DEFAULT ((0)),
	TZ_LOCK       NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SALDOSATM_HISTORICO_01 PRIMARY KEY (NRO_ATM, MONEDA,FECHAPROCESO)
	)

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49259, ''E'', ''Habilitado'', ''H'', ''H'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49259, ''E'', ''Inhabilitado'', ''I'', ''I'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49265, '' '', 0, ''Pago/Deposito'', ''Pago/Deposito'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Pago/Deposito'', 0, NULL)

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49265, ''E'', ''Depósito'', ''D'', ''D'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (49265, ''E'', ''Pago'', ''P'', ''P'')

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4909, 49091, ''Ayuda Saldos ATM'', '''', 0, ''49270R;49271R;49272;49273;49274;49275;49276;49277;49278;'', NULL, NULL, NULL, 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (58298, '' '', 0, ''Ayuda SALDOSATM'', ''Ayuda SALDOSATM'', 0, ''A'', 0, NULL, 0, 0, 0, 0, 0, 49091, 0, 0, ''Ayuda SALDOSATM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (58299, '' '', 0, ''Ayuda Categorias ATM'', ''Ayuda Categorias ATM'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49101, 0, 0, ''Ayuda Categorias ATM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (58300, '' '', 0, ''Ayuda ATM'', NULL, 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 90845, 0, 0, ''Ayuda ATM'', 0, NULL)
	
	
')