EXECUTE('
-----------------------------------
--NUEVO CAMPO CONTROLA RESIDENTES--
-----------------------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35369, '' '', 0, ''Permitido para No Residentes'', ''Permitido para No Residentes'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 311, ''PERMITE_NO_RESI'', 0, NULL)
----
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35369, ''E'', ''No'', ''N'', ''N'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35369, ''E'', ''Si'', ''S'', ''S'')
----
UPDATE dbo.TOPESPRODUCTO
SET PERMITE_NO_RESI = ''S''
WHERE CODPRODUCTO IN (SELECT C6250 FROM PRODUCTOS WHERE C6252 = 4) 
	AND CODPRODUCTO NOT IN (103, 104)
--
UPDATE dbo.TOPESPRODUCTO
SET PERMITE_NO_RESI = ''N''
WHERE CODPRODUCTO IN (103, 104)
----
')


