EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99945, '' '', 0, ''Deuda Total'', ''Ay. Deuda Total'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49550, 0, 0, ''Ayuda Deuda Total'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99946, '' '', 0, ''Ay. Posicion Cliente Detalle'', ''Ay. Pos Cliente Detalle'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49551, 0, 0, ''Ay. Posicion Cliente Detalle'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (99947, '' '', 0, ''Ay Posicion Totales'', NULL, 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49552, 0, 0, ''Posicion Totales'', 0, NULL)

')