Execute('IF OBJECT_ID (''dbo.ITF_I2000_COD_MOV'') IS NOT NULL
	DROP TABLE dbo.ITF_I2000_COD_MOV

CREATE TABLE dbo.ITF_I2000_COD_MOV
	(
	COD_SISTEMA    VARCHAR (1) NOT NULL,
	COD_MOVIMIENTO VARCHAR (11) NOT NULL,
	DESCRIPCION    VARCHAR (55) NULL,
	FECHAPROCESO   NUMERIC (8) NULL,
	CONSTRAINT PK_ITF_I2000_COD_MOV PRIMARY KEY (COD_SISTEMA, COD_MOVIMIENTO)
	)')

Execute('IF OBJECT_ID (''dbo.TMP_TRANSFERENCIAS_ORIGEN_DESTINO'') IS NOT NULL
	DROP TABLE TMP_TRANSFERENCIAS_ORIGEN_DESTINO 

CREATE TABLE dbo.TMP_TRANSFERENCIAS_ORIGEN_DESTINO (
	FILA BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DATO VARCHAR(1000) NOT NULL,
	NOMBREARCHIVO VARCHAR(100) NOT NULL,
	DES_ERROR VARCHAR(1000) NULL
);')

Execute('IF OBJECT_ID (''dbo.TRANSFERENCIAS_ORIGEN_DESTINO'') IS NOT NULL
	DROP TABLE dbo.TRANSFERENCIAS_ORIGEN_DESTINO;

CREATE TABLE dbo.TRANSFERENCIAS_ORIGEN_DESTINO (
	TIPO varchar(12) COLLATE Modern_Spanish_CI_AS DEFAULT ''ORIGINANTE'' NOT NULL,
	PERIODO date NOT NULL,
	LINEA numeric(15,0) IDENTITY(1,1) NOT NULL,
	FIID_ORI numeric(4,0) NULL,
	PAN numeric(19,0) NULL,
	[MEMBER] varchar(3) COLLATE Modern_Spanish_CI_AS NULL,
	FIID_DEST numeric(4,0) NULL,
	CTA_TIPO varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	CTA_NRO numeric(19,0) NULL,
	CTA_ORIG numeric(19,0) NULL,
	TYP_MSJ varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	TRAN_CDE varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
	RESP varchar(3) COLLATE Modern_Spanish_CI_AS NULL,
	POST_DATE numeric(6,0) NULL,
	TRAN_DATE numeric(6,0) NULL,
	TRAN_TIME numeric(6,0) NULL,
	FIID_TER varchar(4) COLLATE Modern_Spanish_CI_AS NULL,
	ID varchar(12) COLLATE Modern_Spanish_CI_AS NULL,
	TYP_TER varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	SEQ varchar(12) COLLATE Modern_Spanish_CI_AS NULL,
	AMT numeric(10,0) NULL,
	MONEDA numeric(3,0) NULL,
	TIPO_CAMBIO varchar(10) COLLATE Modern_Spanish_CI_AS NULL,
	TITULAR_CTA_DEST varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	CDI numeric(11,0) NULL,
	MOTIVO varchar(3) COLLATE Modern_Spanish_CI_AS NULL,
	REFERENCIA varchar(12) COLLATE Modern_Spanish_CI_AS NULL,
	NOMBRE varchar(22) COLLATE Modern_Spanish_CI_AS NULL,
	DNI_DEST numeric(11,0) NULL,
	TIPO_CTA_ORIG varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	AMT_EXT varchar(15) COLLATE Modern_Spanish_CI_AS NULL,
	TERM_ID_16 varchar(16) COLLATE Modern_Spanish_CI_AS NULL,
	RAZON_SOC varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	NOMBRE_FANT varchar(50) COLLATE Modern_Spanish_CI_AS NULL,
	SUBCONCEPTO varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	TIPO_TRAN varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	AUTH_ID_RESP varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
	CVU_DESTINO numeric(22,0) NULL,
	CUIT_DESTINO numeric(11,0) NULL,
	ID_BILLETERA numeric(11,0) NULL,
	CVU_BILLETERA numeric(22,0) NULL,
	ID_QR varchar(64) COLLATE Modern_Spanish_CI_AS NULL,
	DEV_AUTH_ID_RESP varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
	COD_BILL_BCRA varchar(5) COLLATE Modern_Spanish_CI_AS NULL,
	TRANSF_TYPE varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	FILLER varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	CONSTRAINT PK_TRANSF_ORIGEN_DESTINO PRIMARY KEY (TIPO,PERIODO,LINEA)
);')

Execute('INSERT INTO dbo.ITF_MASTER (TZ_LOCK, ID, DESCRIPCION, OBJ_KETTLE, P0_MODO, P0_TIPO, P0_CAPTION, P0_CONSTANTE, P1_MODO, P1_TIPO, P1_CAPTION, P1_CONSTANTE, P2_MODO, P2_TIPO, P2_CAPTION, P2_CONSTANTE, P3_MODO, P3_TIPO, P3_CAPTION, P3_CONSTANTE, P4_MODO, P4_TIPO, P4_CAPTION, P4_CONSTANTE, P5_MODO, P5_TIPO, P5_CAPTION, P5_CONSTANTE, P6_MODO, P6_TIPO, P6_CAPTION, P6_CONSTANTE, P7_MODO, P7_TIPO, P7_CAPTION, P7_CONSTANTE, P8_MODO, P8_TIPO, P8_CONSTANTE, P8_CAPTION, P9_MODO, P9_TIPO, P9_CAPTION, P9_CONSTANTE, TIPO_OBJ, COMENTARIO, ID_REPORTE, MODO_EJECUCION)
VALUES (0, 265, ''I2000 Carga Movimientos'', ''ITF_I2000_CARGA_MOVIMIENTOS.kjb'', '''', '''', '''', '' '', '''', '''', '''', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', ''J'', '' '', 0, ''M'')')
