/****** Object:  View [dbo].[VW_PROD_CANDIDATOS]    Script Date: 24/02/2021 15:26:08 ******/
DROP VIEW [dbo].[VW_PROD_CANDIDATOS]
GO

/****** Object:  View [dbo].[VW_PROD_CANDIDATOS]    Script Date: 24/02/2021 15:26:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_PROD_CANDIDATOS]
AS
		SELECT	c.PRODUCTO, 
				s.SEGMENTO, 
				s.SUBSEGMENTO, 
				t.SECTOR,
				c.CANT_MIN, 
				c.CANT_MAX, 
				c.MAYOR_EDAD, 
				c.MENOR_ADOLESCENTE,
				c.MENOR_EMANCIPADO, 
				c.MENOR_AUTORIZADO, 
				c.TIPO_CLIENTE,
				c.TITULAR_APODERADO 
		FROM PROD_RELCLIENTE c with (nolock) 
			INNER JOIN PROD_RELSEGMENTOS s with (nolock) ON s.PRODUCTO=c.PRODUCTO
			INNER JOIN PROD_RELSECTORES t with (nolock) ON t.PRODUCTO=c.PRODUCTO 
		WHERE s.TZ_LOCK=0 
			AND c.TZ_LOCK=0 
			AND t.TZ_LOCK=0
GO


