INSERT INTO dbo.PROD_RESTRICCIONES (CODPRODUCTO, MONEDA, TIPO_RESTRICCION, TIPO_CONTROL, IMPORTE_LIMITE, TIPO_LIMITE, FORMA_APLICACION, DETALLE_CODIGOS, TIPO_BLOQUEO, MENSAJE, TZ_LOCK)
VALUES (51, 1, 'D', 'M', 50000, 'D', 'I', '11', 'A', 'Supero el saldo máximo permitido', 0)
GO

