EXECUTE('
-----------------------------------
--AJUSTE TABLA SNP_TRANSFERENCIAS--
-----------------------------------
UPDATE dbo.DICCIONARIO
SET CAMPO = ''ID_TRANSFERENCIA''
WHERE NUMERODECAMPO = 44703
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''ORIGEN''
WHERE NUMERODECAMPO = 44704
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''CUIT_EO''
	, LARGO = 11
WHERE NUMERODECAMPO = 44705
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''CODIGO_CLIENTE''
	, LARGO = 12
	, TIPODECAMPO = ''N''
WHERE NUMERODECAMPO = 44706
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''FECHA_ALTA''
WHERE NUMERODECAMPO = 44707
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''FECHA_ACREDITACION''
WHERE NUMERODECAMPO = 44708
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''FECHA_COMPENSACION''
WHERE NUMERODECAMPO = 44709
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''REFERENCIA''
WHERE NUMERODECAMPO = 44710
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''SENTIDO''
WHERE NUMERODECAMPO = 44711
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''TIPO_TRANSFERENCIA''
WHERE NUMERODECAMPO = 44712
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''NOMBRE_ORIGINANTE''
WHERE NUMERODECAMPO = 44713
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''OPERATIVA''
WHERE NUMERODECAMPO = 44714
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''TIPO_DOC_BENEFICIARIO''
WHERE NUMERODECAMPO = 44715
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''DOCUMENTO_BENEFICIARIO''
	, LARGO = 20
WHERE NUMERODECAMPO = 44716
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''NOMBRE_BENEFICIARIO''
WHERE NUMERODECAMPO = 44717
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''MONEDA''
WHERE NUMERODECAMPO = 44718
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''IMPORTE''
WHERE NUMERODECAMPO = 44719
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''CBU_RECEPTOR''
WHERE NUMERODECAMPO = 44720
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''JTS_OID_RECEPTOR''
WHERE NUMERODECAMPO = 44721
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''CBU_ORIGEN''
WHERE NUMERODECAMPO = 44722
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''JTS_OID_ORIGEN''
WHERE NUMERODECAMPO = 44723
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''COD_TRANSACCION''
WHERE NUMERODECAMPO = 44724
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''INFO_ADICIONAL''
WHERE NUMERODECAMPO = 44725
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''MOTIVO_RECHAZO''
WHERE NUMERODECAMPO = 44726
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''ESTADO''
WHERE NUMERODECAMPO = 44727
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''FECHA_ASIENTO''
WHERE NUMERODECAMPO = 44728
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''ASIENTO''
WHERE NUMERODECAMPO = 44729
--
UPDATE dbo.DICCIONARIO
SET CAMPO = ''JTS_OID_FINAL''
WHERE NUMERODECAMPO = 44730
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45316, '' '', 0, ''Sucursal Asiento'', ''Sucursal Asiento:'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4467, ''SUCURSAL_ASIENTO'', 0, NULL)
----
')