EXECUTE('
UPDATE CRE_SOL_ACREDITACIONES_SUELDOS SET ID_JURISDICCION =''0''
')

EXECUTE('
UPDATE CONV_CONVENIOS_PAG SET TipoDominio=''O'' WHERE ID_ConvPago NOT IN (313,587)
UPDATE CONV_CONVENIOS_PAG SET TipoDominio=''J'' WHERE ID_ConvPago =313
UPDATE CONV_CONVENIOS_PAG SET TipoDominio=''B'' WHERE ID_ConvPago =587
')

EXECUTE('
DELETE FROM CONV_DOMINIOS
')

EXECUTE('
INSERT INTO CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
SELECT 0, pag.ID_ConvPago, 0, ''SIN DOMINIO'', pag.CuentaDeb, 0, 0, ''N'', ''N'', ''SIN SUB DOMINIO'',''N'', 0   
FROM CONV_CONVENIOS_PAG pag
WHERE pag.Id_TpoConv=3 AND  pag.TipoDominio=''O'' AND  pag.TZ_LOCK=0

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 1, ''PODER LEGISLATIVO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 2, ''GOBERNACION'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 3, ''MINISTERIO DE GOBIERNO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 4, ''MINISTERIO HACIENDA Y FINANZAS PUBLICAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 5, ''MINISTERIO DE LA PRODUCCION'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 6, ''MINISTERIO DE SALUD PUBLICA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 7, ''MINISTERIO DE SEGURIDAD PUBLICA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 8, ''TRIBUNAL DE CUENTAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 9, ''PODER JUDICIAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 10, ''INSTITUTO PROVINCIAL DE DESARROLLO URBANO Y VIVIENDA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 11, ''MINISTERIO INDUSTRIA, EMPLEO Y TRABAJO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 12, ''LOTERIA CHAQUEÑA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 13, ''DIRECCION PROVINCIAL DE VIALIDAD'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 14, ''INSTITUTO DE COLONIZACION'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 15, ''INSTITUTO DE INVESTIGACION FORESTAL Y AGROPECUARIA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 16, ''IN.S.S.SE.P. ACTIVOS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 17, ''TRIBUNAL ELECTORAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 18, ''FISCALIA DE ESTADO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 19, ''CONTADURIA Y TESORERIA GENERAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 20, ''DIRECCION GENERAL DE RENTAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 21, ''POLICIA PROVINCIAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 22, ''PROGRAMA REHAB.EMERGENCIAS HIDRICAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 23, ''SECRETARIA DE TRANSPORTE Y OBRAS PUBLICAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 24, ''ADMINISTRACION PROVINCIAL DEL AGUA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 25, ''INSTITUTO DEL ABORIGEN CHAQUE#O'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 26, ''TESORERIA GENERAL DE LA PROVINCIA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 27, ''FISCALIA DE INVESTIGACIONES ADMINISTRATIVAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 28, ''SECRETARIA DE DESARROLLO SOCIAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 29, ''MRIO.DE EDUCACION,CULTURA,CIENCIA Y TECNOLOGIA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 30, ''FONDO NACIONAL DE VIVIENDA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 31, ''RETIRO VOLUNTARIOS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 32, ''SECRETARIA PLANIFICACION Y EVALUACION DE RESULTADOS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 33, ''AGENCIA DE INVERSION'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 34, ''INSTITUTO DE LA CULTURA DEL CHACO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 35, ''IN.S.S.SE.P. JUBILADOS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''S'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 36, ''SERVICIO PENITENCIARIO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 37, ''INSTITUTO PROVINCIAL INCLUSIÓN DE PERS.CON DISCAPACIDAD'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 39, ''ADMINISTRACION PORTUARIA PTO.DE BARRANQUERAS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 40, ''CONSEJO DE LA MAGISTRATURA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 42, ''INSTITUTO DE TURISMO DEL CHACO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 44, ''FONDO ESPECIAL. RETIRO LEY 6636'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 45, ''MINISTERIO DE DESARROLLO URBANO Y TERRITORIAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 46, ''SECRETARIA DE DERECHOS HUMANOS'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 47, ''DEFENSORIA DEL PUEBLO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 48, ''INSTITUTO DEL DEPORTE CHAQUEÑO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 49, ''ESCUELA DE GOBIERNO MRIO.DE ECONOMIA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 50, ''COMITÉ PROV. PREV. DE LA TORTURA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 51, ''INSTITUTO PROV. DE ADMINISTRACION PUBLICA DEL CHACO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 52, ''I.D.R.A.F. (INS.DES.RURAL Y AGRIC.FAMILIAR'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 53, ''SECRETARIA DE MUNICIPIOS Y CUIDADES'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 54, ''SECRETARIA DE EMPLEO Y TRABAJO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 60, ''ANSES-JUBILADOS NACIONALES'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 80, ''INSTITUTO DE VIVIENDA - DEPOSITOS JUDICIALES'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 82, ''VIALIDAD PROVINCIAL - DEPOSITOS JUDICIALES'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 83, ''MINISTERIO DE SALUD PUBLICA'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 91, ''LOTERIA CHAQUEÑA-DEP.JUD.PROV'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 92, ''DESARROLLO SOCIAL-DEP.JUD.PROV'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 93, ''INSSSEP.HAB.PERS.PASIVO-DEP.JUD.PROV'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 94, ''CONSEJO DE LA MAGISTRATURA-DEP.JUD.PROV'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 95, ''MINIST.GOBIERNO-DEP.JUD.PROV'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 96, ''VIALIDAD PROVINCIAL'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 97, ''FISCALIA DE ESTADO - DEPOSITOS JUDICIALES'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 98, ''EMPLEADOS DEL NBCH SA.'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO dbo.CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
VALUES (0, 313, 99, ''CODIGO GENERICO'', (SELECT CuentaDeb FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), (SELECT CuentaDebSec FROM CONV_CONVENIOS_PAG WITH (NOLOCK) WHERE ID_ConvPago=313), 0, ''N'', ''J'', ''SIN SUB DOMINIO'', ''N'', 0)

INSERT INTO CONV_DOMINIOS (TZ_LOCK, ID_CONVENIO, ID_DOMINIO, DESCRIPCION, CUENTA_PRINCIPAL, CUENTA_SECUNDARIA, CONC_CONT_TRANSITORIO, RECIBO, TIPO_DOMINIO, DESC_SUB_DOMINIO, TIPO_SUB_DOMINIO, SUB_DOMINIO)
SELECT 0, pag.ID_ConvPago, 0, ''SIN DOMINIO'', pag.CuentaDeb, pag.CuentaDebSec, 0, ''N'', ''N'', ''SIN SUB DOMINIO'',''N'', 0   
FROM CONV_CONVENIOS_PAG pag
WHERE  pag.Id_TpoConv=3 AND pag.TipoDominio=''B'' AND  pag.TZ_LOCK=0
')

