EXECUTE('
IF OBJECT_ID (''dbo.ITF_I2000_MOVS'') IS NOT NULL
	DROP TABLE dbo.ITF_I2000_MOVS
')

EXECUTE('
CREATE TABLE dbo.ITF_I2000_MOVS
	(
	CODSUCURSAL     VARCHAR (4) NOT NULL,
	CODSISTEMA      VARCHAR (1) NOT NULL,
	CUENTA          VARCHAR (11),
	OPERACION       VARCHAR (11) NOT NULL,
	SUBOPERACION    VARCHAR (10),
	CODOPERACIONMOV VARCHAR (11) NOT NULL,
	IMPORTEOPE      VARCHAR (17),
	CODMONEDA       VARCHAR (4),
	TIPOCAMBIO      VARCHAR (11),
	ESPECIE         VARCHAR (10),
	BANCOCORRESP    VARCHAR (12),
	BENEFORDENEXT   VARCHAR (50),
	CODPAISBENEF    VARCHAR (4),
	FECVALOROPE     VARCHAR (8),
	CODSUCORIGENOPE VARCHAR (4),
	NUMBOLETO       VARCHAR (20) NOT NULL,
	FECINGRESO      VARCHAR (8) NOT NULL,
	MARCAREVERSADO  VARCHAR (1),
	CODCONCEPTO     VARCHAR (3),
	TIPOPERSBENEF   VARCHAR (1),
	FECHAPROCESO    VARCHAR (8),
	ESTADO          VARCHAR (1),
	DESESTADO       VARCHAR (150),
	CONSTRAINT ITF_I2000_MOVS_PK PRIMARY KEY (CODSUCURSAL, CODSISTEMA, OPERACION, CODOPERACIONMOV, FECINGRESO, NUMBOLETO)
	)
')

EXECUTE('
IF OBJECT_ID (''dbo.ITF_I2000_MOVS_HIST'') IS NOT NULL
	DROP TABLE dbo.ITF_I2000_MOVS_HIST
')

EXECUTE('
CREATE TABLE dbo.ITF_I2000_MOVS_HIST
	(
	CODSUCURSAL     NUMERIC (4) NOT NULL,
	CODSISTEMA      VARCHAR (1) NOT NULL,
	CUENTA          NUMERIC (11),
	OPERACION       NUMERIC (11) NOT NULL,
	SUBOPERACION    NUMERIC (10),
	CODOPERACIONMOV VARCHAR (11) NOT NULL,
	IMPORTEOPE      NUMERIC (17, 2),
	CODMONEDA       NUMERIC (4),
	TIPOCAMBIO      NUMERIC (11, 6),
	ESPECIE         VARCHAR (10),
	BANCOCORRESP    VARCHAR (12),
	BENEFORDENEXT   VARCHAR (50),
	CODPAISBENEF    NUMERIC (4),
	FECVALOROPE     NUMERIC (8),
	CODSUCORIGENOPE NUMERIC (4),
	NUMBOLETO       NUMERIC (20) NOT NULL,
	FECINGRESO      NUMERIC (8) NOT NULL,
	MARCAREVERSADO  NUMERIC (1),
	CODCONCEPTO     VARCHAR (3),
	TIPOPERSBENEF   VARCHAR (1),
	FECHAPROCESO    NUMERIC (8),
	CONSTRAINT ITF_I2000_MOVS_HIST_PK PRIMARY KEY (CODSUCURSAL, CODSISTEMA, OPERACION, CODOPERACIONMOV, FECINGRESO, NUMBOLETO)
	)
')

EXECUTE('
IF OBJECT_ID (''dbo.ITF_TIPO_CUENTA_OPE'') IS NOT NULL
	DROP TABLE dbo.ITF_TIPO_CUENTA_OPE
')

EXECUTE('
CREATE TABLE dbo.ITF_TIPO_CUENTA_OPE
	(
	TipoCuentaOpe     NUMERIC (3) DEFAULT ((0)) NOT NULL,
	DescTipoCuentaOpe VARCHAR (50) DEFAULT ('' ''),
	CodOperatoria     VARCHAR (1) DEFAULT ('' ''),
	TZ_LOCK           NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_ITF_TIPO_CUENTA_OPE_01 PRIMARY KEY (TipoCuentaOpe)
	)
')