EXECUTE('
--------------------------
--CHE_CHEQUESDENUNCIADOS--
--------------------------
ALTER TABLE CHE_CHEQUESDENUNCIADOS DROP CONSTRAINT PK__CHE_CHEQ__584046F7D4D6CB19
ALTER TABLE CHE_CHEQUESDENUNCIADOS ALTER COLUMN PRODUCTO NUMERIC (6, 0) NOT NULL
ALTER TABLE CHE_CHEQUESDENUNCIADOS ADD CONSTRAINT PK__CHE_CHEQ__584046F7D4D6CB19 PRIMARY KEY (SUCURSAL, MONEDA, CUENTA, PRODUCTO, OPERACION, ORDINAL, NUMEROCHEQUE, SERIE)
---------------------
--CHE_CHEQUES--
---------------------
ALTER TABLE Che_Cheques DROP CONSTRAINT PK_CHE_CHEQUES
ALTER TABLE Che_Cheques ALTER COLUMN PRODUCTO NUMERIC (5, 0) NOT NULL
ALTER TABLE Che_Cheques ADD CONSTRAINT PK_CHE_CHEQUES PRIMARY KEY (SUCURSAL, MONEDA, CUENTA, PRODUCTO, OPERACION, ORDINAL, NUMEROCHEQUE, SERIE)
-------------------------------
--CHE_CHEQUESEXTRAVIADOSINNUM--
-------------------------------
ALTER TABLE CHE_CHEQUESEXTRAVIADOSINNUM ALTER COLUMN PRODUCTO NUMERIC (5, 0) NOT NULL
-------------------------
--GRL_ESTADOS_DE_CUENTA--
-------------------------
ALTER TABLE GRL_ESTADOS_DE_CUENTA DROP CONSTRAINT PK_GRL_ESTADOS_DE_CUENTA
ALTER TABLE GRL_ESTADOS_DE_CUENTA ALTER COLUMN PRODUCTO NUMERIC (5, 0) NOT NULL
ALTER TABLE GRL_ESTADOS_DE_CUENTA ADD CONSTRAINT PK_GRL_ESTADOS_DE_CUENTA PRIMARY KEY (PRODUCTO, SUCURSAL, CUENTA, MONEDA, TIPO_EMISION, OPERACION, ORDINAL)
------
')