EXECUTE('

CREATE VIEW [dbo].[VW_ITF_LINK_UMOZ_H] 
AS
SELECT 
	(RIGHT(''0000000000000000000''+ VT.CTA_REDLINK, 18)) AS ''NROCUENTA'',
	(SELECT CASE 
			WHEN S.C1604 < 0  THEN ''-''+RIGHT(((''00000000''+REPLACE(REPLACE(s.C1604,''-'',''''),''.'',''''))),8)
			WHEN S.C1604 >= 0 THEN ''+''+RIGHT((''00000000''+(REPLACE(s.C1604,''.'',''''))),8) 
			END) AS ''SALDOPLANO'',
	S.C1604 	 AS ''SALDO_ORIGINAL'',
	SPACE(23) 	 AS ''FILLER'',
	ISNULL(HV.CONCEPTO,'''')  AS ''CONCEPTO'',
	(SELECT (CASE 
			WHEN hv.DEBITO_CREDITO = ''C'' THEN (''+''+RIGHT(''00000000''+(REPLACE(HV.MONTO,''.'','''')),8))
			WHEN hv.DEBITO_CREDITO = ''D'' THEN (''-''+RIGHT(''00000000''+(REPLACE(HV.MONTO,''.'','''')),8))
			END)) AS ''IMPORTEDETALLE'',
	(SELECT (CASE 
			WHEN hv.DEBITO_CREDITO = ''C'' THEN (''+'') 
			WHEN hv.DEBITO_CREDITO = ''D'' THEN (''-'') 
			END)) AS ''SIGNO'',
	(SELECT CONVERT(VARCHAR(6),HV.FECHA_VALOR,12)) AS ''FECHA'',
	(SELECT(CASE 
			WHEN S.MONEDA = 1	AND S.C1785 = 2 THEN ''Cuenta Corriente en Pesos''
			WHEN S.MONEDA = 2 	AND S.C1785 = 3 THEN ''Caja Ahorro en Dolares''
			WHEN S.MONEDA = 1 	AND S.C1785 = 3 THEN ''Caja Ahorro en Pesos'' 
			WHEN S.MONEDA = 988 AND S.C1785 = 3 THEN ''Caja Ahorro en Pesos''
			WHEN S.MONEDA = 999 AND S.C1785 = 3 THEN ''Caja Ahorro en Pesos''
			WHEN S.MONEDA = 988 AND S.C1785 = 2 THEN ''Cuenta Corriente en Pesos''
			WHEN S.MONEDA = 999 AND S.C1785 = 2 THEN ''Cuenta Corriente en Pesos'' END)) AS ''TipoDetalle'',
	(SELECT HV.MONTO)  AS IMPORTEORIGINAL,
	S.JTS_OID,
	HV.MOV_JTS_OID,
	AI.ASIENTO,
	AI.HORAFIN,
	ITF.ORDINAL
FROM 	   ITF_MOVCONFORMADOS ITF WITH (NOLOCK)
INNER JOIN HISTORIA_VISTA HV WITH (NOLOCK) ON  ITF.asiento = HV.ASIENTO 
										   AND ITF.fch_procesado = HV.FECHA_PROCESADO 
										   AND ITF.sucursal = HV.SUCURSAL 
										   AND ITF.nro_mov = HV.NUMERO_MOVIMIENTO 
										   AND ITF.ordinal = HV.ORDINAL 
										   AND ITF.TRTIPO = HV.TRTIPO 
										   AND ITF.TRVIRTUAL = HV.TRVIRTUAL 
										   AND ITF.jts_oid = HV.SALDO_JTS_OID
INNER JOIN ASIENTOS AI WITH (NOLOCK) ON HV.ASIENTO=AI.ASIENTO AND HV.SUCURSAL=AI.SUCURSAL AND HV.FECHA_PROCESADO=AI.FECHAPROCESO
INNER JOIN VTA_SALDOS VT WITH (NOLOCK) ON VT.JTS_OID_SALDO = ITF.JTS_OID
INNER JOIN SALDOS S WITH (NOLOCK) ON  S.JTS_OID = ITF.jts_oid 
								  AND S.C1651='' ''
INNER JOIN PROD_RELCANALES REL WITH (NOLOCK) ON  REL.PRODUCTO = S.PRODUCTO 
											 AND REL.MONEDA = S.MONEDA 
											 AND REL.CANAL = 3 
											 AND REL.HABILITADO = ''S''
INNER JOIN CLI_CLIENTES CLI WITH (NOLOCK) ON  CLI.CODIGOCLIENTE = S.C1803 
										  AND CLI.SUBDIVISION1= ''01''
WHERE EXISTS (SELECT TOP 1 * FROM VW_ASIENTOS_SIN_EXTORNO_DIA ad WITH (NOLOCK) WHERE HV.ASIENTO=ad.ASIENTO AND HV.SUCURSAL=ad.SUCURSAL AND HV.FECHA_PROCESADO=ad.FECHAPROCESO)




')


EXECUTE('

ALTER TABLE ITF_MASTER ALTER COLUMN DESCRIPCION VARCHAR(80)
ALTER TABLE ITF_MASTER ALTER COLUMN OBJ_KETTLE VARCHAR(80)

')