--------------------------------------
--NUEVA VISTA PARA COBRO DE ALQUILER--
--------------------------------------
CREATE VIEW [dbo].[VW_COF_ALTA_CONTRATO_CAJA_SEG] 
AS
	SELECT	S.JTS_OID, 
			C.FECHA_INICIO, 
			C.FECHA_VENCIMIENTO,
			S.C1604+S.C1683+S.C1605+S.C2627+S.C50107 AS SALDO_ACTUAL,
			S.MONEDA,
			C.[CODIGO_COFRE],
			F.TIPO AS SEGMENTO,
			S.C1803 AS CLIENTE,
			CC.USF,
			'S' AS COBRA,
			S.C1728 AS INMOVILIZADO,
			C.[CODIGO] AS [CODIGO_CONTRATO]
	FROM SALDOS S with (nolock)
		INNER JOIN COF_COFRES_CONTRATOS C with (nolock) ON C.SUCURSAL_DEBITO = S.SUCURSAL 
														AND C.PRODUCTO_DEBITO = S.PRODUCTO
														AND C.MONEDA_DEBITO = S.MONEDA 
														AND C.CUENTA_DEBITO = S.CUENTA 
														AND C.OPERACION_DEBITO = S.OPERACION
   														AND C.ORDINAL_DEBITO = S.ORDINAL
		INNER JOIN COF_COFRES F with (nolock) ON F.[CODIGO] = C.[CODIGO_COFRE]
		INNER JOIN CLI_CLIENTES CC with (nolock) ON CC.[CODIGOCLIENTE] = S.C1803
	WHERE C.ESTADO = ('I')
			AND S.TZ_LOCK = 0
			AND C.TZ_LOCK = 0
			AND F.TZ_LOCK = 0
GO
