EXECUTE('
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (3550, 3463, ''Cheques con motivo de rechazo temporal'', ''J'', 0, NULL, 0, 0, 0, NULL)

INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (3463, 1, NULL, 0, 0, 1)
')
