
EXECUTE('

UPDATE dbo.NUMERATORDEFINITION
SET CENTRALIZADO = 0
WHERE NUMERO = 162

DELETE FROM dbo.NUMERATORASIGNED
WHERE OID IN (SELECT OID FROM NUMERATORVALUES 
WHERE NUMERO IN  (SELECT NUMERO FROM NUMERATORDEFINITION WHERE NUMERO=162))

DELETE FROM dbo.NUMERATORVALUES
WHERE NUMERO IN  (SELECT NUMERO FROM NUMERATORDEFINITION WHERE NUMERO=162)

')


