EXECUTE('
---
ALTER VIEW VW_COF_COBRO_CAJA_SEG
AS
	SELECT	S.JTS_OID, 
			C.FECHA_INICIO, 
			C.FECHA_VENCIMIENTO,
			S.C1604+S.C1683+S.C1605+S.C2627+S.C50107 AS SALDO_ACTUAL,
			S.MONEDA,
			C.[CODIGO_COFRE],
			F.TIPO AS SEGMENTO,
			S.C1803 AS CLIENTE,
			CC.USF,
			''S'' AS COBRA,
			S.C1728 AS INMOVILIZADO,
			C.[CODIGO] AS [CODIGO_CONTRATO],
			C.FECHA_ALTA,
			(SELECT FECHAPROCESO FROM PARAMETROS with (nolock)) AS FECHA_PROCESO
	FROM SALDOS S with (nolock)
		INNER JOIN COF_COFRES_CONTRATOS C with (nolock) ON C.SUCURSAL_DEBITO = S.SUCURSAL 
														AND C.PRODUCTO_DEBITO = S.PRODUCTO
														AND C.MONEDA_DEBITO = S.MONEDA 
														AND C.CUENTA_DEBITO = S.CUENTA 
														AND C.OPERACION_DEBITO = S.OPERACION
   														AND C.ORDINAL_DEBITO = S.ORDINAL
		INNER JOIN COF_COFRES F with (nolock) ON F.[CODIGO] = C.[CODIGO_COFRE]
		INNER JOIN CLI_CLIENTES CC with (nolock) ON CC.[CODIGOCLIENTE] = S.C1803
		INNER JOIN PARAMETROSGENERALES P with (nolock) ON P.[CODIGO] = 33
	WHERE (C.ESTADO = (''V'') OR C.ESTADO = (''M'') OR C.ESTADO = (''C''))
			AND S.TZ_LOCK = 0
			AND C.TZ_LOCK = 0
			AND F.TZ_LOCK = 0
			AND (
				(C.FECHA_INICIO = (SELECT FECHAPROCESO FROM PARAMETROS WITH (nolock)) AND C.FECHA_INICIO <> C.FECHA_ALTA)
				OR DATEDIFF(dd,C.FECHA_INICIO,(SELECT FECHAPROCESO FROM PARAMETROS with (nolock)) ) = P.NUMERICO
				OR DATEDIFF(dd,C.FECHA_INICIO,(SELECT FECHAPROCESO FROM PARAMETROS with (nolock)) ) = P.NUMERICO + P.NUMERICO
				OR DATEDIFF(dd,C.FECHA_INICIO,(SELECT FECHAPROCESO FROM PARAMETROS with (nolock)) ) = P.NUMERICO + P.NUMERICO + P.NUMERICO)
				--OR C.FECHA_VENCIMIENTO = (SELECT FECHAPROCESO FROM PARAMETROS with (nolock)))
	/*UNION
	SELECT	S.JTS_OID, 
			C.FECHA_INICIO, 
			C.FECHA_VENCIMIENTO,
			S.C1604+S.C1683+S.C1605+S.C2627+S.C50107 AS SALDO_ACTUAL,
			S.MONEDA,
			C.CODIGO_COFRE,
			F.TIPO AS SEGMENTO,
			S.C1803 AS CLIENTE,
			CC.USF,
			''N'' AS COBRA,
			S.C1728 AS INMOVILIZADO,
			C.CODIGO AS CODIGO_CONTRATO
	FROM SALDOS S with (nolock)
		INNER JOIN COF_COFRES_CONTRATOS C with (nolock) ON C.SUCURSAL_DEBITO = S.SUCURSAL 
														AND C.PRODUCTO_DEBITO = S.PRODUCTO
														AND C.MONEDA_DEBITO = S.MONEDA 
														AND C.CUENTA_DEBITO = S.CUENTA 
														AND C.OPERACION_DEBITO = S.OPERACION
   														AND C.ORDINAL_DEBITO = S.ORDINAL
		INNER JOIN COF_COFRES F with (nolock) ON F.CODIGO = C.CODIGO_COFRE
		INNER JOIN CLI_CLIENTES CC with (nolock) ON CC.CODIGOCLIENTE = S.C1803
	WHERE C.ESTADO = (''C'')
		AND S.TZ_LOCK = 0
		AND C.TZ_LOCK = 0
		AND F.TZ_LOCK = 0;*/

----
')
