EXECUTE('
--------------------
--INSERT DE AYUDAS--
--------------------
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 34738, ''Relaciones Producto-Sector'', '''', 0, ''2613RA1;4968;4131RA2;9103;'', ''Producto;Descripción de Producto;Sector;Descripción de Sector;'', ''TOP/CLIENTES'', ''VW_PROD_RELSECTORES'', 0)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34738, '' '', 0, ''Listado Relaciones Producto-Sector'', ''Listado Relaciones Producto-Sector'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34738, 0, 0, ''C34738'', 0, NULL)
----
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 34849, ''Relaciones Productos-Clientes'', '''', 0, ''2612RA1;9103;2613RA2;4968;3265R;3267R;'', ''Apoderamiento;Descripción de Apoderamiento;Producto;Descripción de Producto;[Titular/Apoderado];Tipo de Cliente;'', ''TOP/CLIENTES'', ''VW_PROD_RELCLIENTES'', 0)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34849, '' '', 0, ''Listado Relaciones Producto-Cliente'', ''Listado Relaciones Producto-Cliente'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34849, 0, 0, ''C34849'', 0, NULL)
----
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 34936, ''Relaciones Productos-Segmentos'', '''', 0, ''8892RA1;5010;2373RA2;324;2617RA3;329;9106;'', ''Producto;Descripción de Producto;Segmento;Descripción de Segmento;Subsegmento;Descripción de Subsegmento;Comentario;'', ''TOP/CLIENTES'', ''VW_PROD_RELSEGMENTOS'', 0)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34936, '' '', 0, ''Listado Relaciones Producto-Segment'', ''Listado Relaciones Producto-Segmento'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34936, 0, 0, ''C34936'', 0, NULL)
----
')