EXECUTE('
IF OBJECT_ID (''dbo.RRII_PARAMETROS_PADRON'') IS NOT NULL
	DROP TABLE dbo.RRII_PARAMETROS_PADRON
')

EXECUTE('
CREATE TABLE dbo.RRII_PARAMETROS_PADRON
	(
	TIPO_IDENT_TRIB     NUMERIC (2) NOT NULL,
	TIPO_PERSONA       VARCHAR (3) NOT NULL,
	NACIONALIDAD VARCHAR (1) DEFAULT('' '') NOT NULL,
	TIPO_DOCUMENTO_IDENTIDAD VARCHAR(2) NOT NULL,
	NOMBRE_TIPO_DOC VARCHAR(4),
	CARGO_SDE_FCO VARCHAR(3) DEFAULT(''N''),
	TZ_LOCK           NUMERIC (15) DEFAULT ((0)) NOT NULL
	)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (11, ''F'', '' '', ''01'', ''DNI'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (11, ''F'', '' '', ''02'', ''LE'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (11, ''F'', '' '', ''03'', ''LC'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (11, ''J'', '' '', ''00'', NULL, 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (99, ''F'', ''E'', ''01'', ''DNI'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (99, ''F'', ''E'', ''04'', ''PAS'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (99, ''F'', ''E'', ''06'', ''CI'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, TZ_LOCK)
VALUES (98, ''J'', ''E'', ''00'', NULL, 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, CARGO_SDE_FCO, TZ_LOCK)
VALUES (55, ''J'', '' '', ''00'', ''29'',''SDE'', 0)

INSERT INTO dbo.RRII_PARAMETROS_PADRON (TIPO_IDENT_TRIB, TIPO_PERSONA, NACIONALIDAD, TIPO_DOCUMENTO_IDENTIDAD, NOMBRE_TIPO_DOC, CARGO_SDE_FCO, TZ_LOCK)
VALUES (66, ''J'', '' '', ''00'', ''66'',''FCO'', 0)
');
