EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37282, '' '', 0, ''Seccíon'', ''Seccíon'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 3310, 33101, 0, 81, ''SECCION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37283, '' '', 0, ''Sector'', ''Sector'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 67, 6701, 0, 81, ''SECTOR'', 0, NULL)

ALTER TABLE CLI_Cod_Act_BCRA ADD SECCION VARCHAR (1)

ALTER TABLE CLI_Cod_Act_BCRA ADD SECTOR NUMERIC (5)

UPDATE dbo.AYUDAS
SET CAMPOS = ''1210R;1211R;1212;1213;''
WHERE NUMERODEAYUDA = 81

')