EXECUTE('
DELETE FROM OPERACIONES WHERE IDENTIFICACION IN(6062,6066,6069)

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (5500, 6062, ''Solicitud de Leasing:'', ''Solicitud de Leasing:'', ''6062'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, NULL)

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (5500, 6066, ''Alta del Seguro'', ''Alta del Seguro'', ''6066'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, 0)

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (5500, 6069, ''Actualización Eventos Leasing'', ''Actualización Eventos Leasing'', ''6069'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, 0)
')


