EXECUTE('
-----------------
--NUEVOS CAMPOS--
-----------------
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35415, '' '', 0, ''Estado del evento'', ''Estado del evento'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 808, ''ESTADO_EVENTO'', 0, NULL)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35416, '' '', 0, ''Opción visitas cajas seguridad'', ''Opción visitas'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, NULL)
------------
--OPCIONES--
------------
INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35416, ''E'', ''Registrar nueva visita'', ''N'', ''N'')
--
INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35416, ''E'', ''Pagar visitas seleccionadas'', ''P'', ''P'')
--------------------------
--MODIFICACIÓN DE ÍNDICE--
--------------------------
UPDATE INDICES
SET CAMPO1 = 8083
	, CAMPO2 = NULL
	, CAMPO3 = NULL
WHERE NUMERODEARCHIVO = 808 AND NUMERODEINDICE = 1
-------------------------
--MODIFICACIÓN DE AYUDA--
-------------------------
UPDATE AYUDAS
SET CAMPOS = ''8083ROA3;8061OA2;35415OD1;8079;8084;8085;8081;8097;34655;''
WHERE NUMERODEAYUDA = 8081
----
')


