--METADATA

EXECUTE('        
IF EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO =45385)
BEGIN

 DELETE FROM DICCIONARIO WHERE NUMERODECAMPO =45385;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
    VALUES (45385, '' '', 0, ''Filtro canal'', NULL, 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''filtro_canal'', 0, NULL);


END
ELSE
BEGIN

     INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
     VALUES (45385, '' '', 0, ''Filtro canal'', NULL, 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''filtro_canal'', 0, NULL);
END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''0'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''0'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Todos'', ''0'', ''0'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Todos'', ''0'', ''0'');
END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''2'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''2'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''LotiPagos'', ''2'', ''2'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''LotiPagos'', ''2'', ''2'');
END


IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''3'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''3'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''RapiPagos'', ''3'', ''3'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''RapiPagos'', ''3'', ''3'');
END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''4'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''4'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Link'', ''4'', ''4'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Link'', ''4'', ''4'');
END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''5'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''5'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Caja Municipal'', ''5'', ''5'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Caja Municipal'', ''5'', ''5'');
END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''7'')
BEGIN

 DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45385 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''7'';
 
    INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Pago Fácil'', ''7'', ''7'');


END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
     VALUES (45385, ''E'', ''Pago Fácil'', ''7'', ''7'');
END

')
