EXECUTE('
----------------------------------------
--Metadata vista VW_DEBITOSAUTOMATICOS--
----------------------------------------
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (24, 4520, NULL, ''Vista débitos automáticos'', 0, ''VW_DEBITOSAUTOMATICOS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45203, '' '', 0, ''Nro. Solicitud'', ''Nro. Solicitud'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''NRO_REGISTRO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45204, '' '', 0, ''JTS Débito'', ''JTS Débito'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''JTS_DEBITO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45205, '' '', 0, ''ID Cabezal'', ''ID Cabezal'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''ID_CABEZAL'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45206, '' '', 0, ''ID Línea'', ''ID Línea'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''ID_LINEA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45207, '' '', 0, ''Convenio'', ''Convenio'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''CONVENIO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45208, '' '', 0, ''Tipo de Orden'', ''Tipo de Orden'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4520, ''TIPO_ORDEN'', 0, NULL)
----
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4520, 1, ''ID solicitud débito automático'', 0, 45203, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
-----------------------
--NUEVO CAMPO DETALLE--
-----------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44566, '' '', 0, ''Número de Registro'', ''Nro. Registro'', 10, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 4486, ''NRO_REGISTRO'', 0, NULL)
-------------------
--NUEVO NUMERADOR--
-------------------
INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (45203, 1, 1, '' '', NULL, 1, 1, 0, ''Nro. Solicitud débitos automáticos'', ''T'')
----
')