EXECUTE('
INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (560, 0, 560, 1, ''Analiza graduacion y fraccionamiento'', NULL, NULL)

INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (560, 1, 560, 1, ''C4620=619'', ''C238'', ''C58344'')

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (6000, 5922, ''Graduación y fraccionamiento'', ''Graduación y fraccionamiento'', ''5922'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')