EXECUTE('
DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45095
AND IDIOMA = ''E'' AND OPCIONINTERNA IN (''H'',''X'',''F'') 


INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45095, ''E'', ''Habilitado'', ''H'', ''H'')


INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45095, ''E'', ''Rechazado'', ''X'', ''X'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45095, ''E'', ''Fallido'', ''F'', ''F'')


DELETE FROM AYUDAS WHERE NUMERODEAYUDA = 2678

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 2678, ''Ayuda val. archivo agencieros'', NULL, 0, ''4800R;565;4177;2576;3325;384;'', ''Id;Asiento;Fecha;Sucursal;Cant.Estado H;Cant.Estado F;'', ''TOP/CLIENTES'', ''VW_VALIDACION_AGENCIEROS'', 0)


DELETE FROM OPERACIONES
WHERE IDENTIFICACION = 2678

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2600, 2678, ''Validación Soporte de Agencieros'', ''Validación Soporte de Agencieros'', ''2678'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45680

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45680, '' '', 0, ''Ayuda Grilla Val soporte agencieros'', ''Ayuda Grilla Val soporte agencieros'', 16, ''N'', 0, NULL, 0, 0, 0, 0, 0, 2678, 0, 0, ''Ayuda'', 0, NULL)


')
