EXECUTE('
--Primero Deletes
DELETE FROM CODIGO_TRANSACCIONES WHERE CODIGO_OPERACION = 2660
DELETE FROM CODIGO_TRANSACCIONES WHERE CODIGO_OPERACION = 2667 AND CODIGO_INTERNO_MOV = 1

INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2667, 1, 60, 0)

INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2660, 1, 80, 0)

INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (2660, 2, 82, 0)

--Reporte Faltante

INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (2600, 2621, ''Formulario Reversa Débitos Automáticos'', ''J'', NULL, NULL, NULL, 0, 0, NULL)

INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (2621, 1, NULL, 0, 0, 1)

-- Definición transacción Faltante
INSERT INTO TTR_CODIGO_TRANSACCION_DEF (CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, TZ_LOCK, USO_COMERCIAL)
VALUES (80, ''Débito x Reintegro DA Cuenta Empresa Recaudadora'', ''N'', 0, '' '')
')
