EXECUTE('
---------------------------------------------
--MODIFICACION CREDEB CARGOS CAJA SEGURIDAD--
---------------------------------------------
DELETE FROM dbo.CI_IMPUESTOS_X_CARGO
WHERE ID_IMPUESTO = 10 AND ID_CARGO = 240
----
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 210, ''A'', 0, 34096, ''Cond CREDEB'')
--
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 211, ''A'', 0, 34096, ''Cond CREDEB'')
--
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 212, ''A'', 0, 34096, ''Cond CREDEB'')
----
')