EXECUTE ('DELETE BITACORA_CODIGOS

INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''O'', ''Comienza una operacion'', 0, ''OPERATION_CREATED'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''o'', ''Termina una operacion (Ok o Cancela)'', 1, ''OPERATION_TERMINATED'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''Q'', ''Inicio reporte'', 2, ''REPORT_INIT_GENERATION'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''Q'', ''Fin reporte'', 3, ''REPORT_FINISH_GENERATION'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''Q'', ''Parametros reporte'', 4, ''REPORT_PARAMETERS'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''U'', ''Log in: logueo de un usuario del jdesktop'', 5, ''USER_LOGIN'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''u'', ''Log out: deslogueo de un usuario del jdesktop'', 6, ''USER_LOGOUT'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''F'', ''Cambio de fecha del sistema'', 7, ''CHANGE_DATE'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''C'', ''Cambio de Contraseña'', 8, ''CHANGE_PASSWORD'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''a'', ''Cierre de sucursal'', 9, ''CLOSE_BRANCH'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''q'', ''Encolado de instruccion'', 10, ''ENQUEUE_EVENT'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''A'', ''Apertura de sucursal'', 11, ''OPEN_BRANCH'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''R'', ''Reaplicacion de movimientos encolados'', 12, ''REAPPLY_MOVEMENT'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''f'', ''Sucursal finalizada'', 14, ''FINALIZE_BRANCH'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''E'', ''Error al loguearse un usuario en el jdesktop'', 15, ''USER_LOGIN_ERROR'')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''T'', ''Comando Telnet'', 16, ''TELNET_COMMAND'')

INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''A'', ''Alta de Usuarios'', 17, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''A'', ''Altas de Grupos'', 18, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''R'', ''Mapa de Red'', 19, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''N'', ''Numerador'', 20, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''M'', ''Mapa Topaz'', 21, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''I'', ''Impresora'', 22, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''B'', ''Bajas de Usuario'', 23, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''B'', ''Bajas de Grupo'', 24, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''G'', ''Modificación de Parámetros'', 25, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''P'', ''Enter Program'', 26, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''p'', ''Exit Program'', 27, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''q'', ''Modificación del Grupo'', 28, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''P'', ''Permisos Grupo'', 29, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''P'', ''Restricciones Grupo'', 30, '''')


INSERT INTO dbo.BITACORA_CODIGOS (CODIGO, DESCRIPCION, TIPO_EVENTO, ETIQUETA)
VALUES (''q'', ''Modificación de Usuario'', 31, '''') ')


