-----------------------------
--Estructura SNP_ADHESIONES--
-----------------------------
EXECUTE('
IF OBJECT_ID (''dbo.SNP_ADHESIONES'') IS NOT NULL
	DROP TABLE dbo.SNP_ADHESIONES
')
--
EXECUTE('
CREATE TABLE dbo.SNP_ADHESIONES
	(
	TZ_LOCK     		NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CLIENTE_ADHERIDO	NUMERIC (12) DEFAULT ((0)) NOT NULL,
	CUIT_EO     		NUMERIC (10) DEFAULT ((0)),
	PRESTACION  		VARCHAR (10) DEFAULT ('' '') NOT NULL,
	CODIGO_CLIENTE		NUMERIC (12) DEFAULT ((0)) NOT NULL,
	CBU 	   		VARCHAR (22) DEFAULT ('' ''),
	FECHA_ULT_ACTUALIZ	DATETIME,
	PRIORIDAD 		NUMERIC (2) DEFAULT ((0)),
	TIPO_DOCUMENTO		VARCHAR (4) DEFAULT ('' ''),
	NUMERO_DOCUMENTO	VARCHAR (20) DEFAULT ('' ''),
	ESTADO  		VARCHAR (2) DEFAULT ('' ''),
	MOTIVO_RECHAZO     	VARCHAR (3) DEFAULT ('' ''),
	CONSTRAINT PK_SNP_ADHESIONES_01 UNIQUE (CLIENTE_ADHERIDO, CUIT_EO, PRESTACION, CODIGO_CLIENTE)
	)
')
----