EXECUTE('
IF OBJECT_ID (''dbo.CRE_TIPO_EXCLUSION'') IS NOT NULL
	DROP TABLE dbo.CRE_TIPO_EXCLUSION

')

EXECUTE('
CREATE TABLE CRE_TIPO_EXCLUSION (
OPCION_EXCLUSION VARCHAR (100) DEFAULT ('' '') NOT NULL,
ID_EXCLUSION     NUMERIC (15),  
DETALLE          VARCHAR (500)
CONSTRAINT PK_TIPO_EXCLUSION PRIMARY KEY (ID_EXCLUSION)
)
')