EXECUTE('
DELETE FROM REPORTESJASPER WHERE IDENTIFICACION IN (2627,2629)

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (2627, 1, NULL, 0, 0, 1)


INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (2629, 1, NULL, 0, 0, 1)

')
