EXECUTE('
CREATE TABLE DJ_SOLICITUD_AD_INTEG_JUZ
	(
	NRO_SOLICITUD     NUMERIC (12) DEFAULT ((0)) NOT NULL,
	ID_PERSONA        NUMERIC (12) DEFAULT ((0)) NOT NULL,
	NRO_JUZGADO       NUMERIC (12) DEFAULT ((0)) NOT NULL,
	ACTOR             VARCHAR (3) DEFAULT ('' ''),
	FECHA_INTEGRACION DATETIME,
	FECHA_CESE        DATETIME,
	ACTIVO            VARCHAR (1),
	ESTADO            VARCHAR (1) DEFAULT ('' ''),
	FECHA_ESTADO      DATETIME,
	SUCURSAL          NUMERIC (5),
	TZ_LOCK           NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_DJ_SOLICITUD_AD_INTEG_JUZ_01 PRIMARY KEY (NRO_SOLICITUD, ID_PERSONA, NRO_JUZGADO)
	)
')
