EXECUTE('
----
DELETE FROM OPERACIONES WHERE IDENTIFICACION = 2637  
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45414
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45421
DELETE FROM AYUDAS WHERE NUMERODEAYUDA = 44661
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45420
DELETE FROM OPCIONES WHERE NUMERODECAMPO IN (45421)
----
')
EXECUTE('
---- 
INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2600, 2637, ''Rechazo débitos directos por feriado de Sucursal'', ''Rechazo débitos directos por feriado de Sucursal'', ''2637'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45414, '' '', 0, ''Fecha Estado'', ''Fecha Estado'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4466, ''FECHA_ESTADO'', 0, NULL)
-- 
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45421, '' '', 0, ''rechazar / reversar'', ''rechazar / reversar'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, NULL)
--
INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4466, 44661, ''Ayuda SNP DEBITOS'', '''', 0, ''44685R;44686;44687;44689;44690;44691;44692;44695;44696;44701;44700;45414;'', NULL, NULL, NULL, 0)
--
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45420, '' '', 0, ''Ayuda SNP DEBITOS'', ''Ayuda SNP DEBITOS'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 44661, 0, 0, ''Ayuda SNP DEBITOS'', 0, NULL)
--
INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45421, ''E'', ''Reversar Rechazo'', ''P'', ''P'')
--
INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45421, ''E'', ''Rechazar'', ''R'', ''R'')
----
')
