EXECUTE('
DROP PROCEDURE IF EXISTS dbo.SP_CONTROL_GYF_VINCULADOS
')

EXECUTE('
CREATE PROCEDURE dbo.SP_CONTROL_GYF_VINCULADOS
@CLIENTE NUMERIC(10),
@TIPO_VINCULACION NUMERIC(3),
@IMPORTE_ANALISIS NUMERIC(15,2),
@EXCEDE_GRAD VARCHAR(1) OUTPUT,
@MENSAJE_INDIVIDUAL VARCHAR(200) OUTPUT,
@MENSAJE_GRUPO VARCHAR(200) OUTPUT
AS
BEGIN
DECLARE @TABLA_VINCULADOS TABLE (CLIENTE NUMERIC(10), DEUDA_TOTAL NUMERIC(15,2), 
SITUACION VARCHAR(3), VINCULACION NUMERIC(3), PORC_SIN_G NUMERIC(5,2),
PORC_CON_G NUMERIC(5,2))
DECLARE @SIT_MAYOR NUMERIC(3)
DECLARE @TOPE_SUELDO NUMERIC(18,2)
DECLARE @DEUDA_TOTAL NUMERIC(18,2)
DECLARE @DEUDA_TOPE NUMERIC(20,2)
DECLARE @DEUDA_GRUPO NUMERIC(20,2)
--- Tabla auxiliar de deudas
DECLARE @TABLA_ASISTENCIAS TABLE (CLIENTE NUMERIC(12), JTS_ASISTENCIA NUMERIC(10),
IMPORTE_DEUDA NUMERIC(15,2), TIENE_GARANTIA VARCHAR(1), TIPO_GARANTIA NUMERIC(2),
PRODUCTO NUMERIC(5), FAMILIA NUMERIC(10))

INSERT INTO @TABLA_VINCULADOS
SELECT V.[Cliente Vinculado], V.[Deuda Total], V.Situacion, V.[Vinculo Primario],
ISNULL(G.TOPE_FRACCIONAMIENTO_SING,(SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO=606)),
ISNULL(G.TOPE_FRACCIONAMIENTO_CONG,(SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO=607))
FROM VW_VINCULACIONES_DEUDAS V WITH(NOLOCK) 
LEFT JOIN CRE_VINCULADOS_GYF G WITH(NOLOCK) ON V.[Vinculo Primario] = G.ID AND G.TIPO_VINCULACION = ''P'' AND
G.TZ_LOCK = 0
WHERE [Cliente Vinculante] = @CLIENTE

	INSERT INTO @TABLA_ASISTENCIAS
	SELECT 
	AD.CLIENTE,
	AD.JTS_OID,
	SUM(AD.SALDO_DEUDA),
	CASE 
	WHEN CG.JTSOID_SALDO IS NULL THEN ''N''
	ELSE ''S''
	END AS GARANTIA,
	ISNULL(CTG.TIPO_GARANTIA,0),
	p.C6250, 
	f.FAMILIAPROD
	FROM VW_ASISTENCIAS_DEUDA AD WITH(NOLOCK)
	INNER JOIN SALDOS S WITH(NOLOCK) ON S.JTS_OID = AD.JTS_OID
	INNER JOIN PRODUCTOS p WITH(NOLOCK) ON s.PRODUCTO = p.C6250 
	AND ( (p.tz_lock < 300000000000000 OR p.tz_lock >= 400000000000000) 
	AND (p.tz_lock < 100000000000000 OR p.tz_lock >= 200000000000000)  )
	INNER JOIN CRE_FAMILIAS f ON p.C6283 = f.FAMILIAPROD 
	AND ( (f.tz_lock < 300000000000000 OR f.tz_lock >= 400000000000000) 
	AND (f.tz_lock < 100000000000000 OR f.tz_lock >= 200000000000000)  )	
	LEFT JOIN CRE_GARANTIACREDITO CG WITH(NOLOCK) ON CG.JTSOID_SALDO = S.JTS_OID
	LEFT JOIN CRE_GARANTIASRECIBIDAS CGR WITH(NOLOCK) ON CGR.NUM_GARANTIA = CG.NUM_GARANTIA
	LEFT JOIN CRE_TIPOSGARANTIAS CTG WITH(NOLOCK) ON CGR.TIPOGARANTIA = CTG.TIPO_GARANTIA AND
	CTG.TIPO_BCRA IN (1,2)
	WHERE AD.SALDO_DEUDA <> 0 AND S.C1785 IN (1,5,6)
	AND AD.CLIENTE IN (SELECT CLIENTE FROM @TABLA_VINCULADOS) AND AD.CLIENTE = @CLIENTE
	GROUP BY AD.JTS_OID, CG.JTSOID_SALDO, CTG.TIPO_GARANTIA, p.C6250, f.FAMILIAPROD, AD.CLIENTE
	

SET @DEUDA_TOTAL = (SELECT SUM(IMPORTE_DEUDA) FROM @TABLA_ASISTENCIAS WHERE CLIENTE = @CLIENTE)

SET @DEUDA_GRUPO = (SELECT SUM(IMPORTE_DEUDA) FROM @TABLA_ASISTENCIAS)

SET @SIT_MAYOR = (SELECT COUNT(1) FROM @TABLA_VINCULADOS WHERE SITUACION > 1)

IF(@TIPO_VINCULACION = 10)
 BEGIN
  SET @TOPE_SUELDO = ((SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 611) * 
  					 (SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 612))
  IF(@DEUDA_TOTAL>@TOPE_SUELDO)
   BEGIN
    SET @TOPE_SUELDO = @DEUDA_TOTAL; 
   END
   SET @DEUDA_TOPE = @TOPE_SUELDO;
 END
 ELSE
 BEGIN
 	SET @DEUDA_TOPE = (((SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 617)*
 	(SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 618))*
 	(SELECT IMPORTE FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 616))/100;
 END
 
 IF((@DEUDA_TOTAL+@IMPORTE_ANALISIS)>@DEUDA_TOPE)
 BEGIN
 SET @EXCEDE_GRAD = ''S'';
 SET @MENSAJE_INDIVIDUAL = ''Alerta por exceso de vinculado. Deuda = ''+CONVERT(VARCHAR, @DEUDA_TOTAL+@IMPORTE_ANALISIS) +
 '' Limite deuda = ''+CONVERT(VARCHAR,@DEUDA_TOPE);
 END
 ELSE 
 BEGIN
 SET @MENSAJE_INDIVIDUAL = NULL;
 SET @EXCEDE_GRAD = ''N'';
 END
 
 IF(@DEUDA_GRUPO>@DEUDA_TOPE)
 BEGIN
 SET @MENSAJE_GRUPO = ''Tope deuda = '' + CONVERT(VARCHAR, @DEUDA_TOPE) + '' Deuda grupo = ''+@DEUDA_GRUPO;
 END
 ELSE 
 SET @MENSAJE_GRUPO = NULL;

IF(@SIT_MAYOR > 0 AND @EXCEDE_GRAD = ''N'')
BEGIN
 SET @EXCEDE_GRAD = ''S'';
 SET @MENSAJE_INDIVIDUAL = ''Alerta. Hay integrantes con una situación mayor a 1'';
 SET @MENSAJE_GRUPO = ''Alerta. Hay integrantes con una situación mayor a 1'';
END

END
')