EXECUTE('
UPDATE dbo.OPERACIONES SET AUTORIZACION = ''N'' WHERE IDENTIFICACION = 3021
UPDATE dbo.OPERACIONES SET AUTORIZACION = ''N'' WHERE IDENTIFICACION = 3020
UPDATE dbo.OPERACIONES SET AUTORIZACION = ''N'' WHERE IDENTIFICACION = 3002

DROP TABLE DIF_ARQUEO_CAJA;
')

EXECUTE('

CREATE TABLE dbo.DIF_ARQUEO_CAJA
	(
	TZ_LOCK         NUMERIC (15) DEFAULT ((0)),
	FECHAPROCESO    DATETIME NOT NULL,
	SUCURSAL        NUMERIC (5) DEFAULT ((0)) NOT NULL,
	ASIENTO         NUMERIC (10) NOT NULL,
	CAJA            NUMERIC (3) NOT NULL,
	TIPO            VARCHAR (8) NOT NULL,
	MONEDA          NUMERIC (4) NOT NULL,
	MONTO           NUMERIC (15, 2) DEFAULT ((0)),
	AUTORIZA        VARCHAR (255) DEFAULT ('' ''),
	ESTADO          VARCHAR (1) DEFAULT ('' ''),
	OBSERVACIONES   VARCHAR (255) DEFAULT ('' ''),
	USUARIO         VARCHAR (8),
	MONTO_PENDIENTE NUMERIC (15, 2),
	RUBRO_CONTABLE  NUMERIC (12),
	CONSTRAINT PK_ARQUEO_CAJA PRIMARY KEY (FECHAPROCESO, SUCURSAL, ASIENTO, TIPO, MONEDA, CAJA)
	)


')