EXECUTE('
IF OBJECT_ID (''dbo.ITF_PBF_POS'') IS NOT NULL
	DROP TABLE dbo.ITF_PBF_POS
')

EXECUTE('
CREATE TABLE dbo.ITF_PBF_POS
	(
	ID            NUMERIC (15) IDENTITY NOT NULL,
	CLAVE         VARCHAR (50) DEFAULT ('' ''),
	TIPO_REGISTRO VARCHAR (3) DEFAULT ('' ''),
	DETALLE       VARCHAR (300) DEFAULT ('' ''),
	CONSTRAINT PK_ITF_PBF_POS_01 PRIMARY KEY (ID)
	)
')

EXECUTE('
CREATE INDEX ITF_PBF_POS_IDX01
	ON dbo.ITF_PBF_POS (TIPO_REGISTRO)
')