EXECUTE('
IF OBJECT_ID (''dbo.VW_RRII_ANEXO_12_RENGLON22'') IS NOT NULL
	DROP VIEW dbo.VW_RRII_ANEXO_12_RENGLON22
')
EXECUTE('
CREATE   VIEW [dbo].[VW_RRII_ANEXO_12_RENGLON22] 
AS

--22)
SELECT
    22 AS NRO_CAMPO,
    COUNT(DISTINCT(CP.NUMEROPERSONA)) AS SUM_CONT,
    G.FECHA
FROM
    GRL_SALDOS_DIARIOS G WITH(NOLOCK)
    
INNER JOIN SALDOS S WITH(NOLOCK) ON
	G.SALDOS_JTS_OID = S.JTS_OID AND
	G.MONEDA = S.MONEDA AND
	G.TZ_LOCK = S.TZ_LOCK

INNER JOIN CLI_CLIENTEPERSONA CP WITH(NOLOCK) ON
	CP.CODIGOCLIENTE = S.C1803 AND
	CP.TZ_LOCK = G.TZ_LOCK

LEFT JOIN CLI_PERSONASFISICAS CPF WITH (NOLOCK) ON
	CP.NUMEROPERSONA = CPF.NUMEROPERSONAFISICA AND 
	CPF.TZ_LOCK = G.TZ_LOCK 

WHERE
	S.C1785 =2 AND
    G.TZ_LOCK =0 AND
   	G.SALDO_AJUSTADO!=0 AND
   	CPF.SECTOR=1
GROUP BY 
	G.FECHA
	
UNION ALL

SELECT
    22 AS NRO_CAMPO,
    COUNT(DISTINCT(CP.NUMEROPERSONA)) AS SUM_CONT,
    G.FECHA
FROM
    GRL_SALDOS_DIARIOS G WITH(NOLOCK)
    
INNER JOIN SALDOS S WITH(NOLOCK) ON
	G.SALDOS_JTS_OID = S.JTS_OID AND
	G.MONEDA = S.MONEDA AND
	G.TZ_LOCK = S.TZ_LOCK

INNER JOIN CLI_CLIENTEPERSONA CP WITH(NOLOCK) ON
	CP.CODIGOCLIENTE = S.C1803 AND
	CP.TZ_LOCK = G.TZ_LOCK


LEFT JOIN CLI_PERSONASJURIDICAS CPJ WITH (NOLOCK) ON
    CP.NUMEROPERSONA = CPJ.NUMEROPERSONAJURIDICA AND 
    CPJ.TZ_LOCK = G.TZ_LOCK 
    
WHERE
	S.C1785 =2 AND
    G.TZ_LOCK =0 AND
   	G.SALDO_AJUSTADO!=0 AND
   	CPJ.SECTOR=1
GROUP BY 
	G.FECHA
')
