EXECUTE('
----
IF OBJECT_ID (''VW_AYUDA_CONV_REND'') IS NOT NULL
	DROP VIEW VW_AYUDA_CONV_REND
----
')
EXECUTE('
----
CREATE VIEW VW_AYUDA_CONV_REND AS 
SELECT L.ID_LIQUIDACION AS ''ID_LIQUIDACION'', 
		L.ESTADO AS ''ESTADO'', 
		L.CONVENIO AS ''CONVENIO'', 
		C.NomConvRec AS ''NOMBRE_CONVENIO'', 
		L.CONVENIO_PADRE AS ''CONVENIO_PADRE'',
		C.Cuit AS ''CUIT'', 
		CLI.NOMBRECLIENTE AS ''NOMBRE_CLIENTE'', 
		L.FECHA AS ''FECHA_LIQUIDACION'', 
		C.Acreditacion AS ''PLAZO_ACRED'',
		L.MONEDA AS ''MONEDA'',
		L.TOTALREGISTROS AS ''TOTAL_REGISTROS'', 
		L.TOTALIMPORTE AS ''TOTAL_IMPORTE'',	
		L.COMISION_LIQUIDADA AS ''COMISION_LIQUIDADA'', 
		L.IMPORTE_COMISION AS ''IMPORTE_COMISION'',
		RC.Fecha_Cobranza AS ''FECHA_COBRANZA'',
		CONVERT(DATETIME,(CASE WHEN C.Acreditacion = OE.OPCIONINTERNA AND OE.OPCIONINTERNA = ''24H''
			THEN dbo.diaHabil(DATEADD(day,1,RC.Fecha_Cobranza),''A'')
			WHEN C.Acreditacion = OE.OPCIONINTERNA AND 	OE.OPCIONINTERNA = ''48H''
			THEN dbo.diaHabil(DATEADD(day,2,RC.Fecha_Cobranza),''A'') END)) AS ''FECHA_REND_CANAL'',
			
		CONVERT(DATETIME,(CASE WHEN C.Acreditacion = OE.OPCIONINTERNA AND OE.OPCIONINTERNA = ''24H''
			THEN dbo.diaHabil(DATEADD(day,1,RJ.FECHACARGA),''A'')
			WHEN C.Acreditacion = OE.OPCIONINTERNA AND 	OE.OPCIONINTERNA = ''48H''
			THEN dbo.diaHabil(DATEADD(day,2,RJ.FECHACARGA),''A'') END)) AS ''FECHA_REND_CAJA'',
		RC.ID AS ''ID_CABEZAL''
FROM REC_LIQUIDACION L WITH (NOLOCK) 
JOIN CONV_CONVENIOS_REC C WITH (NOLOCK) ON L.CONVENIO = C.Id_ConvRec AND C.Id_TpoConv NOT IN(1,2)													
JOIN CLI_CLIENTES CLI  WITH (NOLOCK) ON C.Cliente = CLI.CODIGOCLIENTE 
JOIN OPCIONES OE WITH (NOLOCK) ON OE.OPCIONINTERNA = C.Acreditacion AND OE.NUMERODECAMPO = 44755 AND OE.IDIOMA = ''E''
LEFT JOIN REC_CAB_RECAUDOS_CANAL RC WITH (NOLOCK) ON RC.ID_LIQUIDACION = l.ID_LIQUIDACION AND RC.CONVENIO = c.Id_ConvRec
LEFT JOIN REC_CAB_RECAUDOS_CAJA RJ WITH (NOLOCK) ON RJ.ID_LIQUIDACION = l.ID_LIQUIDACION AND RJ.CONVENIO = c.Id_ConvRec
WHERE L.ESTADO = ''L'' AND
(C.tz_lock < 300000000000000 OR C.tz_lock >= 400000000000000) AND (C.tz_lock < 100000000000000 OR C.tz_lock >= 200000000000000) AND
(CLI.tz_lock < 300000000000000 OR CLI.tz_lock >= 400000000000000) AND (CLI.tz_lock < 100000000000000 OR CLI.tz_lock >= 200000000000000) AND
(L.tz_lock < 300000000000000 OR L.tz_lock >= 400000000000000) AND (L.tz_lock < 100000000000000 OR L.tz_lock >= 200000000000000)

----
')