EXECUTE ('
CREATE   OR ALTER  VIEW [dbo].[VW_RRII_IERIC_ANUAL] AS
WITH AUX AS
(
SELECT
	VS.CTA_CBU AS CBU,
	SUM(HV.MONTO) AS MONTO_UVA,
	SUM(HV.EQUIVALENTEMN) AS MONTO_MN,
	D.NUMERODOCUMENTO AS CUIL_EMPLEADO,
	AE.RUC_INDEPENDIENTE AS CUIT_EMPLEADOR,
	HV.SALDO_JTS_OID
FROM
	HISTORIA_VISTA HV WITH (NOLOCK)
INNER JOIN SALDOS S WITH (NOLOCK) ON HV.SALDO_JTS_OID = S.JTS_OID 
INNER JOIN VTA_SALDOS VS WITH (NOLOCK) ON HV.SALDO_JTS_OID = VS.JTS_OID_SALDO
INNER JOIN CLI_CLIENTEPERSONA CP WITH (NOLOCK)ON CP.CODIGOCLIENTE = S.C1803
												AND CP.TITULARIDAD = ''T''
INNER JOIN CLI_DocumentosPFPJ D  WITH (NOLOCK)ON D.NUMEROPERSONAFJ = CP.NUMEROPERSONA
INNER JOIN CLI_ACTIVIDAD_ECONOMICA AE WITH (NOLOCK)ON AE.CODIGO_PERSONA_CLIENTE = D.NUMEROPERSONAFJ
													AND AE.FUENTE_INGRESO = ''D''
WHERE
	HV.DEBITO_CREDITO = ''C''
--	AND HV.FECHA_VALOR NOT BETWEEN DATEADD(MONTH, -12, (SELECT FECHAPROCESO 
--														FROM  PARAMETROS P  WITH (NOLOCK))) 
--													AND (SELECT FECHAPROCESO 
--														FROM  PARAMETROS P  WITH (NOLOCK))
	AND S.PRODUCTO IN (	SELECT PRODUCTOS.C6250 
						FROM PRODUCTOS WITH (NOLOCK) 
						WHERE C6252 IN (2,3) 
							AND TIPO_CUENTA_VISTA = 14) -- valor original 6 -- valor 14 para datos
GROUP BY
	HV.SALDO_JTS_OID,	
	D.NUMERODOCUMENTO,
	AE.RUC_INDEPENDIENTE,
	VS.CTA_CBU
)
SELECT
	A.CBU,
	A.CUIL_EMPLEADO,
	A.CUIT_EMPLEADOR,
	MAX(HV.FECHA_VALOR) AS FECHACONTABLE,
	A.MONTO_MN AS SALDO_CUENTA
FROM
	HISTORIA_VISTA HV WITH (NOLOCK) 
	INNER JOIN ASIENTOS ASIE WITH (NOLOCK)ON hv.ASIENTO = ASIE.ASIENTO 
										AND hv.SUCURSAL = ASIE.SUCURSAL 
										AND hv.FECHA_PROCESADO = ASIE.FECHAPROCESO 
										AND ASIE.ESTADO = 77
	INNER JOIN AUX A WITH (NOLOCK)ON HV.SALDO_JTS_OID = A.SALDO_JTS_OID
--WHERE
--	HV.FECHA_VALOR NOT BETWEEN DATEADD(MONTH, -12, (SELECT FECHAPROCESO 
--													FROM  PARAMETROS P  WITH (NOLOCK))) 
--													AND (SELECT FECHAPROCESO 
--														FROM  PARAMETROS P  WITH (NOLOCK))
GROUP BY
	HV.SALDO_JTS_OID,
	A.MONTO_MN,
	A.CUIL_EMPLEADO,
	A.CUIT_EMPLEADOR,
	A.CBU


')
