EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45363, '' '', 0, ''Rubro Contable'', ''Rubro Contable'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 631, 0, 0, ''C45363'', 0, NULL)
')