
EXECUTE('
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN (37402,37404,37406)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37402, '' '', 0, ''IIBB CABA Retención Condición'', ''IIBB CABA Retención Condición'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 11, ''IIBB_CABA_RETENCION_COND'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37404, '' '', 0, ''IIBB CABA Retención Condición'', ''IIBB CABA Retención Condición'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 14, ''IIBB_CABA_RETENCION_COND'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37406, '' '', 0, ''IIBB CABA Retención Condición'', ''IIBB CABA Retención Condición'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 19, ''IIBB_CABA_RETENCION_COND'', 0, NULL)

')