EXECUTE('
ALTER TABLE TTR_CODIGO_TRANSACCION_DEF ADD GRUPO NUMERIC (3) DEFAULT ((0))
')

EXECUTE('
UPDATE TTR_CODIGO_TRANSACCION_DEF SET GRUPO = 0

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43649, '' '', 0, ''Grupo'', ''Grupo'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3432, ''GRUPO'', 0, NULL)
')