--METADATA

EXECUTE('        
IF EXISTS (SELECT * FROM NUMERATORASIGNED WHERE OID IN (SELECT OID FROM NUMERATORVALUES wHERE NUMERO = 45191))
BEGIN

   DELETE FROM NUMERATORASIGNED
    WHERE OID IN (SELECT OID FROM NUMERATORVALUES wHERE NUMERO = 45191);
 
END

IF EXISTS (SELECT * FROM NUMERATORVALUES WHERE NUMERO = 45191)
BEGIN

  DELETE FROM NUMERATORVALUES 
   WHERE NUMERO = 45191;
 
END

IF EXISTS (SELECT * FROM NUMERATORDEFINITION WHERE NUMERO = 45191)
BEGIN

  DELETE FROM NUMERATORDEFINITION
   WHERE NUMERO = 45191;

  INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
   VALUES (45191, (SELECT max(ID_ConvPago)+1 FROM CONV_CONVENIOS_PAG WHERE ID_ConvPago<99999), 1, '' '', NULL, 1, 0, 0, ''Id Convenio Pagos'', ''T'');

END
ELSE
BEGIN
 
   INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
   VALUES (45191, (SELECT max(ID_ConvPago)+1 FROM CONV_CONVENIOS_PAG WHERE ID_ConvPago<99999), 1, '' '', NULL, 1, 0, 0, ''Id Convenio Pagos'', ''T'');

 
END

')