EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (51007, '' '', 0, ''MONETARIO'', ''Monetario'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 5100, ''Monetario'', 0, NULL)

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (51007, ''E'', ''No'', ''N'', ''N'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (51007, ''E'', ''Si'', ''S'', ''S'')
')

EXECUTE('
UPDATE DICCIONARIO
SET NUMERODECAMPO = 51000
	, USODELCAMPO = '' ''
	, REFERENCIA = 0
	, DESCRIPCION = ''Rubro Origen''
	, PROMPT = ''Rubro Origen''
	, LARGO = 15
	, TIPODECAMPO = ''N''
	, DECIMALES = 0
	, EDICION = NULL
	, CONTABILIZA = 0
	, CONCEPTO = 0
	, CALCULO = 0
	, VALIDACION = 0
	, TABLADEVALIDACION = 63
	, TABLADEAYUDA = 634
	, OPCIONES = 0
	, TABLA = 5100
	, CAMPO = ''RUBRO_ORIGEN''
	, BASICO = 0
	, MASCARA = NULL
WHERE NUMERODECAMPO = 51000

UPDATE DICCIONARIO
SET NUMERODECAMPO = 51002
	, USODELCAMPO = '' ''
	, REFERENCIA = 0
	, DESCRIPCION = ''Rubro Destino del Ajueste''
	, PROMPT = ''Rubro Destino''
	, LARGO = 15
	, TIPODECAMPO = ''N''
	, DECIMALES = 0
	, EDICION = NULL
	, CONTABILIZA = 0
	, CONCEPTO = 0
	, CALCULO = 0
	, VALIDACION = 0
	, TABLADEVALIDACION = 63
	, TABLADEAYUDA = 634
	, OPCIONES = 0
	, TABLA = 5100
	, CAMPO = ''RUBRO_DESTINO''
	, BASICO = 0
	, MASCARA = NULL
WHERE NUMERODECAMPO = 51002

UPDATE DICCIONARIO
SET NUMERODECAMPO = 51003
	, USODELCAMPO = '' ''
	, REFERENCIA = 0
	, DESCRIPCION = ''Rubro Patrimonial''
	, PROMPT = ''Patrimonial''
	, LARGO = 15
	, TIPODECAMPO = ''N''
	, DECIMALES = 0
	, EDICION = NULL
	, CONTABILIZA = 0
	, CONCEPTO = 0
	, CALCULO = 0
	, VALIDACION = 0
	, TABLADEVALIDACION = 63
	, TABLADEAYUDA = 634
	, OPCIONES = 0
	, TABLA = 5100
	, CAMPO = ''RUBRO_PATRIMONIAL''
	, BASICO = 0
	, MASCARA = NULL
WHERE NUMERODECAMPO = 51003
')

EXECUTE('
UPDATE AYUDAS
SET NUMERODEARCHIVO = 5100
	, NUMERODEAYUDA = 51001
	, DESCRIPCION = ''Ayuda Ajuste por Inflación''
	, FILTRO = ''''
	, MOSTRARTODOS = 0
	, CAMPOS = ''51000R;51002;51003;51007;51004;''
	, CAMPOSVISTA = NULL
	, BASEVISTA = NULL
	, NOMBREVISTA = NULL
	, AYUDAGRANDE = 0
WHERE NUMERODEAYUDA = 51001
')