


-- Parche_NUNBCHACO_1500

-- Insertando parametros proceso
INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
		VALUES ('CALIFICACION_DEUDA_REFINANCIADA', 'CONSUMO_P_PERIODO_MAYOR', 60, 0);		
		INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
		VALUES ('CALIFICACION_DEUDA_REFINANCIADA', 'CONSUMO_P_CUOTAS_MENOR', 1, 0);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20240523_1NBCHAR',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fMTUwMAoNCi0tIEluc2VydGFuZG8gcGFyYW1ldHJvcyBw
cm9jZXNvDQpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pUUyAoRlVOQ0lPTkFMSURBRCwgUEFSQU1F
VFJPLCBWQUxPUiwgVFpfTE9DSykKCQlWQUxVRVMgKCdDQUxJRklDQUNJT05fREVVREFfUkVGSU5B
TkNJQURBJywgJ0NPTlNVTU9fUF9QRVJJT0RPX01BWU9SJywgNjAsIDApOwkJCgkJSU5TRVJUIElO
VE8gUEFSQU1FVFJPU19KVFMgKEZVTkNJT05BTElEQUQsIFBBUkFNRVRSTywgVkFMT1IsIFRaX0xP
Q0spCgkJVkFMVUVTICgnQ0FMSUZJQ0FDSU9OX0RFVURBX1JFRklOQU5DSUFEQScsICdDT05TVU1P
X1BfQ1VPVEFTX01FTk9SJywgMSwgMCk7Cg0KCgoNCg==', NULL, 0);
