EXECUTE('
------------------------------
--AGREGAMOS CAMPO A METADATA--
------------------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45789, '' '', 0, ''ID Cliente Pagador'', ''ID Cliente Pagador'', 22, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4459, ''CLIENTE_PAGADOR'', 0, NULL)
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45802, '' '', 0, ''ID Cliente Pagador'', ''ID Cliente Pagador'', 22, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4466, ''IDENTIF_CLIENTE'', 0, NULL)
----
UPDATE dbo.DICCIONARIO
SET LARGO = 2
WHERE NUMERODECAMPO = 44699
----
UPDATE dbo.DICCIONARIO
SET TIPODECAMPO = ''A''
WHERE NUMERODECAMPO = 45638
----
')