--TABLA_FISICA

EXECUTE('CREATE TABLE CON_SOLICITUD_BAJA_ASIENTO
	(ASIENTO        NUMERIC (10) DEFAULT ((0)) NOT NULL,
	SUCURSAL       NUMERIC (5) DEFAULT ((0)) NOT NULL,
	FECHAPROCESO   DATETIME NOT NULL,
	ESTADO         VARCHAR (1) DEFAULT ('' ''),
	USUARIO        VARCHAR (10) DEFAULT ('' ''),
	TIPO_SOLICITUD VARCHAR (3) DEFAULT ('' ''),
	TZ_LOCK        NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CON_SOLICITUD_BAJA_ASIEN_01 PRIMARY KEY (ASIENTO, SUCURSAL, FECHAPROCESO))')
