EXECUTE('
IF OBJECT_ID (''dbo.RRII_SELLOS_CABA'') IS NOT NULL
	DROP TABLE dbo.RRII_SELLOS_CABA
')
EXECUTE('
CREATE TABLE dbo.RRII_SELLOS_CABA
	(
	ID                 NUMERIC (15) IDENTITY,
	FECHA_PROCESO      DATETIME NOT NULL,
	PERIODO            VARCHAR (6) NOT NULL,
	CUIT1              VARCHAR (20) DEFAULT ('' '') NOT NULL,
	CUIT2              VARCHAR (20) DEFAULT ('' '') NOT NULL,
	MONTO_CONTRATO     NUMERIC (9, 2),
	BASE_IMPONIBLE     NUMERIC (9, 2),
	IMPORTE_RETENIDO   NUMERIC (9, 2),
	CODIGO_EXENCION    VARCHAR (6),
	CODIGO_ACTOS       VARCHAR (6),
	FECHA_CONTRATO     DATETIME,
	POLIZA_TRANSACCION VARCHAR (15),
	CBU                VARCHAR (22) DEFAULT ('' '') NOT NULL,
	CONSTRAINT PK_RRII_SELLOS_CABA PRIMARY KEY (FECHA_PROCESO, PERIODO, CUIT1)
	)
')

EXECUTE('
INSERT INTO dbo.RRI_PARAMETROS_DEF (CODIGO, NOMBRE, ID1, ID1DESC, ID2, ID2DESC, ID3, ID3DESC, ID4, ID4DESC, ID5, ID5DESC, NUM1, NUM1DESC, NUM2, NUM2DESC, CHAR1, CHR1DESC, CHAR2, CHR2DESC, TZ_LOCK)
VALUES (508, ''PARAM_SELLOS_CABA'', ''N'', '''', ''N'', '''', ''N'', '''', ''S'', ''C6800'', ''S'', ''DESCRIPCION'', ''S'', ''COD_ACTO'', ''N'', '''', ''S'', ''COD_POLIZA'', ''N'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''A'', ''ACUERDO EN CC'', 138001, 0, ''CD'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''AH'', ''ADELANTO HABERES'', 138009, 0, ''CM'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''C'', ''PRESTAMO COMERCIAL'', 138000, 0, ''PR'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''D'', ''DESCUENTO DOCUMENTOS'', 138009, 0, ''CV'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''L'', ''LEASING'', 138007, 0, ''LG'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''PP'', ''PRESTAMOS PERSONALES'', 138000, 0, ''PP'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''R'', ''RESTRUCTURADO'', 138000, 0, ''PR'', '''', 0)


INSERT INTO dbo.RRI_PARAMETROS_INF (CODIGO, ID1, ID2, ID3, ID4, ID5, NUM1, NUM2, CHAR1, CHAR2, TZ_LOCK)
VALUES (508, 0, 0, 0, ''S'', ''ACUERDO EXTRAORD'', 138001, 0, ''CD'', '''', 0)

')