execute('
CREATE or alter PROCEDURE USP_DisableEnableNonClusteredIndexes  (@DB_NAME SYSNAME, @MODEID CHAR(1), @TABLE_NAME VARCHAR(60), @COLUMN_NAMES VARCHAR(300))
AS
-- ************** Functionality ********************
-- This script Disables or Enables Non-Clustered indexes that are not part of a primary key or unique key.

-- ************** Input Parameters ********************
-- @Db_Name, Name of database for which you want to disable /Rebuild Non-Clustered Indexes
-- MODEID = 1 SCRIPT DISABLES ALL NON-CLUSTERED INDEXES.
-- MODEID = 2 SCRIPT ENABLES / REBUILD ALL NON-CLUSTERED INDEXES.

--  ******************** Compatiblility  ********************
-- Compatible with Sql Server 2005 and higher versions.

SET NOCOUNT ON
DECLARE @SQL1 VARCHAR(2000)
DECLARE @SQL2 VARCHAR(2000)
DECLARE @SQL3 VARCHAR(2000)
DECLARE @SQL4 VARCHAR(2000)

IF (SELECT COUNT(*) FROM TEMPDB..SYSOBJECTS WHERE NAME = ''##STOREINDEXINFORMATION'') > 0
  BEGIN
	DROP TABLE ##STOREINDEXINFORMATION
  END

SET  @SQL1 = ''USE ''+@DB_NAME+ ''
SELECT	IDENT = IDENTITY (INT,1,1)
		,SC.[TABLE_SCHEMA]+''''.''''+SC.[TABLE_NAME] [FULLOBJECTNAME]
		,SI.[NAME] [INDEXNAME]
INTO	##STOREINDEXINFORMATION		
FROM		
SYS.INDEXES I 
JOIN SYS.TABLES T ON I.[OBJECT_ID] = T.[OBJECT_ID] 
JOIN SYSINDEXES SI ON SI.ID = T.[OBJECT_ID] 
JOIN INFORMATION_SCHEMA.TABLES SC ON SC.TABLE_NAME = OBJECT_NAME (T.[OBJECT_ID])
WHERE	I.[INDEX_ID] > 1 
		AND		I.[TYPE] = 2 
		AND		I.[IS_PRIMARY_KEY] <> 1
		AND		I.[IS_UNIQUE_CONSTRAINT] <> 1
		AND		I.[INDEX_ID] = SI.INDID
		AND		SC.[TABLE_NAME] = '''''' + @TABLE_NAME + ''''''
		AND 	SI.[NAME] NOT IN (SELECT I.NAME 
									FROM   SYS.INDEXES I 
									JOIN SYS.INDEX_COLUMNS IC ON I.[OBJECT_ID] = IC.[OBJECT_ID ]AND I.[INDEX_ID] = IC.[INDEX_ID]
									JOIN SYS.COLUMNS C ON IC.[OBJECT_ID] = C.[OBJECT_ID] AND IC.[COLUMN_ID] = C.[COLUMN_ID] 
									JOIN SYS.TABLES T ON I.[OBJECT_ID] = T.[OBJECT_ID] 
									WHERE	I.[TYPE] = 2 
											AND		I.[IS_PRIMARY_KEY] <> 1
											AND		I.[IS_UNIQUE_CONSTRAINT] <> 1
									       	AND T.[NAME] = '''''' + @TABLE_NAME + ''''''
									       	AND C.[NAME] IN ( '''''' + @COLUMN_NAMES + '''''' ) )''

EXEC (@SQL1)

DECLARE @VAR1 INT
DECLARE @TOTALCOUNT INT
DECLARE @COUNT INT
SET  	@TOTALCOUNT = 0
SET		@COUNT  = 0
DECLARE @MODEDESCRIPTION VARCHAR(50)
SELECT @MODEDESCRIPTION  =	CASE	WHEN @MODEID = 1 THEN ''Disabl''
									ELSE ''Enabl''
							END	
PRINT ''Started ''+@MODEDESCRIPTION +''ing all Non-clustered indexes...''

SET @VAR1 = 1
WHILE @VAR1 < = ( SELECT COUNT(*) FROM ##STOREINDEXINFORMATION)
BEGIN 
	DECLARE @OBJECTNAME VARCHAR(256)
	DECLARE @INDEXNAME VARCHAR(128)
	DECLARE @SQLCMD VARCHAR(1000)
	

	SELECT	@OBJECTNAME = [FULLOBJECTNAME]
			, @INDEXNAME = [INDEXNAME] 
	FROM	##STOREINDEXINFORMATION 
	WHERE	[IDENT] = @VAR1
	
	IF @MODEID = 1 -- DISABLE
	  BEGIN
		SET @SQLCMD =''USE ''+@DB_NAME+'' ALTER INDEX ''+@INDEXNAME +'' ON ''+@OBJECTNAME+'' DISABLE ''
		EXEC (@SQLCMD)
		
	END

	IF @MODEID = 2 -- ENABLE/REBUILD
	  BEGIN
		SET @SQLCMD =''USE ''+@DB_NAME+'' ALTER INDEX ''+@INDEXNAME +'' ON ''+@OBJECTNAME+'' REBUILD''
		EXEC (@SQLCMD)
	END

	
	IF (SELECT COUNT(*) FROM ##STOREINDEXINFORMATION )= @VAR1 
	 BEGIN
		SET @TOTALCOUNT = @VAR1
	 END
	 SET @VAR1 = @VAR1 + 1
END

IF @TOTALCOUNT = (SELECT COUNT(*) FROM ##STOREINDEXINFORMATION)
  BEGIN
	PRINT ''Successfully finished ''+@MODEDESCRIPTION+''ing Non-clustered indexes for ''+ @TABLE_NAME +'' table''
  END 
	
IF @TOTALCOUNT <> (SELECT COUNT(*) FROM ##STOREINDEXINFORMATION)
  BEGIN
	PRINT ''Could not ''+@MODEDESCRIPTION+''e all Non-clustered index due to some reason for more information check sql server logs''
  END

DROP TABLE ##STOREINDEXINFORMATION
SET NOCOUNT OFF
-- End of Stored procedure 
; ')
