EXECUTE('
CREATE OR ALTER PROCEDURE [dbo].[SP_DOCUMENTO_CLIENTE]
  @pDocumento 	  VARCHAR(20),
  @pcODIGOcLIENTE NUMERIC(20) OUT
AS
BEGIN

	SELECT TOP 1 @pCODIGOCLIENTE = CODIGOCLIENTE
	FROM VW_CLI_X_DOC
	WHERE NUMERODOC = @pDocumento
	  AND TIPODOC IN (''CUIL'',''CUIT''); 
	
END

')