EXECUTE('
----
IF OBJECT_ID (''dbo.SNP_MSG_CABEZAL'') IS NOT NULL
	DROP TABLE dbo.SNP_MSG_CABEZAL
----
')
EXECUTE('
----
CREATE TABLE dbo.SNP_MSG_CABEZAL
	(
	TZ_LOCK          NUMERIC (15) DEFAULT ((0)) NOT NULL,
	LOTE_ID          NUMERIC (7) DEFAULT ((0)) NOT NULL,
	CUIT_EO          NUMERIC (11) DEFAULT ((0)) NOT NULL,
	ID_ARCHIVO       VARCHAR (30) DEFAULT ('' '') NOT NULL,
	NRO_ARCHIVO      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	FECHA_RECEPCION  DATETIME,
	HORA_RECEPCION   VARCHAR (6),
	ESTADO           VARCHAR (2) DEFAULT ('' ''),
	USUARIO_INGRESO  VARCHAR (20) DEFAULT ('' ''),
	ESTACION_INGRESO VARCHAR (20) DEFAULT ('' ''),
	CONSTRAINT PK_SNP_MSG_CABEZAL_01 PRIMARY KEY (CUIT_EO, ID_ARCHIVO, NRO_ARCHIVO)
	)
----
')