EXECUTE('
CREATE VIEW dbo.VW_INTEGRANTESJUZGADOS (
   [Tipo Documento Identificativo], 
   [Número Documento Identificativo],
   [Tipo Documento Físico],
   [Número de Documento Físico],
   [Apellidos y Nombres],
   [Tipo de Persona], 
   [Nivel de Apertura],
   [Estado],
   [Motivo Inhabilitado],
   [Actor],
   [Descripción],
   [Fecha Integración],
   [Fecha Cese],
   [Activo],  
   [Persona],
   NRO_JUZGADO
   )
AS 
   SELECT TOP 9223372036854775807 WITH TIES 
      V.TIPODOCUMENTO , 
      V.NUMERODOCUMENTO ,
      V.TIPO_DOC_FISICO ,
      V.NUM_DOC_FISICO ,
      (U.APELLIDOPATERNO +'' ''+U.PRIMERNOMBRE) AS NOMBRES,
      V.TIPOPERSONA ,  
      (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA=''E'' AND O.OPCIONINTERNA=U.NIVEL_APERTURA AND O.NUMERODECAMPO = 2203) AS NIVEL_APERTURA,
      (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA=''E'' AND O.OPCIONINTERNA=U.ESTADO AND O.NUMERODECAMPO = 33366) AS ESTADO,   
	  (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA=''E'' AND O.OPCIONINTERNA=U.MOTIVO_INHABILITADO AND O.NUMERODECAMPO = 33368) AS  MOTIVO_INHABILITADO,  
	  DJI.ACTOR,
	  DJA.Descripcion,  
	  DJI.FECHA_INTEGRACION,
	  DJI.FECHA_CESE,
	  (SELECT DESCRIPCION FROM OPCIONES O WHERE O.IDIOMA=''E'' AND O.OPCIONINTERNA=DJI.ACTIVO AND O.NUMERODECAMPO = 33246) AS  ACTIVO,	  
      V.NUMEROPERSONAFJ,
      DJI.NRO_JUZGADO 
   FROM dbo.CLI_PERSONASFISICAS  AS U, dbo.CLI_DOCUMENTOSPFPJ  AS V, dbo.DJ_INTEGRANTES_JUZGADOS AS DJI, dbo.DJ_ACTORES AS DJA
   WHERE 
      U.NUMEROPERSONAFISICA = V.NUMEROPERSONAFJ AND 
      U.NUMEROPERSONAFISICA = DJI.ID_PERSONA	AND
      DJI.ACTOR = DJA.Id	AND
      (V.TIPOPERSONA = ''F'') AND 
      (U.TZ_LOCK =0) AND 
      (V.TZ_LOCK =0) AND 
      (DJA.TZ_LOCK =0)AND
      (DJI.TZ_LOCK =0)
   ORDER BY NUMEROPERSONAFJ
')

EXECUTE('
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 9382, ''Integrantes Juzgados'', '''', 0, ''1064;1963;537;622;274;1063;209;531;624;3261;6951;603;1200;118;1057R;'', ''Tipo Documento Identificativo;Número Documento Identificativo;Tipo Documento Físico;Número de Documento Físico;Apellidos y Nombres;Tipo de Persona;Nivel de Apertura;Estado;Motivo Inhabilitado;Actor;Descripción;Fecha Integración;Fecha Cese;Activo;Persona;'', ''Top/Clientes'', ''VW_INTEGRANTESJUZGADOS'', 0)

UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 9382
WHERE NUMERODECAMPO = 33271

UPDATE dbo.AYUDAS
SET CAMPOS = ''665;9106;3251R;950R;12111;1429R;118;2617R;231;''
WHERE NUMERODEAYUDA = 3584

UPDATE dbo.AYUDAS
SET CAMPOS = ''665;9106;3251R;950R;12111;1429R;3264;2617R;556;118;622;''
WHERE NUMERODEAYUDA = 3585

')
