EXECUTE('

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (8100, 8116, ''Actualiza estado de contratos de alquiler'', ''Actualiza estado de contratos de alquiler'', ''8116'', ''N'', 0, 0, ''P'', 0, 0, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')
