EXECUTE('

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35171

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35171, '' '', 0, ''CLE - Numerador cheqs. ajuste'', ''CLE - Numerador cheqs. ajuste'', 12, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 0, ''Num_cle_cheqs_ajuste'', 0, NULL)

DELETE FROM dbo.NUMERATORVALUES
WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 35171

INSERT INTO dbo.NUMERATORVALUES (DIA, MES, ANIO, SUCURSAL, NUMERO, VALOR)
VALUES (0, 0, 0, 0, 35171, 1)
')

