--METADATA
-- CREACION CAMPO 37332

EXECUTE('        
IF EXISTS (SELECT a.NUMERODECAMPO  FROM DICCIONARIO A WHERE NUMERODECAMPO = 37332)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 37332;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
    VALUES (37332, '' '', 0, ''Código Actividad'', ''Código de Actividad'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''CODIGO_ACTIVIDAD'', 0, NULL);
   

END
ELSE
BEGIN
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
    VALUES (37332, '' '', 0, ''Código Actividad'', ''Código de Actividad'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''CODIGO_ACTIVIDAD'', 0, NULL);
   

END
')
