Execute('
DROP TABLE IF EXISTS REL_CLIENTE_CTA_COMITENTE
CREATE TABLE REL_CLIENTE_CTA_COMITENTE (
  Cuenta NUMERIC(12),
  Cliente NUMERIC(12) NOT NULL,
  FechaAlta DATE,
  PRIMARY KEY (Cuenta,Cliente)
);


DELETE FROM dbo.OPERACIONES WHERE TITULO = 7901 AND IDENTIFICACION = 7942

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (7901, 7942, ''CLIT014 relCCyCLI'', ''Relacion Cliente y Cuenta Conmitente'', ''7942'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')
