/****** Object:  View [dbo].[VW_TRANSF_ENTRE_CUENTAS]    Script Date: 24/02/2021 17:31:25 ******/
DROP VIEW [dbo].[VW_TRANSF_ENTRE_CUENTAS]
GO

/****** Object:  View [dbo].[VW_TRANSF_ENTRE_CUENTAS]    Script Date: 24/02/2021 17:31:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_TRANSF_ENTRE_CUENTAS](
									TZ_LOCK,
									SUCURSAL_FUENTE, 
									CUENTA_FUENTE, 
									PRODUCTO_FUENTE, 
									MONEDA_FUENTE,
									IMPORTE_A_TRANSFERIR, 
									DIA_MES_TRANSF, 
									PORC_AJUSTE_IMPORTE,
									SUCURSAL_DESTINO, 
									CUENTA_DESTINO, 
									PRODUCTO_DESTINO, 
									MONEDA_DESTINO)
AS 
					SELECT
								T.TZ_LOCK,
								F.SUCURSAL AS SUCURSAL_FUENTE, 
								F.CUENTA AS CUENTA_FUENTE,
								F.PRODUCTO AS PRODUCTO_FUENTE, 
								F.MONEDA AS MONEDA_FUENTE,
								T.IMPORTE_A_TRANSFERIR, 
								T.DIA_MES_TRANSF, 
								T.PORC_AJUSTE_IMPORTE, 
								D.SUCURSAL AS SUCURSAL_DESTINO,
								D.CUENTA AS CUENTA_DESTINO, 
								D.PRODUCTO AS PRODUCTO_DESTINO, 
								D.MONEDA AS MONEDA_DESTINO
					FROM CV_TRANSFERENCIA AS T with (nolock)
							inner join SALDOS AS F with (nolock) on F.JTS_OID = T.JTS_OID_CTA_FUENTE 
							inner join SALDOS AS D with (nolock) on D.JTS_OID = T.JTS_OID_CTA_DESTINO
GO


