EXECUTE('
IF OBJECT_ID (''dbo.VW_RRII_IERIC_MENSUAL'') IS NOT NULL
	DROP VIEW dbo.VW_RRII_IERIC_MENSUAL
')

EXECUTE('
CREATE   VIEW VW_RRII_IERIC_MENSUAL AS

SELECT
	VS.CTA_CBU,
	HV.EQUIVALENTEMN AS CAPITALREALIZADO,
	D.NUMERODOCUMENTO AS CUIL_EMPLEADO,
	AE.RUC_INDEPENDIENTE AS CUIT_EMPLEADOR,
	HV.FECHA_VALOR
FROM
CLI_DocumentosPFPJ D WITH (nolock)
INNER JOIN CLI_CLIENTEPERSONA CP WITH (nolock)ON D.NUMEROPERSONAFJ = CP.NUMEROPERSONA
											AND CP.TITULARIDAD = ''T''
INNER JOIN CLI_ACTIVIDAD_ECONOMICA AE WITH (nolock)ON AE.CODIGO_PERSONA_CLIENTE = D.NUMEROPERSONAFJ 
													AND AE.FUENTE_INGRESO = ''D''
	--MC para traer datos del empleado
INNER JOIN SALDOS S_EMPLEADO WITH (nolock) ON CP.CODIGOCLIENTE = S_EMPLEADO.C1803
INNER JOIN HISTORIA_VISTA HV WITH (nolock)ON HV.SALDO_JTS_OID = S_EMPLEADO.JTS_OID
											AND YEAR(HV.FECHA_VALOR) = (SELECT YEAR(P.FECHAPROCESO) FROM PARAMETROS P WITH(nolock)) 
											AND HV.DEBITO_CREDITO = ''C''
INNER JOIN ASIENTOS A WITH (nolock) ON HV.ASIENTO = A.ASIENTO
										AND HV.SUCURSAL = A.SUCURSAL
										AND HV.FECHA_PROCESADO = A.FECHAPROCESO
										AND A.ESTADO = 77
	--En este join de saldos traigo los datos del empleado, es decir, en la cuenta en la cual afectó el saldo
INNER JOIN VTA_SALDOS VS WITH (nolock) ON HV.SALDO_JTS_OID = VS.JTS_OID_SALDO 
');


	
	
	
	
	

