EXECUTE('
----------------------------
--UPDATE CARGOS CAJAS SEG.--
----------------------------
UPDATE dbo.CI_CARGOS
SET PIVOT_ = 203
WHERE ID_CARGO = 240
----
DELETE CI_IMPUESTOS_X_CARGO WHERE ID_CARGO=240
--
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (7, 240, ''A'', 0, 1357, ''Cond IVA'')
--
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (8, 240, ''A'', 0, 1357, ''Cond Percep IVA'')
--
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 240, ''A'', 0, 34096, ''Cond CREDEB'')
----
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (2113, ''CUOTAS ALQUILER CAJAS DE SEGURIDAD'', 0)
----
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (212, 2113, 0, ''A'', 0, ''CAJAS DE SEGURIDAD - CUOTA DETALLADA EN CONTRATO'', 1)
----
')

