EXECUTE('

INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (731, ''Controles cierre'', ''14,15,16'', NULL, NULL, 0, 0, 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35341, '' '', 0, ''Opciones agrega cont./ver productos'', ''Opciones agrega cont./ver productos'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Opciones agrega cont./ver prod'', 0, NULL)
')

EXECUTE('
IF OBJECT_ID (''dbo.VW_CLE_CHEQUES_CLEARING_RECIBIDO'') IS NOT NULL
	DROP VIEW dbo.VW_CLE_CHEQUES_CLEARING_RECIBIDO
')

EXECUTE('
CREATE   VIEW [dbo].[VW_CLE_CHEQUES_CLEARING_RECIBIDO]
															(NRO_CHEQUE, 
															SUCURSAL, 
															CUENTA, 
															DENOMINACION_CUENTA, 
															PRODUCTO, 
															DESC_PRODUCTO, 
															MONEDA, 
															IMPORTE, 
															CAUSAL, 
															DESC_CAUSAL, 
															FECHA,
															JTS_OID)
AS
SELECT R.NUMERO_CHEQUE, 
		R.SUCURSAL, 
		R.CUENTA, 
		V.NOMBRE_CUENTA, 
		R.PRODUCTO, 
		P.C6251, 
		R.MONEDA, 
		R.IMPORTE_CHEQUE, 
		R.CODIGO_CAUSAL_DEVOLUCION, 
		C.DESCRIPCION, 
		R.FECHA,
		S.JTS_OID
FROM CLE_CHEQUES_CLEARING_RECIBIDO AS R WITH (nolock)
INNER JOIN SALDOS AS S WITH (nolock) ON R.SUCURSAL = S.SUCURSAL 
										AND R.MONEDA = S.MONEDA 
										AND R.CUENTA = S.CUENTA 
										AND R.PRODUCTO = S.PRODUCTO 
										AND R.OPERACION = S.OPERACION 
										AND S.ORDINAL = 0 
										AND S.TZ_LOCK = 0
INNER JOIN VTA_SALDOS AS V WITH (nolock) ON S.JTS_OID = V.JTS_OID_SALDO 
										AND V.TZ_LOCK = 0
INNER JOIN PRODUCTOS AS P WITH (nolock) ON R.PRODUCTO = P.C6250 
										AND P.TZ_LOCK = 0
LEFT JOIN CLE_TIPO_CAUSAL AS C WITH (nolock) ON R.CODIGO_CAUSAL_DEVOLUCION = C.CODIGO_DE_CAUSAL
										AND C.TZ_LOCK = 0
										
')

EXECUTE('
INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (3434, 1, 87, 0)

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (3505, 3433, ''Solicitud de cierre caja de ahorro'', ''Solicitud de cierre caja de ahorro'', ''3433'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (3505, 3434, ''Aceptación cheques cuentas cerradas'', ''Aceptación cheques cuentas cerradas'', ''3434'', ''N'', 500, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (3505, 3437, ''Controles automáticos monitor cierre'', ''Controles automáticos monitor cierre'', ''3437'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

')
