EXECUTE('
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (8600, 8716, ''Cobranza TC'', ''Cobranza TC'', ''8716'', ''N'', 500, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, NULL)

')