EXECUTE('
IF OBJECT_ID (''dbo.VTA_TRANSFERENCIAS_DEBIN'') IS NOT NULL
	DROP TABLE dbo.VTA_TRANSFERENCIAS_DEBIN
')
EXECUTE('
CREATE TABLE dbo.VTA_TRANSFERENCIAS_DEBIN
	(
	TZ_LOCK                  NUMERIC (15) DEFAULT ((0)) NOT NULL,
	TRANSACCION              VARCHAR (6) NOT NULL,
	SUCURSAL                 NUMERIC (5),
	NRO_CUENTA               NUMERIC (11) DEFAULT ((0)) NOT NULL,
	SUBSISTEMA               VARCHAR (2),
	FECHALOCAL               VARCHAR(8),
	HORALOCAL                VARCHAR (8),
	RECIBO                   VARCHAR (12) DEFAULT ((0)) NOT NULL,
	TERMINAL                 VARCHAR (16),
	INFORMACION              VARCHAR (35),
	CONCEPTO                 VARCHAR (10),
	BCO_BCRA                 VARCHAR (4),
	CUIT                     NUMERIC (11),
	CBU_BLOQUE1              VARCHAR (8),   
	CBU_BLOQUE2              VARCHAR (14), 
	CUENTA                   VARCHAR (19),
	MOVIMIENTO_CONTRASENTADO NUMERIC (1),
	ID_MOVIMIENTO_SIDEBA     VARCHAR (26),  
	SECUENCIA                VARCHAR (5),
	RENGLON                  VARCHAR (7),    
	NUMERO_TARJETA           VARCHAR (19),
	NOMBREAPELLCOMPRADOR     VARCHAR (40),
	MISMOTITULAR             VARCHAR (1),
	DEBITO_PREAUTORIZADO     VARCHAR (1),
	DEBIN_TRANSF_CONTRACT    VARCHAR (1),
	SCORING                 VARCHAR (3),
	IDENTID_CONTRACARGO      VARCHAR (32),
	MOTIVO_CONTRACARGO       VARCHAR (3),
	CONSTRAINT PK_VTA_TRANSFERENCIAS_DEBIN_01 PRIMARY KEY (NRO_CUENTA, TRANSACCION, RECIBO)
	)

')

