EXECUTE('

INSERT INTO CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK) ----433
VALUES (505, ''DEVOLUCIÓN IMPUESTO Pais'', 0)

INSERT INTO CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK) ---434
VALUES (506, ''DEVOLUCIÓN Percep 4815'', 0)


INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (433, 505, 0, ''A'', 0, ''CONDICIÓN Imp Pais'', 1)


INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (434, 506, 0, ''A'', 0, ''CONDICIÓN Percep 4815'', 1)
')

