EXECUTE('
CREATE OR ALTER   PROCEDURE [dbo].[SP_ITF_SOS_ACTUALIZA_PERFILDOC]
	@Fecha VARCHAR(8)
AS
BEGIN

--Limpiamos por si hay reproceso
DELETE FROM SOS_ACTUALIZA_PERFILDOC WHERE convert(VARCHAR,FECHADEINFORMACION) = @Fecha;

SELECT c.*
  INTO #TMP_CLIPERFILDOCUMENTAL
FROM CLI_PERFILDOCUMENTAL c
WHERE c.FECHA_ACTUALIZACION = (SELECT MAX(cc.FECHA_ACTUALIZACION) 
                               FROM CLI_PERFILDOCUMENTAL cc
					           WHERE cc.ID_PERSONA = c.ID_PERSONA
					             AND cc.TZ_LOCK = 0)
  AND c.TZ_LOCK = 0

INSERT INTO SOS_ACTUALIZA_PERFILDOC
SELECT @Fecha AS FECHADEINFORMACION,
  IDENTTRIBUTARIANUMERO,
  CONVERT(VARCHAR,d.FECHA_ACTUALIZACION,112) AS FECHAINICIOVIGENCIA,
  CONVERT(VARCHAR,d.FECHA_VIGENCIA_HASTA,112) AS FECHAVCTOVIGENCIA,
  @Fecha AS FECHADESDEPROCESO,
  @Fecha AS FECHAHASTAPROCESO
FROM dbo.SOS_CLIENTES c
  INNER JOIN #TMP_CLIPERFILDOCUMENTAL d ON d.ID_PERSONA = c.NUMEROPERSONA
WHERE c.FECHADEINFORMACION = @Fecha
  AND c.TIPOCLIENTE = ''PF''
UNION ALL
SELECT @Fecha AS FECHADEINFORMACION,
  IDENTTRIBUTARIANUMERO,
  CONVERT(VARCHAR,d.FECHA_ACTUALIZACION,112) AS FECHAINICIOVIGENCIA,
  CONVERT(VARCHAR,d.FECHA_VIGENCIA_HASTA,112) AS FECHAVCTOVIGENCIA,
  @Fecha AS FECHADESDEPROCESO,
  @Fecha AS FECHAHASTAPROCESO
FROM dbo.SOS_CLIENTES_SINMOV c
  INNER JOIN #TMP_CLIPERFILDOCUMENTAL d ON d.ID_PERSONA = c.NUMEROPERSONA
WHERE c.FECHADEINFORMACION = @Fecha
  AND c.TIPOCLIENTE = ''PJ''

END
')