EXECUTE('DROP TABLE IF EXISTS dbo.ITF_BCRA_PADFYJ;')
EXECUTE('CREATE TABLE dbo.ITF_BCRA_PADFYJ
	(
	CUIT            NUMERIC (12) DEFAULT ((0)) NOT NULL,
	APELLIDOS       VARCHAR (60) DEFAULT ('' ''),
	ACTIVIDAD       NUMERIC (6) DEFAULT ((0)),
	MARCA_FALLECIDO VARCHAR (1) DEFAULT ('' ''),
	APELLIDOMATERNO VARCHAR (30) DEFAULT ('' ''),
	NOMBRES         VARCHAR (60) DEFAULT ('' ''),
	SEGUNDONOMBRE   VARCHAR (30) DEFAULT ('' ''),
	TZ_LOCK         NUMERIC (15) DEFAULT ((0)) NOT NULL,
	NOMBRE_COMPLETO VARCHAR (160),
	CONSTRAINT PK_ITF_BCRA_PADFYJ_01 PRIMARY KEY (CUIT)
	);')

