UPDATE CI_FORMULAS
SET FORMULA = '((C34499=60)O(C34499>60))YC34965#''S'''
WHERE ID_FORMULA = 1200


EXECUTE('

UPDATE CI_CARGOS
SET ID_FORMULA = 1201
WHERE ID_CARGO = 1200


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34967, NULL, 0, ''Meses de notificado'', ''MESES NOTIFICADO'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3438, ''MESES_NOTIFICADO'', 0, NULL)


INSERT INTO CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (1201, ''COBRO COMISION SALDO INMOVILIZADO DPF'', ''C3298*C34967'', 0, 1)
')