EXECUTE('

DELETE FROM PROD_RELSECTORES WHERE PRODUCTO IN (SELECT C6250 FROM PRODUCTOS WHERE C6252 IN (2,3))

INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (1, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (2, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (3, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (4, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (5, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (5, ''3'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (5, ''4'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (5, ''5'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (6, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (7, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (9, ''3'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (9, ''4'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (10, ''3'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (10, ''4'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (12, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (16, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (17, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (18, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (19, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (23, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (24, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''3'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''4'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''5'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''6'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (51, ''7'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (52, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (14, ''1'', 0)



INSERT INTO PROD_RELSECTORES (PRODUCTO, SECTOR, TZ_LOCK)
VALUES (53, ''1'', 0)


')

