EXECUTE('

IF OBJECT_ID (''dbo.CLI_HISTORICO_INAES'') IS NOT NULL
	DROP TABLE dbo.CLI_HISTORICO_INAES

CREATE TABLE dbo.CLI_HISTORICO_INAES
	(
	USUARIO              VARCHAR (10) DEFAULT ('' ''),
	CUIT                 NUMERIC (12) DEFAULT ((0)) NOT NULL,
	NRO_INTERNO          NUMERIC (4) DEFAULT ((0)),
	FECHA_REALIZACION    DATETIME,
	ASIENTO              NUMERIC (10) DEFAULT ((0)),
	ESTADO_BLOQUEO       NUMERIC (1) DEFAULT ((0)),
	CUENTA               NUMERIC (15) DEFAULT ((0)),
	SUCURSAL             NUMERIC (5) DEFAULT ((0)),
	TZ_LOCK              NUMERIC (15) DEFAULT ((0)) NOT NULL,
	JTSOID               NUMERIC (10) NOT NULL,
	ASIENTO_MODIFICACION NUMERIC (10),
	FECHA_ACTUALIZACION  DATETIME,
	ANT_COD_RENOV        VARCHAR (1),
	REGISTRO_REVERSADO        VARCHAR (1),
	CONSTRAINT PK_CLI_HISTORICO_INAES_01 PRIMARY KEY (CUIT, JTSOID, FECHA_REALIZACION, ASIENTO, SUCURSAL)
	)

')

EXECUTE('

ALTER TABLE CLI_INHABILITADOS_INAES ADD PERSONAJURIDICA_ENCONTRADA NUMERIC(12,0) DEFAULT(0) 

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 41157

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41157, '' '', 0, ''PERSONAJURIDICA_ENCONTRADA'', ''PERSONAJURIDICA_ENCONTRADA'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3308, ''PERSONAJURIDICA_ENCONTRADA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41335, '' '', 0, ''ANT_COD_RENOV'', ''ANT_COD_RENOV'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3324, ''ANT_COD_RENOV'', 0, NULL)





UPDATE dbo.INDICES
SET CAMPO1 = 33241
	, CAMPO2 = 33278
	, CAMPO3 = 33243
	, CAMPO4 = 33244
	, CAMPO5 = 33279
WHERE NUMERODEARCHIVO = 3324 AND NUMERODEINDICE = 1





INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41336, '' '', 0, ''REGISTRO_REVERSADO'', ''REGISTRO_REVERSADO'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3324, ''REGISTRO_REVERSADO'', 0, NULL)

')