


-- Parche_NUBANKIBR_508

alter table HISTORICO_DEVENGAMIENTO add FECHA_CALCULADO_SUSPENSO	  DATETIME;
			alter table HISTORICO_DEVENGAMIENTO add MOTIVO_SUSPENSO			      VARCHAR(9) default (' ');
			alter table HISTORICO_DEVENGAMIENTO add MORA_PERCIBIDA				  numeric(15, 2) default (0) with values;
			alter table HISTORICO_DEVENGAMIENTO add IPFMORATORIO_PERCIBIDO		  numeric(15, 2) default (0) with values;




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20240710_2',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVUJBTktJQlJfNTA4Cg0KYWx0ZXIgdGFibGUgSElTVE9SSUNPX0RFVkVO
R0FNSUVOVE8gYWRkIEZFQ0hBX0NBTENVTEFET19TVVNQRU5TTwkgIERBVEVUSU1FOwoJCQlhbHRl
ciB0YWJsZSBISVNUT1JJQ09fREVWRU5HQU1JRU5UTyBhZGQgTU9USVZPX1NVU1BFTlNPCQkJICAg
ICAgVkFSQ0hBUig5KSBkZWZhdWx0ICgnICcpOwoJCQlhbHRlciB0YWJsZSBISVNUT1JJQ09fREVW
RU5HQU1JRU5UTyBhZGQgTU9SQV9QRVJDSUJJREEJCQkJICBudW1lcmljKDE1LCAyKSBkZWZhdWx0
ICgwKSB3aXRoIHZhbHVlczsKCQkJYWx0ZXIgdGFibGUgSElTVE9SSUNPX0RFVkVOR0FNSUVOVE8g
YWRkIElQRk1PUkFUT1JJT19QRVJDSUJJRE8JCSAgbnVtZXJpYygxNSwgMikgZGVmYXVsdCAoMCkg
d2l0aCB2YWx1ZXM7Cg0KCgoNCg==', NULL, 0);
