EXECUTE('
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43249, ''E'', ''Deuda Previsional en AFIP'', ''A'', ''A'')

INSERT INTO dbo.TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
VALUES (800, 6084, ''S'', ''Consulta Deuda AFIP'', ''Consulta Deuda AFIP'', ''C'', NULL, NULL)
')

