--ACTUALIZACION CLE_TIPO_CAUSAL Y CLE_CONTROLES_RECIBIDO (parametría cámara recibida)

DELETE CLE_TIPO_CAUSAL
DELETE CLE_CONTROLES_RECIBIDO

INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (1, 1, 'N', 230009, 'S', 'Inconsistencia del Cheque', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (2, 1, 'N', 230009, 'S', 'Existencia de Chequera', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (3, 1, 'N', 230009, 'S', 'Estado de Chequera Bloqueada', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (4, 1, 'N', 230009, 'S', 'Estado Chequera Denuncida Robo', 0)


INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (5, 1, 'N', 230009, 'S', 'Estado de Chequera Destruida', 0)


INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (6, 1, 'N', 230009, 'S', 'Estado de Chequera Anulada', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (7, 1, 'N', 230009, 'S', 'Estado del Cheque Anulado', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (8, 1, 'N', 230009, 'S', 'Estado Cheq. Denunciado Robado', 0)


INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (9, 1, 'N', 230009, 'S', 'Estado del Cheque Extraviado', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (10, 1, 'N', 230009, 'S', 'Estado del Cheque Ya Pagado', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (11, 1, 'N', 230009, 'S', 'Estado del Cheque Rechazado', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (12, 1, 'N', 230009, 'S', 'Estado del Cheque Stop Payment', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (13, 2, 'N', 230009, 'S', 'Existencia de la cuenta Saldos', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (14, 1, 'N', 230009, 'S', 'Estado del Saldo Cancelado', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (15, 1, 'N', 230009, 'S', 'Estado Saldo Cuenta Bloqueada', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (16, 3, 'N', 230009, 'S', 'Saldo Insuf en la Cuenta', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (17, 1, 'N', 230009, 'S', 'Diferencia en Importe', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (18, 1, 'N', 230009, 'S', 'Importe > truncamiento', 0)



INSERT INTO CLE_TIPO_CAUSAL (CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, TZ_LOCK)
VALUES (19, 1, 'N', 230009, 'S', 'Cheque Extraviado por Importe', 0)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (1, 'Inconsistencia del Cheque', 1, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (2, 'Existencia de Chequera', 2, 0, 2)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (3, 'Estado de Chequera Bloqueada', 3, 0, 2)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (4, 'Estado Chequera Denuncida Robo', 4, 0, 2)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (5, 'Estado de Chequera Destruida', 5, 0, 2)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (6, 'Estado de Chequera Anulada', 6, 0, 2)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (7, 'Estado del Cheque Anulado', 7, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (8, 'Estado Cheq. Denunciado Robado', 8, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (9, 'Estado del Cheque Extraviado', 9, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (10, 'Estado del Cheque Ya Pagado', 10, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (11, 'Estado del Cheque Rechazado', 11, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (12, 'Estado del Cheque Stop Payment', 12, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (13, 'Existencia de la cuenta Saldos', 13, 0, 0)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (14, 'Estado del Saldo Cancelado', 14, 0, 0)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (15, 'Estado Saldo Cuenta Bloqueada', 15, 0, 0)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (16, 'Saldo Insuficiente en la Cuenta', 16, 0, 0)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (17, 'Diferencia en Importe', 17, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (18, 'Importe > truncamiento', 18, 0, 1)



INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (19, 'Cheque Extraviado por Importe', 19, 0, 1)


