EXECUTE('
-------------------------------------
--ajustes en cle_controles_recibido--
-------------------------------------
DELETE CLE_CONTROLES_RECIBIDO WHERE CODIGO_DE_CONTROL BETWEEN 1 AND 19
----
')
EXECUTE('
----
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (1, ''Saldo inexistente'', 3, 0, 2)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (2, ''Cod postal erroneo p/sucursal'', 96, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (3, ''Estado del Saldo Cancelado'', 84, 0, 2)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (4, ''Existencia de Chequera'', 63, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (5, ''Estado de Chequera Bloqueada'', 48, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (6, ''Estado Chequera Denuncida Robo'', 49, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (7, ''Estado de Chequera Destruida'', 50, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (8, ''Estado de Chequera Anulada'', 51, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (9, ''Estado de Chequera Pendiente'', 52, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (10, ''Estado de Chequera Extraviada'', 53, 0, 1)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (11, ''Estado del Cheque Anulado'', 86, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (12, ''Estado Cheq. Denunciado Robado'', 12, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (13, ''Estado del Cheque Extraviado'', 13, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (14, ''Estado del Cheque Stop Payment'', 14, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (15, ''Estado Saldo Cuenta Bloqueada'', 83, 0, 2)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (16, ''Estado del Cheque Ya Pagado'', 37, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (17, ''Diferencia en Importe'', 54, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (18, ''No corresponde Segunda presentación'', 57, 0, 0)
--
INSERT INTO CLE_CONTROLES_RECIBIDO (CODIGO_DE_CONTROL, DESCRIPCION, CODIGO_CAUSAL, TZ_LOCK, MARCA_CHEQ_CHEQRA)
VALUES (19, ''Saldo Insuficiente en la Cuenta'', 15, 0, 2)
-------------------------------------
--Carga registro en cle_tipo_causal--
-------------------------------------
INSERT INTO CLE_TIPO_CAUSAL (TZ_LOCK, CODIGO_DE_CAUSAL, TIPO_RECHAZO, IMPUTAR_CUENTA_CLIENTE, RUBRO_SI_NO_IMPUTA_CLIENTE, DEVOLUCION_AUTOMATICA, DESCRIPCION, SEGUNDA_PRESENTACION, MODIF_DURANTE_DIA, COMISION, MULTA, CONTABILIZA_RECHAZO, CODIGO_NACHA, CODIGO_RRII, CODIGO_BCRA)
VALUES (0, 96, 1, ''N'', 230009, ''S'', ''Cod postal erroneo p/sucursal'', ''S'', ''T'', ''N'', ''N'', ''N'', 94, NULL, NULL)
-----------------------
--Topes Causal Cámara--
-----------------------
INSERT INTO dbo.CLE_TOPE_CAUSAL_CAMARA (CODIGO_CAUSAL, CODIGO_DE_CAMARA, MONTO, TZ_LOCK)
VALUES (92, 1, 9999999999999, 0)
--
INSERT INTO dbo.CLE_TOPE_CAUSAL_CAMARA (CODIGO_CAUSAL, CODIGO_DE_CAMARA, MONTO, TZ_LOCK)
VALUES (93, 1, 9999999999999, 0)
--
INSERT INTO dbo.CLE_TOPE_CAUSAL_CAMARA (CODIGO_CAUSAL, CODIGO_DE_CAMARA, MONTO, TZ_LOCK)
VALUES (94, 1, 9999999999999, 0)
--
INSERT INTO dbo.CLE_TOPE_CAUSAL_CAMARA (CODIGO_CAUSAL, CODIGO_DE_CAMARA, MONTO, TZ_LOCK)
VALUES (95, 1, 9999999999999, 0)
--
INSERT INTO dbo.CLE_TOPE_CAUSAL_CAMARA (CODIGO_CAUSAL, CODIGO_DE_CAMARA, MONTO, TZ_LOCK)
VALUES (96, 1, 9999999999999, 0)
----------------------------
--cód. postal por sucursal--
----------------------------
INSERT INTO CLE_SUCURSAL_CPA
SELECT 0, ID, 1, CPA_VIEJO FROM CLI_DIRECCIONES 
INNER JOIN SUCURSALES ON
	SUCURSALES.SUCURSAL = CLI_DIRECCIONES.ID
WHERE CLI_DIRECCIONES.FORMATO = ''S'' AND CLI_DIRECCIONES.TZ_LOCK = 0
----
')