EXECUTE('DROP TABLE IF EXISTS dbo.ITF_CHE_RECIBIDOS_RECHAZADOS_HISTORIAL;')
EXECUTE('
CREATE TABLE dbo.ITF_CHE_RECIBIDOS_RECHAZADOS_HISTORIAL
	(
	ORDINAL NUMERIC (15) NOT NULL,
	FECHA   DATETIME NOT NULL,
	CONSTRAINT PK_ITF_CHE_RECIBIDOS_HISTORIAL_01 PRIMARY KEY (ORDINAL, FECHA)
	);')