EXECUTE('
ALTER PROCEDURE dbo.SP_ALTA_DPF_POS 
(
@PRODUCTO NUMERIC(5),
@NRO_DEPOSITO NUMERIC(12),
@CLIENTE NUMERIC(12),
@CAPITAL NUMERIC(15,2),
@INTERES NUMERIC(15,2),
@MONTO NUMERIC(15,2),
@PLAZO NUMERIC(10),
@MONEDA NUMERIC(5),
@ALTA DATETIME,
@VENCIMIENTO DATETIME,
@TASA_INTERES NUMERIC(11,7),
@COTIZACION_UVA NUMERIC(15,2),
@UVAS NUMERIC(15,2),
@TASA_PRECANCELACION NUMERIC(5,2),
@RESULTADO VARCHAR(400) OUT
)
AS
DECLARE @RESULTADO125 VARCHAR(400)
DECLARE @LINEA1 VARCHAR(36)
DECLARE @LINEA2 VARCHAR(36)
DECLARE @LINEA3 VARCHAR(36)
DECLARE @LINEA4 VARCHAR(36)
DECLARE @LINEA5 VARCHAR(36)
DECLARE @LINEA6 VARCHAR(36)
DECLARE @LINEA7 VARCHAR(36)
DECLARE @LINEA8 VARCHAR(36)
DECLARE @LINEA9 VARCHAR(36)
DECLARE @LINEA10 VARCHAR(36)
DECLARE @MONEDA_UVA NUMERIC(5)
DECLARE @SIMBOLO_M VARCHAR(4)
DECLARE @TNA VARCHAR(36)
DECLARE @TEM VARCHAR(36)
DECLARE @CABECERA125 VARCHAR(50)


SET @MONEDA_UVA = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH(NOLOCK) WHERE CODIGO = 18)

SELECT @SIMBOLO_M=C6401 FROM MONEDAS WITH(NOLOCK) WHERE C6399 = @MONEDA

SELECT @LINEA1 = C6251 + REPLICATE('' '',36-LEN(C6251)) FROM PRODUCTOS WITH(NOLOCK) WHERE C6250 = @PRODUCTO

SET @LINEA2 = REPLICATE(''0'',11-LEN(@NRO_DEPOSITO)) + CONVERT(VARCHAR,@NRO_DEPOSITO);
SET @LINEA2 = ''DEPOSITO NRO.''+REPLICATE('' '',36-(LEN(@LINEA2)+DATALENGTH(''DEPOSITO NRO.'')))+@LINEA2;

SELECT @LINEA3 = SUBSTRING(NOMBRECLIENTE,1,36) FROM CLI_CLIENTES WITH(NOLOCK) WHERE CODIGOCLIENTE = @CLIENTE

IF(DATALENGTH(@LINEA3)<36)
SET @LINEA3 = @LINEA3 + REPLICATE('' '',36-DATALENGTH(@LINEA3))

SET @LINEA4 = (CASE WHEN @MONEDA = @MONEDA_UVA THEN FORMAT(@CAPITAL, ''C'', ''es-ar'') 
ELSE REPLACE(FORMAT(@CAPITAL, ''C'', ''es-ar''),''$'',@SIMBOLO_M) END)

SET @LINEA4 = ''CAPITAL'' +REPLICATE('' '',36-(LEN(''CAPITAL'')+DATALENGTH(@LINEA4)))+ @LINEA4

IF(@MONEDA_UVA=@MONEDA)
BEGIN
SET @LINEA5 = FORMAT(@COTIZACION_UVA, ''C'', ''es-ar'')
SET @LINEA5 = ''COTIZACION UVA'' + REPLICATE('' '',36-(DATALENGTH(''COTIZACION UVA'')+DATALENGTH(@LINEA5))) + @LINEA5

SET @LINEA6 = REPLACE(FORMAT(@UVAS, ''C'', ''es-ar''),''$'',@SIMBOLO_M)
SET @LINEA6 = ''UVAS ADQUIRIDAS'' + REPLICATE('' '',36-(DATALENGTH(''UVAS ADQUIRIDAS'')+DATALENGTH(@LINEA6))) + @LINEA6
END
ELSE
BEGIN
SET @LINEA5 = REPLACE(FORMAT(@INTERES, ''C'', ''es-ar''),''$'',@SIMBOLO_M)
SET @LINEA5 = ''INTERES'' + REPLICATE('' '',36-(LEN(''INTERES'')+DATALENGTH(@LINEA5))) + @LINEA5

SET @LINEA6 = REPLACE(FORMAT(@MONTO, ''C'', ''es-ar''),''$'',@SIMBOLO_M)
SET @LINEA6 = ''MONTO'' + REPLICATE('' '',36-(LEN(''MONTO'')+DATALENGTH(@LINEA6))) + @LINEA6
END

SET @LINEA7 = ''PLAZO ''+CONVERT(VARCHAR,@PLAZO)
SET @LINEA7 = @LINEA7 + REPLICATE('' '', 36-(DATALENGTH(@LINEA7)+DATALENGTH(''ALTA '')+DATALENGTH(@ALTA))) + ''ALTA '' + CONVERT(VARCHAR,@ALTA,103)

IF(@PRODUCTO=(SELECT NUMERICO FROM PARAMETROSGENERALES WITH(NOLOCK) WHERE CODIGO = 716))
BEGIN
SET @LINEA8 = RTRIM(LTRIM(REPLACE(FORMAT(@INTERES, ''C'', ''es-ar''),''$'','' '')))
SET @LINEA8 = ''INTERES PRECANC'' + REPLICATE('' '',36-(DATALENGTH(''INTERES PRECANC'')+DATALENGTH(@LINEA8))) + @LINEA8
END
ELSE
BEGIN
SET @LINEA8 = ''VENCIMIENTO''+ REPLICATE('' '',36-(LEN(''VENCIMIENTO'')+LEN(CONVERT(VARCHAR,@VENCIMIENTO,103)))) +CONVERT(VARCHAR,@VENCIMIENTO,103)
END

SELECT @TNA = CASE 
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
		THEN (PR.C6255/ (AVG(DATEDIFF(DD,@ALTA,@VENCIMIENTO)))) *
		(POWER((1+(@TASA_INTERES/100)), (1/(PR.C6255/ (	SELECT AVG(DATEDIFF(DD,@ALTA,@VENCIMIENTO)))))) - 1) * 100			
		--CONVERSION SEGUN CONVENCION BCRA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN @TASA_INTERES * 365 / 30.41666
		--TASA YA EXPRESADA COMO NOMINAL
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN @TASA_INTERES
		END
		FROM PRODUCTOS PR WITH(NOLOCK) WHERE PR.C6250 = @PRODUCTO
		GROUP BY PR.C6253, PR.C6255, PR.C6250
		
SELECT @TEM=CASE
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
			THEN @TASA_INTERES
		-- TASA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN POWER((1 + @TASA_INTERES), 12) - 1			
		--CONVENCION DEL BCRA
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN (@TASA_INTERES * 30.41666 / 365)
		END
		FROM PRODUCTOS PR WITH(NOLOCK) WHERE C6250 = @PRODUCTO
		
SET @LINEA9 = ''TNA ''+ @TNA;
SET @LINEA9 = @LINEA9 +REPLICATE('' '',36-(DATALENGTH(@LINEA9)+DATALENGTH(''TEM '' + @TEM)))+ ''TEM '' + @TEM

IF(@PRODUCTO<>(SELECT NUMERICO FROM PARAMETROSGENERALES WITH(NOLOCK) WHERE CODIGO = 716))
BEGIN
SET @LINEA10 = ''RETENCION''
SET @LINEA10 = @LINEA10 + REPLICATE('' '',36-(LEN(''RETENCION'')+DATALENGTH(FORMAT(0, ''C'', ''es-ar'')))) + FORMAT(0, ''C'', ''es-ar'')
END
ELSE
BEGIN
SET @LINEA10 = ''TASA FIJA DE PRECANCELACION:''
SET @LINEA10 = @LINEA10 +REPLICATE('' '',36-(DATALENGTH(@LINEA10)+LEN(CONVERT(VARCHAR,@TASA_PRECANCELACION) + ''%'')))+ CONVERT(VARCHAR,@TASA_PRECANCELACION) + ''%''
END

SET @CABECERA125 = ''1P''+ SUBSTRING(CONVERT(VARCHAR,(SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK)),112),3,6) + ''1036'';

SET @RESULTADO = @CABECERA125+@LINEA1+@LINEA2+@LINEA3+@LINEA4+@LINEA5+@LINEA6+@LINEA7+@LINEA8+@LINEA9+@LINEA10
')

