EXECUTE('
ALTER TABLE CRE_PAGO_DOMICILIO ADD NROSOLICITUD NUMERIC(10)
')

EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70116, '' '', 0, ''Nro solicitud'', ''Nro solicitud'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 7010, ''NROSOLICITUD'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70117, '' '', 0, ''Numerador sol pago dom'', ''Numerador sol pago dom'', 10, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 0, ''SOL_PAG_DOM'', 0, NULL)

INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (70117, 1, 1, '' '', NULL, 1, 0, 9999999999, ''Numerador Solic. pago domicilio'', ''T'')

DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 7010 AND NUMERODEINDICE = 2

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (7010, 2, ''Nro solicitud'', 0, 70116, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

')