EXECUTE('
---------------------------
--CORRECCIÓN DE NUMERADOR--
---------------------------
UPDATE NUMERATORDEFINITION
SET PERIODO = ''''
	, DESCRIPCION = ''Numerador de Cajas de Seguridad''
WHERE NUMERO = 8026
----
DELETE FROM NUMERATORASIGNED
WHERE OID IN (
	SELECT OID FROM NUMERATORVALUES WHERE NUMERO = 8026
)
----
DELETE FROM NUMERATORVALUES
WHERE NUMERO = 8026
--
INSERT INTO NUMERATORVALUES (DIA, MES, ANIO, SUCURSAL, NUMERO, VALOR)
VALUES (0, 0, 0, 0, 8026, (SELECT ISNULL(MAX(CODIGO), 0) + 1 FROM COF_COFRES))
----
')
