EXECUTE('
IF OBJECT_ID (''dbo.VW_CONV_PAGOS'') IS NOT NULL
	DROP VIEW dbo.VW_CONV_PAGOS
')
EXECUTE('
CREATE   VIEW [dbo].[VW_CONV_PAGOS]
AS
SELECT	cp.ID_ConvPago AS ID_CONVENIO ,
		cp.NomConvPago AS DESCRIPCION ,
		cv.Id_TpoConv AS ID_TIPO,
		cv.DscTpoConv AS TIPO_CONVENIO
FROM CONV_CONVENIOS_PAG cp WITH(NOLOCK)
INNER JOIN CONV_TIPOS cv WITH(NOLOCK) ON cp.Id_TpoConv=cv.Id_TpoConv
									AND cp.Id_TpoConv=3
')