EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (95150, '' '', 0, ''Ayuda Graduacion'', ''Graduación'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 99958, 0, 0, ''Ayuda Graduacion'', 0, NULL)

')

EXECUTE('
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4373, 99958, ''Ayuda Tipo Exclusiones '', '''', 0, ''44078R;44079;44077I;'', NULL, NULL, NULL, 0)

') 