--METADATA
-- MODIFICACICON CAMPO 1151

EXECUTE('        
IF EXISTS (SELECT A.NUMERODECAMPO  FROM DICCIONARIO A WHERE NUMERODECAMPO = 1151)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 1151;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (1151, '' '', 0, ''ID_CARGO'', ''ID_CARGO'', 4, ''N'', 0, '' '', 0, 0, 0, 0, 0, 0, 0, 195, ''Id_Cargo'', 0, NULL);
   

END
ELSE
BEGIN
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (1151, '' '', 0, ''ID_CARGO'', ''ID_CARGO'', 4, ''N'', 0, '' '', 0, 0, 0, 0, 0, 0, 0, 195, ''Id_Cargo'', 0, NULL);

END
')
