EXECUTE('
DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 44748 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''5''

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 44748 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''13''

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44748, ''E'', ''Pago Depósitos Judiciales'', ''13'', ''13'')
')