EXECUTE('
IF OBJECT_ID (''dbo.SIBE_SECTORES'') IS NOT NULL
	DROP TABLE dbo.SIBE_SECTORES

CREATE TABLE dbo.SIBE_SECTORES
	(
	TIPO        VARCHAR (10) DEFAULT ('' '') NOT NULL,
	ID          NUMERIC (5) DEFAULT ((0)) NOT NULL,
	DESCRIPCION VARCHAR (100) DEFAULT ('' ''),
	TZ_LOCK     NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SIBE_SECTORES_01 PRIMARY KEY (TIPO, ID)
	)
')

EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (930, 857, NULL, ''SIBE SECTORES'', 0, ''SIBE_SECTORES'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41340, '' '', 0, ''TIPO'', ''Tipo'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 857, ''TIPO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41341, '' '', 0, ''ID'', ''ID'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 857, ''ID'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41342, '' '', 0, ''DESCRIPCION'', ''Descripcion'', 100, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 857, ''DESCRIPCION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41343, '' '', 0, ''Tipo - ID'', ''Tipo - ID'', 100, ''A'', 0, NULL, 0, 0, 0, 0, 0, 593, 0, 0, ''TipoID'', 0, NULL)

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (857, 1, ''Indice Principal'', 0, 41340, 41341, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (6800, 8899, ''ABMC SIBE Sectores'', ''ABMC SIBE Sectores'', ''8899'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (857, 593, ''Ayudas Tipo - ID'', '''', 0, ''41340R;41341R;41342;'', NULL, NULL, NULL, 0)
')