
EXECUTE('

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3499, NULL, ''Recepción de dpf devueltos'', 0, ''CLE_RECEPCION_DPF_DEV'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')



INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35320, NULL, 0, ''Banco girado'', ''Banco girado'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''BANCO_GIRADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35321, NULL, 0, ''Sucursal del Banco girado'', ''Sucursal Banco'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''SUCURSAL_BANCO_GIRADO'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35322, NULL, 0, ''Importe dpf'', ''Importe dpf'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 3499, ''IMPORTE_DPF'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35323, NULL, 0, ''Código rechazo'', ''Código rechazo'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''CODIGO_RECHAZO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35324, NULL, 0, ''Número dpf'', ''Número dpf'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''NUMERO_DPF'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35325, NULL, 0, ''Estado de devolución'', ''Estado dev.'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''ESTADO_DEVOLUCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35326, NULL, 0, ''Código de cámara'', ''Código cámara'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''CODIGO_CAMARA'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35327, NULL, 0, ''TIPO DOCUMENTO'', ''tipo documento'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3499, ''TIPO_DOCUMENTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35328, '' '', 0, ''Fecha de alta'', ''Fecha de alta'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3499, ''FECHA_ALTA'', 0, NULL)



INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3499, 1, ''Índice recepción dpf dev'', 0, 35324, 35320, 35328, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

')
