EXECUTE('
IF OBJECT_ID (''CHE_BCO_RECHAZADOS'') IS NOT NULL
	DROP TABLE CHE_BCO_RECHAZADOS
')

EXECUTE('
CREATE TABLE CHE_BCO_RECHAZADOS
	(
	TZ_LOCK                NUMERIC (15) DEFAULT ((0)) NOT NULL,
	SUCURSAL               NUMERIC (5) DEFAULT ((0)) NOT NULL,
	SERIE_CHEQUE           VARCHAR (3) DEFAULT ('' '') NOT NULL,
	NRO_CHEQUE             NUMERIC (12) DEFAULT ((0)) NOT NULL,
	MONEDA                 NUMERIC (4) DEFAULT ((0)) NOT NULL,
	CLIENTE                NUMERIC (12) DEFAULT ((0)),
	PRODUCTO               NUMERIC (5) DEFAULT ((0)) NOT NULL,
	IMPORTE_CHEQUE         NUMERIC (15, 2) DEFAULT ((0)),
	FECHA_CHEQUE           DATETIME,
	FECHA_RECHAZO          DATETIME,
	CUENTA                 NUMERIC (12) DEFAULT ((0)) NOT NULL,
	COD_RECHAZO            VARCHAR (1) DEFAULT ('' ''),
	JTS_SALDOS             NUMERIC (12) DEFAULT ((0)),
	MOTIVO_RECHAZO         VARCHAR (60) DEFAULT ('' ''),
	FECHA_NOTIFICACION     DATETIME,
	FECHA_MAXIMA_REINTEGRO DATETIME,
	FECHA_REINTEGRO        DATETIME,
	FECHA_NOTIF_JUDICIAL   DATETIME,
	ESTADO                 NUMERIC (2) DEFAULT ((0)),
	FECHA_VENCIMIENTO      DATETIME,
	FORMA_PRESENTO         VARCHAR (1),
	SUCURSAL_DEVOLUCION    NUMERIC (5),
	FECHA_ESTADO           DATETIME,
	FECHA_EMISION          DATETIME,
	CODIGO_DE_CAUSAL       NUMERIC (2) DEFAULT ((0)),
	CLASEREINCIDENCIA      VARCHAR (1) DEFAULT ('' ''),
	NRO_AVISO              NUMERIC (12),
	CONSTRAINT CHE_BCO_RECHAZADOS115710 PRIMARY KEY (SUCURSAL,SERIE_CHEQUE,NRO_CHEQUE,MONEDA,PRODUCTO,CUENTA)
	)
')