
IF NOT EXISTS (
  SELECT * 
  FROM   sys.columns 
  WHERE  object_id = OBJECT_ID(N'[dbo].[CLE_DEPOSITOS_ECHEQ_TERCEROS]') 
         AND name = 'CODIGO_CHQ_ITF'
)
ALTER TABLE CLE_DEPOSITOS_ECHEQ_TERCEROS ADD CODIGO_CHQ_ITF VARCHAR (19) DEFAULT (' ') NULL



IF NOT EXISTS (
  SELECT * 
  FROM   sys.columns 
  WHERE  object_id = OBJECT_ID(N'[dbo].[CLE_DEPOSITOS_ECHEQ]') 
         AND name = 'CODIGO_CHQ_ITF'
)
ALTER TABLE CLE_DEPOSITOS_ECHEQ ADD CODIGO_CHQ_ITF VARCHAR (19) DEFAULT (' ') NULL
