EXECUTE('
ALTER PROCEDURE [dbo].[SP_DPF_VIGENTES_POS]
(
  @PCliente NUMERIC(12),
  @PPlazo	NUMERIC(10),
  @PImporte NUMERIC(15,2),
  @PProducto NUMERIC(5),
  @PMoneda	NUMERIC(5),
  @PPagina  VARCHAR(20),
  @POperacion NUMERIC(10),
  @PFechaVenc VARCHAR(6),
  @PImportePlazo NUMERIC(15,2),
  @Resultado126   VARCHAR(400) OUTPUT,
  @Resultado125	  VARCHAR(400) OUTPUT
)
AS

DECLARE @TARIFA NUMERIC(5)
DECLARE @CANAL NUMERIC(5)
DECLARE @CANT_CERTIFICADOS INT
DECLARE @CERTIFICADO_X_PAG INT
DECLARE @resto INT = 0
DECLARE @primerRegistroPag INT = 0
DECLARE @ultimoRegistroPag INT =0
DECLARE @cantidadElementoPagina INT = 0
DECLARE @paginaAnterior INT = 0
DECLARE @paginaSiguiente INT = 0
DECLARE @TotalPaginas NUMERIC(5)
DECLARE @DESC_PRODUCTO VARCHAR(50)
DECLARE @CABECERA125 VARCHAR(50)
DECLARE @CABECERA126 VARCHAR(50)
DECLARE @AUX_LINEAS TABLE (DATOS VARCHAR(200))
DECLARE @PAGINA VARCHAR(36)
DECLARE @LINEAS VARCHAR(140)

---Para campo 125

DECLARE @LINEA1 VARCHAR(36)
DECLARE @LINEA2 VARCHAR(36)
DECLARE @LINEA3 VARCHAR(36)
DECLARE @NOMBRECLIENTE VARCHAR(36)
DECLARE @CAPITAL VARCHAR(36)
DECLARE @INTERES VARCHAR(36)
DECLARE @MONTO VARCHAR(36)
DECLARE @PLAZO VARCHAR(36)
DECLARE @ALTA VARCHAR(36)
DECLARE @VENCIMIENTO VARCHAR(36)
DECLARE @TNA VARCHAR(36)
DECLARE @TEM VARCHAR(36)
DECLARE @RETENCION NUMERIC(15,2)
DECLARE @SIMBOLOMONEDA VARCHAR(5)
DECLARE @RETENCION_LIN VARCHAR(36)
DECLARE @OPERACION NUMERIC(12)


SET @CABECERA125 = ''1P''+ SUBSTRING(CONVERT(VARCHAR,(SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK)),112),3,6) + ''1036'';

IF((@POperacion IS NULL OR LEN(@POperacion)=0 OR @POperacion=0) OR (@PFechaVenc IS NULL OR LEN(@PFechaVenc)=0) OR (@PImportePlazo IS NULL OR LEN(@PImportePlazo)=0 OR @PImportePlazo=0))
BEGIN
IF((@PPagina IS NULL OR @PPagina=''0'' OR LEN(@PPagina)=0))
BEGIN
 SET @PPagina = 1;
END
ELSE
BEGIN
SET @PPagina = RTRIM(LTRIM(REPLACE(@PPagina, ''PAGINA'', '''')))
END
END
ELSE
BEGIN
SET @PPagina = NULL;
END


SET @CANAL = (SELECT NUMERICO FROM PARAMETROSGENERALES WITH(NOLOCK) WHERE CODIGO = 219);
	
IF(@PPagina IS NOT NULL AND @PPagina <> 0)
BEGIN

	SET @CERTIFICADO_X_PAG = 5;

	SELECT @CANT_CERTIFICADOS=COUNT(1) FROM SALDOS WITH(NOLOCK) WHERE C1800 = @CANAL 
	AND C1803 = @PCliente AND C1785 = 4 AND C1604 <> 0
	AND C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))

	SET @resto = @CANT_CERTIFICADOS - (((@PPagina -1) * @CERTIFICADO_X_PAG) + @CERTIFICADO_X_PAG)
	SET @primerRegistroPag = ((@PPagina -1) * @CERTIFICADO_X_PAG) +1
	SET @ultimoRegistroPag = (((@PPagina -1) * @CERTIFICADO_X_PAG) + @CERTIFICADO_X_PAG)
	SET @cantidadElementoPagina = ((@ultimoRegistroPag - @primerRegistroPag) +1)

	SET @TotalPaginas = (SELECT dbo.ITFcantPaginas (@CANT_CERTIFICADOS, @CERTIFICADO_X_PAG))
	
	SET @CABECERA126 = '''';
	
	SET @CABECERA126 = @CABECERA126 + REPLICATE(''0'',2-LEN(@CANT_CERTIFICADOS)) + CONVERT(VARCHAR,@CANT_CERTIFICADOS);
	
	IF(@TotalPaginas=1)
	BEGIN
		SET @CABECERA126 = @CABECERA126 + ''S'';
	END
	
	IF(@TotalPaginas=@PPagina AND @TotalPaginas > 1)
	BEGIN
		SET @CABECERA126 = @CABECERA126 + ''C''
		SET @PAGINA = ''PAGINA 1'';
		SET @PAGINA = @PAGINA + REPLICATE('' '',36-DATALENGTH(@PAGINA));
	END
	
	IF(@TotalPaginas>@PPagina)
	BEGIN
		SET @CABECERA126 = @CABECERA126 + ''A''
		SET @PAGINA = ''PAGINA ''+CONVERT(VARCHAR,CONVERT(INT,@PPagina)+1);
		SET @PAGINA = @PAGINA + REPLICATE('' '',36-DATALENGTH(@PAGINA));
	END

	SET @Resultado126 = @CABECERA126 + ''VENC.   OPERAC       IMPORTE'';
			
	IF(@CANT_CERTIFICADOS>@CERTIFICADO_X_PAG AND @CANT_CERTIFICADOS > 1)
	BEGIN
		INSERT INTO @AUX_LINEAS
		SELECT  
		STRING_AGG(SUBSTRING(CONVERT(VARCHAR,C1627,3),4,5) + '' '' + REPLICATE(''0'',8-LEN(OPERACION)) +
		CONVERT(VARCHAR,OPERACION) +  REPLICATE('' '',14-LEN(REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''))) +
		REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''),'''')
		FROM SALDOS WITH(NOLOCK) WHERE C1800 = @CANAL AND C1803 = @PCliente AND C1785 = 4 
		AND C1604 <> 0 AND C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		GROUP BY C1627, OPERACION, C1604
		ORDER BY C1627, OPERACION, C1604
		OFFSET ((@PPagina - 1) * @CERTIFICADO_X_PAG) ROWS
		FETCH NEXT @CERTIFICADO_X_PAG ROWS ONLY;

		SELECT @LINEAS= STRING_AGG(DATOS,'''') FROM @AUX_LINEAS
		
		SET @Resultado126 = @Resultado126 + @LINEAS + @PAGINA + REPLICATE('' '',140-DATALENGTH(@LINEAS)); 
	END

	IF(@CANT_CERTIFICADOS<=@CERTIFICADO_X_PAG AND @CANT_CERTIFICADOS > 1) 
	BEGIN
		INSERT INTO @AUX_LINEAS
		SELECT 
		STRING_AGG(SUBSTRING(CONVERT(VARCHAR,C1627,3),4,5) + '' '' + REPLICATE(''0'',8-LEN(OPERACION)) +
		CONVERT(VARCHAR,OPERACION) +  REPLICATE('' '',14-LEN(REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''))) +
		REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''),'''')
		FROM SALDOS WITH(NOLOCK) 
		WHERE C1800 = @CANAL AND C1803 = @PCliente AND C1785 = 4 
		AND C1604 <> 0 AND C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
	    GROUP BY C1627, OPERACION, C1604
		ORDER BY C1627, OPERACION, C1604
		
		
		SELECT @LINEAS= STRING_AGG(DATOS,'''') FROM @AUX_LINEAS
		SET @Resultado126 = @Resultado126 + @LINEAS + REPLICATE('' '',140-LEN(@LINEAS))
	END

	IF(@CANT_CERTIFICADOS=1) 
	BEGIN
		SELECT @Resultado126 = @Resultado126 + 
		STRING_AGG(SUBSTRING(CONVERT(VARCHAR,C1627,3),4,5) + '' '' + REPLICATE(''0'',8-LEN(OPERACION)) +
		CONVERT(VARCHAR,OPERACION) +  REPLICATE('' '',14-LEN(REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''))) +
		REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',''''),'''')
		FROM SALDOS WITH(NOLOCK) WHERE C1800 = @CANAL AND C1803 = @PCliente AND C1785 = 4 
		AND C1604 <> 0 AND C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		SET @Resultado126 = @Resultado126 + REPLICATE('' '',56)
		
		SELECT @NOMBRECLIENTE = SUBSTRING(C.NOMBRECLIENTE,1,36), @CAPITAL=REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',M.C6401), 
		@SIMBOLOMONEDA = M.C6401, @INTERES = REPLACE(FORMAT(C1608, ''C'', ''es-ar''),''$'',M.C6401),
		@MONTO = REPLACE(FORMAT(C1600, ''C'', ''es-ar''),''$'',M.C6401), @PLAZO = C1689, @ALTA = CONVERT(VARCHAR,C1621,3),
		@VENCIMIENTO = CONVERT(VARCHAR,C1627,3),
		@TNA = CASE 
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
		THEN (PR.C6255/ (	SELECT AVG(DATEDIFF(DD,C2301,C2302)) 
		FROM PLANPAGOS WHERE SALDO_JTS_OID = S.JTS_OID AND TZ_LOCK = 0 )) *
		(POWER((1+(S.C1632/100)), (1/(PR.C6255/ (	SELECT AVG(DATEDIFF(DD,C2301,C2302)) 
		FROM PLANPAGOS 
		WHERE SALDO_JTS_OID = S.JTS_OID AND TZ_LOCK = 0)))) - 1) * 100			
		--CONVERSIÓN SEGÚN CONVENCIÓN BCRA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN S.C1632 * 365 / 30.41666
		--TASA YA EXPRESADA COMO NOMINAL
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN S.C1632
		END,
		@TEM=CASE
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
			THEN CONVERT(NUMERIC(11,7),S.C1632/12)
		-- TASA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN S.C1632		
		--CONVENCIÓN DEL BCRA
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN CONVERT(NUMERIC(11,7),(S.C1632 * 30.41666 / 365)/12)
		END,
		@OPERACION = S.OPERACION,
		@PProducto = S.PRODUCTO
		FROM SALDOS S WITH(NOLOCK) 
		INNER JOIN CLI_CLIENTES C WITH(NOLOCK) ON S.C1803 = C.CODIGOCLIENTE 
		INNER JOIN MONEDAS M WITH(NOLOCK) ON S.MONEDA = M.C6399
		INNER JOIN PRODUCTOS PR WITH(NOLOCK) ON PR.C6250 = S.PRODUCTO
		WHERE S.C1800 = @CANAL AND S.C1803 = @PCliente AND S.C1785 = 4 
		AND S.C1604 <> 0 AND S.C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		
		SELECT @RETENCION=ISNULL(SUM(L.MONTO_FACTURABLE),0)
		FROM SALDOS S WITH(NOLOCK)
		INNER JOIN BS_HISTORIA_PLAZO B WITH(NOLOCK) ON S.JTS_OID = B.SALDOS_JTS_OID AND B.TIPOMOV = ''P''
		INNER JOIN CI_FACTURA_LINEA L WITH(NOLOCK) ON B.SUCURSALMOV = L.SUCURSAL_ASIENTO
		AND B.FECHAPROCESOMOV = L.FECHA_PROCESO_ASIENTO AND B.NROASIENTOMOV = L.ASIENTO
		INNER JOIN CI_CARGOS C WITH(NOLOCK) ON C.TIPO_CARGO_IMPOSITIVO = 4 AND 
		L.ID_CARGO = C.ID_CARGO
		WHERE S.C1800 = @CANAL AND S.C1803 = @PCliente AND S.C1785 = 4
		AND S.C1604 <> 0 AND S.C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		
		SELECT @DESC_PRODUCTO=C6251 FROM PRODUCTOS WITH(NOLOCK) WHERE C6250 = @PProducto
		SET @LINEA1 = @DESC_PRODUCTO + REPLICATE('' '',36-LEN(@DESC_PRODUCTO));
		SET @LINEA2 = ''DEPOSITO NRO.''
		SET @LINEA2 = @LINEA2 + REPLICATE('' '', 36-(LEN(@LINEA2)+LEN(@OPERACION))) + CONVERT(VARCHAR,@OPERACION)
		SET @CAPITAL = ''CAPITAL''+REPLICATE('' '',36-(LEN(''CAPITAL'')+LEN(@CAPITAL)))+@CAPITAL
		SET @INTERES = ''INTERES''+REPLICATE('' '',36-(LEN(''INTERES'')+LEN(@INTERES)))+@INTERES
		SET @MONTO = ''MONTO''+REPLICATE('' '',36-(LEN(''MONTO'')+LEN(@MONTO)))+@MONTO
		SET @PLAZO = ''PLAZO ''+@PLAZO;
		SET @ALTA = ''ALTA ''+@ALTA;
		SET @VENCIMIENTO = ''VENCIMIENTO''+REPLICATE('' '',36-(LEN(''VENCIMIENTO'')+LEN(@VENCIMIENTO)))+@VENCIMIENTO;
		SET @TNA = ''TNA ''+@TNA;
		SET @TEM = ''TEM ''+@TEM;
		SET @RETENCION_LIN = ''RETENCION''+REPLICATE('' '',36-(LEN(''RETENCION'')+LEN(REPLACE(FORMAT(@RETENCION,''C'',''es-ar''),''$'',@SIMBOLOMONEDA))))+REPLACE(FORMAT(@RETENCION,''C'',''es-ar''),''$'',@SIMBOLOMONEDA);
		
		SET @Resultado125 = @CABECERA125 + @LINEA1 + @LINEA2 + @CAPITAL + @INTERES + @MONTO + @PLAZO 
		+ REPLICATE('' '',36-(LEN(@PLAZO)+LEN(@ALTA))) + @ALTA + @VENCIMIENTO + @TNA
		+ REPLICATE('' '',36-(LEN(@TNA)+LEN(@TEM))) + @TEM + @RETENCION_LIN;
	END
END 
ELSE
BEGIN
	IF((@PImportePlazo IS NOT NULL AND LEN(@PImportePlazo)>0 AND @PImportePlazo > 0) AND (@PFechaVenc IS NOT NULL AND LEN(@PFechaVenc)>0) AND (@POperacion IS NOT NULL AND LEN(@POperacion)>0) AND @POperacion > 0)
	BEGIN
		
		SELECT @NOMBRECLIENTE = SUBSTRING(C.NOMBRECLIENTE,1,36), @CAPITAL=REPLACE(FORMAT(C1604, ''C'', ''es-ar''),''$'',M.C6401), 
		@SIMBOLOMONEDA = M.C6401, @INTERES = REPLACE(FORMAT(C1608, ''C'', ''es-ar''),''$'',M.C6401),
		@MONTO = REPLACE(FORMAT(C1600, ''C'', ''es-ar''),''$'',M.C6401), @PLAZO = C1689, @ALTA = CONVERT(VARCHAR,C1621,3),
		@VENCIMIENTO = CONVERT(VARCHAR,C1627,3),
		@TNA = CASE 
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
		THEN (PR.C6255/ (	SELECT AVG(DATEDIFF(DD,C2301,C2302)) 
		FROM PLANPAGOS WHERE SALDO_JTS_OID = S.JTS_OID AND TZ_LOCK = 0 )) *
		(POWER((1+(S.C1632/100)), (1/(PR.C6255/ (	SELECT AVG(DATEDIFF(DD,C2301,C2302)) 
		FROM PLANPAGOS 
		WHERE SALDO_JTS_OID = S.JTS_OID AND TZ_LOCK = 0)))) - 1) * 100			
		--CONVERSIÓN SEGÚN CONVENCIÓN BCRA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN S.C1632 * 365 / 30.41666
		--TASA YA EXPRESADA COMO NOMINAL
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN S.C1632
		END,
		@TEM=CASE
		WHEN PR.C6253 = ''E'' --TASA EFECTIVA
			THEN CONVERT(NUMERIC(11,7),S.C1632/12)
		-- TASA
		WHEN PR.C6253 = ''M'' --TASA EFECTIVA MENSUAL
			THEN S.C1632			
		--CONVENCIÓN DEL BCRA
		WHEN PR.C6253 = ''N'' --TASA NOMINAL
			THEN CONVERT(NUMERIC(11,7),(S.C1632 * 30.41666 / 365)/12)
		END,
		@PProducto = S.PRODUCTO
		FROM SALDOS S WITH(NOLOCK) 
		INNER JOIN CLI_CLIENTES C WITH(NOLOCK) ON S.C1803 = C.CODIGOCLIENTE 
		INNER JOIN MONEDAS M WITH(NOLOCK) ON S.MONEDA = M.C6399
		INNER JOIN PRODUCTOS PR WITH(NOLOCK) ON PR.C6250 = S.PRODUCTO
		WHERE S.C1800 = @CANAL AND S.C1803 = @PCliente AND S.C1785 = 4 
		AND S.C1604 <> 0 AND S.C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		AND S.OPERACION = @POperacion
		
		SELECT @RETENCION=ISNULL(SUM(L.MONTO_FACTURABLE),0)
		FROM SALDOS S WITH(NOLOCK)
		INNER JOIN BS_HISTORIA_PLAZO B WITH(NOLOCK) ON S.JTS_OID = B.SALDOS_JTS_OID AND B.TIPOMOV = ''P''
		INNER JOIN CI_FACTURA_LINEA L WITH(NOLOCK) ON B.SUCURSALMOV = L.SUCURSAL_ASIENTO
		AND B.FECHAPROCESOMOV = L.FECHA_PROCESO_ASIENTO AND B.NROASIENTOMOV = L.ASIENTO
		INNER JOIN CI_CARGOS C WITH(NOLOCK) ON C.TIPO_CARGO_IMPOSITIVO = 4 AND 
		L.ID_CARGO = C.ID_CARGO
		WHERE S.C1800 = @CANAL AND S.C1803 = @PCliente AND S.C1785 = 4 AND S.PRODUCTO = @PProducto
		AND S.C1604 <> 0 AND S.C1627 >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
		AND S.OPERACION = @POperacion
		
		SELECT @DESC_PRODUCTO=C6251 FROM PRODUCTOS WITH(NOLOCK) WHERE C6250 = @PProducto
		SET @LINEA1 = @DESC_PRODUCTO + REPLICATE('' '',36-LEN(@DESC_PRODUCTO));
		SET @LINEA2 = ''DEPOSITO NRO.''
		SET @LINEA2 = @LINEA2 + REPLICATE('' '', 36-(LEN(@LINEA2)+LEN(@POperacion))) + CONVERT(VARCHAR,@POperacion)
		SET @CAPITAL = ''CAPITAL''+REPLICATE('' '',36-(LEN(''CAPITAL'')+LEN(@CAPITAL)))+@CAPITAL
		SET @INTERES = ''INTERES''+REPLICATE('' '',36-(LEN(''INTERES'')+LEN(@INTERES)))+@INTERES
		SET @MONTO = ''MONTO''+REPLICATE('' '',36-(LEN(''MONTO'')+LEN(@MONTO)))+@MONTO
		SET @PLAZO = ''PLAZO ''+@PLAZO;
		SET @ALTA = ''ALTA ''+@ALTA;
		SET @VENCIMIENTO = ''VENCIMIENTO''+REPLICATE('' '',36-(LEN(''VENCIMIENTO'')+LEN(@VENCIMIENTO)))+@VENCIMIENTO;
		SET @TNA = ''TNA ''+@TNA;
		SET @TEM = ''TEM ''+@TEM;
		SET @RETENCION_LIN = ''RETENCION''+REPLICATE('' '',36-(LEN(''RETENCION'')+LEN(REPLACE(FORMAT(@RETENCION,''C'',''es-ar''),''$'',@SIMBOLOMONEDA))))+REPLACE(FORMAT(@RETENCION,''C'',''es-ar''),''$'',@SIMBOLOMONEDA);
		
		SET @Resultado125 = @CABECERA125 + @LINEA1 + @LINEA2 + @CAPITAL + @INTERES + @MONTO + @PLAZO 
		+ REPLICATE('' '',36-(LEN(@PLAZO)+LEN(@ALTA))) + @ALTA + @VENCIMIENTO + @TNA
		+ REPLICATE('' '',36-(LEN(@TNA)+LEN(@TEM))) + @TEM + @RETENCION_LIN;
		
		SET @Resultado126 = ''0001 '';
		
	END
END

')