EXECUTE('
IF OBJECT_ID (''dbo.SOS_PERFILDOC_CONT'') IS NOT NULL
	DROP TABLE dbo.SOS_PERFILDOC_CONT
')

EXECUTE('
CREATE TABLE dbo.SOS_PERFILDOC_CONT
	(
	EMPRESA               VARCHAR (4),
	PERIODO               VARCHAR (6),
	FECHADEINFORMACION    NUMERIC (8),
	IDENTTRIBUTARIATIPO   NUMERIC (4),
	IDENTTRIBUTARIANUMERO NUMERIC (11),
	MONTOPERFIL           NUMERIC (16,2),
	FECHAALTAPERFIL       NUMERIC (8),
	OBSERVACIONES         VARCHAR (50)
	)
')

EXECUTE('
IF OBJECT_ID (''dbo.SOS_VINCULACION_CONT'') IS NOT NULL
	DROP TABLE dbo.SOS_VINCULACION_CONT
')

EXECUTE('
CREATE TABLE dbo.SOS_VINCULACION_CONT
	(
	EMPRESA                NUMERIC (4) NOT NULL,
	PERIODO                VARCHAR (6),
	FECHADEINFORMACION     NUMERIC (8) NOT NULL,
	CLASEDECUENTA          VARCHAR (3),
	NUMERODECUENTA         VARCHAR (22),
	TIPODECUENTAUOPERACION VARCHAR (3),
	NUMERODEOPERACION      VARCHAR (22),
	SUCURSALSISCEN         VARCHAR (5),
	IDENTTRIBUTARIATIPO    NUMERIC (2),
	IDENTTRIBUTARIANUMERO  NUMERIC (16),
	CONDICION              NUMERIC (2),
	ORDENRELACION          NUMERIC (2),
	FECHAALTA              VARCHAR (8),
	CODCLIENTE             NUMERIC (12),
	NROPERSFISICAJURIDICA  NUMERIC (12)
	)
')
