EXECUTE('
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (1800, 1645, ''Reporte cheques pagos'', ''J'', 0, NULL, 0, 0, 0, ''N'')
')