Execute('
IF OBJECT_ID(''dbo.ITF_COELSA_IMAGENES_CHEQUES_PROPIOS_AUX'') IS NOT NULL
	DROP TABLE ITF_COELSA_IMAGENES_CHEQUES_PROPIOS_AUX 
CREATE TABLE [dbo].[ITF_COELSA_IMAGENES_CHEQUES_PROPIOS_AUX] (
	ID int IDENTITY(1,1) NOT NULL,
	ID_TICKET numeric(16,0) NULL,
	ID_PROCESO numeric(15,0) NULL,
	FECHA_PROCESO date NULL,
	ESTADO varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	ID_REGISTRO numeric(1,0) NULL,
	BANCO_DEPOSITARIO numeric(3,0) NULL,
	BANCO_GIRADO numeric(3,0) NULL,
	SUCURSAL_GIRADA numeric(3,0) NULL,
	CODIGO_POSTAL numeric(4,0) NULL,
	NRO_CHEQUE numeric(8,0) NULL,
	NRO_CUENTA numeric(11,0) NULL,
	FECHA_PRESENTACION date NULL,
	FECHA_COMPENSACION date NULL,
	ESTADO_TRAN varchar(1) COLLATE Modern_Spanish_CI_AS NULL,
	NOMBRE_IMAGEN varchar(33) COLLATE Modern_Spanish_CI_AS NULL,
	CONSTRAINT PK__ITF_COELSA_IMAGENES_CHEQUES_PROPIOS_AUX PRIMARY KEY (ID)
);')
