EXECUTE('
----
IF OBJECT_ID (''dbo.VW_OPCIONES_CANALRECAUDACION'') IS NOT NULL
	DROP VIEW dbo.VW_OPCIONES_CANALRECAUDACION
----
')
EXECUTE('
----
CREATE   VIEW [dbo].[VW_OPCIONES_CANALRECAUDACION]
						(OPCIONINTERNA,
						OPCIONDEPANTALLA,
						DESCRIPCION
						)
AS
SELECT O.OPCIONINTERNA AS ''Opción Interna'',
		O.OPCIONDEPANTALLA AS ''Opción de Pantalla'',
		O.DESCRIPCION AS ''Descripción''
FROM OPCIONES AS O with (nolock) 
WHERE O.NUMERODECAMPO = 45044
----
')
