EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45851, '' '', 0, ''VW_AYUDA_EXPECIONES_ANSES'', ''Ayuda Ppal'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 45311, 0, 0, ''Beneficio'', 0, NULL)

UPDATE dbo.DICCIONARIO
SET DESCRIPCION = ''Numérico de 1''
	, PROMPT = ''Numérico''
	, LARGO = 1
	, TIPODECAMPO = ''N''
	, DECIMALES = 0
	, EDICION = NULL
	, CONTABILIZA = 0
	, CONCEPTO = 0
	, CALCULO = 0
	, VALIDACION = 0
	, TABLADEVALIDACION = 0
	, TABLADEAYUDA = 0
	, OPCIONES = 0
	, TABLA = 0
	, CAMPO = ''NUMERICODE1''
WHERE NUMERODECAMPO = 1239
')