EXECUTE('DROP PROCEDURE IF EXISTS SP_LINK_TRK_CLIENTE_PERSONA;

ALTER TABLE TJD_SOLICITUD_LINK ADD AUTORIZADA NUMERIC(1);

')


EXECUTE('CREATE PROCEDURE SP_LINK_TRK_CLIENTE_PERSONA @NRO_TARJETA VARCHAR(19), @NRO_CLIENTE NUMERIC(12) OUTPUT, @NRO_PERSONA NUMERIC(12) OUTPUT
AS
BEGIN
	SET @NRO_CLIENTE = (SELECT TOP 1 a.* FROM (SELECT COD_CLIENTE FROM TJD_SOLICITUD_LINK WHERE AUTORIZADA = 1 AND TZ_LOCK = 0 AND TIPO_SOLICITUD = ''120005'' AND NRO_TARJETA_BASE = CAST(@NRO_TARJETA AS NUMERIC) UNION ALL SELECT 0 AS [CODIGOCLIENTE]) AS a);
    SET @NRO_PERSONA = (SELECT TOP 1 a.* FROM (SELECT NRO_PERSONA FROM TJD_SOLICITUD_LINK WHERE AUTORIZADA = 1 AND TZ_LOCK = 0 AND TIPO_SOLICITUD = ''120005'' AND NRO_TARJETA_BASE = CAST(@NRO_TARJETA AS NUMERIC) UNION ALL SELECT 0 AS NRO_PERSONA) AS a);
    PRINT(CAST(@NRO_CLIENTE AS VARCHAR));
    PRINT(CAST(@NRO_PERSONA AS VARCHAR));
END;')



