EXECUTE('
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (9000, 2055, ''Consultar Plan de Cuentas'', '' '', 0, NULL, 0, 0, 0, ''N'')
')