EXECUTE('
IF OBJECT_ID (''VW_CON_ASIENTOS_X_USUARIO'') IS NOT NULL
	DROP VIEW VW_CON_ASIENTOS_X_USUARIO
')

EXECUTE('
CREATE   VIEW VW_CON_ASIENTOS_X_USUARIO
AS
SELECT
	U.GRUPO_USUARIOS,
	U.ID_ASIENTO,
	A.DESCRIPCION AS DESCRIPCION_ASIENTO,
	OH.DESCRIPCION AS HABILITADO,
	A.TOTAL_LINEAS AS TOTAL_LINEAS
FROM
	CON_ASIENTOTIPO_X_USUARIO AS U WITH (nolock)
INNER JOIN CON_ASIENTOS_TIPO_CV AS A WITH (nolock) ON
	A.ID_ASIENTO = U.ID_ASIENTO
	AND ( (U.TZ_LOCK < 300000000000000 OR U.TZ_LOCK >= 400000000000000) 
		  AND (U.TZ_LOCK < 100000000000000 OR U.TZ_LOCK >= 200000000000000)
	)
INNER JOIN OPCIONES AS OH WITH (nolock) ON
	OH.OPCIONINTERNA = U.HABILITADO
	AND OH.NUMERODECAMPO = 49702
	AND OH.IDIOMA = ''E''
WHERE
	U.TZ_LOCK = 0
')