EXECUTE('
IF OBJECT_ID (''dbo.VW_EXCLUSIONES_ASISTENCIAS'') IS NOT NULL
	DROP VIEW dbo.VW_EXCLUSIONES_ASISTENCIAS
')

EXECUTE('
CREATE VIEW VW_EXCLUSIONES_ASISTENCIAS AS ( 
SELECT 
VA.SUCURSAL AS ''Sucursal'',
VA.NOMBRESUCURSAL AS ''Nombre Sucursal'',
VA.PRODUCTO AS ''Producto'',
VA.NOMBREPRODUCTO ''Nombre Producto'',
VA.CUENTA AS ''Cuenta'',
VA.OPERACION AS ''Operación'',
VA.ORDINAL AS ''Ordinal'',
VA.MONEDA AS ''Moneda'',
VA.MONTOORIGEN AS ''Monto'',
VA.CLIENTE AS ''Cliente'',
VA.JTS_OID AS ''JTS OID'',
TE.DETALLE AS ''Motivo Exclusión Graduación'',
TE.ID_EXCLUSION AS ''Identificador Exclusión'',
CD.NUMERODOC AS ''CUIT CUIL'',
CD.NOMBRECLIENTE AS ''Nombre Cliente''
FROM VW_ASISTENCIAS VA WITH(NOLOCK) 
INNER JOIN CRE_EXCLUSIONES_ASISTENCIAS EA WITH(NOLOCK) 
ON EA.ASISTENCIA_JTS_OID=VA.JTS_OID
INNER JOIN CRE_TIPO_EXCLUSION TE WITH(NOLOCK) ON EA.GRADUACION=TE.ID_EXCLUSION 
INNER JOIN VW_CLI_X_DOC CD WITH(NOLOCK) ON CD.CODIGOCLIENTE = VA.CLIENTE
WHERE EA.TZ_LOCK=0
)
')

EXECUTE('
UPDATE dbo.AYUDAS
SET CAMPOS = ''2576;2490;4355;770;2615;2616R;867;879;2611R;254;410;2504R;2614R;50299R;824R;''
	, CAMPOSVISTA = ''Sucursal;Nombre Sucursal;Producto;Nombre Producto;Cuenta;Operación;Moneda;Monto;Cliente;CUIT CUIL;Nombre Cliente;JTS OID;Ordinal;Identificador Exclusión;Motivo Exclusión Graduación;''
WHERE NUMERODEAYUDA = 49350
')