execute('
UPDATE DICCIONARIO
SET NUMERODECAMPO = 2395
	, USODELCAMPO = '' ''
	, REFERENCIA = 0
	, DESCRIPCION = ''Importe solicitado''
	, PROMPT = ''Importe''
	, LARGO = 14
	, TIPODECAMPO = ''N''
	, DECIMALES = 2
	, EDICION = ''I''
	, CONTABILIZA = 0
	, CONCEPTO = 0
	, CALCULO = 0
	, VALIDACION = 0
	, TABLADEVALIDACION = 0
	, TABLADEAYUDA = 0
	, OPCIONES = 0
	, TABLA = 136
	, CAMPO = ''IMPORTE''
	, BASICO = 0
	, MASCARA = NULL
WHERE NUMERODECAMPO = 2395
')