EXECUTE('

CREATE VIEW VW_PROD_RELSECTORES
(Producto, [Descripción de Producto], Sector, [Descripción de Sector])
AS
SELECT R.PRODUCTO, P.C6251, R.SECTOR, S.DESCRIPCION
FROM PROD_RELSECTORES AS R, PRODUCTOS AS P, CLI_SECTORES AS S
WHERE R.PRODUCTO = P.C6250 AND R.SECTOR = S.SECTOR
AND R.TZ_LOCK = 0 AND P.TZ_LOCK = 0 AND S.TZ_LOCK = 0

')
execute ('

CREATE VIEW VW_PROD_RELCLIENTES
(Apoderamiento, [Descripción de Apoderamiento], Producto, [Descripción de Producto], [Titular / Apoderado], [Tipo de Cliente])
AS
SELECT R.APODERAMIENTO, A.DESCRIPCION, R.PRODUCTO, P.C6251, R.TITULAR_APODERADO, R.TIPO_CLIENTE
FROM PYF_TIPOAPODERAMIENTO AS A, PRODUCTOS AS P, PROD_RELCLIENTE AS R
WHERE A.CODAPODERAMIENTO = R.APODERAMIENTO AND P.C6250 = R.PRODUCTO
AND A.TZ_LOCK = 0 AND P.TZ_LOCK = 0 AND R.TZ_LOCK = 0

')
execute ('
CREATE VIEW VW_PROD_RELSEGMENTOS
(Producto, [Descripción de Producto], Segmento, [Descripción de Segmento], Subsegmento, [Descripción de Subsegmento], Comentario)
AS
SELECT R.PRODUCTO, P.C6251, R.SEGMENTO, S.DESCRIPCION_SEGMENTO, R.SUBSEGMENTO, U.DESCRIPCION_SUBSEGMENTO, R.COMENTARIO
FROM CLI_SEGMENTOS AS S, CLI_SUBSEGMENTOS AS U, PRODUCTOS AS P, PROD_RELSEGMENTOS AS R
WHERE S.COD_SEGMENTO = R.SEGMENTO AND U.COD_SUBSEGMENTO = R.SUBSEGMENTO AND U.COD_SEGMENTO = R.SEGMENTO AND P.C6250 = R.PRODUCTO
AND S.TZ_LOCK = 0 AND U.TZ_LOCK = 0 AND P.TZ_LOCK = 0 AND R.TZ_LOCK = 0
')