EXECUTE('
DELETE FROM DESCRIPTORES WHERE IDENTIFICACION =993.

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (930, 993, NULL, ''VW_TJD_COBRO_COMISIONES'', 0, ''VW_TJD_COBRO_COMISIONES'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

DELETE FROM DICCIONARIO WHERE TABLA = 993

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41952, '' '', 0, ''ID_SOLICITUD'', ''ID_SOLICITUD'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 993, ''ID_SOLICITUD'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41953, '' '', 0, ''SALDO_JTS_OID'', ''SALDO_JTS_OID'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 993, ''SALDO_JTS_OID'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41954, '' '', 0, ''ID_REG'', ''ID_REG'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 993, ''ID_REG'', 0, NULL)


DELETE FROM INDICES WHERE NUMERODEARCHIVO = 993

INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (993, 1, ''Principal'', 0, 41954, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

')
