EXECUTE('

ALTER TABLE TJD_CLASE ADD CANT_DIGITOS NUMERIC(1,0)

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(35330, N'' '', 0, N''Cantidad de dígitos'', N''Cantidad de dígitos'', 1, N''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 300, N''CANT_DIGITOS'', 0, NULL);

INSERT INTO OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(35330, N''E'', N''15 dígitos'', N''1'', N''1'');
INSERT INTO OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(35330, N''E'', N''13 dígitos'', N''2'', N''2'');


')