EXECUTE('
CREATE OR ALTER PROCEDURE SP_DJ_INACTIVAR_CAUSA
   @P_NUM_SOLIC float(12),
   @P_NUM_CAUSA float(12),
   @P_NUM_JUZG  float(12),
   @P_ASIENTO float(10),
   @P_OPERACION VARCHAR(4),
   @P_USUARIO VARCHAR(10),
   @P_HORA VARCHAR(8),
   @P_FECHA_VENCIMIENTO DATE,
   
   @P_RET_PROCESO float(53)  OUTPUT,
   @P_MSG_PROCESO varchar(max)  OUTPUT
      
AS 

   BEGIN

      SET @P_RET_PROCESO = NULL
      SET @P_MSG_PROCESO = NULL
      
      DECLARE

         @FECHA DATETIME,
         @FECHA_ANTERIOR DATETIME,
         @CANT NUMERIC(5),
         @row_number NUMERIC(6),
         @v_constante VARCHAR(1),
         @v_numerador NUMERIC,
         @v_correlativo NUMERIC(10),
         
         --DECLARO VARIABLES TEMPORALES PARA RECORER TABLA AUXILIAR--
		 @NRO_SOLICITUDTemp NUMERIC (12, 0),
   		 @NRO_CAUSATemp NUMERIC (12, 0),
   		 @TIPO_CAUSATemp  VARCHAR (2), 
   		 @NRO_JUZTemp NUMERIC (12, 0),
   		 @ACCIONTemp VARCHAR(1),
      	 @ESTADOTemp VARCHAR(1),
      	 @FECHA_ESTADOTemp DATETIME,
      	 @FECHA_CAUSATemp DATETIME,
      	 @SUCURSALTemp NUMERIC (5, 0),
      	 @ID_PERSONATemp NUMERIC (12, 0),
      	 @JTS_OID_CUENTATemp NUMERIC (10, 0),
      	 @TIPO_PODERTemp NUMERIC (5, 0)
   		 
      	 
      	 
      --SET @CANT = 0
      SELECT @FECHA = FECHAPROCESO FROM PARAMETROS
      SELECT @FECHA_ANTERIOR = FECHAPROCESOANTERIOR FROM PARAMETROS
      
      --DECLARO TABLA AUXILIAR--
	  DECLARE @Tabla_INACTIVAR_CAUSA TABLE(
		NRO_SOLICITUD NUMERIC (12, 0), 
      	NRO_CAUSA NUMERIC (12, 0), 
      	TIPO_CAUSA VARCHAR (2),
      	NRO_JUZGADO NUMERIC (12, 0), 
      	ACCION VARCHAR(1),
      	ESTADO VARCHAR(1),
      	FECHA_ESTADO DATETIME,
      	FECHA_CAUSA DATETIME,
      	SUCURSAL NUMERIC (5, 0),
      	ID_PERSONA NUMERIC (12, 0),
      	JTS_OID_CUENTA NUMERIC (10, 0),
      	FILAS BIGINT,
      	ESTADO_DJ_CAUSA VARCHAR(1),
      	TIPO_PODER NUMERIC (5,0)
	  )
	  
	 
	 
      --COMPLETO TABLA AUXILIAR--
	  INSERT INTO 
		@Tabla_INACTIVAR_CAUSA
      SELECT  
      	     s.NRO_SOLICITUD, 
      	     s.NRO_CAUSA, 
      	     C.TIPO_CAUSA,
      	     s.NRO_JUZGADO,
      	     s.ACCION,
      	     s.ESTADO,
      	     s.FECHA_ESTADO,
      	     s.FECHA_CAUSA,
      	     s.SUCURSAL,
      	     IC.ID_PERSONA,
      	     cc.JTS_OID_CUENTA,
      	     row_number() OVER(ORDER BY s.NRO_SOLICITUD) AS filas,
      	     c.ESTADO AS ESTADO_CAUSA,
      	     PO.TIPO_PODER
	  FROM DJ_SOL_ACT_INAC_CAUSAS s WITH (NOLOCK)
	  INNER JOIN DJ_CAUSAS c WITH (NOLOCK) ON c.NRO_CAUSA=S.NRO_CAUSA AND c.JUZGADO=S.NRO_JUZGADO AND c.TZ_LOCK = 0
	  INNER JOIN DJ_CAUSA_CUENTA cc WITH (NOLOCK) ON c.NRO_CAUSA=cc.NRO_CAUSA AND (cc.TZ_LOCK < 300000000000000 OR cc.TZ_LOCK >= 400000000000000)
	  INNER JOIN DJ_INTEGRANTES_CAUSAS IC WITH (NOLOCK) ON IC.NRO_CAUSA=C.NRO_CAUSA AND IC.NRO_CAUSA=cc.NRO_CAUSA 
	  AND (ic.TZ_LOCK < 300000000000000 OR ic.TZ_LOCK >= 400000000000000),
	  PYF_APODERADOS po WITH (NOLOCK)
	  WHERE  s.NRO_JUZGADO  =  @P_NUM_JUZG
	  	AND s.NRO_SOLICITUD = @P_NUM_SOLIC
	  	AND s.NRO_CAUSA = @P_NUM_CAUSA
	  	AND s.TZ_LOCK = 0
		AND s.ESTADO = ''I''  
		AND s.ACCION = ''I''
	 	AND TRY_CAST(po.ID_ENTIDAD AS DECIMAL(10,0)) = cc.JTS_OID_CUENTA 
		AND po.ID_PERSONA = IC.ID_PERSONA
      
      
      
          --DECLARO TABLA AUXILIAR BENEFICIARIOS--
	  DECLARE @Tabla_INACTIVAR_CAUSA_BENEFICIARIOS TABLE(
		NRO_SOLICITUD NUMERIC (12, 0), 
      	NRO_CAUSA NUMERIC (12, 0), 
      	TIPO_CAUSA VARCHAR (2),
      	NRO_JUZGADO NUMERIC (12, 0), 
      	ACCION VARCHAR(1),
      	ESTADO VARCHAR(1),
      	FECHA_ESTADO DATETIME,
      	FECHA_CAUSA DATETIME,
      	SUCURSAL NUMERIC (5, 0),
      	ID_PERSONA NUMERIC (12, 0),
      	JTS_OID_CUENTA NUMERIC (10, 0),
      	FILAS BIGINT,
      	ESTADO_DJ_CAUSA VARCHAR(1),
      	TIPO_PODER NUMERIC (5,0)
	  )
	  
	  	 
      --COMPLETO TABLA BENEFICIARIOS--
	  INSERT INTO 
		@Tabla_INACTIVAR_CAUSA_BENEFICIARIOS
      SELECT  
      	     s.NRO_SOLICITUD, 
      	     s.NRO_CAUSA, 
      	     C.TIPO_CAUSA,
      	     s.NRO_JUZGADO,
      	     s.ACCION,
      	     s.ESTADO,
      	     s.FECHA_ESTADO,
      	     s.FECHA_CAUSA,
      	     s.SUCURSAL,
      	     DB.ID_BENEFICIARIO,
      	     cc.JTS_OID_CUENTA,
      	     row_number() OVER(ORDER BY s.NRO_SOLICITUD) AS filas,
      	     c.ESTADO AS ESTADO_CAUSA,
      	     PO.TIPO_PODER
	  FROM DJ_SOL_ACT_INAC_CAUSAS s WITH (NOLOCK)
	  INNER JOIN DJ_CAUSAS c WITH (NOLOCK) ON c.NRO_CAUSA=S.NRO_CAUSA AND c.JUZGADO=S.NRO_JUZGADO AND c.TZ_LOCK = 0
	  INNER JOIN DJ_CAUSA_CUENTA cc WITH (NOLOCK) ON c.NRO_CAUSA=cc.NRO_CAUSA AND (cc.TZ_LOCK < 300000000000000 OR cc.TZ_LOCK >= 400000000000000)
	  --INNER JOIN DJ_INTEGRANTES_CAUSAS IC WITH (NOLOCK) ON IC.NRO_CAUSA=C.NRO_CAUSA AND IC.NRO_CAUSA=cc.NRO_CAUSA 
	  --AND (ic.TZ_LOCK < 300000000000000 OR ic.TZ_LOCK >= 400000000000000)
	  INNER JOIN DJ_BENEFICIARIOS DB WITH (NOLOCK) ON DB.NRO_CAUSA = c.NRO_CAUSA AND DB.NRO_CAUSA=cc.NRO_CAUSA
	  AND (DB.TZ_LOCK < 300000000000000 OR DB.TZ_LOCK >= 400000000000000)
	  INNER JOIN SALDOS SS WITH (NOLOCK) ON SS.JTS_OID = cc.JTS_OID_CUENTA AND SS.PRODUCTO = 10,
	  PYF_APODERADOS po WITH (NOLOCK)
	  WHERE  s.NRO_JUZGADO  =  @P_NUM_JUZG
	  	AND s.NRO_SOLICITUD = @P_NUM_SOLIC
	  	AND s.NRO_CAUSA = @P_NUM_CAUSA
	  	AND s.TZ_LOCK = 0
	  	AND s.ESTADO = ''I''  
		AND s.ACCION = ''I''
	 	AND TRY_CAST(po.ID_ENTIDAD AS DECIMAL(10,0)) = cc.JTS_OID_CUENTA 
		AND po.ID_PERSONA = DB.ID_BENEFICIARIO
	  
      
      BEGIN TRANSACTION	
      
       BEGIN TRY
	       	  	
	       	  	/*SE QUITAN PODERES*/
				UPDATE P
				SET 
					P.FECHA_INI_SUSPENSION = P.FECHA_VENCIMIENTO, --@P_FECHA_VENCIMIENTO,
					P.FECHA_VENCIMIENTO = @FECHA_ANTERIOR,
					P.ID_CLIENTE_SALDO = T.JTS_OID_CUENTA
				FROM
					PYF_APODERADOS AS P
				INNER JOIN @Tabla_INACTIVAR_CAUSA AS T ON
					P.ID_PERSONA = T.ID_PERSONA
					AND P.TIPO_ENTIDAD = 2
					AND TRY_CAST(P.ID_ENTIDAD AS DECIMAL(10,0)) = T.JTS_OID_CUENTA
					AND P.TIPO_PODER = T.TIPO_PODER
				 
					
				/*SE QUITAN PODERES BENEFICIARIO*/
				UPDATE P
				SET 
					P.FECHA_INI_SUSPENSION = P.FECHA_VENCIMIENTO, --@P_FECHA_VENCIMIENTO,
					P.FECHA_VENCIMIENTO = @FECHA_ANTERIOR,
					P.ID_CLIENTE_SALDO = T.JTS_OID_CUENTA
				FROM
					PYF_APODERADOS AS P
				INNER JOIN @Tabla_INACTIVAR_CAUSA_BENEFICIARIOS AS T ON
					P.ID_PERSONA = T.ID_PERSONA
					AND P.TIPO_ENTIDAD = 2
					AND TRY_CAST(P.ID_ENTIDAD AS DECIMAL(10,0)) = T.JTS_OID_CUENTA
					AND P.TIPO_PODER = T.TIPO_PODER
					
					
				
		
				/*SE QUITA LOS ITEGRANTES DE LA CAUSA*/
				UPDATE P
				SET 
					P.FECHA_CESE = @FECHA,
					P.ACTIVO = ''N''	
				FROM DJ_INTEGRANTES_CAUSAS AS P
				INNER JOIN @Tabla_INACTIVAR_CAUSA AS T ON
			    P.NRO_CAUSA = T.NRO_CAUSA
			    --AND P.ID_PERSONA = @P_NUM_PER
	  					
   
			COMMIT TRANSACTION;
			
			SET @P_RET_PROCESO = 1
		    SET @P_MSG_PROCESO = ''Se inactivo la causa correctamente.''
			 
		END TRY     
		
		BEGIN CATCH
			ROLLBACK TRANSACTION
			SET @P_RET_PROCESO = ERROR_NUMBER()
			SET @P_MSG_PROCESO = ERROR_MESSAGE()
			EXECUTE dbo.pkg_constantes$VarcharConstantes ''C_LOG_TIPO_ERROR'', @v_constante OUTPUT;
		END CATCH
		 	      
 END
')

