--METADATA
-- CREACION CAMPO 37332

EXECUTE('        
-- CREACION CAMPO 45138 CON OPCIONES
IF EXISTS (SELECT a.NUMERODECAMPO  FROM DICCIONARIO A WHERE NUMERODECAMPO = 45138)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 45138;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
    VALUES (45138, '' '', 0, ''Filtro si no'', NULL, 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Filtro si no'', 0, NULL)

END
ELSE
BEGIN

     INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
     VALUES (45138, '' '', 0, ''Filtro si no'', NULL, 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Filtro si no'', 0, NULL)

END

IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 45138)
BEGIN

 DELETE FROM OPCIONES 
     WHERE NUMERODECAMPO = 45138;
 
  INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
   VALUES (45138, ''E'', ''No'', ''N'', ''N'')


  INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
  VALUES (45138, ''E'', ''Si'', ''S'', ''S'')  
    
    
    
END
ELSE
BEGIN

     INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45138, ''E'', ''No'', ''N'', ''N'')


INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45138, ''E'', ''Si'', ''S'', ''S'')
     
     
END

')
