EXECUTE('

DELETE FROM dbo.ITF_MASTER_PARAMETROS
WHERE CODIGO = 154

INSERT INTO dbo.ITF_MASTER_PARAMETROS (CODIGO, CODIGO_INTERFACE, FUNCIONALIDAD, ALFA_1, ALFA_2, ALFA_3, NUMERICO_1, NUMERICO_2, FECHA, IMPORTE_1, IMPORTE_2, TZ_LOCK)
VALUES (154, 0, ''Sec Nom Archivo Cheq'', ''Img Cheque'', '' '', '' '', 1, 0, ''20270714'', 0, 0, 0)

DELETE FROM dbo.PARAMETROSGENERALES
WHERE CODIGO = 736

INSERT INTO dbo.PARAMETROSGENERALES (CODIGO, DESCRIPCION, ALFA, NUMERICO, FECHA, IMPORTE, TASA, TZ_LOCK)
VALUES (736, ''importe fijado BCRA '', '''', 5000, NULL, 0, 0, 0)

')