EXECUTE('
UPDATE OPCIONES
SET DESCRIPCION = ''Intransferible''
WHERE NUMERODECAMPO = 20245 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''01''

UPDATE OPCIONES
SET DESCRIPCION = ''Transferible''
WHERE NUMERODECAMPO = 20245 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''02''
')


