EXECUTE('
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44446, '' '', 0, ''Listado rubros plan de cuentas'', ''Listado rubros plan de cuentas'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 634, 0, 0, ''C44446'', 0, NULL)
--
UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 634
WHERE NUMERODECAMPO = 50224
----
')

