EXECUTE('
IF OBJECT_ID (''CRE_BCRA_CENDEU'') IS NOT NULL
	DROP TABLE CRE_BCRA_CENDEU
')

EXECUTE('
CREATE TABLE CRE_BCRA_CENDEU
	(
	FECHA_PROCESO       DATETIME NULL,
	COD_ENTIDAD         VARCHAR (5) DEFAULT ('' '') NOT NULL,
	FECHA               VARCHAR (6) DEFAULT ('' '') NULL,
	CODIGOCLIENTE       NUMERIC (11) DEFAULT ('' '') NOT NULL,
	TPO_IDENTIFICACION  NUMERIC (2) DEFAULT ((0)) NOT NULL,
	NRO_IDENTIFICACION  VARCHAR (11) DEFAULT ('' '') NOT NULL,
	ACTIVIDAD           NUMERIC (3) DEFAULT ('' '') NULL,
	SITUACION_BCRA      VARCHAR (2) DEFAULT ('' '') NULL,
	PRESTAMOS           NUMERIC (15,2) DEFAULT ((0)) NULL,
	PARTICIPACIONES     NUMERIC (15,2) DEFAULT ((0)) NULL,
	GARANTIAS           NUMERIC (15,2) DEFAULT ((0)) NULL,
	OTROS_CONCEPTOS     NUMERIC (15,2) DEFAULT ((0)) NULL,
	DEUDA_TOTAL         NUMERIC (15,2) DEFAULT ((0)) NULL,
	GARANTIA_A          NUMERIC (15,2) DEFAULT ((0)) NULL,
	GARANTIA_B          NUMERIC (15,2) DEFAULT ((0)) NULL,
	SIN_GARANTIAS       NUMERIC (15,2) DEFAULT ((0)) NULL,
	CONTRA_GARANTIA_A   NUMERIC (15,2) DEFAULT ((0)) NULL,
	CONTRA_GARANTIA_B   NUMERIC (15,2) DEFAULT ((0)) NULL,
	SIN_CONTRA_GARANTIA NUMERIC (15,2) DEFAULT ((0)) NULL,
	PREVISIONES         NUMERIC (15,2) DEFAULT ((0)) NULL,
	DEUDA_CUBIERTA      NUMERIC (1) DEFAULT ((0)) NULL,
	PROCESO_JUDICIAL    NUMERIC (1) DEFAULT ((0)) NULL,
	REFINANCIACIONES    NUMERIC (1) DEFAULT ((0)) NULL,
	RECATEGORIZACION    NUMERIC (1) DEFAULT ((0)) NULL,
	SIT_JURIDICA        NUMERIC (1) DEFAULT ((0)) NULL,
	IRR_DISP_TECNICA    NUMERIC (1) DEFAULT ((0)) NULL,
	DIAS_ATRASO         NUMERIC (4) DEFAULT ((0)) NULL,
	SITUACION_ENTIDAD   NUMERIC (1) DEFAULT ((0)) NULL,
	TZ_LOCK             NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_BCRA_CENDEU PRIMARY KEY (COD_ENTIDAD,CODIGOCLIENTE)
	)
')

EXECUTE('
IF OBJECT_ID (''CRE_EXCEP_ENT_DISCREPANCIA'') IS NOT NULL
	DROP TABLE CRE_EXCEP_ENT_DISCREPANCIA
')

EXECUTE('
CREATE TABLE CRE_EXCEP_ENT_DISCREPANCIA
	(
	TZ_LOCK     NUMERIC (15) NULL,
	ENTIDAD     NUMERIC (5) NOT NULL,
	DESCRIPCION VARCHAR (50) NULL,
	CARTERA     VARCHAR (1) NULL,
	CONSTRAINT PK_CRE_EXCEP_ENT_DISCREPANCIA PRIMARY KEY (ENTIDAD)
	)
')

EXECUTE('
IF OBJECT_ID (''CRE_BITACORA_CALIF_SUBJETIVA'') IS NOT NULL
	DROP TABLE CRE_BITACORA_CALIF_SUBJETIVA
')

EXECUTE('
CREATE TABLE CRE_BITACORA_CALIF_SUBJETIVA
	(
	CLIENTE                NUMERIC (12) DEFAULT ((0)) NOT NULL,
	FECHA                  DATETIME NOT NULL,
	CALIFICACION_SUBJETIVA VARCHAR (2) DEFAULT ('' '') NULL,
	JUSTIFICACION          VARCHAR (200) DEFAULT ('' '') NULL,
	CONSTRAINT PK_CRE_BITACORA_CALIF_SUBJETIVA_01 PRIMARY KEY (CLIENTE,FECHA)
	)
')

EXECUTE('
IF OBJECT_ID (''VW_JMPM_PROCESS_INSTANCE_LEASING'') IS NOT NULL
	DROP VIEW VW_JMPM_PROCESS_INSTANCE_LEASING
')

EXECUTE('
CREATE   VIEW [dbo].[VW_JMPM_PROCESS_INSTANCE_LEASING] (
NROSOLICITUD, 
TIPO, 
PROCESS_INSTANCE, 
TZ_LOCK)
AS 
SELECT	J.NRO_SOLICITUD AS NROSOLICITUD, 
		''L'' AS TIPO, 
		J.PROCESSINSTANCE_ID AS PROCESS_INSTANCE, 
		0 AS TZ_LOCK
FROM dbo.CRE_SOLICITUDCREDITO  AS S WITH(NOLOCK)
INNER JOIN PRODUCTOS p WITH(NOLOCK) ON S.CODPRODUCTOSOLICITADO = p.C6250 AND p.C6800 = ''L'' AND p.TZ_LOCK = 0
INNER JOIN dbo.JBPM_TZKEY_SOLICITUDLEASING AS J WITH(NOLOCK) ON S.NUMEROSOLICITUD = J.NRO_SOLICITUD
')

EXECUTE('
ALTER TABLE HISTORICO_CALIF_X_CLIENTE ADD DISCREPANCIA VARCHAR(2) DEFAULT ('' '')
')

EXECUTE('
ALTER TABLE HISTORICO_CALIF_X_CLIENTE ADD TIPO_CALIFICACION NUMERIC(1)
')

EXECUTE('
ALTER TABLE HISTORICO_CALIF_X_CLIENTE ADD FECHA_SITUACION DATETIME
')

EXECUTE('
ALTER TABLE HISTORICO_CALIF_X_CLIENTE ADD Sit_MorExEnt VARCHAR(2) DEFAULT '' ''
')

EXECUTE('
ALTER TABLE HISTORICO_CALIF_X_CLIENTE ADD SITUACION_JUDICIAL VARCHAR(2) DEFAULT '' ''
')

EXECUTE('
ALTER TABLE CLI_CLIENTES ADD Sit_MorExEnt VARCHAR(2) DEFAULT '' ''
')

EXECUTE('
ALTER TABLE CLI_CLIENTES ADD DISCREPANCIA VARCHAR(2) DEFAULT('' '')
')

EXECUTE('
ALTER TABLE CLI_CLIENTES ADD SITUACION_JUDICIAL VARCHAR(2) DEFAULT '' ''
')




