EXECUTE('
IF OBJECT_ID (''dbo.VW_CHEQUES_MULTA'') IS NOT NULL
	DROP VIEW dbo.VW_CHEQUES_MULTA
')
EXECUTE('
CREATE VIEW [dbo].[VW_CHEQUES_MULTA] (
		[Número de cheque],
		Sucursal,
		Cuenta,
		Denominación,
		Producto,
		Moneda,
		Importe,
		[Causal de Devolución],
		Descripción,
		[Fecha de rechazo],
		Cliente,
		Serie,
		Banco,
		Multa,
		[Fecha pago de multa],
		[Número de aviso],
		[Fecha notificación BCRA])
AS 
SELECT 
	DISTINCT 
		D.NROCHEQUE,
		D.SUCURSAL,
		D.CUENTA,
		VS.NOMBRE_CUENTA,
		D.PRODUCTO,
		D.MONEDA,
		D.IMPORTE,
		D.CONCDEVOLUCION,
		T.DESCRIPCION,
		B.FECHA_CHEQUE,
		D.CLIENTE,
		D.SERIE,
		D.CODBANCO,
		T.MULTA,
		B.FECHA_PAGO_MULTA,
		B.Nro_Aviso,
		B.FECHA_NOTIF_BCRA
FROM CLE_CHEQUES_CLEARING_DEVUELTOS D WITH (NOLOCK)
INNER JOIN CHE_BCO_RECHAZADOS B WITH (NOLOCK) ON 
	B.SERIE_CHEQUE = D.SERIE 
	AND B.NRO_CHEQUE = D.NROCHEQUE 
	AND B.SUCURSAL = D.SUCURSAL 
	AND B.MONEDA = D.MONEDA 
	AND B.PRODUCTO = D.PRODUCTO 
	AND B.CUENTA = D.CUENTA
	AND B.TZ_LOCK = 0
INNER JOIN SALDOS S WITH (NOLOCK) ON 
	S.SUCURSAL = D.SUCURSAL
	AND S.MONEDA = D.MONEDA
	AND S.PRODUCTO = D.PRODUCTO
	AND S.CUENTA = D.CUENTA
	AND S.TZ_LOCK = 0
INNER JOIN CLE_TIPO_CAUSAL T WITH (NOLOCK) ON 
	T.CODIGO_DE_CAUSAL = D.CONCDEVOLUCION
	AND ((T.TZ_LOCK < 100000000000000 OR T.TZ_LOCK >= 200000000000000)
		AND (T.TZ_LOCK < 300000000000000 OR T.TZ_LOCK >= 400000000000000)  
	)
INNER JOIN VTA_SALDOS VS WITH (NOLOCK) ON 
	S.JTS_OID = VS.JTS_OID_SALDO
	AND ((VS.TZ_LOCK < 100000000000000 OR VS.TZ_LOCK >= 200000000000000)
		AND (VS.TZ_LOCK < 300000000000000 OR VS.TZ_LOCK >= 400000000000000)  
	)
WHERE
	D.TZ_LOCK = 0
')