EXECUTE('
UPDATE a
SET a.DESCRIPCION =  substring(b.DESCRIPCION,1,45)
FROM MC_CONCEPTOS a
INNER JOIN MC_CONCEPTOS b ON a.COD_CONCEPTO = b.COD_CONCEPTO 
')

EXECUTE('
ALTER TABLE MC_CONCEPTOS 
ALTER COLUMN DESCRIPCION  VARCHAR (60)
')

EXECUTE('
UPDATE DICCIONARIO
SET LARGO = 60
WHERE NUMERODECAMPO = 57041
')
