EXECUTE('
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (3100, 8205, ''Movimientos Tesorero'', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (3100, 8206, ''Consulta saldos ATM'', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (8205, 1, NULL, 0, 0, 1)

INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (8206, 1, NULL, 0, 0, 1)
')

EXECUTE('
INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (3111, 3261, ''Reporte movimiento tesoreria'', ''Reporte movimiento tesoreria'', ''3261'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')

