/****** Object:  StoredProcedure [dbo].[SP_ITF_ACTUALIZAR_GASTOSXCUOTA]    Script Date: 01/06/2021 14:06:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_ITF_ACTUALIZAR_GASTOSXCUOTA]  
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */

   @P_ID_PROCESO float(53),
   @P_DT_PROCESO datetime2(0),
   @P_RET_PROCESO smallint  OUTPUT,
   @P_MSG_PROCESO varchar(max)  OUTPUT
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
   BEGIN

      BEGIN TRY

         SET @P_RET_PROCESO = NULL

         SET @P_MSG_PROCESO = NULL

         /*ORDER BY saldos_jts_oid, numero_cuota;*/
         DECLARE
            @LINEA_REG$TZ_LOCK numeric(15, 0), 
            @LINEA_REG$SALDOS_JTS_OID numeric(10, 0), 
            @LINEA_REG$NUMERO_CUOTA numeric(4, 0), 
            @LINEA_REG$SECUENCIAL numeric(4, 0), 
            @LINEA_REG$CARGO_ID numeric(4, 0), 
            @LINEA_REG$IMPUESTO_ID numeric(4, 0), 
            @LINEA_REG$IMPORTE_GASTO numeric(15, 2), 
            @LINEA_REG$SALDO_GASTO numeric(15, 2), 
            @LINEA_REG$GASTOPARALELO numeric(15, 2), 
            @LINEA_REG$GASTO_NP_ULT_PAGO numeric(15, 2), 
            @LINEA_REG$PRIORIDAD numeric(4, 0), 
            @V_ORDINAL_MOVS numeric(15) = 1, 
            @V_FECHAAPERTURA datetime2(0), 
            @V_FECHAVTO datetime2(0), 
            @V_IMPORTE_GASTO numeric(15, 2), 
            @V_CANTREGTOTAL numeric(15) = 0, 
            @V_IMPORTE_IVA numeric(15, 2), 
            @V_ORDINAL numeric(15), 
            @V_SECUENCIAL numeric(4) = 2, 
            @V_ID_IMPUESTO numeric(4) = 3, 
            @V_SALDO_GASTO numeric(15, 2), 
            @V_SALDO_IVA numeric(15, 2)

         DECLARE
             MOVS_REG CURSOR LOCAL FOR 
               SELECT 
                  GASTOS_POR_CUOTA.TZ_LOCK, 
                  GASTOS_POR_CUOTA.SALDOS_JTS_OID, 
                  GASTOS_POR_CUOTA.NUMERO_CUOTA, 
                  GASTOS_POR_CUOTA.SECUENCIAL, 
                  GASTOS_POR_CUOTA.CARGO_ID, 
                  GASTOS_POR_CUOTA.IMPUESTO_ID, 
                  GASTOS_POR_CUOTA.IMPORTE_GASTO, 
                  GASTOS_POR_CUOTA.SALDO_GASTO, 
                  GASTOS_POR_CUOTA.GASTOPARALELO, 
                  GASTOS_POR_CUOTA.GASTO_NP_ULT_PAGO, 
                  GASTOS_POR_CUOTA.PRIORIDAD
               FROM dbo.GASTOS_POR_CUOTA WITH (NOLOCK)
               WHERE 
                  GASTOS_POR_CUOTA.CARGO_ID = 3007 AND 
                  GASTOS_POR_CUOTA.SALDO_GASTO <> 0 AND 
                  (GASTOS_POR_CUOTA.TZ_LOCK < 310000000000000 OR GASTOS_POR_CUOTA.TZ_LOCK > 339999999999999)

         /*RECORRO EL CURSOR DE LAS FACTURAS POR EL CARGO de PRONTO*/
         OPEN MOVS_REG

         WHILE 1 = 1
         
            BEGIN

               FETCH MOVS_REG
                   INTO 
                     @LINEA_REG$TZ_LOCK, 
                     @LINEA_REG$SALDOS_JTS_OID, 
                     @LINEA_REG$NUMERO_CUOTA, 
                     @LINEA_REG$SECUENCIAL, 
                     @LINEA_REG$CARGO_ID, 
                     @LINEA_REG$IMPUESTO_ID, 
                     @LINEA_REG$IMPORTE_GASTO, 
                     @LINEA_REG$SALDO_GASTO, 
                     @LINEA_REG$GASTOPARALELO, 
                     @LINEA_REG$GASTO_NP_ULT_PAGO, 
                     @LINEA_REG$PRIORIDAD

               /*
               *   SSMA warning messages:
               *   O2SS0113: The value of @@FETCH_STATUS might be changed by previous FETCH operations on other cursors, if the cursors are used simultaneously.
               */

               IF @@FETCH_STATUS <> 0
                  BREAK

               SET @V_CANTREGTOTAL = @V_CANTREGTOTAL + 1

               SET @V_IMPORTE_GASTO = @LINEA_REG$IMPORTE_GASTO / 1.22

               SET @V_IMPORTE_IVA = @LINEA_REG$IMPORTE_GASTO - @V_IMPORTE_GASTO

               SET @V_SALDO_GASTO = @LINEA_REG$SALDO_GASTO / 1.22

               SET @V_SALDO_IVA = @LINEA_REG$SALDO_GASTO - @V_SALDO_GASTO

               /*ACTUALIZO EL IMPORTE_GASTO SIN IVA*/
               UPDATE dbo.GASTOS_POR_CUOTA
                  SET 
                     IMPORTE_GASTO = @V_IMPORTE_GASTO, 
                     SALDO_GASTO = @V_SALDO_GASTO
               WHERE 
                  GASTOS_POR_CUOTA.SALDOS_JTS_OID = @LINEA_REG$SALDOS_JTS_OID AND 
                  GASTOS_POR_CUOTA.NUMERO_CUOTA = @LINEA_REG$NUMERO_CUOTA AND 
                  GASTOS_POR_CUOTA.SECUENCIAL = @LINEA_REG$SECUENCIAL

               
               /*
               *   v_ordinal:=v_ordinal+1;
               *   DOY DE ALTA LA LINEA DEL IVA SOLO PARA EL IMPUESTO 3
               */
               INSERT dbo.GASTOS_POR_CUOTA(
                  TZ_LOCK, 
                  SALDOS_JTS_OID, 
                  NUMERO_CUOTA, 
                  SECUENCIAL, 
                  CARGO_ID, 
                  IMPUESTO_ID, 
                  IMPORTE_GASTO, 
                  SALDO_GASTO, 
                  GASTOPARALELO)
                  VALUES (
                     @LINEA_REG$TZ_LOCK, 
                     @LINEA_REG$SALDOS_JTS_OID, 
                     @LINEA_REG$NUMERO_CUOTA, 
                     @V_SECUENCIAL, 
                     @LINEA_REG$CARGO_ID, 
                     @V_ID_IMPUESTO, 
                     @V_IMPORTE_IVA, 
                     @V_SALDO_IVA, 
                     @LINEA_REG$GASTOPARALELO)

               IF @@TRANCOUNT > 0
                  COMMIT WORK 

            END

         CLOSE MOVS_REG

         DEALLOCATE MOVS_REG

         IF @@TRANCOUNT > 0
            COMMIT WORK 

         SET @P_MSG_PROCESO = 'Resultado del Proceso:'

         SET @P_MSG_PROCESO = ISNULL(@P_MSG_PROCESO, '') + ISNULL(char(10), '') + 'Cantidad de Registros procesadas: ' + ISNULL(CAST(@V_CANTREGTOTAL AS varchar(max)), '')

         SET @P_MSG_PROCESO = @P_MSG_PROCESO

      END TRY


     BEGIN CATCH

         DECLARE
            @errornumber int

         SET @errornumber = ERROR_NUMBER()

         DECLARE
            @errormessage nvarchar(4000)

         SET @errormessage = ERROR_MESSAGE()

         DECLARE
            @exceptionidentifier nvarchar(4000)
-- LF 03/06/2021 EVITANDO LA EJECUCIÓN DE COMANDOS ORACLE.

 --        SELECT @exceptionidentifier = 
  --          ssma_oracle.db_error_get_oracle_exception_id(@errormessage, @errornumber)

 --        BEGIN
 --           BEGIN

   --            DECLARE
  --                @ERROR_CODE numeric(4) = 
   --                  ssma_oracle.db_error_sqlcode(@exceptionidentifier, @errornumber), 
  --                @ERROR_MSG varchar(300) = 
  --                   ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier, @errornumber), 
 --                 @BIGERRMSG varchar(4000)

   --            IF @@TRANCOUNT > 0
    --              ROLLBACK WORK 
               /* reviete cambios y cierra cursores*/

               /*
               *   SSMA warning messages:
               *   O2SS0542: Results of the DBMS_UTILITY.FORMAT_ERROR_BACKTRACE conversion will not include full stack trace for the error.
               */

               /* Valores de Retorno.*/
--               SET @BIGERRMSG = ISNULL(CONCAT(
--                  ERROR_NUMBER(), 
--                  ': at "', 
--                  ERROR_PROCEDURE(), 
--                  '", line ', 
--                  ERROR_LINE()), '') + ISNULL(
--                  ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier, @errornumber), '')

 --           END
	
 --        END
   
      END CATCH

   END
  