EXECUTE('
IF OBJECT_ID (''dbo.RRII_ITF_TRANSPARENCIA'') IS NOT NULL
	DROP TABLE dbo.RRII_ITF_TRANSPARENCIA


CREATE TABLE dbo.RRII_ITF_TRANSPARENCIA
	(
	FECHADEINFORMACION DATETIME NOT NULL,
	CODIGOPARTIDA      VARCHAR (6) NOT NULL,
	IMPORTEVIGENTE     NUMERIC (11, 2),
	TASAINTERES        NUMERIC (7, 2),
	CANTIDAD           NUMERIC (11),
	OBSERVACIONES      VARCHAR (120),
	MONEDA             VARCHAR (1),
	EMPRESA            VARCHAR (4) NOT NULL,
	IMPORTEPREVISTO    NUMERIC (11, 2),
	FECHAVIGENCIA      DATETIME,
	FECHADEINFORME     DATETIME NOT NULL,
	CONSTRAINT PK_RRII_ITF_TRANSPARENCIA PRIMARY KEY (FECHADEINFORMACION, CODIGOPARTIDA, EMPRESA, FECHADEINFORME)
	)
')
