EXECUTE('
DELETE FROM dbo.TTR_CODIGO_TRANSACCION_DEF
WHERE CODIGO_TRANSACCION = 3030

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO, DEBITO_CREDITO)
VALUES (0, 3030, ''DEBITO PAGO PRESTAMO SUBSIDIO'', ''N'', NULL, '' '', ''N'', 0, NULL, NULL)
')
