EXECUTE('

ALTER PROCEDURE SP_PROD_CARACTERISTICAS_CLIENTE
  @CodCliente     NUMERIC(12, 0),
  @CANTIDAD_INTEG  FLOAT OUTPUT,
  @MAYOR_EDAD_FINAL VARCHAR(1) OUTPUT,
  @MENOR_ADOLE_FINAL  VARCHAR (1) OUTPUT,
  @MENOR_EMANCIPADO_FINAL VARCHAR (1) OUTPUT,
  @MENOR_AUTORIZ_FINAL VARCHAR (1) OUTPUT,
  @TIPO_CLIENTE_FINAL VARCHAR (1) OUTPUT
  AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @NUMEROPERSONAREC AS NUMERIC(12,0)=0, 
  @EDADREC AS float=0,
  @TIPOPERSONAREG AS VARCHAR(1),
  @TITULARIDADREG AS VARCHAR(1),
  @ESTADOCIVILREG AS VARCHAR(1),
  @MAYOR_EDAD AS VARCHAR(1)=''N'',
  @MENOR_ADOLE AS VARCHAR(1)=''N'',
  @MENOR_AUTORIZ AS VARCHAR(1)=''N'',
  @TIPO_CLIENTE AS VARCHAR(1),
  @ENCONTROEMANCIPADO_ float(53),
  @TITULARIDAD VARCHAR(1)=''T''
    
  SET @CANTIDAD_INTEG =0
  SET @MAYOR_EDAD_FINAL=''N''  
  SET @MENOR_ADOLE_FINAL =''N''
  SET @MENOR_EMANCIPADO_FINAL =''N''
  SET @MENOR_AUTORIZ_FINAL =''N''
  
  SELECT 
  @TIPO_CLIENTE=(CASE WHEN TIPO =''F'' THEN
  		''F''
  		   ELSE
  		''J'' 
  END)
  FROM CLI_CLIENTES WHERE CODIGOCLIENTE=@CodCliente AND TZ_LOCK=0
  
  SET @TIPO_CLIENTE_FINAL =@TIPO_CLIENTE
  
     		
	    -- Analizo los integrantes

    DECLARE EdadesIntegrantesCur CURSOR FOR
  
						--************INTEGRA CLIENTE****************
						
						SELECT cp.NUMEROPERSONA, 
						cp.TIPOPERSONA,
						cp.TITULARIDAD,
				  
						-- INTEGRANTE DEL CLIENTE ES UNA PERSONA FISICA
						-- Muestro edad del mismo
						CASE WHEN cp.tipopersona=''F'' THEN
						(SELECT FLOOR(DATEDIFF(month, FECHANACIMIENTO, (SELECT FECHAPROCESO FROM PARAMETROS)) / CONVERT(FLOAT, 12))
						 FROM CLI_PERSONASFISICAS f 
						 WHERE f.NUMEROPERSONAFISICA=cp.NUMEROPERSONA AND f.TZ_LOCK=0)
						ELSE
								-- INTEGRANTE DEL CLIENTE ES UNA PERSONA JURÍDICA
								-- Si el titular de esa PJ es una PF se muestra la edad de ella.
							CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE TIPOVINCULACION =''T'' AND TIPO_PERSONA=''F'' AND NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA)>0 THEN 
								 (SELECT FLOOR(DATEDIFF(month, F.FECHANACIMIENTO, (SELECT FECHAPROCESO FROM PARAMETROS)) / CONVERT(FLOAT, 12))
								 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
								 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPOVINCULACION =''T'' AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
								 		AND f.TZ_LOCK=0 AND i.TZ_LOCK=0)
							ELSE
						     	-- Sino Si el titular es una PJ 
								  -- Y a su vez no hay un Representante Legal
										CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA AND CODIGOCARGO=''REP'')=0 THEN
										-- Se muestra Edad Persona Física Integrante
											(SELECT TOP (1) FLOOR(DATEDIFF(month, F.FECHANACIMIENTO, (SELECT FECHAPROCESO FROM PARAMETROS)) / CONVERT(FLOAT, 12))
											 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
											 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
											 AND i.TIPOVINCULACION =''C'' AND f.TZ_LOCK=0 AND i.TZ_LOCK=0)
										ELSE	 
									    -- Pero si hay un representante Legal
									          -- Y no hay otra PF como integrante
									    		CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA AND CODIGOCARGO<>''REP'' AND TIPO_PERSONA=''F'')=0 THEN
									    			-- Muestro edad del RL
									    			 (SELECT FLOOR(DATEDIFF(month, F.FECHANACIMIENTO, (SELECT FECHAPROCESO FROM PARAMETROS)) / CONVERT(FLOAT, 12))
														 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
														 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
														 		AND f.TZ_LOCK=0 AND i.TZ_LOCK=0 AND CODIGOCARGO=''REP'')
												 ELSE
								    				-- Sino Muestro edad de Persona Física Integrante
									    			 (SELECT TOP (1) FLOOR(DATEDIFF(month, F.FECHANACIMIENTO, (SELECT FECHAPROCESO FROM PARAMETROS)) / CONVERT(FLOAT, 12))
													  FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
													  WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
													  AND f.TZ_LOCK=0 AND i.TZ_LOCK=0 AND CODIGOCARGO<>''REP'')						 	
									    		 END	
									     END
							 END
									
						END AS EDAD,
						CASE WHEN cp.tipopersona=''F'' THEN
						  (SELECT F.ESTADOCIVIL FROM CLI_PERSONASFISICAS f 
						   WHERE f.NUMEROPERSONAFISICA=cp.NUMEROPERSONA AND f.TZ_LOCK=0)
						ELSE
								-- INTEGRANTE DEL CLIENTE ES UNA PERSONA JURÍDICA
								-- Si el titular de esa PJ es una PF se muestra la edad de ella.
							CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE TIPOVINCULACION =''T'' AND TIPO_PERSONA=''F'' AND NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA)>0 THEN 
								 (SELECT F.ESTADOCIVIL
								 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
								 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPOVINCULACION =''T'' AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
								 		AND f.TZ_LOCK=0 AND i.TZ_LOCK=0)
							ELSE
						     	-- Sino Si el titular es una PJ 
								  -- Y a su vez no hay un Representante Legal
										CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA AND CODIGOCARGO=''REP'')=0 THEN
										-- Se muestra Edad Persona Física Integrante
											(SELECT TOP (1) F.ESTADOCIVIL
											 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
											 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
											 AND i.TIPOVINCULACION =''C'' AND f.TZ_LOCK=0 AND i.TZ_LOCK=0)
										ELSE	 
									    -- Pero si hay un representante Legal
									          -- Y no hay otra PF como integrante
									    		CASE WHEN (SELECT count (*) FROM CLI_INTEGRANTESPJ WHERE NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA AND CODIGOCARGO<>''REP'' AND TIPO_PERSONA=''F'')=0 THEN
									    			-- Muestro edad del RL
									    			 (SELECT F.ESTADOCIVIL
														 FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
														 WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
														 		AND f.TZ_LOCK=0 AND i.TZ_LOCK=0 AND CODIGOCARGO=''REP'')
												 ELSE
								    				-- Sino Muestro edad de Persona Física Integrante
									    			 (SELECT TOP (1) F.ESTADOCIVIL
													  FROM CLI_PERSONASFISICAS f, CLI_INTEGRANTESPJ i 
													  WHERE f.NUMEROPERSONAFISICA=i.NUMEROPERSONAFISICA AND i.TIPO_PERSONA=''F'' AND i.NUMEROPERSONAJURIDICA=cp.NUMEROPERSONA
													  AND f.TZ_LOCK=0 AND i.TZ_LOCK=0 AND CODIGOCARGO<>''REP'')						 	
									    		 END	
									     END
							 END
									
						END AS ESTADO_CIVIL
						FROM VW_CLIENTES_PERSONAS cp WHERE cp.CODIGOCLIENTE = @CodCliente
   ;

  OPEN EdadesIntegrantesCur;

			FETCH NEXT FROM EdadesIntegrantesCur INTO @NUMEROPERSONAREC,@TIPOPERSONAREG,@TITULARIDADREG,@EDADREC,@ESTADOCIVILREG;
			WHILE @@FETCH_STATUS = 0 
		    	BEGIN
		    	
				
				-- Evaluamos si son mayores de edad
			
				IF @EDADREC>= (SELECT numerico FROM PARAMETROSGENERALES WHERE CODIGO=13 ) AND @TITULARIDAD=@TITULARIDADREG
						AND @TIPO_CLIENTE_FINAL=''F''
					SET @MAYOR_EDAD=''S''
					
				IF @MAYOR_EDAD=''S''
					SET @MAYOR_EDAD_FINAL=''S''
					
				-- Evaluamos si son menores emancipados
				
				    SET @ENCONTROEMANCIPADO_ = 0
				
			   		SELECT @ENCONTROEMANCIPADO_ = count_big(*)
	            	FROM CLI_ACTIVIDAD_ECONOMICA
	           	    WHERE TZ_LOCK=0
	           	    AND CODIGO_PERSONA_CLIENTE= @NUMEROPERSONAREC
	           	    AND CODIGO_ACTIVIDAD NOT IN (''000008'', ''000012'')

				
			    IF (@ENCONTROEMANCIPADO_ > 0 OR @ESTADOCIVILREG<>''S'') AND @EDADREC< (SELECT numerico FROM PARAMETROSGENERALES WHERE CODIGO=13 )
			    	AND @TIPO_CLIENTE_FINAL=''F''
			   		 SET @MENOR_EMANCIPADO_FINAL=''S''
					
			    -- Evaluamos si son menores adolescentes, si es menor emancipado condiciona a que este campo sea N
			
				IF @EDADREC> (SELECT numerico FROM PARAMETROSGENERALES WHERE CODIGO=14 ) AND @EDADREC< (SELECT importe FROM PARAMETROSGENERALES WHERE CODIGO=14 )
						AND @TITULARIDAD=@TITULARIDADREG AND @TIPO_CLIENTE_FINAL=''F''
					SET @MENOR_ADOLE=''S''
					
				IF @MENOR_ADOLE=''S''
					SET @MENOR_ADOLE_FINAL=''S''
					
			   	-- Evaluamos si son menores autorizados, si es menor emancipado condiciona a que este campo sea N
			
				IF @EDADREC< (SELECT numerico FROM PARAMETROSGENERALES WHERE CODIGO=14 ) AND @TITULARIDAD=@TITULARIDADREG 
					   AND @TIPO_CLIENTE_FINAL=''F''
					SET @MENOR_AUTORIZ=''S'' 
					
				IF @MENOR_AUTORIZ=''S''
					SET @MENOR_AUTORIZ_FINAL=''S''
				 
			   		 
    		    -- Cantidad de Integrantes
			    
			    IF @TIPO_CLIENTE_FINAL = ''F''			    
			    SET @CANTIDAD_INTEG=@CANTIDAD_INTEG+1
				 	   
	    		FETCH NEXT FROM EdadesIntegrantesCur INTO @NUMEROPERSONAREC,@TIPOPERSONAREG,@TITULARIDADREG,@EDADREC,@ESTADOCIVILREG;
	    			   
		    	END
		   
		 CLOSE EdadesIntegrantesCur;
         
         DEALLOCATE EdadesIntegrantesCur;
         
        PRINT  @CANTIDAD_INTEG;
        PRINT  @MAYOR_EDAD_FINAL;
        PRINT  @MENOR_EMANCIPADO_FINAL;
        PRINT  @MENOR_AUTORIZ_FINAL;
        PRINT  @MENOR_ADOLE_FINAL;
        PRINT  @TIPO_CLIENTE_FINAL;
        
   
  SET NOCOUNT OFF;
END
')

