
EXECUTE('

UPDATE CI_CARGOS
SET DESCRIPCION = ''COMISION RECHAZO CHEQ AJUSTES''
WHERE ID_CARGO = 1455
--
UPDATE CI_CARGOS
SET DESCRIPCION = ''COMISION GESTIÓN CHEQ OTRO BCO AJUSTES''
WHERE ID_CARGO = 1456

')