
EXECUTE('
IF OBJECT_ID (''dbo.CLE_RECEPCION_CHEQUES_DEV'') IS NOT NULL
	DROP TABLE dbo.CLE_RECEPCION_CHEQUES_DEV
')

EXECUTE('
CREATE TABLE dbo.CLE_RECEPCION_CHEQUES_DEV
	(
	BANCO_GIRADO           NUMERIC (4) DEFAULT ((0)) NOT NULL,
	SUCURSAL_BANCO_GIRADO  NUMERIC (5) DEFAULT ((0)) NOT NULL,
	SERIE_DEL_CHEQUE       VARCHAR (6) DEFAULT ('' '') NOT NULL,
	IMPORTE_CHEQUE         NUMERIC (15,2) DEFAULT ((0)) NULL,
	CODIGO_RECHAZO         NUMERIC (3) DEFAULT ((0)) NULL,
	NUMERO_CHEQUE          NUMERIC (12) DEFAULT ((0)) NOT NULL,
	ESTADO_DEVOLUCION      NUMERIC (1) DEFAULT ((0)) NULL,
	CODIGO_CAMARA          NUMERIC (4) DEFAULT ((0)) NULL,
	TIPO_DOCUMENTO         VARCHAR (4) DEFAULT ('' '') NOT NULL,
	FECHA_ALTA             DATETIME NOT NULL,
	NUMERO_CUENTA_GIRADORA NUMERIC (12) DEFAULT ((0)) NOT NULL,
	TZ_LOCK                NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CLE_RECEPCION_CHEQUES_DE_01 PRIMARY KEY (NUMERO_CHEQUE,SERIE_DEL_CHEQUE,BANCO_GIRADO,FECHA_ALTA,SUCURSAL_BANCO_GIRADO,NUMERO_CUENTA_GIRADORA,TIPO_DOCUMENTO)
	)
')

