EXECUTE('
--------
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35184, '' '', 0, ''Fecha de alta'', ''Fecha de alta'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 230, ''FECHA_ALTA'', 0, NULL)
----
UPDATE INDICES
SET CAMPO4 = 35184
WHERE NUMERODEARCHIVO = 230 AND NUMERODEINDICE = 1
--------
')