
EXECUTE('

--DESCRIPTOR

INSERT INTO DESCRIPTORES
(TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES(35, 3420, NULL, ''Histórico caja forense'', 0, ''DJ_HISTORICO_INACTIVAS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'');


--CAMPOS

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34768, '' '', 0, ''Jts oid'', ''Jts oid'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3420, ''JTS_OID_SALDO'', 0, NULL);

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34769, '' '', 0, ''Cuenta'', ''Cuenta'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3420, ''CUENTA'', 0, NULL);

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34770, '' '', 0, ''Número de lote'', ''Número de lote'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3420, ''NRO_LOTE'', 0, NULL);

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34771, '' '', 0, ''Estado de cuenta'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3420, ''ESTADO_CTA'', 0, NULL);

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34772, '' '', 0, ''Fecha de alta'', ''Fecha de alta'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3420, ''FECHA_ALTA'', 0, NULL);

INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(34773, '' '', 0, ''Fecha de transferencia'', ''Fecha de transferencia'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3420, ''FECHA_TRANSFERENCIA'', 0, NULL);

--INDICE

INSERT INTO INDICES
(NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES(3420, 1, ''Indice primario'', 0, 34768, 34770, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--OPCION 

INSERT INTO OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(34335, ''E'', ''Reiniciar proceso pendiente'', ''R'', ''R'');



')