EXECUTE('
INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (30, 4907, NULL, ''Vista Cajas Sin Tesoros'', 0, ''VW_CAJ_CAJAS_SIN_TESORO'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')



INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49130, '' '', 0, ''Número de Caja'', ''Número de Caja'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''NRO_CAJA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49131, '' '', 0, ''Clave de Usuario'', ''Clave de Usuario'', 10, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''USUARIO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49132, '' '', 0, ''Nombre de Usuario'', ''Nombre de Usuario'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''NOMBRE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49133, '' '', 0, ''Estado'', ''Estado'', 7, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''ESTADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49134, '' '', 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49135, '' '', 0, ''Minifilial'', ''Minifilial'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''MINIFILIAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49136, '' '', 0, ''Iniciales'', ''Iniciales'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''INICIALES'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49137, '' '', 0, ''Descripcion'', ''Descripcion'', 45, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4907, ''DESCRIPCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49138, '' '', 0, ''Es Tesoro'', ''Es Tesoro'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4907, ''ESTESORO'', 0, NULL)



INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4907, 90842, ''Vista cajas sin tesoro'', '''', 0, ''49130R;49133;49131R;49132;49134R;49135I;'', NULL, NULL, NULL, 0)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4907, 1, NULL, 0, 49130, 49134, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)



INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49139, '' '', 0, ''Ayuda cajas sin tesoro'', ''Ayuda cajas sin tesoro'', 3, ''N'', 0, NULL, 0, 0, 0, 0, 0, 90842, 0, 0, ''Ayuda cajas sin tesoro'', 0, NULL)
')