EXECUTE('
DELETE FROM dbo.DICCIONARIO WHERE NUMERODECAMPO=45370

DELETE FROM dbo.OPCIONES WHERE NUMERODECAMPO = 45370

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45370, '' '', 0, ''Opciones Tipo Dom'', ''Opciones Tipo Dominio'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''Opciones Tipo Dom'', 0, NULL)

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45370, ''E'', ''Ex/Caja'', ''E'', ''E'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45370, ''E'', ''Jurisdicción'', ''J'', ''J'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45370, ''E'', ''No Aplica'', ''N'', ''N'')
')