EXECUTE('
UPDATE dbo.DESCRIPTORES
SET TITULO = 550
	, IDENTIFICACION = 4362
	, TIPODEARCHIVO = NULL
	, DESCRIPCION = ''CRE_SEGURO_VIDA_VOLUNTARIO''
	, GRUPODELMAPA = 0
	, NOMBREFISICO = ''CRE_SEGURO_VIDA_VOLUNTARIO''
	, TIPODEDBMS = ''D''
	, LARGODELREGISTRO = NULL
	, INICIALIZACIONDELREGISTRO = NULL
	, BASE = ''Top/Clientes''
	, SELECCION = NULL
	, ACEPTA_MOVS_DIFERIDO = ''N''
WHERE TITULO = 550 AND IDENTIFICACION = 4362


INSERT INTO dbo.ME_CRIT_INDIC (TZ_LOCK, COD_ITEM, TIPO, NOMBRE)
VALUES (0, 22, 3, ''Los seguros no cubren el monto de la solicitud'')

INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (6820, 6119, ''Sub Ope Actualiza JTS Seguro Vida Voluntario'', ''Sub Ope Actualiza JTS Seguro Vida Voluntario'', ''6119'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

')