EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (59001, '' '', 0, ''Alfa de 25'', NULL, 25, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Alfa25'', 0, NULL)

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 49553, ''VW_SEGUROS_SALDO_VIDA'', '''', 0, ''50033;28201;623;59001;740;45278;50999;99345;'', ''Aseguradora;Nombre Aseguradora;Numero de Poliza;Tipo de Seguro;Monto de Seguro;Tasa de Seguro;Fecha de Vencimiento;Jts Asistencia;'', ''TOP/CLIENTES'', ''VW_SEGUROS_SALDO_VIDA'', 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (91069, '' '', 0, ''Ayuda Seguros Saldo Vida'', ''Seguros Saldo Vida'', 50, ''A'', 0, NULL, 0, 0, 0, 0, 0, 49553, 0, 0, ''AYUDA SSV'', 0, NULL)
')
