EXECUTE('

UPDATE DICCIONARIO
SET TABLADEVALIDACION=214 
WHERE NUMERODECAMPO=1447;


UPDATE DICCIONARIO
SET TABLADEVALIDACION=214
WHERE NUMERODECAMPO=1387;


INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36081, '' '', 0, ''Opciones Cons - Mod'', ''Opciones cons Mod'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''cmpo_opc_con_mod'', 0, NULL);

INSERT INTO OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(36081, ''E'', ''Consulta'', ''C'', ''C'');


INSERT INTO OPCIONES
(NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES(36081, ''E'', ''Modificación'', ''M'', ''M'');




')