execute('
DELETE FROM ITF_MASTER_PARAMETROS WHERE CODIGO=483
INSERT INTO dbo.ITF_MASTER_PARAMETROS (CODIGO, CODIGO_INTERFACE, FUNCIONALIDAD, ALFA_1, ALFA_2, ALFA_3, NUMERICO_1, NUMERICO_2, FECHA, IMPORTE_1, IMPORTE_2, TZ_LOCK)
VALUES (483, 0, ''TRANSF. BEE EVENTO'', ''J'', ''2'', ''CUIT'', 2700, 0, NULL, 0, 0, 0)
');
