


-- Patch_NUPAGSEGUR_155

alter table DSP_GRUPOS_CUENTAS add USO_SOB_CREDITO_PA_FUNDS_TRANS NUMERIC(1) default (1);

alter table DSP_GRUPOS_CUENTAS add USO_SOB_DEBITO_PA_FUNDS_TRANS NUMERIC(1) default (1);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210217_3',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VUEFHU0VHVVJfMTU1Cg0KYWx0ZXIgdGFibGUgRFNQX0dSVVBPU19DVUVO
VEFTIGFkZCBVU09fU09CX0NSRURJVE9fUEFfRlVORFNfVFJBTlMgTlVNRVJJQygxKSBkZWZhdWx0
ICgxKTsKCmFsdGVyIHRhYmxlIERTUF9HUlVQT1NfQ1VFTlRBUyBhZGQgVVNPX1NPQl9ERUJJVE9f
UEFfRlVORFNfVFJBTlMgTlVNRVJJQygxKSBkZWZhdWx0ICgxKTsKDQoKCg0K', NULL, 0);
