


-- Parche_NUSICREDBR_2269

-- Actualizando valor por Default al campo con concepto 940
-- HM begin sentence
BEGIN
 DECLARE @campo AS varchar (30);

DECLARE @campo1 AS varchar (30);

DECLARE @campo2 AS varchar (15);

DECLARE @SQL AS NVARCHAR (500);

DECLARE @nameConstraint AS NVARCHAR (128);

DECLARE @ParmDefinition nvarchar(500);

SET @campo=(SELECT CAMPO  FROM DICCIONARIO WHERE CONCEPTO=940);

SET @campo1 = ''''+@campo+'''';

SET @campo2=(SELECT CAST(NUMERODECAMPO AS INT)  FROM DICCIONARIO WHERE CONCEPTO=940);

SET @ParmDefinition = N'@nameConstraintOUT varchar(128) OUTPUT';

SET @SQL= 'SELECT  @nameConstraintOUT=d.name FROM sys.default_constraints AS d INNER JOIN sys.columns AS c ON d.parent_object_id = c.object_id AND d.parent_column_id = c.column_id WHERE c.name =' + @campo1 +' AND d.parent_object_id = OBJECT_ID(N''SALDOS'', N''U'') ';

exec sp_executesql @SQL, @ParmDefinition, @nameConstraintOUT=@nameConstraint OUTPUT;

SET @SQL= 'ALTER TABLE SALDOS DROP CONSTRAINT ' + @nameConstraint;

exec sp_executesql @SQL;

SET @SQL= 'ALTER TABLE SALDOS add DEFAULT (''N'') FOR ' + @campo;

exec sp_executesql @SQL;

SET @SQL= 'UPDATE OPCIONES SET DESCRIPCION = ''No Permite, NO usa cupo Sobreg'' WHERE NUMERODECAMPO = ' + @campo2 + ' AND OPCIONINTERNA = ''N''';

exec sp_executesql @SQL;

SET @SQL= 'INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA) VALUES (' + @campo2  + ' , ''E'', ''No Permite, SI usa cupo Sobreg'', ''L'', ''L'')';

exec sp_executesql @SQL;

DECLARE @campo4 AS varchar (30);

DECLARE @SQL2 AS NVARCHAR (100);

SET @campo4=(SELECT CAMPO  FROM DICCIONARIO WHERE CONCEPTO=615);

SET @SQL2= 'UPDATE SALDOS SET ' + @campo + ' = ''N''' + 'WHERE ' + @campo + ' = ' + ''' '' AND ' + @campo4 + ' In (5,6)';

exec sp_executesql @SQL2;

END;

-- HM end sentence;




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210311_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVVNJQ1JFREJSXzIyNjkKDQotLSBBY3R1YWxpemFuZG8gdmFsb3IgcG9y
IERlZmF1bHQgYWwgY2FtcG8gY29uIGNvbmNlcHRvIDk0MA0KLS0gSE0gYmVnaW4gc2VudGVuY2UK
QkVHSU4KIERFQ0xBUkUgQGNhbXBvIEFTIHZhcmNoYXIgKDMwKTsKCkRFQ0xBUkUgQGNhbXBvMSBB
UyB2YXJjaGFyICgzMCk7CgpERUNMQVJFIEBjYW1wbzIgQVMgdmFyY2hhciAoMTUpOwoKREVDTEFS
RSBAU1FMIEFTIE5WQVJDSEFSICg1MDApOwoKREVDTEFSRSBAbmFtZUNvbnN0cmFpbnQgQVMgTlZB
UkNIQVIgKDEyOCk7CgpERUNMQVJFIEBQYXJtRGVmaW5pdGlvbiBudmFyY2hhcig1MDApOwoKU0VU
IEBjYW1wbz0oU0VMRUNUIENBTVBPICBGUk9NIERJQ0NJT05BUklPIFdIRVJFIENPTkNFUFRPPTk0
MCk7CgpTRVQgQGNhbXBvMSA9ICcnJycrQGNhbXBvKycnJyc7CgpTRVQgQGNhbXBvMj0oU0VMRUNU
IENBU1QoTlVNRVJPREVDQU1QTyBBUyBJTlQpICBGUk9NIERJQ0NJT05BUklPIFdIRVJFIENPTkNF
UFRPPTk0MCk7CgpTRVQgQFBhcm1EZWZpbml0aW9uID0gTidAbmFtZUNvbnN0cmFpbnRPVVQgdmFy
Y2hhcigxMjgpIE9VVFBVVCc7CgpTRVQgQFNRTD0gJ1NFTEVDVCAgQG5hbWVDb25zdHJhaW50T1VU
PWQubmFtZSBGUk9NIHN5cy5kZWZhdWx0X2NvbnN0cmFpbnRzIEFTIGQgSU5ORVIgSk9JTiBzeXMu
Y29sdW1ucyBBUyBjIE9OIGQucGFyZW50X29iamVjdF9pZCA9IGMub2JqZWN0X2lkIEFORCBkLnBh
cmVudF9jb2x1bW5faWQgPSBjLmNvbHVtbl9pZCBXSEVSRSBjLm5hbWUgPScgKyBAY2FtcG8xICsn
IEFORCBkLnBhcmVudF9vYmplY3RfaWQgPSBPQkpFQ1RfSUQoTicnU0FMRE9TJycsIE4nJ1UnJykg
JzsKCmV4ZWMgc3BfZXhlY3V0ZXNxbCBAU1FMLCBAUGFybURlZmluaXRpb24sIEBuYW1lQ29uc3Ry
YWludE9VVD1AbmFtZUNvbnN0cmFpbnQgT1VUUFVUOwoKU0VUIEBTUUw9ICdBTFRFUiBUQUJMRSBT
QUxET1MgRFJPUCBDT05TVFJBSU5UICcgKyBAbmFtZUNvbnN0cmFpbnQ7CgpleGVjIHNwX2V4ZWN1
dGVzcWwgQFNRTDsKClNFVCBAU1FMPSAnQUxURVIgVEFCTEUgU0FMRE9TIGFkZCBERUZBVUxUICgn
J04nJykgRk9SICcgKyBAY2FtcG87CgpleGVjIHNwX2V4ZWN1dGVzcWwgQFNRTDsKClNFVCBAU1FM
PSAnVVBEQVRFIE9QQ0lPTkVTIFNFVCBERVNDUklQQ0lPTiA9ICcnTm8gUGVybWl0ZSwgTk8gdXNh
IGN1cG8gU29icmVnJycgV0hFUkUgTlVNRVJPREVDQU1QTyA9ICcgKyBAY2FtcG8yICsgJyBBTkQg
T1BDSU9OSU5URVJOQSA9ICcnTicnJzsKCmV4ZWMgc3BfZXhlY3V0ZXNxbCBAU1FMOwoKU0VUIEBT
UUw9ICdJTlNFUlQgSU5UTyBPUENJT05FUyAoTlVNRVJPREVDQU1QTywgSURJT01BLCBERVNDUklQ
Q0lPTiwgT1BDSU9OSU5URVJOQSwgT1BDSU9OREVQQU5UQUxMQSkgVkFMVUVTICgnICsgQGNhbXBv
MiAgKyAnICwgJydFJycsICcnTm8gUGVybWl0ZSwgU0kgdXNhIGN1cG8gU29icmVnJycsICcnTCcn
LCAnJ0wnJyknOwoKZXhlYyBzcF9leGVjdXRlc3FsIEBTUUw7CgpERUNMQVJFIEBjYW1wbzQgQVMg
dmFyY2hhciAoMzApOwoKREVDTEFSRSBAU1FMMiBBUyBOVkFSQ0hBUiAoMTAwKTsKClNFVCBAY2Ft
cG80PShTRUxFQ1QgQ0FNUE8gIEZST00gRElDQ0lPTkFSSU8gV0hFUkUgQ09OQ0VQVE89NjE1KTsK
ClNFVCBAU1FMMj0gJ1VQREFURSBTQUxET1MgU0VUICcgKyBAY2FtcG8gKyAnID0gJydOJycnICsg
J1dIRVJFICcgKyBAY2FtcG8gKyAnID0gJyArICcnJyAnJyBBTkQgJyArIEBjYW1wbzQgKyAnIElu
ICg1LDYpJzsKCmV4ZWMgc3BfZXhlY3V0ZXNxbCBAU1FMMjsKCkVORDsKCi0tIEhNIGVuZCBzZW50
ZW5jZTsKDQoKCg0K', NULL, 0);
