EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35999, '' '', 0, ''Aceptar / Rechazar Solicitud'', ''Aceptar / Rechazar Solicitud'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, ''C35999'', 0, NULL)


INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35999, ''E'', ''Aceptar'', ''A'', ''A'')

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35999, ''E'', ''Rechazar'', ''R'', ''R'')
')


