execute('
ALTER VIEW VW_CARGO_SALDOS_INMOVILIZADOS_DPF 
(
   JTS_OID_SALDO,
   MONEDA,
   SALDO_ACTUAL,
   DIAS_NOTIFICADO,
   MESES_NOTIFICADO,
   DIAS_PARAMETRO,
   USF,
   FECHA_INMOVILIZACION)
AS 

SELECT S.JTS_OID, 
	S.MONEDA, 
	S.C1604 + S.C1683 + S.C1605 + S.C2627 + S.C50107 AS SALDOACTUAL, 
	DATEDIFF(day,SI.FECHA_INMOVILIZACION, (SELECT P.FECHAPROCESO FROM PARAMETROS P)) AS DIASNOTIFICADO,
	DATEDIFF(month,SI.FECHA_INMOVILIZACION, (SELECT P.FECHAPROCESO FROM PARAMETROS P)) AS MESESNOTIFICADO,
	(SELECT PG.NUMERICO FROM PARAMETROSGENERALES PG WHERE PG.CODIGO = 223 AND PG.TZ_LOCK = 0),
	C.USF,
	SI.FECHA_INMOVILIZACION
FROM SALDOS S INNER JOIN DPF_SALDOS_INMOVILIZADOS SI ON S.JTS_OID = SI.JTS_OID_SALDO_DPF 
	INNER JOIN CLI_CLIENTES C ON C.CODIGOCLIENTE = S.C1803
WHERE S.C1785 = 4
AND ((S.TZ_LOCK < 300000000000000 OR S.TZ_LOCK >= 400000000000000) AND (S.TZ_LOCK < 100000000000000 OR S.TZ_LOCK >= 200000000000000))
AND SI.TZ_LOCK = 0
AND C.TZ_LOCK = 0;');

execute('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34574, NULL, 0, ''Fecha Inmovilizacion'', ''Fecha Inmovilizacion'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3438, ''FECHA_INMOVILIZACION'', 0, NULL);
');

