EXECUTE('
CREATE TABLE dbo.ITF_CUENTAS_BEE_AUX
	(
	ID            INT IDENTITY NOT NULL,
	LINEA         VARCHAR (250),
	TIPO_REGISTRO VARCHAR (1),
	ESTADO        VARCHAR (1) DEFAULT (''P''),
	DESC_ERROR    VARCHAR (1000),
	CUIT          NUMERIC (13),
	TIPOCUENTA    VARCHAR (2),
	NROCUENTA     NUMERIC (19),
	JTS_OID       NUMERIC (10)
	)

CREATE INDEX idx_ITF_CUENTAS_BEE_AUX_lookup
	ON dbo.ITF_CUENTAS_BEE_AUX (ID)
')
