EXECUTE('

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (4586, '' '', 0, ''Nro. de Caja'', ''Nro. de Caja'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 990, ''NRODECAJA'', 0, NULL)

')