EXECUTE('
IF OBJECT_ID (''dbo.SOS_PERFILDOC'') IS NOT NULL
	DROP TABLE dbo.SOS_PERFILDOC
')

EXECUTE('
CREATE TABLE dbo.SOS_PERFILDOC
	(
	EMPRESA               VARCHAR (4),
	FECHADEINFORMACION    NUMERIC (8),
	IDENTTRIBUTARIATIPO   NUMERIC (4),
	IDENTTRIBUTARIANUMERO NUMERIC (11),
	MONTOPERFIL           NUMERIC (16,2),
	FECHAALTAPERFIL       NUMERIC (8),
	OBSERVACIONES         VARCHAR (50)
	)
')
