-- Modificar nombre de job en ITF_MASTER y parametros
update ITF_MASTER 
SET 
	P2_MODO = 'C', P2_TIPO = 'S', P2_CAPTION = ' ', P2_CONSTANTE = 'B'
WHERE ID = 35

-- Agregar evento
INSERT INTO EVENTOS (TZ_LOCK,ID_EVENTO,CANAL,SUB_CANAL) VALUES (0,136,N'7',N'150');

INSERT INTO EVENTOS_TRANSACCION (TZ_LOCK,CODIGO_TRANSACCION,ID_EVENTO,CONDICION,CAMPOS,PRIORIDAD,DESCRIPCION,TIPO_MAPEO,GRABAR_TABLA,ENVIAR_EN_REVERSA,ENABLE_OBJ_FORMAT) VALUES
	 (0,541,136,NULL,N'transactionId=760;ref=9503;loteId=93;cuit=339;convenio=621;resultado=4886;codError=622;descripcion=910;',2,N'DJP Recaudaciones Soporte',2,1,1,0);

-- Configuración transacción
INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION,CODIGO_INTERNO_MOV,CODIGO_TRANSACCION,TZ_LOCK) VALUES
	 (9918,136,541,0);

-- Configuración de operación topaz
INSERT INTO OPERACIONES (TITULO,IDENTIFICACION,NOMBRE,DESCRIPCION,MNEMOTECNICO,AUTORIZACION,FORMULARIOPRINCIPAL,PROXOPERACION,ESTADO,TZ_LOCK,COPIAS,SUBOPERACION,PERMITEBAJA,COMPORTAMIENTOENCIERRE,REQUIERECONTRASENA,PERMITECONCURRENTE,PERMITEESTADODIFERIDO,ICONO_TITULO,ESTILO) VALUES
	 (6800,9918,N'1.29.26 DJP-Recaudaciones',N'1.29.26 DJP-Recaudaciones - Caja Municipal',N'9918',N'N',NULL,NULL,N'P',0,NULL,0,N'S',N'N',N'N',N'N',N'N',NULL,0);

