EXECUTE('
IF OBJECT_ID (''CRE_LIMITE_GARANTIA'') IS NOT NULL
	DROP TABLE CRE_LIMITE_GARANTIA

CREATE TABLE CRE_LIMITE_GARANTIA
	(
	TZ_LOCK                   NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ID_LIMITE                 NUMERIC (12) DEFAULT ((0)) NOT NULL,
	TIPO                      VARCHAR (1) DEFAULT ('' '') NOT NULL,
	RIESGO                    NUMERIC (2) DEFAULT ((0)) NOT NULL,
	FAMILIA                   NUMERIC (12) DEFAULT ((0)) NOT NULL,
	MONEDA                    NUMERIC (4) DEFAULT ((0)) NOT NULL,
	PRODUCTO                  NUMERIC (5) NOT NULL,
	PAIS_GARANTIA             VARCHAR (15) DEFAULT ('' '') NOT NULL,
	TIPO_GARANTIA             NUMERIC (2) DEFAULT ((0)) NOT NULL,
	SUBTIPO_GARANTIA          NUMERIC (2) DEFAULT ((0)) NOT NULL,
	SUBCLASIFICACION_GARANTIA NUMERIC (2) DEFAULT ((0)) NOT NULL,
	VALOR_REALIZACION         NUMERIC (15,2) DEFAULT ((0)) NULL,
	CONDICIONANTE_DESEMBOLSO  VARCHAR (1) DEFAULT ('' '') NULL,
	DESC_TIPO_GARANTIA        VARCHAR (100) NULL,
	CONSTRAINT PK_CRE_LIMITE_GARANTIA PRIMARY KEY (ID_LIMITE,TIPO,RIESGO,FAMILIA,MONEDA,PRODUCTO,PAIS_GARANTIA,TIPO_GARANTIA,SUBTIPO_GARANTIA,SUBCLASIFICACION_GARANTIA)
	)
	
IF OBJECT_ID (''HISTORICO_CALIF_X_CLIENTE'') IS NOT NULL
	DROP TABLE HISTORICO_CALIF_X_CLIENTE

CREATE TABLE HISTORICO_CALIF_X_CLIENTE
	(
	CLIENTE                     NUMERIC (12) DEFAULT ((0)) NOT NULL,
	FECHA                       DATETIME NOT NULL,
	CALIFICACION_OBJETIVA       VARCHAR (2) DEFAULT ('' '') NULL,
	CALIFICACION_REESTRUCTURADA VARCHAR (2) DEFAULT ('' '') NULL,
	CALIFICACION_SUBJETIVA      VARCHAR (2) DEFAULT ('' '') NULL,
	CALIFICACION_SF             VARCHAR (2) DEFAULT ('' '') NULL,
	CALIFICACION_RESULTANTE     VARCHAR (2) DEFAULT ('' '') NULL,
	TIPO_RIESGO                 VARCHAR (2) DEFAULT ('' '') NULL,
	DIAS_ATRASO                 NUMERIC (6) DEFAULT ((0)) NULL,
	TZ_LOCK                     NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_HISTORICO_CALIF_X_CLIENTE_01 PRIMARY KEY (CLIENTE,FECHA)
	)

IF OBJECT_ID (''CRE_CAB_CASTIGOCARTERA'') IS NOT NULL
	DROP TABLE CRE_CAB_CASTIGOCARTERA

CREATE TABLE CRE_CAB_CASTIGOCARTERA
	(
	NUMERO_LISTA          NUMERIC (10) DEFAULT ((0)) NOT NULL,
	ESTADO                VARCHAR (1) DEFAULT ('' '') NULL,
	SUCURSAL_ALTA         NUMERIC (5) DEFAULT ((0)) NULL,
	USUARIO_ALTA          VARCHAR (10) DEFAULT ('' '') NULL,
	FECHA_ALTA            DATETIME NULL,
	HORA_ALTA             VARCHAR (8) DEFAULT ('' '') NULL,
	SUCURSAL_CONFIRMACION NUMERIC (5) DEFAULT ((0)) NULL,
	USUARIO_CONFIRMACION  VARCHAR (10) DEFAULT ('' '') NULL,
	FECHA_CONFIRMACION    DATETIME NULL,
	HORA_CONFIRMACION     VARCHAR (8) DEFAULT ('' '') NULL,
	COMENTARIO            VARCHAR (200) DEFAULT ('' '') NULL,
	TZ_LOCK               NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_CAB_CASTIGOCARTERA_01 PRIMARY KEY (NUMERO_LISTA)
	)


IF OBJECT_ID (''CRE_DET_CASTIGOCARTERA'') IS NOT NULL
	DROP TABLE CRE_DET_CASTIGOCARTERA

CREATE TABLE CRE_DET_CASTIGOCARTERA
	(
	NUMERO_LISTA NUMERIC (10) DEFAULT ((0)) NOT NULL,
	CLIENTE      NUMERIC (12) DEFAULT ((0)) NOT NULL,
	ESTADO       VARCHAR (1) DEFAULT ('' '') NULL,
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_DET_CASTIGOCARTERA_01 PRIMARY KEY (NUMERO_LISTA,CLIENTE)
	)


IF OBJECT_ID (''CRE_CAB_CESIONCARTERA'') IS NOT NULL
	DROP TABLE CRE_CAB_CESIONCARTERA

CREATE TABLE CRE_CAB_CESIONCARTERA
	(
	NUMERO_CESION         NUMERIC (10) DEFAULT ((0)) NOT NULL,
	CLIENTE               NUMERIC (12) NULL,
	CON_RECURSOS          VARCHAR (1) DEFAULT ('' '') NULL,
	TIPO_CESION           VARCHAR (1) DEFAULT ('' '') NULL,
	CUOTA_DESDE           NUMERIC (3) DEFAULT ((0)) NULL,
	CUOTA_HASTA           NUMERIC (3) DEFAULT ((0)) NULL,
	ESTADO                VARCHAR (1) DEFAULT ('' '') NULL,
	SUCURSAL_ALTA         NUMERIC (5) DEFAULT ((0)) NULL,
	USUARIO_ALTA          VARCHAR (10) DEFAULT ('' '') NULL,
	FECHA_ALTA            DATETIME NULL,
	HORA_ALTA             VARCHAR (8) DEFAULT ('' '') NULL,
	SUCURSAL_CONFIRMACION NUMERIC (5) DEFAULT ((0)) NULL,
	USUARIO_CONFIRMACION  VARCHAR (10) DEFAULT ('' '') NULL,
	FECHA_CONFIRMACION    DATETIME NULL,
	HORA_CONFIRMACION     VARCHAR (8) DEFAULT ('' '') NULL,
	COMENTARIO            VARCHAR (200) DEFAULT ('' '') NULL,
	TZ_LOCK               NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_CAB_CESIONCARTERA_01 PRIMARY KEY (NUMERO_CESION)
	)

IF OBJECT_ID (''CRE_DET_CESIONCARTERA'') IS NOT NULL
	DROP TABLE CRE_DET_CESIONCARTERA

CREATE TABLE CRE_DET_CESIONCARTERA
	(
	NUMERO_CESION      NUMERIC (10) DEFAULT ((0)) NOT NULL,
	JTS_OID_ASISTENCIA NUMERIC (10) DEFAULT ((0)) NOT NULL,
	ESTADO             VARCHAR (1) DEFAULT ('' '') NULL,
	TZ_LOCK            NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_DET_CESIONCARTERA_01 PRIMARY KEY (NUMERO_CESION,JTS_OID_ASISTENCIA)
	)



ALTER TABLE TOPESPRODUCTO ADD DIAS_AVISO_VENCIMIENTO NUMERIC(3)
ALTER TABLE TOPESPRODUCTO ADD PERIODO_COMISION NUMERIC(3)
ALTER TABLE TOPESPRODUCTO ADD MAIL_NBCH VARCHAR(40)
ALTER TABLE CRE_USUARIOS_CARGOS_PP DROP CONSTRAINT PK_CRE_USUARIOS_CARGOS_PP_01
ALTER TABLE CRE_USUARIOS_CARGOS_PP ALTER COLUMN CLAVE VARCHAR (10) NOT NULL
ALTER TABLE CRE_USUARIOS_CARGOS_PP ADD CONSTRAINT PK_CRE_USUARIOS_CARGOS_PP_01 PRIMARY KEY (CLAVE, CARGO)
ALTER TABLE CRE_PROD_CONVENIOS ALTER COLUMN CANT_CUOTA_MAXIMA NUMERIC(5,0)
ALTER TABLE CRE_SUBSIDIOS ADD TipoCuenta VARCHAR (1)
ALTER TABLE CRE_TIPOS_RIESGOS ADD APLICAENDOLARES VARCHAR(1) DEFAULT(''N'') NULL
ALTER TABLE CRE_RIESGOLIC ADD MONTODOL NUMERIC(15,2) DEFAULT(0) NULL
ALTER TABLE CRE_FAMILIALIC ADD MONTODOL NUMERIC(15,2) DEFAULT(0) NULL
ALTER TABLE CRE_PRODUCTOLIC ADD MONTODOL NUMERIC(15,2) DEFAULT(0) NULL
ALTER TABLE CRE_TIPO_TRAMITE_LEASING ADD DISTRIBUIDO_CUOTAS VARCHAR(1) DEFAULT ''S''
ALTER TABLE CRE_GASTOS_LEASING ADD COD_ASEGURADORA NUMERIC(12)
ALTER TABLE CRE_GASTOS_LEASING ADD TIPO_COBERTURA VARCHAR(1)
ALTER TABLE CRE_GASTOS_LEASING ADD NRO_POLIZA VARCHAR(12)
ALTER TABLE GASTOS_POR_CUOTA DROP CONSTRAINT PK_GASTOS_POR_CUOTA
ALTER TABLE GASTOS_POR_CUOTA ADD CONSTRAINT PK_GASTOS_POR_CUOTA PRIMARY KEY (SALDOS_JTS_OID, NUMERO_CUOTA, SECUENCIAL, CARGO_ID)
')