


-- Patch_NUSICREDBR_2619

-- Se agregan atributos a Plan de Pagos, para guardar el IPF de cada Cuota.
ALTER TABLE PLANPAGOS ADD C2305_IPF NUMERIC (15,2) DEFAULT (0) WITH VALUES;

ALTER TABLE PLANPAGOS ADD C2310_IPF NUMERIC (15,2) DEFAULT (0) WITH VALUES;

-- Actualización de Conceptos y Diccionario
INSERT INTO CONCEPTOS (CODIGO, DESCRIPCION, CAMPOV25)
VALUES (2760, 'IPF plan de pagos', 0);

INSERT INTO CONCEPTOS (CODIGO, DESCRIPCION, CAMPOV25)
VALUES (2761, 'Saldo IPF Plan de Pagos', 0);

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3693, ' ', NULL, 'IPF', 'IPF', 15, 'N', 2, NULL, 0, 2760, NULL, NULL, NULL, NULL, 0, 22, 'C2305_IPF', 0, ' ');

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3694, ' ', NULL, 'Saldo IPF', 'Saldo IPF', 15, 'N', 2, NULL, 0, 2761, NULL, NULL, NULL, NULL, 0, 22, 'C2310_IPF', 0, ' ');




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20220829_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VU0lDUkVEQlJfMjYxOQoNCi0tIFNlIGFncmVnYW4gYXRyaWJ1dG9zIGEg
UGxhbiBkZSBQYWdvcywgcGFyYSBndWFyZGFyIGVsIElQRiBkZSBjYWRhIEN1b3RhLg0KQUxURVIg
VEFCTEUgUExBTlBBR09TIEFERCBDMjMwNV9JUEYgTlVNRVJJQyAoMTUsMikgREVGQVVMVCAoMCkg
V0lUSCBWQUxVRVM7CgpBTFRFUiBUQUJMRSBQTEFOUEFHT1MgQUREIEMyMzEwX0lQRiBOVU1FUklD
ICgxNSwyKSBERUZBVUxUICgwKSBXSVRIIFZBTFVFUzsKDQotLSBBY3R1YWxpemFjafNuIGRlIENv
bmNlcHRvcyB5IERpY2Npb25hcmlvDQpJTlNFUlQgSU5UTyBDT05DRVBUT1MgKENPRElHTywgREVT
Q1JJUENJT04sIENBTVBPVjI1KQpWQUxVRVMgKDI3NjAsICdJUEYgcGxhbiBkZSBwYWdvcycsIDAp
OwoKSU5TRVJUIElOVE8gQ09OQ0VQVE9TIChDT0RJR08sIERFU0NSSVBDSU9OLCBDQU1QT1YyNSkK
VkFMVUVTICgyNzYxLCAnU2FsZG8gSVBGIFBsYW4gZGUgUGFnb3MnLCAwKTsKCklOU0VSVCBJTlRP
IERJQ0NJT05BUklPIChOVU1FUk9ERUNBTVBPLCBVU09ERUxDQU1QTywgUkVGRVJFTkNJQSwgREVT
Q1JJUENJT04sIFBST01QVCwgTEFSR08sIFRJUE9ERUNBTVBPLCBERUNJTUFMRVMsIEVESUNJT04s
IENPTlRBQklMSVpBLCBDT05DRVBUTywgQ0FMQ1VMTywgVkFMSURBQ0lPTiwgVEFCTEFERVZBTElE
QUNJT04sIFRBQkxBREVBWVVEQSwgT1BDSU9ORVMsIFRBQkxBLCBDQU1QTywgQkFTSUNPLCBNQVND
QVJBKQpWQUxVRVMgKDM2OTMsICcgJywgTlVMTCwgJ0lQRicsICdJUEYnLCAxNSwgJ04nLCAyLCBO
VUxMLCAwLCAyNzYwLCBOVUxMLCBOVUxMLCBOVUxMLCBOVUxMLCAwLCAyMiwgJ0MyMzA1X0lQRics
IDAsICcgJyk7CgpJTlNFUlQgSU5UTyBESUNDSU9OQVJJTyAoTlVNRVJPREVDQU1QTywgVVNPREVM
Q0FNUE8sIFJFRkVSRU5DSUEsIERFU0NSSVBDSU9OLCBQUk9NUFQsIExBUkdPLCBUSVBPREVDQU1Q
TywgREVDSU1BTEVTLCBFRElDSU9OLCBDT05UQUJJTElaQSwgQ09OQ0VQVE8sIENBTENVTE8sIFZB
TElEQUNJT04sIFRBQkxBREVWQUxJREFDSU9OLCBUQUJMQURFQVlVREEsIE9QQ0lPTkVTLCBUQUJM
QSwgQ0FNUE8sIEJBU0lDTywgTUFTQ0FSQSkKVkFMVUVTICgzNjk0LCAnICcsIE5VTEwsICdTYWxk
byBJUEYnLCAnU2FsZG8gSVBGJywgMTUsICdOJywgMiwgTlVMTCwgMCwgMjc2MSwgTlVMTCwgTlVM
TCwgTlVMTCwgTlVMTCwgMCwgMjIsICdDMjMxMF9JUEYnLCAwLCAnICcpOwoNCgoKDQo=', NULL, 0);
