EXECUTE('
IF OBJECT_ID (''dbo.CRE_TAM_EMP_PERS'') IS NOT NULL
	DROP TABLE dbo.CRE_TAM_EMP_PERS
')

EXECUTE('
CREATE TABLE dbo.CRE_TAM_EMP_PERS
	(
	SECTOR              NUMERIC (5) DEFAULT ((0)) NOT NULL,
	PERSONALLIM         NUMERIC (5) DEFAULT ((0)),
	TAMANIO             VARCHAR (1) DEFAULT ('' '') NOT NULL,
	TZ_LOCK             NUMERIC (15) DEFAULT ((0)) NOT NULL,
	FECHA_VIGENCIA      DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CONSTRAINT PK_CRE_TAM_EMP_PERS_01 PRIMARY KEY (SECTOR, TAMANIO)
	)
')