--CODIGO_TRANSACCIONES

EXECUTE('       
IF EXISTS (SELECT * FROM CODIGO_TRANSACCIONES WHERE CODIGO_OPERACION = 8605 AND CODIGO_INTERNO_MOV = 6)
BEGIN

 DELETE FROM CODIGO_TRANSACCIONES WHERE CODIGO_OPERACION = 8605 AND CODIGO_INTERNO_MOV = 6;
 
   INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
   VALUES (8605, 6, 106, 0)
   
END
ELSE
BEGIN

    INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
    VALUES (8605, 6, 106, 0)
END
')
