EXECUTE('
-----------------------------------
--UPDATE LARGO DE CAMPOS PRODUCTO--
-----------------------------------
UPDATE DICCIONARIO
SET LARGO = 5
WHERE NUMERODECAMPO = 1079
--
UPDATE DICCIONARIO
SET LARGO = 5
WHERE NUMERODECAMPO = 8903
--
UPDATE DICCIONARIO
SET LARGO = 5
WHERE NUMERODECAMPO = 34674
----
')