EXECUTE('
INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (6650, 6893, ''Certificados Emergencia Sanita'', ''J'', 0, NULL, 0, 0, 0, ''N'')

INSERT INTO dbo.REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (6893, 1, NULL, 0, 0, 1)
')