EXECUTE('
CREATE OR ALTER PROCEDURE [dbo].[SP_ITF_SOS_OPERACIONES]
	@Fecha VARCHAR(8)
AS
BEGIN

--Limpiamos por si hay reproceso
DELETE FROM SOS_MOVS_HISTORICOS WHERE convert(VARCHAR,FECHADEINFORMACION) = @Fecha;


INSERT INTO SOS_MOVS_HISTORICOS(EMPRESA, FECHADEINFORMACION, NUMERODECUENTA, NUMERODEOPERACION, CLASEDECUENTA, TIPODECUENTAUOPERACION,
	SUCURSALSISCEN, SUCURSALINTERNA, FECHADELAOPERACION, MONTOPESOS, ESPECIETRANSADACANTIDAD,
	ESPECIETRANSADATIPO, BANCOCORRESPONSALSWIFT, BENEFICIARIOORDENANTEDELEXTE, PAISDELBENEFICIARIOORDENANTE, DATOSADICIONALES,
	FECHAALTA, CODIGOSTOPAZ, COTIZACION, REVERSADA, OPER_ID_BIC_SWIFT, RTE_OPE_FON_CUIT_CUIL_CDI,
	RTE_OPE_FON_TIPO_PERSONA, RTE_OPE_FON_DENOMINACION, RTE_OPE_FON_APELLIDOS, RTE_OPE_FON_NOMBRES, RTE_OPE_FON_TIPODOC,
	RTE_OPE_FON_NUMDOC, RTE_TIT_FON_CUIT_CUIL_CDI, RTE_TIT_FON_TIPO_PERSONA, RTE_TIT_FON_DENOMINACION, RTE_TIT_FON_APELLIDOS,
	RTE_TIT_FON_NOMBRES, RTE_TIT_FON_TIPODOC, RTE_TIT_FON_NUMDOC, RTI_TIPOPERSONA, RTI_TIPOOPERACION_COMEX, 
	FECHAAPERTURACUENTA, CUENTACLIENTE, SUCURSALSISCENCTA,
	REL_FON_TIT, REL_PRO_TIT, REL_FON_OPER, REL_PRO_OPER)
SELECT  Z.*, 
--38
LEFT((CASE WHEN LTRIM(Z.RTE_OPE_FON_CUIT_CUIL_CDI) = '''' THEN '''' ELSE ''Titular'' END), 30) AS REL_FON_TIT,
--39
LEFT((CASE WHEN LTRIM(Z.RTE_OPE_FON_CUIT_CUIL_CDI) = '''' THEN '''' ELSE ''SI'' END), 30) AS REL_PRO_TIT,
--40
LEFT((CASE WHEN LTRIM(Z.RTE_OPE_FON_CUIT_CUIL_CDI) = '''' THEN '''' ELSE ''Operador'' END), 30) AS REL_FON_OPER,
--41
LEFT((CASE WHEN LTRIM(Z.RTE_OPE_FON_CUIT_CUIL_CDI) = '''' THEN '''' ELSE ''SI'' END), 30) AS REL_PRO_OPER

FROM(
SELECT
--1
311 AS EMPRESA, 
--2
CONVERT(VARCHAR,mov.fechaproceso,112) AS FECHADEINFORMACION,
--3
CONCAT(RIGHT(''0''+CONVERT(VARCHAR,mov.SUCURSAL),2), sos.Subsistema, CONVERT(VARCHAR,mov.CUENTA)) AS NUMERODECUENTA,
--4
(CASE WHEN sos.Subsistema IN (''CA'', ''CC'') THEN LEFT(concat(mov.ASIENTO, CONVERT(VARCHAR,mov.FECHAPROCESO,112), mov.SUCURSAL, mov.ORDINAL),22) ELSE '''' END) AS NUMERODEOPERACION,
--5
LEFT(sos.Subsistema,3) AS CLASEDECUENTA,
--6
(SELECT t.TipOperacion FROM SOS_TRANSACCIONES t WHERE t.CodTransaccion = mov.COD_TRANSACCION)  AS TIPODECUENTAUOPERACION,
--7
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,suc.SucursalBCRA) END) AS SUCURSALSISCEN,
--8
(CASE WHEN sos.Subsistema = ''ME'' THEN ''0'' ELSE CONVERT(VARCHAR,mov.SUCURSAL) END) AS SUCURSALINTERNA,
--9
CONVERT(VARCHAR,mov.FECHAPROCESO,112) AS FECHADELAOPERACION,
--10
(CASE WHEN mov.MONEDA = 1 THEN (CASE WHEN mov.OPERACION = 8620 THEN (select dpf.IMPORTE_MN from SOLICAPERTURADPF dpf where dpf.CUENTA = mov.CUENTA AND dpf.OPERACION = MOV.OPERACION_CUENTA) ELSE mov.CAPITALREALIZADO END) ELSE 0 END) AS MONTOPESOS, --PENDIENTE
--11
(CASE WHEN mov.MONEDA <> 1 THEN (CASE WHEN mov.OPERACION = 8620 THEN (select dpf.IMPORTE_MN from SOLICAPERTURADPF dpf where dpf.CUENTA = mov.CUENTA AND dpf.OPERACION = MOV.OPERACION_CUENTA) ELSE mov.CAPITALREALIZADO END) ELSE 0 END) AS ESPECIETRANSADACANTIDAD, --PENDIENTE
--12
LEFT((SELECT m.C6402 FROM MONEDAS m WHERE m.C6399 = (CASE WHEN mov.MONEDA IN (988,999) THEN 1 ELSE mov.MONEDA END)),10) AS ESPECIETRANSADATIPO,
--13
'''' AS BANCOCORRESPONSALSWIFT,
--13
'''' AS BENEFICIARIOORDENANTEDELEXTE,
--15
'''' AS PAISDELBENEFICIARIOORDENANTE,
--16
'''' AS DATOSADICIONALES, --PENDIENTE
--17
CONVERT(VARCHAR, mov.FECHAVALOR,112) AS FECHAALTA, --PENDIENTE
--18
(CASE WHEN sos.Subsistema IN (''CC'',''CA'')
  THEN CONVERT(VARCHAR,mov.COD_TRANSACCION) ELSE '''' END) AS CODIGOSTOPAZ,
--19
(CASE WHEN mov.MONEDA = 1 THEN 0 ELSE (CASE WHEN sos.SubSistema IN (''AC'',''CC'',''TC'',''ME'',''TT'') THEN (SELECT TipC.TIPO_CAMBIO_OFICIAL FROM HISTORICOTIPOSCAMBIO TipC WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO) 
  WHEN sos.SubSistema IN (''PR'',''PF'') THEN (SELECT CASE WHEN mov.OPERACION = 3015 THEN TipC.TIPO_CAMBIO_COMPRA 
  													   WHEN mov.OPERACION = 3016 THEN TipC.TIPO_CAMBIO_VENTA END
  										   FROM HISTORICOTIPOSCAMBIO TipC WHERE TipC.FECHA_COTIZACION = mov.FECHAPROCESO)
  ELSE 0 END) END) AS COTIZACION, --PENDIENTE
--20
ISNULL((SELECT (CASE WHEN asi.ESTADO = 42 THEN ''SI'' ELSE ''NO'' END) FROM ASIENTOS asi 
 WHERE asi.FECHAPROCESO = mov.FECHAPROCESO AND asi.ASIENTO = mov.ASIENTO AND asi.SUCURSAL = mov.SUCURSAL),''NO'') AS REVERSADA,
--21
'''' AS OPER_ID_BIC_SWIFT,
--22
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT CONVERT(VARCHAR,vmov.NRO_DOC_I) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),11) AS RTE_OPE_FON_CUIT_CUIL_CDI,
--23
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT (CASE WHEN vmov.TIPO_PERSONA_I = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),2) AS RTE_OPE_FON_TIPO_PERSONA,
--24
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_I,'' '', vmov.NOMBRE_I) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),100) AS RTE_OPE_FON_DENOMINACION,
--25
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_I,'' '', vmov.NOMBRE_I) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),50)  AS RTE_OPE_FON_APELLIDOS,
--26
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_I,'' '', vmov.NOMBRE_I) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),50) AS RTE_OPE_FON_NOMBRES,
--27
/*LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 THEN (SELECT vmov.TIPO_DOC_I FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),5)*/ '''' AS RTE_OPE_FON_TIPODOC,
--28
/*LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 THEN (SELECT CONVERT(VARCHAR,vmov.NRO_DOC_I) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),10)*/''''  AS RTE_OPE_FON_NUMDOC,
--29
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT CONVERT(VARCHAR,vmov.NRO_DOC_M) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),11) AS RTE_TIT_FON_CUIT_CUIL_CDI,
--30
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT (CASE WHEN vmov.TIPO_PERSONA_M = ''F'' THEN ''PF'' WHEN vmov.TIPO_PERSONA_I = ''J'' THEN ''PJ'' END) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),2) AS RTE_TIT_FON_TIPO_PERSONA,
--31
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_M,'' '', vmov.NOMBRE_M) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),100) AS RTE_TIT_FON_DENOMINACION,
--32
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_M,'' '', vmov.NOMBRE_M) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),50) AS RTE_TIT_FON_APELLIDOS,
--33
LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 AND mov.COD_TRANSACCION IN (1,3) THEN (SELECT concat(vmov.APELLIDO_M,'' '', vmov.NOMBRE_M) FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),50) AS RTE_TIT_FON_NOMBRES,
--34
/*LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 THEN (SELECT vmov.TIPO_DOC_M FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),5)*/'''' AS RTE_TIT_FON_TIPODOC,
--35
/*LEFT((
CASE WHEN (SELECT COUNT(1) FROM SOS_TRANSACCIONES tra 
		   WHERE tra.Subsistema IN (''CC'',''CA'') 
		     AND tra.CodTransaccion = mov.COD_TRANSACCION 
		     AND tra.MtoMinimo <= mov.CAPITALREALIZADO
		     AND tra.MtoMinimo <> 0) > 0 THEN 
		         (SELECT (CASE WHEN vmov.TIPO_DOC_I = ''CUIL'' THEN SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),2,8)
		           ELSE SUBSTRING(CONVERT(VARCHAR,vmov.NRO_DOC_M),2,9) END) 
		          FROM VTA_CUMPLIMIENTO vmov WHERE vmov.SUCURSAL = mov.SUCURSAL
		       AND vmov.ASIENTO = mov.ASIENTO AND vmov.FECHA_PROCESO = mov.FECHAPROCESO)
	ELSE '''' END
),10)*/'''' AS RTE_TIT_FON_NUMDOC,
--36
'''' AS RTI_TIPOPERSONA,
--37
'''' AS RTI_TIPOOPERACION_COMEX,
--FECHAAPERTURACUENTA
(CASE WHEN sos.Subsistema = ''ME'' THEN CONVERT(NUMERIC,CONVERT(VARCHAR, mov.FECHAVALOR  ,112)) 
  	  WHEN EXISTS(SELECT 1 FROM TJC_MAESTRO_USUARIO WITH (NOLOCK) WHERE JTS_CUENTA_COBRO = sa.JTS_OID AND TZ_LOCK = 0)
	    THEN (SELECT CONVERT(NUMERIC,CONVERT(VARCHAR,A.FECHA_VTO ,112)) FROM TJC_SALDOS A WITH (NOLOCK) INNER JOIN TJC_MAESTRO_USUARIO B WITH (NOLOCK)
  				ON A.ADMINISTRADORA = B.ADMINISTRADORA AND A.USUARIO = B.USUARIO
           WHERE B.JTS_CUENTA_COBRO = sa.JTS_OID 
             AND PERIODO_DEUDA = (SELECT MAX(PERIODO_DEUDA) FROM TJC_SALDOS A WITH (NOLOCK) INNER JOIN TJC_MAESTRO_USUARIO B WITH (NOLOCK)
  				ON A.ADMINISTRADORA = B.ADMINISTRADORA AND A.USUARIO = B.USUARIO
           WHERE B.JTS_CUENTA_COBRO = sa.JTS_OID))
  
	  ELSE
	   CONVERT(NUMERIC,CONVERT(VARCHAR,sa.c1620 ,112)) END) AS FECHAAPERTURACUENTA,
--CLIENTE
sa.C1803 AS CUENTACLIENTE,
suc.SucursalBCRA AS SUCURSALSISCENCTA
--SELECT mov.*
FROM MOVIMIENTOS_CONTABLES mov WITH (NOLOCK)
  INNER JOIN SOS_TRANSACCIONES sos WITH (NOLOCK) ON sos.CodTransaccion = mov.COD_TRANSACCION
  INNER JOIN SOS_SUCURSALES suc WITH (NOLOCK) ON suc.Sucursal = mov.SUCURSAL
  INNER JOIN SALDOS sa WITH (NOLOCK) ON sa.JTS_OID = mov.SALDO_JTS_OID
WHERE mov.FECHAPROCESO = @Fecha
  AND mov.CLIENTE <> 0
  AND sos.TZ_LOCK = 0
  AND suc.TZ_LOCK = 0
  AND sa.TZ_LOCK = 0
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASFISICAS nat WITH(NOLOCK) ON p.NUMEROPERSONA = nat.NUMEROPERSONAFISICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND nat.SECTOR IN (6,7))
  AND NOT EXISTS(SELECT 1 FROM CLI_CLIENTES cli WITH(NOLOCK)
   					INNER JOIN CLI_ClientePersona p WITH(NOLOCK) ON p.CODIGOCLIENTE = cli.CODIGOCLIENTE
  					INNER JOIN CLI_PERSONASJURIDICAS jur WITH(NOLOCK) ON p.NUMEROPERSONA = jur.NUMEROPERSONAJURIDICA
  				 WHERE cli.CODIGOCLIENTE = sa.C1803
  				   AND jur.SECTOR IN (6,7))
) Z

END
')