Execute('DROP TABLE IF EXISTS dbo.ITF_LK_RM_SOLICITUD_TIMESTAMP;

CREATE TABLE dbo.ITF_LK_RM_SOLICITUD_TIMESTAMP (
	ID_SOLICITUD NUMERIC(15,0) NOT NULL PRIMARY KEY,
	TIME_STAMP NUMERIC(16,0) NOT NULL
)')