EXECUTE ('IF OBJECT_ID (''HISTORICO_CALIF_X_SALDO'') IS NOT NULL
	DROP TABLE HISTORICO_CALIF_X_SALDO')


EXECUTE ('CREATE TABLE HISTORICO_CALIF_X_SALDO
	(
	JTS_OID                     NUMERIC (10) DEFAULT ((0)) NOT NULL,
	FECHA                       DATETIME NOT NULL,
	CALIFICACION_OBJETIVA       VARCHAR (2) DEFAULT ('' '') NULL,
	CALIFICACION_REESTRUCTURADA VARCHAR (2) DEFAULT ('' '') NULL,
	TIPO_RIESGO                 VARCHAR (2) DEFAULT ('' '') NULL,
	DIAS_ATRASO                 NUMERIC (6) DEFAULT ((0)) NULL,
	TZ_LOCK                     NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_HISTORICO_CALIF_X_SALDO_01 PRIMARY KEY (JTS_OID,FECHA)
	)')



EXECUTE ('IF OBJECT_ID (''CRE_GASTOS_LEASING'') IS NOT NULL
	DROP TABLE CRE_GASTOS_LEASING')


EXECUTE ('CREATE TABLE CRE_GASTOS_LEASING
	(
	NUMERO_BIEN      NUMERIC (10) DEFAULT ((0)) NOT NULL,
	SALDOS_JTS_OID   NUMERIC (10) DEFAULT ((0)) NOT NULL,
	CODIGO_TRAMITE   NUMERIC (10) DEFAULT ((0)) NOT NULL,
	FECHA_INICIO     DATETIME NOT NULL,
	CLIENTE          NUMERIC (12) DEFAULT ((0)) NULL,
	TIPODOCUMENTO    VARCHAR (4) DEFAULT ('' '') NULL,
	NUMERODOCUMENTO  VARCHAR (20) DEFAULT ('' '') NULL,
	SUCURSAL         NUMERIC (5) DEFAULT ((0)) NULL,
	FECHA_FIN        DATETIME NULL,
	IMPORTE          NUMERIC (15,2) DEFAULT ((0)) NULL,
	FECHA_ALTA       DATETIME NULL,
	OBSERVACIONES    VARCHAR (200) DEFAULT ('' '') NULL,
	MUNICIPIO        VARCHAR (40) DEFAULT ('' '') NULL,
	FECHA_ENVIO_MAIL DATETIME NULL,
	GESTOR_ESCRIBANO NUMERIC (12) DEFAULT ((0)) NULL,
	NUMERO_FACTURA   VARCHAR (40) DEFAULT ('' '') NULL,
	TZ_LOCK          NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CRE_GASTOS_LEASING_01 PRIMARY KEY (NUMERO_BIEN,SALDOS_JTS_OID,CODIGO_TRAMITE,FECHA_INICIO)
	)')


EXECUTE ('IF OBJECT_ID (''VW_ASISTENCIAS_REFINANCIADO'') IS NOT NULL
	DROP VIEW VW_ASISTENCIAS_REFINANCIADO')


EXECUTE ('CREATE VIEW dbo.VW_ASISTENCIAS_REFINANCIADO (
	Sucursal, 
	"Nombre Sucursal", 
	Producto, 
	"Nombre Producto", 
	Cuenta, 
	Operacion, 
	Desglose, 
	Moneda, 
	"Capital Original", 
	"Saldo Capital", 
	Vencimiento, 
	"Capital Bonificado", 
	"Interes Bonificado", 
	"Moratorio Bonificado", 
	"Punitorio Bonificado", 
	"Gastos Bonificado", 
	"Numero Solicitud"
)
AS
	SELECT SUCURSAL AS "Sucursal", 
	NOMBRESUCURSAL AS "Nombre Sucursal", 
	PRODUCTO AS "Producto", 
	NOMBREPRODUCTO AS "Nombre Producto", 
	CUENTA AS "Cuenta", 
	OPERACION AS "Operacion", 
	DESGLOSE AS "Desglose", 
	MONEDA AS "Moneda", 
	MONTOORIGEN AS "Capital Original", 
	SALDO AS "Saldo Capital", 
	VENCIMIENTO AS "Vencimiento",
	CAPITAL_BONIFICADO AS "Capital Bonificado", 
	INTERES_BONIFICADO AS "Interes Bonificado", 
	MORATORIO_BONIFICADO AS "Moratorio Bonificado", 
	PUNITORIO_BONIFICADO AS "Punitorio Bonificado", 
	GASTOS_BONIFICADO AS "Gastos Bonificado", 
	NUMERO_SOLICITUD AS "Numero Solicitud"
	FROM VW_ASISTENCIAS cre
	INNER JOIN CRE_DET_REESTRUCTURA r ON cre.JTS_OID = r.JTS_OID_REESTRUCTURADA AND r.TZ_LOCK = 0')


EXECUTE ('ALTER TABLE CRE_GARANTIADOCUMENTOS ALTER COLUMN DSC_DOC VARCHAR(100)')