EXECUTE('
IF OBJECT_ID (''dbo.VW_COBRO_COMISIONES'') IS NOT NULL
	DROP VIEW dbo.VW_COBRO_COMISIONES
')

EXECUTE('

CREATE VIEW [dbo].[VW_COBRO_COMISIONES] 
AS
SELECT 
	CAST (com.ID_SOLICITUD AS NUMERIC (12)) AS ID_SOLICITUD,
	CAST (com.JTS_OID AS NUMERIC (12)) AS JTS_OID,
	CAST (ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS NUMERIC (12)) AS ID_REG
FROM 
	TJD_COBRO_COMISIONES AS com WITH(nolock)
		INNER JOIN saldos s WITH(nolock) ON s.JTS_OID=com.JTS_OID AND s.TZ_LOCK=0 AND S.C1651 <> ''1''
											AND S.C1679 = ''0'' AND S.C1728 <> ''I''
WHERE
	com.ESTADO=''P'' AND com.TZ_LOCK=0

')

