
Execute('
IF OBJECT_ID (''dbo.ITF_PADRON_IMPUESTOS'') IS NOT NULL
	DROP TABLE dbo.ITF_PADRON_IMPUESTOS
')

Execute('
CREATE TABLE dbo.ITF_PADRON_IMPUESTOS
	(
	ID              INT IDENTITY NOT NULL,
	CUIT            NUMERIC (11) NOT NULL,
	RAZON_SOCIAL    VARCHAR (44),
	PERIODO_ARCHIVO VARCHAR (6),
	ALICUOTA        NUMERIC (11, 7),
	CONSTRAINT PK_PADRON PRIMARY KEY (ID)
	)
')