
/****** Object:  View [dbo].[VW_SOLICITUD_CUENTAS_LINK]    Script Date: 24/02/2021 17:24:53 ******/
DROP VIEW [dbo].[VW_SOLICITUD_CUENTAS_LINK]
GO

/****** Object:  View [dbo].[VW_SOLICITUD_CUENTAS_LINK]    Script Date: 24/02/2021 17:24:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_SOLICITUD_CUENTAS_LINK] AS
		SELECT 
		TC.ID_SOLICITUD Id_Solicitud,
		TC.NRO_TARJETA Nro_Tarjeta,
		TC.NRO_CUENTA Nro_Cuenta,
		VS.NOMBRE_CUENTA Nombre_Cuenta, 
		TC.NUMERO_CUENTA_PBF Nro_Cuenta_PBF 
		FROM TJD_SOLICITUD_CUENTAS_LINK TC with(nolock) 
			INNER JOIN VTA_SALDOS VS with(nolock) 
				ON TC.NUMERO_CUENTA_PBF = VS.CTA_REDLINK 
GO


