EXECUTE ('

UPDATE dbo.DICCIONARIO
SET DESCRIPCION = ''SALDO_JTS_OID''
WHERE NUMERODECAMPO = 34959

UPDATE dbo.DICCIONARIO
SET PROMPT = ''SALDO_JTS_OID''
WHERE NUMERODECAMPO = 34959


UPDATE dbo.DICCIONARIO
SET CAMPO = ''SALDO_JTS_OID''
WHERE NUMERODECAMPO = 34959

')

