EXECUTE('
UPDATE PARAMETROSGENERALES SET ALFA = 237 WHERE CODIGO = 300

UPDATE PARAMETROSGENERALES SET ALFA = 110 WHERE CODIGO = 301

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50296, '' '', 0, ''Id_Referencia'', ''Id_Referencia'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''ID_REFERENCIA'', 0, NULL)
')