
EXECUTE('

ALTER VIEW VW_ASIENTOS
AS
SELECT
DISTINCT A.ASIENTO AS ASIENTO,
A.DESCRIPCION AS DESCRIPCION, 
A.FECHAPROCESO AS FECHAPROCESO,
CAST(CONVERT(date, A.HORAFIN) AS datetime) AS FECHA_FIN,
CAST(CONVERT(time, A.HORAFIN) AS VARCHAR(8)) AS HORA_FIN,
A.SUCURSAL AS SUCURSAL, 
M.SALDO_JTS_OID AS JTS_OID,
S.C1785 AS TIPO_PRODUCTO
FROM ASIENTOS A (nolock)

INNER JOIN MOVIMIENTOS_CONTABLES M (nolock) ON A.ASIENTO = M.ASIENTO AND A.FECHAPROCESO = M.FECHAPROCESO AND A.SUCURSAL = M.SUCURSAL
INNER JOIN SALDOS S (nolock) ON M.SALDO_JTS_OID = S.JTS_OID

WHERE 
A.ESTADO = 77
AND A.EXTORNO = 0
AND NOT EXISTS (SELECT * FROM ASIENTOS_EXTORNADOS AE (nolock) WHERE AE.SUCURSAL = A.SUCURSAL AND AE.FECHA_PROCESO = A.FECHAPROCESO AND AE.ASIENTO = A.ASIENTO)


')