EXECUTE
('
TRUNCATE TABLE CLE_CAMARAS_COMPENSADORAS 
')

EXECUTE('
INSERT INTO CLE_CAMARAS_COMPENSADORAS (CODIGO_DE_CAMARA, NOMBRE, DIRECCION, CENTRO_DE_CANJE, CORRESPONSAL_DE_CLEARING, SUCURSAL_CORRESPONSAL, TIPO_DE_CONFIRMACION, PLAZO_DE_CONFIRMACION, TIPO_DE_INTERFASE, TZ_LOCK, IMPORTE_TRUNCAMIENTO, CANJE_CON_IMAGENES, COD_CAMARA_BC_MN, COD_CAMARA_BC_ME)
VALUES (1, ''CAMARA FEDERAL UNIFORME'', ''Buenos Aires'', 0, NULL, 50, NULL, NULL, NULL, 0, 80000, ''S'', 0, 0)
')
