

EXECUTE('

UPDATE OPERACIONES
SET PERMITEBAJA=''N''
WHERE TITULO=2001 AND IDENTIFICACION=2041;


IF NOT EXISTS (SELECT * FROM DESCRIPTORES WHERE TITULO = 305 AND IDENTIFICACION = 3409)
BEGIN
INSERT INTO DESCRIPTORES
(TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES(305, 3409, NULL, ''Vista Asientos genérica'', 0, ''VW_ASIENTOS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'');
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36071)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36071, '' '', 0, ''Asiento'', ''Asiento'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''ASIENTO'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36072)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36072, '' '', 0, ''Descripcion'', ''Descripción'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''DESCRIPCION'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36073)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36073, '' '', 0, ''Fecha proceso'', ''Fecha proceso'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3409, ''FECHAPROCESO'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36074)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36074, '' '', 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''SUCURSAL'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36075)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36075, '' '', 0, ''jts oid'', ''Jts oid'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''JTS_OID'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36076)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36076, '' '', 0, ''Tipo de producto'', ''Tipo de producto'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''TIPO_PRODUCTO'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36079)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36079, '' '', 0, ''Hora fin'', ''Hora fin'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3409, ''HORA_FIN'', 0, NULL);
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36080)
BEGIN	
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36080, '' '', 0, ''Fecha fin'', ''Fecha fin'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3409, ''FECHA_FIN'', 0, NULL);
END


IF NOT EXISTS (SELECT * FROM INDICES WHERE NUMERODEARCHIVO = 3409 AND NUMERODEINDICE = 1)
BEGIN
INSERT INTO INDICES
(NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES(3409, 1, ''Indice principal'', 0, 36071, 36073, 36074, 36075, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
END

IF NOT EXISTS (SELECT * FROM AYUDAS WHERE NUMERODEAYUDA = 34017)
BEGIN
INSERT INTO AYUDAS
(NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES(3409, 34017, ''Ayuda principal'', '''', 0, ''36071R;36072;36073RA1;36074R;'', NULL, NULL, NULL, 0);
END


IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 36077)
BEGIN
INSERT INTO DICCIONARIO
(NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES(36077, '' '', 0, ''Campo ayuda asientos'', ''Campo ayuda asientos'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34017, 0, 0, ''cmp_ayuda_asientos'', 0, NULL);
END


')



