EXECUTE('
IF OBJECT_ID (''RRII_CHE_RECHAZADOS'') IS NOT NULL
	DROP TABLE RRII_CHE_RECHAZADOS

CREATE TABLE RRII_CHE_RECHAZADOS
	(
	COD_ENTIDAD                 NUMERIC (5) DEFAULT ((0)) NOT NULL,
	NRO_SUCURSAL                NUMERIC (3) DEFAULT ((0)) NOT NULL,
	CUENTA                      NUMERIC (11) DEFAULT ((0)) NOT NULL,
	NRO_CHEQUE                  NUMERIC (8) DEFAULT ((0)) NOT NULL,
	AVISO                       NUMERIC (8) DEFAULT ((0)),
	COD_MOVIMIENTO              VARCHAR (1) DEFAULT ('' ''),
	CLASE_REGISTRO              NUMERIC (1) DEFAULT ((0)),
	FECHA_NOTIF_O_DENUNCIA      DATETIME,
	CAUSAL                      VARCHAR (8) DEFAULT (('' '')),
	MONEDA                      NUMERIC (2) DEFAULT ((0)),
	IMPORTE                     NUMERIC (13, 2) DEFAULT ((0)),
	FECHA_RECHAZO_O_PRES_COBRO  DATETIME,
	FECHA_REGISTRACION          DATETIME,
	PLAZO_DIFERIMIENTO          NUMERIC (3) DEFAULT ((0)),
	FECHA_PAGO_CHEQUE           DATETIME,
	FECHA_PAGO_MULTA            DATETIME,
	FECHA_CIERRE_CTA            DATETIME,
	PRIMER_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	SEGUNDO_NRO_IDENTIFICATORIO NUMERIC (11) DEFAULT ((0)),
	TERCER_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	CUARTO_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	QUINTO_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	SEXTO_NRO_IDENTIFICATORIO   NUMERIC (11) DEFAULT ((0)),
	SEPTIMO_NRO_IDENTIFICATORIO NUMERIC (11) DEFAULT ((0)),
	OCTAVO_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	NOVENO_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	DECIMO_NRO_IDENTIFICATORIO  NUMERIC (11) DEFAULT ((0)),
	FECHA_REGISTRO_NOVEDAD      DATETIME NOT NULL,
	TZ_LOCK                     NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CODIGO_MOTIVO               NUMERIC (2),
	CONSTRAINT PK_RRII_CHE_RECHAZADOS_01 PRIMARY KEY (COD_ENTIDAD, NRO_SUCURSAL, CUENTA, NRO_CHEQUE, FECHA_REGISTRO_NOVEDAD)
	)

')



