EXECUTE('
DELETE DICCIONARIO WHERE NUMERODECAMPO=43897
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43897, NULL, 0, ''Ayuda Escribanos'', ''Escribano'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 9452, 0, 0, ''Ayuda Escribanos'', 0, NULL)
')