EXECUTE('
UPDATE dbo.DJ_TIPOS_CAUSAS
SET CODIGO = ''AL''
	, DESCRIPCION = ''LITIS ALIMENTO''
	, PRODUCTO = 10
	, TZ_LOCK = 0
WHERE CODIGO = ''al''


UPDATE dbo.DJ_TIPOS_CAUSAS
SET CODIGO = ''CH''
	, DESCRIPCION = ''Ejecutivo''
	, PRODUCTO = 9
	, TZ_LOCK = 0
WHERE CODIGO = ''ch''

')