EXEC sys.sp_dropextendedproperty @name=N'MS_SSMA_SOURCE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_GRUPOS'
GO

/****** Object:  View [dbo].[VW_GRUPOS]    Script Date: 24/02/2021 11:07:02 ******/
DROP VIEW [dbo].[VW_GRUPOS]
GO

/****** Object:  View [dbo].[VW_GRUPOS]    Script Date: 24/02/2021 11:07:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_GRUPOS] (GRUPO, DESCRIPCION, GRUPOBASE)
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
  --LF 24/02/2021 SELECT TOP 9223372036854775807 WITH TIES GRUPOS.GRUPO, GRUPOS.DESCRIPCION, GRUPOS.GRUPOBASE
	SELECT GRUPOS.GRUPO, GRUPOS.DESCRIPCION, GRUPOS.GRUPOBASE
	FROM dbo.GRUPOS with (nolock)
GO

EXEC sys.sp_addextendedproperty @name=N'MS_SSMA_SOURCE', @value=N'BANKPROD.VW_GRUPOS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_GRUPOS'
GO


