--METADATA
-- MODIFICACICON CAMPO 51413

EXECUTE('        
IF EXISTS (SELECT A.NUMERODECAMPO  FROM DICCIONARIO A WHERE NUMERODECAMPO = 51413)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 51413;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (51413, '' '', 0, ''Porcentaje Minimo'', ''Porcentaje Min'', 5, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 195, ''PORCENTAJE_MINIMO'', 0, NULL);
   

END
ELSE
BEGIN
	INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (51413, '' '', 0, ''Porcentaje Minimo'', ''Porcentaje Min'', 5, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 195, ''PORCENTAJE_MINIMO'', 0, NULL);

END

IF EXISTS (SELECT D.NUMERODECAMPO FROM DICCIONARIO D WHERE NUMERODECAMPO = 51414)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 51414;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (51414, '' '', 0, ''Porcentaje Maximo'', ''Porcentaje Max.'', 5, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 195, ''PORCENTAJE_MAXIMO'', 0, NULL);
   

END
ELSE
BEGIN
	INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
	VALUES (51414, '' '', 0, ''Porcentaje Maximo'', ''Porcentaje Max.'', 5, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 195, ''PORCENTAJE_MAXIMO'', 0, NULL);

END



')
