EXECUTE('DROP VIEW IF EXISTS dbo.VW_ITF_PEP_DOCS;')
EXECUTE('
CREATE VIEW [dbo].[VW_ITF_PEP_DOCS] ( 
											   NUMEROPERSONAFJ, 
											   TIPODOCUMENTO, 
											   NUMERODOCUMENTO, 
											   TIPOPERSONA)
AS
SELECT
	CLI_PERSONASFISICAS.NUMEROPERSONAFISICA,
	CLI_DocumentosPFPJ.TIPODOCUMENTO,
	CLI_DocumentosPFPJ.NUMERODOCUMENTO,
	CLI_DocumentosPFPJ.TIPOPERSONA
		
	
FROM CLI_DocumentosPFPJ WITH (NOLOCK)
INNER JOIN CLI_PERSONASFISICAS WITH (NOLOCK)ON	CLI_DocumentosPFPJ.TIPOPERSONA = ''F'' 
											AND CLI_DocumentosPFPJ.TIPODOCUMENTO = ''CUIL'' 
											AND CLI_DocumentosPFPJ.NUMEROPERSONAFJ = CLI_PERSONASFISICAS.NUMEROPERSONAFISICA

UNION ALL

	SELECT
	CLI_PERSONASJURIDICAS.NUMEROPERSONAJURIDICA,
	CLI_DocumentosPFPJ.TIPODOCUMENTO,
	CLI_DocumentosPFPJ.NUMERODOCUMENTO,
	CLI_DocumentosPFPJ.TIPOPERSONA
	
FROM CLI_DocumentosPFPJ WITH (NOLOCK)
INNER JOIN CLI_PERSONASJURIDICAS WITH (NOLOCK)ON  CLI_DocumentosPFPJ.TIPOPERSONA = ''J'' 
												AND CLI_DocumentosPFPJ.TIPODOCUMENTO = ''CUIT'' 
												AND CLI_DocumentosPFPJ.NUMEROPERSONAFJ = CLI_PERSONASJURIDICAS.NUMEROPERSONAJURIDICA')