EXECUTE('
IF OBJECT_ID (''dbo.CRE_EXCLUSIONES_PRODUCTOS'') IS NOT NULL
	DROP TABLE dbo.CRE_EXCLUSIONES_PRODUCTOS
')

EXECUTE('
CREATE TABLE dbo.CRE_EXCLUSIONES_PRODUCTOS
	(
	TIPO       VARCHAR (1) NOT NULL,
	ITEM       NUMERIC (5) DEFAULT ((0)) NOT NULL,
	GRADUACION NUMERIC (15),
	TZ_LOCK    NUMERIC (15),
	CONSTRAINT PK_EXLUSIONES_PRODUCTOS PRIMARY KEY (TIPO, ITEM)
	)
')

EXECUTE('
UPDATE dbo.DICCIONARIO
SET LARGO = 15
	, TIPODECAMPO = ''N''
WHERE NUMERODECAMPO = 44035

')


EXECUTE('
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 44036

')