EXECUTE('
UPDATE dbo.OPCIONES
SET DESCRIPCION = ''Registrar ctas a causa existente''
WHERE NUMERODECAMPO = 33962 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''2''

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 1816, ''Ayuda Causa - Cuentas'', NULL, 0, ''2615R;2616;661;44871;4898;112;4073;9208;3325;2844;5011;'', ''Nro. Causa;Juzgado;Año;Expediente;Tipo Causa;Fecha Causa;Estado;Caratula;Cuenta;Alta de la Cuenta;Bloqueo de la Cuenta;'', ''TOP/CLIENTES'', ''VW_DJ_CAUSAS'', 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37010, '' '', 0, ''Numerador Causas'', ''Nro. Causa'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 1816, 0, 0, NULL, 0, NULL)

')

EXECUTE('
CREATE VIEW dbo.VW_DJ_CAUSAS (

[Nro. Causa],
[Juzgado],
[Año],
[Expediente],
[Tipo Causa],
[Fecha Causa],
[Estado],
[Caratula],
[Cuenta],
[Alta de la Cuenta],
[Bloqueo de la Cuenta]
)
AS

SELECT
c.NRO_CAUSA,
c.JUZGADO,
c.ANO,
c.EXPEDIENTE,
c.TIPO_CAUSA,
c.FECHA_CAUSA,
( SELECT DESCRIPCION FROM OPCIONES WHERE NUMERODECAMPO=33141 AND OPCIONINTERNA=c.ESTADO) AS ESTADO,
c.CARATULA,
s.CUENTA,
a.FECHA_OFICIO,
b.DESCRIPCION
FROM DJ_CAUSAS c INNER JOIN DJ_CAUSA_CUENTA a ON c.NRO_CAUSA=a.NRO_CAUSA INNER JOIN saldos s ON a.JTS_OID_CUENTA=s.JTS_OID 
INNER JOIN GRL_BLOQUEOS b ON s.JTS_OID=b.SALDO_JTS_OID AND b.ESTADO<>2

')