EXECUTE('
DELETE FROM dbo.CI_IMPUESTOS_X_CARGO
WHERE ID_IMPUESTO = 5 AND ID_CARGO = 2156

DELETE FROM dbo.CI_IMPUESTOS_X_CARGO
WHERE ID_IMPUESTO = 6 AND ID_CARGO = 2156

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (3, 2156, ''A'', 0, 0, NULL)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (4, 2156, ''A'', 0, 1357, ''Cond Percep IVA'')
')