--METADATA

EXECUTE('    

IF EXISTS (SELECT * FROM DESCRIPTORES WHERE IDENTIFICACION = 4508)
BEGIN

 DELETE FROM DESCRIPTORES WHERE IDENTIFICACION = 4508;
 
    INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
    VALUES (24, 4508, NULL, ''Convenios Codigos Mora'', 0, ''CONV_CODIGOS_MORA'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


END
ELSE
BEGIN

     INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
     VALUES (24, 4508, NULL, ''Convenios Codigos Mora'', 0, ''CONV_CODIGOS_MORA'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

END
')
