EXECUTE('

CREATE VIEW VW_CONCURSO_ACREEDORES 
(
[T. Doc. Ident.],
[Nro. Doc. Ident.],
[Ape./s y Nomb./s - Razón Social],
[Juzgado],
[Desc. Juzgado],
[Año],
[Expediente],
[Carátula],
[F. Ingreso],
[F. Fin],
[Medio],
[Desc. Medio],
[Concurso Acreedores],
[Observaciones],
[Tipo persona],
[Nivel Aper.],
[Estado Persona],
[Motivo Inhabilitado],
[Núm. CA]
)
AS

SELECT 
c.TIPODOCUMENTO,
c.CUIT_CUIL,
(CASE 
WHEN d.TIPOPERSONA=''F'' THEN p.APELLIDOPATERNO+'' ''+p.PRIMERNOMBRE 
ELSE u.RAZONSOCIAL 
END) AS ''Nombre o Razón'',
c.JUZGADO,
UPPER(j.NOMBRE),
c.ANIO,
c.EXPEDIENTE,
UPPER(c.CARATULA),
c.FECHA_INGRESO,
c.FECHA_FIN,
UPPER(c.MEDIO),
(SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=33031 AND OPCIONINTERNA=c.MEDIO AND IDIOMA=''E'') AS ''Descripcion medio'',
c.CONC_ACREEDORES,
UPPER(c.OBSERVACIONES),
(CASE 
WHEN d.TIPOPERSONA=''F'' THEN ''PERSONA HUMANA''
WHEN d.TIPOPERSONA=''J'' THEN ''PERSONA JURÍDICA''
WHEN d.TIPOPERSONA=''I'' THEN ''PERSONA INSTITUCÓN FINANCIERA''
END) AS ''Tipo Persona'',
(CASE 
WHEN d.TIPOPERSONA=''F'' THEN (SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=2216 AND OPCIONINTERNA=p.NIVEL_APERTURA AND IDIOMA=''E'')
WHEN d.TIPOPERSONA=''J'' THEN (SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=2216 AND OPCIONINTERNA=u.NIVEL_APERTURA AND IDIOMA=''E'')
END) AS ''Nivel apertura'',
(CASE 
WHEN d.TIPOPERSONA=''F'' THEN UPPER((SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=33366 AND IDIOMA=''E'' AND OPCIONINTERNA=p.ESTADO))
WHEN d.TIPOPERSONA=''J'' THEN UPPER((SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=33367 AND IDIOMA=''E'' AND OPCIONINTERNA=u.ESTADO))
END) AS ''Estado'',
(CASE 
WHEN d.TIPOPERSONA=''F'' THEN UPPER((SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=33368 AND IDIOMA=''E'' AND OPCIONINTERNA=p.MOTIVO_INHABILITADO))
WHEN d.TIPOPERSONA=''J'' THEN UPPER((SELECT DESCRIPCION FROM OPCIONES WITH (NOLOCK) WHERE NUMERODECAMPO=33369 AND IDIOMA=''E'' AND OPCIONINTERNA=u.MOTIVO_INHABILITADO))
END) AS ''Motivo'',
c.ID
FROM CLI_CONCURSO_ACREEDORES c  WITH (NOLOCK)
JOIN CLI_DocumentosPFPJ d WITH (NOLOCK) ON c.CUIT_CUIL=d.NUMERODOCUMENTO AND c.TIPODOCUMENTO=d.TIPODOCUMENTO AND
((d.TZ_LOCK < 300000000000000 OR d.TZ_LOCK >= 400000000000000) AND (d.TZ_LOCK < 100000000000000 OR d.TZ_LOCK >= 200000000000000)) AND
((c.TZ_LOCK < 300000000000000 OR c.TZ_LOCK >= 400000000000000) AND (c.TZ_LOCK < 100000000000000 OR c.TZ_LOCK >= 200000000000000))
LEFT JOIN DJ_JUZGADOS j WITH (NOLOCK) ON c.JUZGADO=j.NRO_JUZGADO AND
((j.TZ_LOCK < 300000000000000 OR j.TZ_LOCK >= 400000000000000) AND (j.TZ_LOCK < 100000000000000 OR j.TZ_LOCK >= 200000000000000))
LEFT JOIN CLI_PERSONASFISICAS p WITH (NOLOCK) ON d.TIPOPERSONA=''F'' AND p.NUMEROPERSONAFISICA=d.NUMEROPERSONAFJ LEFT JOIN CLI_PERSONASJURIDICAS u WITH (NOLOCK) ON d.TIPOPERSONA=''J'' AND u.NUMEROPERSONAJURIDICA=d.NUMEROPERSONAFJ
')

EXECUTE('

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 1818, ''Ayuda Concurso Acreedores'', NULL, 0, ''537R;50033R;114R;40009R;9105R;437R;44871R;9208;1853;1443;8753;241;33341;33965;215;249;274;410;665R;'', ''T. Doc. Ident.;Nro. Doc. Ident.;Ape./s y Nomb./s - Razón Social;Juzgado;Desc. Juzgado;Año;Expediente;Carátula;F. Ingreso;F. Fin;Medio;Desc. Medio;Concurso Acreedores;Observaciones;Tipo persona;Nivel Aper.;Estado Persona;Motivo Inhabilitado;Núm. CA'', ''Top/Clientes'', ''VW_CONCURSO_ACREEDORES'', 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37008, '' '', 0, ''Ayuda Concurso Acreedores'', ''Concurso Acreedores'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 1818, 0, 0, NULL, 0, NULL)


INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3315, 2, ''FK causas'', 0, 33135, 33136, 33137, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


ALTER TABLE CLI_CONCURSO_ACREEDORES DROP CONSTRAINT PK_CLI_CONCURSO_ACREEDORES_01;
ALTER TABLE CLI_CONCURSO_ACREEDORES DROP CONSTRAINT DF__CLI_CONCU__EXPED__103C0301;
ALTER TABLE CLI_CONCURSO_ACREEDORES ALTER COLUMN EXPEDIENTE VARCHAR(12) NOT NULL;
ALTER TABLE CLI_CONCURSO_ACREEDORES ADD CONSTRAINT PK_CLI_CONCURSO_ACREEDORES_01  PRIMARY KEY (CUIT_CUIL, TIPODOCUMENTO, ID);

UPDATE dbo.DICCIONARIO
SET TIPODECAMPO = ''A''
WHERE NUMERODECAMPO = 33024



UPDATE dbo.INDICES
SET CAMPO4 = NULL
WHERE NUMERODEARCHIVO = 3304 AND NUMERODEINDICE = 1


')