EXECUTE('
	INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO) VALUES(3100, 3041, ''Consulta Saldo de tesoro'', ''Consulta journal y movimientos de caja'', ''3041'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0);
	INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO) VALUES(3100, 3042, ''Consulta Libro de tesoro'', ''Consulta journal y movimientos de caja'', ''3042'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0);
	DELETE FROM REPORTES WHERE TITULO = 9000 AND IDENTIFICACION = 2616;
	DELETE FROM REPORTESJASPER WHERE IDENTIFICACION = 2616;
	INSERT INTO REPORTES
	(TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
	VALUES(9000, 2616, ''Consulta Libro de Tesoro'', ''J'', 0, NULL, 0, 0.0, 0, ''N'');
	select * from reportesjasper where IDENTIFICACION = 2615
	INSERT INTO REPORTESJASPER
	(IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
	VALUES(2616, 1, NULL, 0, 0, 1);
	DELETE FROM REPORTES WHERE TITULO = 9000 AND IDENTIFICACION = 2615;
	DELETE FROM REPORTESJASPER WHERE IDENTIFICACION = 2615;
	INSERT INTO REPORTES
	(TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
	VALUES(9000, 2615, ''Consulta saldos sucursal - Tes'', ''J'', 0, NULL, 0, 0.0, 0, ''N'');
	INSERT INTO REPORTESJASPER
	(IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
	VALUES(2615, 1, NULL, 0, 0, 1);
');