EXECUTE('

DELETE CI_IMPUESTOS_X_CARGO WHERE ID_CARGO IN (2160,2161)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (3, 2160, ''A'', 0, NULL, NULL)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (4, 2160, ''A'', 0, 1357, ''Cond Percep IVA'')

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (3, 2161, ''A'', 0, NULL, NULL)

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (4, 2161, ''A'', 0, 1357, ''Cond Percep IVA'')

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 2160, ''A'', 0, 34096, ''Cond CREDEB'')

INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (10, 2161, ''A'', 0, 34096, ''Cond CREDEB'')
')
