EXECUTE('
UPDATE dbo.CRE_VINCULOS_RELACIONES
SET REQUIERE_VINC = ''N''
WHERE TIPO_RELACION = 2 AND ID_VINCULO = 6

UPDATE dbo.CRE_VINCULOS_RELACIONES
SET REQUIERE_VINC = ''N''
WHERE TIPO_RELACION = 2 AND ID_VINCULO = 7
')
