EXECUTE('
IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 3035)
BEGIN
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3035, '' '', 0, ''Ayuda Vista Integrantes Pj PInst'', ''Ayuda Vista Pj/PI'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 30351, 0, 0, ''C3035'', 0, NULL)
END

IF NOT EXISTS (SELECT * FROM AYUDAS WHERE NUMERODEAYUDA = 30351)
BEGIN
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 30351, ''Ayuda Integrante PJ PInst'', NULL, 0, ''1064R;1963R;1901;324;329;537R;622R;1058;332;335;3242;1063R;1057R;4161R;'', ''Tipo Documento Identificativo;Número Documento Identificativo;Razón Social;Nivel Apertura;Estado;Tipo Documento Identificativo PH/PJ;Número Documento Identificativo PH/PJ;Nombre;Nivel Apertura PH/PJ;Estado PH/PJ;Cargo;Tipo persona;Numero PJ;Numero PH/PJ'', ''Top/Clientes'', ''VW_INTEGRANTES_PJ_PIF'', 0)
END

IF NOT EXISTS (SELECT * FROM DICCIONARIO WHERE NUMERODECAMPO = 3036)
BEGIN
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3036, '' '', 0, ''Ayuda Docs PJ Hab'', ''Ayuda docs PJ Hab'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 30361, 0, 0, ''C3036'', 0, NULL)
END

IF NOT EXISTS (SELECT * FROM AYUDAS WHERE NUMERODEAYUDA = 30361)
BEGIN
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 30361, ''Ayuda Docs PJ hab'', NULL, 0, ''1064R;1963R;274;209;531;1057R;1063R;'', ''Tipo Documento Identificativo;Número Documento Identificativo;Razón Social;Nivel de Apertura;Estado de la Persona;Número de Persona;Tipo de Persona'', ''Top/Clientes'', ''VW_PJ_DOCS_HABILITADOS'', 0)
END
')











