EXECUTE('
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN DEUDA_SIN_GARANTIA NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN DEUDA_CON_GARANTIA NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN DEUDA_SIN_GARANTIA_GRUPO NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN DEUDA_CON_GARANTIA_GRUPO NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN MARGEN_REGUARDO NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN LIMITE_GRADUACION NUMERIC(38,2)
ALTER TABLE CRE_GRAD_FRACC_BITACORA ALTER COLUMN DEUDA_TOTAL NUMERIC(38,2)
')