execute('
-- Modificar nombre de job en ITF_MASTER y parametros
update ITF_MASTER 
SET 
	DESCRIPCION = ''Carga Masiva débitos automáticos'',
	OBJ_KETTLE = ''ITF_DJP_DEBAUT_SOPORTE.kjb'',
	P0_MODO = ''P'', P0_TIPO = ''S'', P0_CAPTION = ''Nombre Archivo'', P0_CONSTANTE = '' '',
	P1_MODO = ''P'', P1_TIPO = ''N'', P1_CAPTION = ''ID Convenio'', P1_CONSTANTE = '' '',
	P2_MODO = '' '', P2_TIPO = '' '', P2_CAPTION = '' '', P2_CONSTANTE = '' '',
	P3_MODO = ''C'', P3_TIPO = ''S'', P3_CAPTION = '' '', P3_CONSTANTE = ''B'',
	P4_MODO = '' '', P4_TIPO = '' '', P4_CAPTION = '' '', P4_CONSTANTE = '' '',
	P5_MODO = '' '', P5_TIPO = '' '', P5_CAPTION = '' '', P5_CONSTANTE = '' '',
	P6_MODO = '' '', P6_TIPO = '' '', P6_CAPTION = '' '', P6_CONSTANTE = '' '',
	P7_MODO = '' '', P7_TIPO = '' '', P7_CAPTION = '' '', P7_CONSTANTE = '' '',
	P8_MODO = '' '', P8_TIPO = '' '', P8_CAPTION = '' '', P8_CONSTANTE = '' '',
	P9_MODO = '' '', P9_TIPO = '' '', P9_CAPTION = '' '', P9_CONSTANTE = '' '',
	TIPO_OBJ = ''J'', COMENTARIO = ''Soporte de Debitos Automáticos'',
	ID_REPORTE = 0, MODO_EJECUCION = ''M''
WHERE ID = 19

-- Agregar evento
INSERT INTO EVENTOS (TZ_LOCK,ID_EVENTO,CANAL,SUB_CANAL) VALUES (0,135,N''7'',N''150'');

-- Configuración de mensaje
INSERT INTO EVENTOS_TRANSACCION (TZ_LOCK,CODIGO_TRANSACCION,ID_EVENTO,CONDICION,CAMPOS,PRIORIDAD,DESCRIPCION,TIPO_MAPEO,GRABAR_TABLA,ENVIAR_EN_REVERSA,ENABLE_OBJ_FORMAT) VALUES
	 (0,540,135,NULL,N''transactionId=760;ref=9503;loteId=93;cuit=339;convenio=621;resultado=4886;codError=622;descripcion=910'',2,N''ITF_DJP_DEBAUT_SOPORTE.kjb'',2,1,1,0);

-- Configuración transacción
INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION,CODIGO_INTERNO_MOV,CODIGO_TRANSACCION,TZ_LOCK) VALUES
	 (9919,135,540,0);

-- Configuración de operación topaz
INSERT INTO dbo.OPERACIONES (TITULO,IDENTIFICACION,NOMBRE,DESCRIPCION,MNEMOTECNICO,AUTORIZACION,FORMULARIOPRINCIPAL,PROXOPERACION,ESTADO,TZ_LOCK,COPIAS,SUBOPERACION,PERMITEBAJA,COMPORTAMIENTOENCIERRE,REQUIERECONTRASENA,PERMITECONCURRENTE,PERMITEESTADODIFERIDO,ICONO_TITULO,ESTILO) VALUES
	 (6800,9919,N''1.29.23 DJP - DebAut Soporte'',N''1.29.23 DJP - DebAut Soporte'',N''9919'',N''N'',NULL,NULL,N''P'',0,NULL,0,N''S'',N''N'',N''N'',N''N'',N''N'',NULL,0);
');

execute('
-- DROP TABLE gamma.dbo.REC_DET_DEBITOSAUTOMATICOS;

ALTER TABLE dbo.REC_DET_DEBITOSAUTOMATICOS DROP CONSTRAINT PK_REC_DET_DEBITOSAUTOMATIC_01;

ALTER TABLE dbo.REC_DET_DEBITOSAUTOMATICOS ADD CONSTRAINT PK_REC_DET_DEBITOSAUTOMATIC_01 PRIMARY KEY (NRO_REGISTRO);

ALTER TABLE dbo.REC_DET_DEBITOSAUTOMATICOS ADD CONSTRAINT UK_REC_DET_DEBITOSAUTOMATIC_01 UNIQUE (ID_CABEZAL, ID_LINEA);
');

execute('
DROP TABLE IF EXISTS dbo.REC_CAB_DEBITOSAUTOMATICOS;

CREATE TABLE dbo.REC_CAB_DEBITOSAUTOMATICOS (
	ID numeric(15,0) IDENTITY(1,1) NOT NULL,
	ESTADO varchar(1) COLLATE Modern_Spanish_CI_AS DEFAULT '' '' NULL,
	ARCHIVO varchar(75) COLLATE Modern_Spanish_CI_AS DEFAULT '' '' NULL,
	CONVENIO numeric(15,0) DEFAULT 0 NULL,
	FECHACARGA datetime NULL,
	ID_LIQUIDACION numeric(15,0) DEFAULT 0 NULL,
	MONEDA numeric(4,0) DEFAULT 0 NULL,
	TOTALREGISTROS numeric(7,0) DEFAULT 0 NULL,
	TOTALIMPORTE numeric(15,2) DEFAULT 0 NULL,
	TZ_LOCK numeric(15,0) DEFAULT 0 NOT NULL,
	FECHACORTE datetime NULL,
	CONSTRAINT PK_REC_CAB_DEBITOSAUTOMATIC_01 PRIMARY KEY (ID)
);
');