EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (550, 4366, NULL, ''Bit graduacion-fraccionamiento'', 0, ''CRE_GRAD_FRACC_BITACORA'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43967, NULL, 0, ''Cliente'', ''Cliente'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''CODIGOCLIENTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43978, '' '', 0, ''Asiento'', ''Asiento'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''ASIENTO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43979, '' '', 0, ''Fecha de proceso'', ''Fecha de proceso'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 4366, ''FECHAPROCESO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43980, '' '', 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''SUCURSAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43981, '' '', 0, ''Tipo'', ''Tipo'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4366, ''TIPO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43982, '' '', 0, ''CN1 Banco'', ''CN1 Banco'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''CN1_BANCO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43983, '' '', 0, ''Porcentaje tramo sin garantia'', ''Porcentaje tramo sin garantia'', 5, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PORC_TRAMO_SIN_G'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43984, '' '', 0, ''Tramo sin garantía'', ''Tramo sin garantía'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''TRAMO_SIN_GARANTIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43985, '' '', 0, ''Porcentaje tramo con garantía'', ''Porcentaje tramo con garantía'', 5, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PORC_TRAMO_CON_G'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43986, '' '', 0, ''Tramo con garantia'', ''Tramo con garantia'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''TRAMO_CON_GARANTIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43987, '' '', 0, ''Deuda sin garantia'', ''Deuda sin garantia'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''DEUDA_SIN_GARANTIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43988, '' '', 0, ''Deuda con garantía'', ''Deuda con garantía'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''DEUDA_CON_GARANTIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43989, '' '', 0, ''Deuda con garantia grupo'', ''Deuda con garantia grupo'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''DEUDA_CON_GARANTIA_GRUPO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (43999, '' '', 0, ''Deuda sin garantia grupo'', ''Deuda sin garantia grupo'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''DEUDA_SIN_GARANTIA_GRUPO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44000, '' '', 0, ''RPC_BANCO'', ''RPC Banco'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''RPC_BANCO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44005, '' '', 0, ''EXCLUSIONES'', ''Exclusiones'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''EXCLUSIONES'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44006, '' '', 0, ''RPC Cliente'', ''RPC Cliente'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''RPC_CLIENTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44007, '' '', 0, ''Maximo RPC cliente'', ''Maximo RPC cliente'', 20, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''MAXIMO_RPC_CLIENTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44008, '' '', 0, ''Porcentaje RPC Neta banco'', ''Porcentaje RPC Neta banco'', 5, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PORC_RPC_NETA_BANCO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44009, '' '', 0, ''RPC Neta banco'', ''RPC Neta banco'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''RPC_NETA_BANCO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44010, '' '', 0, ''Porcentaje margen resguardo'', ''Porcentaje margen resguardo'', 5, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PORC_MARGE_RES'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44011, '' '', 0, ''Margen resguardo'', ''Margen resguardo'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''MARGEN_REGUARDO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44012, '' '', 0, ''Limite graduacion'', ''Limite graduacion'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''LIMITE_GRADUACION'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44013, '' '', 0, ''Porcentaje rpc cliente'', ''Porcentaje rpc cliente'', 5, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PORCENTAJE_RPC_CLIENTE'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44014, '' '', 0, ''Importe solicitado'', ''Importe solicitado'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''IMPORTE_SOLICITADO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44015, '' '', 0, ''Excluido'', ''Excluido'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4366, ''EXCLUIDO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44016, '' '', 0, ''Con garantía'', ''Con garantía'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4366, ''CON_GTIA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44017, '' '', 0, ''Deuda total'', ''Deuda total'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 4366, ''DEUDA_TOTAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44020, '' '', 0, ''Periodo'', ''Periodo'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''PERIODO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44021, '' '', 0, ''Resultado graduacion'', ''Resultado graduacion'', 200, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''RESULTADO_GRAD'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44022, '' '', 0, ''Resultado fraccionamiento'', ''Resultado fraccionamiento'', 200, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''RESULTADO_FRACC'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44105, '' '', 0, ''Grupo'', ''Grupo'', 80, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''DESCRIPCION_GRUPO'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44106, '' '', 0, ''Vinculo'', ''Vinculo'', 80, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4366, ''DESCRIPCION_VINCULO'', 0, NULL)

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43981, ''E'', ''Asistencia'', ''A'', ''A'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43981, ''E'', ''Simulación por proceso'', ''B'', ''B'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (43981, ''E'', ''Simulación manual'', ''S'', ''S'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44015, ''E'', ''No'', ''N'', ''N'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44015, ''E'', ''Si'', ''S'', ''S'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44016, ''E'', ''No'', ''N'', ''N'')

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44016, ''E'', ''Si'', ''S'', ''S'')

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4366, 1, ''Indices'', 0, 43978, 43967, 43979, 43980, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4366, 4366, ''Graduación y fraccionamiento'', '''', 0, ''43967R;43978R;43980R;43979R;43981;44014;44017;44012;'', NULL, NULL, NULL, 0)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44018, '' '', 0, ''Graduación y Fraccionamiento'', ''Graduación y Fraccionamiento'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 4366, 0, 0, ''AYUDA_GRAD_FRACC'', 0, NULL)
')