EXECUTE('
------------------------------
--AJUSTE COLUMNAS Y METADATA--
------------------------------
BEGIN

DECLARE @ConstraintName nvarchar(200)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASFISICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASFISICAS DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASFISICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_ALI''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASFISICAS DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASFISICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IIBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASFISICAS DROP CONSTRAINT '' + @ConstraintName)
 
END
')
--
EXECUTE('
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASFISICAS DROP COLUMN IBB_CABA_RETENCION_COND
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_ALI'' AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASFISICAS DROP COLUMN IBB_CABA_RETENCION_ALI
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IIBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_PERSONASFISICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASFISICAS DROP COLUMN IIBB_CABA_RETENCION_COND
END
')
--------------
EXECUTE('
BEGIN

DECLARE @ConstraintName nvarchar(200)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASJURIDICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASJURIDICAS DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASJURIDICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_ALI''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASJURIDICAS DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_PERSONASJURIDICAS'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IIBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_PERSONASJURIDICAS DROP CONSTRAINT '' + @ConstraintName)
 
END
')
--
EXECUTE('
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASJURIDICAS DROP COLUMN IBB_CABA_RETENCION_COND
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_ALI'' AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASJURIDICAS DROP COLUMN IBB_CABA_RETENCION_ALI
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IIBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_PERSONASJURIDICAS'')) IS NOT NULL
		ALTER TABLE CLI_PERSONASJURIDICAS DROP COLUMN IIBB_CABA_RETENCION_COND
END
')
--------------
EXECUTE('
BEGIN

DECLARE @ConstraintName nvarchar(200)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_CLIENTES'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_CLIENTES''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_CLIENTES DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_CLIENTES'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IBB_CABA_RETENCION_ALI''
                        AND object_id = OBJECT_ID(N''CLI_CLIENTES''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_CLIENTES DROP CONSTRAINT '' + @ConstraintName)

SET @ConstraintName = NULL
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID(''CLI_CLIENTES'')
AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
                        WHERE NAME = N''IIBB_CABA_RETENCION_COND''
                        AND object_id = OBJECT_ID(N''CLI_CLIENTES''))

IF @ConstraintName IS NOT NULL
 EXEC(''ALTER TABLE CLI_CLIENTES DROP CONSTRAINT '' + @ConstraintName)
 
END
')
--
EXECUTE('
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_CLIENTES'')) IS NOT NULL
		ALTER TABLE CLI_CLIENTES DROP COLUMN IBB_CABA_RETENCION_COND
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IBB_CABA_RETENCION_ALI'' AND object_id = OBJECT_ID(N''CLI_CLIENTES'')) IS NOT NULL
		ALTER TABLE CLI_CLIENTES DROP COLUMN IBB_CABA_RETENCION_ALI
END
BEGIN
	IF (SELECT column_id FROM sys.columns WHERE NAME = N''IIBB_CABA_RETENCION_COND'' AND object_id = OBJECT_ID(N''CLI_CLIENTES'')) IS NOT NULL
		ALTER TABLE CLI_CLIENTES DROP COLUMN IIBB_CABA_RETENCION_COND
END
')
--------------
EXECUTE('
ALTER TABLE CLI_PERSONASFISICAS ADD IIBB_CABA_RETENCION_COND VARCHAR (2) DEFAULT ('' '')
								, IIBB_CABA_RETENCION_ALI NUMERIC (11, 7) DEFAULT ((0)) NOT NULL
--
ALTER TABLE CLI_PERSONASJURIDICAS ADD IIBB_CABA_RETENCION_COND VARCHAR (2) DEFAULT ('' '')
								, IIBB_CABA_RETENCION_ALI NUMERIC (11, 7) DEFAULT ((0)) NOT NULL
--
ALTER TABLE CLI_CLIENTES ADD IIBB_CABA_RETENCION_COND VARCHAR (2) DEFAULT ('' '')
								, IIBB_CABA_RETENCION_ALI NUMERIC (11, 7) DEFAULT ((0)) NOT NULL
----
')