EXECUTE('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3571, NULL, ''VTA Transferencias Debin'', 0, ''VTA_TRANSFERENCIAS_DEBIN'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')
')

EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45761, '''', 0, ''TRANSACCION'', ''TRANSACCION'', 6, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''TRANSACCION'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45762, '''', 0, ''SUCURSAL'', ''SUCURSAL'', 5, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''SUCURSAL'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45763, '''', 0, ''NRO_CUENTA'', ''NRO_CUENTA'', 11, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''NRO_CUENTA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45764, '''', 0, ''SUBSISTEMA'', ''SUBSISTEMA'', 2, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''SUBSISTEMA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45765, '''', 0, ''FECHALOCAL'', ''FECHALOCAL'', 10, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''FECHALOCAL'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45766, '''', 0, ''HORALOCAL'', ''HORALOCAL'', 8, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''HORALOCAL'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45767, '''', 0, ''RECIBO'', ''RECIBO'', 12, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''RECIBO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45768, '''', 0, ''TERMINAL'', ''TERMINAL'', 16, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''TERMINAL'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45769, '''', 0, ''INFORMACION'', ''INFORMACION'', 35, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''INFORMACION'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45770, '''', 0, ''CONCEPTO'', ''CONCEPTO'', 10, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''CONCEPTO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45771, '''', 0, ''BCO_BCRA'', ''BCO_BCRA'', 4, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''BCO_BCRA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45772, '''', 0, ''CUIT'', ''CUIT'', 11, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''CUIT'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45773, '''', 0, ''CBU_BLOQUE1'', ''CBU_BLOQUE1'', 8, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''CBU_BLOQUE1'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45774, '''', 0, ''CBU_BLOQUE2'', ''CBU_BLOQUE2'', 14, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''CBU_BLOQUE2'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45775, '''', 0, ''CUENTA'', ''CUENTA'', 19, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''CUENTA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45776, '''', 0, ''MOVIMIENTO_CONTRASENTADO'', ''MOVIMIENTO_CON'', 1, ''N'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''MOVIMIENTO_CONTRASENTADO'', 0, '''')


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45777, '''', 0, ''ID_MOVIMIENTO_SIDEBA'', ''ID_MOVIMIENTO_'', 26, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''ID_MOVIMIENTO_SIDEBA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45778, '''', 0, ''SECUENCIA'', ''SECUENCIA'', 5, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''SECUENCIA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45779, '''', 0, ''RENGLON'', ''RENGLON'', 7, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''RENGLON'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45780, '''', 0, ''NUMERO_TARJETA'', ''NUMERO_TARJETA'', 19, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''NUMERO_TARJETA'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45781, '''', 0, ''NOMBREAPELLCOMPRADOR'', ''NOMBREAPELLCOM'', 40, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''NOMBREAPELLCOMPRADOR'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45782, '''', 0, ''MISMOTITULAR'', ''MISMOTITULAR'', 1, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''MISMOTITULAR'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45783, '''', 0, ''DEBITO_PREAUTORIZADO'', ''DEBITO_PREAUTO'', 1, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''DEBITO_PREAUTORIZADO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45784, '''', 0, ''DEBIN_TRANSF_CONTRACT'', ''DEBIN_TRANSF_C'', 1, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''DEBIN_TRANSF_CONTRACT'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45785, '''', 0, ''SCORING'', ''SCORING'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''SCORING'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45786, '''', 0, ''IDENTID_CONTRACARGO'', ''IDENTID_CONTRA'', 32, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''IDENTID_CONTRACARGO'', 0, '''')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45787, '''', 0, ''MOTIVO_CONTRACARGO'', ''MOTIVO_CONTRAC'', 3, ''A'', 0, '''', 0, 0, 0, 0, 0, 0, 0, 3571, ''MOTIVO_CONTRACARGO'', 0, '''')

')

EXECUTE('
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3571, 1, ''Indice principal'', 0, 45761, 45763, 45767, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
')

