


-- Patch_NUGAN106_281

-- Se agrega tabla BITACORA_REASIGNACION
create table BITACORA_REASIGNACION
(
  NOMBRE_FLUJO   VARCHAR(255) default (' '),
  NOMBRE_TAREA VARCHAR(255) default (' '),
  ID_FLUJO   NUMERIC(19) default (0) not null,
  USUARIO_ANTERIOR  VARCHAR(255) default (' '),
  USUARIO_NUEVO   VARCHAR(255) default (' '),
  USUARIO_ASIGNACION   VARCHAR(50) default (' '),
  FECHA_REASIGNACION   DATETIME not null,
  HORA_REASIGNACION   VARCHAR(10) not null,  
  SUCURSAL_REASIGNACION   NUMERIC(4) default (0)  
);

-- Se agrega index a BITACORA_REASIGNACION
create unique index PK_BITACORA_REASIGNACION on BITACORA_REASIGNACION (ID_FLUJO, FECHA_REASIGNACION, HORA_REASIGNACION);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210921_1',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VR0FOMTA2XzI4MQoNCi0tIFNlIGFncmVnYSB0YWJsYSBCSVRBQ09SQV9S
RUFTSUdOQUNJT04NCmNyZWF0ZSB0YWJsZSBCSVRBQ09SQV9SRUFTSUdOQUNJT04KKAogIE5PTUJS
RV9GTFVKTyAgIFZBUkNIQVIoMjU1KSBkZWZhdWx0ICgnICcpLAogIE5PTUJSRV9UQVJFQSBWQVJD
SEFSKDI1NSkgZGVmYXVsdCAoJyAnKSwKICBJRF9GTFVKTyAgIE5VTUVSSUMoMTkpIGRlZmF1bHQg
KDApIG5vdCBudWxsLAogIFVTVUFSSU9fQU5URVJJT1IgIFZBUkNIQVIoMjU1KSBkZWZhdWx0ICgn
ICcpLAogIFVTVUFSSU9fTlVFVk8gICBWQVJDSEFSKDI1NSkgZGVmYXVsdCAoJyAnKSwKICBVU1VB
UklPX0FTSUdOQUNJT04gICBWQVJDSEFSKDUwKSBkZWZhdWx0ICgnICcpLAogIEZFQ0hBX1JFQVNJ
R05BQ0lPTiAgIERBVEVUSU1FIG5vdCBudWxsLAogIEhPUkFfUkVBU0lHTkFDSU9OICAgVkFSQ0hB
UigxMCkgbm90IG51bGwsICAKICBTVUNVUlNBTF9SRUFTSUdOQUNJT04gICBOVU1FUklDKDQpIGRl
ZmF1bHQgKDApICAKKTsKDQotLSBTZSBhZ3JlZ2EgaW5kZXggYSBCSVRBQ09SQV9SRUFTSUdOQUNJ
T04NCmNyZWF0ZSB1bmlxdWUgaW5kZXggUEtfQklUQUNPUkFfUkVBU0lHTkFDSU9OIG9uIEJJVEFD
T1JBX1JFQVNJR05BQ0lPTiAoSURfRkxVSk8sIEZFQ0hBX1JFQVNJR05BQ0lPTiwgSE9SQV9SRUFT
SUdOQUNJT04pOwoNCgoKDQo=', NULL, 0);
