
EXECUTE('       
IF EXISTS (SELECT * FROM OPCIONES WHERE NUMERODECAMPO = 44755 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''SEM'')
BEGIN

   DELETE FROM OPCIONES
WHERE NUMERODECAMPO = 44755 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''SEM'';
 
END

')