EXECUTE('
UPDATE dbo.DESCRIPTORES
SET NOMBREFISICO = ''TLF_COD_TRANSACCIONES''
WHERE TITULO = 800 AND IDENTIFICACION = 4361


UPDATE dbo.DESCRIPTORES
SET DESCRIPCION = ''TLF_COD_TRANSACCIONES''
WHERE TITULO = 800 AND IDENTIFICACION = 4361

')

EXECUTE('
IF OBJECT_ID (''dbo.TLF_CODIGOS_OPERACIONES'') IS NOT NULL
	DROP TABLE dbo.TLF_CODIGOS_OPERACIONES

')

EXECUTE('
CREATE TABLE dbo.TLF_COD_TRANSACCIONES
	(
	TZ_LOCK      NUMERIC (15),
	COD_MSJ_H2H  VARCHAR (6) NOT NULL,
	COD_MSJ_TLF  VARCHAR (6) NOT NULL,
	NRO_OPE      NUMERIC (5) NOT NULL,
	DESC_COD_MSJ VARCHAR (50),
	PARAMETRO1   VARCHAR (50),
	PARAMETRO2   VARCHAR (50),
	PARAMETRO3   VARCHAR (50),
	PARAMETRO4   VARCHAR (50),
	PARAMETRO5   VARCHAR (50),
	PARAMETRO6   VARCHAR (50),
	PARAMETRO7   VARCHAR (50),
	PARAMETRO8   VARCHAR (50),
	PARAMETRO9   VARCHAR (50),
	PARAMETRO10  VARCHAR (50),
	CONSTRAINT PK_TLF_CODIGOS_OPERACIONES PRIMARY KEY (COD_MSJ_H2H, NRO_OPE)
	)
')