


-- Parche_NUNBCHACO_202

-- Inserta registros en PARAMETROS_JTS
INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('DEVENGA_DIFERENCIA_INTERESES', 'CANAL', '0', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('DEVENGA_DIFERENCIA_INTERESES', 'DESCRIPCION', 'Devengar diferencia intereses tasa contractual/tasa mercado', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('DEVENGA_DIFERENCIA_INTERESES', 'OPERACION', '29', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('DEVENGA_DIFERENCIA_INTERESES', 'PIVOT_TOTAL_INTERES', '1', 0);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO)
VALUES ('8600' , '29', 'Deven Dif Int', 'Deven Dif Int', '29', 'N', NULL, NULL, 'P', 0, NULL, 0, 'S', 'N', 'N', 'S', 'S');




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210217_2NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fMjAyCg0KLS0gSW5zZXJ0YSByZWdpc3Ryb3MgZW4gUEFS
QU1FVFJPU19KVFMNCklOU0VSVCBJTlRPIFBBUkFNRVRST1NfSlRTIChGVU5DSU9OQUxJREFELCBQ
QVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdERVZFTkdBX0RJRkVSRU5DSUFfSU5U
RVJFU0VTJywgJ0NBTkFMJywgJzAnLCAwKTsKCklOU0VSVCBJTlRPIFBBUkFNRVRST1NfSlRTIChG
VU5DSU9OQUxJREFELCBQQVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdERVZFTkdB
X0RJRkVSRU5DSUFfSU5URVJFU0VTJywgJ0RFU0NSSVBDSU9OJywgJ0RldmVuZ2FyIGRpZmVyZW5j
aWEgaW50ZXJlc2VzIHRhc2EgY29udHJhY3R1YWwvdGFzYSBtZXJjYWRvJywgMCk7CgpJTlNFUlQg
SU5UTyBQQVJBTUVUUk9TX0pUUyAoRlVOQ0lPTkFMSURBRCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpf
TE9DSykKVkFMVUVTICgnREVWRU5HQV9ESUZFUkVOQ0lBX0lOVEVSRVNFUycsICdPUEVSQUNJT04n
LCAnMjknLCAwKTsKCklOU0VSVCBJTlRPIFBBUkFNRVRST1NfSlRTIChGVU5DSU9OQUxJREFELCBQ
QVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdERVZFTkdBX0RJRkVSRU5DSUFfSU5U
RVJFU0VTJywgJ1BJVk9UX1RPVEFMX0lOVEVSRVMnLCAnMScsIDApOwoKSU5TRVJUIElOVE8gT1BF
UkFDSU9ORVMgKFRJVFVMTywgSURFTlRJRklDQUNJT04sIE5PTUJSRSwgREVTQ1JJUENJT04sIE1O
RU1PVEVDTklDTywgQVVUT1JJWkFDSU9OLCBGT1JNVUxBUklPUFJJTkNJUEFMLCBQUk9YT1BFUkFD
SU9OLCBFU1RBRE8sIFRaX0xPQ0ssIENPUElBUywgU1VCT1BFUkFDSU9OLCBQRVJNSVRFQkFKQSwg
Q09NUE9SVEFNSUVOVE9FTkNJRVJSRSwgUkVRVUlFUkVDT05UUkFTRU5BLCBQRVJNSVRFQ09OQ1VS
UkVOVEUsIFBFUk1JVEVFU1RBRE9ESUZFUklETykKVkFMVUVTICgnODYwMCcgLCAnMjknLCAnRGV2
ZW4gRGlmIEludCcsICdEZXZlbiBEaWYgSW50JywgJzI5JywgJ04nLCBOVUxMLCBOVUxMLCAnUCcs
IDAsIE5VTEwsIDAsICdTJywgJ04nLCAnTicsICdTJywgJ1MnKTsKDQoKCg0K', NULL, 0);
