execute('

UPDATE NUMERATORVALUES SET VALOR = ISNULL((SELECT MAX(ID_LIQUIDACION)+1 FROM REC_LIQUIDACION) ,0) 
	WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 45036

DELETE FROM NUMERATORASIGNED WHERE OID = (SELECT OID FROM NUMERATORVALUES WHERE NUMERO = 45036)
')