EXECUTE('
CREATE OR ALTER   PROCEDURE PA_ITF_BITACORA_RESETEO_PARAM(
  @P_ID_PROCESO float(53),
  @P_DT_PROCESO datetime2(0),
  @P_RET_PROCESO float(53)  OUTPUT,
  @P_MSG_PROCESO varchar(max)  OUTPUT)
AS
BEGIN
  DECLARE @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6 varchar(8000)
  SET @P_RET_PROCESO = NULL
  SET @P_MSG_PROCESO = NULL 
      
  BEGIN TRY
     
	UPDATE ITF_MASTER_PARAMETROS 
	SET NUMERICO_1 = 1
	WHERE CODIGO= 478

	UPDATE ITF_MASTER_PARAMETROS 
	SET NUMERICO_1 = 1
	WHERE CODIGO= 479

	UPDATE ITF_MASTER_PARAMETROS 
	SET NUMERICO_1 = 1
	WHERE CODIGO= 480

	ALTER SEQUENCE dbo.BITACORA_CLIENTE_ORDINAL RESTART WITH 1;
	ALTER SEQUENCE dbo.BITACORA_FISICA_ORDINAL RESTART WITH 1;
	ALTER SEQUENCE dbo.BITACORA_JURIDICA_ORDINAL RESTART WITH 1;
	
	SET @P_RET_PROCESO = 1;
    SET @P_MSG_PROCESO = ''Se reseteo los parametros y secuencias de la bitacora'';
    SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6 = @P_MSG_PROCESO;
    
    EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
               @P_ID_PROCESO, 
               @P_DT_PROCESO, 
               ''BITACORARESETEO'', 
               @P_RET_PROCESO, 
               @P_MSG_PROCESO, 
               @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6
               
  END TRY

  BEGIN CATCH
    -- Captura la excepcion y almacena el mensaje de error en la variable @Error
    SET @P_RET_PROCESO = 2
    SET @P_MSG_PROCESO = CONCAT(''Linea '',ERROR_LINE(), '' - '' , ERROR_MESSAGE());
    
  END CATCH;
END
')