

UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Humana'
WHERE NUMERODECAMPO = 36024 AND IDIOMA = 'E' AND OPCIONINTERNA = 'F'


UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Humana'
WHERE NUMERODECAMPO = 36026 AND IDIOMA = 'E' AND OPCIONINTERNA = 'F'




