EXECUTE ('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49609, '' '', 0, ''Listado de Códigos de Balance'', ''Listado de Códigos de Balance'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 0, 9562, 0, 0, NULL, 0, NULL)
 ')


