EXECUTE('
IF OBJECT_ID (''dbo.CRE_EXCLUSIONES_ASISTENCIAS'') IS NOT NULL
DROP TABLE dbo.CRE_EXCLUSIONES_ASISTENCIAS

')


EXECUTE('
CREATE TABLE CRE_EXCLUSIONES_ASISTENCIAS
	(
	ASISTENCIA_JTS_OID      NUMERIC (15) NOT NULL,
	GRADUACION              VARCHAR (1),
	FRACCIONAMIENTO         VARCHAR (1),
	TZ_LOCK                 NUMERIC (15),
	CONSTRAINT PK_EXLUSIONES_ASISTENCIAS PRIMARY KEY (ASISTENCIA_JTS_OID)
	)

')

EXECUTE ('
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (550, 4368, NULL, ''CRE_EXCLUSIONES_ASISTENCIAS'', 0, ''CRE_EXCLUSIONES_ASISTENCIAS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

')

EXECUTE('
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4368, 1, ''Indice Principal'', 0, 44030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

')