UPDATE dbo.OPCIONES
SET DESCRIPCION = 'PERSONA HUMANA'
WHERE NUMERODECAMPO = 33352 AND IDIOMA = 'E' AND OPCIONINTERNA = 'F'


UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Persona Humana'
WHERE NUMERODECAMPO = 33352 AND IDIOMA = 'I' AND OPCIONINTERNA = 'F'


