EXECUTE('
-----------------------------
--NUEVOS CAMPOS DE LA VISTA--
-----------------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35364, '' '', 0, ''Bloqueo'', ''Bloqueo'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3452, ''BLOQUEO'', 0, NULL)
---
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35367, '' '', 0, ''Cancelación'', ''Cancelación'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3452, ''CANCELACION'', 0, NULL)
---
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35368, '' '', 0, ''JTS_OID'', ''JTS_OID'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3452, ''JTS_OID'', 0, NULL)
----
')