EXECUTE('

DELETE FROM DESCRIPTORES
WHERE IDENTIFICACION = 4510

INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (24, 4510, NULL, ''Vw cargo esp canal SECHEEP'', 0, ''VW_CANAL_CARGO_ESPECIFICO_2'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


DELETE FROM DICCIONARIO
WHERE TABLA = 4510


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45671, '' '', 0, ''ID_CABEZAL'', ''ID_CABEZAL'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''ID_CABEZAL'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45672, '' '', 0, ''ID_LINEA'', ''ID_LINEA'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''ID_LINEA'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45673, '' '', 0, ''NRO_COMPROBANTE_CLIENTE'', ''NRO_COMPROBANTE_CLIENTE'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''NRO_COMPROBANTE_CLIENTE'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45674, '' '', 0, ''LETRA'', ''LETRA'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''LETRA'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45675, '' '', 0, ''PUNTO_VENTA'', ''PUNTO_VENTA'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''PUNTO_VENTA'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45676, '' '', 0, ''TOTAL_CARGO_ESPECIFICO'', ''TOTAL_CARGO_ESPECIFICO'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''TOTAL_CARGO_ESPECIFICO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45677, '' '', 0, ''CODIGO_BARRAS'', ''CODIGO_BARRAS'', 120, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4510, ''CODIGO_BARRAS'', 0, NULL)


DELETE FROM INDICES WHERE NUMERODEARCHIVO=4510

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (4510, 1, ''Pk'', 0, 45671, 45672, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


DELETE FROM AYUDAS WHERE NUMERODEAYUDA = 45101

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (4510, 45101, ''Ayuda Cergo esp Canal SECHEEP'', '''', 0, ''45671;45672;45677;45673;45674;45675;45676;'', NULL, NULL, NULL, 0)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45678

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45678, '' '', 0, ''Cargo especifico Canal Scheep'', ''Cargo especifico Canal Scheep'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 45101, 0, 0, NULL, 0, NULL)


DELETE FROM DICCIONARIO WHERE NUMERODECAMPO = 45679

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45679, '' '', 0, ''Seleccionar Estado'', ''Seleccionar Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, NULL)


DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45679

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45679, ''E'', ''Anulados'', ''A'', ''A'')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45679, ''E'', ''Ingresados'', ''I'', ''I'')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45679, ''E'', ''Rendidos'', ''R'', ''R'')

DELETE FROM OPCIONES WHERE NUMERODECAMPO = 45629

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45629, ''E'', ''Anular'', ''A'', ''A'')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45629, ''E'', ''Reversar'', ''P'', ''P'')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (45629, ''E'', ''Rendir'', ''R'', ''R'')

')
