EXECUTE('

UPDATE dbo.DICCIONARIO
SET LARGO = 7
	, TIPODECAMPO = ''A''
	, DECIMALES = 0
	, EDICION = NULL
WHERE NUMERODECAMPO = 33754


ALTER TABLE BITACORA_ACTIVIDAD_ECONOMICA ALTER COLUMN INICIO_ACTIVIDAD VARCHAR(7)
')

