EXECUTE('
IF OBJECT_ID (''dbo.CRE_EXCLUSIONES_ASISTENCIAS'') IS NOT NULL
	DROP TABLE dbo.CRE_EXCLUSIONES_ASISTENCIAS
')

EXECUTE ('
CREATE TABLE dbo.CRE_EXCLUSIONES_ASISTENCIAS
	(
	ASISTENCIA_JTS_OID NUMERIC (15) NOT NULL,
	GRADUACION         NUMERIC (15),
	TZ_LOCK            NUMERIC (15),
	CONSTRAINT PK_EXLUSIONES_ASISTENCIAS PRIMARY KEY (ASISTENCIA_JTS_OID)
	)

')

EXECUTE('
UPDATE dbo.DICCIONARIO
SET LARGO = 15
	, TIPODECAMPO = ''N''
WHERE NUMERODECAMPO = 44031

')

EXECUTE('

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 44032

')

