EXECUTE('
-------------------
--METADATA VISTAS--
-------------------
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3546, NULL, ''Vista de documentos de PF'', 0, ''VW_PF_DOCUMENTOS_2'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35437, '' '', 0, ''Listado documentos de PF'', ''Listado documentos de PF'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 35461, 0, 0, NULL, 0, NULL)
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35463, '' '', 0, ''Tipo documento identificativo'', ''Tipo documento identificativo'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''TIPODOCUMENTO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35464, '' '', 0, ''Número documento identificativo'', ''Número Documento Identificativo'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''NUMERODOCUMENTO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35465, '' '', 0, ''Tipo documento físico'', ''Tipo documento físico'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''TIPO_DOC_FISICO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35466, '' '', 0, ''Número documento físico'', ''Número documento físico'', 20, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''NUM_DOC_FISICO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35467, '' '', 0, ''Apellido y Nombre'', ''Apellido y Nombre'', 61, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''APELLIDO_NOMBRE'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35468, '' '', 0, ''Tipo de Persona'', ''Tipo de Persona'', 14, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''TIPO_PERSONA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35469, '' '', 0, ''Nivel de Apertura'', ''Nivel de Apertura'', 15, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''NIVEL_APERTURA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35470, '' '', 0, ''Estado de la Persona'', ''Estado de la Persona'', 15, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''ESTADO_PERSONA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35471, '' '', 0, ''Motivo Inhabilitado'', ''Motivo Inhabilitado'', 35, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''MOTIVO_INHABILITADO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35472, '' '', 0, ''Número de la Persona'', ''Número de la Persona'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''NUMERO_PERSONA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35473, '' '', 0, ''Es empleado del Banco'', ''Es empleado del Banco'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3546, ''EMPLEADO_BC_BANCO'', 0, NULL)
----
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3546, 1, ''índice documentos PF'', 0, 35463, 35464, 35472, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3546, 35461, ''listado de documentos de PF'', '''', 0, ''35463R;35464R;35465;35466;35467;35468;35469;35470;35471;35472ROA1;'', NULL, NULL, NULL, 0)
----
----
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3547, NULL, ''Vista Tarjetas con Clase'', 0, ''VW_DSCCLASETARJETAS'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35478, '' '', 0, ''Titularidad'', ''Titularidad'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''TITULARIDAD'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35479, '' '', 0, ''ID Tarjeta'', ''ID Tarjeta'', 19, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''ID_TARJETA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35483, '' '', 0, ''Nro. Cliente'', ''Nro. Cliente'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''NRO_CLIENTE'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35484, '' '', 0, ''Tipo Tarjeta'', ''Tipo Tarjeta'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''TIPO_TARJETA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35485, '' '', 0, ''Descripción Tipo Tarjeta'', ''Descripción Tipo Tarjeta'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''DESCRIPCION'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35486, '' '', 0, ''Clase de Tarjeta'', ''Clase de Tarjeta'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''CLASE'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35487, '' '', 0, ''Nombre de Tarjeta'', ''Nombre de Tarjeta'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''NOMBRE_TARJETA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35488, '' '', 0, ''Permiso'', ''Permiso'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''PERMISO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35489, '' '', 0, ''Descripción Permiso'', ''Descripción Permiso'', 35, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''DESCRIPCION_PERMISO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35490, '' '', 0, ''Estado'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''ESTADO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35491, '' '', 0, ''Código Paquete'', ''Código Paquete'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''COD_PAQUETE'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35492, '' '', 0, ''Nro. Persona'', ''Nro. Persona'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3547, ''NRO_PERSONA'', 0, NULL)
----
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3547, 1, ''índice vista tarjetas'', 0, 35479, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3547, 35471, ''Listado Tarjetas'', '''', 0, ''35478OD2;35479ROA3;35483OA1;35484;35485;35486;35487;35490;35491;35492;35488;35489;'', NULL, NULL, NULL, 0)
----
----
UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 35471
WHERE NUMERODECAMPO = 9714
---
UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 35461
WHERE NUMERODECAMPO = 35238
---
UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 35461
WHERE NUMERODECAMPO = 35239
-------------------------------------
--MODIFICACIÓN PARÁMETROS GENERALES--
-------------------------------------
UPDATE dbo.PARAMETROSGENERALES
SET ALFA = ''''''2'''',''''4'''',''''9'''',''''X''''''
WHERE CODIGO = 101
----
')








