EXECUTE('
------------------------------
--AJUSTE EVENTOS PARA DPF TV--
------------------------------
UPDATE dbo.CI_CARGOS_X_EVENTO
SET ID_CARGO = 622
WHERE ID_CARGO = 624 AND ID_EVENTO = 8623
----
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (8625, ''CANCELACIÓN DPF TV INMOV'', 0)
----
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (624, 8625, 0, ''A'', 1037, '''', 1)
----
')