EXECUTE('
/****** Object:  StoredProcedure [dbo].[PA_ACTUASALDOSCAMPANIA]    Script Date: 02/06/2021 10:31:28 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
')
EXECUTE('
ALTER PROCEDURE [dbo].[PA_ACTUASALDOSCAMPANIA]  
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */
   @P_ID_PROCESO float(53),
   @P_DT_PROCESO datetime2(0),
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */
   @P_RET_PROCESO float(53)  OUTPUT,
   @P_MSG_PROCESO varchar(max)  OUTPUT
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
   BEGIN
      SET @P_RET_PROCESO = NULL
      SET @P_MSG_PROCESO = NULL
     /*
      *    
      *   El proceso se queda con todos los saldos con campaña distinta de 0, y que ya esta vencida
      *
      */
      DECLARE
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @CAMPANIAAUX_ float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @GRUPOAUX_ float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @CANTCAMP_ float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @PROCESO_OK_ float(53)
      DECLARE
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$JTS_OID float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$CAMPANIA float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$PAQUETE float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$CAMPANIA_ANT float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$GRUPO float(53), 
         @TABLA_REC$CLIENTE float(53), 
         @TABLA_REC$GRUPOCAMPANIA varchar(max), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$PRODUCTO float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$TIPOCTA float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$MONEDA float(53)
      SET @CANTCAMP_ = 0
      SET @PROCESO_OK_ = 0
      DECLARE
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$JTS_OID$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$CAMPANIA$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$PAQUETE$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$CAMPANIA_ANT$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
  @TABLA_REC$GRUPO$2 float(53), 
         @TABLA_REC$CLIENTE$2 float(53), 
         @TABLA_REC$GRUPOCAMPANIA$2 varchar(max), 
         /*
       *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$PRODUCTO$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$TIPOCTA$2 float(53), 
         /*
         *   SSMA warning messages:
         *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
         */
         @TABLA_REC$MONEDA$2 float(53)
      DECLARE
          TABLA CURSOR LOCAL FOR 
            SELECT 
               S.JTS_OID AS JTS_OID, 
               S.C1771 AS CAMPANIA, 
               S.C1770 AS PAQUETE, 
               S.C1666 AS CAMPANIA_ANT, 
               S.C1772 AS GRUPO, 
               S.C1803 AS CLIENTE, 
               C.GRUPO AS GRUPOCAMPANIA, 
               S.PRODUCTO AS PRODUCTO, 
               S.C1785 AS TIPOCTA, 
               S.MONEDA AS MONEDA
            FROM dbo.SALDOS  AS S with (nolock)
			INNER JOIN dbo.CLI_CAMPANIAS  AS C with (nolock)ON S.C1771 = C.COD_CAMPANIA
															AND S.C1771 <> 0
															AND (
																  SELECT PARAMETROS.FECHAPROCESO
																  FROM dbo.PARAMETROS with (nolock)
															   ) > C.VIGENCIA_HASTA 
															   AND C.TZ_LOCK = 0 
															   AND S.TZ_LOCK = 0

      OPEN TABLA
      WHILE 1 = 1
         BEGIN
            FETCH TABLA
                INTO 
                  @TABLA_REC$JTS_OID$2, 
                  @TABLA_REC$CAMPANIA$2, 
                  @TABLA_REC$PAQUETE$2, 
                  @TABLA_REC$CAMPANIA_ANT$2, 
                  @TABLA_REC$GRUPO$2, 
                  @TABLA_REC$CLIENTE$2, 
                  @TABLA_REC$GRUPOCAMPANIA$2, 
                  @TABLA_REC$PRODUCTO$2, 
                  @TABLA_REC$TIPOCTA$2, 
                  @TABLA_REC$MONEDA$2

            IF @@FETCH_STATUS = -1
               BREAK

            /*Loop que recorre los registros recuperados por el cursor*/
            IF @TABLA_REC$PAQUETE$2 <> 100
               BEGIN
                  /* si el paquete no es default*/
                  BEGIN
                     BEGIN TRY
                        SET @CAMPANIAAUX_ = 0
                        SELECT @CAMPANIAAUX_ = CLI_CLIENTES_PAQUETES.COD_CAMPANIA
                        FROM dbo.CLI_CLIENTES_PAQUETES with (nolock)
                        WHERE 
                           CLI_CLIENTES_PAQUETES.TZ_LOCK = 0 AND 
                           CLI_CLIENTES_PAQUETES.COD_CLIENTE = @TABLA_REC$CLIENTE$2 AND 
                           CLI_CLIENTES_PAQUETES.COD_PAQUETE = @TABLA_REC$PAQUETE$2

                        IF @CAMPANIAAUX_ = 0 OR @TABLA_REC$GRUPOCAMPANIA$2 = @TABLA_REC$GRUPO$2
                           SELECT @GRUPOAUX_ = CLI_PAQUETE_PRODUCTOS.GRUPO
                           FROM dbo.CLI_PAQUETE_PRODUCTOS with (nolock)
                           WHERE 
                              CLI_PAQUETE_PRODUCTOS.PRODUCTO = @TABLA_REC$PRODUCTO$2 AND 
                              CLI_PAQUETE_PRODUCTOS.COD_PAQUETE = @TABLA_REC$PAQUETE$2 AND 
                              CLI_PAQUETE_PRODUCTOS.MONEDA = @TABLA_REC$MONEDA$2 AND 
                              CLI_PAQUETE_PRODUCTOS.TZ_LOCK = 0

                        UPDATE dbo.CLI_CLIENTES_PAQUETES
                           SET 
                              COD_CAMPANIA = 0
                        WHERE 
                           CLI_CLIENTES_PAQUETES.TZ_LOCK = 0 AND 
                           CLI_CLIENTES_PAQUETES.COD_CLIENTE = @TABLA_REC$CLIENTE$2 AND 
                           CLI_CLIENTES_PAQUETES.COD_PAQUETE = @TABLA_REC$PAQUETE$2
                     END TRY
                     BEGIN CATCH
                        DECLARE @errornumber int
                        SET @errornumber = ERROR_NUMBER()
                        DECLARE @errormessage nvarchar(4000)
                        SET @errormessage = ERROR_MESSAGE()
						DECLARE @exceptionidentifier nvarchar(4000)
                        SELECT @exceptionidentifier =  ssma_oracle.db_error_get_oracle_exception_id(@errormessage, @errornumber)

                        BEGIN

                           /* Valores de Retorno.*/
                           SET @P_RET_PROCESO = 
                              ssma_oracle.db_error_sqlcode(@exceptionidentifier, @errornumber)

                           SET @P_MSG_PROCESO = 
                              ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier, @errornumber)

                           SET @PROCESO_OK_ = 1

                           DECLARE
                              @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION varchar(8000)

                           SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

                           EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
                              @P_ID_PROCESO = @P_ID_PROCESO, 
                              @P_FCH_PROCESO = @P_DT_PROCESO, 
                              @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA - Error UPDATE CLI_CLIENTES_PAQUETES'', 
                              @P_COD_ERROR = @P_RET_PROCESO, 
                              @P_MSG_ERROR = @P_MSG_PROCESO, 
                              @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION

                        END

                     END CATCH

                  END

                  BEGIN

                     BEGIN TRY
                        UPDATE dbo.SALDOS
                           SET 
                              C1666 = @TABLA_REC$CAMPANIA_ANT$2, 
                              C1771 = 0, 
                              C1772 = @GRUPOAUX_
                        WHERE SALDOS.JTS_OID = @TABLA_REC$JTS_OID$2 AND SALDOS.C1785 IN ( 1, 2, 3 )
                     END TRY

                     BEGIN CATCH

                        DECLARE
                           @errornumber$2 int

                        SET @errornumber$2 = ERROR_NUMBER()

                        DECLARE
                           @errormessage$2 nvarchar(4000)

                        SET @errormessage$2 = ERROR_MESSAGE()

                        DECLARE
                           @exceptionidentifier$2 nvarchar(4000)

                        SELECT @exceptionidentifier$2 = 
                           ssma_oracle.db_error_get_oracle_exception_id(@errormessage$2, @errornumber$2)

                        BEGIN

                           /* Valores de Retorno.*/
                           SET @P_RET_PROCESO = 
                              ssma_oracle.db_error_sqlcode(@exceptionidentifier$2, @errornumber$2)

                           SET @P_MSG_PROCESO = 
                              ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier$2, @errornumber$2)

                           SET @PROCESO_OK_ = 1

                           DECLARE
                              @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$2 varchar(8000)

                           SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$2 = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

                           EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
                              @P_ID_PROCESO = @P_ID_PROCESO, 
                              @P_FCH_PROCESO = @P_DT_PROCESO, 
                              @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA - Error UPDATE SALDOS CAMPANIA SALDOS 1 2 3'', 
                              @P_COD_ERROR = @P_RET_PROCESO, 
                              @P_MSG_ERROR = @P_MSG_PROCESO, 
                              @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$2

                        END

                     END CATCH

                  END

                  BEGIN

                     BEGIN TRY
                        UPDATE dbo.SALDOS
                           SET 
                             C1666 = @TABLA_REC$CAMPANIA_ANT$2, 
                              C1771 = 0
                        WHERE SALDOS.JTS_OID = @TABLA_REC$JTS_OID$2 AND SALDOS.C1785 NOT IN ( 1, 2, 3 )
                     END TRY

                     BEGIN CATCH

                        DECLARE
                           @errornumber$3 int

                        SET @errornumber$3 = ERROR_NUMBER()

                        DECLARE
                           @errormessage$3 nvarchar(4000)

                        SET @errormessage$3 = ERROR_MESSAGE()

                        DECLARE
                           @exceptionidentifier$3 nvarchar(4000)

                        SELECT @exceptionidentifier$3 = 
                           ssma_oracle.db_error_get_oracle_exception_id(@errormessage$3, @errornumber$3)

                        BEGIN

                           /* Valores de Retorno.*/
                           SET @P_RET_PROCESO = 
                              ssma_oracle.db_error_sqlcode(@exceptionidentifier$3, @errornumber$3)

                           SET @P_MSG_PROCESO = 
                              ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier$3, @errornumber$3)

                           SET @PROCESO_OK_ = 1

                           DECLARE
                              @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$3 varchar(8000)

                           SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$3 = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

                           EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
                              @P_ID_PROCESO = @P_ID_PROCESO, 
                              @P_FCH_PROCESO = @P_DT_PROCESO, 
                              @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA - Error UPDATE SALDOS CAMPANIA SALDOS NO 1 2 3'', 
                              @P_COD_ERROR = @P_RET_PROCESO, 
                              @P_MSG_ERROR = @P_MSG_PROCESO, 
                              @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$3

                        END

                     END CATCH

                  END

                  SET @CANTCAMP_ = @CANTCAMP_ + 1

               END
            ELSE 
               BEGIN

                  BEGIN

                     BEGIN TRY
                        UPDATE dbo.SALDOS
                           SET 
                              C1772 = 0, 
                              C1666 = @TABLA_REC$CAMPANIA_ANT$2, 
                              C1771 = 0
                        WHERE SALDOS.JTS_OID = @TABLA_REC$JTS_OID$2
                     END TRY

                     BEGIN CATCH

                        DECLARE
                           @errornumber$4 int

                        SET @errornumber$4 = ERROR_NUMBER()

                        DECLARE
                           @errormessage$4 nvarchar(4000)

                        SET @errormessage$4 = ERROR_MESSAGE()

                        DECLARE
                           @exceptionidentifier$4 nvarchar(4000)

                        SELECT @exceptionidentifier$4 = 
                           ssma_oracle.db_error_get_oracle_exception_id(@errormessage$4, @errornumber$4)

                        BEGIN

                           /* Valores de Retorno.*/
                           SET @P_RET_PROCESO = 
                              ssma_oracle.db_error_sqlcode(@exceptionidentifier$4, @errornumber$4)

                           SET @P_MSG_PROCESO = 
                              ssma_oracle.db_error_sqlerrm_0(@exceptionidentifier$4, @errornumber$4)

                           SET @PROCESO_OK_ = 1

                           DECLARE
                              @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$4 varchar(8000)

                           SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$4 = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

                           EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
                              @P_ID_PROCESO = @P_ID_PROCESO, 
                              @P_FCH_PROCESO = @P_DT_PROCESO, 
                              @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA - Error UPDATE SALDOS GRUPO'', 
                              @P_COD_ERROR = @P_RET_PROCESO, 
                              @P_MSG_ERROR = @P_MSG_PROCESO, 
                              @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$4

                        END

                     END CATCH

                  END

                  SET @CANTCAMP_ = @CANTCAMP_ + 1

               END

         END

      CLOSE TABLA

      DEALLOCATE TABLA

      IF @PROCESO_OK_ = 0
         BEGIN

            IF @@TRANCOUNT > 0
               COMMIT WORK 

            SET @P_RET_PROCESO = 1

            SET @P_MSG_PROCESO = ''Actualizacion de Saldos de Campaña Finalizo Correctamente''

            DECLARE
               @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$5 varchar(8000)

          --  SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$5 = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

            EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
               @P_ID_PROCESO = @P_ID_PROCESO, 
               @P_FCH_PROCESO = @P_DT_PROCESO, 
               @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA'', 
               @P_COD_ERROR = @P_RET_PROCESO, 
               @P_MSG_ERROR = @P_MSG_PROCESO, 
               @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$5

           SET @P_MSG_PROCESO = ''Se actualizaron '' + ISNULL(CAST(@CANTCAMP_ AS nvarchar(max)), '''') + '' campañas en saldos''

            DECLARE
               @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6 varchar(8000)

       --     SET @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6 = ssma_oracle.get_pv_varchar(''dbo'', ''PKG_CONSTANTES'', ''C_LOG_TIPO_INFORMACION'')

            EXECUTE dbo.PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO 
               @P_ID_PROCESO = @P_ID_PROCESO, 
               @P_FCH_PROCESO = @P_DT_PROCESO, 
               @P_NOM_PACKAGE = ''ACTUASALDOSCAMPANIA'', 
               @P_COD_ERROR = @P_RET_PROCESO, 
               @P_MSG_ERROR = @P_MSG_PROCESO, 
               @P_TIPO_ERROR = @PKG_CONSTANTES$C_LOG_TIPO_INFORMACION$6

         END
      ELSE 
         BEGIN

            IF @@TRANCOUNT > 0
               ROLLBACK WORK 

            SET @P_RET_PROCESO = 3

            SET @P_MSG_PROCESO = ''Actualizacion de Saldos de Campaña Finalizo con Errores''

         END

   END
')