EXECUTE('
INSERT INTO CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (2157, ''AH INTERES ADELANTADO'', 0)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (705, 2157, 0, ''A'', 1357, ''CONDICION IVA'', 2)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (706, 2157, 0, ''A'', 1357, ''COND PERCEPCION IVA'', 3)

INSERT INTO TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 3014, ''DEBITO INTERES ADELANTADO AH'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (6097, 2, 3014, 0)

INSERT INTO CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (6094, 2, 3014, 0)

UPDATE PRODUCTOS SET C6260=''N'' WHERE C6252 IN(5,6)

UPDATE PRODUCTOS SET C6258='' '' WHERE C6252 IN(6)

UPDATE PRODUCTOS SET C6258=''A'' WHERE C6250=50001
')