EXECUTE('
-------------------------------------
--AGREGAMOS CAMPOS CLAVE A LA VISTA--
-------------------------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50233, '' '', 0, ''Tr Real'', ''TRREAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''TRREAL'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50234, '' '', 0, ''Ordinal'', ''Ordinal'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ORDINAL'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50235, '' '', 0, ''Tr Virtual'', ''Tr Virtual'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''TRVIRTUAL'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50236, '' '', 0, ''Tr Tipo'', ''Tr Tipo'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''TRTIPO'', 0, NULL)
----
')
