EXECUTE('
UPDATE CO  
SET CO.DESCRIPCION= (CASE WHEN CO.MODALIDAD=''C'' THEN S.DESCRIP_FINANC     
	ELSE S.DESCRIP_NO_FINANC
	END)
FROM CLI_CLAOBJATRASO CO 
INNER JOIN CLI_CLASUBJETIVA S     
ON (CO.CATEGORIA=S.CATEGORIASUB) 
WHERE CO.TZ_LOCK=0
')