EXECUTE('
----------------------
--AJUSTE DE OPCIONES--
----------------------
DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 46098
----
')
EXECUTE('
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Altas'', ''A'', ''A'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Baja del cheque'', ''B'', ''B'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Desvinculación de personas del cheque '', ''D'', ''D'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''En revisión '', ''E'', ''E'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Modificaciones'', ''M'', ''M'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Rectificativas para cheques denunciados'', ''N'', ''N'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Rectificativas para cheques rechazados'', ''R'', ''R'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Fin de revisión'', ''S'', ''S'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (46098, ''E'', ''Vinculación de personas al cheque '', ''V'', ''V'')
----
')