--METADATA

EXECUTE('IF EXISTS (SELECT * FROM DESCRIPTORES WHERE IDENTIFICACION IN (5006,5007,5008,5010))
BEGIN

 DELETE FROM DESCRIPTORES WHERE IDENTIFICACION IN (5006,5007,5008,5010);
 
  INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
   VALUES (20, 5006, NULL, ''Cotizaciones BNA'', 0, ''CON_COTIZACIONES_BNA'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


  INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
   VALUES (20, 5007, NULL, ''Movimientos Impuestos ME'', 0, ''CON_MOVIMIENTOS_IMPUESTOS_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


  INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
  VALUES (20, 5008, NULL, ''Vista Movimientos Impuestos ME'', 0, ''VW_CON_MOVIMIENTOS_IMPUESTOS_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


  INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
  VALUES (20, 5010, NULL, ''Rubros contables Origen/Dest'', 0, ''CON_RUBRO_CONTABLE_ORIG_DEST_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

END
ELSE
BEGIN

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (20, 5006, NULL, ''Cotizaciones BNA'', 0, ''CON_COTIZACIONES_BNA'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (20, 5007, NULL, ''Movimientos Impuestos ME'', 0, ''CON_MOVIMIENTOS_IMPUESTOS_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (20, 5008, NULL, ''Vista Movimientos Impuestos ME'', 0, ''VW_CON_MOVIMIENTOS_IMPUESTOS_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')


INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (20, 5010, NULL, ''Rubros contables Origen/Dest'', 0, ''CON_RUBRO_CONTABLE_ORIG_DEST_ME'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')

END
IF EXISTS (SELECT * FROM DICCIONARIO WHERE TABLA IN (5006,5007,5008,5010))
BEGIN

DELETE FROM DICCIONARIO WHERE TABLA IN (5006,5007,5008,5010);

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49642, '' '', 3, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 64, 0, 5006, ''Moneda'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49643, '' '', 0, ''Fecha_Cotizacion'', ''Fecha Cotización'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5006, ''Fecha_Cotizacion'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49644, '' '', 0, ''TC_COMPRA'', ''TC COMPRA'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5006, ''TC_COMPRA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49645, '' '', 0, ''TC_VENTA'', ''TC VENTA'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5006, ''TC_VENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49647, '' '', 0, ''FECHAPROCESO'', ''Fecha de Proceso'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAPROCESO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49648, '' '', 0, ''SUCURSAL'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49649, '' '', 0, ''ASIENTO'', ''Asiento'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ASIENTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49650, '' '', 0, ''TRREAL'', ''TRREAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRREAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49651, '' '', 0, ''ORDINAL'', ''Ordinal'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ORDINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49652, '' '', 0, ''TRVIRTUAL'', ''TRVIRTUAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRVIRTUAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49653, '' '', 0, ''TRTIPO'', ''TRTIPO'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRTIPO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49654, '' '', 0, ''OPERACION'', ''Operacion'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''OPERACION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49655, '' '', 0, ''SUCURSAL_CUENTA'', ''Sucursal Cuenta'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49656, '' '', 3, ''MONEDA'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''MONEDA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49657, '' '', 0, ''CUENTA'', ''Cuenta'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49658, '' '', 0, ''RUBROCONTABLE'', ''Rubro Contable'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''RUBROCONTABLE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49659, '' '', 0, ''DEBITOCREDITO'', ''DebitoCredito'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''DEBITOCREDITO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49660, '' '', 0, ''FECHAVALOR_ORIGINAL'', ''Fecha Valor Original'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAVALOR_ORIGINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49661, '' '', 0, ''CAPITALREALIZADO'', ''Capital Realizado'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''CAPITALREALIZADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49662, '' '', 0, ''EQUIVALENTEMN'', ''EquivalenteMN'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''EQUIVALENTEMN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49663, '' '', 0, ''SALDO_JTS_OID'', ''SALDO_JTS_OID'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SALDO_JTS_OID'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49664, '' '', 0, ''JTS_OID_ORIGINAL'', ''JTS_OID_ORIGINAL'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''JTS_OID_ORIGINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49665, '' '', 0, ''EXTORNADO'', ''Extornado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''EXTORNADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49666, '' '', 0, ''FECHAPROCESO_MOV'', ''Fecha Proceso Mov'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAPROCESO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49667, '' '', 0, ''SUCURSAL_MOV'', ''Sucursal Mov'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49668, '' '', 0, ''ASIENTO_MOV'', ''Asiento Mov'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ASIENTO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49669, '' '', 0, ''TIPO_CAMBIO_MOV'', ''Tipo Cambio Mov'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TIPO_CAMBIO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49670, '' '', 0, ''IMPORTE_MOV'', ''Importe Mov'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''IMPORTE_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49671, '' '', 0, ''FECHAVALOR'', ''Fecha Valor'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAVALOR'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49672, '' '', 0, ''JTS_OID_EJECUCION'', ''JTS_OID_EJECUCION'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''JTS_OID_EJECUCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50230, '' '', 0, ''Resultado de la ejecución'', ''Resultado de la ejecución'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''RESULTADO_EJECUCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50231, '' '', 0, ''Detalle'', ''Detalle'', 50, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''DETALLE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50213, '' '', 0, ''ID_LIQUIDACION'', ''ID_LIQUIDACION'', 19, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ID_LIQUIDACION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50214, '' '', 0, ''FECHAPROCESO'', ''FECHAPROCESO'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5008, ''FECHAPROCESO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50215, '' '', 0, ''SUCURSAL'', ''SUCURSAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50216, '' '', 0, ''MONEDA'', ''MONEDA'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''MONEDA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50217, '' '', 0, ''ASIENTO'', ''ASIENTO'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ASIENTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50218, '' '', 0, ''IMPORTE'', ''IMPORTE'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 5008, ''IMPORTE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50219, '' '', 0, ''SUCURSAL_CUENTA'', ''SUCURSAL_CUENTA'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''SUCURSAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50220, '' '', 0, ''DEBITOCREDITO'', ''DEBITOCREDITO'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''DEBITOCREDITO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50221, '' '', 0, ''CUENTA'', ''CUENTA'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50222, '' '', 0, ''ORDINAL_CUENTA'', ''ORDINAL_CUENTA'', 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ORDINAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50226, '' '', 0, ''RUBRO_ORIGEN'', ''RUBRO_ORIGEN'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''RUBRO_ORIGEN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50227, '' '', 0, ''RUBRO_DESTINO'', ''RUBRO_DESTINO'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''RUBRO_DESTINO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50228, '' '', 0, ''MARCAAJUSTE'', ''MARCAAJUSTE'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''MARCAAJUSTE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50229, '' '', 0, ''CONCEPTO'', ''CONCEPTO'', 50, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''CONCEPTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50223, '' '', 0, ''Rubro contable origen'', ''Rubro contable origen'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 634, 0, 5010, ''RUBRO_ORIGEN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50224, '' '', 0, ''Rubro contable destino'', ''Rubro contable destino'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5010, ''RUBRO_DESTINO'', 0, NULL)



END
ELSE
BEGIN

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49642, '' '', 3, ''Moneda'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 64, 0, 5006, ''Moneda'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49643, '' '', 0, ''Fecha_Cotizacion'', ''Fecha Cotización'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5006, ''Fecha_Cotizacion'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49644, '' '', 0, ''TC_COMPRA'', ''TC COMPRA'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5006, ''TC_COMPRA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49645, '' '', 0, ''TC_VENTA'', ''TC VENTA'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5006, ''TC_VENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49647, '' '', 0, ''FECHAPROCESO'', ''Fecha de Proceso'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAPROCESO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49648, '' '', 0, ''SUCURSAL'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49649, '' '', 0, ''ASIENTO'', ''Asiento'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ASIENTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49650, '' '', 0, ''TRREAL'', ''TRREAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRREAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49651, '' '', 0, ''ORDINAL'', ''Ordinal'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ORDINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49652, '' '', 0, ''TRVIRTUAL'', ''TRVIRTUAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRVIRTUAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49653, '' '', 0, ''TRTIPO'', ''TRTIPO'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TRTIPO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49654, '' '', 0, ''OPERACION'', ''Operacion'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''OPERACION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49655, '' '', 0, ''SUCURSAL_CUENTA'', ''Sucursal Cuenta'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49656, '' '', 3, ''MONEDA'', ''Moneda'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''MONEDA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49657, '' '', 0, ''CUENTA'', ''Cuenta'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49658, '' '', 0, ''RUBROCONTABLE'', ''Rubro Contable'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''RUBROCONTABLE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49659, '' '', 0, ''DEBITOCREDITO'', ''DebitoCredito'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''DEBITOCREDITO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49660, '' '', 0, ''FECHAVALOR_ORIGINAL'', ''Fecha Valor Original'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAVALOR_ORIGINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49661, '' '', 0, ''CAPITALREALIZADO'', ''Capital Realizado'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''CAPITALREALIZADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49662, '' '', 0, ''EQUIVALENTEMN'', ''EquivalenteMN'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''EQUIVALENTEMN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49663, '' '', 0, ''SALDO_JTS_OID'', ''SALDO_JTS_OID'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SALDO_JTS_OID'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49664, '' '', 0, ''JTS_OID_ORIGINAL'', ''JTS_OID_ORIGINAL'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''JTS_OID_ORIGINAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49665, '' '', 0, ''EXTORNADO'', ''Extornado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''EXTORNADO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49666, '' '', 0, ''FECHAPROCESO_MOV'', ''Fecha Proceso Mov'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAPROCESO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49667, '' '', 0, ''SUCURSAL_MOV'', ''Sucursal Mov'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''SUCURSAL_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49668, '' '', 0, ''ASIENTO_MOV'', ''Asiento Mov'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''ASIENTO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49669, '' '', 0, ''TIPO_CAMBIO_MOV'', ''Tipo Cambio Mov'', 15, ''N'', 9, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''TIPO_CAMBIO_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49670, '' '', 0, ''IMPORTE_MOV'', ''Importe Mov'', 15, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''IMPORTE_MOV'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49671, '' '', 0, ''FECHAVALOR'', ''Fecha Valor'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5007, ''FECHAVALOR'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49672, '' '', 0, ''JTS_OID_EJECUCION'', ''JTS_OID_EJECUCION'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''JTS_OID_EJECUCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50230, '' '', 0, ''Resultado de la ejecución'', ''Resultado de la ejecución'', 4, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''RESULTADO_EJECUCION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50231, '' '', 0, ''Detalle'', ''Detalle'', 50, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5007, ''DETALLE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50213, '' '', 0, ''ID_LIQUIDACION'', ''ID_LIQUIDACION'', 19, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ID_LIQUIDACION'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50214, '' '', 0, ''FECHAPROCESO'', ''FECHAPROCESO'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 5008, ''FECHAPROCESO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50215, '' '', 0, ''SUCURSAL'', ''SUCURSAL'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''SUCURSAL'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50216, '' '', 0, ''MONEDA'', ''MONEDA'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''MONEDA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50217, '' '', 0, ''ASIENTO'', ''ASIENTO'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ASIENTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50218, '' '', 0, ''IMPORTE'', ''IMPORTE'', 15, ''N'', 2, ''I'', 0, 0, 0, 0, 0, 0, 0, 5008, ''IMPORTE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50219, '' '', 0, ''SUCURSAL_CUENTA'', ''SUCURSAL_CUENTA'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''SUCURSAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50220, '' '', 0, ''DEBITOCREDITO'', ''DEBITOCREDITO'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''DEBITOCREDITO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50221, '' '', 0, ''CUENTA'', ''CUENTA'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50222, '' '', 0, ''ORDINAL_CUENTA'', ''ORDINAL_CUENTA'', 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''ORDINAL_CUENTA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50226, '' '', 0, ''RUBRO_ORIGEN'', ''RUBRO_ORIGEN'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''RUBRO_ORIGEN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50227, '' '', 0, ''RUBRO_DESTINO'', ''RUBRO_DESTINO'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''RUBRO_DESTINO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50228, '' '', 0, ''MARCAAJUSTE'', ''MARCAAJUSTE'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''MARCAAJUSTE'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50229, '' '', 0, ''CONCEPTO'', ''CONCEPTO'', 50, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5008, ''CONCEPTO'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50223, '' '', 0, ''Rubro contable origen'', ''Rubro contable origen'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 634, 0, 5010, ''RUBRO_ORIGEN'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50224, '' '', 0, ''Rubro contable destino'', ''Rubro contable destino'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 5010, ''RUBRO_DESTINO'', 0, NULL)

END
 IF EXISTS (SELECT * FROM INDICES WHERE NUMERODEARCHIVO in (5006,5007,5008,5010))
BEGIN

 DELETE FROM INDICES WHERE NUMERODEARCHIVO in (5006,5007,5008,5010);

 INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5006, 1, ''Indice Cotizaciones BNA'', 0, 49642, 49643, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 1, ''Indice Movimientos ImpuestosME'', 0, 49647, 49648, 49649, 49650, 49651, 49652, 49653, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 2, ''Indice por JTS_OID'', 0, 49664, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 3, ''Indice por asiento'', 0, 49666, 49667, 49668, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5008, 1, ''pk'', 0, 50213, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5010, 1, ''Clave PK'', 0, 50223, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

END
ELSE
BEGIN

INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5006, 1, ''Indice Cotizaciones BNA'', 0, 49642, 49643, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 1, ''Indice Movimientos ImpuestosME'', 0, 49647, 49648, 49649, 49650, 49651, 49652, 49653, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 2, ''Indice por JTS_OID'', 0, 49664, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5007, 3, ''Indice por asiento'', 0, 49666, 49667, 49668, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5008, 1, ''pk'', 0, 50213, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


INSERT INTO INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (5010, 1, ''Clave PK'', 0, 50223, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

END
IF EXISTS (SELECT * FROM AYUDAS WHERE NUMERODEARCHIVO in (5006,5010))
BEGIN

 DELETE FROM AYUDAS WHERE NUMERODEARCHIVO in (5006,5010);

 INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (5006, 50061, ''Ayuda Cotizaciones BNA'', '''', 0, ''49642R;49643R;49644;49645;'', NULL, NULL, NULL, 0)


INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (5010, 50101, ''Ayuda rubros origen/ destino'', '''', 0, ''50223R;50224;'', NULL, NULL, NULL, 0)

 
END
ELSE
BEGIN

INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (5006, 50061, ''Ayuda Cotizaciones BNA'', '''', 0, ''49642R;49643R;49644;49645;'', NULL, NULL, NULL, 0)


INSERT INTO AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (5010, 50101, ''Ayuda rubros origen/ destino'', '''', 0, ''50223R;50224;'', NULL, NULL, NULL, 0)

END

IF EXISTS (SELECT * FROM DICCIONARIO WHERE TABLADEAYUDA IN (50061,50101))
BEGIN

 DELETE FROM DICCIONARIO WHERE TABLADEAYUDA IN (50061,50101);

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49646, '' '', 0, ''Ayuda Cotizaciones BNA'', ''Ayuda Cotizaciones BNA'', 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 50061, 0, 0, ''Ayuda Cotizaciones BNA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50225, '' '', 0, ''Ayuda Rubros'', ''Rubros'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 50101, 0, 0, ''AYUDA'', 0, NULL)

 
END
ELSE
BEGIN

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49646, '' '', 0, ''Ayuda Cotizaciones BNA'', ''Ayuda Cotizaciones BNA'', 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 50061, 0, 0, ''Ayuda Cotizaciones BNA'', 0, NULL)


INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (50225, '' '', 0, ''Ayuda Rubros'', ''Rubros'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 50101, 0, 0, ''AYUDA'', 0, NULL)


END
IF EXISTS (SELECT * FROM OPERACIONES WHERE IDENTIFICACION IN (2070,2072,2073))
BEGIN

 DELETE FROM OPERACIONES WHERE IDENTIFICACION IN (2070,2072,2073);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2070, ''ABMC Cotizaciones BNA'', ''ABMC Cotizaciones BNA'', ''2070'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, 0)


INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2072, ''Calculo Impuestos Movimiento Moneda Extranjera'', ''Calculo Impuestos Movimiento Moneda Extranjera'', ''2072'', ''N'', 500, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)


INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2073, ''ABMC Rubro operativo Origen / Destino'', ''ABMC Rubro operativo Origen / Destino'', ''2073'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

 
END
ELSE
BEGIN

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2070, ''ABMC Cotizaciones BNA'', ''ABMC Cotizaciones BNA'', ''2070'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''S'', ''S'', NULL, 0)


INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2072, ''Calculo Impuestos Movimiento Moneda Extranjera'', ''Calculo Impuestos Movimiento Moneda Extranjera'', ''2072'', ''N'', 500, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)


INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2001, 2073, ''ABMC Rubro operativo Origen / Destino'', ''ABMC Rubro operativo Origen / Destino'', ''2073'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)


END
')