EXECUTE ('

IF OBJECT_ID (''dbo.VW_VISTA_PLAZO_SALDO'') IS NOT NULL
	DROP VIEW dbo.VW_VISTA_PLAZO_SALDO
')

EXECUTE ('
CREATE VIEW VW_VISTA_PLAZO_SALDO(
SUCURSAL,
CUENTA,
NOMBRE,
PRODUCTO,
DESCRIPCION,
MONEDA,
CLIENTE,
PRODUCTOPLAZO,
"SALDO ACTUAL"

) AS 
SELECT S.SUCURSAL, S.CUENTA, VS.NOMBRE_CUENTA, S.PRODUCTO, P.C6251, S.MONEDA, S.C1803, R.ProductoPlazo, S.C1604 AS SALDO
FROM SALDOS AS S, VTA_SALDOS AS VS, PRODUCTOS AS P, VW_CLI_X_DOC AS D, DPF_RELPRODVISTA AS R
WHERE S.JTS_OID = VS.JTS_OID_SALDO AND S.PRODUCTO= P.C6250 AND S.C1803 = D.[CODIGOCLIENTE] AND S.PRODUCTO = R.ProductoVista
AND S.TZ_LOCK = 0 AND P.TZ_LOCK = 0 AND VS.TZ_LOCK = 0
')