EXECUTE('
----
INSERT INTO dbo.REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (9300, 3434, ''Voucher Agencieros'', '' '', 0, NULL, 0, 0, 0, ''N'')
----
')