EXECUTE('
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (6810, 7007, ''Pago prestamo por siniestro'', ''Pago prestamo por siniestro'', ''7007'', ''N'', 500, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)

ALTER TABLE CRE_ASEGURADORAS ADD CUENTAVTA NUMERIC(12)
ALTER TABLE CRE_ASEGURADORAS ADD CONC_CONT NUMERIC(10)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70600, '' '', 0, ''CUENTAVTA'', ''Cuenta vista'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 186, ''CUENTAVTA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70601, '' '', 0, ''CONC_CONT'', ''Concepto contable transitorio'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 186, ''CONC_CONT'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (7007, 1, 3017, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (7007, 2, 3024, 0)
')