EXECUTE('
--
ALTER TABLE CHE_CHEQUERAS DROP CONSTRAINT DF__CHE_CHEQU__VIA_P__6064695B
ALTER TABLE CHE_CHEQUERAS DROP COLUMN VIA_PAGO
ALTER TABLE CHE_CHEQUERAS ADD NOMINA_CIERRE VARCHAR(1)
ALTER TABLE CHE_CHEQUES ADD NOMINA_CIERRE VARCHAR(1)
--
')

EXECUTE('
IF OBJECT_ID (''dbo.VW_CHE_CHEQUES_NOMINA'') IS NOT NULL
	DROP VIEW dbo.VW_CHE_CHEQUES_NOMINA
')

EXECUTE('
CREATE   VIEW [dbo].[VW_CHE_CHEQUES_NOMINA](SUCURSAL,
											CUENTA,
											DENOMINACION_CUENTA,
											PRODUCTO,
											DESCRIPCION_PRODUCTO,
											MONEDA,SERIE,
											NUMERO_CHEQUE,
											IMPORTE,
											ESTADO,
											FECHA_ESTADO,
											TIPO_DOCUMENTO,
											NUMERO_DOCUMENTO)
AS
SELECT	CH.SUCURSAL,
		CH.CUENTA,
		V.NOMBRE_CUENTA,
		CH.PRODUCTO,
		P.C6251,
		CH.MONEDA,
		CH.SERIE,
		CH.NUMEROCHEQUE,
		CH.IMPORTE,
		E.DESCRIPCION,
		CH.FECHAESTADO,
		C.TIPODOC,
		C.NUMERODOC
FROM CHE_CHEQUES AS CH with (nolock)
LEFT JOIN SALDOS AS S with (nolock) ON CH.SUCURSAL=S.SUCURSAL 
										AND CH.PRODUCTO=S.PRODUCTO 
										AND CH.CUENTA=S.CUENTA 
										AND CH.MONEDA=S.MONEDA 
										AND CH.OPERACION=S.OPERACION 
										AND CH.ORDINAL=S.ORDINAL 
										AND S.TZ_LOCK = 0
LEFT JOIN VTA_SALDOS AS V with (nolock) ON S.JTS_OID = V.JTS_OID_SALDO 
										AND V.TZ_LOCK = 0
LEFT JOIN PRODUCTOS AS P with (nolock) ON CH.PRODUCTO = P.C6250 
										AND P.TZ_LOCK = 0
LEFT JOIN VW_CLI_X_DOC AS C with (nolock) ON S.C1803 = C.[CODIGOCLIENTE]
LEFT JOIN CHE_ESTADOSCHEQUES AS E with (nolock) ON CH.ESTADO = E.[CODIGO] 
												AND E.TZ_LOCK = 0
WHERE CH.TZ_LOCK = 0 AND CH.NOMINA_CIERRE = ''S''
')

EXECUTE('


UPDATE dbo.OPCIONES
SET DESCRIPCION = ''Si''
	, OPCIONINTERNA = ''S''
	, OPCIONDEPANTALLA = ''S''
WHERE NUMERODECAMPO = 34249 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''R''


UPDATE dbo.OPCIONES
SET DESCRIPCION = ''No''
	, OPCIONINTERNA = ''N''
	, OPCIONDEPANTALLA = ''N''
WHERE NUMERODECAMPO = 34249 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''T''


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35348, '' '', 0, ''NOMINA_CIERRE'', ''Pertenece a nomina de cierre'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 165, ''NOMINA_CIERRE'', 0, NULL)
')


