EXECUTE('



DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 41282
 


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41282, NULL, 0, ''Decimal'', ''Decimal'', 20, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Decimal'', 0, NULL)
 

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 41283
 



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41283, NULL, 0, ''Decimal1'', ''Decimal1'', 20, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Decimal1'', 0, NULL)
 



')