
EXECUTE('
DELETE FROM OPCIONES WHERE NUMERODECAMPO = 44750 AND OPCIONINTERNA = 8 

INSERT INTO OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44750, ''E'', ''Recaudación Propia del Ente'', ''8'', ''8'')

')