


-- Parche_NUNBCHACO_1089

-- Alterar Tabla GRL_ACREDITACIONES_MASIVAS
ALTER TABLE GRL_ACREDITACIONES_MASIVAS
ADD CANAL  VARCHAR (35) DEFAULT (' ') NULL;




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20221124_1NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fMTA4OQoNCi0tIEFsdGVyYXIgVGFibGEgR1JMX0FDUkVE
SVRBQ0lPTkVTX01BU0lWQVMNCkFMVEVSIFRBQkxFIEdSTF9BQ1JFRElUQUNJT05FU19NQVNJVkFT
CkFERCBDQU5BTCAgVkFSQ0hBUiAoMzUpIERFRkFVTFQgKCcgJykgTlVMTDsKDQoKCg0K', NULL, 0);
