EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35451, '' '', 0, ''Utiliza Contador Movimiento'', ''Utiliza Contador Movimiento'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3432, ''UTILIZA_CONTADOR_MOVIM'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35452, '' '', 0, ''En Promedio Mensual'', ''En Promedio Mensual'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3432, ''EN_PROMEDIO_MENSUAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35453, '' '', 0, ''Uso Comercial'', ''Uso Comercial'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3432, ''USO_COMERCIAL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35454, '' '', 0, ''Información Extendida'', ''Información Extendida'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3432, ''INFO_EXTENDIDA'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35455, '' '', 0, ''Débito / Crédito'', ''Débito / Crédito'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3432, ''DEBITO_CREDITO'', 0, NULL)


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35365, '' '', 0, ''AYUDA TIPOS MOVIMIENTOS'', NULL, 6, ''N'', 0, NULL, 0, 0, 0, 0, 0, 34321, 0, 0, ''AYUDA TIPOS MOVIMIENTOS'', 0, NULL)



INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (8000, 8260, ''ABMC - Tipos de Movimiento'', ''ABMC - Tipos de Movimiento'', ''8260'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')
