EXECUTE('
DELETE FROM AYUDAS WHERE NUMERODEAYUDA=70211

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (7021, 70211, ''Ay CRE_SITUACIONLABORAL'', '''', 0, ''70047R;70048R;70049R;70050;'', NULL, NULL, NULL, 0)

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO=70211
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, [LARGO], TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (70211, '' '', 0, ''Ayuda CRE_SITUACIONLABORAL'', NULL, 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 70211, 0, 0, NULL, 0, NULL)

DELETE FROM OPERACIONES WHERE IDENTIFICACION=7028
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (7700, 7028, ''ABMC - SITUACION LABORAL'', ''ABMC - SITUACION LABORAL'', ''7028'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
')