execute('CREATE or alter  VIEW dbo.[VW_IMPUESTOS]
AS
SELECT 
TIPOCARGO,
cct.SEGMENTO,
ID_IMPUESTO,
DESCRIPCION,
TASA,
MONEDA 
FROM CI_impuestos_TARIFAS CCT
JOIN 
	(

	  SELECT ID_IMPUESTO AS idCargo, DESCRIPCION,TIPO_IMPUESTO AS TipoCargo
	  FROM CI_IMPUESTOS
	  WHERE TIPO_IMPUESTO IN (2,3)
	) AS Impuesto
ON CCT.ID_IMPUESTO = Impuesto.idCargo
WHERE (TipoCargo = 2 AND SEGMENTO = ''AC'' OR TipoCargo = 3 AND SEGMENTO = ''0'') AND id_cliente = 0 AND TZ_LOCK = 0');