
EXECUTE('

ALTER VIEW VW_TJD_SOLICITUD_LINK
AS
SELECT
	TS.ID_SOLICITUD AS [Id_Solicitud],
	TS.TIPO_SOLICITUD AS [Tipo_Solicitud],
	TTN.DESCRIPCION AS [Descripción_Tipo_Solicitud],
	TS.ESTADO AS [Estado_Solicitud],
	O.DESCRIPCION AS [Descripción_Estado_Solicitud],
	''CUIL'' AS [Tipo_Documento],
	TS.CUIL AS [Nro_Documento],
	TS.APELLIDO AS [Apellido],
	TS.NOMBRE AS [Nombre],
	TS.NRO_TARJETA_BASE AS [Número_de_Tarjeta_Base],
	CASE WHEN TT.ID_TARJETA  IS NULL THEN ''''
	ELSE TT.ID_TARJETA
	END [Número_de_Tarjeta_Completa],
	TS.USUARIO_SOLICITUD AS [Usuario_Solicitud],
	TS.FECHA_SOLICITUD AS [Fecha_Solicitud],
	TS.HORA_SOLICITUD AS [Hora_Solicitud]
FROM
	TJD_SOLICITUD_LINK TS WITH (nolock)
INNER JOIN TJD_TIPOS_NOVEDADES_LINK TTN WITH (nolock) ON
	TS.TIPO_SOLICITUD = TTN.CODIGO_LINK
LEFT JOIN TJD_TARJETAS TT WITH (nolock) ON TS.NRO_TARJETA_BASE = TT.ID_TARJETA_BASE 
LEFT JOIN OPCIONES O WITH (nolock) ON
	TS.ESTADO = O.OPCIONINTERNA
	AND O.IDIOMA = ''E''
	AND O.NUMERODECAMPO = 34812
WHERE TS.TZ_LOCK = 0
	AND TTN.TZ_LOCK = 0;


')
