EXECUTE ('

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 37401, ''Ayuda para clientes'', '''', 0, ''1146R;1059;2639;2636;2635;9103;2638;'', ''Cliente;Nombre Cliente;Nivel Cliente;Tipo Cliente;Código Bloqueo;Motivo Inhabilitado;Estado Cliente;'', ''TOP/CLIENTES'', ''VW_CLIENTES_TODOS'', 0)



INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37401, NULL, 0, ''Ayuda para vista de clientes'', ''Ayuda Clientes'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 37401, 0, 0, ''AYUDA_CLIENTES'', 0, NULL)

')




