EXECUTE('

IF OBJECT_ID (''dbo.VW_CHEQUES_OTRO_BCO_SIN_IMG_DEPOSITOS'') IS NOT NULL
	DROP VIEW dbo.VW_CHEQUES_OTRO_BCO_SIN_IMG_DEPOSITOS

')


EXECUTE('

CREATE   VIEW [dbo].[VW_CHEQUES_OTRO_BCO_SIN_IMG_DEPOSITOS] (
																	   NRO_DEPOSITO,
																	   SUCURSAL,
																	   FECHA,
																	   HORA,
																	   CANTIDAD_CHEQUES,
																	   ASIENTO,
																	   USUARIO)
AS 
SELECT	s.NUMERO_DEPOSITO,
		s.SUCURSAL_DE_INGRESO,
		s.FECHA_ALTA,
		m.HORASISTEMA,
		COUNT(s.NUMERO_CHEQUE),
		s.NRO_ASIENTO,
		s.[CODIGO_USUARIO]
FROM	PARAMETROSGENERALES P WITH (nolock)
INNER JOIN CLE_CHEQUES_SALIENTE s with (nolock)ON s.BANCO_GIRADO<>P.NUMERICO
												AND s.TZ_LOCK =0 
												AND P.[CODIGO] = 2
												and NOT EXISTS (SELECT * 
																FROM CLE_IMG_CHEQUES WITH(NOLOCK)
																WHERE CMC7=s.CMC7 AND FECHAPROCESO=s.FECHA_ALTA)
LEFT JOIN MOVIMIENTOS_CONTABLES m with (nolock) on s.NRO_ASIENTO = m.ASIENTO 
												and s.RUBRO_CONTABLE = m.RUBROCONTABLE
												AND m.FECHAPROCESO=s.FECHA_ALTA
												AND m.SUCURSAL=s.SUCURSAL_DE_INGRESO
GROUP BY	s.NUMERO_DEPOSITO,  
			s.NRO_ASIENTO, 
			s.SUCURSAL_DE_INGRESO, 
			s.FECHA_ALTA, 
			s.[CODIGO_USUARIO], 
			m.HORASISTEMA
')


