
EXECUTE('
DELETE FROM REPORTESJASPER WHERE IDENTIFICACION =3759

INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (3759, 1, NULL, 0, 0, 1)

DELETE FROM CON_EQUIVALENCIA_CARGO_IMPOSITIVO

INSERT INTO CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 1, ''C'', 1, ''PRUEBA'')


INSERT INTO CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 3, ''C'', 3, ''IVA RETENCION'')


INSERT INTO CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 4, ''C'', 4, ''IGA'')


INSERT INTO CON_EQUIVALENCIA_CARGO_IMPOSITIVO (TZ_LOCK, TIPO_IMPUESTO, CARGO_O_IMPUESTO, TIPO_CARGO_IMPOSITIVO, DESCRIPCION)
VALUES (0, 12, ''C'', 12, ''IIBB CABA RET'')


DELETE FROM CON_REGIMEN_CERTIF_RET

INSERT INTO CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN)
VALUES (0, 2784, 3, ''20230419'', '' Intereses por otro tipo de Operaciones'')


INSERT INTO CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN)
VALUES (0, 2784, 4, ''20230419'', '' Intereses por otro tipo de Operaciones'')


INSERT INTO CON_REGIMEN_CERTIF_RET (TZ_LOCK, CODIGO_REGIMEN, TIPO_CARGO_IMPOSITIVO, VIGENCIA_DESDE, DESCRIPCION_REGIMEN)
VALUES (0, 2784, 12, ''20230419'', '' Intereses por otro tipo de Operaciones'')

DELETE FROM OPERACIONES WHERE IDENTIFICACION = 2091


INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (2080, 2091, ''Sub Ope Impresión Cert Retención en Opes online'', ''Sub Ope Impresión Cert Retención en Opes online'', ''2091'', ''N'', NULL, NULL, ''P'', 0, NULL, 1, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)


')
