EXECUTE('
----
DELETE FROM dbo.DESCRIPTORES
WHERE TITULO = 35 AND IDENTIFICACION = 3573
--
DELETE FROM dbo.DESCRIPTORES
WHERE TITULO = 35 AND IDENTIFICACION = 3569
----
DELETE FROM dbo.DICCIONARIO
WHERE TABLA = 3573
--
DELETE FROM dbo.DICCIONARIO
WHERE TABLA = 3569
----
DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 3573
--
DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 3569
----
DELETE FROM dbo.AYUDAS
WHERE NUMERODEARCHIVO = 3573
--
DELETE FROM dbo.AYUDAS
WHERE NUMERODEARCHIVO = 3569
----
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 35738
----
')
EXECUTE('
--------------------------------
--TABLA CLE_PREVALENCIA_CAUSAL--
--------------------------------
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3573, NULL, ''Prevalencias causales clearing'', 0, ''CLE_PREVALENCIA_CAUSAL'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35730, '' '', 0, ''ID Prevalencia'', ''ID Prevalencia'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3573, ''ID_PREVALENCIA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35731, '' '', 0, ''Funcionalidad'', ''Funcionalidad'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3573, ''FUNCIONALIDAD'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35732, '' '', 0, ''Causal depositaria'', ''Causal depositaria'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3573, ''CAUSAL_DEPOSITARIA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35733, '' '', 0, ''Causal girada'', ''Causal entidad girada'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3573, ''CAUSAL_GIRADA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35798, '' '', 0, ''Causal prevaleciente'', ''Causal prevaleciente'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3573, ''CAUSAL_PREVALECIENTE'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35856, '' '', 0, ''Causal interna'', ''Código de Causal'', 2, ''N'', 0, NULL, 0, 0, 0, 0, 180, 0, 0, 3573, ''CODIGO_CAUSAL_INTERNO'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35857, '' '', 0, ''Descripción Causal'', ''Descripción Causal'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3573, ''DESCRIPCION'', 0, NULL)
----
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3573, 1, ''índice prevalencia causales'', 0, 35730, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35855, '' '', 0, ''Numerador Prevalencias Causales'', ''Numerador Prevalencias Causales'', 5, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 0, ''C35855'', 0, NULL)
----
INSERT INTO dbo.NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (35855, 1, 1, '' '', NULL, 1, 1, 99999, ''Numerador Prevalencias Causales'', ''T'')
-------------------------------------------
--VISTA VW_CLE_PREVALENCIA_CAUSAL_CHEQUES--
-------------------------------------------
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (35, 3569, NULL, ''Prevalencias causales cheques'', 0, ''VW_CLE_PREVALENCIA_CAUSAL_CHEQUES'', ''D'', NULL, NULL, ''TOP/CLIENTES'', NULL, ''N'')
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35734, '' '', 0, ''ID prevalencia'', ''ID prevalencia'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''ID_PREVALENCIA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35735, '' '', 0, ''Causal depositaria'', ''Causal depositaria'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''CAUSAL_DEPOSITARIA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35736, '' '', 0, ''Desc. causal depositaria'', ''Descripción causal depositaria'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''DESCRIPCION_CAUSAL_DEP'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35737, '' '', 0, ''Causal entidad girada'', ''Causal entidad girada'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''CAUSAL_GIRADA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35853, '' '', 0, ''Desc. causal entidad girada'', ''Descripción causal girada'', 30, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''DESCRIPCION_CAUSAL_GIRADA'', 0, NULL)
--
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35854, '' '', 0, ''Causal prevaleciente'', ''Causal prevaleciente'', 3, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3569, ''CAUSAL_PREVALECIENTE'', 0, NULL)
----
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3569, 1, ''índice prev. causales cheques'', 0, 35734, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
----
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (3569, 35691, ''Listado prev. causales cheques'', '''', 0, ''35734ROA1;35735;35736;35737;35853;35854;'', NULL, NULL, NULL, 0)
----
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35738, '' '', 0, ''Listado prev. causales cheque'', ''Listado prev. causales cheque'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 35691, 0, 0, ''C35738'', 0, NULL)
-------------------------------
--AJUSTE CAMPO CON REFERENCIA--
-------------------------------
UPDATE dbo.DICCIONARIO
SET REFERENCIA = 0
WHERE NUMERODECAMPO = 35766
-----
')
