EXECUTE('
IF OBJECT_ID (''dbo.VTA_TRANSFERENCIAS'') IS NOT NULL
	DROP TABLE dbo.VTA_TRANSFERENCIAS
')
EXECUTE('
CREATE TABLE dbo.VTA_TRANSFERENCIAS
	(
	TZ_LOCK            NUMERIC (15) DEFAULT ((0)) NOT NULL,
	OP_NUMERO          NUMERIC (12) DEFAULT ((0)) NOT NULL,
	OP_FECHA_PRES      DATETIME,
	OP_CLASE_TRANS     VARCHAR (1) DEFAULT ('' '') NOT NULL,
	OP_TIPO            NUMERIC (3) DEFAULT ((0)),
	OP_FORMA_ING       VARCHAR (1) DEFAULT ('' ''),
	OP_MONEDA          NUMERIC (4) DEFAULT ((0)),
	OP_IMPORTE         NUMERIC (15, 2) DEFAULT ((0)),
	OP_MOTIVO          VARCHAR (200) DEFAULT ('' ''),
	OP_REFERENCIA      VARCHAR (3) DEFAULT ('' ''),
	OP_INFO_REF        VARCHAR (15) DEFAULT ('' ''),
	OP_INFO_AD         VARCHAR (12) DEFAULT ('' ''),
	ORD_CBU            VARCHAR (22) DEFAULT ('' ''),
	ORD_TIPO_DOC       VARCHAR (4) DEFAULT ('' ''),
	ORD_NRO_DOC        NUMERIC (11) DEFAULT ((0)),
	ORD_CLIENTE        NUMERIC (12) DEFAULT ((0)),
	ORD_NOMBRE         VARCHAR (70) DEFAULT ('' ''),
	ORD_CUENTA         NUMERIC (12) DEFAULT ((0)),
	ORD_JTS_OID_CUENTA NUMERIC (10) DEFAULT ((0)),
	BEN_CBU            VARCHAR (22) DEFAULT ('' ''),
	BEN_TIPO_CTA       VARCHAR (2) DEFAULT ('' ''),
	BEN_BANCO          NUMERIC (6) DEFAULT ((0)),
	BEN_SUCURSAL       NUMERIC (17) DEFAULT ((0)),
	BEN_JTS_OID_CUENTA NUMERIC (10) DEFAULT ((0)),
	BEN_TIPO_DOC       VARCHAR (4) DEFAULT ('' ''),
	BEN_NRO_DOC        NUMERIC (11) DEFAULT ((0)),
	BEN_NOMBRE         VARCHAR (50) DEFAULT ('' ''),
	BEN_MISMO_TITULAR  VARCHAR (1) DEFAULT ('' ''),
	BEN_USO_JUDICIAL   VARCHAR (1) DEFAULT ('' ''),
	FECHA_PAGO         DATETIME,
	ESTADO             VARCHAR (2) DEFAULT ('' ''),
	MOTIVO_RECHAZO     NUMERIC (3) DEFAULT ((0)),
	FECHA_ESTADO       DATETIME,
	CONTABILIZADA      VARCHAR (1) DEFAULT ('' ''),
	NUMERO_ASIENTO     NUMERIC (10) DEFAULT ((0)),
	SUCURSAL_ASIENTO   NUMERIC (5) DEFAULT ((0)),
	FECHA_ASIENTO      DATETIME,
	OPERATORIA_BCRA    VARCHAR (3),
	CONSTRAINT PK_VTA_TRANSFERENCIAS_01 PRIMARY KEY (OP_NUMERO, OP_CLASE_TRANS)
	)
')

