EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49114, '' '', 0, ''Asiento'', ''Asiento'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4905, ''ASIENTO'', 0, NULL)
')