/****** Object:  StoredProcedure [dbo].[SP_TIENE_CODBLOQ]    Script Date: 24/02/2021 8:35:48 ******/
DROP PROCEDURE [dbo].[SP_TIENE_CODBLOQ]
GO

/****** Object:  StoredProcedure [dbo].[SP_TIENE_CODBLOQ]    Script Date: 24/02/2021 8:35:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_TIENE_CODBLOQ]
@p_JTSOID NUMERIC(10),
@p_ACCION VARCHAR(2),
@p_TIPO	  VARCHAR(2),
@p_GRUPO  VARCHAR(8),
@p_CANT   NUMERIC(5) OUTPUT
AS
BEGIN
DECLARE @Cod	VARCHAR (200)
DECLARE @Cod2	VARCHAR (200)
DECLARE @Cant	NUMERIC(5)
	IF @p_ACCION = 'B'
BEGIN
	IF @p_TIPO = 'B'
BEGIN
	SELECT @p_CANT = COUNT(*) 
	FROM GRL_REL_BLOQUEO_SEGURIDAD with (nolock)
	WHERE GRUPO_BLOQUEO = @p_GRUPO 
			AND COD_BLOQUEO NOT IN (997,998,999) 
			AND TZ_LOCK = 0
END 
IF @p_TIPO = 'E'
BEGIN
	SELECT @p_CANT = COUNT(*) 
	FROM GRL_REL_BLOQUEO_SEGURIDAD with (nolock)
	WHERE GRUPO_BLOQUEO = @p_GRUPO 
		AND COD_BLOQUEO IN (997,998,999) 
		AND TZ_LOCK = 0
END 
END
IF @p_ACCION = 'D'
BEGIN
IF @p_TIPO = 'B'
BEGIN
SELECT @p_CANT = COUNT(*) 
FROM GRL_BLOQUEOS with (nolock)
WHERE SALDO_JTS_OID = @p_JTSOID 
		AND ESTADO = 1 
		AND COD_BLOQUEO IN 
							(	SELECT COD_BLOQUEO 
								FROM GRL_REL_BLOQUEO_SEGURIDAD with (nolock) 
								WHERE GRUPO_DESBLOQUEO = @p_GRUPO 
									AND COD_BLOQUEO NOT IN (997,998,999) 
									AND TZ_LOCK = 0
							) 
		AND TZ_LOCK = 0
END 
IF @p_TIPO = 'E'
BEGIN
SELECT @p_CANT = COUNT(*) 
FROM GRL_BLOQUEOS with (nolock)
WHERE SALDO_JTS_OID = @p_JTSOID 
		AND ESTADO = 1 
		AND COD_BLOQUEO IN 
						(	SELECT COD_BLOQUEO 
							FROM GRL_REL_BLOQUEO_SEGURIDAD with (nolock)
							WHERE GRUPO_DESBLOQUEO = @p_GRUPO 
									AND COD_BLOQUEO IN (997,998,999) 
									AND TZ_LOCK = 0
						) 
		AND TZ_LOCK = 0
END
END 
PRINT @p_CANT
END
GO


