EXECUTE('
UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 2
WHERE CODIGO_OPERACION = 8606 

UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 0
WHERE CODIGO_OPERACION = 8602 AND CODIGO_INTERNO_MOV = 1

UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 0
WHERE CODIGO_OPERACION = 8608 AND CODIGO_INTERNO_MOV = 1

UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 0
WHERE CODIGO_OPERACION = 8613 AND CODIGO_INTERNO_MOV = 1

UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 0
WHERE CODIGO_OPERACION = 8621 AND CODIGO_INTERNO_MOV = 1

UPDATE dbo.CODIGO_TRANSACCIONES
SET CODIGO_INTERNO_MOV = 0
WHERE CODIGO_OPERACION = 8601 AND CODIGO_INTERNO_MOV = 1



--- renovacion y cancelacion dpf

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 106, ''Pago Plazo Fijo'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 1, 106, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 15, 106, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 16, 106, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 17, 106, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 18, 106, 0)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 107, ''Renovación Plazo fijo'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 11, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 12, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 13, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 14, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 3, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 5, 107, 0)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8620, 6, 107, 0)

--- Traspaso entre cuentas

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 108, ''Débito Traspaso entre cuentas'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8605, 1, 108, 0)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 109, ''Crédito Traspaso entre cuentas'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8605, 2, 109, 0)


--- Cobertura entre cuentas

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 110, ''Débito Cobertura pool de cuentas'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8614, 1, 110, 0)

INSERT INTO dbo.TTR_CODIGO_TRANSACCION_DEF (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM, EN_PROMEDIO_MENSUAL, USO_COMERCIAL, INFO_EXTENDIDA, GRUPO, TIPO)
VALUES (0, 111, ''Crédito Cobertura pool de cuentas'', ''N'', NULL, '' '', ''N'', 0, NULL)

INSERT INTO dbo.CODIGO_TRANSACCIONES (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK)
VALUES (8614, 2, 111, 0)
')


