--METADATA
-- MODIFICACICON CAMPO 5793

EXECUTE('        
IF EXISTS (SELECT a.NUMERODECAMPO  FROM DICCIONARIO A WHERE NUMERODECAMPO = 5793)
BEGIN

 DELETE FROM DICCIONARIO 
     WHERE NUMERODECAMPO = 5793;
 
    INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (5793, '' '', 0, ''Rol'', ''Rol'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 7611, 0, 762, ''ROLE_NAME'', 0, NULL);
   

END
ELSE
BEGIN
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (5793, '' '', 0, ''Rol'', ''Rol'', 8, ''A'', 0, NULL, 0, 0, 0, 0, 0, 7611, 0, 762, ''ROLE_NAME'', 0, NULL);

END
')
