EXECUTE('
DELETE	FROM RESTRICCIONES WHERE GRUPO=''ACTIVAS''

INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''09000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''10000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''10010000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)

INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''10020000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''10030000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''12000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''20000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''20010000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''20020000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''20030000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''20800000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''21000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''24000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''24450000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''25000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''26000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''27000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''28000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''28020000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''28500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''29000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''29100000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''30000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''31000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''31500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''32000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35010000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35020000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35030000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35040000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35050000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35100000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503535'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503551'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503553'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503554'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503557'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503563'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503573'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503577'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503578'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503579'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503582'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503583'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503584'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503585'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503588'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503606'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503607'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503610'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503612'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503613'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503614'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503615'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503616'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503619'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503620'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503621'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503623'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503624'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503640'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503641'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503642'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503649'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503688'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35503689'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35510000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35520000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35530000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35540000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''35600000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''36500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''37500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''38000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''39990000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''40000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''46000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''47000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''48000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50010000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50020000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50030000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50040000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50050000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50060000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''50070000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''54000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55000000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006062'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006063'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006064'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006065'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006066'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006067'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006068'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006069'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006070'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006071'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''55006082'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''58000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''59400000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''60000000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''60000000'', ''ACTIVAS'', ''Q'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''60006850'', ''ACTIVAS'', ''Q'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''65000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''66000000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''66500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''67000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68100000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68200000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206083'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206084'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206085'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206086'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206087'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206088'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206089'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206090'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206091'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206092'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206093'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206094'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206095'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206096'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206097'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206098'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68206099'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68500000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68500159'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68505930'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506854'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506855'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506856'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506857'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506858'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506859'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506867'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506868'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506869'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506870'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506871'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506872'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506873'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506874'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506875'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68506876'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508001'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508002'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508012'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508026'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508052'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508054'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508059'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508069'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508073'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68508074'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68509202'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68509216'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68600000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''68800000'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''70000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''71000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''72000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''73000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''74000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''75000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''75900000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''76000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''76500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''78000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008063'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008064'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008178'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008179'', ''ACTIVAS'', ''O'', NULL, 1, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''81000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''81010000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''81500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''82000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''84000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''86000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''86920000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''87000000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''87100000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''87500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99290000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99300000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99310000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99500000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99900000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)


INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''99990000'', ''ACTIVAS'', ''O'', NULL, 0, NULL)

')
