EXECUTE('
IF OBJECT_ID (''dbo.SNP_MOTIVOS_RECHAZO'') IS NOT NULL
	DROP TABLE dbo.SNP_MOTIVOS_RECHAZO
')
EXECUTE('
CREATE TABLE dbo.SNP_MOTIVOS_RECHAZO
	(
	TZ_LOCK        NUMERIC (15) DEFAULT ((0)) NOT NULL,
	ID_MOTIVO      NUMERIC (3) DEFAULT ((0)) NOT NULL,
	FUNCIONALIDAD  VARCHAR (2) DEFAULT ('' ''),
	CODIGO_NACHA   VARCHAR (3) DEFAULT ('' ''),
	DESCRIPCION    VARCHAR (80) DEFAULT ('' ''),
	ENTIDAD_CAMARA VARCHAR (1) DEFAULT ('' ''),
	CONSTRAINT PK_SNP_MOTIVOS_RECHAZO_01 PRIMARY KEY (ID_MOTIVO)
	)
')

