
UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Alta'
WHERE NUMERODECAMPO = 901 AND IDIOMA = 'E' AND OPCIONINTERNA = 'A'

UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Baja'
WHERE NUMERODECAMPO = 901 AND IDIOMA = 'E' AND OPCIONINTERNA = 'B'

UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Consulta'
WHERE NUMERODECAMPO = 901 AND IDIOMA = 'E' AND OPCIONINTERNA = 'C'

UPDATE dbo.OPCIONES
SET DESCRIPCION = 'Modificación'
WHERE NUMERODECAMPO = 901 AND IDIOMA = 'E' AND OPCIONINTERNA = 'M'
