EXECUTE('
IF OBJECT_ID (''dbo.ITF_I2000_CLIENTES'') IS NOT NULL
	DROP TABLE dbo.ITF_I2000_CLIENTES
')

EXECUTE('
CREATE TABLE dbo.ITF_I2000_CLIENTES
	(
	CODNOVEDAD       VARCHAR (1),
	TIPODOC          VARCHAR (4),
	NUMDOC           VARCHAR (20),
	SEGTIPODOC       VARCHAR (4),
	SEGNUMDOC        VARCHAR (20),
	CODTIPOINDIVIDUO VARCHAR (1),
	DENOMINACIONCLI  VARCHAR (50),
	CODSUCURSAL      VARCHAR (4),
	CODACTIVIDAD     VARCHAR (4),
	FECINICIO        VARCHAR (8),
	DOMICILIOCLI     VARCHAR (20),
	NUMERO           VARCHAR (5),
	PISO             VARCHAR (2),
	DEPARTAMENTO     VARCHAR (3),
	LOCALIDAD        VARCHAR (13),
	CODPOSTAL        VARCHAR (4),
	TELEFONO         VARCHAR (12),
	CODPAIS          VARCHAR (5),
	CODPROVINCIA     VARCHAR (2),
	CODSISTEMA       VARCHAR (1),
	FECPROCESO       NUMERIC (8),
	ESTADO           VARCHAR (1),
	DESCESTADO       VARCHAR (50)
	)
')