
Execute('
IF EXISTS (SELECT a.IDENTIFICACION  FROM TRANSACCIONES A WHERE IDENTIFICACION = 952)
BEGIN

 DELETE FROM TRANSACCIONES WHERE IDENTIFICACION = 952;
 INSERT INTO dbo.TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
 VALUES (800, 952, ''S'', ''Control De Baja ABMC 2'', ''Control De Baja ABMC'', ''C'', 0, 0);
END
ELSE
BEGIN
 INSERT INTO dbo.TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
 VALUES (800, 952, ''S'', ''Control De Baja ABMC 2'', ''Control De Baja ABMC'', ''C'', 0, 0);
END

IF EXISTS (SELECT a.IDENTIFICACION  FROM TRANSACCIONES A WHERE IDENTIFICACION = 951)
BEGIN

 DELETE FROM TRANSACCIONES WHERE IDENTIFICACION = 951;
 INSERT INTO dbo.TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
 VALUES (800, 951, ''S'', ''Control De Baja ABMC'', ''Control De Baja ABMC'', ''C'', 0, 0);
END
ELSE
BEGIN
 INSERT INTO dbo.TRANSACCIONES (TITULO, IDENTIFICACION, TIPO, NOMBRE, DESCRIPCION, TIPODETRANSACCION, NUMERODETABLA, REGISTRODESALIDA)
 VALUES (800, 951, ''S'', ''Control De Baja ABMC'', ''Control De Baja ABMC'', ''C'', 0, 0);
END
')

