EXECUTE('
-----------------------------
--CARGOS RECHAZO DE CHEQUES--
-----------------------------
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (1300, ''RECHAZO CHEQ PROPIOS'', 0)
----
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (1460, 1300, 0, ''A'', 924, ''TIPO CAUSAL SIN FONDOS'', 1)
----
')