EXECUTE('
DELETE FROM DICCIONARIO WHERE NUMERODECAMPO  IN (69000,69001)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (69000, NULL, 0, ''CotizaDol'', ''CotizaDol'', 15, ''N'', 9, ''I'', 0, 0, 0, 0, 0, 0, 0, 544, ''COTIZA_DOL'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (69001, NULL, 0, ''CotizaDol'', ''CotizaDol'', 15, ''N'', 9, ''I'', 0, 0, 0, 0, 0, 0, 0, 541, ''COTIZA_DOL'', 0, NULL)
')
