
EXECUTE('
---DELETES

DELETE FROM dbo.DESCRIPTORES
WHERE TITULO = 3300 AND IDENTIFICACION = 3368;

--DICIONARIO

DELETE FROM DICCIONARIO WHERE NUMERODECAMPO IN 
(35753,
35754,
35755,
35756,
35757,
35758,
35759,
35760,
35761,
35762,
35763);


--OPCIONES

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35757 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''A'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35757 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''I'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35757 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''T'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35758 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''A'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35758 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''I'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35758 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''R'';


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 35758 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''T'';




--INDICES

DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 3368 AND NUMERODEINDICE = 1;




---INSERTS



INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (3300, 3368, NULL, ''DJ_SOL_ACT_INAC_CAUSAS'', 0, ''DJ_SOL_ACT_INAC_CAUSAS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'');


-------------------------------------------------


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35753, '' '', 0, ''Número de Solicitud'', ''Nro. Solicitud'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''NRO_SOLICITUD'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35754, '' '', 0, ''Número Causa'', ''Nro Causa'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''NRO_CAUSA'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35755, '' '', 0, ''Tipo de causa'', ''Tipo causa'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''TIPO_CAUSA'', 0, NULL);

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35756, '' '', 0, ''Numero Juzgado'', ''Número Juzgado'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''NRO_JUZGADO'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35757, '' '', 0, ''Accion'', ''Accion'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3368, ''ACCION'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35758, '' '', 0, ''Estado Solicitud'', ''Estado'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3368, ''ESTADO'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35759, '' '', 0, ''Fecha Estado'', ''Fecha Estado'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3368, ''FECHA_ESTADO'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35760, '' '', 0, ''Fecha Causa'', ''Fecha Causa'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 3368, ''FECHA_CAUSA'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35761, '' '', 0, ''Sucursal'', ''Sucursal'', 5, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''SUCURSAL'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35762, '' '', 0, ''Comentario'', ''Comentario'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''COMENTARIO'', 0, NULL);


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35763, '' '', 0, ''Juzgado nuevo'', ''Juzgado nuevo'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3368, ''NRO_JUZGADO_NUEVO'', 0, NULL);



--------------------------------------



INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35757, ''E'', ''ACTIVAR'', ''A'', ''A'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35757, ''E'', ''INACTIVAR'', ''I'', ''I'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35757, ''E'', ''TRANSFERIR'', ''T'', ''T'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35758, ''E'', ''Aceptado'', ''A'', ''A'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35758, ''E'', ''Ingresado'', ''I'', ''I'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35758, ''E'', ''Rechazado manual'', ''R'', ''R'');


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (35758, ''E'', ''Rechazado automatico'', ''T'', ''T'');



INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3368, 1, ''Indice1'', 0, 35753, 35754, 35756, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

')