EXECUTE('
----------------------------------
--AGREGO METADATA CAMPO DE VISTA--
----------------------------------
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35389, '' '', 0, ''JTS OID'', ''JTS OID'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3515, ''JTS_OID'', 0, NULL)
----
')
