EXECUTE('

INSERT INTO REPORTES
(TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES(5000, 5073, ''Ticket Certificado de DPF'', '' '', 0, NULL, 0, 0.0, 0, ''N'');

')