EXECUTE('
--------------------------------------
--NUEVA VISTA VW_CLI_PERSONAS_FIRMAS--
--------------------------------------
CREATE VIEW VW_CLI_PERSONAS_FIRMAS
(TIPO_DOC,NRO_DOC,NRO_PERSONA,NOMBRE_APELLIDO,NRO_FIRMA,VENCIMIENTO,AUTORIZADOR)
AS 
SELECT D.TIPODOCUMENTO, D.NUMERODOCUMENTO, F.NUMEROPERSONAFISICA, CONCAT(P.PRIMERNOMBRE+'' '',P.APELLIDOPATERNO),
F.NUMERO_FIRMA, F.VENCIMIENTO, F.AUTORIZADOR
FROM CLI_PERSONAS_FIRMAS AS F
LEFT JOIN CLI_DOCUMENTOSPFPJ AS D ON F.NUMEROPERSONAFISICA = D.NUMEROPERSONAFJ AND D.TZ_LOCK = 0
LEFT JOIN CLI_PERSONASFISICAS AS P ON F.NUMEROPERSONAFISICA = P.NUMEROPERSONAFISICA AND P.TZ_LOCK = 0
WHERE F.TZ_LOCK = 0
-----
')