EXECUTE('
IF OBJECT_ID (''dbo.VW_RRII_ANEXO_2'') IS NOT NULL
	DROP VIEW dbo.VW_RRII_ANEXO_2
')
EXECUTE('
CREATE   VIEW [dbo].[VW_RRII_ANEXO_2] 
AS
SELECT 
	CBE.CODIGO_INTERNO AS CODIGO_INTERNO,
	DBO.convertirAMonNac(SUM(CBR.SALDOFINMESMO),CBR.MONEDA,CBR.FECHA) AS IMPORTE,
	CBR.MONEDA AS MONEDA,
	CBR.FECHA AS FECHA
FROM CO_BALANCE_ESTRUCTURA CBE WITH (NOLOCK)
INNER JOIN CO_BALANCE_RESULTADOS CBR WITH(NOLOCK) ON 
	CBE.CODIGO_BCE=CBR.CODIGO_INTERNO AND 
	CBR.ID_BCE=2 
WHERE CBE.ID_BCE=3 
	AND CBE.TZ_LOCK=0
	AND CBR.TIPO_BALANCE=''M''
GROUP BY 
	CBE.CODIGO_INTERNO,
	CBR.FECHA,
	CBR.MONEDA
')
