EXECUTE('TRUNCATE TABLE dbo.TJD_TARJETAS;')

EXECUTE('TRUNCATE TABLE dbo.TJD_REL_TARJETA_CUENTA;')

EXECUTE('INSERT INTO dbo.TJD_TARJETAS (JTS_OID_GTOS, TIPO_TARJETA, FECHA_PRIMER_USO, FECHA_ULTIMO_USO, ID_TARJETA, NRO_CLIENTE, TITULARIDAD, ESTADO, FECHA_ENTREGA, VENCIMIENTO, NOMBRE_TARJETA, SUCURSAL, ID_TARJETA_TITULAR, NRO_PERSONA, COD_PLAN, ID_CONVENIO, [CODIGO_CLIENTE_EMPRESA], COD_PAQUETE, STANDARD, NOMBREEMPRESA, OBSERVACIONES, FECHAMODIFICACION, CANAL, ID_TARJETA_BASE, ORIGEN, NUM_ENVIO, TZ_LOCK, REIMPRESION, MOTIVO_REIMPRESION, NUM_VERSION, DIGITO_VERIFICADOR, LIMITE_CREDITO, LIMITE_DEBITO, PERMISO) VALUES (0, ''5'', NULL, NULL, ''0000000000050105613'', 35, ''T'', ''P'', NULL, NULL, '' '', 1, '' '', 23, 0, 0, 0, 0, '' '', '' '', '' '', NULL, '' '', 0, '' '', 0, 0, NULL, NULL, ''0'', ''0'', NULL, 8, NULL);')

EXECUTE('INSERT INTO dbo.TJD_TARJETAS (JTS_OID_GTOS, TIPO_TARJETA, FECHA_PRIMER_USO, FECHA_ULTIMO_USO, ID_TARJETA, NRO_CLIENTE, TITULARIDAD, ESTADO, FECHA_ENTREGA, VENCIMIENTO, NOMBRE_TARJETA, SUCURSAL, ID_TARJETA_TITULAR, NRO_PERSONA, COD_PLAN, ID_CONVENIO, [CODIGO_CLIENTE_EMPRESA], COD_PAQUETE, STANDARD, NOMBREEMPRESA, OBSERVACIONES, FECHAMODIFICACION, CANAL, ID_TARJETA_BASE, ORIGEN, NUM_ENVIO, TZ_LOCK, REIMPRESION, MOTIVO_REIMPRESION, NUM_VERSION, DIGITO_VERIFICADOR, LIMITE_CREDITO, LIMITE_DEBITO, PERMISO) VALUES (0, ''5'', NULL, NULL, ''0000000000051436520'', 540, ''T'', ''I'', NULL, NULL, '' '', 1, '' '', 74, 0, 0, 0, 0, '' '', '' '', '' '', NULL, '' '', 0, '' '', 0, 0, NULL, NULL, ''0'', ''0'', NULL, 1, NULL);')

EXECUTE('INSERT INTO dbo.TJD_TARJETAS (JTS_OID_GTOS, TIPO_TARJETA, FECHA_PRIMER_USO, FECHA_ULTIMO_USO, ID_TARJETA, NRO_CLIENTE, TITULARIDAD, ESTADO, FECHA_ENTREGA, VENCIMIENTO, NOMBRE_TARJETA, SUCURSAL, ID_TARJETA_TITULAR, NRO_PERSONA, COD_PLAN, ID_CONVENIO, [CODIGO_CLIENTE_EMPRESA], COD_PAQUETE, STANDARD, NOMBREEMPRESA, OBSERVACIONES, FECHAMODIFICACION, CANAL, ID_TARJETA_BASE, ORIGEN, NUM_ENVIO, TZ_LOCK, REIMPRESION, MOTIVO_REIMPRESION, NUM_VERSION, DIGITO_VERIFICADOR, LIMITE_CREDITO, LIMITE_DEBITO, PERMISO) VALUES (0, ''5'', NULL, NULL, ''0000000000051436521'', 434, ''T'', ''I'', NULL, NULL, '' '', 1, '' '', 56, 0, 0, 0, 0, '' '', '' '', '' '', NULL, '' '', 0, '' '', 0, 0, NULL, NULL, ''0'', ''0'', NULL, 1, NULL);')

EXECUTE('INSERT INTO dbo.TJD_TARJETAS (JTS_OID_GTOS, TIPO_TARJETA, FECHA_PRIMER_USO, FECHA_ULTIMO_USO, ID_TARJETA, NRO_CLIENTE, TITULARIDAD, ESTADO, FECHA_ENTREGA, VENCIMIENTO, NOMBRE_TARJETA, SUCURSAL, ID_TARJETA_TITULAR, NRO_PERSONA, COD_PLAN, ID_CONVENIO, [CODIGO_CLIENTE_EMPRESA], COD_PAQUETE, STANDARD, NOMBREEMPRESA, OBSERVACIONES, FECHAMODIFICACION, CANAL, ID_TARJETA_BASE, ORIGEN, NUM_ENVIO, TZ_LOCK, REIMPRESION, MOTIVO_REIMPRESION, NUM_VERSION, DIGITO_VERIFICADOR, LIMITE_CREDITO, LIMITE_DEBITO, PERMISO) VALUES (0, ''5'', NULL, NULL, ''0000000000051436522'', 221, ''T'', ''I'', NULL, NULL, '' '', 1, '' '', 8, 0, 0, 0, 0, '' '', '' '', '' '', NULL, '' '', 0, '' '', 0, 0, NULL, NULL, ''0'', ''0'', NULL, 1, NULL);')

EXECUTE('INSERT INTO dbo.TJD_REL_TARJETA_CUENTA (TZ_LOCK, ID_TARJETA, SALDO_JTS_OID, TIPO_CUENTA, PRIORITARIA, PRODUCTO, CUENTA, MONEDA, SUCURSAL, ORDINAL_PREFERENCIA, ESTADO) VALUES (0, ''0000000000050105613'', 38197, 0, 0, 1, 3500, 80, 1, 0, ''1'');')

EXECUTE('INSERT INTO dbo.TJD_REL_TARJETA_CUENTA (TZ_LOCK, ID_TARJETA, SALDO_JTS_OID, TIPO_CUENTA, PRIORITARIA, PRODUCTO, CUENTA, MONEDA, SUCURSAL, ORDINAL_PREFERENCIA, ESTADO) VALUES (0, ''0000000000051436520'', 38269, 11, 0, 7, 54000, 80, 1, 0, ''1'');')

EXECUTE('INSERT INTO dbo.TJD_REL_TARJETA_CUENTA (TZ_LOCK, ID_TARJETA, SALDO_JTS_OID, TIPO_CUENTA, PRIORITARIA, PRODUCTO, CUENTA, MONEDA, SUCURSAL, ORDINAL_PREFERENCIA, ESTADO) VALUES (0, ''0000000000051436521'', 38245, 1, 0, 51, 43400, 80, 1, 0, ''1'');')

EXECUTE('INSERT INTO dbo.TJD_REL_TARJETA_CUENTA (TZ_LOCK, ID_TARJETA, SALDO_JTS_OID, TIPO_CUENTA, PRIORITARIA, PRODUCTO, CUENTA, MONEDA, SUCURSAL, ORDINAL_PREFERENCIA, ESTADO) VALUES (0, ''0000000000051436522'', 38200, 1, 0, 3, 3500, 80, 1, 0, ''1'');')



