EXECUTE('
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (53961, '' '', 0, ''Importe largo 11'', ''Importe largo 11'', 11, ''N'', 2, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''Importe largo 11'', 0, NULL)
')

