EXECUTE('
INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (303, 0, 14, 1, ''Obtener Estado Persona Humana'', NULL, NULL)


INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (303, 1, 14, 1, ''C1401=C1401'', ''C5048'', ''C33366'')



INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (304, 0, 19, 1, ''Obtener Estado Persona Juridica'', NULL, NULL)


INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (304, 1, 19, 1, ''C1451=C1451'', ''C5048'', ''C33367'')

')