EXECUTE('
DELETE FROM NUMERATORASIGNED WHERE OID IN (SELECT OID FROM NUMERATORVALUES WHERE NUMERO=43418);

')

EXECUTE('
DELETE FROM NUMERATORVALUES WHERE NUMERO=43418;
')

EXECUTE('
UPDATE dbo.NUMERATORDEFINITION
SET INIVAL = (SELECT max(CODIGO)+1 FROM CRE_ENTES_SUBSIDIOS)
WHERE NUMERO = 43418;

')