EXECUTE('
CREATE OR ALTER VIEW V_DJ_CUENTAS
AS
SELECT
	S.JTS_OID, --565,
	COALESCE(CC.NRO_CAUSA, 0) AS NRO_CAUSA, --50033,
	S.CUENTA, --2615,
	VS.NOMBRE_CUENTA, --910,
	S.PRODUCTO, --2613,
	P.C6251 AS NOMBRE_PRODUCTO, --4968,
	S.SUCURSAL, --2612,
	SUC.NOMBRESUCURSAL AS NOMBRE_SUCURSAL, --324,
	S.MONEDA, --611,
	M.C6400 AS NOMBRE_MONEDA, --622,
	CC.NRO_OFICIO --1850
FROM SALDOS S  WITH(NOLOCK)
LEFT JOIN DJ_CAUSA_CUENTA CC WITH(NOLOCK) ON S.JTS_OID=CC.JTS_OID_CUENTA 
								AND (CC.TZ_LOCK = 0 OR CC.TZ_LOCK BETWEEN 300000000000000 AND 400000000000000)
JOIN SUCURSALES SUC WITH(NOLOCK) ON SUC.SUCURSAL=S.SUCURSAL
JOIN MONEDAS M WITH(NOLOCK) ON M.C6399=S.MONEDA
JOIN PRODUCTOS P WITH(NOLOCK) ON P.C6250=S.PRODUCTO
JOIN VTA_SALDOS VS WITH(NOLOCK) ON VS.JTS_OID_SALDO=S.JTS_OID
WHERE S.PRODUCTO IN (SELECT TC.PRODUCTO 
					FROM DJ_TIPOS_CAUSAS TC  WITH(NOLOCK)
					WHERE TC.TZ_LOCK=0) 
	AND S.TZ_LOCK=0
')