/****** Object:  View [dbo].[VW_PARAM_CUENTAS_INMOVILIZADAS]    Script Date: 24/02/2021 11:21:42 ******/
DROP VIEW [dbo].[VW_PARAM_CUENTAS_INMOVILIZADAS]
GO

/****** Object:  View [dbo].[VW_PARAM_CUENTAS_INMOVILIZADAS]    Script Date: 24/02/2021 11:21:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_PARAM_CUENTAS_INMOVILIZADAS]
									(NUMERO,
									TIPO,
									INCLUIR,
									VALOR,
									ACTIVO
									)
AS
		SELECT	P.ORDINAL, 
				T.DESCRIPCION, 
				I.DESCRIPCION, 
				P.VALOR, 
				A.DESCRIPCION
		FROM VTA_PARAM_CTAS_INMOV AS P with (nolock)
		INNER JOIN OPCIONES AS T with (nolock) ON T.NUMERODECAMPO = 34128 
												AND T.IDIOMA = 'E' 
												AND T.OPCIONINTERNA = P.TIPO
		INNER JOIN OPCIONES AS I with (nolock) ON I.NUMERODECAMPO = 34187 
												AND I.IDIOMA = 'E' 
												AND I.OPCIONINTERNA = P.INCLUIR_EXCLUIR
		INNER JOIN OPCIONES AS A with (nolock) ON A.NUMERODECAMPO = 34188 
												AND A.IDIOMA = 'E' 
												AND A.OPCIONINTERNA = P.ACTIVO
		WHERE P.TZ_LOCK = 0
GO


