EXECUTE('
IF OBJECT_ID (''dbo.VW_DJ_SOL_ACT_INAC_CAUSAS'') IS NOT NULL
	DROP VIEW dbo.VW_DJ_SOL_ACT_INAC_CAUSAS
')


EXECUTE('
CREATE VIEW dbo.VW_DJ_SOL_ACT_INAC_CAUSAS
AS
SELECT
	A.NRO_SOLICITUD,
	A.NRO_CAUSA,
	A.TIPO_CAUSA,
	A.NRO_JUZGADO,
	O.Descripcion AS ACTIVO,
	OE.Descripcion AS ESTADO,
	A.FECHA_ESTADO,
	A.FECHA_CAUSA,
	A.SUCURSAL,
	A.COMENTARIO,
	A.NRO_JUZGADO_NUEVO,
	A.NRO_CAUSA_ANTERIOR
FROM dbo.DJ_SOL_ACT_INAC_CAUSAS AS A WITH (nolock)
INNER JOIN OPCIONES AS O WITH (nolock) ON
	O.NUMERODECAMPO = 35757
	AND O.IDIOMA = ''E''
	AND O.OPCIONINTERNA = A.ACCION
INNER JOIN OPCIONES AS OE WITH (nolock) ON
	OE.NUMERODECAMPO = 35758
	AND OE.OPCIONINTERNA = A.ESTADO
	AND OE.IDIOMA = ''E''
WHERE
	A.TZ_LOCK = 0
')