EXECUTE('
-------------------------
--OPCIONES CAMPO ESTADO--
-------------------------
UPDATE dbo.DICCIONARIO
SET OPCIONES = 1
WHERE NUMERODECAMPO = 34771
----
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (34771, ''E'', ''Candidato a inmovilizar'', ''A'', ''A'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (34771, ''E'', ''Excluido'', ''E'', ''E'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (34771, ''E'', ''Inmovilizado'', ''I'', ''I'')
--
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (34771, ''E'', ''Reversado'', ''R'', ''R'')
----
')