EXECUTE('
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (6900, 7500, ''Ticket compra/venta moneda'', '' '', 0, NULL, 0, 0, 0, ''S'')
')

