EXECUTE('
IF OBJECT_ID (''dbo.CLE_CHEQUES_SALIENTE_HTO'') IS NOT NULL
	DROP TABLE dbo.CLE_CHEQUES_SALIENTE_HTO
')

EXECUTE('
CREATE TABLE dbo.CLE_CHEQUES_SALIENTE_HTO
	(
	TZ_LOCK                   NUMERIC (16) DEFAULT ((0)) NULL,
	ORDINAL                   NUMERIC (12) NOT NULL,
	TIPO_DOCUMENTO            VARCHAR (4) DEFAULT ('' '') NOT NULL,
	MONEDA                    NUMERIC (4) DEFAULT ((0)) NULL,
	SERIE_DEL_CHEQUE          VARCHAR (6) DEFAULT ('' '') NOT NULL,
	NUMERO_CHEQUE             NUMERIC (12) DEFAULT ((0)) NOT NULL,
	BANCO_GIRADO              NUMERIC (4) DEFAULT ((0)) NOT NULL,
	SUCURSAL_BANCO_GIRADO     NUMERIC (5) DEFAULT ((0)) NOT NULL,
	NUMERICO_CUENTA_GIRADORA  NUMERIC (12) DEFAULT ((0)) NOT NULL,
	CODIGO_USUARIO            VARCHAR (10) DEFAULT ('' '') NULL,
	FECHA_ALTA                DATETIME NOT NULL,
	NUMERO_DEPOSITO           NUMERIC (15) DEFAULT ((0)) NULL,
	IMPORTE                   NUMERIC (15,2) DEFAULT ((0)) NULL,
	FECHA_ENVIO_COMPENSACION  DATETIME NULL,
	SUCURSAL_DE_INGRESO       NUMERIC (5) DEFAULT ((0)) NULL,
	FECHA_ENVIO_CAMARA        DATETIME NULL,
	FECHA_RECEP_CENTRAL_CLEAR DATETIME NULL,
	NRO_ASIENTO               NUMERIC (10) DEFAULT ((0)) NULL,
	FECHA_DEVUELTO            DATETIME NULL,
	IMPORTE_IMPUESTO          NUMERIC (15,2) DEFAULT ((0)) NULL,
	CMC7                      VARCHAR (30) DEFAULT ('' '') NULL,
	CONSTRAINT PK_CLE_CHEQUES_SALIENTE_HTO PRIMARY KEY (ORDINAL,TIPO_DOCUMENTO,SERIE_DEL_CHEQUE,NUMERO_CHEQUE,BANCO_GIRADO,SUCURSAL_BANCO_GIRADO, NUMERICO_CUENTA_GIRADORA)
	)

')
