execute('

INSERT INTO CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (853, ''CRÉDITO MASIVOS PA IMPUESTO LOTERIA'', 0)

INSERT INTO CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (854, ''DÉBITO MASIVOS PA IMPUESTO LOTERIA'', 0)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (400, 854, 0, ''A'', 34096, ''SEGMENTO CREDEB'', 1)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (401, 853, 0, ''A'', 34096, ''CONDICIÓN CREDEB'', 1)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (501, 853, 0, ''A'', 33991, ''CONDICIÓN SIRCREB'', 2)

INSERT INTO CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (555, 853, 0, ''A'', 0, '''', 3)

')