EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (95100, '' '', 0, ''Ayuda Tipo Exclusiones'', ''Tipo Exclusiones'', 15, ''N'', 0, NULL, 0, 0, 0, 0, 0, 49466, 0, 0, ''Tipo Exclusiones'', 0, NULL)
')

EXECUTE ('
INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (0, 49466, ''VW_GRADUACION_TIPO_EXCLUSIONES'', '''', 0, ''50299R;9103R;37362;'', ''Identificador;Tipo de Exclusion;Detalle;'', ''TOP/CLIENTES'', ''VW_GRADUACION_TIPO_EXCLUSIONES'', 0)

')