/****** Object:  StoredProcedure [dbo].[PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO_AT$IMPL]    Script Date: 18/06/2021 16:06:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO_AT$IMPL]  
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */

   @P_ID_PROCESO float(53),
   @P_FCH_PROCESO datetime2(0),
   @P_NOM_PACKAGE varchar(max),
   /*
   *   SSMA warning messages:
   *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
   */

   @P_COD_ERROR float(53),
   @P_MSG_ERROR varchar(max),
   @P_TIPO_ERROR varchar(max)
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.9.0.*/
   BEGIN

      SET  IMPLICIT_TRANSACTIONS  ON

      BEGIN TRY

         INSERT dbo.LOG_PROCESO(
            ID_PROCESO, 
            FECHA_ERROR, 
            NOM_PACKAGE, 
            COD_ERROR, 
            MSG_ERROR, 
            TIPO_ERROR)
            VALUES (
               @P_ID_PROCESO, 
               @P_FCH_PROCESO, 
               @P_NOM_PACKAGE, 
               @P_COD_ERROR, 
               @P_MSG_ERROR, 
               @P_TIPO_ERROR)

         IF @@TRANCOUNT > 0
            COMMIT WORK 

      END TRY

      BEGIN CATCH
         BEGIN
            DECLARE
               @db_null_statement int
         END
      END CATCH

   END
GO

EXEC sys.sp_addextendedproperty @name=N'MS_SSMA_SOURCE', @value=N'BANKPROD.PKG_LOG_PROCESO.proc_ins_log_proceso_at' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'PROCEDURE',@level1name=N'PKG_LOG_PROCESO$PROC_INS_LOG_PROCESO_AT$IMPL'
GO


