/****** Object:  View [dbo].[VW_PYF_FORMULAS]    Script Date: 24/02/2021 16:09:17 ******/
DROP VIEW [dbo].[VW_PYF_FORMULAS]
GO

/****** Object:  View [dbo].[VW_PYF_FORMULAS]    Script Date: 24/02/2021 16:09:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_PYF_FORMULAS]
								(TipoEntidad, 
								DESCRIPCION_TIPO_ENTIDAD,
								IdEntidad,
								Cuenta,
								DENOMINACION_CUENTA,
								TipoPoder,
								DESCRIPCION_TIPO_PODER,
								TipoDoc,
								NumDoc,
								NOMBRE_PERSONA
								)
AS
			SELECT	F.TIPO_ENTIDAD, 
					E.DESCRIPCION, 
					F.ID_ENTIDAD, 
					ISNULL(S.CUENTA,0),  
					CASE WHEN F.TIPO_ENTIDAD = 2 THEN V.NOMBRE_CUENTA
						ELSE C.NOMBRECLIENTE
					END,
					F.TIPO_PODER, 
					P.DESCRIPCION,
					CASE WHEN F.TIPO_ENTIDAD = 2 THEN ISNULL(DS.TIPODOC,0)
						ELSE ISNULL(DC.TIPODOC,0)
					END,
					CASE WHEN F.TIPO_ENTIDAD = 2 THEN ISNULL(DS.NUMERODOC,0)
						ELSE ISNULL(DC.NUMERODOC,0)
					END,
					CASE WHEN F.TIPO_ENTIDAD = 2 AND DS.TIPOPERSONA = 'F' 
							THEN (	SELECT CONCAT(PF.PRIMERNOMBRE + ' ', PF.APELLIDOPATERNO) 
									FROM CLI_PERSONASFISICAS AS PF with (nolock) 
									WHERE DS.NUMEROPERSONA = PF.NUMEROPERSONAFISICA 
										AND PF.TZ_LOCK = 0 )
						WHEN F.TIPO_ENTIDAD = 2 AND DS.TIPOPERSONA = 'J'
							THEN (	SELECT PJ.RAZONSOCIAL 
									FROM CLI_PERSONASJURIDICAS AS PJ with (nolock)
									WHERE DS.NUMEROPERSONA = PJ.NUMEROPERSONAJURIDICA 
										AND PJ.TZ_LOCK = 0)
						WHEN F.TIPO_ENTIDAD = 1 AND DC.TIPOPERSONA = 'F'
							THEN	(SELECT CONCAT(PF.PRIMERNOMBRE + ' ', PF.APELLIDOPATERNO) 
									FROM CLI_PERSONASFISICAS AS PF with (nolock) 
									WHERE DC.NUMEROPERSONA = PF.NUMEROPERSONAFISICA 
										AND PF.TZ_LOCK =0 )
						ELSE (	SELECT PJ.RAZONSOCIAL 
								FROM CLI_PERSONASJURIDICAS AS PJ with (nolock) 
								WHERE DC.NUMEROPERSONA = PJ.NUMEROPERSONAJURIDICA 
									AND PJ.TZ_LOCK = 0)
					END
			FROM PYF_FORMULAS AS F with (nolock)
			LEFT JOIN SALDOS S with (nolock) ON F.ID_ENTIDAD = S.JTS_OID AND F.TIPO_ENTIDAD = 2 AND S.TZ_LOCK=0
			LEFT JOIN CLI_CLIENTES AS C with (nolock)ON F.ID_ENTIDAD = C.CODIGOCLIENTE AND F.TIPO_ENTIDAD = 1 AND C.TZ_LOCK = 0
			LEFT JOIN PYF_TIPOENTIDAD AS E with (nolock) ON F.TIPO_ENTIDAD = E.TIPO_ENTIDAD
			LEFT JOIN PYF_TIPOPODERES AS P ON F.TIPO_PODER = P.TIPO_PODER 
			LEFT JOIN VTA_SALDOS AS V with (nolock) ON S.JTS_OID = V.JTS_OID_SALDO AND V.TZ_LOCK = 0 
			LEFT JOIN VW_CLI_X_DOC AS DS with (nolock) ON S.C1803 = DS.CODIGOCLIENTE
			LEFT JOIN VW_CLI_X_DOC AS DC with (nolock) ON C.CODIGOCLIENTE = DC.CODIGOCLIENTE
			--LEFT JOIN CLI_CLIENTEPERSONA AS CPS ON S.C1803 = CPS.CODIGOCLIENTE AND CPS.TITULARIDAD = 'T' AND CPS.TZ_LOCK = 0
			--LEFT JOIN CLI_CLIENTEPERSONA AS CPC ON C.CODIGOCLIENTE = CPC.CODIGOCLIENTE AND CPC.TITULARIDAD = 'T' AND CPC.TZ_LOCK = 0
			--LEFT JOIN CLI_PERSONASFISICAS AS RS ON CPS.NUMEROPERSONA = RS.NUMEROPERSONAFISICA AND RS.TZ_LOCK = 0
			--LEFT JOIN CLI_PERSONASFISICAS AS RC ON CPC.NUMEROPERSONA = RC.NUMEROPERSONAFISICA AND RC.TZ_LOCK = 0
			WHERE	F.TZ_LOCK=0 
				AND E.TZ_LOCK = 0
				AND P.TZ_LOCK = 0 
GO


