execute ('

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37360, '' '', 0, ''Tipo Sujeto Obligado UIF'', ''Tipo Sujeto Obligado UIF'', 5, ''A'', 0, NULL, 0, 0, 0, 0, 0, 33631, 0, 0, ''TIPOSUJETOUIF'', 0, NULL)


UPDATE dbo.DICCIONARIO
SET TABLADEAYUDA = 0
WHERE NUMERODECAMPO = 37311

DELETE FROM INDICES WHERE NUMERODEINDICE=33631 AND NUMERODEARCHIVO=3363

INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3363, 33631, ''Indice'', 0, 37309, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


UPDATE dbo.DESCRIPTORES
SET LARGODELREGISTRO = 0
WHERE TITULO = 10 AND IDENTIFICACION = 3363

UPDATE dbo.DESCRIPTORES
SET INICIALIZACIONDELREGISTRO = 0
WHERE TITULO = 10 AND IDENTIFICACION = 3363


')