execute('
delete FROM CI_EVENTO WHERE ID_EVENTO IN (3099)
INSERT INTO dbo.CI_EVENTO (ID_EVENTO, DESCRIPCION, TZ_LOCK)
VALUES (3099, ''OFICIO JUDICIAL'', 0)

delete FROM CI_CARGOS_X_EVENTO WHERE ID_EVENTO IN (3099)

INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (3099, 3099, 0, ''A'', 0, '''', 1)
INSERT INTO dbo.CI_CARGOS_X_EVENTO (ID_CARGO, ID_EVENTO, TZ_LOCK, TIPO_RELACION, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO, PRIORIDAD)
VALUES (3100, 3099, 0, ''A'', 0, '''', 2)

delete FROM CI_CARGOS WHERE ID_CARGO IN (3099,3100)
INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (3099, ''COMISIÓN OFICIO JUDICIAL CLIENTE'', ''N'', ''N'', 1, ''N'', 3120, 34355, 1, 0, 9999999999999.99, ''C'', 0, 0, 0, ''N'', 0, 0, NULL, ''N'', ''R'', ''R'', ''N'', 2, ''F'', ''N'', ''30650201'', ''20000101'', 0, ''N'', 0, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)
INSERT INTO dbo.CI_CARGOS (ID_CARGO, DESCRIPCION, ENQUEUE, EXONERABLE, ID_FORMULA, ACTUALIZABLE, CONDICION, PIVOT_, MONEDA_IMPORTE, IMPORTE_MINIMO, IMPORTE_MAXIMO, TRATAMIENTO_MINIMO, TZ_LOCK, CAMPO_MONTO_IMPONIBLE, CAMPO_RANGO_TARIFA, NETEAR, CANTIDAD_REINTENTOS, CONCEPTO, PIVOT_ENCOLA, CONTABILIZA, SOBREGIRO, BLOQUEO, CONTROL_MAX_MIN, TIPO_FECHA_VIGENCIA, TIPO_DOCUMENTO, ACEPTAPAGOPARCIAL, FECHAHASTA, FECHADESDE, MONEDA_RANGO, BUSCA_MONEDA_RANGO, CODIGO_TRANSACCION, REGENERA_AL_PAGAR, CARGO_O_IMPUESTO, INCLUIRENCUOTA, CUOTASNOCONSIDERARALFINAL, COBRARHASTADIAS, PORCENTAJE_MINIMO, PORCENTAJE_MAXIMO, CAMPO_DIA_COBRO, GENERA_RESERVA, DIAS_COBRO_HASTA_INMOVILIZADA, DESCRIPCION_1, DESCRIPCION_2, DESCRIPCION_3, GENERA_FACTURA_EN_CERO, TIPO_CARGO_IMPOSITIVO)
VALUES (3100, ''COMISIÓN OFICIO JUDICIAL'', ''N'', ''N'', 1, ''N'', 3121, 34355, 1, 0, 9999999999999.99, ''C'', 0, 0, 0, ''N'', 0, 0, NULL, ''N'', ''R'', ''R'', ''N'', 2, ''F'', ''N'', ''30650201'', ''20000101'', 0, ''N'', 0, ''N'', ''C'', ''N'', 0, 0, 0, 0, 0, ''S'', 0, NULL, NULL, NULL, ''N'', 0)

delete FROM CI_CARGOS_TARIFAS WHERE ID_CARGO IN (3099,3100)
INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA)
VALUES (3099, 1, 9999999999999, 0, 6000, 1, 0, 0, ''0'', ''N'', 0, 0, ''20000101'', ''20651231'')
INSERT INTO dbo.CI_CARGOS_TARIFAS (ID_CARGO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, ID_CLIENTE, SEGMENTO, APLICA_MIN_MAX, IMPORTE_MINIMO, IMPORTE_MAXIMO, FECHA_DESDE, FECHA_HASTA)
VALUES (3100, 1, 9999999999999, 0, 6000, 1, 0, 0, ''0'', ''N'', 0, 0, ''20000101'', ''20651231'')

delete FROM CI_IMPUESTOS_X_CARGO WHERE ID_CARGO IN (3099,3100)
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (3, 3099, ''A'', 0, NULL, NULL)
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (4, 3099, ''A'', 0, 1357, ''Cond Percep IVA'')
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (3, 3100, ''A'', 0, NULL, NULL)
INSERT INTO dbo.CI_IMPUESTOS_X_CARGO (ID_IMPUESTO, ID_CARGO, LECTURA_TOPAZ, TZ_LOCK, CAMPO_SEGMENTO, DESCRIPCION_SEGMENTO)
VALUES (40, 3100, ''A'', 0, 49500, ''Cond Percep IVA'')

delete FROM CI_IMPUESTOS WHERE ID_IMPUESTO=40
INSERT INTO dbo.CI_IMPUESTOS (ID_IMPUESTO, DESCRIPCION, CONDICION, TZ_LOCK, PIVOT_, ID_FORMULA, CONCEPTO, MONTO_DEDUCIBLE, IMPORTE_MAXIMO, IMPORTE_MINIMO, MONEDA_IMPORTE, TRATAMIENTO_MINIMO, TIPO_FECHA_VIGENCIA, FECHADESDE, FECHAHASTA, MONEDA_RANGO, BUSCA_MONEDA_RANGO, COBRO_PROPORCIONAL, CAMPO_RANGO_TARIFA, GENERA_FACTURA_EN_CERO, TIPO_IMPUESTO, CODIGO_TRANSACCION)
VALUES (40, ''IVA Percepción comi judicial'', 3122, 0, 58360, 2, 0, 0, 9999999999999, 60, 1, ''D'', 0, ''19000123'', ''50000101'', 0, ''N'', ''N'', 0, ''N'', 2, 201)

delete FROM CI_IMPUESTOS_TARIFAS WHERE ID_IMPUESTO=40
INSERT INTO dbo.CI_IMPUESTOS_TARIFAS (ID_IMPUESTO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, FECHA_HASTA, FECHA_DESDE, ID_CLIENTE, SEGMENTO)
VALUES (40, 1, 9999999999999, 0, 0, 1, 0, ''20990101'', ''20000101'', 0, ''0'')
INSERT INTO dbo.CI_IMPUESTOS_TARIFAS (ID_IMPUESTO, MONEDA, RANGO_HASTA, TASA, IMPORTE_APLICAR, MONEDA_IMPORTE, TZ_LOCK, FECHA_HASTA, FECHA_DESDE, ID_CLIENTE, SEGMENTO)
VALUES (40, 1, 9999999999999, 0.03, 0, 1, 0, ''20990101'', ''20000101'', 0, ''AC'')

delete FROM CI_FORMULAS WHERE ID_FORMULA IN (3120,3121,3122)
INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (3120, ''CARGO A CLIENTE'', ''C49501=1'', 0, 1)
INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (3121, ''CARGO A NO CLIENTE'', ''C49501=2'', 0, 1)
INSERT INTO dbo.CI_FORMULAS (ID_FORMULA, DESCRIPCION, FORMULA, TZ_LOCK, ES_CONDICION)
VALUES (3122, ''CARGO A NO CLIENTE'', ''C49500=''''AC'''''', 0, 1)

--DICCIONARIO
delete FROM DICCIONARIO WHERE NUMERODECAMPO IN (49500,49501)
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49500, NULL, 0, ''Condición IVA Percep Comi Jud'', ''Condición Iva Percep Comi Jud'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''IVA'', 0, NULL)
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (49501, NULL, 0, ''Condicion Comi oficio Judicial'', ''Condicion Comi oficio Judicial'', 1, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, ''IVA'', 0, NULL)

---GASTOS SUCURSAL
DELETE FROM CAJ_GASTOS_SUCURSALES 
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (1, ''Pagos Varios de Gtos. Propios'', 5600579990, 3311369990, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (2, ''Pagos Energía Elect. Sucursal'', 5600390010, 3311360090, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (3, ''Pagos Agua Potable Sucursal'', 5600570010, 3311360410, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (4, ''Pagos Imp. Municipales Inmob.'', 5600450020, 3311480030, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (5, ''Pago Imp. Mun. Comercio e Industria'', 5600450070, 3311480050, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (6, ''Pago Imp. Mun. Barrido y Alumbrado'', 5600450030, 3311480040, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (7, ''Mante. Edific. Instalac. Maquina'', 5600480060, 3311360110, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (8, ''Pago Serv. Comunicaciones'', 5600390020, 3311360090, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (9, ''Gastos Franqueo y Telegrama'', 5600570060, 3311360140, 0)
INSERT INTO dbo.CAJ_GASTOS_SUCURSALES (CODIGO_SERVICIO, SERVICIO, CTA_CONTABLE_RESULTADO, CTA_CONTABLE_PASIVO, TZ_LOCK)
VALUES (10, ''Combustible Minifilial'', 5600570240, 3311360240, 0)
---NUMERADORES
DELETE FROM NUMERATORDEFINITION WHERE NUMERO=49004
INSERT INTO NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (49004, 11, 1, '' '', NULL, 0, 1, 0, ''Código Servicio'', ''T'')
')