


-- Parche_NUNBCHACO_593

-- Parche_NUNBCHACO_593

-- Cambiar el tamaño del campo DESCRIPCION_RESTRICCION en la tabla BITACORA_RESTRICCIONES
ALTER TABLE BITACORA_RESTRICCIONES ALTER COLUMN DESCRIPCION_RESTRICCION varchar(2000);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210419_3',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhcmNoZV9OVU5CQ0hBQ09fNTkzCg0KLS0gUGFyY2hlX05VTkJDSEFDT181OTMKDQot
LSBDYW1iaWFyIGVsIHRhbWHxbyBkZWwgY2FtcG8gREVTQ1JJUENJT05fUkVTVFJJQ0NJT04gZW4g
bGEgdGFibGEgQklUQUNPUkFfUkVTVFJJQ0NJT05FUw0KQUxURVIgVEFCTEUgQklUQUNPUkFfUkVT
VFJJQ0NJT05FUyBBTFRFUiBDT0xVTU4gREVTQ1JJUENJT05fUkVTVFJJQ0NJT04gdmFyY2hhcigy
MDAwKTsKDQoKCg0K', NULL, 0);
