
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37303, NULL, NULL, 'Tipo de Cliente', 'Tipo Cliente', 1, 'A', 0, NULL, 0, 0, NULL, NULL, NULL, NULL, 1, 0, 'TIPOCLIENTE', 0, NULL)


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'E', 'CLIENTE FÍSICO', 'F', 'F')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'E', 'INSTITUCIÓN FINANCIERA', 'I', 'I')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'E', 'CLIENTE JURÍDICO', 'J', 'J')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'I', 'CLIENTE FÍSICO', 'F', 'F')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'I', 'INSTITUCIÓN FINANCIERA', 'I', 'I')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (37303, 'I', 'CLIENTE JURÍDICO', 'J', 'J')


