EXECUTE('
-------------
UPDATE COF_COFRES_CONTRATOS
SET FECHA_ALTA = ''2020-06-24''
WHERE CODIGO = 45
-----
UPDATE COF_COFRES_CONTRATOS
SET CODIGO_COFRE = 9
WHERE CODIGO = 3012
--
UPDATE COF_COFRES_CONTRATOS
SET CODIGO_COFRE = 9
WHERE CODIGO = 3013
--
')