EXECUTE('
UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 25

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 26

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 27

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 28

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 30

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 31

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 32

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 33

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 34

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 35

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 36

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 37

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 101

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 210

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 220

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 230

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 231

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 240

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 241

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1010

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1015

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1100

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1101

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1102

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1200

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1501

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 1571

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 8012

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 8021

UPDATE dbo.CI_CARGOS
SET TIPO_FECHA_VIGENCIA = 2
WHERE ID_CARGO = 8022
')


