EXECUTE('
CREATE OR ALTER PROCEDURE [dbo].[SP_ITF_MIPYME_PADRON]
(@IND_MSJ_ERROR VARCHAR(1) OUTPUT,
 @MSJ_ERROR VARCHAR(500) OUTPUT)
AS
  DECLARE @FECHAPROCESO VARCHAR(8);
  DECLARE @EXISTE   NUMERIC(10);
  
BEGIN
  
  BEGIN TRY 
  
  SET @IND_MSJ_ERROR = ''1'';
  
  SELECT @FECHAPROCESO = CONVERT(VARCHAR, FECHAPROCESO, 112) FROM PARAMETROS
  
  SELECT @EXISTE = COUNT(1)
  FROM ITF_MIPYME_PADRON (NOLOCK)
  
  IF @EXISTE = 0 --Para cuando sea la primera vez
  BEGIN
    INSERT INTO ITF_MIPYME_PADRON
	SELECT A.CUIT, A.FECHAPROCESO, A.VIGENCIADESDE, A.VIGENCIAHASTA
	FROM ITF_TMP_MIPYME_PADRON A (NOLOCK)
  END
  
  ELSE
  
  BEGIN
	  
	  --Pasamos a la tabla historica los registros que no estan vigentes.
	  INSERT INTO ITF_MIPYME_PADRON_HISTORICA
	  SELECT A.CUIT, A.FECHAPROCESO, A.VIGENCIADESDE, A.VIGENCIAHASTA
	  FROM ITF_MIPYME_PADRON A (NOLOCK) 
	  WHERE @FECHAPROCESO NOT BETWEEN A.VIGENCIADESDE AND A.VIGENCIAHASTA
	    AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON_HISTORICA B (NOLOCK)
	    			   WHERE B.CUIT = A.CUIT
	    			     AND B.FECHAPROCESO = A.FECHAPROCESO)
	    
	  DELETE FROM ITF_MIPYME_PADRON 
	  WHERE @FECHAPROCESO NOT BETWEEN VIGENCIADESDE AND VIGENCIAHASTA
	    
	  --Quitamos los CUIT que han sido modificado la fecha de vigencia
	  INSERT INTO ITF_MIPYME_PADRON_HISTORICA
	  SELECT A.CUIT, A.FECHAPROCESO, A.VIGENCIADESDE, A.VIGENCIAHASTA
	  FROM ITF_MIPYME_PADRON A (NOLOCK)
	    INNER JOIN ITF_TMP_MIPYME_PADRON B (NOLOCK) ON B.CUIT = A.CUIT
	  WHERE A.VIGENCIADESDE <> B.VIGENCIADESDE OR A.VIGENCIAHASTA <> B.VIGENCIAHASTA
	    AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON_HISTORICA B (NOLOCK)
	    			   WHERE B.CUIT = A.CUIT
	    			     AND B.FECHAPROCESO = A.FECHAPROCESO)
	    			     
	  DELETE A FROM ITF_MIPYME_PADRON A
	    INNER JOIN ITF_TMP_MIPYME_PADRON B (NOLOCK) ON B.CUIT = A.CUIT
	  WHERE A.VIGENCIADESDE <> B.VIGENCIADESDE OR A.VIGENCIAHASTA <> B.VIGENCIAHASTA
	  
	  --Quitamos los que no vienen en la trama
	  INSERT INTO ITF_MIPYME_PADRON_HISTORICA
	  SELECT A.CUIT, A.FECHAPROCESO, A.VIGENCIADESDE, A.VIGENCIAHASTA
	  FROM ITF_MIPYME_PADRON A (NOLOCK)
	  WHERE NOT EXISTS(SELECT 1 FROM ITF_TMP_MIPYME_PADRON B (NOLOCK) WHERE B.CUIT = A.CUIT)
	    AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON_HISTORICA B (NOLOCK)
	    			   WHERE B.CUIT = A.CUIT
	    			     AND B.FECHAPROCESO = A.FECHAPROCESO)
	  
	  DELETE A FROM ITF_MIPYME_PADRON A
	  WHERE NOT EXISTS(SELECT 1 FROM ITF_TMP_MIPYME_PADRON B (NOLOCK) WHERE B.CUIT = A.CUIT)
	  
	  
  	  --Se Elimina aquellos registros que en el json vengan fuera de vigencia
  	  DELETE FROM ITF_TMP_MIPYME_PADRON 
	  WHERE @FECHAPROCESO NOT BETWEEN VIGENCIADESDE AND VIGENCIAHASTA
	  
	  --Insertamos los nuevos CUIT
	  INSERT INTO ITF_MIPYME_PADRON
	  SELECT A.CUIT, A.FECHAPROCESO, A.VIGENCIADESDE, A.VIGENCIAHASTA
	  FROM ITF_TMP_MIPYME_PADRON A (NOLOCK)
	  WHERE NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK) WHERE B.CUIT = A.CUIT)
	  
  END
  
    /***********************************************************************************/
    --Tabla Temporal para grabar el registro con fecha mas actual por jts_oid_saldos
	SELECT A.*
	  INTO #TMP_RRII_BITACORA_CREDEB
	FROM RRII_BITACORA_CREDEB A (NOLOCK)
	WHERE FECHA = (SELECT MAX(FECHA) FROM RRII_BITACORA_CREDEB B (NOLOCK) WHERE B.JTS_OID_SALDOS = A.JTS_OID_SALDOS)
	
	--Registros que cambian de N a S
	SELECT A.CODIGOCLIENTE, VW.NUMERODOC, ''S'' AS PADRON
	  INTO #TMP_CLIENTE_CAMBIADO
	FROM CLI_CLIENTES A (NOLOCK)
	  INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON A.CODIGOCLIENTE = VW.CODIGOCLIENTE
	  INNER JOIN ITF_MIPYME_PADRON B (NOLOCK) ON B.CUIT = VW.NUMERODOC
	WHERE ISNULL(A.CREDEB_MIPYME,''N'') = ''N''
	UNION ALL
	--Registros que cambian de S a N
	SELECT A.CODIGOCLIENTE, VW.NUMERODOC, ''N'' AS PADRON
	FROM CLI_CLIENTES A (NOLOCK)
	  INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON A.CODIGOCLIENTE = VW.CODIGOCLIENTE
	WHERE ISNULL(A.CREDEB_MIPYME,''N'') = ''S''
	  AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK)
	            WHERE B.CUIT = VW.NUMERODOC)
	
	--Se graba en bitacora los registros modificados
	INSERT INTO RRII_BITACORA_CREDEB
	SELECT RI.TZ_LOCK, RI.JTS_OID_SALDOS, @FECHAPROCESO, RI.SEGMENTO, Ri.TIPO_CARGO_IMPOSITIVO, RI.PADRON_BENEF_FISCAL, CB.PADRON
	FROM #TMP_RRII_BITACORA_CREDEB RI
	INNER JOIN SALDOS S (NOLOCK) ON S.JTS_OID = RI.JTS_OID_SALDOS
	INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON S.C1803 = VW.CODIGOCLIENTE
	INNER JOIN #TMP_CLIENTE_CAMBIADO CB (NOLOCK) ON CB.NUMERODOC = VW.NUMERODOC
	--INNER JOIN PARAMETROS PA ON 1 = 1
	  
	--Se actualiza a S
	UPDATE CLI_PERSONASJURIDICAS
	SET CLI_PERSONASJURIDICAS.CREDEB_MIPYME = ''S''
	WHERE ISNULL(CLI_PERSONASJURIDICAS.CREDEB_MIPYME,''N'') = ''N''
	  AND EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK)
	                    INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON VW.NUMERODOC = B.CUIT
	            WHERE VW.NUMEROPERSONA = CLI_PERSONASJURIDICAS.NUMEROPERSONAJURIDICA)
	
	
	UPDATE CLI_CLIENTES
	SET CLI_CLIENTES.CREDEB_MIPYME = ''S''
	WHERE ISNULL(CLI_CLIENTES.CREDEB_MIPYME,''N'') = ''N''
	  AND EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK)
	                  INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON VW.NUMERODOC = B.CUIT
	            WHERE VW.CODIGOCLIENTE = CLI_CLIENTES.CODIGOCLIENTE)
	
	---Se actualiza a N cuando es en S
	UPDATE CLI_PERSONASJURIDICAS
	SET CLI_PERSONASJURIDICAS.CREDEB_MIPYME = ''N''
	WHERE ISNULL(CLI_PERSONASJURIDICAS.CREDEB_MIPYME,''N'') = ''S''
	  AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK)
	                           INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON VW.NUMERODOC = B.CUIT
	            WHERE VW.NUMEROPERSONA = CLI_PERSONASJURIDICAS.NUMEROPERSONAJURIDICA)
	
	UPDATE CLI_CLIENTES
	SET CLI_CLIENTES.CREDEB_MIPYME = ''N''
	WHERE ISNULL(CLI_CLIENTES.CREDEB_MIPYME,''N'') = ''S''
	  AND NOT EXISTS(SELECT 1 FROM ITF_MIPYME_PADRON B (NOLOCK)
	                           INNER JOIN VW_CLI_X_DOC VW (NOLOCK) ON VW.NUMERODOC = B.CUIT
	            WHERE VW.CODIGOCLIENTE = CLI_CLIENTES.CODIGOCLIENTE)
	              
  SET @IND_MSJ_ERROR = ''0'';
 END TRY  
BEGIN CATCH  
  SET @IND_MSJ_ERROR = ''1'';
  SET @MSJ_ERROR = ''Linea '' + CONVERT(VARCHAR, ERROR_LINE()) + '' Mensaje ''+ ERROR_MESSAGE();
END CATCH

END
')