EXECUTE('EXEC sp_rename ''CRE_SOLLICCLIENTE.MERCADODESTINO'', ''EXTRAORDINARIO'', ''COLUMN'' ')

EXECUTE('EXEC sp_rename ''CRE_SOLLICCLIENTE.CONTASUFICIENTE'', ''EXTRAORDINARIO_AUTORIZADO'', ''COLUMN'' ')

EXECUTE('ALTER TABLE CLE_CHEQUES_LISTA_DESCUENTO ADD DIGITALIZADO VARCHAR(1) DEFAULT ''N'' ')

EXECUTE('ALTER TABLE CLE_CHEQUES_LISTA_DESCUENTO ADD JTS_OID_CTACH NUMERIC(10) DEFAULT 0')

EXECUTE('ALTER TABLE CLE_CHEQUES_SALIENTE ADD JTS_OID_DESCUENTO NUMERIC(10)')

EXECUTE('ALTER TABLE TOPAZ_ROLES_ASSIGNMENT ALTER COLUMN DATA varchar(10) NOT NULL')

EXECUTE('ALTER TABLE CRE_SALDOS ADD EXPEDIENTE VARCHAR(20)')

EXECUTE('ALTER TABLE TOPESPRODUCTO ADD FECHA_PAGO_ULT_ACREDITACIONES  VARCHAR (1) DEFAULT(''N'')')

EXECUTE('ALTER TABLE TOPESPRODUCTO ADD OPERA_TARJETA_RECARGABLE VARCHAR(1) DEFAULT ''N''')

EXECUTE('ALTER TABLE CRE_SOLICITUDCREDITO ADD ADMINISTRADORA_TC NUMERIC(2)')

EXECUTE('ALTER TABLE CRE_SOLICITUDCREDITO ADD USUARIO_TC NUMERIC(20)')

EXECUTE('ALTER TABLE CLI_CLIENTES ADD DEFAULT 0 FOR CLIENTE_DEVENGA_SUSPENSO')


EXECUTE('
IF OBJECT_ID (''dbo.CRE_PROD_ADMINISTRADORAS'') IS NOT NULL
	DROP TABLE dbo.CRE_PROD_ADMINISTRADORAS
')


EXECUTE('
CREATE TABLE dbo.CRE_PROD_ADMINISTRADORAS
	(
	PRODUCTO           NUMERIC (5) NOT NULL,
	COD_ADMINISTRADORA NUMERIC (2) NOT NULL,
	PORCENTAJE         NUMERIC (5, 2) DEFAULT ((0)) NULL,
	TZ_LOCK            NUMERIC (15) DEFAULT ((0)) NULL,
	CONSTRAINT PK_CRE_PROD_ADMINISTRADORAS PRIMARY KEY (PRODUCTO, COD_ADMINISTRADORA)
	)
')


EXECUTE('
IF OBJECT_ID (''dbo.CRE_EMERGENCIA_AGRO'') IS NOT NULL
	DROP TABLE dbo.CRE_EMERGENCIA_AGRO
')


EXECUTE('
CREATE TABLE dbo.CRE_EMERGENCIA_AGRO
	(
	id                 NUMERIC (4) NOT NULL,
	motivo             VARCHAR (1) NULL,
	decreto_provincial VARCHAR (15) NULL,
	detalle            VARCHAR (400) NULL,
	fecha_vig_desde    DATETIME NULL,
	fecha_vig_hasta    DATETIME NULL,
	decreto_nacional   VARCHAR (15) NULL,
	TZ_LOCK            NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK__CRE_EMER PRIMARY KEY (id)
	)
')


EXECUTE('
IF OBJECT_ID (''dbo.VW_SOL_CRED_EMPRESAS'') IS NOT NULL
	DROP VIEW dbo.VW_SOL_CRED_EMPRESAS
')

EXECUTE('
CREATE     VIEW [dbo].[VW_SOL_CRED_EMPRESAS] (
												   Solicitud, 
												   Operacion, 
												   TipoDocumento, 
												   NumeroDocumento, 
												   Nombre, 
												   Estado,
												   "Descripcion Estado", 
												   Producto, 
												   "Descripcion Producto",
												   Moneda,
												   Monto,
												   TipoSolicitud,
												   Cliente,
												   SOL_CRED)
AS 

SELECT TOP 9223372036854775807 WITH TIES 
      S.NUMEROSOLICITUD AS Solicitud, 
      S.OPERACION_RENOVACION AS Operacion, 
      s.TIPODOCUMENTO AS TipoDocumento,
      s.NUMERODOCUMENTO AS NumeroDocumento,       
      C.NOMBRECLIENTE AS Nombre, 
      S.ESTADOSOLICITUD AS Estado, 
      (SELECT O.DESCRIPCION 
	  FROM dbo.OPCIONES  AS O WITH(NOLOCK)
      WHERE O.NUMERODECAMPO = 7333 
	  AND  O.IDIOMA = ''E'' 
	  AND O.OPCIONINTERNA = S.ESTADOSOLICITUD) AS "Descripcion Estado",      
      S.CODPRODUCTOSOLICITADO AS Producto, 
      (SELECT P.C6251 
	  FROM dbo.PRODUCTOS  AS P 	WITH(NOLOCK)
	  WHERE S.CODPRODUCTOSOLICITADO = P.C6250 
	  AND P.TZ_LOCK = 0) AS "Descripcion Producto",      
      MON.C6401 AS Moneda,
      S.MONTOSOLICITADO AS Monto,     
	  S.TIPO_SOL_NUEVA_RENOVACION AS TipoSolicitud,
	  S.CLIENTE AS Cliente,
	  SOL_CRED
FROM dbo.CRE_SOLICITUDCREDITO  AS S	WITH(NOLOCK)
INNER JOIN dbo.CLI_CLIENTES  AS C	WITH(NOLOCK)ON S.CLIENTE = C.CODIGOCLIENTE
												AND c.TZ_LOCK = 0
												AND S.TZ_LOCK = 0
INNER JOIN dbo.MONEDAS AS MON	WITH(NOLOCK)ON s.MONEDA = MON.C6399
											AND MON.TZ_LOCK = 0 
WHERE S.SOL_CRED IN (0,1) 
	AND S.TIPO_SOLICITUD = ''E''
ORDER BY S.NUMEROSOLICITUD DESC
')


EXECUTE('
IF OBJECT_ID (''dbo.VW_SaldosClienteLimite'') IS NOT NULL
	DROP VIEW dbo.VW_SaldosClienteLimite
')


EXECUTE('
CREATE   VIEW [dbo].[VW_SaldosClienteLimite] 
AS 
select	s.C1803 AS cliente,
		(CASE
		WHEN (C1604+C1605) <0 THEN
			(C1604+C1605) * -1
		ELSE
			(C1604+C1605)
		END) AS IMPORTE,
			s.C1601 AS CAPITAL_ORIGINAL,
		s.c1608 AS INTERESES,
		s.moneda as MONEDA,
		s.jts_oid AS SALDO_JTS_OID,
		p.c6283 as FAMILIAPROD,
		s.PRODUCTO,
		s.c1612 as CUOTA_APROBADA,
		s.MATRICULA_LIMITE	
from saldos s WITH (NOLOCK)
INNER JOIN productos p WITH (NOLOCK)ON s.producto = p.C6250
									and p.tz_lock = 0
									and (p.EVALUA_DEUDA = ''S'') 	
INNER JOIN planctas pc WITH (NOLOCK)ON pc.C6326 = s.C1730
									and pc.tz_lock = 0
WHERE S.C1604 < 0 AND (s.tz_lock = 0 	OR (s.TZ_LOCK > 099999999999999 AND s.TZ_LOCK < 199999999999999 ))
UNION												
SELECT	s.C1803 AS CLIENTE, 
		(v.IMPORTE - v.IMPORTE_CONSUMIDO) AS IMPORTE, 
		v.IMPORTE AS  CAPITAL_ORIGINAL, 
		0 AS INTERES,
		s.MONEDA AS MONEDA,
		s.JTS_OID AS SALDO_JTS_OID, 
		p.C6283 as FAMILIAPROD, 
		v.NROLINEA AS PRODUCTO,
		0 AS CUOTA_APROBADA , 
		'' '' AS MATRICULA_LIMITE
FROM VTA_SOBREGIROS v WITH(NOLOCK)
INNER JOIN SALDOS s WITH(NOLOCK) ON v.JTS_OID_SALDO = s.JTS_OID AND s.TZ_LOCK = 0
INNER JOIN PRODUCTOS p WITH(NOLOCK) ON v.NROLINEA = p.C6250 
									AND p.TZ_LOCK = 0
									AND  p.EVALUA_DEUDA = ''S''
INNER JOIN MONEDAS m WITH(NOLOCK) ON s.MONEDA = m.C6399 AND m.TZ_LOCK = 0
INNER JOIN SUCURSALES suc WITH(NOLOCK) ON v.SUCURSAL_ACUERDO = suc.SUCURSAL 
										AND suc.TZ_LOCK = 0
										AND v.ESTADO = 1 
										AND v.TZ_LOCK =0 AND (v.IMPORTE - v.IMPORTE_CONSUMIDO)> 0
')


EXECUTE('
IF OBJECT_ID (''dbo.VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO'') IS NOT NULL
	DROP VIEW dbo.VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO
')


EXECUTE('
CREATE   VIEW [dbo].[VW_CRE_DOCUMENTOS_DESC_O_AL_COBRO]
AS

SELECT ''FACTURA'' AS tipo,
		ISNULL((SELECT C1803 
				FROM SALDOS WITH(NOLOCK) 
				WHERE JTS_OID=jts_oid_cta_vista),0) AS cliente, 
	CASE destino WHEN 3 THEN ''DESCUENTO'' 
	ELSE ''AL COBRO'' 
	END AS destino,
	tipo_documento,
	documento_librador,
	Serie + ''-'' + numero_doc_real AS documento,
	moneda,
	importe,
	fecha_documento,
	fecha_vencimiento,
	jts_oid_cta_vista ,
	0 AS banco_girado,
	0 AS sucursal_banco_girado, 
	0 AS numerico_cuenta_giradora
FROM CRE_CONF_FACTURAS WITH(NOLOCK)
WHERE ESTADO=1 
	AND TZ_LOCK=0
union
SELECT  ''CHEQUE'' AS TIPO, 
	ISNULL((SELECT C1803 
			FROM SALDOS WITH(NOLOCK) 
			WHERE JTS_OID=jts_oid_banco),0) AS cliente, 
	CASE destino_cheque WHEN 3 THEN ''DESCUENTO'' 
	ELSE ''AL COBRO'' 
	END AS destino,
	ISNULL((SELECT TOP 1 tipo_documento 
			FROM CHE_CUENTAS_CHEQUES WITH(NOLOCK) 
			WHERE CUENTA_CHEQUE= numerico_cuenta_giradora 
				AND SUC_CHEQUE = sucursal_banco_girado 
				AND  BANCO_CHEQUE=  banco_girado),'''') AS tipo_documento,
	ISNULL((SELECT TOP 1 numero_documento 
			FROM CHE_CUENTAS_CHEQUES WITH(NOLOCK) 
			WHERE CUENTA_CHEQUE= numerico_cuenta_giradora 
				AND SUC_CHEQUE = sucursal_banco_girado 
				AND  BANCO_CHEQUE=  banco_girado),'''') AS  documento_librador,
	convert(VARCHAR(4),banco_girado,1) + ''-'' + convert(VARCHAR(5),sucursal_banco_girado,1) + ''-'' + convert(VARCHAR(4),COD_POSTAL,1) + ''-'' + convert(VARCHAR(12),numero_cheque,1) + ''-'' + convert(VARCHAR(12),numerico_cuenta_giradora,1) AS documento,
	MONEDA,
	importe,
	fecha_alta AS fecha_documento,
	fecha_acreditacion AS fecha_vencimiento,
	jts_oid_banco AS jts_oid_cta_vusta,
	banco_girado,
	sucursal_banco_girado,
	numerico_cuenta_giradora
FROM CLE_CHEQUES_SALIENTE WITH(NOLOCK) 
WHERE ESTADO = 2 AND acreditado=0
	AND DESTINO_CHEQUE IN(2,3) 
	AND TZ_LOCK=0
')


EXECUTE('
IF OBJECT_ID (''dbo.VW_CHEQUES_DESCONTADOS'') IS NOT NULL
	DROP VIEW dbo.VW_CHEQUES_DESCONTADOS
')


EXECUTE('
CREATE VIEW [dbo].[VW_CHEQUES_DESCONTADOS] 
(
	TipoDocumento, Serie, Numero, Banco, SucursalBanco, Cuenta, Importe, FechaAcreditacion, JTS_OID_DESCUENTO
)
AS
SELECT TIPO_DOCUMENTO AS TipoDocumento, SERIE_DEL_CHEQUE AS Serie, NUMERO_CHEQUE AS Numero, BANCO_GIRADO AS Banco, SUCURSAL_BANCO_GIRADO AS SucursalBanco, 
NUMERICO_CUENTA_GIRADORA AS Cuenta, IMPORTE AS Importe, FECHA_ACREDITACION AS FechaAcreditacion, JTS_OID_DESCUENTO
FROM(
	SELECT TIPO_DOCUMENTO, SERIE_DEL_CHEQUE, NUMERO_CHEQUE, BANCO_GIRADO, SUCURSAL_BANCO_GIRADO, NUMERICO_CUENTA_GIRADORA, IMPORTE, FECHA_ACREDITACION, JTS_OID_DESCUENTO
	FROM CLE_CHEQUES_SALIENTE WITH(NOLOCK)
	WHERE FECHA_ENVIO_COMPENSACION IS NULL 
	AND FECHA_ENVIO_CAMARA >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK)) 
	AND TZ_LOCK = 0 AND ACREDITADO = 0 AND DESTINO_CHEQUE = 3 AND
	NRO_SOLICITUD NOT IN (SELECT NRO_SOLICITUD FROM CHE_CHEQUES WITH(NOLOCK) WHERE TZ_LOCK = 0)
	UNION
	SELECT TIPO_DOCUMENTO, SERIE_DEL_CHEQUE, NUMERO_CHEQUE, BANCO_GIRADO, SUCURSAL_BANCO_GIRADO, NUMERICO_CUENTA_GIRADORA, IMPORTE, FECHA_ACREDITACION, JTS_OID_DESCUENTO
	FROM CLE_CHEQUES_SALIENTE WITH(NOLOCK)
	WHERE FECHA_ENVIO_COMPENSACION >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))
	AND FECHA_ENVIO_CAMARA >= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK)) 
	AND TZ_LOCK = 0 AND ACREDITADO = 0 AND DESTINO_CHEQUE = 3 AND
	NRO_SOLICITUD IN (SELECT NRO_SOLICITUD FROM CHE_CHEQUES WITH(NOLOCK) WHERE TZ_LOCK = 0)) a
')


EXECUTE('
IF OBJECT_ID (''dbo.VW_FAMILIAS_LIMITE'') IS NOT NULL
	DROP VIEW dbo.VW_FAMILIAS_LIMITE
')

EXECUTE('
CREATE VIEW [dbo].[VW_FAMILIAS_LIMITE] (
CLIENTE, 
LIMITE, 
RIESGO, 
FAMILIA, 
DESCRIPCION)
AS 
SELECT DISTINCT TOP 9223372036854775807 WITH TIES 
	fci.CLIENTE, 
	fci.LIMITE, 
	fci.RIESGO, 
	fci.FAMILIA, 
	fci.DESCRIPCION
FROM 
(
	SELECT 
		LC.CLIENTE AS CLIENTE, 
		LC.IDLIMITE AS LIMITE, 
		FL.CODIGO_RIESGO AS RIESGO, 
		FL.FAMILIA AS FAMILIA, 
		F.DESCRIPCION AS DESCRIPCION
	FROM dbo.CRE_LIMITECLIENTE  AS LC WITH(NOLOCK)
	INNER JOIN dbo.CRE_FAMILIALIC  AS FL WITH(NOLOCK) ON LC.IDLIMITE = FL.IDLIMITE
	INNER JOIN dbo.CRE_FAMILIAS  AS F WITH(NOLOCK) ON FL.FAMILIA = F.FAMILIAPROD
	INNER JOIN CRE_TIPOS_RIESGOS AS R WITH(NOLOCK) ON FL.CODIGO_RIESGO = R.CODIGO_RIESGO AND R.EXTRAORDINARIO IN (''N'',''S'')
	WHERE 
	((LC.TZ_LOCK < 300000000000000 OR LC.TZ_LOCK >= 400000000000000) AND (LC.TZ_LOCK < 100000000000000 OR LC.TZ_LOCK >= 200000000000000)) AND 
	((FL.TZ_LOCK < 300000000000000 OR FL.TZ_LOCK >= 400000000000000) AND (FL.TZ_LOCK < 100000000000000 OR FL.TZ_LOCK >= 200000000000000)) AND 
	((F.TZ_LOCK < 300000000000000 OR F.TZ_LOCK >= 400000000000000) AND (F.TZ_LOCK < 100000000000000 OR F.TZ_LOCK >= 200000000000000)) AND
	((R.TZ_LOCK < 300000000000000 OR R.TZ_LOCK >= 400000000000000) AND (R.TZ_LOCK < 100000000000000 OR R.TZ_LOCK >= 200000000000000))   
)  AS fci
ORDER BY fci.CLIENTE, fci.FAMILIA;
')

EXECUTE('
IF OBJECT_ID (''dbo.VW_CASTIGOCARTERA'') IS NOT NULL
	DROP VIEW dbo.VW_CASTIGOCARTERA
')

EXECUTE('
CREATE   VIEW [dbo].[VW_CASTIGOCARTERA] (
TipoDocumento, 
Documento,
Nombre,
TipoPersona, 
Cliente)
AS 
SELECT DISTINCT cli.TIPODOC AS TipoDocumento, 
		cli.NUMERODOC AS Documento, 
		cli.NOMBRECLIENTE AS Nombre, 
		cli.TIPOPERSONA AS TipoPersona, 
		cli.CODIGOCLIENTE AS Cliente
FROM VW_CLI_X_DOC cli WITH(NOLOCK)
JOIN (SELECT h.CLIENTE
	FROM VW_CLI_X_DOC cli WITH(NOLOCK)
	INNER JOIN HISTORICO_CALIF_X_CLIENTE h WITH(NOLOCK) ON cli.CODIGOCLIENTE = h.CLIENTE AND h.TZ_LOCK = 0
	AND h.FECHA_SITUACION < DATEADD(MM, -(SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 160), (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))) 
	GROUP BY h.CLIENTE
	HAVING max(h.FECHA_SITUACION) IN (SELECT FECHA_SITUACION 
									FROM HISTORICO_CALIF_X_CLIENTE h2 WITH(NOLOCK) 
									INNER JOIN CLI_CLASUBJETIVA c WITH(NOLOCK) ON h2.CALIFICACION_RESULTANTE = c.CATEGORIASUB 
									AND c.PONDERACION >= (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH(NOLOCK) WHERE CATEGORIASUB = (SELECT PARAMETRO_ALFA FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 161)) AND c.TZ_LOCK = 0
									WHERE h2.CLIENTE = h.CLIENTE AND h2.TZ_LOCK = 0)) a2 
	ON cli.CODIGOCLIENTE = a2.CLIENTE
WHERE cli.CODIGOCLIENTE NOT IN (SELECT cli.CODIGOCLIENTE
								FROM VW_CLI_X_DOC cli WITH(NOLOCK)
								INNER JOIN HISTORICO_CALIF_X_CLIENTE h WITH(NOLOCK) ON cli.CODIGOCLIENTE = h.CLIENTE AND h.TZ_LOCK = 0
								AND h.FECHA_SITUACION >= DATEADD(MM, -(SELECT DIASINMOVILIZADA FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 160), (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK))) AND h.FECHA_SITUACION <= (SELECT FECHAPROCESO FROM PARAMETROS WITH(NOLOCK)) 
								INNER JOIN CLI_CLASUBJETIVA c WITH(NOLOCK) ON h.CALIFICACION_RESULTANTE = c.CATEGORIASUB 
								AND c.PONDERACION < (SELECT PONDERACION FROM CLI_CLASUBJETIVA WITH(NOLOCK) WHERE CATEGORIASUB = (SELECT PARAMETRO_ALFA FROM CRE_PARAMETROS WITH(NOLOCK) WHERE CODIGO = 161)) AND c.TZ_LOCK = 0
								GROUP BY cli.CODIGOCLIENTE
								HAVING count(*) > 0)
')











