EXECUTE('DROP procedure IF EXISTS [dbo].[SP_ITF_ENVIO_PBF];');
EXECUTE('DROP procedure IF EXISTS [dbo].[SP_CARGASWIFT_NBC];');
EXECUTE('DROP procedure IF EXISTS [dbo].[SP_ITF_ACTUALIZAR_GASTOSXCUOTA];');
EXECUTE('DROP procedure IF EXISTS [dbo].[SP_INTEGRIDAD_REFERENCIAL];');