EXECUTE('DROP TABLE IF EXISTS dbo.TJD_LINK_MAESTRO;')

EXECUTE('
CREATE TABLE dbo.TJD_LINK_MAESTRO
	(
	ID_TARJETA              VARCHAR (19) DEFAULT ('' '') NOT NULL,
	COD_TRAN                VARCHAR (6) DEFAULT ('' '') NOT NULL,
	TIPO_TARJETA            VARCHAR (2) DEFAULT ('' ''),
	ESTADO_TARJETA          VARCHAR (1) DEFAULT ('' ''),
	FECHA_ENTREGA_TARJ      VARCHAR (8),
	VENCIMIENTO_TARJETA     VARCHAR (4),
	LIMITE_MONTO_TARJETA    VARCHAR (2) DEFAULT ('' ''),
	NUM_VERSION_TARJ        VARCHAR (1) DEFAULT ('' ''),
	DIGITO_VERIFICADOR_TARJ VARCHAR (1) DEFAULT ('' ''),
	NRO_PERSONA             NUMERIC (12) DEFAULT ((0)),
	NRO_CLIENTE             NUMERIC (12) DEFAULT ((0)),
	TZ_LOCK                 NUMERIC (15) DEFAULT ((0)) NOT NULL,
	PROCESADO               VARCHAR (1) DEFAULT (''N''),
	PRODUCTO                VARCHAR (4),
	NOMBRE_TARJETA          VARCHAR (30),
	LIMITE_CREDITO          VARCHAR (2),
	CONSTRAINT PK_TJD_LINK_MAESTRO_01 PRIMARY KEY (ID_TARJETA, COD_TRAN)
	);')
	
EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (35000, '' '', 0, ''LIMITE_CREDITO'', ''Límite Crédito'', 2, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3472, ''LIMITE_CREDITO'', 0, NULL);')
