EXECUTE('
CREATE PROCEDURE dbo.SP_CONTROL_INTEGRANTES  
   @P_NUMEROPERSONA NUMERIC(12),
   @P_RETURN NUMERIC(3)  OUTPUT
AS 
	BEGIN
	SET NOCOUNT ON;  
	SET @P_RETURN = NULL
			  	SET @P_RETURN =(
				      SELECT COUNT(*) FROM dbo.CLI_INTEGRANTESPJ AS D
				      WHERE D.NUMEROPERSONAJURIDICA= @P_NUMEROPERSONA AND D.TIPOVINCULACION=''C'' AND D.TZ_LOCK BETWEEN 200000000000000 AND 300000000000000)
				END
')