EXECUTE('
-------------------------------
--INSERT DE REPORTES CLEARING--
-------------------------------
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (1800, 1638, ''Totales Clearing Enviado (jas)'', ''J'', 0, NULL, 0, 0, 0, ''N'')
--
INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (1638, 1, NULL, 0, 0, 1)
----
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (1800, 1639, ''Detalle Clearing Enviado'', ''J'', 0, NULL, 0, 0, 0, ''N'')
--
INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (1639, 1, NULL, 0, 0, 1)
----
INSERT INTO REPORTES (TITULO, IDENTIFICACION, DESCRIPCION, TIPO, BIGREPORT, TIPOSALIDA, GENERAREPORTE, GENERAONLINEREPORTE, GRUPO_REIMPRESION, EJ_DE_OPERACION)
VALUES (1800, 1640, ''Cle - Enviado x Bco y estado'', ''J'', 0, NULL, 0, 0, 0, ''N'')
--
INSERT INTO REPORTESJASPER (IDENTIFICACION, DESTINO, DATAQUERY, COMPILADO, FORCE, SELECTIVEDESTINATION)
VALUES (1640, 1, NULL, 0, 0, 1)
----

')