EXECUTE('

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45191, '' '', 0, ''Id Convenio Pagos'', ''Id Convenio Pagos'', 15, ''N'', 0, NULL, 0, 19, 0, 0, 0, 0, 0, 0, ''ID_CONVENIO_PAGOS'', 0, NULL)

INSERT INTO NUMERATORDEFINITION (NUMERO, INIVAL, INCREMENTO, PERIODO, ULTIMAINIC, REUTILIZABLE, CENTRALIZADO, MAXIMO, DESCRIPCION, TIPO)
VALUES (45191, 20030, 1, ''A'', NULL, 1, 0, 0, NULL, ''T'')

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (45192, '' '', 0, ''Cuenta Debito Secundaria'', ''Cuenta Debito Secundaria'', 10, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 4472, ''CuentaDebSec'', 0, NULL)

INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (7241, '' '', 0, ''Cuenta Secundaria'', ''Cuenta secundaria'', 12, ''N'', 0, NULL, 0, 0, 0, 0, 0, 45451, 0, 0, ''C7241'', 0, NULL)

UPDATE OPCIONES
SET DESCRIPCION = ''Acreditación o Movimiento''
WHERE NUMERODECAMPO = 44840 AND IDIOMA = ''E'' AND OPCIONINTERNA = ''RL''

')