EXECUTE('
IF OBJECT_ID (''SALDOSCAJA_HISTORICO'') IS NOT NULL
DROP TABLE dbo.SALDOSCAJA_HISTORICO;
')
EXECUTE('
CREATE TABLE dbo.SALDOSCAJA_HISTORICO
	(
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	FECHAPROCESO DATETIME NOT NULL,
	NROCAJA      NUMERIC (3) DEFAULT ((0)) NOT NULL,
	MONEDA       NUMERIC (4) DEFAULT ((0)) NOT NULL,
	SALDOINICIAL NUMERIC (15, 2) DEFAULT ((0)),
	ENTRADAS     NUMERIC (15, 2) DEFAULT ((0)),
	SALIDAS      NUMERIC (15, 2) DEFAULT ((0)),
	MINIMOAVISO  NUMERIC (15, 2) DEFAULT ((0)),
	MAXIMOAVISO  NUMERIC (15, 2) DEFAULT ((0)),
	SUCURSAL     NUMERIC (5) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_SALDOSCAJA_HISTORICO PRIMARY KEY (FECHAPROCESO, NROCAJA, MONEDA, SUCURSAL)
	)
')
EXECUTE('

CREATE OR ALTER VIEW [dbo].[VW_BILLETAJE_PARA_REPORTE] AS
SELECT 
b.SUCURSAL,
b.ASIENTO,
b.CAJA,
c.ESTADO,
c.MINIFILIAL,
b.FECHA,
b.MONEDA,
b.TIPO,
b.DENOMINACION,
b.DETERIORADO,
b.CANTIDAD,
(b.DENOMINACION*b.CANTIDAD) AS ''IMPORTE'',
(s.SALDOINICIAL+s.ENTRADAS-s.SALIDAS) AS ''ACTUAL_CONTABLE_MONEDA''
FROM CAJ_HISTORIAL_BILLETAJE b LEFT JOIN VW_CAJ_CAJAS c ON 
c.NRO_CAJA=b.CAJA AND c.SUCURSAL=b.SUCURSAL LEFT JOIN SALDOSCAJA_HISTORICO s ON s.FECHAPROCESO=b.FECHA AND s.NROCAJA=b.CAJA AND s.MONEDA=b.MONEDA AND s.SUCURSAL=b.SUCURSAL
WHERE b.ASIENTO IN (SELECT MAX(ASIENTO) FROM CAJ_HISTORIAL_BILLETAJE WHERE SUCURSAL=b.SUCURSAL AND CAJA=b.CAJA  AND FECHA=b.FECHA AND TZ_LOCK=0 GROUP BY CAJA)
AND ((b.TZ_LOCK < 300000000000000 OR b.TZ_LOCK >= 400000000000000) AND (b.TZ_LOCK < 100000000000000 OR b.TZ_LOCK >= 200000000000000))

')