EXECUTE('

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, 
REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, 
CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44477, NULL, 0, ''MODALIDAD'', ''MODALIDAD'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 4447, ''MODALIDAD'', 0, NULL)

UPDATE dbo.AYUDAS
SET CAMPOS = ''44471R;44472R;44473;44474;44477R;''
WHERE NUMERODEAYUDA = 44475
 
UPDATE dbo.INDICES
SET CAMPO3 = 44477
WHERE NUMERODEARCHIVO = 4447 AND NUMERODEINDICE = 1


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44477, ''E'', ''Consumo'', ''C'', ''C'')


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (44477, ''E'', ''Comercial'', ''M'', ''M'')

')