EXECUTE('

INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008178'', ''ACTIVAS'', ''O'', NULL, 1, NULL)

INSERT INTO RESTRICCIONES (IDENTIFICACION, GRUPO, TIPO, DESCRIPCION, PERMITE, FECHA_HABILITACION)
VALUES (''80008179'', ''ACTIVAS'', ''O'', NULL, 1, NULL)
')

EXECUTE('
ALTER TABLE BS_HISTORIA_PLAZO ALTER COLUMN detalle_gastos VARCHAR(max)

ALTER TABLE BS_HISTORIA_PLAZO ALTER COLUMN detalle_cuotas VARCHAR(max)
')