EXECUTE('
-----------------------------------
--INSERT OPERACION PARAMETROS JTS--
-----------------------------------
INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (8600, 8624, ''PA Bandeja Movimientos Contables'', ''PA Bandeja Movimientos Contables'', ''8624'', ''N'', 500, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''S'', NULL, 0)
----
')