EXECUTE('
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41448, '' '', NULL, ''Nro.de Cuota'', ''Nro.de Cuota'', 3, ''N'', 0, ''I'', 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41448'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41449, '' '', NULL, ''Fecha de Vto.'', ''Fecha de Vto.'', 8, ''F'', 0, ''F'', 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41449'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41450, '' '', 0, ''Fecha de Pago'', ''Fecha de Pago'', 8, ''F'', 0, ''F'', 0, 0, 0, 0, 0, 0, 0, 0, ''C41450'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41451, '' '', NULL, ''Dias de atraso'', ''Dias de atraso'', 12, ''N'', 0, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41451'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41452, '' '', NULL, ''Capital'', ''Capital'', 15, ''N'', 2, ''I'', 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41452'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41453, '' '', 0, ''Tasa de Interes'', ''Tasa de Interes'', 11, ''N'', 7, ''I'', 0, 0, 0, 0, 0, 0, 0, 0, ''C41453'', 0, NULL)

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41454, '' '', NULL, ''Intereses'', ''Intereses'', 15, ''N'', 2, ''I'', 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41454'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41455, '' '', NULL, ''Iva Interes'', ''Iva Interes'', 15, ''N'', 2, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41455'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41456, '' '', NULL, ''Intereses Moratorios'', ''Intereses Moratorios '', 15, ''N'', 2, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41456'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41457, '' '', NULL, ''Iva Mora'', ''Iva Mora'', 15, ''N'', 2, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41457'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41458, '' '', NULL, ''Intereses Punitorios'', ''Intereses Punitorios'', 15, ''N'', 2, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41458'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41459, '' '', NULL, ''Monto total de la Cuota'', ''Monto total de la Cuota'', 15, ''N'', 2, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41459'', 0, '' '')

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (41460, '' '', NULL, ''Saldo Capital'', ''Saldo Capital'', 15, ''N'', 2, ''I'', 0, 0, NULL, NULL, NULL, NULL, 0, 0, ''C41460'', 0, '' '')

INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (341, 0, 3451, 1, ''Cod. Cliente por CUIT o CUIL'', NULL, NULL)

INSERT INTO dbo.MACROR (PROCESO, ORDINAL, ARCHIVO, INDICE, CONDICION, RECEPTOR, FORMULA)
VALUES (341, 1, 3451, 1, ''C34511=C3250Y(A(C34510="CUIL")OA(C34510="CUIT"))'', ''C3793'', ''C34513'')

')