EXECUTE('
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 44503

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (44503, '' '', 0, ''ID_Cargo_IVA'', ''ID_Cargo_IVA'', 4, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL)
')