EXECUTE('
IF OBJECT_ID (''dbo.SOS_VINCULACION'') IS NOT NULL
	DROP TABLE dbo.SOS_VINCULACION
')

EXECUTE('
CREATE TABLE dbo.SOS_VINCULACION
	(
	EMPRESA                NUMERIC (4) NOT NULL,
	FECHADEINFORMACION     NUMERIC (8) NOT NULL,
	CLASEDECUENTA          VARCHAR (3),
	NUMERODECUENTA         VARCHAR (22),
	TIPODECUENTAUOPERACION VARCHAR (3),
	NUMERODEOPERACION      VARCHAR (22),
	SUCURSALSISCEN         VARCHAR (5),
	IDENTTRIBUTARIATIPO    NUMERIC (2),
	IDENTTRIBUTARIANUMERO  NUMERIC (16),
	CONDICION              NUMERIC (2),
	ORDENRELACION          NUMERIC (2),
	FECHAALTA              VARCHAR (8),
	CODCLIENTE             NUMERIC (12),
	NROPERSFISICAJURIDICA  NUMERIC (12)
	)
')

