EXECUTE('
IF OBJECT_ID (''dbo.ITF_COELSA_WS'') IS NOT NULL
	DROP TABLE dbo.ITF_COELSA_WS
')
EXECUTE('
CREATE TABLE dbo.ITF_COELSA_WS
	(
	CBU          VARCHAR (30) DEFAULT ('' '') NOT NULL,
	CUIT         NUMERIC (22) DEFAULT ((0)) NOT NULL,
	NOMBRE       VARCHAR (250) DEFAULT ('' ''),
	TIPO_PERSONA VARCHAR (1) DEFAULT ('' ''),
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CUIT1        NUMERIC (30),
	CONSTRAINT PK_ITF_COELSA_WS_01 PRIMARY KEY (CBU, CUIT)
	)
')
EXECUTE('
	
DELETE FROM dbo.INDICES
WHERE NUMERODEARCHIVO = 6666 AND NUMERODEINDICE = 1
 
DELETE FROM dbo.DESCRIPTORES
WHERE TITULO = 1122 AND IDENTIFICACION = 6666
 
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (1122, 6666, NULL, ''ITF_COELSA_WS'', 0, ''ITF_COELSA_WS'', ''D'', NULL, NULL, ''Top/Clientes'', NULL, ''N'')
 
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (6666, 1, ''Indice COELSA'', 0, 66666, 66667, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
 
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 3686
 
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 66666
 
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 66667
 
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 66668
 
DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 66669
 
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (3686, NULL, 0, ''CUIT1'', ''CUIT1'', 30, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 6666, ''CUIT1'', 0, NULL)
 
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (66666, '' '', 0, ''CBU'', ''CBU'', 30, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 6666, ''CBU'', 0, NULL)
 
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (66667, '' '', 0, ''CUIT'', ''CUIT'', 22, ''N'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 6666, ''CUIT'', 0, NULL)
 
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (66668, '' '', 0, ''NOMBRE'', ''NOMBRE'', 250, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 6666, ''NOMBRE'', 0, NULL)
 
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (66669, '' '', 0, ''TIPO_PERSONA'', ''TIPO_PERSONA'', 1, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 6666, ''TIPO_PERSONA'', 0, NULL)
 
DELETE FROM dbo.AYUDAS
WHERE NUMERODEAYUDA = 66661

INSERT INTO dbo.AYUDAS (NUMERODEARCHIVO, NUMERODEAYUDA, DESCRIPCION, FILTRO, MOSTRARTODOS, CAMPOS, CAMPOSVISTA, BASEVISTA, NOMBREVISTA, AYUDAGRANDE)
VALUES (6666, 66661, ''AYUDA_COELSA'', '''', 0, ''66666;66667;66668R;66669R;'', NULL, NULL, NULL, 0)
 
DELETE FROM dbo.ITF_MASTER
WHERE ID = 63

INSERT INTO dbo.ITF_MASTER (TZ_LOCK, ID, DESCRIPCION, OBJ_KETTLE, P0_MODO, P0_TIPO, P0_CAPTION, P0_CONSTANTE, P1_MODO, P1_TIPO, P1_CAPTION, P1_CONSTANTE, P2_MODO, P2_TIPO, P2_CAPTION, P2_CONSTANTE, P3_MODO, P3_TIPO, P3_CAPTION, P3_CONSTANTE, P4_MODO, P4_TIPO, P4_CAPTION, P4_CONSTANTE, P5_MODO, P5_TIPO, P5_CAPTION, P5_CONSTANTE, P6_MODO, P6_TIPO, P6_CAPTION, P6_CONSTANTE, P7_MODO, P7_TIPO, P7_CAPTION, P7_CONSTANTE, P8_MODO, P8_TIPO, P8_CONSTANTE, P8_CAPTION, P9_MODO, P9_TIPO, P9_CAPTION, P9_CONSTANTE, TIPO_OBJ, COMENTARIO, ID_REPORTE, MODO_EJECUCION)
VALUES (0, 63, ''COELSA ALIAS CBU'', ''ITF_COELSA_CBU_ALIAS.kjb'', '''', '''', '' '', '''', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', '' '', ''J'', '' '', 0, ''M'')

DELETE FROM dbo.OPERACIONES
WHERE TITULO = 7946 AND IDENTIFICACION = 6663
 
INSERT INTO dbo.OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO, ICONO_TITULO, ESTILO)
VALUES (7946, 6663, ''MACRO KETTLE COELSA'', ''MACRO KETTLE COELSA'', ''6663'', ''N'', NULL, NULL, ''P'', 0, NULL, 0, ''S'', ''N'', ''N'', ''N'', ''N'', NULL, 0)
 
')