EXECUTE('
IF OBJECT_ID (''dbo.VW_CRE_SOL_ASISTENCIAS_REF'') IS NOT NULL
	DROP VIEW dbo.VW_CRE_SOL_ASISTENCIAS_REF
')

EXECUTE('
CREATE VIEW dbo.VW_CRE_SOL_ASISTENCIAS_REF 
AS 
SELECT 
r.NUMERO_SOLICITUD,
p.C6251 AS CONCEPTO,
concat(''Nº: '', convert(VARCHAR(50),s.OPERACION)) AS OPERACION,
((isnull(r.INTS_REESTRUCTURA,0)+isnull(r.CAP_REESTRUCTURA,0)) - (isnull(r.CAPITAL_BONIFICADO,0)+isnull(r.INTERES_BONIFICADO,0)+isnull(r.MORATORIO_BONIFICADO,0)+isnull(r.PUNITORIO_BONIFICADO,0)+isnull(r.GASTOS_BONIFICADO,0))) AS IMPORTE_CANCELADO
FROM SALDOS s WITH (NOLOCK)
INNER JOIN CRE_DET_REESTRUCTURA r WITH (NOLOCK) ON s.JTS_OID=r.JTS_OID_REESTRUCTURADA AND r.TZ_LOCK=0
INNER JOIN PRODUCTOS p ON p.C6250=s.PRODUCTO AND   ( (p.tz_lock < 300000000000000 OR p.tz_lock >= 400000000000000) AND (p.tz_lock < 100000000000000 OR p.tz_lock >= 200000000000000)  )	
UNION  
SELECT
dext.NUMERO_SOLICITUD,
ext.DESCRIPCION AS CONCEPTO,
concat(ded.ID, '' - '', ded.DESCRIPCION) AS OPERACION,
dext.IMPORTE AS IMPORTE_CANCELADO
FROM CRE_SOL_DEUDA_EXTERNA dext WITH (NOLOCK)
INNER  JOIN CRE_ENTIDADEXTERNA ext ON dext.CODIGO_ENTE=ext.CODIGO
LEFT JOIN CRE_CODIGOS_DEDUCCIONES ded ON ded.ID=ext.COD_ECOM
')

EXECUTE('
UPDATE dbo.REPORTES
SET DESCRIPCION = ''Detalle deuda a cancelar/ cancelada''
WHERE TITULO = 6650 AND IDENTIFICACION = 8075

UPDATE dbo.REPORTES
SET DESCRIPCION = ''Cupón de Liquidación''
WHERE TITULO = 6650 AND IDENTIFICACION = 8074
')