execute('DROP TABLE IF EXISTS ITF_AFIP_RG_INCONSISTENCIAS_ERRORES');

execute(
'CREATE TABLE ITF_AFIP_RG_INCONSISTENCIAS_ERRORES
(
    ID INT IDENTITY,
    NRO_LINEA INT,
    CUIT VARCHAR(11),
    RAZON_SOCIAL VARCHAR(80),
    TIPO_CERTIFICADO VARCHAR(10),
    PORCENTAJE VARCHAR(10),
    FECHA_DESDE VARCHAR(10),
    FECHA_HASTA VARCHAR(10),
    DESCRIPCION_ERROR VARCHAR(200),
    INCISO_RESOLUCION_GRAL VARCHAR(10),
    ORIGEN VARCHAR(50),
    TICKET VARCHAR(20),
    FECHA_PROCESO DATETIME,
    CONSTRAINT PK_ITF_AFIP_RG_INCONSISTENCIAS_ERRORES 
        PRIMARY KEY (TICKET, NRO_LINEA)
)'
);