


-- Patch_NUGAN106_41

-- Crea la tabla BITACORA_UAREU4500FINGERDATA
CREATE TABLE BITACORA_UAREU4500FINGERDATA
(
USUARIO    VARCHAR (8) NOT NULL,
FINGERKEY  NUMERIC NOT NULL,
FINGERDATA IMAGE,
BIT_FECHA_HORA DATETIME NOT NULL,
BIT_USUARIO    VARCHAR (8) NOT NULL,
BIT_ACCION     VARCHAR (20) NOT NULL,
CONSTRAINT PK_BITACORA_UAREU PRIMARY KEY (BIT_FECHA_HORA, USUARIO, FINGERKEY)
);

-- Crea la tabla BITACORA_PERSONFINGERDATA
CREATE TABLE BITACORA_PERSONFINGERDATA
(
NUMEROPERSONAFISICA NUMERIC (12) NOT NULL,
FINGERKEY           NUMERIC NOT NULL,
FINGERDATA          IMAGE,
FINGERDATAANSI      IMAGE,
FINGERDATABMP       IMAGE,
BIT_FECHA_HORA DATETIME NOT NULL,
BIT_USUARIO    VARCHAR (8) NOT NULL,
BIT_ACCION     VARCHAR (20) NOT NULL,
CONSTRAINT PK_BITACORA_PERSONFINGERDATA PRIMARY KEY (BIT_FECHA_HORA, NUMEROPERSONAFISICA, FINGERKEY)
);

-- Agrega campo TIPOLOGIN
ALTER table USUARIOS add TIPOLOGIN NUMERIC(5) DEFAULT '0';

ALTER table BITACORA_USUARIOS add TIPOLOGIN NUMERIC(5);




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20210210_2',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VR0FOMTA2XzQxCg0KLS0gQ3JlYSBsYSB0YWJsYSBCSVRBQ09SQV9VQVJF
VTQ1MDBGSU5HRVJEQVRBDQpDUkVBVEUgVEFCTEUgQklUQUNPUkFfVUFSRVU0NTAwRklOR0VSREFU
QQooClVTVUFSSU8gICAgVkFSQ0hBUiAoOCkgTk9UIE5VTEwsCkZJTkdFUktFWSAgTlVNRVJJQyBO
T1QgTlVMTCwKRklOR0VSREFUQSBJTUFHRSwKQklUX0ZFQ0hBX0hPUkEgREFURVRJTUUgTk9UIE5V
TEwsCkJJVF9VU1VBUklPICAgIFZBUkNIQVIgKDgpIE5PVCBOVUxMLApCSVRfQUNDSU9OICAgICBW
QVJDSEFSICgyMCkgTk9UIE5VTEwsCkNPTlNUUkFJTlQgUEtfQklUQUNPUkFfVUFSRVUgUFJJTUFS
WSBLRVkgKEJJVF9GRUNIQV9IT1JBLCBVU1VBUklPLCBGSU5HRVJLRVkpCik7Cg0KLS0gQ3JlYSBs
YSB0YWJsYSBCSVRBQ09SQV9QRVJTT05GSU5HRVJEQVRBDQpDUkVBVEUgVEFCTEUgQklUQUNPUkFf
UEVSU09ORklOR0VSREFUQQooCk5VTUVST1BFUlNPTkFGSVNJQ0EgTlVNRVJJQyAoMTIpIE5PVCBO
VUxMLApGSU5HRVJLRVkgICAgICAgICAgIE5VTUVSSUMgTk9UIE5VTEwsCkZJTkdFUkRBVEEgICAg
ICAgICAgSU1BR0UsCkZJTkdFUkRBVEFBTlNJICAgICAgSU1BR0UsCkZJTkdFUkRBVEFCTVAgICAg
ICAgSU1BR0UsCkJJVF9GRUNIQV9IT1JBIERBVEVUSU1FIE5PVCBOVUxMLApCSVRfVVNVQVJJTyAg
ICBWQVJDSEFSICg4KSBOT1QgTlVMTCwKQklUX0FDQ0lPTiAgICAgVkFSQ0hBUiAoMjApIE5PVCBO
VUxMLApDT05TVFJBSU5UIFBLX0JJVEFDT1JBX1BFUlNPTkZJTkdFUkRBVEEgUFJJTUFSWSBLRVkg
KEJJVF9GRUNIQV9IT1JBLCBOVU1FUk9QRVJTT05BRklTSUNBLCBGSU5HRVJLRVkpCik7Cg0KLS0g
QWdyZWdhIGNhbXBvIFRJUE9MT0dJTg0KQUxURVIgdGFibGUgVVNVQVJJT1MgYWRkIFRJUE9MT0dJ
TiBOVU1FUklDKDUpIERFRkFVTFQgJzAnOwoKQUxURVIgdGFibGUgQklUQUNPUkFfVVNVQVJJT1Mg
YWRkIFRJUE9MT0dJTiBOVU1FUklDKDUpOwoNCgoKDQo=', NULL, 0);
