EXECUTE('
CREATE SEQUENCE dbo.BITACORA_CLIENTE_ORDINAL 
	START WITH 1  
	INCREMENT BY 1
	MINVALUE 1  
	MAXVALUE 999999  
	CYCLE  
	NO CACHE;
 
CREATE SEQUENCE dbo.BITACORA_FISICA_ORDINAL 
	START WITH 1  
	INCREMENT BY 1
	MINVALUE 1  
	MAXVALUE 999999  
	CYCLE  
	NO CACHE;

CREATE SEQUENCE dbo.BITACORA_JURIDICA_ORDINAL 
	START WITH 1  
	INCREMENT BY 1
	MINVALUE 1  
	MAXVALUE 999999  
	CYCLE  
	NO CACHE;
')