EXECUTE('
-------------------------
--NUEVO CAMPO VW_COFRES--
-------------------------
INSERT INTO DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (34987, '' '', 0, ''Tipo de Caja de Seguridad'', ''Tipo de Caja de Seguridad'', 60, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 805, ''DESCRIPCION_TIPO'', 0, NULL)
----
UPDATE AYUDAS
SET DESCRIPCION = ''Cajas de Seguridad Libres''
	, CAMPOS = ''8054OA1;8055OA2;34987;8059;8053R;34878;''
WHERE NUMERODEAYUDA = 8053
----
')