
INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 16, 3, 'LAS BOMBAS', 5301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 16, 4, 'VILLA BUSTOS', 5301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 16, 5, 'VILLA SANAGASTA', 5379, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 16, 6, 'DIQUE LOS SAUCES', 5300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 1, 'EL HORNO', 5357, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 2, 'LA BANDA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 3, 'POTRERO GRANDE', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 4, 'VALLE HERMOSO', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 5, 'VINCHINA', 5357, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 6, 'BUENA VISTA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 17, 7, 'LA PAMPA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 1, 'ALTO JAGUEL', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 2, 'BAJO JAGUEL', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 3, 'CASA PINTADA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 4, 'DISTRITO PUEBLO', 5371, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 5, 'JAGUE', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 6, 'LA CIENAGA', 5350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 7, 'BOCA DE LA QUEBRADA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 8, 'LA ARMONIA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'F', 18, 9, 'VILLA SAN JOSE DE VINCHINA', 5359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 1, 'COLONIA SANTA ROSA AGUIRRE', 2357, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 2, 'MALBRAN', 2355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 3, 'PINTO - VILLA GENERAL MITRE', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 4, 'ARBOL NEGRO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 5, 'AZUCENA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 6, 'CAMPO RAMON LAPLACE', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 7, 'CAPILLA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 8, 'CLEVELAND', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 9, 'COLONIA ERMELINDA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 10, 'COLONIA PAULA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 11, 'EL DESTINO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 12, 'EL GALPON', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 13, 'EL SOLITARIO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 14, 'GUARDIA VIEJA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 15, 'LA CASIMIRA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 16, 'LAS ABRAS DE SAN ANTONIO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 17, 'LAS ALMAS', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 18, 'LAS DELICIAS', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 19, 'LIBERTAD', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 20, 'LOS MILAGROS', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 21, 'MARTIN PASO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 22, 'MONTE CRECIDO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 23, 'PUNTA DEL GARABATO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 24, 'PUNTA DEL MONTE', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 25, 'QUEBRACHITOS', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 26, 'SAN AGUSTIN', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 27, 'SAN JOSE', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 28, 'SAN RUFINO', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 29, 'TOME Y TRAIGA', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 30, 'ALARCON', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 31, 'CASARES', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 32, 'ARGENTINA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 33, 'EL AIBAL', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 34, 'EL ASPIRANTE', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 35, 'EL OSO', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 36, 'EL UCLE', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 37, 'FORTIN LA VIUDA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 38, 'KILOMETRO 735', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 39, 'KILOMETRO 764', 2356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 40, 'LA BLANCA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 41, 'LA CAROLINA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 42, 'LA CENTELLA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 43, 'LA ESMERALDA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 44, 'LA RECOMPENSA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 45, 'LAS PALMAS', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 46, 'MARAVILLA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 47, 'NUEVA TRINIDAD', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 48, 'PALMAS', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 49, 'SAN SEBASTIAN', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 50, 'SANTA ANA', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 51, 'TRES LAGUNAS', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 1, 52, 'TRES POZOS', 2354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 1, 'BUEN LUGAR', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 2, 'CAMPO GALLO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 3, 'CAMPO GRANDE', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 4, 'CEJAS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 5, 'CUQUENOS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 6, 'EL MILAGRO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 7, 'EL OLIVAR', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 8, 'EL PORVENIR', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 9, 'ESTEROS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 10, 'FORTUNA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 11, 'HUACHANA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 12, 'LA PALOMA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 13, 'LAS PALMITAS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 14, 'MAJANCITO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 15, 'MONTEVIDEO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 16, 'MORADITO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 17, 'NARANJITO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 18, 'NORQUEOJ', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 19, 'NUEVA GRANADA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 20, 'POZO GRANDE', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 21, 'RANCHITOS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 22, 'RETIRO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 23, 'SACHAYOJ', 3731, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 24, 'SANTA CRUZ', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 25, 'SANTA ROSA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 26, 'SANTOS LUGARES', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 27, 'TACANITAS', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 28, 'TACO POZO', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 29, 'TARPUNA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 30, 'VILLA PALMAR', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 31, 'AIBALITO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 32, 'ALBERDI', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 33, 'EL SIMBOLAR', 3474, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 34, 'ESTANCIA LA AGUSTINA', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 35, 'KILOMETRO 20', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 36, 'LA FLORIDA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 37, 'SAN RAMON', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 38, 'PUNTA RIELES', 3731, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 39, 'AGUA BLANCA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 40, 'AGUSTINA LIBARONA', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 41, 'CAMPO ALEGRE', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 42, 'CENTRAL DOLORES', 3745, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 43, 'CORONEL MANUEL LEONCIO RICO', 3712, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 44, 'CUQUERO', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 45, 'DOBLE TERO', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 46, 'DONADEU', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 47, 'DOS EULALIAS', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 48, 'EL CAMBIADO', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 49, 'EL COLMENAR', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 50, 'EL FISCO', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 51, 'EL NOVENTA', 3741, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 52, 'EL OSCURO', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 53, 'EL SETENTA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 54, 'EL SIMBOL', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 55, 'EL TRASLADO', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 56, 'FLORIDA', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 57, 'VILLA HAZAN', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 58, 'KILOMETRO 1362', 3712, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 59, 'KILOMETRO 1380', 3712, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 60, 'KILOMETRO 1391', 3712, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 61, 'LA AMERICA', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 62, 'LA ARGENTINA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 63, 'LA ARMONIA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 64, 'LA FORTUNA', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 65, 'LA MANGA', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 66, 'LAS AGUILAS', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 67, 'LAS CARPAS', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 68, 'LAS PERFORACIONES', 3712, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 69, 'LOS CARRIZOS', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 70, 'MAIDANA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 71, 'MOJON', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 72, 'MONTE VERDE', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 73, 'NUEVO LIBANO', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 74, 'NUEVO LUJAN', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 75, 'OBRAJE IRIONDO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 76, 'POZO MUERTO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 77, 'POZO SALADO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 78, 'RIVADAVIA', 3749, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 79, 'SALADILLO', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 80, 'SAN ANTONIO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 81, 'SAN ENRIQUE', 4324, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 82, 'SEPULTURA', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 83, 'YUNTA POZO', 3747, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 2, 84, 'ZANJA', 4197, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 1, 'ALBARDON', 4208, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 2, 'AYUNCHA', 4208, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 3, 'EL REMANSO', 4208, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 4, 'ISLA VERDE', 4212, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 5, 'VILLA ATAMISQUI', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 6, 'BURRO POZO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 7, 'CARBON POZO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 8, 'CHILQUITAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 9, 'COLLERA HUIRCUNA', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 10, 'EL PERU', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 11, 'ESCALERA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 12, 'ESPERANZA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 13, 'HIGUERILLAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 14, 'HORNILLOS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 15, 'JUANILLO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 16, 'LOS SAUCES', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 17, 'PAMPALLAJTA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 18, 'PUEBLITO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 19, 'PUNTA POZO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 20, 'SALINAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 21, 'SAN GREGORIO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 22, 'SAUCEN', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 23, 'SAUCIOJ', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 24, 'VENTURA PAMPA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 25, 'ANCHANGA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 26, 'ARAGONES', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 27, 'ARBOL SOLO', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 28, 'CANCINOS', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 29, 'CANDELARIA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 30, 'CHUIQUI', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 31, 'COROPAMPA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 32, 'DIQUE LOS QUIROGA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 33, 'EL CARMEN', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 34, 'EL DEAN', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 35, 'HOYON', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 36, 'HUACHANA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 37, 'ISLA DE ARAGONES', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 38, 'KENTI TACO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 39, 'LA DARSENA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 40, 'LA ESQUINA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 41, 'LA PERLITA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 42, 'LEIVA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 43, 'LEZCANOS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 44, 'LOMITAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 45, 'LOS QUIROGA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 46, 'MANOGASTA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 47, 'MIRANDAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 48, 'POZO CERCADO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 49, 'POZO GRANDE', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 50, 'PUENTE DEL SALADO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 51, 'PUESTO DE DIAZ', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 52, 'RAMADITAS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 53, 'RODEO DE SORIA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 54, 'RODEO DE VALDEZ', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 55, 'SAN ANTONIO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 56, 'SAN ANTONIO DE LOS CACERES', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 57, 'SAN CARLOS', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 58, 'SAN DIONISIO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 59, 'SAN ISIDRO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 60, 'SAN MARTIN', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 61, 'SANTA MARIA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 62, 'SAUZAL', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 63, 'SIMBOL POZO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 64, 'SOL DE MAYO', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 65, 'TIPIRO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 66, 'NEGRA MUERTA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 67, 'PAAJ MUYO', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 68, 'PINEDA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 69, 'PUESTO DEL ROSARIO', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 70, 'ABRITA CHICA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 71, 'REMANSITO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 72, 'ABRITA GRANDE', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 73, 'ANCOCHA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 74, 'SAN LUIS', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 75, 'BAJADITA', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 76, 'SANTA ISABEL', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 77, 'BOQUERON', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 78, 'SOCONCHO', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 79, 'BUENA VISTA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 80, 'TACO POZO', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 81, 'CANEINOS', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 82, 'CHAUCHILLAS', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 83, 'CHILCA ALBARDON', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 84, 'CHILCAS LA LOMA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 85, 'CHILQUITA', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 86, 'TULUM', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 87, 'YACUCHIRI', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 88, 'CODO', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 89, 'CODO VIEJO', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 90, 'COLLERA HUIRI', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 91, 'KILOMETRO 436', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 92, 'EL DORADO', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 93, 'ESTACION ATAMISQUI', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 94, 'GUANACO SOMBRIANA', 4212, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 95, 'HUAJIA', 4318, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 96, 'KILOMETRO 437', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 97, 'LA NORIA', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 98, 'LA RESBALOSA', 5250, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 99, 'LOS ANGELES', 4315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 100, 'LOS MOLLARES', 4317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 3, 101, 'MEDELLIN', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 1, 'COLONIA DORA', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 2, 'HERRERA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 3, 'LUGONES', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 4, 'REAL SAYANA', 4335, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 5, 'COLONIA ISLA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 6, 'EL TRECE', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 7, 'LUJAN', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 8, 'MALLIN VIEJO', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 9, 'MOCONZA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 10, 'REPRESA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 11, 'RINCON DE LA ESPERANZA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 12, 'SALVIAIOJ GAITAN', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 13, 'SAN ANTONIO DE COPO', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 14, 'SAN PEDRO', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 15, 'SAN RAMON', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 16, 'TALA', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 17, 'LA COSTA', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 18, 'LAGO MUYOJ', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 19, 'MAL PASO', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 20, 'ORO PAMPA', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 21, 'POZO CABADO', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 22, 'TIESTITUYOS', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 23, 'TORO PAMPA', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 24, 'TRONCO BLANCO', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 25, 'YACASNIOJ', 4334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 26, 'CODO POZO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 27, 'CONCHAYOS', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 28, 'CRUZ POZO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 29, 'GUARDIA', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 30, 'NOVILLO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 31, 'PAAJ RODEO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 32, 'PUNTA POZO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 33, 'SAN ISIDRO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 34, 'SAN LUIS', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 35, 'SAN ROQUE', 4320, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 36, 'SANTO DOMINGO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 37, 'SAUCE BAJADA', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 38, 'ZAPI POZO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 39, 'SAN PEDRO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 40, 'SAN JOSE', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 41, 'AVE MARIA', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 42, 'BLANCA POZO', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 43, 'BRACHO', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 44, 'BREALOJ', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 45, 'CALOJ', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 46, 'CATORCE QUEBRACHOS', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 47, 'COLLUN LIOJ', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 48, 'LA ESMERALDA', 3766, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 49, 'LIBANESA', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 50, 'MAILIN', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 51, 'PASO GRANDE', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 52, 'PASO MOSOJ', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 53, 'PERCAS', 4324, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 54, 'POZO MARCADO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 55, 'PUENTE NEGRO', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 56, 'PUNTA CORRAL', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 57, 'SAN ANTONIO', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 58, 'SAN JOSE DE FLORES', 4324, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 59, 'SUNCHITUYOJ', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 60, 'TACO ATUN', 4328, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 4, 61, 'TACON ESQUINA', 4332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 1, 'ABRA GRANDE', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 2, 'ALTO POZO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 3, 'ANTAJE', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 4, 'ARDILES', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 5, 'ARDILES DE LA COSTA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 6, 'BARRIO ESTE', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 7, 'BEJAN', 4225, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 8, 'CHAUPI POZO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 9, 'CLODOMIRA', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 10, 'COLONIAS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 11, 'COLONIA MARIA LUISA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 12, 'CORVALANES', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 13, 'CUYOJ', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 14, 'EL AIBE', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 15, 'EL ALAMBRADO', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 16, 'EL BARRIAL', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 17, 'EL BOSQUE', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 18, 'EL CARMEN', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 19, 'EL CEBOLLIN', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 20, 'EL PARAISO', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 21, 'EL PUENTE', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 22, 'EL ROSARIO', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 23, 'KILOMETRO 661', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 24, 'KILOMETRO 665', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 25, 'KISKA HURMANA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 26, 'LA BANDA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 27, 'LA CUARTEADA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 28, 'LA FALDA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 29, 'LA GERMANIA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 30, 'LA ISLA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 31, 'LA VUELTA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 32, 'LAS COLONIAS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 33, 'LAS HERMANAS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 34, 'LOS ALDERETES', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 35, 'LOS DIAZ', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 36, 'LOS DOCE QUEBRACHOS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 37, 'LOS GALLARDOS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 38, 'LOS HERREROS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 39, 'LOS NARANJOS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 40, 'LOS PUESTOS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 41, 'LOS PUNTOS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 42, 'MEDIA FLOR', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 43, 'NUEVA ANTAJE', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 44, 'NUEVA TRINIDAD', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 45, 'PALERMO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 46, 'QUISHCA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 47, 'QUITA PUNCO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 48, 'RINCON', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 49, 'RUBIA MORENO', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 50, 'SAN CARLOS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 51, 'SAN JUAN', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 52, 'SAN LORENZO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 53, 'SAN MARTIN', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 54, 'SAN RAMON', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 55, 'SAN ROQUE', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 56, 'SANTA CRUZ', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 57, 'SANTA RITA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 58, 'SANTA ROSA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 59, 'SANTOS LUGARES', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 60, 'SIMBOLAR', 4340, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 61, 'SINQUEN PUNCO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 62, 'SURI POZO', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 63, 'TAPERAS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 64, 'TRAMO 16', 4301, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 65, 'VILLA UNION', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 66, 'BAJO GRANDE', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 67, 'BAYO MUERTO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 68, 'CONDOR HUASI', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 69, 'EL FAVORITO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 70, 'FAVORITA', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 71, 'KILOMETRO 629', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 72, 'LAGUNA LARGA', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 73, 'LAS CHACRAS', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 74, 'NEGRA MUERTA', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 75, 'PALMARES', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 76, 'PALMITAS', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 77, 'RUMIOS', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 78, 'SAN FELIPE', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 79, 'SAN FRANCISCO LAVALLE', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 80, 'SAN JAVIER', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 81, 'SANTA ROSA DE VITERVO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 82, 'SANTO DOMINGO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 83, 'AHI VEREMOS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 84, 'EL CRUCE KILOMETRO 659', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 85, 'JUMIALITO', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 86, 'KILOMETRO 1033', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 87, 'KILOMETRO 659', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 88, 'LA CAPILLA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 89, 'LA GRANJA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 90, 'CERRILLO', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 91, 'EL DIAMANTE', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 92, 'LOS HERRERAS', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 93, 'LOS MARCOS', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 94, 'SAN FELIX', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 95, 'SAN NICOLAS', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 96, 'SAN PEDRO', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 97, 'CHANCHILLOS', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 98, 'CHILQUITA I', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 99, 'CHUIQUI', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 100, 'CORO ABRA', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 101, 'COROPAMPA', 4201, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 102, 'EL OJO DE AGUA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 103, 'HUYAMAMPA', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 104, 'JUMI POZO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 105, 'KILOMETRO 645', 4339, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 106, 'KILOMETRO 651', 4339, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 107, 'LA AURORA', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 108, 'LA COLONIA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 109, 'LAS SALINAS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 110, 'LAS ZANJAS', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 111, 'LOMA NEGRA', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 112, 'LOS GUERREROS', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 113, 'MEDIA FLOR', 4302, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 114, 'PALOS QUEMADOS', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 115, 'PAMPA MAYO', 4336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 116, 'PUESTO LOS MARCOS', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 117, 'RUTA NACIONAL 34', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 118, 'RUTA PROVINCIAL 11', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 119, 'RUTA PROVINCIAL 130', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 120, 'RUTA PROVINCIAL 17', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 121, 'RUTA PROVINCIAL 40', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 122, 'RUTA PROVINCIAL 5', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 123, 'RUTA PROVINCIAL 8', 4326, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 124, 'SAN ISIDRO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 125, 'SAN NICOLAS', 4339, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 126, 'SAN PABLO', 4338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 127, 'SANTA ROSA', 4339, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 128, 'TRAMO 20', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 129, 'VALDIVIA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 5, 130, 'PARAJE LA BAJADA', 4300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 1, 'BANDERA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 2, 'FORTIN INCA', 3063, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 3, 'GUARDIA ESCOLTA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 4, 'COLONIA ALSINA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 5, 'CAMPO BELGRANO', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 6, 'DESVIO POZO DULCE', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 7, 'EL CRUCERO', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 8, 'EL JARDIN', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 9, 'EL ONCE', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 10, 'LA AIDA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 11, 'LA DELIA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 12, 'LA DORA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 13, 'LA FELICIANA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 14, 'LA ISLETA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 15, 'LA LIBIA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 16, 'LA MAGDALENA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 17, 'LA SANTAFECINA', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 18, 'LAS CHILCAS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 19, 'LAS ISLETAS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 20, 'LAS MOCHAS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 21, 'LAS TERESAS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 22, 'SAN GERMAN', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 23, 'DON PIETRO', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 24, 'EL AGRICULTOR', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 25, 'EL CANDELERO', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 26, 'EL SIMBOL', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 27, 'ISLA BAJA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 28, 'LA ALEMANA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 29, 'LA DOLORES', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 30, 'LA ESPERANZA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 31, 'LA EULALIA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 32, 'LA FRANCISCA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 33, 'LA HIEDRA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 34, 'LA HUERTA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 35, 'LA PAMPA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 36, 'LA PANCHITA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 37, 'LA ROSILLA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 38, 'LA SIMONA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 39, 'LA SUSANA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 40, 'LA TERESA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 41, 'LAS AGUADAS', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 42, 'LAS GAMAS', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 43, 'LOS PARAISOS', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 44, 'LOS TABLEROS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 45, 'NUEVA AURORA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 46, 'POZO DULCE', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 47, 'SANTA CATALINA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 48, 'SELVA BLANCA', 3064, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 6, 49, 'TRES LAGUNAS', 3062, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 1, 'ANTILO', 4225, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 2, 'EL BARRIAL', 4225, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 3, 'EL CHURQUI', 4225, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 4, 'LAS CEJAS', 4221, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 5, 'SANTIAGO DEL ESTERO', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 6, 'CONTRERAS ESTABLECIMIENTO', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 7, 'EL PUESTITO', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 8, 'EL VINALAR', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 9, 'MERCEDES', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 10, 'PUESTO DEL MEDIO', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 11, 'VILLA CONSTANTINA', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 12, 'VILLA GRIMANESA', 4200, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 13, 'MACO YANDA', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 14, 'MAGUITO', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 15, 'MAQUITA', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 16, 'MAQUITIS', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 17, 'NANDA', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 18, 'NAQUITO', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 19, 'PAMPA MUYOJ', 4203, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 20, 'POZO NUEVO', 5209, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 21, 'PUESTITO', 4313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 22, 'PUESTO NUEVO', 4203, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 23, 'QUEBRACHO HERRADO', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 24, 'REMES', 4203, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 25, 'SAN ISIDRO', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 26, 'SAN LORENZO', 4203, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 27, 'SAN PEDRO', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 28, 'SANTA MARIA', 4206, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 29, 'SANTA ROSA', 4205, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'G', 7, 30, 'SANTA ROSA ARRAGA', 4206, 0)
GO