
ALTER TABLE dbo.CLI_MAESTRO_FALLECIDOS ALTER COLUMN nombre VARCHAR (60)
GO

UPDATE dbo.DICCIONARIO
SET LARGO = 60
WHERE NUMERODECAMPO = 33201


UPDATE dbo.DICCIONARIO
SET LARGO = 30
WHERE NUMERODECAMPO = 33342


UPDATE dbo.DICCIONARIO
SET LARGO = 30
WHERE NUMERODECAMPO = 33344

