EXECUTE('

UPDATE dbo.DICCIONARIO
SET DESCRIPCION = ''Descripción''
	, PROMPT = ''Descripción''
WHERE NUMERODECAMPO = 37034


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (37045, '' '', 0, ''Cadena de actividades utilizadas'', ''actividades utilizadas'', 1000, ''A'', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL)


')
