
INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 21, 'EL RECOVECO', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 22, 'EL RECOVO', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 23, 'LAS CUCHILLAS', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 24, 'LAS PIEDRITAS', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 25, 'PAMPA BRUGNOLI', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 26, 'PAMPA DEL CIELO', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 27, 'PAMPA HERMOSA', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 28, 'PAMPA MITRE', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 29, 'PAMPA VILLORDO', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 30, 'PAMPA ZANATA', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 31, 'PAMPINI', 3722, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 4, 32, 'PUEBLO PUCA', 3732, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 1, 'AGUA BUENA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 2, 'BOTIJA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 3, 'CONCEPCION DEL BERMEJO', 3708, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 4, 'LORENA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 5, 'LOS FRENTONES', 3715, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 6, 'PAMPA BORRACHO', 3708, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 7, 'PAMPA DEL INFIERNO', 3721, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 8, 'PAMPA HERMOSA', 3708, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 9, 'PAMPA JUANITA', 3708, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 10, 'POZO HONDO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 11, 'RIO MUERTO', 3719, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 12, 'TACO POZO', 3713, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 13, 'KILOMETRO 1183', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 14, '9 DE JULIO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 15, 'CASTELLIN', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 16, 'COLOMBIA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 17, 'EL GUANACO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 18, 'EL INDIO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 19, 'EL PARAISO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 20, 'EL VALLA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 21, 'LA AGUADA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 22, 'LA ARGENTINA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 23, 'LA CHINA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 24, 'LA ILUSION', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 25, 'LA PALOMA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 26, 'LA PINTA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 27, 'LA PROVIDENCIA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 28, 'LA SARA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 29, 'LA TRANQUILIDAD', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 30, 'LAS CARPAS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 31, 'LAS DELICIAS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 32, 'LAS FLORES', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 33, 'LOS MAGOS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 34, 'LOS TIGRES', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 35, 'LOS TOBAS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 36, 'LOTE 33', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 37, 'MADRE DE DIOS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 38, 'NUEVA YORK', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 39, 'PALO BLANCO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 40, 'PAMPA BOLSA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 41, 'PAMPA CABURE', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 42, 'PAMPA EL FOSFORITO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 43, 'PAMPA EL MANGRULLO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 44, 'PAMPA EL MOLLAR', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 45, 'PAMPA PELADO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 46, 'PAMPA PEREYRA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 47, 'PAMPA QUIMILI', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 48, 'PAMPA RALERA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 49, 'PAMPA VIRGEN', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 50, 'PARAJE INDEPENDENCIA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 51, 'PARAJE KILOMETRO 77', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 52, 'PARAJE OJO DE AGUA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 53, 'PARAJE SANTA CRUZ', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 54, 'SAN AGUSTIN', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 55, 'SAN ANTONIO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 56, 'SAN JOSE', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 57, 'SAN LUIS', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 58, 'SAN MARTIN', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 59, 'SAN TELMO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 60, 'SANTA AGUEDA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 61, 'SANTA ELENA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 62, 'SANTA ROSA', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 63, 'SANTA TERESA DE CARBALLO', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 5, 64, 'URUNDEL', 3714, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 1, 'CABRAL CUE', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 2, 'CANCHA LARGA', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 3, 'COLONIA RIO DE ORO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 4, 'EL CAMPAMENTO', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 5, 'EL LAPACHO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 6, 'EL MIRASOL', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 7, 'EL RETIRO', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 8, 'FLORADORA', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 9, 'GANDOLFI', 3526, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 10, 'GENERAL VEDIA', 3520, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 11, 'GUAYCURU', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 12, 'ISLA DEL CERRITO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 13, 'KILOMETRO 76 RIO BERMEJO', 3526, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 14, 'LA LEONESA', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 15, 'LA MAGDALENA', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 16, 'LA POSTA', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 17, 'LA RINCONADA', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 18, 'LAGUNA PATOS', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 19, 'LAPACHO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 20, 'LAS PALMAS', 3523, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 21, 'LAS ROSAS', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 22, 'LOMA ALTA', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 23, 'MIERES', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 24, 'PUERTO BERMEJO', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 25, 'PUERTO LAS PALMAS', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 26, 'PUERTO EVA PERON', 3526, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 27, 'RANCHOS VIEJOS', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 28, 'RINCON DEL ZORRO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 29, 'RIO BERMEJO', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 30, 'RIO DE ORO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 31, 'SAN CARLOS', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 32, 'SAN EDUARDO', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 33, 'SAN FERNANDO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 34, 'SOLALINDE', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 35, 'TACUARI', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 36, 'TIMBO', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 37, 'TRES HORQUETAS', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 38, 'VELAZ', 3526, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 39, 'PUNTA DE RIELES', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 40, 'QUIA', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 41, 'COLONIA CABRAL', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 42, 'EL 14', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 43, 'EL PALMAR', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 44, 'LA ESPERANZA', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 45, 'LOTE 15 ESCUELA 268', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 46, 'LOTE 16 ESCUELA 204', 3522, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 47, 'LOTE 92 LA RINCONADA', 3524, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 48, 'PINDO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 49, 'TERMAS DEL CERRITO', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 6, 50, 'YATAY', 3518, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 1, 'CERRITO', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 2, 'COLONIA JUAN LARREA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 3, 'EL PUCA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 4, 'PAMPA BARRERA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 5, 'PUEBLO PUCA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 6, 'SANTA ELVIRA', 3731, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 7, 'TRES ESTACAS', 3727, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 8, 'CHARATA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 9, 'GENERAL NECOCHEA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 10, 'MESON DE FIERRO', 3729, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 11, 'PAMPA CABRERA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 12, 'PAMPA SOMMER', 3728, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 13, 'CABRAL', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 14, 'CAMPO FERRANDO', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 15, 'COLONIA BARRERA', 3732, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 16, 'COLONIA SCHMIDT', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 17, 'EL PICASO', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 18, 'INDIA MUERTA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 19, 'IPORA GUAZU', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 20, 'LOS GUALCOS', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 21, 'LOTE 77', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 22, 'PAMPA AVILA', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 23, 'PAMPA CEJAS', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 24, 'PAMPA DEL CIELO', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 7, 25, 'PAMPA FLORES', 3730, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 1, 'PRESIDENCIA ROQUE SAENZ PEҁ', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 2, 'COLONIA BERNARDINO RIVADAVIA', 3701, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 3, 'BARRIO GRAL JOSE DE SAN MARTIN', 3698, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 4, 'BARRIO SARMIENTO', 3699, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 5, 'COLONIA BAJO HONDO', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 6, 'GIRASOL', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 7, 'KILOMETRO 15', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 8, 'LAS CUCHILLAS CNIA J MARMOL', 3701, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 9, 'PAMPA AGUADO', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 10, 'PAMPA ALEGRIA', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 11, 'PAMPA DE LOS LOCOS', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 12, 'PAMPA FLORIDA', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 13, 'PAMPA GALPON', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 14, 'PAMPA LOCA', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 8, 15, 'PAMPA GAMBA', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 1, 'CABEZA DE TIGRE', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 2, 'KILOMETRO 596', 3504, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 3, 'SANTA MARIA', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 4, 'CAMPO EL JACARANDA', 3733, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 5, 'CHOROTIS', 3735, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 6, 'SANTA SYLVINA', 3542, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 7, 'ZUBERBUHLER', 3734, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 8, 'TRES MOJONES', 3733, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 9, 'TRES MONJES', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 10, 'VENADOS GRANDES', 3733, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 11, 'CAMPO LAS PUERTAS', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 12, 'CAMPO NUEVO', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 9, 13, 'COLONIA EL CURUPI', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 1, 'AMAMBAY', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 2, 'CORZUELA', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 3, 'LORO BLANCO', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 4, 'PAMPA ALSINA', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 5, 'PAMPA CUVALO', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 6, 'PAMPA GRANDE', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 10, 7, 'PUESTO CARRIZO', 3718, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 1, 'COLONIA JUAN PENCO', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 2, 'COLONIA MIXTA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 3, 'HIVONNAIT', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 4, 'KILOMETRO 29', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 5, 'KILOMETRO 34', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 6, 'KILOMETRO 38', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 7, 'KILOMETRO 5', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 8, 'LA ELABORADORA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 9, 'LAGUNA ESCONDIDA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 10, 'PUENTE PHILIPPON', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 11, 'PUENTE SVRITZ', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 12, 'EL OBRAJE', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 13, 'KILOMETRO 2 FCGB', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 14, 'KILOMETRO 22', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 15, 'LA ESCONDIDA', 3519, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 16, 'LA VERDE', 3527, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 17, 'LAPACHITO', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 18, 'MAKALLE', 3528, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 19, 'LOTE 48 COLONIA MIXTA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 11, 20, 'LOTE 53 COLONIA MIXTA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 1, 'LA LIBERTAD', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 2, 'JUAN JOSE CASTELLI', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 3, 'EL ESPINILLO', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 4, 'EL PINTADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 5, 'EL QUEBRACHAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 6, 'EL SAUZALITO', 3704, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 7, 'FORTIN LAVALLE', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 8, 'FUERTE ESPERANZA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 9, 'KILOMETRO 184', 3620, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 10, 'MANANTIALES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 11, 'MIRAFLORES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 12, 'MISION NUEVA POMPEYA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 13, 'NUEVA POBLACION', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 14, 'POZO DE LAS GARZAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 15, 'POZO NAVAGAN', 3621, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 16, 'VILLA RIO BERMEJITO', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 17, 'WICHI', 3702, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 18, 'PUERTO URQUIZA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 19, 'SAN ANTONIO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 20, 'BAJO HONDO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 21, 'BAJO VERDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 22, 'BERLIN', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 23, 'BOLSA GRANDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 24, 'CALIFORNIA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 25, 'CAMPO EL AIBAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 26, 'CAMPO EL ONZA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 27, 'CAMPO GRANDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 28, 'CAMPO OVEROS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 29, 'COLONIA CABEZA DE BUEY', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 30, 'COLONIA EL ALAZAN', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 31, 'COLONIA ESPERANZA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 32, 'COLONIA FORTUNI', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 33, 'COLONIA INDIGENA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 34, 'COLONIA JUAN JOSE CASTELLI', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 35, 'COLONIA LA FLORIDA CHICA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 36, 'COLONIA LA FLORIDA GRANDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 37, 'COLONIA MONTE QUEMADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 38, 'COLONIA SAN ANTONIO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 39, 'COMANDANCIA FRIAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 40, 'CORRALITO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 41, 'EL 15', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 42, 'EL AIBAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 43, 'EL ASUSTADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 44, 'EL DESIERTO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 45, 'EL RECREO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 46, 'EL SAUZAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 47, 'EL SIMBOLAR', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 48, 'EL VISCACHERAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 49, 'ESTANCIA LOMA ALTA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 50, 'EX FORTIN ZELAYA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 51, 'EX FORTIN ARENALES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 52, 'EX FORTIN COMANDANTE FRIAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 53, 'EX FORTIN LAVALLE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 54, 'EX FORTIN PEREZ MILLAN', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 55, 'EX FORTIN WILDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 56, 'EX FORTIN ZELAVA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 57, 'LA ARMONIA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 58, 'LA COSTOSA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 59, 'LA ENTRADA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 60, 'LA ESPERANZA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 61, 'LA ESTACION', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 62, 'LA FIDELIDAD', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 63, 'LA FLOJERA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 64, 'LA GRINGA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 65, 'LA INVERNADA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 66, 'LA MEDIA LUNA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 67, 'LA MORA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 68, 'LA RINCONADA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 69, 'LA SALTARINA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 70, 'LA SOLEDAD', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 71, 'LA ZANJA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 72, 'LAS BLANCAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 73, 'LAS FLORES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 74, 'LAS HACHERAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 75, 'LAS MARAVILLAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 76, 'LAS VERTIENTES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 77, 'LOS BARRILES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 78, 'LOS PORONGOS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 79, 'LOS QUIRQUINCHOS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 80, 'LOS TUNALES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 81, 'LOTE OCHO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 82, 'MIRAMAR', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 83, 'MISION ANGELICANA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 84, 'MOLLE MARCADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 85, 'MONTE CASEROS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 86, 'NUEVA UNION', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 87, 'PALO MARCADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 88, 'PAMPA CASTRO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 89, 'PAMPA EL SILENCIO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 90, 'PAMPA LOS BEDOGNI', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 91, 'PAMPA MACHETE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 92, 'PAMPA TOLOSA CHICA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 93, 'PAMPA TOLOSA GRANDE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 94, 'PARAJE EL COLCHON', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 95, 'PASO DE LOS LIBRES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 96, 'PARAJE EL COLORADO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 97, 'KILOMETRO 40', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 98, 'POZO DE LA LINEA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 99, 'POZO DE LA MULA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 100, 'POZO DE LA PAVA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 101, 'POZO DE LA TUNA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 102, 'POZO DE LOS SURIS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 103, 'POZO DEL CINCUENTA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 104, 'POZO DEL GATO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 105, 'POZO DEL GRIS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 106, 'POZO DEL MOLLE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 107, 'POZO DEL NEGRO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 108, 'POZO DEL TALA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 109, 'POZO DEL TIGRE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 110, 'POZO LA BREA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 111, 'POZO LA OSCA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 112, 'PUERTO LAVALLE', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 113, 'REDUCCION DE LA CANGAYE LUGAR', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 114, 'REDUCCION DE SAN BERNARDO EL V', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 115, 'ROSALES', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 116, 'SAN AGUSTIN', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 117, 'SAN JUANCITO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 118, 'SAN LORENZO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 119, 'SANTA RITA', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 120, 'SANTO DOMINGO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 121, 'SOL DE MAYO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 122, 'TARTAGAL', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 123, 'TOLDERIAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 124, 'TRES POZOS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 12, 125, 'POZO DEL TORO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 1, 'AVIA TERAI', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 2, 'CAMPO LARGO', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 3, 'CNIA AGRICOLA PAMPA NAPENAY', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 4, 'COLONIA JOSE MARMOL', 3700, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 5, 'COLONIA MALGRATTI', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 6, 'COLONIA MARIANO SARRATEA', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 7, 'EL CATORCE', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 8, 'LA MASCOTA', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 9, 'MALBALAES', 3701, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 10, 'NAPENAY', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 11, 'PAMPA DEL REGIMIENTO', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 12, 'PAMPA GRANDE', 3701, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 13, 'PAMPA OCULTA', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 14, 'LA CUCHILLA', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 15, 'LA FLECHA', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 16, 'LORO BLANCO', 3716, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 13, 17, 'LOTE 34', 3706, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 1, 'CAMPO EL BERMEJO', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 2, 'CAMPO WINTER', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 3, 'CIERVO PETISO', 3515, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 4, 'COLONIA CORONEL DORREGO', 3511, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 5, 'COLONIA SIETE ARBOLES', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 6, 'GENERAL JOSE DE SAN MARTIN', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 7, 'KILOMETRO 39', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 8, 'KILOMETRO 42', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 9, 'KILOMETRO 48', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 10, 'KILOMETRO 59', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 11, 'LAGUNA LIMPIA', 3515, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 12, 'LOS POZOS', 3511, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 13, 'PAMPA ALMIRON', 3507, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 14, 'PAMPA DEL INDIO', 3531, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 15, 'PRESIDENCIA ROCA', 3511, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 16, 'PUERTO ZAPALLAR', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 17, 'SANTOS LUGARES', 3531, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 18, 'SELVAS DEL RIO DE ORO', 3507, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 19, 'VENEZUELA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 20, '10 DE MAYO', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 21, 'LA EDUVIGES', 3648, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 22, 'COLONIA BERMEJO', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 23, 'COLONIA EL CIERVO', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 24, 'COLONIA EL FISCAL', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 25, 'COLONIA ESPERANZA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 26, 'COLONIA LA FILOMENA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 27, 'COLONIA SABINA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 28, 'COLONIA SAN ANTONIO', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 29, 'COLONIA TRES LAGUNAS', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 30, 'EL 15', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 31, 'EL PERDIDO', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 32, 'KILOMETRO 62', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 33, 'LOMA ALTA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 34, 'LOMA FLORIDA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 35, 'PAMPA CHICA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 36, 'PAMPA LARGA', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 37, 'PARAJE LAS TABLAS', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 38, 'VILLA DOS', 3509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 14, 39, 'ZAPARINQUI', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 1, 'CAMPO DE LA CHOZA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 2, 'CAMPO ECHEGARAY', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 3, 'COLONIA ECHEGARAY', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 4, 'COLONIA POPULAR', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 5, 'CORONEL AVALOS', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 6, 'FORTIN CARDOSO', 3513, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 7, 'GENERAL DONOVAN', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 8, 'GENERAL OBLIGADO', 3513, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 9, 'KILOMETRO 501', 3513, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 10, 'LA CHOZA', 3513, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 11, 'LAGUNA BELIGAY', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 12, 'LAGUNA BLANCA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 13, 'PUERTO BASTIANI', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 14, 'PUERTO TIROL', 3521, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 15, 'RIO ARAZA', 3514, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 16, 'VILLA JALON', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 17, 'LA EVANGELICA', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 18, 'COLONIA CODUTTI', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 19, 'COLONIA LUCINDA', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 20, 'KILOMETRO 523', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 21, 'LA LUCINDA', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 22, 'LA NEGRA', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 23, 'LA RAQUEL', 3505, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 15, 24, 'KILOMETRO 519', 3513, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 1, 'ALELOY', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 2, 'COLONIA VELEZ SARSFIELD', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 3, 'EL BOQUERON', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 4, 'EL PALMAR  TRES ISLETAS', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 5, 'LA POBLADORA', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 6, 'PAMPA AGUARA', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 7, 'PAMPA VARGAS', 3705, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 8, 'EL TREINTA Y SEIS', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 9, 'KILOMETRO 841', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 10, 'KILOMETRO 884', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 11, 'TRES ISLETAS', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 12, 'COLONIA ALELAY', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 13, 'EL DESTIERRO', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 14, 'KILOMETRO 855 ESTACION', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 15, 'LA MATANZA', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 16, 'PAMPA ALELAI', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 17, 'PAMPA EL 11', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 18, 'PAMPA EL 12', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 19, 'TRES NACIONES', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 16, 20, 'EL CUARENTA Y SEIS', 3703, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 1, 'AVANZADA', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 2, 'COLONIA EL TIGRE', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 3, 'COLONIA JUAN JOSE PASO', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 4, 'COLONIA MATHEU', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 5, 'CORONEL DU GRATY', 3541, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 6, 'EL ESQUINERO', 3543, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 7, 'EL PORVENIR', 3543, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 8, 'ENRIQUE URIEN', 3544, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 9, 'FORTIN POTRERO', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 10, 'LA NUEVA', 3540, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'H', 17, 11, 'LA OFELIA', 3540, 0)
GO
