
INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 13, 'COLONIA ARISTOBULO DEL VALLE', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 14, 'COLONIA GUARANI', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 15, 'COLONIA MARTIRES', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 16, 'COLONIA PROFUNDIDAD', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 17, 'LA INVERNADA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 18, 'LAS QUEMADAS', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 19, 'LORETO', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 20, 'LOTE 12', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 21, 'NACIENTES DEL ISABEL', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 22, 'PICADA FINLANDESA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 23, 'PICADA PORTUGUESA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 24, 'PICADA SAN JAVIER', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 25, 'PICADA SAN MARTIN', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 26, 'PROFUNDIDAD', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 27, 'PUERTO LA MINA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 28, 'RINCON DE BONPLAND', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 29, 'RUINAS DE LORETO', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 30, 'SANTA ANA', 3316, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 31, 'SOL DE MAYO', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 32, 'TACUARUZU', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 33, 'TEYUGUARE', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 34, 'TIMBAUBA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 35, 'TRATADO DE PAZ', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 36, 'VILLA VENECIA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 37, 'YABEBIRI', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 38, 'YACUTINGA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 39, 'YERBAL MAMBORETA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 40, 'LOTE 117', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 1, 'BARRIO DON SANTIAGO', 3312, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 2, 'DAMUS', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 3, 'DOMINGO BARTHE', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 4, 'FACHINAL', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 5, 'GARUPA', 3304, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 6, 'GARUPA NORTE', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 7, 'KILOMETRO 538', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 8, 'KILOMETRO 546', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 9, 'KILOMETRO 577', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 10, 'MANANTIALES', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 11, 'MIGUEL LANUS', 3310, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 12, 'NUEVA VALENCIA', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 13, 'PARADA LEIS', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 14, 'PUENTE NACIONAL', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 15, 'RINCON DE BUGRES', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 16, 'SAN ANDRES', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 17, 'SAN ISIDRO', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 18, 'SAN JUAN', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 19, 'SANTA INES', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 20, 'SIERRA DE SAN JOSE', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 21, 'TORORO', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 22, 'VILLA LANUS', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 23, 'VILLALONGA', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 24, 'ARROYO', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 25, 'DON HORACIO', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 26, 'EL REPOSO', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 27, 'EL TROPEZON', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 28, 'ESTANCIA ITAEMBRE', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 29, 'ITAEMBRE MINI', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 30, 'KILOMETRO 595', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 31, 'LA MILAGROSA', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 32, 'LAS VERTIENTES', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 33, 'PUERTO LUJAN', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 34, 'LA ROTONDA', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 35, 'VILLA EMILIA', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 5, 36, 'POSADAS', 3300, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 1, 'ARRECHEA', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 2, 'ARROYO PERSIGUERO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 3, 'ARROYO SANTA MARIA', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 4, 'BARRA CONCEPCION', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 5, 'BRETES MARTIRES', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 6, 'COLONIA CAPON BONITO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 7, 'COLONIA MARTIR SANTA MARIA', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 8, 'COLONIA SAN JAVIER', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 9, 'COLONIA SANTA MARIA', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 10, 'CONCEPCION DE LA SIERRA', 3371, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 11, 'EL PERSIGUERO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 12, 'OJO DE AGUA', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 13, 'PASO DEL ARROYO PERSIGUERO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 14, 'PERSIGUERO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 15, 'PUERTO CONCEPCION', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 16, 'PUERTO SAN LUCAS', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 17, 'SAN ISIDRO', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 18, 'SAN LUCAS', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 19, 'SANTA MARIA LA MAYOR', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 20, 'SANTA MARIA MARTIR', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 6, 21, 'ISLA SAN LUCAS', 3355, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 1, '9 DE JULIO KILOMETRO 20', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 2, 'COLONIA VICTORIA', 3388, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 3, 'ELDORADO', 3380, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 4, 'KILOMETRO 10', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 5, 'MARIA MAGDALENA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 6, 'PATI CUA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 7, 'PUERTO DELICIA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 8, 'PUERTO PINARES', 3389, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 9, 'PUERTO VICTORIA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 10, 'SANTIAGO DE LINIERS', 3387, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 11, 'VILLA ROULET', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 12, 'COLONIA CUNCI', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 13, 'COLONIA DELICIA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 14, 'COLONIA DURAN', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 15, 'PUERTO MADO', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 16, 'PUERTO PATICAA', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 7, 17, 'PUERTO EL DORADO', 3382, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 1, 'DOS HERMANAS', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 2, 'ALMIRANTE BROWN', 3385, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 3, 'BARRACON', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 4, 'BERNARDO DE IRIGOYEN', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 5, 'CABURE', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 6, 'COLONIA MANUEL BELGRANO', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 7, 'DESEADO', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 8, 'EL PORVENIR', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 9, 'INTEGRACION', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 10, 'SAN ANTONIO', 3383, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 11, 'PARAJE ESTELINA', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 12, 'PARAJE GRANADO', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 13, 'PARAJE INTERCONTINENTAL', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 14, 'CAMPO ALEGRE', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 15, 'COLONIA EL PESADO', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 16, 'COLONIA TRES MARIAS', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 17, 'PARAJE AZOPARDO', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 8, 18, 'PARAJE VILLA UNION', 3366, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 1, 'CAPITAN ANTONIO MORALES', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 2, 'COMANDANTE ANDRESITO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 3, 'EL SOBERBIO', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 4, 'FRACRAN', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 5, 'MONTEAGUDO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 6, 'SAN VICENTE', 3356, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 7, 'ALTA UNION', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 8, 'COLONIA CHAFARIZ', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 9, 'COLONIA PRIMAVERA', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 10, 'CRUCE LONDERO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 11, 'GUAIBICHU', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 12, 'LAS MERCEDES', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 13, 'MESA REDONDA', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 14, 'MIGUEL GUEMES', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 15, 'MOCONA', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 16, 'PUERTO PARAISO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 17, 'RIO YABOTAY', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 18, 'EL SOCORRO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 19, 'KILOMETRO 286', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 20, 'LUJAN', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 21, 'PARAISO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 22, 'LAS FLORES', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 23, '2 DE ABRIL', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 24, 'MARIANO MORENO', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 25, 'MANUEL BELGRANO', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 26, 'EL LAPACHO', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 27, 'PICADA MANDARINA', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 28, 'KM 18', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 29, 'LECHUZA', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 30, '17 DE AGOSTO', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 31, 'FRAY LUIS BELTRAN', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 32, 'VIRGEN DE LOURDES', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 9, 33, 'LA BONITA', 3338, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 1, 'CATARATAS DEL IGUAZU', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 2, 'PUERTO ESPERANZA', 3378, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 3, 'GOBERNADOR LANUSSE', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 4, 'LA PLANTADORA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 5, 'LIBERTAD', 3374, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 6, 'PUERTO AGUIRRE', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 7, 'PUERTO BEMBERG', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 8, 'PUERTO BOSSETTI', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 9, 'PUERTO CAROLINA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 10, 'PUERTO ERRECABORDE', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 11, 'PUERTO IGUAZU', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 12, 'PUERTO PENINSULA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 13, 'PUERTO URUGUAY', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 14, '22 DE DICIEMBRE', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 15, 'WANDA', 3376, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 16, 'PUERTO LIBERTAD', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 17, 'SEGUNDA ZONA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 18, 'PLANCHADA BANDERITA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 19, 'PUERTO CANOAS', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 20, 'PUERTO PAULITO', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 21, 'PUERTO YACUY', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 22, 'VILLA FLOR', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 23, 'PUERTO WANDA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 10, 24, 'TIRICA', 3370, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 1, 'ARROYO DEL MEDIO', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 2, 'ARROYO ISABEL', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 3, 'CAMPO TORNQUINST', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 4, 'CERRO AZUL', 3313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 5, 'COLONIA ALBERDI', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 6, 'COLONIA ALMAFUERTE', 3336, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 7, 'COLONIA CAAGUAZU', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 8, 'COLONIA FINLANDESA', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 9, 'COLONIA POLACA', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 10, 'DOS ARROYOS', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 11, 'EL CHATON', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 12, 'GRAL GUEMES', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 13, 'LEANDRO N ALEM', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 14, 'MECKING', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 15, 'OLEGARIO VICTOR ANDRADE', 3311, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 16, 'ONCE VUELTAS', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 17, 'PICADA BELGRANO', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 18, 'PICADA BONPLAND', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 19, 'PICADA GOBERNADOR LOPEZ', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 20, 'PICADA IGLESIA', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 21, 'PICADA LIBERTAD', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 22, 'PICADA POLACA', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 23, 'PICADA POZO FEO', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 24, 'PICADA RUSA', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 25, 'PICADA SAN JAVIER', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 26, 'PICADA SUR MECKING', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 27, 'VILLA LIBERTAD', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 28, 'COLONIA TARANCO', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 29, 'KILOMETRO 26', 3315, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 30, 'BELGRANO', 3313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 31, 'VILLA INTA', 3313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 11, 32, 'CAMPO SAN JUAN', 3313, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 1, 'CAPIOVY', 3332, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 2, 'CAPIVU', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 3, 'COLONIA LA OTILIA', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 4, 'COLONIA ORO VERDE', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 5, 'EL ALCAZAR', 3390, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 6, 'GARUHAPE', 3396, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 7, 'LINEA CUCHILLA', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 8, 'LOS TEALES', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 9, 'PUERTO INGENIERO MORANDI', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 10, 'PUERTO LEONI', 3333, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 11, 'PUERTO MBOPICUA', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 12, 'PUERTO MINERAL', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 13, 'PUERTO ORO VERDE', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 14, 'PUERTO PARANAY', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 15, 'PUERTO RICO', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 16, 'PUERTO SAN ALBERTO', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 17, 'PUERTO TIGRE', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 18, 'RUIZ DE MONTOYA', 3330, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 19, 'SAN ALBERTO', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 20, 'SAN GOTARDO', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 21, 'SAN MIGUEL', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 22, 'SAN SEBASTIAN', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 23, '3 DE MAYO', 3334, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 12, 24, 'MBOPICUA', 3331, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 1, 'BARRANCON', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 2, 'CARAGUATAY', 3372, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 3, 'GUARAYPO', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 4, 'ITA CURUZU', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 5, 'LARRAQUE', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 6, 'LINEA DE PERAY', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 7, 'MONTECARLO', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 8, 'PARANAY', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 9, 'PUERTO ALCAZAR', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 10, 'PUERTO AVELLANEDA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 11, 'PUERTO CARAGUATAY', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 12, 'PUERTO LAHARRAGUE', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 13, 'PUERTO PIRAY', 3381, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 14, 'TARUMA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 15, 'PIRAY', 3386, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 16, 'CITRUS', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 17, 'COLONIA SANTA TERESA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 18, 'ESTANCIA SANTA RITA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 19, 'KILOMETRO 34', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 20, 'KILOMETRO 60', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 21, 'LA MISIONERA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 22, 'LA POSTA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 23, 'MACACA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 24, 'MACACO', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 13, 25, 'VILLA OJO DE AGUA', 3384, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 14, 1, 'ARROYO FEDOR', 3360, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 14, 2, 'BARRA BONITA', 3360, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 14, 3, 'BAYO TRONCHO', 3360, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 14, 4, 'CAMPO RAMON', 3367, 0)
GO