INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (1, 'S', 'R', 32, 'H', 8, 1, 3700, 'H3700AAA', 'PELLEGRINI', 445, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (2, 'S', 'R', 32, 'H', 22, 4, 3545, 'H3545AAA', 'SAN MARTIN Y BELGRANO', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (3, 'S', 'R', 32, 'H', 17, 16, 3540, 'H3540AAA', '1RO. DE MAYO Y SAN MARTIN', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (4, 'S', 'R', 32, 'H', 16, 11, 3703, 'H3703AAA', 'AVDA. MITRE Y PARAGUAY', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (5, 'S', 'R', 32, 'H', 14, 6, 3509, 'H3509AAA', '12 DE OCTUBRE Y RIVADAVIA', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (6, 'S', 'R', 32, 'H', 2, 7, 3732, 'H3732AAA', 'GOB.DUCA Y ANGEL T. GONZALEZ', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (7, 'S', 'R', 32, 'H', 13, 2, 3716, 'H3716AAA', 'SAN MARTIN Y JUAN M. DE ROSAS', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (8, 'S', 'R', 32, 'H', 4, 8, 3722, 'H3722AAA', 'RIVADAVIA Y MERCANTE', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (9, 'S', 'R', 32, 'H', 9, 6, 3542, 'H3542AAA', 'FALCHINI Y SARMIENTO', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (10, 'S', 'R', 32, 'H', 5, 3, 3708, 'H3708AAA', 'AV SAN MARTIN', 244, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (11, 'S', 'R', 32, 'H', 23, 2, 3515, 'H3515AAA', 'AV. SAN MARTIN', 398, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (12, 'S', 'R', 32, 'H', 6, 14, 3518, 'H3518AAA', 'REMEDIO DE ESCALADA', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (13, 'S', 'R', 32, 'H', 5, 12, 3730, 'H3730AAA', 'Güemes', 101, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (14, 'S', 'R', 32, 'H', 20, 7, 3530, 'H3530AAA', 'SAN MARTIN', 448, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (15, 'S', 'R', 32, 'H', 21, 1, 3503, 'H3503AAA', 'AV. 9 DE JULIO', 4470, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (16, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Av. 25 de Mayo', 1460, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (17, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'AV. 9 DE JULIO', 1535, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (18, 'S', 'R', 32, 'H', 12, 2, 3705, 'H3705AAA', 'SARMIENTO Y DR.VAZQUEZ', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (19, 'S', 'R', 32, 'C', 1, 1, 1001, 'C1001AAA', 'SARMIENTO Y ESMERALDA', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (20, 'S', 'R', 32, 'H', 10, 2, 3718, 'H3718AAA', 'RIVADAVIA Y ESPAÃ±A', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (21, 'S', 'R', 32, 'H', 3, 7, 3535, 'H3535AAA', 'ANTONIO GALIZZI Y MAIPU', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (22, 'S', 'R', 32, 'H', 5, 12, 3713, 'H3713AAA', 'BELGRANO Y BROWN', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (23, 'S', 'R', 32, 'H', 2, 8, 3733, 'H3733AAA', 'PTE. PERON E ISLAS MALVINAS', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (24, 'S', 'R', 32, 'H', 14, 14, 3531, 'H3531AAA', 'SANTE FE Y BELGRANO', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (25, 'S', 'R', 32, 'H', 18, 4, 3726, 'H3726AAA', '25 DE MAYO Y SAN LORENZO', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (27, 'S', 'R', 32, 'H', 17, 5, 3541, 'H3541AAA', 'MARIANO MORENO PROLONGACION', 0, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (30, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (50, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (80, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (84, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (85, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (86, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (91, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (95, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (96, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (97, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 2, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (99, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO

INSERT INTO dbo.CLI_DIRECCIONES (ID, FORMATO, TIPODIRECCION, PAIS, PROVINCIA, DEPARTAMENTO, LOCALIDAD, CPA_VIEJO, CPA_NUEVO, CALLE, NUMERO, PISO, APARTAMENTO, BARRIO, MANZANA, PARCELA, CASA, MONOBLOCK, TIRA, CHACRA, OBSERVACIONES, FECHA_MODIFICACION, ESTADO, TZ_LOCK, NORMALIZADO, ORDINAL_DIR, PROVINCIA_EXTERIOR, DEPARTAMENTO_EXTERIOR, LOCALIDAD_EXTERIOR)
VALUES (99999, 'S', 'R', 32, 'H', 21, 3, 3500, 'H3500AAA', 'Güemes', 102, 0, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, 'A', 0, 'N', 0, NULL, NULL, NULL)
GO


--------------------------------------------------------------------------------------------
INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (1, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (2, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (3, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (4, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (5, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (6, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (7, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (8, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (9, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (10, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (11, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (12, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (13, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (14, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (15, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (16, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (17, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (18, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (19, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (20, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (21, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (22, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (23, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (24, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (25, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (27, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (30, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (50, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (80, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (84, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (85, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (86, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (91, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (95, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (96, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (97, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (99, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

INSERT INTO dbo.CLI_EMAILS (ID, FORMATO, TIPO, ORDINAL, EMAIL, TZ_LOCK)
VALUES (99999, 'S', 'LE', 1, 'ProteccionAUsuariosDeServiciosFinancieros@nbch.com.ar', 0)
GO

--------------------------------------------------------------------------------------------


INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (1, 'S', 'LE', 1, 'F', '+54-364-4426252', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (2, 'S', 'LE', 1, 'F', '+54-373-5497191', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (3, 'S', 'LE', 1, 'F', '+54-373-5430441', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (4, 'S', 'LE', 1, 'F', '+54-364-4461226', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (5, 'S', 'LE', 1, 'F', '+54-372-5420945', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (6, 'S', 'LE', 1, 'F', '+54-373-1480449', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (7, 'S', 'LE', 1, 'F', '+54-364-4495143', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (8, 'S', 'LE', 1, 'F', '+54-373-1460550', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (9, 'S', 'LE', 1, 'F', '+54-373-5492550', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (10, 'S', 'LE', 1, 'F', '+54-364-4497130', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (11, 'S', 'LE', 1, 'F', '+54-373-4491100', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (12, 'S', 'LE', 1, 'F', '+54-362-4470055', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (13, 'S', 'LE', 1, 'F', '+54-373-1426898', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (14, 'S', 'LE', 1, 'F', '+54-364-4480376', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (15, 'S', 'LE', 1, 'F', '+54-362-4482800', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (16, 'S', 'LE', 1, 'F', '+54-362-4463220', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (17, 'S', 'LE', 1, 'F', '+54-362-4447427', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (18, 'S', 'LE', 1, 'F', '+54-364-4471724', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (19, 'S', 'LE', 1, 'F', '+54-114-3257736', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (20, 'S', 'LE', 1, 'F', '+54-373-1470151', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (21, 'S', 'LE', 1, 'F', '+54-373-4470391', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (22, 'S', 'LE', 1, 'F', '+54-387-7495062', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (23, 'S', 'LE', 1, 'F', '+54-373-5495293', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (24, 'S', 'LE', 1, 'F', '+54-372-5494020', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (25, 'S', 'LE', 1, 'F', '+54-373-5496482', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (27, 'S', 'LE', 1, 'F', '+54-373-5430441', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (30, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (50, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (80, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (84, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (85, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (86, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (91, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (95, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (96, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (97, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (99, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO

INSERT INTO dbo.CLI_TELEFONOS (ID, FORMATO, TIPO, ORDINAL, TIPO_CEL_TEL, NUMERO, TZ_LOCK)
VALUES (99999, 'S', 'LE', 1, 'F', '+54-362-4580300', 0)
GO


--------------------------------------------------------------------------------

CREATE PROCEDURE dbo.SP_CONTROL_DIRECCIONES  
   @P_DATO NUMERIC (1),	
   @P_FORMATO VARCHAR (2),
   @P_TIPO VARCHAR (2), 	
   @P_NUMEROPERSONA NUMERIC(12),
   @P_RETURN NUMERIC(3)  OUTPUT
AS 
	BEGIN
	SET NOCOUNT ON;  
	SET @P_RETURN = NULL
				IF(@P_DATO = 1)
				BEGIN
				SET @P_RETURN =(
				      SELECT COUNT(*) FROM dbo.CLI_DIRECCIONES AS D
				      WHERE D.FORMATO= @P_FORMATO AND D.TIPODIRECCION = @P_TIPO AND D.ID = @P_NUMEROPERSONA AND D.TZ_LOCK BETWEEN 200000000000000 AND 300000000000000)
				END
				ELSE IF (@P_DATO = 3)
				BEGIN 
				SET @P_RETURN =(
				      SELECT COUNT(*) FROM dbo.CLI_TELEFONOS AS T
				      WHERE T.FORMATO= @P_FORMATO AND T.TIPO= @P_TIPO AND T.ID = @P_NUMEROPERSONA AND T.TZ_LOCK BETWEEN 200000000000000 AND 300000000000000)
			    END	
			    ELSE IF (@P_DATO = 2)
			    BEGIN
			    SET @P_RETURN =(
				      SELECT COUNT(*) FROM dbo.CLI_EMAILS AS E
				      WHERE E.FORMATO= @P_FORMATO AND E.TIPO= @P_TIPO AND E.ID = @P_NUMEROPERSONA AND E.TZ_LOCK BETWEEN 200000000000000 AND 300000000000000)  
				END
				 
   -- SET @P_RETURN = @@ROWCOUNT
	END
GO


