DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33072
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33073
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33074
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33075
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33076
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33080
GO


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33059
GO


-----------------------------------TELÉFONOS-----------------------------------

CREATE TABLE dbo.CLI_TELEFONOS
	(
	ID           NUMERIC (12) DEFAULT ((0)) NOT NULL,
	FORMATO      VARCHAR (2) DEFAULT (' ') NOT NULL,
	TIPO         VARCHAR (2) DEFAULT (' ') NOT NULL,
	ORDINAL      NUMERIC (3) DEFAULT ((0)) NOT NULL,
	TIPO_CEL_TEL VARCHAR (1) DEFAULT (' '),
	NUMERO       VARCHAR (17) DEFAULT (' '),
	TZ_LOCK      NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CLI_TELEFONOS_01 PRIMARY KEY (ID,FORMATO,TIPO,ORDINAL)
	)
GO

------DESCRIPTOR
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (10, 3341, NULL, 'Teléfonos', 0, 'CLI_TELEFONOS', 'D', NULL, NULL, 'Top/Clientes', NULL, 'N')
GO

-------INDICE
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3341, 33411, 'Indice 1', 0, 33422, 33426, 33427, 33433, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

------CAMPOS
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33422, ' ', 0, 'ID', 'ID', 12, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3341, 'ID', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33426, ' ', 0, 'FORMATO', 'FORMATO', 2, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3341, 'FORMATO', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33427, ' ', 0, 'TIPO', 'TIPO', 2, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3341, 'TIPO', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33433, ' ', 0, 'ORDINAL', 'ORDINAL', 3, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3341, 'ORDINAL', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33435, ' ', 0, 'TIPO_CEL_TEL', 'TIPO_CEL_TEL', 1, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3341, 'TIPO_CEL_TEL', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33441, ' ', 0, 'NUMERO', 'NUMERO', 17, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3341, 'NUMERO', 0, NULL)
GO

-------OPCIONES
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33435, 'E', 'Celular', 'C', 'C')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33435, 'E', 'Fijo', 'F', 'F')
GO
--------------

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33427, 'E', 'Especial', 'ES', 'ES')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33427, 'E', 'Exterior', 'EX', 'EX')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33427, 'E', 'Laboral', 'LA', 'LA')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33427, 'E', 'Legal', 'LE', 'LE')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33427, 'E', 'Personal', 'PE', 'PE')
GO
-------------


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33426, 'E', 'Persona Humana', 'PF', 'PF')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33426, 'E', 'Persona Jurídica', 'PJ', 'PJ')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33426, 'E', 'Sucursal', 'S', 'S')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33426, 'E', 'Juzgado', 'J', 'J')
GO
----------------------------------------------------------------------------------------
--------------------------CORREO ELECTRÓNICO--------------------------
CREATE TABLE dbo.CLI_EMAILS
	(
	ID      NUMERIC (12) DEFAULT ((0)) NOT NULL,
	FORMATO VARCHAR (2) DEFAULT (' ') NOT NULL,
	TIPO    VARCHAR (2) DEFAULT (' ') NOT NULL,
	ORDINAL NUMERIC (3) DEFAULT ((0)) NOT NULL,
	EMAIL   VARCHAR (250) DEFAULT (' '),
	TZ_LOCK NUMERIC (15) DEFAULT ((0)) NOT NULL,
	CONSTRAINT PK_CLI_EMAILS_01 PRIMARY KEY (ID,FORMATO,TIPO,ORDINAL)
	)
GO

------DESCRIPTOR
INSERT INTO dbo.DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, LARGODELREGISTRO, INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (10, 3342, NULL, 'Correos Electrónicos', 0, 'CLI_EMAILS', 'D', NULL, NULL, 'TOP/CLIENTES', NULL, 'N')
GO

-------INDICE
INSERT INTO dbo.INDICES (NUMERODEARCHIVO, NUMERODEINDICE, DESCRIPCION, CLAVESREPETIDAS, CAMPO1, CAMPO2, CAMPO3, CAMPO4, CAMPO5, CAMPO6, CAMPO7, CAMPO8, CAMPO9, CAMPO10, CAMPO11, CAMPO12, CAMPO13, CAMPO14, CAMPO15, CAMPO16, CAMPO17, CAMPO18, CAMPO19, CAMPO20)
VALUES (3342, 0, NULL, 0, 33458, 33460, 33494, 33495, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO


-------CAMPOS
INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33458, ' ', 0, 'ID', 'ID', 12, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3342, 'ID', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33460, ' ', 0, 'FORMATO', 'FORMATO', 2, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3342, 'FORMATO', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33494, ' ', 0, 'TIPO', 'TIPO', 2, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 1, 3342, 'TIPO', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33495, ' ', 0, 'ORDINAL', 'ORDINAL', 3, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3342, 'ORDINAL', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33496, ' ', 0, 'EMAIL', 'EMAIL', 250, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3342, 'EMAIL', 0, NULL)
GO

-------OPCIONES
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33494, 'E', 'Especial', 'ES', 'ES')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33494, 'E', 'Fiscal-Electrónico', 'FE', 'FE')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33494, 'E', 'Laboral', 'LA', 'LA')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33494, 'E', 'Legal', 'LE', 'LE')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33494, 'E', 'Personal', 'PE', 'PE')
GO

--------------

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33460, 'E', 'Persona Humana', 'PF', 'PF')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33460, 'E', 'Persona Jurídica', 'PJ', 'PJ')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33460, 'E', 'Sucursal', 'S', 'S')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33460, 'E', 'Juzgado', 'J', 'J')
GO
----------------------------------------------------------------------------------------



-------------------------------------------AJUSTES SOBRE DIRECCIONES
UPDATE dbo.INDICES
SET CAMPO4 = 33059
WHERE NUMERODEARCHIVO = 3302 AND NUMERODEINDICE = 1
GO

UPDATE dbo.AYUDAS
SET CAMPOS = '33007R;33008;33005R;33006R;33415;33004R;'
WHERE NUMERODEAYUDA = 33011
GO



TRUNCATE TABLE dbo.ITF_CORREO_ARGENTINO
GO

ALTER TABLE dbo.ITF_CORREO_ARGENTINO DROP CONSTRAINT DF__ITF_CORRE__NUMER__07A6BD00
GO


ALTER TABLE dbo.ITF_CORREO_ARGENTINO DROP COLUMN NUMERO
GO

ALTER TABLE dbo.ITF_CORREO_ARGENTINO ADD NUMERO_DESDE NUMERIC (8)
GO

ALTER TABLE dbo.ITF_CORREO_ARGENTINO ADD NUMERO_HASTA NUMERIC (8)
GO

TRUNCATE TABLE dbo.CLI_LOCALIDADES
GO

ALTER TABLE dbo.CLI_LOCALIDADES DROP CONSTRAINT PK_CLI_LOCALIDADES_01
GO

ALTER TABLE dbo.CLI_LOCALIDADES ALTER COLUMN DIM3 NUMERIC (3)  NOT NULL
GO


ALTER TABLE dbo.CLI_LOCALIDADES ADD  CODIGO_POSTAL NUMERIC (4) DEFAULT ((0)) NOT NULL
GO


ALTER TABLE dbo.CLI_LOCALIDADES ADD CONSTRAINT PK_CLI_LOCALIDADES_01 PRIMARY KEY (CODIGOPAIS,DIM1,DIM2,DIM3,CODIGO_POSTAL)
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP CONSTRAINT DF__CLI_DIREC__EMAIL__26B488AE
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN EMAIL1 
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP CONSTRAINT DF__CLI_DIREC__EMAIL__27A8ACE7
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN EMAIL2  
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN TELEFONO
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN TELEFONO_PREFERIDO
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN CELULAR
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN TIPO_MAIL_2
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP CONSTRAINT DF__CLI_DIREC__SCOD___1A4EB1C9
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP COLUMN SCOD_POSTAL 
GO

ALTER TABLE dbo.CLI_DIRECCIONES ADD ORDINAL_DIR NUMERIC (3) NOT NULL DEFAULT(0)
GO

ALTER TABLE dbo.CLI_DIRECCIONES DROP CONSTRAINT PK_CLI_DIRECCIONES_01
GO

ALTER TABLE dbo.CLI_DIRECCIONES ADD CONSTRAINT PK_CLI_DIRECCIONES_01 PRIMARY KEY (ID,FORMATO,TIPODIRECCION,ORDINAL_DIR) 
GO

ALTER TABLE dbo.CLI_DIRECCIONES ADD PROVINCIA_EXTERIOR VARCHAR (100) 
GO

ALTER TABLE dbo.CLI_DIRECCIONES ADD DEPARTAMENTO_EXTERIOR VARCHAR (100) 
GO

ALTER TABLE dbo.CLI_DIRECCIONES ADD LOCALIDAD_EXTERIOR VARCHAR (100) 
GO


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33415, ' ', 0, 'Código Postal', 'Código Postal', 4, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3301, 'CODIGO_POSTAL', 0, NULL)
GO


INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33059, ' ', 0, 'ORDINAL_DIR', 'ORDINAL_DIR', 3, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3302, 'ORDINAL_DIR', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33455, ' ', 0, 'Provincia Exterior', 'Provincia', 100, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3302, 'PROVINCIA_EXTERIOR', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33456, ' ', 0, 'Departamento Exterior', 'Departamento', 100, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3302, 'DEPARTAMENTO_EXTERIOR', 0, NULL)
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33457, ' ', 0, 'Localidad Exterior', 'Localidad', 100, 'A', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3302, 'LOCALIDAD_EXTERIOR', 0, NULL)
GO

--------------------OPCIONES TIPOS DE DIRECCIONES
--------------------PF

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Particular Real', 'PR', 'PR')
GO


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Particular Laboral', 'PL', 'PL')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Fiscal', 'F', 'F')
GO


INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Exterior Domicilio', 'ED', 'ED')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Legal', 'L', 'L')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33096, 'E', 'Especial', 'E', 'E')
GO

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 33096 AND IDIOMA = 'E' AND OPCIONINTERNA = 'AE'
GO
--------------------PJ

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33097, 'E', 'Especial', 'E', 'E')
GO

INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33097, 'E', 'Fiscal', 'F', 'F')
GO
INSERT INTO dbo.OPCIONES (NUMERODECAMPO, IDIOMA, DESCRIPCION, OPCIONINTERNA, OPCIONDEPANTALLA)
VALUES (33097, 'E', 'Exterior Domicilio', 'ED', 'ED')
GO


----------------

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 33051 AND IDIOMA = 'E' AND OPCIONINTERNA = 'CF'
GO

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 33051 AND IDIOMA = 'E' AND OPCIONINTERNA = 'CJ'
GO


DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 33051 AND IDIOMA = 'I' AND OPCIONINTERNA = 'CF'
GO

DELETE FROM dbo.OPCIONES
WHERE NUMERODECAMPO = 33051 AND IDIOMA = 'I' AND OPCIONINTERNA = 'CJ'
GO

--------------

DROP VIEW VW_DIRECCIONES_CPA
GO

CREATE VIEW dbo.VW_DIRECCIONES_CPA (
 ID_TICKET,
 FECHA_PROCESO,
 STATUS,
 PROVINCIA,
 CIUDAD,
 BARRIO,
 CODIGO_POSTAL,
 NUEVO_CODIGO_POSTAL,
 CALLE,
 NUMERO_DESDE,
 NUMERO_HASTA
 )
 AS 
	SELECT  C.ID_TICKET AS ID_TICKET,
		 	C.FECHA_PROCESO AS FECHA_PROCESO,
			C.STATUS AS STATUS,
			C.PROVINCIA AS PROVINCIA,
			C.CIUDAD AS CIUDAD,
			C.BARRIO AS BARRIO,
			C.CODIGO_POSTAL AS CODIGO_POSTAL,
			C.NUEVO_CODIGO_POSTAL AS NUEVO_CODIGO_POSTAL,
			C.CALLE AS CALLE,
			C.NUMERO_DESDE AS NUMERO_DESDE,
			C.NUMERO_HASTA AS NUMERO_HASTA
		 
	FROM dbo.ITF_CORREO_ARGENTINO AS C,
	 	 dbo.PARAMETROS AS F
	WHERE C.FECHA_PROCESO = F.FECHAPROCESO
	AND C.TZ_LOCK = 0
GO


UPDATE dbo.AYUDAS
SET CAMPOS ='20919I;537I;4968R;4990R;4991R;531R;722R;5010R;80R;48R;',
    CAMPOSVISTA = 'ID_TICKET;STATUS;PROVINCIA;CIUDAD;BARRIO;CODIGO_POSTAL;NUEVO_CODIGO_POSTAL;CALLE;NUMERO_DESDE;NUMERO_HASTA;'
WHERE NUMERODEAYUDA = 3300
GO


-----------------------BITACORAS


DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33925
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33938
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33939
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33940
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33941
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33942
GO

DELETE FROM dbo.DICCIONARIO
WHERE NUMERODECAMPO = 33946
GO


ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___SCOD___56E38A14
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN SCOD_POSTAL
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___EMAIL__634960F9
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN EMAIL1
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___EMAIL__643D8532
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN EMAIL2
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___TELEF__6531A96B
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN TELEFONO
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___TELEF__6625CDA4
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN TELEFONO_PREFERIDO
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___CELUL__6719F1DD
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN CELULAR
GO

ALTER TABLE dbo.BITACORA_DIRECCIONES DROP CONSTRAINT DF__BITACORA___TIPO___69F65E88
GO

ALTER TABLE BITACORA_DIRECCIONES DROP COLUMN TIPO_MAIL_2
GO

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, LARGO, TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (33925, ' ', 0, 'ORDINAL_DIR', 'Ordinal Dirección', 3, 'N', 0, NULL, 0, 0, 0, 0, 0, 0, 0, 3340, 'ORDINAL_DIR', 0, NULL)
GO

ALTER TABLE BITACORA_DIRECCIONES ADD ORDINAL_DIR NUMERIC (3,0)

