EXECUTE('CREATE VIEW V_BITACORA_DJ
AS
SELECT HM.NRO_CAUSA, 
       HM.FECHA, --56
       HM.ORDINAL, --9209
       O.DESCRIPCION, --4968
       HM.VALOR_ANTERIOR, --4990
       HM.VALOR_NUEVO --4991
FROM DJ_HISTORICO_MOD HM
JOIN OPCIONES O ON O.NUMERODECAMPO=33166 AND O.OPCIONINTERNA=HM.MOTIVO_MOD AND O.IDIOMA=''E''
WHERE HM.TZ_LOCK=0
');