
INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 1, 291, 'TRINIDAD', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 1, 292, 'TUNALITO', 4119, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 1, 293, 'TUSCA PAMPA', 4119, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 1, 294, 'VILLA LA COLMENA', 4103, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 1, 295, 'ZAPALLAR', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 1, 'ESTACION EXPERIMENTAL AGRICOLA', 4101, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 2, 'ESTACION SUPERIOR AGRICOLA', 4101, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 3, 'GOBERNADOR NOUGES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 4, 'KILOMETRO 792', 4105, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 5, 'NUEVOS MATADEROS', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 6, 'SAN MIGUEL DE TUCUMAN', 4000, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 7, 'VILLA ZENON SANTILLAN', 4000, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 8, 'KILOMETRO 180', 4000, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 2, 9, 'VILLA ANGELINA', 4105, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 1, 'ALPACHIRI', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 2, 'ALTO VERDE', 4153, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 3, 'ARCADIA', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 4, 'BAJO DE LOS SUELDOS', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 5, 'BARRIO BELGRANO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 6, 'BELICHA HUAICO', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 7, 'CARRETA QUEMADA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 8, 'COCHUNA', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 9, 'COLONIA FARA', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 10, 'COLONIA HUMAITA PRIMERA', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 11, 'COLONIA JUAN JOSE IRAMAIN', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 12, 'COLONIA PEDRO LEON CORNET', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 13, 'CONCEPCION', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 14, 'CORTADERAS', 4153, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 15, 'CUESTA DE CHILCA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 16, 'EL CEIBAL', 4153, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 17, 'EL MILAGRO', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 18, 'EL MISTOLAR', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 19, 'EL MOLINO', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 20, 'EL PORVENIR', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 21, 'EL POTRERILLO', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 22, 'EL POTRERO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 23, 'FINCA ENTRE RIOS', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 24, 'GASTONA', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 25, 'GASTONILLA', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 26, 'HUMAITA 1', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 27, 'HUMAITA 2', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 28, 'ILTICO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 29, 'INGENIO LA CORONA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 30, 'INGENIO LA TRINIDAD', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 31, 'JAYA', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 32, 'KILOMETRO 1185', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 33, 'KILOMETRO 66', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 34, 'LA CALERA', 4158, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 35, 'LA ESPERANZA', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 36, 'LA HIGUERA', 4122, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 37, 'LA TRINIDAD', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 38, 'LAGARTE', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 39, 'LAS ANIMAS', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 40, 'LAS FALDAS', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 41, 'LAS LEGUAS', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 42, 'LESCANO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 43, 'LOS GUCHEA', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 44, 'LOS TIMBRES', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 45, 'LOS VEGA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 46, 'MARIA LUISA', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 47, 'MEDINAS', 4167, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 48, 'MEMBRILLO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 49, 'MOLINOS', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 50, 'MONTE RICO', 4152, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 51, 'POSTA', 4157, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 52, 'RESCATE', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 53, 'RIO SECO KILOMETRO 1207', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 54, 'RODEO GRANDE', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 55, 'ROSARIO OESTE', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 56, 'SAN JOSE', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 57, 'SAN RAMON CHICLIGASTA', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 58, 'SUD DE SANDOVALES', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 59, 'SURIYACO', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 60, 'VILLA ALVEAR', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 61, 'VILLA CAROLINA', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 62, 'VILLA LA TRINIDAD', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 63, 'YUCUMANITA', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 64, 'ALTO LAS LECHUZAS', 4147, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 65, 'AROCAS', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 66, 'BARRIO TEXTIL', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 67, 'CALERA DE CHIRIMAYO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 68, 'CAMPO SOLCO LOS COCHAMOLLES', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 69, 'COCHAMOLLE', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 70, 'COSTA DEL RIO SECO', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 71, 'EL PUESTO', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 72, 'ENSENADA', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 73, 'ESCUELA 115', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 74, 'ESCUELA 168', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 75, 'ESCUELA 17', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 76, 'ESCUELA 18', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 77, 'ESCUELA 118', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 78, 'ESCUELA 186', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 79, 'ESCUELA 19', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 80, 'ESCUELA 234', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 81, 'ESCUELA 239', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 82, 'ESCUELA 268', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 83, 'ESCUELA 365', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 84, 'ESCUELA 387', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 85, 'ESCUELA 6', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 86, 'ESCUELA 65', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 87, 'ESCUELA 85', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 88, 'ESCUELA ALMIRANTE BROWN', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 89, 'ESCUELA FLORENCIO VARELA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 90, 'ESCUELA GREGORIA LAMADRID', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 91, 'ESCUELA MANUEL DOMINGO BASSAIL', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 92, 'ESCUELA MERCEDES PACHECO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 93, 'ISCHILLON', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 94, 'LA BANDERITA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 95, 'LAS CUEVAS', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 96, 'LAS GUCHAS LOS GUCHEA', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 97, 'LAS LENGUAS LAS LEGUAS', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 98, 'LAS PAVAS', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 99, 'LOS AGUEROS', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 100, 'LOS AGUIRRE', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 101, 'LOS LESCANOS', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 102, 'LOS TIMBOS', 4101, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 103, 'MUYO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 104, 'PIEDRA GRANDE', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 105, 'RIEGASTA', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 106, 'SAN ANTONIO', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 107, 'SAN CARLOS', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 108, 'SAN RAMON', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 109, 'SANTA ROSA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 110, 'VILLA DEVOTO', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 3, 111, 'YUNCA SUMA', 4146, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 1, 'AGUA DULCE', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 2, 'ALABAMA', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 3, 'ALDERETES', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 4, 'ARBOL SOLO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 5, 'BANDA DEL RIO SALI', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 6, 'BARRIO BELGRANO', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 7, 'BLANCO POZO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 8, 'BOCA DEL TIGRE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 9, 'CAMPO LA FLOR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 10, 'CARBON POZO', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 11, 'CAROLINAS BAJAS', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 12, 'CASA ROSADA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 13, 'CEVIL POZO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 14, 'COHIGAC', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 15, 'COLMENA LOLITA', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 16, 'COLOMBRES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 17, 'COLONIA LOLITA NORTE', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 18, 'CRUZ DEL NORTE ESTACION FCGM', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 19, 'DELFIN GALLO', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 20, 'EL BRACHO', 4112, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 21, 'EL CEVILAR COLOMBRES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 22, 'EL COCHUCHAL', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 23, 'EL NARANJITO', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 24, 'EL PARAISO', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 25, 'EL PUERTO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 26, 'EL PUESTO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 27, 'EL RINCON', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 28, 'EMPALME AGUA DULCE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 29, 'FAVORINA', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 30, 'FINCA ELISA', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 31, 'FINCA MAYO', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 32, 'LA FAVORITA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 33, 'LA FLOR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 34, 'LA FLORIDA', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 35, 'LA LIBERTAD', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 36, 'LA MARAVILLA', 4124, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 37, 'LA TALA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 38, 'LAPACHITOS', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 39, 'LAS CEJAS', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 40, 'LAS MERCEDES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 41, 'LAS PALOMITAS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 42, 'LAS PIEDRITAS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 43, 'LASTENIA', 4116, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 44, 'LOLITA', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 45, 'LOS GODOS', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 46, 'LOS GODOY', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 47, 'LOS GUTIERREZ', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 48, 'LOS HARDOY', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 49, 'LOS PEREYRA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 50, 'LOS PEREZ', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 51, 'LOS PORCELES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 52, 'LOS RALOS', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 53, 'LOS VALLISTOS', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 54, 'LOS VILLAGRA', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 55, 'LUISIANA ESTACION FCGM', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 56, 'LUJAN', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 57, 'MAYO', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 58, 'MONTE LARGO', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 59, 'MOYA', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 60, 'NUEVO PUEBLO LA FLORIDA', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 61, 'PACARA', 4003, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 62, 'PACARA PINTADO', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 63, 'PALMAS REDONDAS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 64, 'POLITO', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 65, 'POZO LAPACHO', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 66, 'PUENTE RIO SALI', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 67, 'RANCHILLOS', 4179, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 68, 'RANCHILLOS VIEJOS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 69, 'RETIRO', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 70, 'SAN AGUSTIN', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 71, 'SAN ANTONIO', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 72, 'SAN JOSE', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 73, 'SAN MIGUEL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 74, 'SAN MIGUELITO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 75, 'SAN PEDRO', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 76, 'SAN PEREYRA', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 77, 'SAN VICENTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 78, 'SANTA LUISA', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 79, 'SANTILLAN', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 80, 'VILLA TERCERA', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 81, 'GUANACO MUERTO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 82, 'GUZMAN ESTACION FCGB', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 83, 'INGENIO CONCEPCION', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 84, 'INGENIO CRUZ ALTA', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 85, 'INGENIO LA FLORIDA', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 86, 'INGENIO SAN JUAN', 4109, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 87, 'AGUADITA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 88, 'ALABAMA NUEVA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 89, 'ALTO LAS LECHUZAS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 90, 'ANDRES FERREYRA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 91, 'BAJO GRANDE', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 92, 'BELLO HORIZONTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 93, 'BRACHO VIEJO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 94, 'BUSTAMANTE', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 95, 'CAMPO LA FLOR LOS RALOS', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 96, 'CERCO CUATRO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 97, 'COLONIA EL PUESTO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 98, 'COLONIA EL TARCO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 99, 'COLONIA LA BONARIA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 100, 'COLONIA LA ORTIZ', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 101, 'COLONIA LA ROCA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 102, 'COLONIA MERCEDES', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 103, 'COLONIA MISTOL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 104, 'COLONIA MONTEROS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 105, 'COLONIA SAN LUIS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 106, 'COLONIA SAN MIGUEL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 107, 'COLONIA SANTA RITA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 108, 'CRUZ ALTA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 109, 'EL CARBON', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 110, 'EL CARDENAL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 111, 'EL CARMEN PUENTE ALTO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 112, 'EL CEVILAR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 113, 'EL CORTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 114, 'EL CRUCE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 115, 'EL CUADRO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 116, 'EL PAJAL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 117, 'EL PALOMAR', 4186, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 118, 'EL PRADO', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 119, 'EL TALAR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 120, 'ESCUELA BLAS PARERA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 121, 'ESCUELA 106', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 122, 'ESCUELA 108', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 123, 'ESCUELA 109', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 124, 'ESCUELA 110', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 125, 'ESCUELA 111', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 126, 'ESCUELA 12 DE OCTUBRE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 127, 'ESCUELA 141', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 128, 'ESCUELA 142', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 129, 'ESCUELA 220', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 130, 'ESCUELA 225', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 131, 'ESCUELA 228', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 132, 'ESCUELA 270', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 133, 'ESCUELA 277', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 134, 'ESCUELA 283', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 135, 'ESCUELA 284', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 136, 'ESCUELA 291', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 137, 'ESCUELA 3', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 138, 'ESCUELA 308', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 139, 'ESCUELA 312', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 140, 'ESCUELA 327', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 141, 'ESCUELA 329', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 142, 'ESCUELA 330', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 143, 'ESCUELA 334', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 144, 'ESCUELA 335', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 145, 'ESCUELA 56', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 146, 'ESCUELA 76', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 147, 'ESCUELA 86', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 148, 'ESCUELA 9', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 149, 'ESCUELA ALMAFUERTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 150, 'ESCUELA ARENALES', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 151, 'ESCUELA CORONEL ROCA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 152, 'ESCUELA E DE LUCAS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 153, 'ESCUELA G DE VEGA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 154, 'ESCUELA GUIDO SPANO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 155, 'ESCUELA INGENIERO BASCARY', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 156, 'ESCUELA JOSE COLOMBRES', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 157, 'ESCUELA JOSE POSSE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 158, 'ESCUELA JUANA MANSO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 159, 'ESCUELA N VERGARA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 160, 'ESCUELA R J FREYRE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 161, 'ESCUELA SANTIAGO GALLO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 162, 'ESCUELA SARGENTO CABRAL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 163, 'ESCUELA W POSSE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 164, 'FINCA EL CEIBO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 165, 'FINCA LEILA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 166, 'FINCA LOPEZ', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 167, 'FINCA SAN LUIS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 168, 'INGENIO ESPERANZA', 4187, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 169, 'INGENIO LOS RALOS', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 170, 'KILOMETRO 781', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 171, 'KILOMETRO 784', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 172, 'KILOMETRO 794', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 173, 'KILOMETRO 1270', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 174, 'KILOMETRO 34', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 175, 'KILOMETRO 771', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 176, 'LA CANTINA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 177, 'LA CORNELIA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 178, 'LA ERCILIA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 179, 'LA GUILLERMINA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 180, 'LA MEDIA AGUA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 181, 'LOLITA NUEVA', 4182, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 182, 'LOPEZ DOMINGUEZ', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 183, 'LOS BULACIOS', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 184, 'MARTA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 185, 'NARANJITO', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 186, 'OVERO POZO', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 187, 'P G MENDEZ', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 188, 'LUIS PASTEUR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 189, 'PEREYRA NORTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 190, 'PEREYRA SUR', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 191, 'POTRERO DE LOS ALAMOS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 192, 'POZO ALTO', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 193, 'POZO DEL ALTO', 4184, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 194, 'QUINTEROS 1', 4144, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 195, 'QUINTEROS 2', 4144, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 196, 'RAFAELA POZO', 4115, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 197, 'RUTA NACIONAL 9', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 198, 'RUTA PROVINCIAL 302', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 199, 'RUTA PROVINCIAL 303', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 200, 'RUTA PROVINCIAL 304', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 201, 'RUTA PROVINCIAL 306', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 202, 'RUTA PROVINCIAL 319', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 203, 'RUTA PROVINCIAL 335', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 204, 'SAN ANDRES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 205, 'SANTA RITA', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 206, 'SINQUIAL', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 207, 'TAMBOR DE TACUARI', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 4, 208, 'VA RECASTE', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 1, 'AGUA AZUL', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 2, 'ARROYO DE LA CRUZ', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 3, 'BUEN RETIRO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 4, 'CAMPO HERRERA', 4110, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 5, 'CARRICHANGO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 6, 'COLONIA EL SUNCHAL', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 7, 'COLONIA MARIA ELENA', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 8, 'COLONIA SANTA CLARA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 9, 'EL CARMEN', 4128, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 10, 'EL CEIBAL', 4105, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 11, 'EL CRUCE', 4138, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 12, 'EL MOYAR', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 13, 'EL OBRAJE', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 14, 'ENTRE RIOS', 4166, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 15, 'FAMAILLA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 16, 'FINCA PEREYRA', 4135, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 17, 'FINCA TULIO', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 18, 'INGENIO LULES', 4128, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 19, 'INVERNADA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 20, 'KILOMETRO 102', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 21, 'KILOMETRO 5', 4166, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 22, 'KILOMETRO 99', 4134, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 23, 'LA AGUADITA', 4101, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 24, 'LA BANDA', 4133, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 25, 'LA CAPILLA', 4128, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 26, 'LA FRONTERITA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 27, 'LA RINCONADA PARADA', 4107, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 28, 'LAS BANDERITAS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 29, 'LAS MORERAS', 4128, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 30, 'LAS TABLAS', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 31, 'LAURELES', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 32, 'MALVINAS', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 33, 'MANANTIAL DE OVANTA', 4105, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 34, 'MERCEDES', 4130, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 35, 'MONTE GRANDE', 4133, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 36, 'NUEVA BAVIERA', 4136, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 37, 'OBRAJE', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 38, 'PADILLA', 4133, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 39, 'POTRERO', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 40, 'PUERTAS GRANDES', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 41, 'PUNTA DEL MONTE', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 42, 'QUEBRADA DE LULES', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 43, 'RIO LULES', 4166, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 44, 'SAN FELIPE', 4166, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 45, 'SAN GABRIEL DEL MONTE', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 46, 'SAN JENARO', 4129, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 47, 'SAN JOSE DE BUENA VISTA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 48, 'SAN JOSE DE LULES', 4128, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 49, 'SAN LUIS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 50, 'SAUCE HUACHO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 51, 'TRES ALMACENES', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 52, 'AGUA BLANCA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 53, 'BARRANCAS COLORADAS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 54, 'CAMPO REDONDO', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 55, 'COLONIA ACEVEDO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 56, 'COLONIA BASCARY', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 57, 'COLONIA PACARA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 58, 'COLONIA SANTA LUCIA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 59, 'COLONIA SANTA RITA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 60, 'EL MATADERO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 61, 'EL TROPEZON', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 62, 'ESCUELA 100', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 63, 'ESCUELA 124', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 64, 'ESCUELA 154', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 65, 'ESCUELA 160', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 66, 'ESCUELA 197', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 67, 'ESCUELA 200', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 68, 'ESCUELA 206', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 69, 'ESCUELA 257', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 70, 'ESCUELA 261', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 71, 'ESCUELA 298', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 72, 'ESCUELA 321', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 73, 'ESCUELA 356', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 74, 'ESCUELA 373', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 75, 'ESCUELA 63', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 76, 'ESCUELA 88', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 77, 'ESCUELA CONGRESALES TUCUMANOS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 78, 'ESCUELA GUILLERMINA MOREIRA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 79, 'ESCUELA MONTE GRANDE', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 80, 'ESCUELA VELEZ SARSFIELD', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 81, 'ESQUINA NORTE', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 82, 'FINCA ARAOZ', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 83, 'INGENIO LA FRONTERITA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 84, 'KILOMETRO 1240', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 85, 'KILOMETRO 1244', 4168, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 86, 'KILOMETRO 108', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 87, 'LA AGUADA', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 88, 'LA PINTA Y LA CUARENTA', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 89, 'LAS RATAS', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 90, 'LAS TRES FLORES', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 91, 'LAURELES NORTE', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 92, 'LAURELES SUR', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 93, 'LOS SIFONES', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 94, 'RUTA NACIONAL 157', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 95, 'RUTA NACIONAL 38', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 96, 'RUTA PROVINCIAL 322', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 97, 'RUTA PROVINCIAL 334', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 98, 'RUTA PROVINCIAL 380', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 5, 99, 'SAUCE PARTIDO', 4132, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 1, '25 DE MAYO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 2, '9 DE JULIO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 3, 'ALONGO', 4161, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 4, 'AMUNPA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 5, 'ARBOLES GRANDES', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 6, 'BARRANCAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 7, 'BELTRAN', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 8, 'CAMPO GRANDE', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 9, 'CAMPO LA CRUZ', 4161, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 10, 'CASA VIEJA', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 11, 'CHALCHACITO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 12, 'CHILCA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 13, 'COCO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 14, 'DURAZNO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 15, 'EL PARAISO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 16, 'EL PUESTITO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 17, 'EL QUEBRACHITO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 18, 'EL SESTEADERO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 19, 'EL TOSTADO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 20, 'ENCRUCIJADA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 21, 'ESCOBAS', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 22, 'GRANEROS', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 23, 'KILOMETRO 19', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 24, 'LA CHILCA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 25, 'LA FLORIDA', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 26, 'LA GRAMA', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 27, 'LA IGUANA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 28, 'LA LAGUNILLA', 4163, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 29, 'LA TRINIDAD', 4151, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 30, 'LA ZANJA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 31, 'LACHICO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 32, 'LAMADRID', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 33, 'LAS BRISAS', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 34, 'LAS LOMITAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 35, 'LOS AGUDOS', 4157, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 36, 'LOS AGUIRRE', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 37, 'LOS CERCOS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 38, 'LOS DIAZ', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 39, 'LOS GONZALEZ', 4119, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 40, 'LOS GRAMAJOS', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 41, 'LOS PARAISOS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 42, 'LOS SAUCES', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 43, 'MISTOL', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 44, 'MONTUOSO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 45, 'MORON', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 46, 'PAEZ', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 47, 'PALO BLANCO', 4161, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 48, 'PALOMAS', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 49, 'PAMPA LARGA', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 50, 'POZO HONDO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 51, 'PUESTO 9 DE JULIO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 52, 'PUESTO LOS AVILAS', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 53, 'PUESTO LOS PEREZ', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 54, 'RAMADITAS', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 55, 'RAMOS', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 56, 'RETIRO', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 57, 'ROMERELLO', 4163, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 58, 'RUMI YURA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 59, 'SALA VIEJA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 60, 'SAN ANTONIO DE QUISCA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 61, 'SAN FRANCISCO', 4161, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 62, 'SAN GERMAN', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 63, 'SAN JUANCITO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 64, 'SAN MIGUEL', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 65, 'SANTA BARBARA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 66, 'SANTA CRUZ', 4149, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 67, 'SANTA ROSA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 68, 'SAUCE GAUCHO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 69, 'SAUCE SECO', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 70, 'SIMBOL', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 71, 'SOL DE MAYO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 72, 'TACO RALO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 73, 'TACO RODEO', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 74, 'TALA CAIDA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 75, 'TALITAS', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 76, 'TORO MUERTO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 77, 'TRES POZOS', 4178, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 78, 'VILTRAN', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 79, 'YAPACHIN', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 80, 'YMPAS', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 81, 'ZAPALLAR', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 82, 'ALTO DEL PUESTO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 83, 'ALTO VERDE', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 84, 'AMIMPA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 85, 'ANIMAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 86, 'ARBOLES VERDES', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 87, 'BARRANQUERAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 88, 'BARROSA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 89, 'CAJAS VIEJAS', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 90, 'CAMPO ALEGRE', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 91, 'CASA SANTA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 92, 'CONSIMO', 4174, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 93, 'DOS POZOS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 94, 'EL BARRANQUERO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 95, 'EL CAMPO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 96, 'EL ESPINAL', 4137, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 97, 'EL MISTOL', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 98, 'EL MOJON', 4117, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 99, 'EL NIAL', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 100, 'EL PALANCHO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 101, 'EL RODEO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 102, 'EL SAUZAL', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 103, 'EL VALLECITO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 104, 'EMBALSE RIO HONDO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 105, 'ESCUELA 151', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 106, 'ESCUELA 158', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 107, 'ESCUELA 172', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 108, 'ESCUELA 178', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 109, 'ESCUELA 179', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 110, 'ESCUELA 180', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 111, 'ESCUELA 182', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 112, 'ESCUELA 184', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 113, 'ESCUELA 187', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 114, 'ESCUELA 189', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 115, 'ESCUELA 191', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 116, 'ESCUELA 245', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 117, 'ESCUELA 302', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 118, 'ESCUELA 303', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 119, 'ESCUELA 306', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 120, 'ESCUELA 316', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 121, 'ESCUELA 343', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 122, 'ESCUELA 346', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 123, 'ESCUELA 72', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 124, 'ESCUELA 74', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 125, 'ESCUELA 75', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 126, 'ESCUELA 90', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 127, 'ESCUELA 92', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 128, 'ESCUELA 96', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 129, 'ESCUELA CAP DIEGO FCO PEREYRA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 130, 'ESCUELA CRISTOBAL COLON', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 131, 'ESCUELA 123', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 132, 'ESQUINA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 133, 'IGUANA', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 134, 'KILOMETRO 12', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 135, 'KM 12', 4159, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 136, 'LA BRAMA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 137, 'LA CONCEPCION', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 138, 'LA COSTA PALAMPA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 139, 'LA ESPERANZA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 140, 'LA ESTRELLA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 141, 'LA LOMA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 142, 'LA SOLEDAD', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 143, 'LAGUNA LARGA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 144, 'LAS PARRITAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 145, 'LAS ZANJITAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 146, 'LOS MISTOLES', 4162, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 147, 'LOS PANCHILLOS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 148, 'LOS RUIZ', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 149, 'LOS SARACHO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 150, 'LOS SORAIRE', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 151, 'LOS SOTELO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 152, 'LOS VAZQUEZ', 4105, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 153, 'MOLLES', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 154, 'PALO SECO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 155, 'PALOS QUEMADOS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 156, 'PAMPA MAYO', 4172, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 157, 'PAMPA MUYO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 158, 'PAMPA ROSA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 159, 'PASO DE LOS NIEVAS', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 160, 'PASO GRANDE', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 161, 'POZO EL QUEBRACHO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 162, 'POZO VERDE', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 163, 'PUEBLO NUEVO', 4164, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 164, 'PUESTO BELEN', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 165, 'PUESTO DE GALVANES', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 166, 'PUESTO DEL MEDIO', 4187, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 167, 'PUESTO LOS BARRAZA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 168, 'PUESTO LOS GALVEZ', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 169, 'PUESTO LOS ROBLES', 4142, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 170, 'RIO HONDITO', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 171, 'RUMI COCHA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 172, 'RUTA NACIONAL 157', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 173, 'RUTA PROVINCIAL 333', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 174, 'RUTA PROVINCIAL 334', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 175, 'SAN ANDRES', 4111, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 176, 'SANTA CLARA SUD', 4187, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 177, 'SESTEADERO', 4242, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 178, 'SUNCHO PUNTA', 4164, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 179, 'TALA SACHA', 4176, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'T', 6, 180, 'TOSTADO', 4242, 0)
GO