
INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 6, 'CHIVILCOY', 5571, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 7, 'COLONIA LAMBARE', 5653, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 8, 'COLONIA REINA', 5584, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 9, 'EL ALTO SALVADOR', 5654, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 10, 'EL CENTRAL', 5580, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 11, 'EL DIVISADERO', 5583, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 12, 'ESPINO', 5657, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 13, 'GURRUCHAGA', 5584, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 14, 'LA CHIMBA', 5589, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 15, 'LA PASTORAL', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 16, 'LAS COLONIAS', 5659, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 17, 'LOS OLMOS', 5571, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 18, 'MONTE CASEROS', 5671, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 19, 'PALMIRA', 5584, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 20, 'REINA', 5584, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 21, 'REYES', 5589, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 22, 'VILLA CENTENARIO', 5570, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 23, 'VILLA DEL CARMEN', 5570, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 24, 'CHIMBA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 25, 'LOS EUCALIPTOS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 26, 'ALTO VERDE', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 27, 'LIBERTADOR GRAL SAN MARTIN', 5570, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 28, 'NUEVA CALIFORNIA', 5543, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 29, 'RUTA 7 KILOMETRO 1014', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 30, 'ALBERTO FLORES', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 31, 'AZCURRA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 32, 'BALDE DE LA JARILLA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 33, 'BALDE DE LOS GAUCHOS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 34, 'BALDE JOFRE', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 35, 'BALDE LA PICHANA VIEJA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 36, 'BALDE LAS CARPAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 37, 'BALDE LAS CATITAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 38, 'BALDE SAN AGUSTIN', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 39, 'BALDE E AQUERA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 40, 'LOLA MORA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 41, 'COLONIA MONTE CASEROS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 42, 'EL PLUMERO', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 43, 'EL PUNTIAGUDO', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 44, 'FLORINDO FLORES', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 45, 'ISABEL FLORES', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 46, 'LA PICHANA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 47, 'LA VERDE', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 48, 'LAS TORRECITAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 49, 'LOS AHUMADOS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 50, 'LOS TORDILLOS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 51, 'MASA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 52, 'PUESTO LA FLORIDA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 53, 'PUESTO LAS JUNTITAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 54, 'PUESTO LAS PICHANAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 55, 'PUESTO LAS VIBORAS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 56, 'PUESTO LOS CAUSES', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 57, 'PUESTO LOS GAUCHOS', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 58, 'PUESTO SAN JOSE', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 59, 'PUESTO SAN MIGUEL', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 60, 'PUESTO SANTA MARIA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 61, 'PUESTO VEGA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 14, 62, 'TAPERA NEGRA', 5582, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 1, 'ARISTIDES VILLANUEVA', 5609, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 2, 'ATUEL SUD', 5623, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 3, 'BALDE EL SOSNEADO', 5611, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 4, 'CALLE LARGA VIEJA', 5605, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 5, 'CAPITAN MONTOYA', 5601, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 6, 'CERRO ALQUITRAN', 5611, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 7, 'COLONIA ATUEL NORTE', 5605, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 8, 'COLONIA BOMBAL Y TABANERA', 5607, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 9, 'COLONIA COLOMER', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 10, 'COLONIA ELENA', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 11, 'COLONIA JAUREGUI', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 12, 'COLONIA LOPEZ', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 13, 'COLONIA PASCUAL IACARINI', 5614, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 14, 'COLONIA RUSA', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 15, 'CUADRO BENEGAS', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 16, 'CUADRO BOMBAL', 5607, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 17, 'CUADRO NACIONAL', 5607, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 18, 'EL ALGARROBAL', 5607, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 19, 'EL BORBOLLON', 5666, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 20, 'EL CAMPAMENTO', 5609, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 21, 'EL CERRITO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 22, 'EL NIHUIL', 5636, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 23, 'EL PORVENIR', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 24, 'EL TROPEZON', 5629, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 25, 'EL USILLAL', 5601, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 26, 'FINCA LOPEZ', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 27, 'GOUDGE', 5631, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 28, 'GUADALES', 5609, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 29, 'IGUAZU', 5601, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 30, 'INGENIERO BALLOFFET', 5630, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 31, 'KILOMETRO 47', 5624, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 32, 'LA CHILCA', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 33, 'LA GUEVARINA', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 34, 'LA LLAVE', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 35, 'LA LLAVE VIEJA', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 36, 'LA PICHANA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 37, 'LA QUEBRADA', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 38, 'LA VASCONIA', 5623, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 39, 'LAS MALVINAS', 5635, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 40, 'LAS PAREDES', 5601, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 41, 'LOS BRITOS', 5611, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 42, 'LOS EMBARQUES', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 43, 'LOS HUARPES', 5634, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 44, 'LOS PARLAMENTOS', 5611, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 45, 'LOS PEJES', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 46, 'LOS REYUNOS', 5615, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 47, 'LOS TERNEROS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 48, 'MINAS DEL NEVADO', 5605, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 49, 'MONTE COMAN', 5609, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 50, 'PALERMO CHICO', 5625, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 51, 'PEDRO VARGAS', 5617, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 52, 'PIEDRA DE AFILAR', 5615, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 53, 'PUEBLO DIAMANTE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 54, 'PUEBLO ECHEVARRIETA', 5618, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 55, 'PUEBLO SOTO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 56, 'PUNTA DEL AGUA', 5627, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 57, 'RAMA CAIDA', 5619, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 58, 'REAL DEL PADRE', 5624, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 59, 'RESOLANA', 5611, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 60, 'RINCON DEL ATUEL', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 61, 'RODOLFO ISELIN', 5628, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 62, 'SALINAS EL DIAMANTE', 5605, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 63, 'SALTO DE LAS ROSAS', 5603, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 64, 'SAN RAFAEL', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 65, 'SANTA TERESA', 5640, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 66, 'SOITUE', 5623, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 67, 'TABANERA', 5607, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 68, '25 DE MAYO', 5615, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 69, 'VILLA ATUEL', 5622, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 70, 'AGUA NUEVA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 71, 'AGUA DE LA MULA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 72, 'CAJON DE MAYO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 73, 'CENTRAL HIDROELECTRICA 1', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 74, 'CENTRAL HIDROELECTRICA 2', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 75, 'COLONIA LA LLAVE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 76, 'COLONIA SOITUE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 77, 'COMISION NAC DE EMERGENCIA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 78, 'CUESTA DE LOS TERNEROS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 79, 'EL PICONA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 80, 'EL PLATEADO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 81, 'EMBALSE VALLE GRANDE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 82, 'ESTANCIA EL CAMPAMENTO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 83, 'ESTANCIA LA SARITA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 84, 'ESTANCIA LA TRINTRICA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 85, 'ESTANCIA LOS HUAICOS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 86, 'ESTANCIA LOS LEONES', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 87, 'ESTANCIA SOFIA RAQUEL', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 88, 'ESTANCIA TIERRAS BLANCAS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 89, 'LA LLAVE NUEVA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 90, 'LA PICASA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 91, 'MINAS EL SOSNEADO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 92, 'PTA DEL AGUA VIEJA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 93, 'PUESTA EL CAVADO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 94, 'PUESTO AGUA DE LA LIEBRE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 95, 'PUESTO AGUA DEL MEDANO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 96, 'PUESTO EL JILGUERO', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 97, 'PUESTO LAS PUNTANAS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 98, 'ALGARROBO DE SORTUE', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 99, 'LA CARUSINA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 100, 'LA JAULA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 101, 'LA PICARONA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 102, 'LA TOSCA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 103, 'LOS CLAVELES', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 104, 'LOS PATOS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 105, 'LOS PEJECITOS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 106, 'LOS REPUNTES', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 107, 'LOS TOLDITOS', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 108, 'COLONIA ATUEL', 5623, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 109, 'COM NAC DE ENERGIA ATOMICA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 110, 'CUPILES', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 111, 'EL ALGARROBO', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 112, 'EL VILTEGUINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 113, 'ESTANCIA LAS CHILCAS', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 114, 'LA LATA', 5600, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 115, 'LAGUNITA', 5527, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 116, 'NEGRO QUEMADO', 5623, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 15, 117, 'NIHUIL', 5605, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 1, '12 DE OCTUBRE', 5597, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 2, 'BALDE DE PIEDRA', 5596, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 3, 'CATITAS VIEJAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 4, 'COMANDANTE SALAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 5, 'EL COLORADO', 5592, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 6, 'EL RETIRO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 7, 'EL VILLEGUINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 8, 'GOBERNADOR CIVIT', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 9, 'LA COLONIA SUD', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 10, 'LA COSTA', 5596, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 11, 'LA DORMIDA', 5592, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 12, 'LAS CATITAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 13, 'PICHI CIEGO ESTACION FCGSM', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 14, 'RECOARO', 5596, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 15, 'SANTA ROSA', 5596, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 16, 'VILLA CATALA', 5596, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 17, 'ALTO CON ZAMPA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 18, 'ARANCIBIA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 19, 'ARANZABAL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 20, 'B DE ARAYA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 21, 'B DE QUEBRADO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 22, 'BAJO DEL YUYO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 23, 'BALDE LAS LAGUNITAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 24, 'BALDE NUEVO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 25, 'BANDERITA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 26, 'BELLE VILLE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 27, 'BORDE DE LA LINEA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 28, 'CASA DE ADOBE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 29, 'CHILOTE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 30, 'CLODOMIRO RETA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 31, 'COLONIA SAN JORGE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 32, 'CRISTOBAL LOPEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 33, 'D LOPEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 34, 'DIVISADERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 35, 'EL ALGARROBO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 36, 'EL BONITO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 37, 'EL CABAO VIEJO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 38, 'EL CARMEN', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 39, 'EL CHACALLAL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 40, 'EL CORBALNO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 41, 'EL DIVISADERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 42, 'EL ESCONDIDO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 43, 'EL GORGINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 44, 'EL GUANACO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 45, 'EL LEMINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 46, 'EL MARCADO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 47, 'EL MARUCHO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 48, 'EL MAURINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 49, 'EL MOLINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 50, 'EL PLUMERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 51, 'EL PORVENIR', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 52, 'EL RETAMOSO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 53, 'EL TAMARINDO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 54, 'EL VALLE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 55, 'EL ZAMPAL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 56, 'EL ZORZAL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 57, 'EMILIANO LUCERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 58, 'ERNESTO LOPEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 59, 'ESCUDERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 60, 'ESTANCIA GIL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 61, 'ESTANCIA EL BONITO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 62, 'FELIPE PEREZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 63, 'CRUZ GIMENEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 64, 'HUAICOS DE RUFINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 65, 'JARILLOSO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 66, 'JOFRE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 67, 'JOSE CAMPOS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 68, 'JOSE SOSA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 69, 'KILOMETRO 947', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 70, 'L DEL AGUERO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 71, 'L PEREZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 72, 'LA ANGELINA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 73, 'LA ARGENTINA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 74, 'LA CHUNA', 5595, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 75, 'LA CIENAGUITA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 76, 'LA CLARITA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 77, 'LA FLORIDA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 78, 'LA JACINTO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 79, 'LA LAGUNITA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 80, 'LA SOMBRILLA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 81, 'LAS ARABIAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 82, 'LAS GATITAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 83, 'LAS RAJADURAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 84, 'LAS VAYAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 85, 'LEZCANO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 86, 'LIRA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 87, 'LOMAS BLANCAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 88, 'LOMAS COLORADAS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 89, 'LOS MEDANOS NEGROS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 90, 'LOS MOROS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 91, 'LOS VERDES', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 92, 'LOS YOLES', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 93, 'EL LUQUINO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 94, 'MATURANA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 95, 'MELITON CAMPOS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 96, 'MIGUEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 97, 'MORON CHICO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 98, 'MORON VIEJO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 99, 'N ZAPATA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 100, 'NAVARRO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 101, 'P ROSALES', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 102, 'PONCE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 103, 'PUESTO EL TRUENO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 104, 'PUESTO GARCIA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 105, 'PUESTO LORCA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 106, 'PUESTO SAN VICENTE', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 107, 'PUNTA DEL CANAL', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 108, 'R BUSTOS', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 109, 'RODRIGUEZ', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 110, 'SAN PEDRO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 111, 'SANTA ANA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 112, 'SANTA MARIA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 113, 'SANTO DOMINGO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 114, 'T OROZCO', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 115, 'TALQUENCA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 116, 'URISA', 5594, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 117, 'EL CARBALINO', 5592, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 16, 118, 'LA BANDERA', 5592, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 1, 'ARROYO CLARO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 2, 'ARROYO LOS SAUCES', 5563, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 3, 'CAMPO DE LOS ANDES', 5565, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 4, 'COLONIA LAS ROSAS', 5662, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 5, 'COLONIA TABANERA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 6, 'ESTANCIA LA PAMPA', 5563, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 7, 'LA ESTACADA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 8, 'LA PRIMAVERA', 5565, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 9, 'LAS ROSAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 10, 'LAS TORRECITAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 11, 'LOS ARBOLES DE VILLEGAS', 5563, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 12, 'LOS SAUCES', 5663, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 13, 'LOS SAUCES LAVALLE', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 14, 'MELOCOTON', 5565, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 15, 'RUIZ HUIDOBRO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 16, 'SAN PABLO', 5563, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 17, 'TOTORAL', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 18, 'TUNUYAN', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 19, 'VILLA SECA DE TUNUYAN', 5563, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 20, 'VISTA FLORES', 5665, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 21, 'EL MANZANO HISTORICO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 22, 'DOCTOR ANTONIO SOOMAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 23, 'COLONIA DE LAS MULAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 24, 'COLONIA DEL DIABLO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 25, 'COLONIA FARO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 26, 'COLONIA LA ESCONDIDA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 27, 'COLONIA LA TORRECILLA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 28, 'COLONIA LOS OSCUROS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 29, 'COLONIA LOS TAPONES', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 30, 'DIQUE DEL VALLE DE UCO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 31, 'EL PORTILLO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 32, 'EL TOPON', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 33, 'EL TOSCAL', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 34, 'ESTANCIA MALLEA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 35, 'ESTANCIA AVEIRO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 36, 'ESTANCIA BELLA VISTA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 37, 'ESTANCIA CORREA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 38, 'ESTANCIA EL CARRIZALITO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 39, 'ESTANCIA GUINAZU', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 40, 'ESTANCIA LA ROSA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 41, 'ESTANCIA LAS HIGUERAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 42, 'ESTANCIA LOS CHACAYES', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 43, 'ESTANCIA SILVA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 44, 'LAS PINTADAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 45, 'LOMA CHATA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 46, 'LOS COMETIERRAS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 47, 'PASO LOS PALOS', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 48, 'PORTILLO DE PINQUENES', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 49, 'PORTILLO DEL DIABLO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 50, 'POTRERO SAN PABLO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 51, 'PUESTO EL MANZANO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 52, 'PUESTO LA TOSCA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 53, 'PUESTO MANZANITO', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 54, 'PUESTO MIRONDA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 17, 55, 'PUESTO SANTA MARIA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 1, 'ANCHORIS', 5509, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 2, 'ANCON', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 3, 'ARBOLEDA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 4, 'CORDON DE PLATA', 5661, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 5, 'EL PERAL', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 6, 'LA CARRERA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 7, 'SAN JOSE DE TUPUNGATO', 5667, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 8, 'TUPUNGATO', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 9, 'VILLA BASTIAS', 5562, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 10, 'ZAPATA', 5560, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 11, 'EL ZAMPAL', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 12, 'GUALTALLARY', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 13, 'LA ARBOLEDA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 14, 'PUESTO ALFARFA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 15, 'PUESTO LA JERILLA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'M', 18, 16, 'SANTA CLARA', 5561, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 1, '25 DE MAYO', 3379, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 2, 'ACARAGUA', 3361, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 3, 'ALBA POSSE', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 4, 'BARTOLITO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 5, 'COLONIA ALICIA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 6, 'COLONIA AURORA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 7, 'COLONIA EL DORADILLO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 8, 'COLONIA EL PROGRESO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 9, 'DESPLAYADA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 10, 'EL MACACO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 11, 'EL SALTITO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 12, 'MAI BAO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 13, 'PUERTO ALICIA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 14, 'PUERTO AURORA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 15, 'PUERTO INSUA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 16, 'PUERTO LONDERO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 17, 'PUERTO SAN MARTIN', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 18, 'SAN CARLOS', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 19, 'SAN FRANCISCO DE ASIS', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 20, 'SANTA RITA', 3377, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 21, 'TORTA QUEMADA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 22, 'TRES BOCAS', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 23, 'VILLA VILMA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 24, '9 DE JULIO', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 25, 'BARRA BONITA', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 26, 'CAMPOS SALLES', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 1, 27, 'FILEMON POSE', 3363, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 1, 'APOSTOLES', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 2, 'ARROYO TUNITAS', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 3, 'AZARA', 3351, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 4, 'CAMPO RICHARDSON', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 5, 'CARRILLO VIEJO', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 6, 'CENTINELA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 7, 'CHEROGUITA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 8, 'CHIRIMAY', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 9, 'COLONIA APOSTOLES', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 10, 'EL RANCHO', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 11, 'ENSANCHE ESTE', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 12, 'ENSANCHE NORTE', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 13, 'ESTACION APOSTOLES', 3359, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 14, 'LA CAPILLA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 15, 'LAS TUNAS', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 16, 'LOTE 117', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 17, 'MONTE HERMOSO', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 18, 'NACIENTES DEL TUNAR', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 19, 'PINDAPOY', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 20, 'RINCON DE CHIMTRAY', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 21, 'SAN JOSE', 3307, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 22, 'SAN JUAN DE LA SIERRA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 23, 'SIERRAS SAN JUAN', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 24, 'TIGRE', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 25, 'TRES CAPONES', 3354, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 26, 'VILLA ERRECABORDE', 3250, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 27, 'VILLA ORTIZ PEREIRA', 3250, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 28, 'COLONIA AZARA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 2, 29, 'PUERTO AZARA', 3350, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 1, 'ARISTOBULO DEL VALLE', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 2, 'BERNARDINO RIVADAVIA', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 3, 'CAINGUAS', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 4, 'CAMPO GRANDE', 3362, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 5, 'COLONIA SEGUI', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 6, 'DESTACAMENTO BOSQUES', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 7, '2 DE MAYO', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 8, 'EL TIGRE', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 9, 'FRONTERAS', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 10, 'KILOMETRO 17 RUTA 8', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 11, 'PARAJE LUCERO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 12, 'PINDAITI', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 13, 'PINDAYTI', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 14, '1 DE MAYO', 3364, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 15, 'SALTO ENCANTADO', 3339, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 16, 'ADOLFO J POMAR', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 17, 'FRIGO', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 18, 'MILAGRO', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 19, 'DORADITO', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 20, 'LOMA PORA', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 21, 'INDUMAR', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 22, 'INTEGRACION', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 23, 'JUAN DOMINGO PERON', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 24, 'SOL NACIENTE', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 25, 'CARRIL DE ANTA', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 26, 'CASCUDA', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 27, 'LAPACHO', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 28, 'KM1228', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 29, 'KM 1230', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 30, 'KM 1246', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 3, 31, 'KM 1247', 3337, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 1, 'ARROYO MAGDALENA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 2, 'ARROYO PASTORA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 3, 'ARROYO TOMAS', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 4, 'BELLA VISTA', 3309, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 5, 'BONPLAND', 3317, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 6, 'BONPLAND NORTE', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 7, 'BRAZO DEL TACUARUZU', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 8, 'CAAPORA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 9, 'CANDELARIA', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 10, 'CAPUERON', 3308, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 11, 'CERRO CORA', 3319, 0)
GO


INSERT INTO CLI_LOCALIDADES (CODIGOPAIS, DIM1, DIM2, DIM3, DESCRIPCION_DIM3, CODIGO_POSTAL, TZ_LOCK)
VALUES (32, 'N', 4, 12, 'COLONIA ALEMANA', 3308, 0)
GO
