
INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_GARANTIAS', 'DESCRIPCION', 'Calculo Afectacion Garantias', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_GARANTIAS', 'OPERACION', '11', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_GARANTIAS', 'CANAL', '0', 0);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO)
VALUES (8600 , 11 , 'Calculo Afectacion Garantias', 'Afec Gtias', 11, 'N', NULL, NULL, 'P', 0, NULL, 0, 'S', 'N', 'N', 'S', 'S');

INSERT INTO DESCRIPTORES (TITULO, IDENTIFICACION, TIPODEARCHIVO, DESCRIPCION, GRUPODELMAPA, NOMBREFISICO, TIPODEDBMS, [LARGODELREGISTRO], INICIALIZACIONDELREGISTRO, BASE, SELECCION, ACEPTA_MOVS_DIFERIDO)
VALUES (550, 4321, NULL, 'Historico Deuda Garantias', 0, 'CRE_HISTORICO_DEUDA_GARANTIAS', 'D', NULL, NULL, 'top/clientes', NULL, 'N');


CREATE TABLE CRE_HISTORICO_DEUDA_GARANTIAS
(
SALDO_JTS_OID               NUMERIC (10) DEFAULT ((0)) NOT NULL,
TIPO_ASISTENCIA             VARCHAR (1) DEFAULT (' ') NOT NULL,
FECHA_PROCESO	         	DATETIME NOT NULL,
NRO_GARANTIA                NUMERIC (6) DEFAULT ((0)) NOT NULL,
DEUDA_TOTAL                 NUMERIC (15,2) DEFAULT ((0)),
CAPITAL			            NUMERIC (15,2) DEFAULT ((0)),
INTERES			            NUMERIC (15,2) DEFAULT ((0)),
IVA_FINANCIADO 				NUMERIC (15,2) DEFAULT ((0)),
IVA_PERCEPCION_FINANCIADO	NUMERIC (15,2) DEFAULT ((0)),
ACCESORIOS					NUMERIC (15,2) DEFAULT ((0)),
MONTO_GARANTIZADO 			NUMERIC (15,2) DEFAULT ((0)),
MONTO_GARANTIZADO_MG 		NUMERIC (15,2) DEFAULT ((0)),
IMPORTE_CONTRACTUAL 		NUMERIC (15,2) DEFAULT ((0)),
TIPO_BCRA 					NUMERIC (1)	DEFAULT ((0)),
PORCENTAJE_AFECTACION 		NUMERIC (15,2) DEFAULT ((0)),
AFECTACION_GARANTIA 		NUMERIC (1)	DEFAULT ((0))
CONSTRAINT PK_CRE_HISTORICO_DEUDA_GARANTIAS PRIMARY KEY (SALDO_JTS_OID,TIPO_ASISTENCIA,FECHA_PROCESO,NRO_GARANTIA)
);

ALTER TABLE SALDOS ADD FECHA_SOBREGIRO DATE;

INSERT INTO dbo.DICCIONARIO (NUMERODECAMPO, USODELCAMPO, REFERENCIA, DESCRIPCION, PROMPT, [LARGO], TIPODECAMPO, DECIMALES, EDICION, CONTABILIZA, CONCEPTO, CALCULO, VALIDACION, TABLADEVALIDACION, TABLADEAYUDA, OPCIONES, TABLA, CAMPO, BASICO, MASCARA)
VALUES (1034, ' ', 0, 'Fecha Sobregiro', 'FchaSobreg', 8, 'F', 0, NULL, 0, 705, 0, 0, 0, 0, 0, 21, 'FECHA_SOBREGIRO', 0, NULL);

INSERT INTO CONCEPTOS ([CODIGO], DESCRIPCION, CAMPOV25)
VALUES (705, 'Fecha Sobregiro', 0);


DELETE PARAMETROS_JTS WHERE FUNCIONALIDAD = 'AFECTACION_PRESTAMOS_SIN_GARANTIAS';

INSERT INTO dbo.PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_PRESTAMOS_SIN_GARANTIAS', 'DESCRIPCION', 'Calculo Afectacion Prestamos sin Garantia', 0);

INSERT INTO dbo.PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_PRESTAMOS_SIN_GARANTIAS', 'OPERACION', '8', 0);

INSERT INTO dbo.PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('AFECTACION_PRESTAMOS_SIN_GARANTIAS', 'CANAL', '0', 0);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO)
VALUES (8600 , 8 , 'Calculo Afectacion sin Garantias', 'Pres Gtias', 8, 'N', NULL, NULL, 'P', 0, NULL, 0, 'S', 'N', 'N', 'S', 'S');


INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('BORRADO_TABLAS', 'DESCRIPCION', 'Borrado tablas', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('BORRADO_TABLAS', 'OPERACION', '12', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('BORRADO_TABLAS', 'CANAL', '0', 0);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO)
VALUES (8600 , 12 , 'Borrado tablas', 'Borr tablas', 12, 'N', NULL, NULL, 'P', 0, NULL, 0, 'S', 'N', 'N', 'S', 'S');


INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CONTABILIZACION_AFECTACION_GARANTIAS', 'DESCRIPCION', 'Contabilizacion Afectacion Garantias', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CONTABILIZACION_AFECTACION_GARANTIAS', 'OPERACION', '13', 0);

INSERT INTO PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
VALUES ('CONTABILIZACION_AFECTACION_GARANTIAS', 'CANAL', '0', 0);

INSERT INTO OPERACIONES (TITULO, IDENTIFICACION, NOMBRE, DESCRIPCION, MNEMOTECNICO, AUTORIZACION, FORMULARIOPRINCIPAL, PROXOPERACION, ESTADO, TZ_LOCK, COPIAS, SUBOPERACION, PERMITEBAJA, COMPORTAMIENTOENCIERRE, REQUIERECONTRASENA, PERMITECONCURRENTE, PERMITEESTADODIFERIDO)
VALUES (8600 , 13 , 'Contabilizacion Afectacion Garantias', 'ContAfecGtias', 13, 'N', NULL, NULL, 'P', 0, NULL, 0, 'S', 'N', 'N', 'S', 'S');




INSERT INTO BITACORA_HM (ACTUALIZACION,FECHA_APLICADO,TIPO_ACTUALIZACION,ESTADO,SCRIPT_SQL,SCRIPT_SQL_UNDO,ULT_SENTENCIA_OK)  VALUES ('20200714_1NBCH',NULL,'MANUAL','NO_DEFINIDO','CgoNCi0tIFBhdGNoX05VTkJDSEFDT18xNzAKDQotLSBJbnNlcnQgZGUgUEFSQU1FVFJPU19KVFMs
IE9QRVJBQ0lPTkVTIHkgREVTQ1JJUFRPUkVTDQpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pUUyAo
RlVOQ0lPTkFMSURBRCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQUZFQ1RB
Q0lPTl9HQVJBTlRJQVMnLCAnREVTQ1JJUENJT04nLCAnQ2FsY3VsbyBBZmVjdGFjaW9uIEdhcmFu
dGlhcycsIDApOwoKSU5TRVJUIElOVE8gUEFSQU1FVFJPU19KVFMgKEZVTkNJT05BTElEQUQsIFBB
UkFNRVRSTywgVkFMT1IsIFRaX0xPQ0spClZBTFVFUyAoJ0FGRUNUQUNJT05fR0FSQU5USUFTJywg
J09QRVJBQ0lPTicsICcxMScsIDApOwoKSU5TRVJUIElOVE8gUEFSQU1FVFJPU19KVFMgKEZVTkNJ
T05BTElEQUQsIFBBUkFNRVRSTywgVkFMT1IsIFRaX0xPQ0spClZBTFVFUyAoJ0FGRUNUQUNJT05f
R0FSQU5USUFTJywgJ0NBTkFMJywgJzAnLCAwKTsKCklOU0VSVCBJTlRPIE9QRVJBQ0lPTkVTIChU
SVRVTE8sIElERU5USUZJQ0FDSU9OLCBOT01CUkUsIERFU0NSSVBDSU9OLCBNTkVNT1RFQ05JQ08s
IEFVVE9SSVpBQ0lPTiwgRk9STVVMQVJJT1BSSU5DSVBBTCwgUFJPWE9QRVJBQ0lPTiwgRVNUQURP
LCBUWl9MT0NLLCBDT1BJQVMsIFNVQk9QRVJBQ0lPTiwgUEVSTUlURUJBSkEsIENPTVBPUlRBTUlF
TlRPRU5DSUVSUkUsIFJFUVVJRVJFQ09OVFJBU0VOQSwgUEVSTUlURUNPTkNVUlJFTlRFLCBQRVJN
SVRFRVNUQURPRElGRVJJRE8pClZBTFVFUyAoODYwMCAsIDExICwgJ0NhbGN1bG8gQWZlY3RhY2lv
biBHYXJhbnRpYXMnLCAnQWZlYyBHdGlhcycsIDExLCAnTicsIE5VTEwsIE5VTEwsICdQJywgMCwg
TlVMTCwgMCwgJ1MnLCAnTicsICdOJywgJ1MnLCAnUycpOwoKSU5TRVJUIElOVE8gREVTQ1JJUFRP
UkVTIChUSVRVTE8sIElERU5USUZJQ0FDSU9OLCBUSVBPREVBUkNISVZPLCBERVNDUklQQ0lPTiwg
R1JVUE9ERUxNQVBBLCBOT01CUkVGSVNJQ08sIFRJUE9ERURCTVMsIExBUkdPREVMUkVHSVNUUk8s
IElOSUNJQUxJWkFDSU9OREVMUkVHSVNUUk8sIEJBU0UsIFNFTEVDQ0lPTiwgQUNFUFRBX01PVlNf
RElGRVJJRE8pClZBTFVFUyAoNTUwLCA0MzIxLCBOVUxMLCAnSGlzdG9yaWNvIERldWRhIEdhcmFu
dGlhcycsIDAsICdDUkVfSElTVE9SSUNPX0RFVURBX0dBUkFOVElBUycsICdEJywgTlVMTCwgTlVM
TCwgJ3RvcC9jbGllbnRlcycsIE5VTEwsICdOJyk7Cg0KLS0gU1FMIC0gQ3JlYWNpb24gdGFibGEg
Q1JFX0hJU1RPUklDT19ERVVEQV9HQVJBTlRJQVMNCkNSRUFURSBUQUJMRSBDUkVfSElTVE9SSUNP
X0RFVURBX0dBUkFOVElBUwooClNBTERPX0pUU19PSUQgICAgICAgICAgICAgICBOVU1FUklDICgx
MCkgREVGQVVMVCAoKDApKSBOT1QgTlVMTCwKVElQT19BU0lTVEVOQ0lBICAgICAgICAgICAgIFZB
UkNIQVIgKDEpIERFRkFVTFQgKCcgJykgTk9UIE5VTEwsCkZFQ0hBX1BST0NFU08JICAgICAgICAg
CURBVEVUSU1FIE5PVCBOVUxMLApOUk9fR0FSQU5USUEgICAgICAgICAgICAgICAgTlVNRVJJQyAo
NikgREVGQVVMVCAoKDApKSBOT1QgTlVMTCwKREVVREFfVE9UQUwgICAgICAgICAgICAgICAgIE5V
TUVSSUMgKDE1LDIpIERFRkFVTFQgKCgwKSksCkNBUElUQUwJCQkgICAgICAgICAgICBOVU1FUklD
ICgxNSwyKSBERUZBVUxUICgoMCkpLApJTlRFUkVTCQkJICAgICAgICAgICAgTlVNRVJJQyAoMTUs
MikgREVGQVVMVCAoKDApKSwKSVZBX0ZJTkFOQ0lBRE8gCQkJCU5VTUVSSUMgKDE1LDIpIERFRkFV
TFQgKCgwKSksCklWQV9QRVJDRVBDSU9OX0ZJTkFOQ0lBRE8JTlVNRVJJQyAoMTUsMikgREVGQVVM
VCAoKDApKSwKQUNDRVNPUklPUwkJCQkJTlVNRVJJQyAoMTUsMikgREVGQVVMVCAoKDApKSwKTU9O
VE9fR0FSQU5USVpBRE8gCQkJTlVNRVJJQyAoMTUsMikgREVGQVVMVCAoKDApKSwKTU9OVE9fR0FS
QU5USVpBRE9fTUcgCQlOVU1FUklDICgxNSwyKSBERUZBVUxUICgoMCkpLApJTVBPUlRFX0NPTlRS
QUNUVUFMIAkJTlVNRVJJQyAoMTUsMikgREVGQVVMVCAoKDApKSwKVElQT19CQ1JBIAkJCQkJTlVN
RVJJQyAoMSkJREVGQVVMVCAoKDApKSwKUE9SQ0VOVEFKRV9BRkVDVEFDSU9OIAkJTlVNRVJJQyAo
MTUsMikgREVGQVVMVCAoKDApKSwKQUZFQ1RBQ0lPTl9HQVJBTlRJQSAJCU5VTUVSSUMgKDEpCURF
RkFVTFQgKCgwKSkKQ09OU1RSQUlOVCBQS19DUkVfSElTVE9SSUNPX0RFVURBX0dBUkFOVElBUyBQ
UklNQVJZIEtFWSAoU0FMRE9fSlRTX09JRCxUSVBPX0FTSVNURU5DSUEsRkVDSEFfUFJPQ0VTTyxO
Uk9fR0FSQU5USUEpCik7Cg0KQUxURVIgVEFCTEUgU0FMRE9TIEFERCBGRUNIQV9TT0JSRUdJUk8g
REFURTsKCklOU0VSVCBJTlRPIGRiby5ESUNDSU9OQVJJTyAoTlVNRVJPREVDQU1QTywgVVNPREVM
Q0FNUE8sIFJFRkVSRU5DSUEsIERFU0NSSVBDSU9OLCBQUk9NUFQsIExBUkdPLCBUSVBPREVDQU1Q
TywgREVDSU1BTEVTLCBFRElDSU9OLCBDT05UQUJJTElaQSwgQ09OQ0VQVE8sIENBTENVTE8sIFZB
TElEQUNJT04sIFRBQkxBREVWQUxJREFDSU9OLCBUQUJMQURFQVlVREEsIE9QQ0lPTkVTLCBUQUJM
QSwgQ0FNUE8sIEJBU0lDTywgTUFTQ0FSQSkKVkFMVUVTICgxMDM0LCAnICcsIDAsICdGZWNoYSBT
b2JyZWdpcm8nLCAnRmNoYVNvYnJlZycsIDgsICdGJywgMCwgTlVMTCwgMCwgNzA1LCAwLCAwLCAw
LCAwLCAwLCAyMSwgJ0ZFQ0hBX1NPQlJFR0lSTycsIDAsIE5VTEwpOwoKSU5TRVJUIElOVE8gQ09O
Q0VQVE9TIChDT0RJR08sIERFU0NSSVBDSU9OLCBDQU1QT1YyNSkKVkFMVUVTICg3MDUsICdGZWNo
YSBTb2JyZWdpcm8nLCAwKTsKDQotLSBQYXJjaGVfTlVOQkNIQUNPXzI4NwoNCi0tIERlcHVyYSBl
IEluc2VydGEgcmVnaXN0cm9zIGVuIFBBUkFNRVRST1NfSlRTDQpTZW50ZW5jaWEvcyBTUUwuCkRF
TEVURSBQQVJBTUVUUk9TX0pUUyBXSEVSRSBGVU5DSU9OQUxJREFEID0gJ0FGRUNUQUNJT05fUFJF
U1RBTU9TX1NJTl9HQVJBTlRJQVMnOwoKSU5TRVJUIElOVE8gZGJvLlBBUkFNRVRST1NfSlRTIChG
VU5DSU9OQUxJREFELCBQQVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdBRkVDVEFD
SU9OX1BSRVNUQU1PU19TSU5fR0FSQU5USUFTJywgJ0RFU0NSSVBDSU9OJywgJ0NhbGN1bG8gQWZl
Y3RhY2lvbiBQcmVzdGFtb3Mgc2luIEdhcmFudGlhJywgMCk7CgpJTlNFUlQgSU5UTyBkYm8uUEFS
QU1FVFJPU19KVFMgKEZVTkNJT05BTElEQUQsIFBBUkFNRVRSTywgVkFMT1IsIFRaX0xPQ0spClZB
TFVFUyAoJ0FGRUNUQUNJT05fUFJFU1RBTU9TX1NJTl9HQVJBTlRJQVMnLCAnT1BFUkFDSU9OJywg
JzgnLCAwKTsKCklOU0VSVCBJTlRPIGRiby5QQVJBTUVUUk9TX0pUUyAoRlVOQ0lPTkFMSURBRCwg
UEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQUZFQ1RBQ0lPTl9QUkVTVEFNT1Nf
U0lOX0dBUkFOVElBUycsICdDQU5BTCcsICcwJywgMCk7CgpJTlNFUlQgSU5UTyBPUEVSQUNJT05F
UyAoVElUVUxPLCBJREVOVElGSUNBQ0lPTiwgTk9NQlJFLCBERVNDUklQQ0lPTiwgTU5FTU9URUNO
SUNPLCBBVVRPUklaQUNJT04sIEZPUk1VTEFSSU9QUklOQ0lQQUwsIFBST1hPUEVSQUNJT04sIEVT
VEFETywgVFpfTE9DSywgQ09QSUFTLCBTVUJPUEVSQUNJT04sIFBFUk1JVEVCQUpBLCBDT01QT1JU
QU1JRU5UT0VOQ0lFUlJFLCBSRVFVSUVSRUNPTlRSQVNFTkEsIFBFUk1JVEVDT05DVVJSRU5URSwg
UEVSTUlURUVTVEFET0RJRkVSSURPKQpWQUxVRVMgKDg2MDAgLCA4ICwgJ0NhbGN1bG8gQWZlY3Rh
Y2lvbiBzaW4gR2FyYW50aWFzJywgJ1ByZXMgR3RpYXMnLCA4LCAnTicsIE5VTEwsIE5VTEwsICdQ
JywgMCwgTlVMTCwgMCwgJ1MnLCAnTicsICdOJywgJ1MnLCAnUycpOwoNCi0tIFBhdGNoX05VTkJD
SEFDT18yOTUKDQotLSBJbnNlcnQgZGUgUEFSQU1FVFJPU19KVFMgWSBPUEVSQUNJT05FUw0KSU5T
RVJUIElOVE8gUEFSQU1FVFJPU19KVFMgKEZVTkNJT05BTElEQUQsIFBBUkFNRVRSTywgVkFMT1Is
IFRaX0xPQ0spClZBTFVFUyAoJ0JPUlJBRE9fVEFCTEFTJywgJ0RFU0NSSVBDSU9OJywgJ0JvcnJh
ZG8gdGFibGFzJywgMCk7CgpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pUUyAoRlVOQ0lPTkFMSURB
RCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQk9SUkFET19UQUJMQVMnLCAn
T1BFUkFDSU9OJywgJzEyJywgMCk7CgpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pUUyAoRlVOQ0lP
TkFMSURBRCwgUEFSQU1FVFJPLCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQk9SUkFET19UQUJM
QVMnLCAnQ0FOQUwnLCAnMCcsIDApOwoKSU5TRVJUIElOVE8gT1BFUkFDSU9ORVMgKFRJVFVMTywg
SURFTlRJRklDQUNJT04sIE5PTUJSRSwgREVTQ1JJUENJT04sIE1ORU1PVEVDTklDTywgQVVUT1JJ
WkFDSU9OLCBGT1JNVUxBUklPUFJJTkNJUEFMLCBQUk9YT1BFUkFDSU9OLCBFU1RBRE8sIFRaX0xP
Q0ssIENPUElBUywgU1VCT1BFUkFDSU9OLCBQRVJNSVRFQkFKQSwgQ09NUE9SVEFNSUVOVE9FTkNJ
RVJSRSwgUkVRVUlFUkVDT05UUkFTRU5BLCBQRVJNSVRFQ09OQ1VSUkVOVEUsIFBFUk1JVEVFU1RB
RE9ESUZFUklETykKVkFMVUVTICg4NjAwICwgMTIgLCAnQm9ycmFkbyB0YWJsYXMnLCAnQm9yciB0
YWJsYXMnLCAxMiwgJ04nLCBOVUxMLCBOVUxMLCAnUCcsIDAsIE5VTEwsIDAsICdTJywgJ04nLCAn
TicsICdTJywgJ1MnKTsKDQotLSBQYXRjaF9OVU5CQ0hBQ09fMzAwCg0KLS0gSW5zZXJ0IGRlIFBB
UkFNRVRST1NfSlRTLCBPUEVSQUNJT05FUw0KSU5TRVJUIElOVE8gUEFSQU1FVFJPU19KVFMgKEZV
TkNJT05BTElEQUQsIFBBUkFNRVRSTywgVkFMT1IsIFRaX0xPQ0spClZBTFVFUyAoJ0NPTlRBQklM
SVpBQ0lPTl9BRkVDVEFDSU9OX0dBUkFOVElBUycsICdERVNDUklQQ0lPTicsICdDb250YWJpbGl6
YWNpb24gQWZlY3RhY2lvbiBHYXJhbnRpYXMnLCAwKTsKCklOU0VSVCBJTlRPIFBBUkFNRVRST1Nf
SlRTIChGVU5DSU9OQUxJREFELCBQQVJBTUVUUk8sIFZBTE9SLCBUWl9MT0NLKQpWQUxVRVMgKCdD
T05UQUJJTElaQUNJT05fQUZFQ1RBQ0lPTl9HQVJBTlRJQVMnLCAnT1BFUkFDSU9OJywgJzEzJywg
MCk7CgpJTlNFUlQgSU5UTyBQQVJBTUVUUk9TX0pUUyAoRlVOQ0lPTkFMSURBRCwgUEFSQU1FVFJP
LCBWQUxPUiwgVFpfTE9DSykKVkFMVUVTICgnQ09OVEFCSUxJWkFDSU9OX0FGRUNUQUNJT05fR0FS
QU5USUFTJywgJ0NBTkFMJywgJzAnLCAwKTsKCklOU0VSVCBJTlRPIE9QRVJBQ0lPTkVTIChUSVRV
TE8sIElERU5USUZJQ0FDSU9OLCBOT01CUkUsIERFU0NSSVBDSU9OLCBNTkVNT1RFQ05JQ08sIEFV
VE9SSVpBQ0lPTiwgRk9STVVMQVJJT1BSSU5DSVBBTCwgUFJPWE9QRVJBQ0lPTiwgRVNUQURPLCBU
Wl9MT0NLLCBDT1BJQVMsIFNVQk9QRVJBQ0lPTiwgUEVSTUlURUJBSkEsIENPTVBPUlRBTUlFTlRP
RU5DSUVSUkUsIFJFUVVJRVJFQ09OVFJBU0VOQSwgUEVSTUlURUNPTkNVUlJFTlRFLCBQRVJNSVRF
RVNUQURPRElGRVJJRE8pClZBTFVFUyAoODYwMCAsIDEzICwgJ0NvbnRhYmlsaXphY2lvbiBBZmVj
dGFjaW9uIEdhcmFudGlhcycsICdDb250QWZlY0d0aWFzJywgMTMsICdOJywgTlVMTCwgTlVMTCwg
J1AnLCAwLCBOVUxMLCAwLCAnUycsICdOJywgJ04nLCAnUycsICdTJyk7Cg0KCgoNCg==', NULL, 0);
